close #10110
unifyai/ivy pull request #10115
Opened 2023-01-26 13:58 UTC by rarisenpai

2023-01-26 14:25 UTC, rarisenpai commented
can someone please show why the linting tests are failing?

2023-01-26 18:44 UTC, aditya-hari commented
Hey! Thanks for the contribution. The linting test is failing because the newlines haven't been added appropriately, I have flagged them in the review.  In the future, use pre-commit to avoid these issues.

2023-01-26 18:48 UTC, rarisenpai commented
Hey thanks for you reply. I did setup precommit I don't know why its not registering probably because I changed in to a new codespace. I also tried adding tests for floordiv and test 1 started failing

2023-01-26 19:14 UTC, rarisenpai commented
I also did check the lint seems some of them are from parts of the code I didn't work on like some characters being too long in the backends

2023-01-26 19:38 UTC, rarisenpai commented
let me do this again

2023-01-26 19:49 UTC, aditya-hari commented
Thanks for the changes! Just need the tests now.

2023-01-27 08:20 UTC, rarisenpai commented
Okay will be working on the tests today

2023-01-30 16:45 UTC, rarisenpai commented
Hi I need some guidance I added the tests and all of this failed

2023-01-31 03:47 UTC, rarisenpai commented
hello

2023-01-31 07:18 UTC, aditya-hari approved these changes

2023-01-31 07:19 UTC, rarisenpai commented
okay will do that

2023-02-01 09:07 UTC, rarisenpai commented
Hello

2023-02-01 16:33 UTC, aditya-hari commented
Hey! Please go through the error log of test-frontend-numpy. It fails with "NameError: name 'pf' not defined".

2023-02-02 07:40 UTC, rarisenpai commented
Hi thanks let me fix that

2023-02-02 10:32 UTC, rarisenpai commented
Hey I just made the changes you highlighted in test-frontend-numpy and it's
still failing some tests. How should I proceed?


On Wed, Feb 1, 2023 at 7:33 PM Aditya Hari ***@***.***> wrote:

> Hey! Please go through the error log of test-frontend-numpy. It fails with
> "NameError: name 'pf' not defined".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unifyai/ivy/pull/10115#issuecomment-1412356088>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALENVCUR7JS7BBUO7TT2HWLWVKF5BANCNFSM6AAAAAAUHQ527E>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-02-02 16:01 UTC, rarisenpai commented
There are some tests failing

2023-02-03 12:46 UTC, rarisenpai commented
root@codespaces-116095:/workspaces/ivy# pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py::test_numpy_instance_floordiv__
Use Database in ReadOnly Mode with local caching !
======================================================================================================== test session starts ========================================================================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /workspaces/ivy
plugins: hypothesis-6.55.0, json-report-1.5.0, typeguard-2.13.3, metadata-2.0.4
collected 4 items                                                                                                                                                                                                                   

ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py ...F                                                                                                                                                [100%]

============================================================================================================= FAILURES ==============================================================================================================
___________________________________________________________________________ test_numpy_instance_floordiv__[cpu-ivy.functional.backends.torch-False-False] ___________________________________________________________________________

args = (ivy.array(-1.), ivy.array(-1.)), kwargs = {'out': None}

    @functools.wraps(fn)
    def new_fn(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
>           return fn(*args, **kwargs)

ivy/exceptions.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (ivy.array(-1.), ivy.array(-1.)), kwargs = {'out': None}, cont_fn = <function ContainerWithElementwise.static_floor_divide at 0x7f852b7c8e50>

    @functools.wraps(fn)
    def new_fn(*args, **kwargs):
        """
        Calls `fn` with the *nestable* property of the function correctly handled.
        This means mapping the function to the container leaves if any containers are
        passed in the input.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, with the nestable property handled correctly.
        """
        # if any of the arguments or keyword arguments passed to the function contains
        # a container, get the container's version of the function and call it using
        # the passed arguments.
        if hasattr(ivy.Container, "static_" + fn_name):
            cont_fn = getattr(ivy.Container, "static_" + fn_name)
        else:
            cont_fn = lambda *args, **kwargs: ivy.Container.cont_multi_map_in_function(
                fn, *args, **kwargs
            )
        if ivy.get_nestable_mode() and (
            ivy.nested_any(args, ivy.is_ivy_container, check_nests=True)
            or ivy.nested_any(kwargs, ivy.is_ivy_container, check_nests=True)
        ):
            return cont_fn(*args, **kwargs)
    
        # if the passed arguments does not contain a container, the function using
        # the passed arguments, returning an ivy or a native array.
>       return fn(*args, **kwargs)

ivy/func_wrapper.py:457: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

out = None, args = (ivy.array(-1.), ivy.array(-1.)), kwargs = {}

    @functools.wraps(fn)
    def new_fn(*args, out=None, **kwargs):
        """
        Calls `fn` with the `out` argument handled correctly for performing an inplace
        update.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        out
            The array to write the result to.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, with `out` handled correctly for
            inplace updates.
        """
        if out is None:
>           return fn(*args, **kwargs)

ivy/func_wrapper.py:384: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (ivy.array(-1.), ivy.array(-1.)), kwargs = {}, has_out = False, out = None, new_args = (tensor(-1., dtype=torch.float16), tensor(-1., dtype=torch.float16)), new_kwargs = {}

    @functools.wraps(fn)
    def new_fn(*args, **kwargs):
        """
        Converts all `ivy.Array` instances in both the positional and keyword arguments
        into `ivy.NativeArray` instances, and then calls the function with the updated
        arguments.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, with native arrays passed in the arguments.
        """
        if not ivy.get_array_mode():
            return fn(*args, **kwargs)
        # check if kwargs contains an out argument, and if so, remove it
        has_out = False
        out = None
        if "out" in kwargs:
            out = kwargs["out"]
            del kwargs["out"]
            has_out = True
        # convert all arrays in the inputs to ivy.NativeArray instances
        new_args, new_kwargs = ivy.args_to_native(*args, **kwargs)
        # add the original out argument back to the keyword arguments
        if has_out:
            new_kwargs["out"] = out
>       return fn(*new_args, **new_kwargs)

ivy/func_wrapper.py:126: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (tensor(-1., dtype=torch.float16), tensor(-1., dtype=torch.float16)), kwargs = {}

    @functools.wraps(fn)
    def new_fn(*args, **kwargs):
        """
        Calls the function, and then converts all `ivy.NativeArray` instances in
        the function return into `ivy.Array` instances.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, with native arrays as ivy arrays.
        """
        # call unmodified function
>       ret = fn(*args, **kwargs)

ivy/func_wrapper.py:188: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x1 = tensor(-1., dtype=torch.float16), x2 = tensor(-1., dtype=torch.float16)

    @with_unsupported_dtypes({"1.11.0 and below": ("float16", "complex")}, ba [...]

2023-02-03 12:48 UTC, rarisenpai commented
This is the error message I am getting after running the test_ndarray function for __floordiv__. Its passing 3 tests and failing one

2023-02-04 15:58 UTC, Daniel4078 commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +        return ivy.floor_divide(self._ivy_array,value)
small lint error here: ivy/functional/frontends/numpy/ndarray/ndarray.py:294:48: E231 missing whitespace after ','

2023-02-05 06:52 UTC, aditya-hari commented
Hey so besides the minor linting errors, here's what you need to for the tests -  
 
1. The assume statements about zero seem to deal with the zero division errors, so that should be clear. If you run into further problems though, then just explicitly generate non-zero denominators.  
2. E RuntimeError: "floor" "_vml_cpu" not implemented for 'Half' means that floor divide doesn't work for float16 in torch. Just disallow that data type, and any other ones that don't work

2023-02-05 06:54 UTC, aditya-hari requested changes
This should be np_frontend.floor_divide

2023-02-05 15:48 UTC, rarisenpai commented
hi made those changes

2023-02-05 15:52 UTC, rarisenpai commented
I also made the changes to the tests 
Kindly offer any other guidance in case I still need to make more changes

2023-02-06 14:00 UTC, aditya-hari commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +    # Make sure it's not dividing value too close to zero
Don't think the comments are necessary.

2023-02-06 15:06 UTC, aditya-hari commented
Looks good to me! Thanks for the contribution!

2023-02-06 15:09 UTC, merged