added row_stack pytorch frontend function
unifyai/ivy pull request #10155
Opened 2023-01-28 06:47 UTC by adhi1910

Close #10154

2023-02-01 16:10 UTC, guillesanbri requested changes
Hi! Thank you very much for the contribution! I have requested some changes, let me know if I can help with anything :slightly_smiling_face:

2023-02-02 19:08 UTC, guillesanbri requested changes
just some final changes :grin: btw, I think that the problem with the files in the idea folder is that the files didn't have a newline at the end of the file

2023-02-02 19:08 UTC, guillesanbri commented on ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py
> +        available_dtypes=helpers.get_dtypes("float"),
the test seems to work fine, but you should add `num_arrays=st.integers(1, 5),` here, as currently we are only passing one array and therefore not testing the function properly :slightly_smiling_face:

2023-02-03 16:28 UTC, adhi1910 commented
@guillesanbri I have added the requested changes and for the idea file new line(eof) has been added. But it still shows an error. Can you please look into it? and BTW sorry for more commits (all are reformating issues).

2023-02-03 18:20 UTC, merged

2023-02-03 18:23 UTC, guillesanbri commented
don't worry about the commits, it's squashed into one before merging so no problem haha. I have fixed the `.idea` files and merged your PR, thank you very much for the contribution!

P.S. I don't really know why the EOF thing was happening, but for future reference, it's best to just add and commit changes to the files that you have modified :slightly_smiling_face: