Ivy eye and logspace
unifyai/ivy pull request #1021
Opened 2022-05-02 22:28 UTC by SayanJerr

I have reverted the array test to as is in the current ivy version
for:
#945 
#963 
@djl11

2022-05-11 05:44 UTC, 1Doomdie1 requested changes
Please resolve the conflicts

2022-05-27 16:24 UTC, bicycleman15 commented on ivy/functional/ivy/linear_algebra.py
> +     >>> x = ivy.Container(a = ivy.array([[3., -1.], [-1., 3.]]) ,
you would need a `\` character at the end of the line for this to pass docstring tests

2022-05-27 16:24 UTC, bicycleman15 commented on ivy/functional/ivy/creation.py
> +    ivy.array([[1, 0],[0, 1]])
I think the examples are still not exhaustive. Please refer [here](https://lets-unify.ai/ivy/contributing/13_docstring_examples.html)

2022-05-27 16:24 UTC, bicycleman15 commented on ivy/functional/ivy/creation.py
>           device on which to place the created array.
Please update the docstring according to [this](https://lets-unify.ai/ivy/contributing/12_docstrings.html)

2022-05-27 16:24 UTC, bicycleman15 commented on ivy/functional/ivy/creation.py
> +    ivy.array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])
same thing as `eye`, not enough examples. Kindly refer to the contribution guidelines.

2022-05-27 16:25 UTC, bicycleman15 commented
I would suggest you to make a new PR perhaps, this one has become very messy and difficult to review. Let me know if you do make a new PR, I will then close this one 🙂

2022-06-07 14:05 UTC, juliagsy commented
Hey there! As the PR is inactive for more than 7 days, it will be closed in 24 hours if there are no further response. Thank you!

2022-06-08 06:37 UTC, juliagsy commented
Closing due to inactivity

2022-06-08 06:37 UTC, closed without merging