Adding cumsum_
unifyai/ivy pull request #10232
Opened 2023-02-01 08:19 UTC by soma2000-lang

#10231

2023-02-04 12:21 UTC, jkeane508 requested changes
Hello,

Thanks for submitting this PR,

It seems that the test is failing for this test, it needs to be passing before we can merge :)

Thanks,
James

2023-02-04 14:46 UTC, soma2000-lang commented
@jkeane508 the testa are failing due to files not modified by me.

2023-02-04 16:50 UTC, jkeane508 commented
> @jkeane508 the tests are failing due to files not modified by me.

Hey,

This [test](https://github.com/unifyai/ivy/actions/runs/4062507101/jobs/6993645160#step:3:260) indicates that the test in this PR is failing :)

But as far as lint errors go, yes I agree they are for different files not relevant to this PR, so no need to worry about them!

Happy Coding,
James

2023-02-04 17:23 UTC, soma2000-lang commented
@jkeane508  Can you check now.

2023-02-10 18:49 UTC, jkeane508 requested changes
Hey,

So looks like the test is failing due to the input dtype and output dtype not being the same in the tests. You can see that [here](https://github.com/unifyai/ivy/actions/runs/4108402481/jobs/7089053736)

Feel free to ask any questions :)

2023-02-11 17:58 UTC, soma2000-lang commented
@jkeane508  I think cumsum has been implemented wrong.Also I did a mistake of writing self.ivy_array instead of self._ivy_array.In pr #10487.I corrected that ,but then also the tests are failing.Please continue on  PR #10487.

2023-02-12 13:11 UTC, jkeane508 requested changes
The issue seems to be with your test actually, you're using two different dtypes in the generation which is why the test is failing.

2023-02-12 13:11 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +    dtype_value,
here you are generating a dtype

2023-02-12 13:11 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +    dtypes,
and also here

2023-02-14 21:45 UTC, soma2000-lang commented
@jkeane508 I have added the  changes in PR https://github.com/unifyai/ivy/pull/10487.But still the tests fail.

2023-02-17 08:44 UTC, closed without merging