Codespace jamalshah47 probable waddle p6j7q77wpwg369xq
unifyai/ivy pull request #10317
Opened 2023-02-05 18:45 UTC by JamalShah47

adding lp_normalize function for ivy expermental API

2023-02-06 17:43 UTC, JamalShah47 commented
Keep in mind that the tests failing related to assertion error are related to l2_normalize function not lp_normalize.

2023-02-07 13:23 UTC, fspyridakos requested changes
Hey thanks for your contribution! I left a few comments and I also took a look as to why l2_normalize was failing. Basically it seems numpy and jax return a different norm from tf and torch if axis=None and this can be fixed by flattening the array, check the changes to l2 normalize if you want to see what I mean. Also I would reccommend you install the pre-commit hook to fix some lint errors that are present, the guide to that is here:  [test_experimental/test_core/test_norms](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit)

2023-02-07 13:23 UTC, fspyridakos commented on ivy/functional/backends/numpy/experimental/norms.py
> +        return out
Here you can just use np.divide(x, denorm, out=out)

2023-02-07 13:23 UTC, fspyridakos commented on ivy/functional/ivy/experimental/norms.py
> +    >>> ivy.Lp_normalize(x, p=1, axis=1)
lowercase lp

2023-02-07 13:23 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_norms.py
> +    )
This tests already exists in test_experimental/test_core/test_norms, no need to copy it here

2023-02-07 13:23 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_norms.py
> +    )
Move this test to test_experimental/test_core/test_norms. Also generate a float for p instead of just passing 2.

2023-02-08 20:12 UTC, JamalShah47 commented
Hi, Thank you for explaining about the issue with l2_normalize function. I also encountered the same assertion error when the value of p was 1. I added the changes as you requested and set up precommit. I also made an additional change of changing the data type of p to int as the value p can only b 1 or 2 (as mentioned in the documentation)

2023-02-08 23:12 UTC, JamalShah47 commented
#10203

2023-02-09 11:22 UTC, fspyridakos commented on ivy/functional/ivy/experimental/norms.py
> +    p: int,
I don't see why p should be int, all frameworks seems to accept floats as long as they're >0

2023-02-09 11:25 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_norms.py
> +        atol_=1e-1,
You can probably remove the tolerance

2023-02-09 11:26 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_norms.py
> +    p=st.integers(min_value=1, max_value=2),
Also change this to generate floats >0

2023-02-09 13:38 UTC, JamalShah47 commented on ivy/functional/backends/tensorflow/experimental/norms.py
> +    return tf.math.divide(x, denorm)
i tried to add tf.linalg.normalize and the test for tensorflow backend was sucessfull however, the tests for numpy,torch and jax failed with the following assertion error
Failed: [undefined]AssertionError: len(ret_np_flat) != len(ret_np_from_gt_flat):

ret_np_flat:

[array([-1.], dtype=float32)]

ret_np_from_gt_flat:

2023-02-09 14:17 UTC, JamalShah47 commented
Hi @fspyridakos I added the changes you requested except the tf.linalg.normalize() as I mentioned in your reply, a few tests are failing due to the p value being less than 1 which is leading to an assertion error after changing the data type of p from float to int. I used int for p by referencing the following documentation.
https://onnx.ai/onnx/operators/onnx__LpNormalization.html

2023-02-09 14:53 UTC, fspyridakos requested changes
Great work again, can you just add p = 2 for the array, container and ivy functions. Thanks!

2023-02-09 14:53 UTC, fspyridakos commented on ivy/functional/ivy/experimental/norms.py
> +    p: float,
p: float = 2,

2023-02-09 15:54 UTC, fspyridakos commented
Can you actually add back the tolerance in the test, it seems to be failing due to slight differences as calculated by tf

2023-02-09 16:14 UTC, JamalShah47 commented
> Can you actually add back the tolerance in the test, it seems to be failing due to slight differences as calculated by tf

Done. Let me know if anymore changes are needed.

2023-02-09 16:26 UTC, merged