unique_all
unifyai/ivy pull request #1032
Opened 2022-05-04 13:06 UTC by Archymade

2022-05-12 19:35 UTC, sherry30 commented
> I keep getting this: `` ivy/functional/ivy/set.py:16 in public function `unique_all`: D207: Docstring is under-indented `` for the numpy-docstrings-test. Any ideas?

The Example part of the docstring was under-indented in the unique_all function. Under indentation can be fixed by selecting the part and pressing shift+tab once to unindent it then press tab to indent it properly.

2022-05-19 12:52 UTC, Archymade commented
I still can't figure out why the nightly tests are still failing, but I'll still work on it today.

2022-06-07 08:09 UTC, juliagsy requested changes
comments by section are the feedbacks, thanks!

2022-06-07 08:09 UTC, juliagsy commented on ivy/functional/ivy/set.py
> +    Examples
please format the examples into different sections, which are functional and instance, with their respective subsections if applicable. Docstrings example samples are shown here (https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html) and there are multiple points listed down for reference, thanks!

2022-06-15 05:47 UTC, juliagsy commented
Hey there! As the PR is inactive for more than 7 days, it will be closed in 24 hours if there are no further response! Thank you!

2022-06-16 03:23 UTC, Archymade commented
Tests that were passing previously are failing now. I can't see why, as I haven't changed anything other than the docstring. Please review.

2022-06-16 03:49 UTC, juliagsy commented
Hey there! Thanks for contributing! The failing tests which previously passed are mainly caused by the master branch so you may leave that for now! I'll review them as soon as possible (by today), then request changes or merge if there isn't further issues! Thanks!

2022-06-16 04:10 UTC, Archymade commented
Got it. Thanks.

2022-06-16 05:35 UTC, merged

2022-06-17 21:39 UTC, Archymade commented
Thanks for the merge! I have already worked on the `unique_values` and `unique_inverse` functions. Do I commit and push those too?

2022-06-18 02:13 UTC, juliagsy commented
Hello! As this PR is merged, you'll have to open a new PR and request for review! Then, we'll decide if further changes are needed or it's good for a merge! Thank you!