tensorflow.roll
unifyai/ivy pull request #10354
Opened 2023-02-07 05:53 UTC by ebyau

2023-02-08 03:43 UTC, ebyau commented
@Nightcrab Could you help out on why my tests are failing

2023-02-14 07:39 UTC, Nightcrab requested changes

2023-02-14 07:39 UTC, Nightcrab commented on ivy/functional/frontends/tensorflow/general_functions.py
> +    return ivy.roll(input, shift, axis)
axis is keyword only, see the ivy doc: 
https://lets-unify.ai/ivy/functional/ivy/manipulation/roll/roll_functional.html?highlight=*
so this should be 
```
axis=axis
```

2023-02-14 07:39 UTC, Nightcrab commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py
> +        shifts=shift,
``shifts`` should be ``shift``, and ``dims`` should be ``axis``.

2023-02-14 08:46 UTC, merged