added __ifloordiv__
unifyai/ivy pull request #10380
Opened 2023-02-07 17:50 UTC by rarisenpai

closes #10308

2023-02-08 06:59 UTC, rarisenpai commented
Are there any changes required

2023-02-09 10:03 UTC, zaeemansari70 requested changes
Requested some changes.

2023-02-09 10:03 UTC, zaeemansari70 commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +        return np_frontend.floor_divide(self.ivy_array, value, out=self)
This should be `self._ivy_array`  in floor_divide(), and also remove the `out=self`.

Thanks!

2023-02-10 10:38 UTC, zaeemansari70 approved these changes
floor_div is not failing on the CI
lgtm!

2023-02-10 10:38 UTC, merged