scikit_learn issues
unifyai/ivy pull request #10399
Opened 2023-02-08 10:07 UTC by ndurumo254

2023-02-08 13:40 UTC, ndurumo254 commented
#10401

2023-02-14 15:22 UTC, ndurumo254 commented
hi @YushaArif99 
hope this finds you well. kindly can you check my pr

2023-02-19 18:45 UTC, hirwa-nshuti requested changes
Hey @ndurumo254 

Excellent job so far but generally many of the functions you implemented here are not on our functional API which means that many functions of this frontend will be implemented using the composition of other ivy functions🙂
Kindly go through the below comments and change the implementations accordingly, also update other functions which are not on the API as well😊

Thanks

2023-02-19 18:45 UTC, hirwa-nshuti commented on ivy/functional/frontends/scikit-learn/Clustering/Functions.py
> +    return ivy.k_means(x)
We currently don't have this function on the functional API🙂

You can implement it using compositions😊

2023-02-19 18:45 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_scikit_learn/test_Clustering/test_Functions.py
> +def scikit_learn_k_means(
the testing function should have a name starting with `test_fn_name`

2023-02-23 20:42 UTC, closed without merging