Hypothesis Helpers Documentation
unifyai/ivy pull request #10481
Opened 2023-02-10 21:58 UTC by ZiadAmerr

2023-02-14 19:43 UTC, CatB1t requested changes
Hello @ZiadAmerr, Great work! just few points to address then we're good to merge 👍🏻

2023-02-14 21:48 UTC, ZiadAmerr commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +    """Returns a list of the given length with elements drawn randomly from x.
Since I renamed the parameter to `x` back, I will leave this as is

2023-02-14 21:49 UTC, ZiadAmerr commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +    other,
Renamed it to `x`

2023-02-14 22:07 UTC, ZiadAmerr commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +    """Draws a list of booleans with a fixed size.
Done

2023-02-14 22:07 UTC, ZiadAmerr commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +    other,
Renamed it do `x`

2023-02-14 22:41 UTC, ZiadAmerr commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +    >>> dtype_and_values(
Done

2023-02-14 22:45 UTC, ZiadAmerr commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> -    elif mode == "nearest" or mode == "area":
Done

2023-02-14 22:46 UTC, ZiadAmerr commented
I think all problems are resolved now :)

2023-02-15 00:24 UTC, CatB1t approved these changes
LGTM! great work @ZiadAmerr !

2023-02-15 00:24 UTC, merged