updated test_function helper to throw an exception if an out paramete…
unifyai/ivy pull request #10562
Opened 2023-02-15 13:19 UTC by hello-fri-end

https://trello.com/c/JZUQpvQc/1144-improve-test-failure-log-for-frontend-testing

Creating this as a draft PR so that you can see the progress @CatB1t

2023-02-22 16:27 UTC, CatB1t requested changes
Hello @hello-fri-end, great work! I'd suggest adding a flag to enable or disable the full trace back.
for example `--tb_mode=none` or `--tb_mode=ivy`. also let's keep the default behaviour of the traceback to `--tb_mode=ivy` for now. Thank you!

2023-02-22 16:54 UTC, hello-fri-end commented
> I'd suggest adding a flag to enable or disable the full trace back.

Thanks for the review! Pytest has an inbuilt flag `tb` for choosing between various traceback modes ( 'auto', 'native', 'long', 'short', 'line'). I added a flag `tb-ivy` for choosing between different tracebacks modes for ivy with the default value of `none`.

2023-02-23 13:59 UTC, CatB1t approved these changes
lgtm! great work @hello-fri-end, I've modified the traceback flag name and changed the default to be full, just to not cause issues with the CI, thank you!

2023-02-23 14:02 UTC, merged

2023-02-23 15:42 UTC, hello-fri-end commented on ivy_tests/test_ivy/conftest.py
> +    config.option.tbstyle = config.getoption("--tb")
Hey @CatB1t! If we're going to keep the default as 'full', this line is not required. The default tracemode for Pytest is "auto" which displays the full traceback. I had actually changed the default behavior to "line" which displays a shorter, more concise traceback.