feat: add t function, issue 10474
unifyai/ivy pull request #10588
Opened 2023-02-15 23:12 UTC by ChunchangShao

2023-02-16 10:45 UTC, fspyridakos requested changes
Thanks for the contribution! I left a comment for one more addition to the function. Can you also add the test for it? Thanks

2023-02-16 10:46 UTC, fspyridakos commented
Also, I will link this to the corresponding issue, but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)

2023-02-16 18:13 UTC, ChunchangShao commented on ivy/functional/frontends/torch/indexing_slicing_joining_mutating_ops.py
> +
Hi, thank you for your help. I add the if and test function as your request.

2023-02-17 10:53 UTC, fspyridakos commented
Looks good, thanks for your contribution! Just made a small formatting change myself

2023-02-17 10:53 UTC, merged