Issue #10421 unravel_index
unifyai/ivy pull request #10594
Opened 2023-02-16 09:35 UTC by rajshukla1102

Added unravel_index function in _ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py_
Added unravel_index_test function in _ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py_

Facing issues while running against test cases. Need help in implementing the unravel_index_test function

2023-02-16 09:52 UTC, rajshukla1102 commented
@Aarsh2001 I am unable to understand the implementation of unravel_index_test could you please guide me?

2023-02-20 12:41 UTC, kurshakuz requested changes
Hey @rajshukla1102! I have left a couple of review comments for you to fix. Please also make sure that your test implementation runs locally and producess passing results. 

Please let me know once you are done and post the result of your passing test here. Thanks 🙂

2023-02-20 12:41 UTC, kurshakuz commented on ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py
> -
Please remove empty line additions that you make to irrelevant parts

2023-02-20 12:41 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +import numpy as np
I do not think that you need to add this import

2023-02-20 12:41 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +        st.sampled_from(helpers.dtype_values_axis(available_dtypes=helpers.get_dtypes(kind='integer'),
This line is producing following error:
```
hypothesis.errors.InvalidArgument: Cannot sample from dtype_values_axis(available_dtypes=get_dtypes(kind='integer'), min_value=0, max_value=10), not an ordered collection.
```

2023-02-24 18:02 UTC, rajshukla1102 commented
@kurshakuz I have done my latest commit [4b567b4](https://github.com/unifyai/ivy/pull/10594/commits/4b567b4d6272632eca59275b21cb60f3aece6bea) Please review this

2023-02-24 18:50 UTC, Daniel4078 commented
this pull request continues here: https://github.com/unifyai/ivy/pull/10986

2023-02-24 18:50 UTC, closed without merging