Ivy eigh tridiagonal
unifyai/ivy pull request #10640
Opened 2023-02-18 22:40 UTC by somaia02

Close #10208

2023-02-19 13:44 UTC, fspyridakos requested changes
Thanks for your contribution! Please go over the requested changes. Also there seem to be quite a few lint issues, I would reccommend you install our pre-commit hook to fix them: https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit

2023-02-19 13:44 UTC, fspyridakos commented on ivy/functional/ivy/experimental/linear_algebra.py
> +    """
Could you add docstrings to the function as done with other functions, this is further explained here: https://lets-unify.ai/ivy/deep_dive/docstrings.html

2023-02-19 13:44 UTC, fspyridakos commented on ivy/functional/ivy/experimental/linear_algebra.py
> +
add `eigh_tridiagonal.mixed_function = True`

2023-02-19 13:44 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +        tol=tol,
Might want to add some tolerance to the test like so: `rtol_=1e-2, atol_=1e-2,`

2023-02-21 03:57 UTC, somaia02 commented
Is it meaningful to have instance method variants of this function?

2023-02-21 03:59 UTC, somaia02 commented
Tensorflow throws an error when there is no eigenvalues in the range provided by the select_range argument. How do I deal with this?

2023-02-21 10:40 UTC, fspyridakos requested changes
Good work so far! For the select range, I would suggest you could just make it quite large such that it's guaranteed to have eigenvalues within it, let me know if that works. Also making intance methods for all the functins in the API is a design choice we explain further here: https://lets-unify.ai/ivy/design/ivy_as_a_framework/ivy_array.html#instance-methods

2023-02-21 10:40 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +    ret_np_flat, ret_from_np_flat = results
The second one would come form the ground truth framework, you can abbreviate it at `gt`

2023-02-22 10:34 UTC, fspyridakos commented
LGTM! Many thanks for your contribution again!

2023-02-22 10:37 UTC, merged