An implementation of dropout3d from scratch for all frameworks.
unifyai/ivy pull request #10641
Opened 2023-02-19 02:04 UTC by MuhammadSaeedBatikh

add: dropout3d has been implemented from scratch for all backends except for tensorflow:

  -torch\experimental\layers.py:
       Generated a Bernoulli samples from uniform with the appropriate noise_shape which is then passed as a mask to np.where for efficiency.

  -tensorflow\experimental\layers.py:
      Used the noise_shape argument in tf.nn.dropout to perform a channel-wise dropout.

  -numpy\experimental\layers.py:
       Generated a Bernoulli samples with the appropriate noise_shape which is then passed as a mask to np.where for efficiency.

  -jax\experimental\layers.py:
       Similar to numpy.

and:functional\ivy\layers.py
    calls ivy.current_backend

add:ivy\array\layers.py, ivy\container\layers.py
    instance method support

add:ivy\array\layers.py, ivy\container\layers.py
    instance method support

add: test_ivy\test_docstrings.py
    added to skiplist since output is dependent on external factors.

2023-02-20 18:47 UTC, sherry30 requested changes
Hi Muhammad,

There are some lint errors, can you fix those?
I recommend installing `pre-commit`. The instructions are here in this [guide](https://docs.google.com/document/d/1J5Ij0u3nU_jVkOeXvrTOuGF-W9tnwhukenqwtpar83k/edit)

Also, is it not possible to use `torch.nn.functional.dropout` for torch backend implementation? 🤔. Just wondering if it is and if that would be more efficient. If you think this makes more sense then we can go with this.

2023-02-20 19:21 UTC, MuhammadSaeedBatikh commented
> Hi Muhammad,
> 
> There are some lint errors, can you fix those? I recommend installing `pre-commit`. The instructions are here in this [guide](https://docs.google.com/document/d/1J5Ij0u3nU_jVkOeXvrTOuGF-W9tnwhukenqwtpar83k/edit)
> 
> Also, is it not possible to use `torch.nn.functional.dropout` for torch backend implementation? 🤔. Just wondering if it is and if that would be more efficient. If you think this makes more sense then we can go with this.

Hi @sherry30 , thanks for the review.
Unfortunately `torch.nn.functional.dropout` is an elementwise dropout that does not accept a `noise_shape` argument, while  `dropout3d` is a channel-wise dropout (i.e. it drops or keeps entire 3D feature maps) and therefore cannot be replaced by a standard elementwise function. I should say that in more recent torch versions there are indeed `dropoutnd` functions'; hence the `ToDo` I added to replace the current implementation for torch once ivy's torch is updated.

2023-02-20 19:47 UTC, MuhammadSaeedBatikh commented
hi @sherry30, I fixed the lint error. Please merge.

2023-02-21 11:36 UTC, sherry30 approved these changes
I see,
That makes sense, Thanks for the explanation. 😄 

looks good to merge!

2023-02-21 11:37 UTC, merged