Torch frontend lerp
unifyai/ivy pull request #10690
Opened 2023-02-20 21:52 UTC by aparna2071

Closes #10683

2023-02-21 09:49 UTC, fspyridakos requested changes
Thanks for your contribution! I left a few comments please go over them and ask for another review once you're done.

2023-02-21 09:49 UTC, fspyridakos commented on ivy/functional/frontends/torch/pointwise_ops.py
> +    return ivy.lerp(start, end, weight)
ivy.lerp doesn't exist in the ivy API, you can suggest its addition by following the steps here: https://lets-unify.ai/ivy/deep_dive/ivy_frontends.html#missing-ivy-functions.
That being said the function can simply composed by a few arithmetic operations as described here: https://pytorch.org/docs/stable/generated/torch.lerp.html.
Also please add the `out` argument

2023-02-21 09:49 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +
Please remove these imports

2023-02-21 09:49 UTC, fspyridakos commented on ivy/functional/frontends/torch/pointwise_ops.py
> +def lerp(start, end, weight):
The first argument should be `input` as stated in the torch docs: https://pytorch.org/docs/stable/generated/torch.lerp.html

2023-02-21 09:49 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +    assert_allclose(expected_output, output, rtol=1e-03, atol=1e-05)
No need to do this here, `test_frontend_fuction` handles this

2023-02-21 09:49 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +        expected_output=expected_output,
don't pack all input arguments into one, make them seperate keyword args, i.e. `input=start`, `end=end`, `weight=weight`.
Remove `expected_output`
No need to include the `out` argument when you add it

2023-02-21 14:41 UTC, aparna2071 commented
Thank you so much for your detailed review, will help me a lot.
I will make the necessary changes as soon as possible.

2023-02-21 16:46 UTC, aparna2071 commented
Hi @fspyridakos, as far as the addition of ivy.lerp function is concerned, I've raised a new issue #10762.
Other than that, I've tried to make all necessary changes as suggested by you.
Kindly review & please feel free to suggest if any more changes are required.
Also, thanks a lot for detailed suggestions.

2023-02-21 17:17 UTC, fspyridakos requested changes
Thanks for the changes! Also your ivy.lerp issue mentions the `.interp` function in jax and numpy, and `ivy.interp` already exists, if you think you can use that function here go ahead, but I think `lerp` and `interp` do different things, just chaning some elementwise functions is fine for now

2023-02-21 17:17 UTC, fspyridakos commented on ivy/functional/frontends/torch/pointwise_ops.py
> +    out = ivy.multiply_add(ivy.subtract(end, input), weight, ivy.subtract(input, out), out=out)
most lines are redundant, you can just do `return <operation>` as with the above functions (`out` in the docs practically means the `return`) also look over your implementation, `ivy.multiply_add` doesn't exist

2023-02-21 17:17 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +        default=0.5,
I'm not sure what `default` is here, but you should probably use `num_arrays=3`

2023-02-21 17:17 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +)
fix indentation here to match functions above

2023-02-21 18:23 UTC, aparna2071 commented
Hi @fspyridakos, once again thanks a lot.
As far as ivy.lerp issue is concerned, I've deleted the links for interp & have tried to make all necessary changes as required for this PR.
Kindly review & please let me know if any more changes are required.

2023-02-22 11:50 UTC, fspyridakos requested changes
Few more chnages and you're golden

2023-02-22 11:50 UTC, fspyridakos commented on ivy/functional/frontends/torch/pointwise_ops.py
> +@to_ivy_arrays_and_back
Please add float16 and bfloat16 as unsupprted dtypes for torch (like other functions above)

2023-02-22 11:50 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +        num_arrays=3,
Add the following:
`       large_abs_safety_factor=2.5,
        small_abs_safety_factor=2.5,
        safety_factor_scale="log",`
Some large values will not interpolate properly due to float percision limitations, this prevents those from being generated

2023-02-22 11:50 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +        input_weight=weight,
just have this be `input=start, end=end` and so on, the kwargs must have the same names as the function args

2023-02-22 13:36 UTC, aparna2071 commented
Hi @fspyridakos, thanks for all your help.
I've made the changes, please let me know if anything else is required.

2023-02-22 15:07 UTC, fspyridakos commented
LGTM, had to make 2 small changes but it's good now and the test passes

2023-02-22 15:07 UTC, merged

2023-02-22 15:08 UTC, aparna2071 commented
Thanks a lot for merging @fspyridakos.