ldexp extension
unifyai/ivy pull request #10772
Opened 2023-02-21 19:14 UTC by pillarxyz

2023-02-22 14:19 UTC, nassimberrada requested changes
Hey @pillarxyz, I've looked through your PR and it's looking mostly good ! I left a couple comments maybe you could address those and make appropriate modifications across the files ? Let me know when you feel it's good to go and the tests are passing, I'll give it another review then. Thanks !

2023-02-22 14:19 UTC, nassimberrada commented on ivy/functional/backends/numpy/experimental/elementwise.py
> +    i: Union[np.ndarray, int, list, tuple],
It doesn't change much really but only torch uses the notation `x` and `i` for the inputs, might be better to stick with `x1` and `x2` as is the case numpy and jax ? I see you've used the latter notation for the testing when you passed `x1=x[0]` and `x2=x[1]` , you've also used that in the jax backend. In general you want to keep consistency in input format across the backends. It's at the front-end level that we mimic the patterns of each framework separately

2023-02-22 14:19 UTC, nassimberrada commented on ivy/functional/ivy/experimental/elementwise.py
> +    i: Union[ivy.Array, ivy.NativeArray],
I believe the second array input (whether you call it `i` or `x2`), should be positional-only and placed before the `/,` sign

2023-02-22 14:19 UTC, nassimberrada commented on ivy/container/elementwise.py
> +        >>> i = ivy.Container(a=ivy.array([1, 2, 3]), b=ivy.array([1, 5, 10]))
You've already made changes to the experimental version of the containers so this should be removed

2023-02-23 10:43 UTC, nassimberrada requested changes
@pillarxyz haven't taken a look at the tests yet but I've left a couple other comments that should make things almost ready once adjusted to, could you give those a look ? Thanks !

2023-02-23 10:43 UTC, nassimberrada commented on ivy/array/experimental/elementwise.py
> +        /,
I think the second array input is missing here, and in the docstring as well

2023-02-23 10:43 UTC, nassimberrada commented on ivy/container/experimental/elementwise.py
> +        i: Union[ivy.Array, ivy.NativeArray, ivy.Container],
I see you've changed Numpy's arguments to `x1` and `x2` , could you apply those changes here as well ?

2023-02-23 10:43 UTC, nassimberrada commented on ivy/container/experimental/elementwise.py
> +        i: Union[ivy.Array, ivy.NativeArray, ivy.Container],
I see you've changed Numpy's arguments to `x1` and `x2` , could you apply those changes here as well ?

2023-02-23 10:43 UTC, nassimberrada commented on ivy/container/experimental/elementwise.py
> +            i=i,
Also the second array input is not a keyword argument as specified so no need to write is as argument = argument

2023-02-23 10:43 UTC, nassimberrada commented on ivy/container/experimental/elementwise.py
> +        i: Union[ivy.Array, ivy.NativeArray, ivy.Container],
Likewise should be changed to `x1` and `x2` alongside the docstrings

2023-02-23 10:43 UTC, nassimberrada commented on ivy/functional/backends/tensorflow/experimental/elementwise.py
> +    i: Union[tf.Tensor, tf.Variable],
Likewise should be changed to `x1` and `x2` alongside the function calls

2023-02-23 10:43 UTC, nassimberrada commented on ivy/functional/backends/torch/experimental/elementwise.py
> +    i: Union[int, torch.Tensor],
Likewise should be changed to `x1` and `x2` alongside the function calls

2023-02-23 10:43 UTC, nassimberrada commented on ivy/functional/ivy/experimental/elementwise.py
> +    Returns x * (2**i), element-wise.
Likewise the docstrings should reflect  `x1` and `x2`

2023-02-23 10:43 UTC, nassimberrada requested changes
@pillarxyz haven't taken a look at the tests yet but I've left a couple other comments that should make things almost ready once adjusted to, could you give those a look ? Thanks !

2023-02-26 14:16 UTC, closed without merging

2023-02-26 19:42 UTC, pillarxyz commented
@VedPatwardhan what happened with the PR ?

2023-02-27 13:13 UTC, pillarxyz commented
#11113