prod
unifyai/ivy pull request #10869
Opened 2023-02-23 11:23 UTC by KevinUnadkat

Added prod from Statistical to paddle backend

2023-02-23 11:23 UTC, KevinUnadkat commented
issue - prod #10868

2023-02-23 11:30 UTC, KevinUnadkat commented
hy @MahmoudAshraf97 
pls review this file it is probably ready to merge

2023-02-23 12:50 UTC, KevinUnadkat commented
hy 
@MahmoudAshraf97
pls review this file it is probably ready to merge

2023-02-23 14:13 UTC, MahmoudAshraf97 requested changes

2023-02-23 14:13 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return paddle.std(x, dim=axis, unbiased=False, keepdim=keepdims)
please review the input arguments and make sure that the output adheres to them

2023-02-23 14:13 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return torch.sum(input=x, dim=axis, dtype=dtype, keepdim=keepdims)
use paddle implementation, and check that the args and kwargs are correct

2023-02-23 14:13 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return paddle.var(x, dim=axis, unbiased=False, keepdim=keepdims)
same comments as above

2023-02-23 15:17 UTC, KevinUnadkat commented
@MahmoudAshraf97 
made the changes , everything seems good now

2023-02-23 18:20 UTC, MahmoudAshraf97 requested changes

2023-02-23 18:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return paddle.std(x, axis=axis, unbiased=True, keepdim=keepdims)
you need to implement the correction parameter, the unbiased parameter in paddle sets correction = 1, but it needs to be a float, check the torch backend implementation as it's the closest one to paddle

2023-02-23 18:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return paddle.var(x, axis, unbiased=true, keepdim=keepdims)
same comment as std

2023-02-23 18:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return paddle.cumprod(x, dim=None, dtype=None, name=None)
you need to implement the `exclusive` and `reverse` arguments here

2023-02-23 18:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return paddle.cumsum(x, axis=axis, dtype=dtype)
same comment as `cumprod`

2023-02-23 18:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    return paddle.einsum(equation, *operands)
Please verify the results with another backend to make sure the implementation is correct

2023-02-23 18:22 UTC, MahmoudAshraf97 commented
I recommend you to read both Ivy documentation and paddle documentation when implementing a function in order to know the difference in implementation because some functions work differently, also check other backends implementations for reference

2023-02-25 13:23 UTC, MahmoudAshraf97 approved these changes

2023-02-25 13:23 UTC, merged