creating atleast_2d function
unifyai/ivy pull request #10980
Opened 2023-02-24 16:13 UTC by ndurumo254

2023-02-24 16:14 UTC, ndurumo254 commented
#8422

2023-02-24 16:26 UTC, ndurumo254 commented
#https://github.com/unifyai/ivy/pull/10905#issuecomment-1442434800

2023-02-24 17:50 UTC, hirwa-nshuti requested changes
Hey @ndurumo254 

The implementation looks good but you have also changed many other functions where there are added unnecessary spaces would you remove them.

After that is resolved I'll merge your PR

Thanks😊

2023-02-24 17:50 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/numpy/manipulations.py
> +        a,
These added spaces are not needed

2023-02-24 20:13 UTC, hirwa-nshuti commented
Hey @ndurumo254 
Still there are many unnecessary changes if you head here you can find them
https://github.com/unifyai/ivy/pull/10980/files

2023-02-25 08:44 UTC, hirwa-nshuti requested changes
Hey @ndurumo254 

There are too many formatting errors in your PR😊
You can use the pre-commit hook to remove them here is a guide to it https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit

After successfully installing it you can run `pre-commit run --files FILE_PATH` for both the changed files it will reformat the code automatically and push the changes.

Hope this will help out🙂

Thanks

2023-02-25 08:44 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_manipulation.py
> +        on_device,
These extra tabs aren't supposed to be here.

2023-02-25 09:13 UTC, ndurumo254 commented
> Hey @ndurumo254
> 
> There are too many formatting errors in your PR😊 You can use the pre-commit hook to remove them here is a guide to it https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit
> 
> After successfully installing it you can run `pre-commit run --files FILE_PATH` for both the changed files it will reformat the code automatically and push the changes.
> 
> Hope this will help out🙂
> 
> Thanks

done

2023-02-25 09:17 UTC, hirwa-nshuti requested changes
I checked from the frontends and this function is already implemented there as I can see is that what you did change its location in the same files😊

https://github.com/unifyai/ivy/blob/37a5139bdee81f49a84ad63aa9d6597bc0c0b4f8/ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_manipulation.py#L663

Would you work on another task
And mind checking if the function exists before spending much time re-implementing the same stuff🙂

Thanks

2023-02-25 09:21 UTC, ndurumo254 commented
> I checked from the frontends and this function is already implemented there as I can see is that what you did change its location in the same files😊
> 
> https://github.com/unifyai/ivy/blob/37a5139bdee81f49a84ad63aa9d6597bc0c0b4f8/ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_manipulation.py#L663
> 
> Would you work on another task And mind checking if the function exists before spending much time re-implementing the same stuff🙂
> 
> Thanks

ok.

2023-02-25 09:28 UTC, closed without merging