Update elementwise.py
unifyai/ivy pull request #11043
Opened 2023-02-25 16:59 UTC by vandit98

Added bitwise_right_shift to Paddle Backend.

2023-02-25 17:11 UTC, vandit98 commented
Hi @MahmoudAshraf97 
With reference to above pull request i have tried to implement bitwise_right_shift in  paddle backend.
https://github.com/unifyai/ivy/pull/10935/files
Please let me know if i am doing it right.
Thanks

2023-02-25 19:36 UTC, MahmoudAshraf97 commented
Hi @vandit98 , unfortunately the implementation is not correct because the function you used doesn't exist in paddle, please check the documentation [Here](https://www.paddlepaddle.org.cn/documentation/docs/en/api/index_en.html) and look for an appropriate function.
I didn't find any so probably you'll have to implement it yourself using composite functions

2023-02-25 19:37 UTC, MahmoudAshraf97 requested changes

2023-02-25 19:37 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/elementwise.py
> +    result = paddle.fluid.layers.bitwise_right_shift(x1, x2, out)
this function doesn't exist

2023-02-26 06:24 UTC, vandit98 commented
hi @MahmoudAshraf97 
I have tried another method.
Can You please review it.
Thanks

2023-02-26 11:16 UTC, MahmoudAshraf97 approved these changes

2023-02-26 11:17 UTC, MahmoudAshraf97 commented
Great work, i've added some casting to ensure compatibility in some operations so please make sure they're added the next time, will proceed to merge this

2023-02-26 11:17 UTC, merged