implement cov
unifyai/ivy pull request #11193
Opened 2023-02-28 12:42 UTC by Hokchris

https://github.com/unifyai/ivy/issues/6269

closes https://github.com/unifyai/ivy/issues/6269

Implemented cov for linear algebra section.

2023-03-01 11:31 UTC, AnnaTz requested changes

2023-03-01 11:31 UTC, AnnaTz commented on ivy/functional/backends/tensorflow/linear_algebra.py
> +        fweights = tf.cast(fweights, dtype=tf.float64)
I'm not sure casting `fweights` and `aweights` makes any difference in the results. Is there a specific reason you have added it in all backends?

2023-03-01 11:31 UTC, AnnaTz commented on ivy_tests/test_ivy/test_functional/test_core/test_linalg.py
> +    test_gradients=st.just(False),
If you remove the `out` argument, you should add `test_with_out=st.just(False),` here.

2023-03-06 12:52 UTC, Hokchris commented
Hey! Just went through the requested changes and I think they should be done now. The one thing I wasn't sure about making changes to were some of the datatype casts, namely in the Jax, Numpy and Tensorflow backends. 

Jax's default datatype is float32 and I get a datatype warning that it doesn't match with the ground truth backend (Tensorflow and Numpy both give the same complaint I think).
The three backends give an error if I get rid of the fweights datatype casting to _int64_ (I removed the aweights and they all still worked). Jax and Numpy both say that fweights must be integer (it should be with the dtype specified in the test file, but it looks like the fweights are being cast to floats when being passed into the backends), and Tensorflow doesn't allow **w** * **aweights** on line 117 without the casting ("cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor").
 
Is there another flag that I could use in the test file to prevent the datatype casting? The datatypes for fweights and aweights are currently hardcoded into the dtypes input array.

I assume I should make another PR due to the recent force push again to resolve the conflicts above?

2023-03-06 13:15 UTC, AnnaTz commented
> 

Hi!
Since the casting is there to prevent certain errors you were getting, you shouldn't remove them of course. I just wasn't sure what reason you had to add them in the first place. 
As far as I know there is no flag to disable that. That's why we are using the `input_dtypes` argument.
Yes, after the force-push all PRs need to be re-created.

2023-03-06 13:20 UTC, AnnaTz commented
> Hey! Just went through the requested changes and I think they should be done now. The one thing I wasn't sure about making changes to were some of the datatype casts, namely in the Jax, Numpy and Tensorflow backends.
> 
> Jax's default datatype is float32 and I get a datatype warning that it doesn't match with the ground truth backend (Tensorflow and Numpy both give the same complaint I think). The three backends give an error if I get rid of the fweights datatype casting to _int64_ (I removed the aweights and they all still worked). Jax and Numpy both say that fweights must be integer (it should be with the dtype specified in the test file, but it looks like the fweights are being cast to floats when being passed into the backends), and Tensorflow doesn't allow **w** * **aweights** on line 117 without the casting ("cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor").
> 
> Is there another flag that I could use in the test file to prevent the datatype casting? The datatypes for fweights and aweights are currently hardcoded into the dtypes input array.
> 
> I assume I should make another PR due to the recent force push again to resolve the conflicts above?

Hi!
Since the castings are there to prevent certain errors you were getting, you shouldn't remove them of course. I just wasn't sure what was the reason you had added them.
As far as I know there is no flag to prevent that. That's why we are using the `input_dtypes` argument.
Yes, after the force-push all PRs need to be re-created.

2023-03-07 09:43 UTC, Hokchris commented
Hey, I think I might've accidentally closed this yesterday when trying to re-commit the changes to a new branch. Should I contact someone about issue 6269 (https://github.com/unifyai/ivy/issues/6269) being closed by ivy-leaves yesterday (I assume automatically) or can these changes be done via this PR?

2023-03-07 10:01 UTC, AnnaTz commented
> Hey, I think I might've accidentally closed this yesterday when trying to re-commit the changes to a new branch. Should I contact someone about issue 6269 (#6269) being closed by ivy-leaves yesterday (I assume automatically) or can these changes be done via this PR?

No worries, I opened the issue again and re-linked it to the ToDo list.

2023-03-15 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-03-17 19:02 UTC, Hokchris commented
Hey, just made a small change removing a flag from the test. I had an issue trying to run the tests locally after the previous force push and I started getting an assertion error: "ground truth backend (tensorflow) returned array on device gpu:0 but target backend (torch) returned array on device cpu" regardless of the function I was trying to test, but I just set up the environment with a docker container and it worked as intended.

Are there still some changes I should make or is this version fine as the tests look to pass locally at least for me?

2023-03-20 11:46 UTC, AnnaTz commented
Hi @Hokchris, unfortunately there's been another force push in our repository so you'll need to create a new PR. Apologies for the inconvenience. 
If the tests are passing locally I guess the new PR will be able to get merged fairly quickly.

2023-03-23 15:39 UTC, closed without merging