blackman
unifyai/ivy pull request #11508
Opened 2023-03-01 18:38 UTC by ndurumo254

2023-03-01 19:10 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/11197

2023-03-01 19:11 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/11190

2023-03-01 19:11 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/11011

2023-03-01 19:12 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/8422

2023-03-01 19:13 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/pull/11129

2023-03-03 04:31 UTC, hirwa-nshuti requested changes
Hey @ndurumo254 

Sorry for the late review🙂
Some few changes to be made then we progress also remember to use pre-commit🤣
I'm getting some unnecessary tabs introduced in the manipulation file

Thanks

2023-03-03 05:07 UTC, ndurumo254 commented
> Hey @ndurumo254
> 
> Sorry for the late review🙂 Some few changes to be made then we progress also remember to use pre-commit🤣 I'm getting some unnecessary tabs introduced in the manipulation file
> 
> Thanks

ok.

2023-03-03 06:34 UTC, hirwa-nshuti requested changes
Hey

The unit tests are still failing would you look into them😊
And also do check some comments I added below

Thanks

2023-03-03 06:34 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/numpy/manipulations.py
> +        return ivy.concatenate(
`ivy.concatenate` is not present in ivy API but, it is available as `ivy.concat`

2023-03-03 06:34 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_manipulation.py
> +    dtype_and_M,
Try to pass generated data correctly as this is supposed to be `dtype_and_m`

2023-03-03 22:52 UTC, hirwa-nshuti requested changes
Hey I see that still your unit tests are failing now

Would you have a look and fix them😊

2023-03-04 23:29 UTC, closed without merging

2023-04-28 03:33 UTC, ndurumo254 commented
i want to finalize on this

2023-04-28 04:07 UTC, hirwa-nshuti commented
Sure