#10861 Added modf to numpy frontend mathematical functions
unifyai/ivy pull request #11587
Opened 2023-03-02 17:43 UTC by AryanSharma9917

2023-03-03 04:56 UTC, hirwa-nshuti requested changes
Hey @AryanSharma9917 

Thanks for contributing to ivy😊
Firstly to have your function fully working you will need to add it to the init file as it is a `ufunc` object refer to example here to know how to import it and initialize it:
import: https://github.com/unifyai/ivy/blob/d12bede7d6ecce1728714a49e5d06bf5a92e37e1/ivy/functional/frontends/numpy/__init__.py#L514

instantiate: https://github.com/unifyai/ivy/blob/d12bede7d6ecce1728714a49e5d06bf5a92e37e1/ivy/functional/frontends/numpy/__init__.py#L667

Other changes that are needed are mentioned in comments below.

Thanks again and happy coding🙂

2023-03-03 04:56 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +def _modf(
Need to add all needed function parameters.
Refer to Documentation: https://numpy.org/doc/1.23/reference/generated/numpy.modf.html

2023-03-03 04:56 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_arithmetic_operations.py
> +                max_dims=1,
Some of these arguments aren't supported you might have wrong-typed them kindly check the helpers documentation to know accepted arguments https://lets-unify.ai/ivy/testing/hypothesis_helpers.html

2023-03-04 08:27 UTC, AryanSharma9917 commented
@hirwa-nshuti I have made all the changes, so I just simply send the pull request or is there anything to be done while sending the pull request to connect those changes to this pull request?

2023-03-04 08:40 UTC, hirwa-nshuti commented
> @hirwa-nshuti I have made all the changes, so I just simply send the pull request or is there anything to be done while sending the pull request to connect those changes to this pull request?

You have to commit new changes to this branch you're working on

2023-03-04 13:34 UTC, hirwa-nshuti requested changes
Hey

The unit tests are still failing would you check on them and fix lint errors as well

Thanks

2023-03-04 13:34 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_arithmetic_operations.py
> +                max_dims=1,
Still the following data generation is causing failures would you check on them

2023-03-04 16:19 UTC, AryanSharma9917 commented
> Hey
> 
> The unit tests are still failing would you check on them and fix lint errors as well
> 
> Thanks

@hirwa-nshuti could you please help me out, I am facing a problem in solving these two issues.

2023-03-04 17:45 UTC, AryanSharma9917 commented
@hirwa-nshuti  Do I need to fill in all the errors in lint or the specific files I have worked on during the contribution?

2023-03-04 19:38 UTC, closed without merging