added allclose and imag
unifyai/ivy pull request #11609
Opened 2023-03-03 06:54 UTC by vandit98

2023-03-03 12:01 UTC, MahmoudAshraf97 reviewed
imag and allclose are good to merge, please review the others and make sure they pass the tests

2023-03-03 12:04 UTC, MahmoudAshraf97 requested changes

2023-03-03 12:04 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/elementwise.py
> +    paddle.floor(x, name="fix")
AssertionError: The length of results from backend paddle and ground truth framework tensorflow does not match

2023-03-03 12:53 UTC, vandit98 commented
hi @MahmoudAshraf97 
How can i make sure that my function are passing test. Can u please elaborate how to do do testing.
What tests my functions should pass? 
So far i tried passing my own inputs.
thanks

2023-03-03 13:20 UTC, MahmoudAshraf97 commented
use this command in terminal and make sure you are in the right directory
`pytest -B paddle ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_elementwise.py::test_function_name`

2023-03-03 13:22 UTC, vandit98 commented
thanks @MahmoudAshraf97

2023-03-03 13:34 UTC, MahmoudAshraf97 commented
can you separate imag and allclose in a separate PR so we can merge them? also in the next PRs make sure to add 1 function only

2023-03-03 15:52 UTC, MahmoudAshraf97 approved these changes

2023-03-03 15:53 UTC, merged

2023-03-04 13:24 UTC, vandit98 commented
hi @MahmoudAshraf97 
Can u help me with this error. I am trying to use an alreading working function.
![Screenshot from 2023-03-04 18-34-58](https://user-images.githubusercontent.com/91458535/222904302-ef2cc404-1c1f-4a55-b059-e368c9ecbff9.png)

2023-03-04 19:34 UTC, vandit98 commented
hi @MahmoudAshraf97 
Can u help me with this error. I have tried to run test for allclose.
Is there any documents or resources for doing this. 
![Screenshot from 2023-03-05 01-04-13](https://user-images.githubusercontent.com/91458535/222925382-d2d75018-9d96-4f49-b532-47bb93ad9ee1.png)