issue #11630
unifyai/ivy pull request #11632
Opened 2023-03-03 13:06 UTC by cyberCharl

I think this is correct, but can't run the test since I keep getting Empty Suite error. Even though I'm following the instructions given in the Setting Up wiki regarding the Empty Suite error.

2023-03-03 14:08 UTC, cyberCharl commented
I got the Empty Suite issue sorted, all 4 tests passed for moveaxis. I opened another issue (#11636) and commited it after all the tests succeeded.

2023-03-03 17:16 UTC, cyberCharl commented
I apologize for including 4 commits of different tasks in 1 PR, I had intended to open separate PR's for the issues but GutHub pulled all my commits into the same PR.

2023-03-03 22:01 UTC, MahmoudAshraf97 requested changes
please remove the functions that don't work so we can merge

2023-03-03 22:02 UTC, MahmoudAshraf97 commented
if you want to create separate PRs, create a different branch for each issue

2023-03-04 18:47 UTC, cyberCharl commented on ivy/functional/backends/paddle/experimental/manipulation.py
> +    return paddle.dtack(arrays)
removed the incorrect code for both dstack and flipud

2023-03-06 10:43 UTC, merged