Updated docstring
unifyai/ivy pull request #11709
Opened 2023-03-04 17:45 UTC by chetna-mittal

Reformat general #791

2023-03-04 18:33 UTC, chetna-mittal commented
Please let me know if there are any suggestions or changes needed?

2023-03-07 07:49 UTC, chetna-mittal commented
@fspyridakos Have synced my branch with Ivy

2023-03-07 11:13 UTC, fspyridakos commented
Can you sync once again, there were some further changes again, apologies for that

2023-03-07 16:23 UTC, chetna-mittal commented
> Can you sync once again, there were some further changes again, apologies for that

I have synced again, could you review please

2023-03-07 16:31 UTC, fspyridakos commented
Are you sure? The branch you want to merge doesn't seem to have been updated: https://github.com/chetna-mittal/ivy/tree/Clip_vector_norm

2023-03-07 16:38 UTC, chetna-mittal commented
> Are you sure? The branch you want to merge doesn't seem to have been updated: https://github.com/chetna-mittal/ivy/tree/Clip_vector_norm

Could you check now

2023-03-07 16:54 UTC, fspyridakos requested changes
Can you also include the changes to the equivalent array and container instance methods?

2023-03-07 16:54 UTC, fspyridakos commented on ivy/functional/ivy/general.py
> +        An array with the matrix norm downscaled to the max norm if needed.
this should remain as vector

2023-03-08 08:28 UTC, fspyridakos commented
Thanks for the update, but I was reffering to the `clip_vector_norm` methods found in `ivy/array/general` and `ivy/container/general`, could you update those with the same changes?

2023-03-08 09:39 UTC, chetna-mittal commented
> Thanks for the update, but I was reffering to the `clip_vector_norm` methods found in `ivy/array/general` and `ivy/container/general`, could you update those with the same changes?

I have updated those changes as well

2023-03-09 10:26 UTC, fspyridakos commented
Looks good now!

2023-03-09 10:27 UTC, merged