Added Instance method tolist() and Frontend test
unifyai/ivy pull request #11760
Opened 2023-03-05 19:58 UTC by cressidasuphina

2023-03-08 23:33 UTC, cressidasuphina commented
Hi, could you help me? My values ret_np_flat and ret_from_np_gt_flat don't match. But I compared it manually and it looks the same. As I got it right ground truth framework is original Numpy library itself, isn't it? Also, I'm not sure if it's ok that I added ivy.to_list(x) to manipulation_routines/changing_kind_of_array.py file. 
![image](https://user-images.githubusercontent.com/127023793/223875205-f5d2d7ef-cc85-4e8a-a5fb-2ba83c1fa9de.png)
![image](https://user-images.githubusercontent.com/127023793/223875260-35e72961-5e89-49a2-94f6-9d9ae99fbc6e.png)

2023-03-14 04:51 UTC, hirwa-nshuti requested changes
Hey @cressidasuphina 

Would you add the unit tests for `to_list` function as well and also remove the changes from `.idea` files 

Thanks

2023-03-16 20:20 UTC, cressidasuphina commented
Hi @hirwa-nshuti thank you for your comment, I did what you asked but unfortunately I have got an an exception in test_frontend_function
![image](https://user-images.githubusercontent.com/127023793/225743392-19fb9d90-fa32-4675-9f5e-fdd22ec1f7f2.png)

2023-03-24 11:21 UTC, hirwa-nshuti requested changes
Hey @cressidasuphina 

The reason why your tests are failing is because `numpy` doesn't have `tolist` as a function it is only and instance method of `np.ndarray` https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html

You need to implement it only in the `ndarray ` class methods

Thanks

2023-04-11 08:33 UTC, hirwa-nshuti requested changes
Hey @cressidasuphina 

This function isn't yet implemented on the numpy frontend.
You'll have to implement its composition😊

2023-04-11 11:11 UTC, cressidasuphina commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +        return np_frontend.ivy.to_list(self._ivy_array)
Hello, thank you for your comment and your attention. I hope I have got it right this time.

2023-04-16 15:42 UTC, hirwa-nshuti requested changes
Hey @cressidasuphina 

There is some progress now😊 However the function `tolist` is not present in the numpy frontend namespace, you'll have to implement it using compositions

2023-04-26 06:27 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-30 15:38 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +        on_device=on_device,
```suggestion
        on_device=on_device,
        test_values=False, #Todo change this after we add __iter__ to ndarray
```

2023-04-30 15:38 UTC, hirwa-nshuti approved these changes
Hey @cressidasuphina 

Thanks for the PR
All looks good going to merge😊

2023-04-30 15:39 UTC, merged

2023-04-30 16:51 UTC, cressidasuphina commented
Hi