Adding PyTorch Frontend pdist #11753
unifyai/ivy pull request #11805
Opened 2023-03-06 13:57 UTC by mrdedede

Created Frontend PyTorch pdist distance algorithm
Related to #11753 and #25

2023-03-06 18:27 UTC, zaeemansari70 commented
Hi @mrdedede  ,
Do request a review from me by just commenting on the PR once you are done with the implementation slightly_smiling_face

2023-03-08 17:15 UTC, mrdedede commented
Hi @zaeemansari70 
Thanks!
I'll look forward to check what the failing tests may mean.

Meanwhile, would you mind helping me understand some of the error messages? Most of them are just one line long and don't offer much advice on what does need changes.

2023-03-08 21:19 UTC, zaeemansari70 requested changes
I've mentioned the issue n your code below.
Thanks! :slightly_smiling_face:

2023-03-08 21:19 UTC, zaeemansari70 commented on ivy/functional/frontends/torch/nn/functional/distance_functions.py
> +    x1 = torch_frontend.promote_types_of_torch_inputs(x1)
You are using `promote_types_of_torch_inputs()` which takes two arguments and you passing one. :slightly_smiling_face: 
https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/torch/__init__.py#L241

2023-03-09 11:33 UTC, mrdedede commented
Thanks, @zaeemansari70 
I'll look into it asap! :)

I have had some issues trying to run my local tests, however, I can't seem to get it right when I run it locally.
Do you mind if I ping you on Discord in order to analyze why this may be happening? Testing locally and getting my results there would make a huge difference!!

2023-03-17 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-03-26 06:26 UTC, closed without merging

2023-03-26 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.