gamma added to tensorflow random
unifyai/ivy pull request #11809
Opened 2023-03-06 15:06 UTC by ian0549

#10864

2023-03-15 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-03-16 07:29 UTC, kurshakuz requested changes
Hi! 

I have tested your implementation locally and it is failing one test. Can you please fix it and let me know once you are done?

```
E           ivy.utils.exceptions.IvyBackendException: torch: gamma: to() received an invalid combination of arguments - got (NoneType, FloatDtype), but expected one of:
E            * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
E            * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
E            * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format memory_format)
E           
E           Falsifying example: test_tensorflow_Gamma(
E               shape=(1,),
E               alpha=1.0,
E               beta=1.0,
E               dtype=['bfloat16', 'float32'],
E               seed=0,
E               test_flags=FrontendFunctionTestFlags(
E                   num_positional_args=0,
E                   with_out=False,
E                   inplace=False,
E                   as_variable=[False],
E                   native_arrays=[False],
E               ),
E               fn_tree='ivy.functional.frontends.tensorflow.random.gamma',
E               frontend='tensorflow',
E               on_device='cpu',
E           )
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.68.2', b'AXicY2RAAYyYbAAAXgAE') as a decorator on your test case

ivy/utils/exceptions.py:128: IvyBackendException
```

2023-03-16 07:29 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py
> +def test_tensorflow_Gamma(
```suggestion
def test_tensorflow_gamma(
```

2023-03-16 07:29 UTC, kurshakuz commented on ivy/functional/frontends/tensorflow/random.py
> +    "tensorflow",
Is there any specific reason why all of the above data types are not supported?

2023-03-16 07:29 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py
> +def test_tensorflow_Gamma(
We use lowercase naming for all functions

2023-03-26 06:25 UTC, closed without merging

2023-03-26 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.