#12537 : Added fmin mathematical function for numpy frontend
unifyai/ivy pull request #11829
Opened 2023-03-06 19:39 UTC by AryanSharma9917

2023-03-06 20:14 UTC, AryanSharma9917 commented
Heyy @kurshakuz , how do I solve this lint issue could you please guide me out

2023-03-16 07:42 UTC, kurshakuz requested changes
Hey! I have tested your implementation locally and it fails for all 4 tests. Additionally, you have a syntax error that was causing one of the issues. Please fix your solution, test it locally and let me know once you are done, so that I can have a second look. Thanks! 🙂 

```
ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py FFFF                                               [100%]

======================================================================== FAILURES =========================================================================
_____________________________________________ test_numpy_fmin[cpu-ivy.functional.backends.numpy-False-False] ______________________________________________

frontend = 'numpy', on_device = 'cpu'

    @handle_frontend_test(
>       fn_tree="numpy.fmin",
        dtype_x1_x2_axis=helpers.dtype_values_axis(
            available_dtypes=helpers.get_dtypes("float"),
            min_num_dims=1,
            valid_axis=True,
            force_int_axis=True,
            large_abs_safety_factor=2,
            safety_factor_scale="log",
        ),
        where=np_frontend_helpers.where(),
    )

ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dtype_x1_x2_axis = (['float16'], [array([-1.], dtype=float16)], 0), frontend = 'numpy'
test_flags = num_positional_args=1. with_out=False. inplace=False. native_arrays=[False]. as_variable=[False]. 
fn_tree = 'ivy.functional.frontends.numpy.fmin', on_device = 'cpu', where = [array([False])]

    @handle_frontend_test(
        fn_tree="numpy.fmin",
        dtype_x1_x2_axis=helpers.dtype_values_axis(
            available_dtypes=helpers.get_dtypes("float"),
            min_num_dims=1,
            valid_axis=True,
            force_int_axis=True,
            large_abs_safety_factor=2,
            safety_factor_scale="log",
        ),
        where=np_frontend_helpers.where(),
    )
    def test_numpy_fmin(
        dtype_x1_x2_axis,
        frontend,
        test_flags,
        fn_tree,
        on_device,
        where,
    ):
>       input_dtypes, x1, x2, axis = dtype_x1_x2_axis
E       ValueError: not enough values to unpack (expected 4, got 3)
E       Falsifying example: test_numpy_fmin(
E           dtype_x1_x2_axis=(['float16'], [array([-1.], dtype=float16)], 0),
E           where=[array([False])],
E           fn_tree='ivy.functional.frontends.numpy.fmin',
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           frontend='numpy',
E           on_device='cpu',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.68.2', b'AXicY2BkAAMoBacBAEcABA==') as a decorator on your test case

ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py:82: ValueError
______________________________________________ test_numpy_fmin[cpu-ivy.functional.backends.jax-False-False] _______________________________________________

frontend = 'numpy', on_device = 'cpu'

    @handle_frontend_test(
>       fn_tree="numpy.fmin",
        dtype_x1_x2_axis=helpers.dtype_values_axis(
            available_dtypes=helpers.get_dtypes("float"),
            min_num_dims=1,
            valid_axis=True,
            force_int_axis=True,
            large_abs_safety_factor=2,
            safety_factor_scale="log",
        ),
        where=np_frontend_helpers.where(),
    )

ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dtype_x1_x2_axis = (['float16'], [array([-1.], dtype=float16)], 0), frontend = 'numpy'
test_flags = num_positional_args=1. with_out=False. inplace=False. native_arrays=[False]. as_variable=[False]. 
fn_tree = 'ivy.functional.frontends.numpy.fmin', on_device = 'cpu', where = [array([False])]

    @handle_frontend_test(
        fn_tree="numpy.fmin",
        dtype_x1_x2_axis=helpers.dtype_values_axis(
            available_dtypes=helpers.get_dtypes("float"),
            min_num_dims=1,
            valid_axis=True,
            force_int_axis=True,
            large_abs_safety_factor=2,
            safety_factor_scale="log",
        ),
        where=np_frontend_helpers.where(),
    )
    def test_numpy_fmin(
        dtype_x1_x2_axis,
        frontend,
        test_flags,
        fn_tree,
        on_device,
        where,
    ):
>       input_dtypes, x1, x2, axis = dtype_x1_x2_axis
E       ValueError: not enough values to unpack (expected 4, got 3)
E       Falsifying example: test_numpy_fmin(
E           dtype_x1_x2_axis=(['float16'], [array([-1.], dtype=float16)], 0),
E           where=[array([False])],
E           fn_tree='ivy.functional.frontends.numpy.fmin',
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           frontend='numpy',
E           on_device='cpu',
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.68.2', b'AXicY2BkAAMoBacBAEcABA==') as a decorator on your test case

ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py:82: ValueError
___________________________________________ test_numpy_fmin[cpu-ivy.functional.backends.tensorflow-False-False] ___________________________________________

frontend = 'numpy', on_device = 'cpu'

    @handle_frontend_test(
>       fn_tree="numpy.fmin",
        dtype_x1_x2_axis=helpers.dtype_values_axis(
            available_dtypes=helpers.get_dtypes("float"),
            min_num_dims=1,
            valid_axis=True,
            force_int_axis=True,
            large_abs_safety_factor=2,
            safety_factor_scale="log",
        ),
        where=np_frontend_helpers.where(),
    )

ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py:63: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

dtype_x1_x2_axis = (['float16'], [array([-1.], dtype=float16)], 0), frontend = 'numpy'
test_flags = num_positional_args=1. with_out=False. inplace=False. native_arrays=[False]. as_variable=[False]. 
fn_tree = 'ivy.functional.frontends.numpy.fmin', on_device = 'cpu', where = [array([False])]

    @handle_frontend_test(
        fn_tree="numpy.fmin",
        dtype_x1_x2_axis=helpers.dtype_values_axis(
            available_dtypes=helpers.get_dtypes("float"),
            min_num_dims=1,
            valid_axis=True,
            force_int_axis=True,
            large_abs_safety_factor=2,
            safety_factor_scale="log",
        ),
        where=np_frontend_helpers.where(),
    )
    def test_numpy_fmin(
        dtype_x1_x2_axis,
        frontend,
        test_flags,
        fn_tree,
        on_device,
        where,
    ):
>       input_dtypes, x1, x2, axis = dtype_x1_x2_axis
E       ValueError: not enough values to unpack (expected 4, got 3)
E       Falsifying example: test_numpy_fmin(
E           dtype_x1_x2_axis=(['float16'], [array([-1.], dtype=float16)], 0),
E           where=[array([False])],
E           fn_tree='ivy.functional.frontends.numpy.fmin',
E           test_flags=FrontendFunctionTestFlags(
E               num_positional_args=1,
E               with_out=False,
E               inplace=False,
E        [...]

2023-03-16 07:42 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +    dtype_x1_x2_axis=helpers.dtype_values_axis2(
This seems to be an error right?
```suggestion
    dtype_x1_x2_axis=helpers.dtype_values_axis(
```

2023-03-16 07:43 UTC, kurshakuz commented
Could you create an issue for your PR, comment it to the corresponding To-Do list and link the issue to the PR as outlined in the Frontend APIs part of the [Open Tasks section](https://lets-unify.ai/ivy/contributing/open_tasks.html#open-tasks) in the docs as well?

2023-03-16 13:04 UTC, AryanSharma9917 commented
> Could you create an issue for your PR, comment it to the corresponding To-Do list and link the issue to the PR as outlined in the Frontend APIs part of the [Open Tasks section](https://lets-unify.ai/ivy/contributing/open_tasks.html#open-tasks) in the docs as well?

I created the issue and added it to to-do. Is there anything to do please guide me out.

2023-03-19 04:54 UTC, kurshakuz commented
@AryanSharma9917 your implementation is still producing following errors' https://github.com/unifyai/ivy/pull/11829#pullrequestreview-1343073859

Please fix it and then I can review your PR

2023-03-19 09:26 UTC, AryanSharma9917 commented
> @AryanSharma9917 your implementation is still producing following errors' [#11829 (review)](https://github.com/unifyai/ivy/pull/11829#pullrequestreview-1343073859)
> 
> Please fix it and then I can review your PR

Hi sir I made the changes I think keepdims argument was giving the error

2023-03-19 16:16 UTC, kurshakuz requested changes
Hey! This is looking good! Can you please finally run the test locally and show the passing test for your implementation? Thanks!

2023-03-20 16:23 UTC, AryanSharma9917 commented
> Hey! This is looking good! Can you please finally run the test locally and show the passing test for your implementation? Thanks!

Hello sir, sorry for this late reply but I am facing some problems with the local setup of ivy my docker was giving some issues and when I switched to GitHub codespace I am again facing some issues can you take a look and help me out? 
![image](https://user-images.githubusercontent.com/72792907/226403753-8659588e-6c43-49a6-92e3-e4ed281ac090.png)

2023-03-20 16:23 UTC, AryanSharma9917 commented
> > Hey! This is looking good! Can you please finally run the test locally and show the passing test for your implementation? Thanks!
> 
> Hello @kurshakuz  sir, sorry for this late reply but I am facing some problems with the local setup of ivy my docker was giving some issues and when I switched to GitHub codespace I am again facing some issues can you take a look and help me out? ![image](https://user-images.githubusercontent.com/72792907/226403753-8659588e-6c43-49a6-92e3-e4ed281ac090.png)

2023-03-21 19:10 UTC, AryanSharma9917 commented
> > > Hey! This is looking good! Can you please finally run the test locally and show the passing test for your implementation? Thanks!
> > 
> > 
> > Hello @kurshakuz  sir, sorry for this late reply but I am facing some problems with the local setup of ivy my docker was giving some issues and when I switched to GitHub codespace I am again facing some issues can you take a look and help me out? ![image](https://user-images.githubusercontent.com/72792907/226403753-8659588e-6c43-49a6-92e3-e4ed281ac090.png)

Hi @kurshakuz sir is there any way you can help me out, It would be very helpful.

2023-03-27 21:04 UTC, AryanSharma9917 commented
Heyy @kurshakuz could you please review my PR

2023-03-28 11:45 UTC, kurshakuz requested changes
Hey @AryanSharma9917! Sorry for a delay. I see that you are using Codespaces and are not able to run the tests. What I would suggest to you is to run the following pytest directly to test your implementation from the root of your Ivy folder:
```
pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py::test_numpy_fmin
```

It will show you the results of your tests. Currently it is failing due to following errors:
```
E   AttributeError: module 'ivy_tests.test_ivy.test_frontends.test_numpy.helpers' has no attribute 'dtypes_values_casting_2'
```

2023-04-01 12:09 UTC, AryanSharma9917 commented
> Hey @AryanSharma9917! Sorry for a delay. I see that you are using Codespaces and are not able to run the tests. What I would suggest to you is to run the following pytest directly to test your implementation from the root of your Ivy folder:
> 
> ```
> pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py::test_numpy_fmin
> ```
> 
> It will show you the results of your tests. Currently it is failing due to following errors:
> 
> ```
> E   AttributeError: module 'ivy_tests.test_ivy.test_frontends.test_numpy.helpers' has no attribute 'dtypes_values_casting_2'
> ```

Okey sir

2023-04-01 14:22 UTC, AryanSharma9917 commented
Heyy @kurshakuz I made the changes that were causing the error. Could you please review my PR again.

2023-04-03 14:44 UTC, kurshakuz requested changes
Hi! Your implemenation is still failing, can you please fix and run the test locally and show me the output that you get?

For reference, I would suggest you to take a look at the `dtypes_values_casting_dtype` helper that you used: https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py#L240

2023-04-03 14:44 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +        arrs_shapes=[((2, 3),), ((2, 3),)],
This line is causing your test to fail:

```
========================================================================= ERRORS =========================================================================
___________________ ERROR collecting ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py ____________________
ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py:64: in <module>
    dtypes_values_casting=np_frontend_helpers.dtypes_values_casting_dtype(
E   TypeError: dtypes_values_casting_dtype() got an unexpected keyword argument 'arrs_shapes'
-------------------------------------------------------------------- Captured stderr ---------------------------------------------------------------------
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
================================================================ short test summary info =================================================================
ERROR ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py - TypeError: dtypes_values_casting_dtype() got an unexpected keyword argument 'arrs_shapes'
```

2023-04-12 16:25 UTC, AryanSharma9917 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +        arrs_shapes=[((2, 3),), ((2, 3),)],
> This line is causing your test to fail:
> 
> ```
> ========================================================================= ERRORS =========================================================================
> ___________________ ERROR collecting ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py ____________________
> ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py:64: in <module>
>     dtypes_values_casting=np_frontend_helpers.dtypes_values_casting_dtype(
> E   TypeError: dtypes_values_casting_dtype() got an unexpected keyword argument 'arrs_shapes'
> -------------------------------------------------------------------- Captured stderr ---------------------------------------------------------------------
> No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
> ================================================================ short test summary info =================================================================
> ERROR ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py - TypeError: dtypes_values_casting_dtype() got an unexpected keyword argument 'arrs_shapes'
> ```

okey sir

2023-04-27 07:35 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-04 06:27 UTC, closed without merging

2023-05-04 06:27 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.