Fliplr
unifyai/ivy pull request #11831
Opened 2023-03-06 19:47 UTC by ipriyam26

2023-03-06 19:51 UTC, ipriyam26 commented
closes https://github.com/unifyai/ivy/pull/11831

2023-03-08 08:22 UTC, MahmoudAshraf97 requested changes
`AssertionError:  the results from backend paddle and ground truth framework torch do not match`

Please fix the error and request another review when the hypothesis tests are passing
```
pytest -B paddle ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_manipulation.py::test_fliplr
```

2023-03-10 07:26 UTC, MahmoudAshraf97 approved these changes

2023-03-10 07:27 UTC, MahmoudAshraf97 approved these changes

2023-03-10 07:27 UTC, merged