append function
unifyai/ivy pull request #11838
Opened 2023-03-06 23:37 UTC by ndurumo254

2023-03-07 00:03 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/11769

2023-03-07 00:03 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/11772

2023-03-09 03:41 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/12018

2023-03-09 04:08 UTC, ndurumo254 commented
https://github.com/unifyai/ivy/issues/12019

2023-03-10 06:43 UTC, hirwa-nshuti requested changes
Hey @ndurumo254 

Sorry for the late review the implementations looks good only two functions with failing tests
* `nanstd`
*  `nanvar`
Fix them I'll merge the PR after their tests are passing😊

Thanks

2023-03-10 06:43 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_statistical.py
> +def test_numpy_nanvar(
This should be renamed to `test_jax_numpy_nanvar`

2023-03-10 06:43 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_statistical.py
> +def test_numpy_nanstd(
Should be renamed to `test_jax_numpy_nanstd`

2023-03-10 15:20 UTC, hirwa-nshuti approved these changes
LGTM!

2023-03-10 15:23 UTC, merged