Repair `torch.nn.functional.gelu` function
unifyai/ivy pull request #11985
Opened 2023-03-08 18:15 UTC by suvadityamuk

Repaired and added functionality for `approximate` kwarg. All tests now pass locally. This function is required in order to transpile some models from `timm`

2023-03-09 10:53 UTC, fspyridakos requested changes
I suggested a change to the code, please also add `approximate` to the test since it not being tested currently. Should be `approximate = st.sampled_from(["none", "tanh"])`

2023-03-09 10:53 UTC, fspyridakos commented on ivy/functional/frontends/torch/nn/functional/non_linear_activation_functions.py
> +    return ivy.gelu(input, approximate=approximate)
```suggestion
def gelu(input, approximate='none'):
    if approximate is 'none':
        return ivy.gelu(input, approximate=False)
    elif approximate is 'tanh':
        return ivy.gelu(input, approximate=True)
    else:
        raise ivy.utils.exceptions.IvyException(
             "approximate argument must be either none or tanh."
        )
```

2023-03-15 18:47 UTC, suvadityamuk commented on ivy/functional/frontends/torch/nn/functional/non_linear_activation_functions.py
> +    return ivy.gelu(input, approximate=approximate)
Have incorporated this, thank you!

2023-03-16 10:26 UTC, fspyridakos commented
LGTM

2023-03-16 10:27 UTC, merged