ApproximateEqual
unifyai/ivy pull request #12008
Opened 2023-03-09 00:23 UTC by shreyjain26

2023-03-09 16:27 UTC, juliagsy requested changes
Hello! Great work so far! However, there are some required arguments missing in the tests, I've added hints as comments. Once you're done with the changes, please request my review again, thanks!

2023-03-09 16:27 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +        x=x[0],
please also add the arguments `y` and `tolerance`, hints on data generation will be added as another comment

2023-03-09 16:27 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +    dtype_and_x=helpers.dtype_and_values(
to generate 2 arrays, add the parameter: `num_arrays=2`

as the types of the arrays for this function have to be the same, please add this parameter too: `shared_dtype=True`

2023-03-09 16:27 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +    )
then you'll be able to do `y=x[1]` here

2023-03-09 16:27 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +    ),
data for tolerance can be generated such as: `tol=st.floats(1e-05, 1e-03)`

2023-03-09 16:27 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +    frontend,
please remember to add `tol` in the list after generating the data

2023-03-09 16:27 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +    )
then you can do `tolerance=tol` here after generating the data

2023-03-09 17:20 UTC, shreyjain26 commented
I made the changes but the lint test is still failing.

2023-03-09 20:40 UTC, juliagsy requested changes
Hello! Great work so far! The tests are not passing unfortunately due to a few more additions required! Btw, there is an import error in the workflow and tests are not being run in the workflow, so please run the tests locally and make sure that they are passing!

PS: I was meant to say that because of an issue in our workflow, though there are green ticks in the intelligent tests, there actually isn't any tests being run, so the ticks are not accurate as of now! Please do run them locally and verify that they are passing correctly! Thanks a lot!

2023-03-09 20:40 UTC, juliagsy commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +    ret = ivy.abs(x-y)
the lint failures may be caused by this, it needs spaces in between like `x - y`, but this is not a major issue as I think we have a workflow for fixing this, feel free to push a fix though :)

2023-03-09 20:40 UTC, juliagsy commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +def ApproximateEqual(
there is a list of limited accepted `dtypes` for this function, please check the docs for more info: https://www.tensorflow.org/api_docs/python/tf/raw_ops/ApproximateEqual

then add the `@with_unsupported_dtypes` accordingly

2023-03-10 14:44 UTC, shreyjain26 commented
@juliagsy I'm getting two fails after putting in `with_unsupported_dtypes`

2023-03-10 19:19 UTC, juliagsy requested changes
Hello! Thanks for the great work! I've left some suggestions in the comments! As usual, please request my review again when you're done! Thanks a lot!

2023-03-10 19:19 UTC, juliagsy commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +            "bool",
only `float16` and `bool` is necessary here, the others may be removed. please also add `bfloat16`, the tests should be passing after that, but please verify it again locally!

2023-03-12 02:41 UTC, shreyjain26 commented
I ran the test locally and I got this error 
![image](https://user-images.githubusercontent.com/68336956/224521074-7f1e222e-912e-4a84-924d-64ab9a32cb54.png)
Also, I realised that my environment is different from ivy's as mine is python 3.10 while ivy is using 3.8.10 I think that may alter my results.
![image](https://user-images.githubusercontent.com/68336956/224521172-a2e77c93-5d07-49f9-97ac-201178b1bbec.png)
Locally, the lint check/flask8 is passing but here it isn't.

2023-03-12 13:13 UTC, juliagsy reviewed
Hey there! Thanks for the changes! For the lint checks, it may be other parts of the repo failing and not related to your changes, so don't worry about that!

Not sure if it is related, but please remove any changes related to the `.idea` folder, please only keep the changes related to the function you are working on in this PR!

EDIT: I've also tried out the tests and they're working good for me! Once the `.idea` related changes are removed, we'll be able to merge this PR in general! As usual, please request my review again once the changes are done! Thanks so much!

2023-03-12 14:05 UTC, shreyjain26 commented
@juliagsy There was a change in .idea when I pushed from pycharm directly. But I had already corrected it 11 hours ago. The .idea files in my pr and unifyai: master are identical.

2023-03-12 14:11 UTC, shreyjain26 commented
In my other pull requests where I haven't made any changes in .idea file, even in those only lint is failing rest all tests are passing.

2023-03-12 14:11 UTC, juliagsy approved these changes
oh! it was only an end of file difference, apologies for overlooking it, my bad! thanks for contributing!

2023-03-12 14:11 UTC, merged

2023-03-12 14:55 UTC, shreyjain26 commented
Thanks a lot for the help 😄