Fix the Import behaviour of nvidia-ml-py ( pynvml )
unifyai/ivy pull request #12124
Opened 2023-03-10 07:44 UTC by sagewhocodes

This PR fixes the Import behaviour of `pynvml` to only be imported in case of GPU enabled environments.

2023-03-10 07:55 UTC, Dsantra92 commented on ivy/functional/ivy/device.py
> +
merge into one try statement? `pynvml_installed` can be skipped.

2023-03-11 06:04 UTC, Dsantra92 requested changes
I have one thing to add here:
We need to check if intelligent tests are run on GPU. If not, we can safely remove pyvnml installation. I think @RashulChutani can help us here.

2023-03-11 06:04 UTC, Dsantra92 commented on ivy/functional/ivy/device.py
> +    # nvidia-ml-py (pynvml) is not installed in CPU Dockerfile.
Could you add a warning or throw an import error when GPU is present but pynvml is not installed? I feel it's better to show import warnings during initialization, than during actual work.

2023-03-11 06:21 UTC, RashulChutani commented
> I have one thing to add here:
> We need to check if intelligent tests are run on GPU. If not, we can safely remove pyvnml installation. I think @RashulChutani can help us here.

They are not currently run on GPU. We will be extending to GPUs soon but we will pass the GPU using the --device argument.

2023-03-11 12:06 UTC, Dsantra92 approved these changes
LGTM

2023-03-13 04:19 UTC, VedPatwardhan approved these changes
lgtm!

2023-03-13 07:35 UTC, RashulChutani approved these changes
Looks good to me!

2023-03-13 14:23 UTC, CatB1t reviewed
Just looking at the git  blame, the import seems to be there for a little while, also `pynvml` is listed in the requirements but it fails these days, maybe worth looking why it started failing recently? some tests internally use `pynvml` so the try except block won't be really helpful in making sure these doesn't run.

2023-03-13 14:29 UTC, sagewhocodes commented
> Just looking at the git blame, the import seems to be there for a little while, also `pynvml` is listed in the requirements but it fails these days, maybe worth looking why it started failing recently?

We actually made changes to the CPU Dockerfile such that it excludes nvidia based packages while building the CPU only version, however `pynvml` was always imported regardless if there was a GPU found or not. 
I have run tests under `ivy_tests` folder and didn't find any related errors, do I need to run tests from some other directory too?

2023-03-13 14:35 UTC, CatB1t approved these changes
lgtm!

2023-03-13 15:14 UTC, merged