Avg pool
unifyai/ivy pull request #12388
Opened 2023-03-13 14:51 UTC by shreyjain26

Close #12011

2023-03-14 01:42 UTC, shreyjain26 commented
@AnnaTz Could you please review this.

2023-03-14 14:40 UTC, AnnaTz requested changes

2023-03-14 14:40 UTC, AnnaTz commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +    return ivy.avg_pool1d(
Judging from `AvgPool`'s documentation it seems that it actually does 2d average pooling, so you'd need to call `ivy.avg_pool2d`.

2023-03-14 14:40 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +    x_k_s_p=helpers.arrays_for_pooling(min_dims=3, max_dims=3, min_side=1, max_side=4),
and since we need 2d pooling, I think `min_dims` and ``max_dims` should be 4.

2023-03-14 14:40 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +    data_format=df(data_format=st.sampled_from(["NHWC"])),
Supported values for `data_format` are "NHWC" and "NCHW". Also it's redundant to use a composite function here. You could do `data_format=st.sampled_from(["NHWC", "NCHW"]),`.

2023-03-14 14:40 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +        value=x[0],
I think `x` is an array so `value=x,`.

2023-03-15 15:42 UTC, shreyjain26 commented
I've made the changes.

2023-03-15 16:57 UTC, AnnaTz commented
> I've made the changes.

I think there are some requested changes that have not been fully resolved. Please have a look at my comment above.

2023-03-15 17:09 UTC, shreyjain26 commented
> I think there are some requested changes that have not been fully resolved. Please have a look at my comment above.

My bad. I've corrected it.

2023-03-20 11:48 UTC, AnnaTz commented
Hi @shreyjain26, there's been a force push in our repository so you'll have to create a new PR. Please refer to this [link](https://discord.com/channels/799879767196958751/983684937712558080/1080080255387189318).

2023-03-28 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-04 06:25 UTC, closed without merging

2023-04-04 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.