#12433
unifyai/ivy pull request #12434
Opened 2023-03-14 14:23 UTC by ndurumo254

2023-03-14 14:23 UTC, ndurumo254 commented
close #12433

2023-03-14 14:23 UTC, ndurumo254 commented
##12433

2023-03-14 15:35 UTC, ndurumo254 commented
#12433

2023-03-14 18:00 UTC, hirwa-nshuti requested changes
Hey 

Just few changes are needed, will merge then😊

Thanks

2023-03-14 18:00 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_searching_sorting.py
> +        available_dtypes=helpers.get_dtypes("float"),
We should test for all numeric dtypes I am sure that this function should support it

2023-03-14 18:28 UTC, hirwa-nshuti approved these changes
LGTM!
Going to merge

2023-03-14 18:29 UTC, merged

2023-03-15 07:48 UTC, ndurumo254 commented
close #12436