Grammatically upgrated the tech docs
unifyai/ivy pull request #12479
Opened 2023-03-15 11:40 UTC by H3c7o4

Small grammatical updates to the Ivy tech docs.

![pull-request.png](https://github.com/H3c7o4/Microships-projects/blob/master/pull-request.png)

2023-03-16 03:40 UTC, VedPatwardhan requested changes
Just a small change, rest looks good to merge 🙂

2023-03-16 03:40 UTC, VedPatwardhan commented on README.rst
> +It is important to keep in mind that Ivy is still in its early stages of development, and there may be breaking changes and rough edges before the release of version 1.2.0 in the coming weeks. If you
If this line is meant to replace some other lines such as 93-94 and 98-100, the old ones can be removed

2023-03-20 19:51 UTC, zaeemansari70 commented
Take a look at this announcement, I hope this resolves it :slightly_smiling_face: 
https://discordapp.com/channels/799879767196958751/983684937712558080/1080080255387189318

2023-05-26 00:07 UTC, zaeemansari70 commented
Closing due to inactivity for more than 2 months :slightly_smiling_face:

2023-05-26 00:07 UTC, closed without merging