Add activation functions in jax.nn module
unifyai/ivy pull request #12502
Opened 2023-03-15 16:16 UTC by karalleyna

2023-03-16 11:39 UTC, fspyridakos requested changes
Great PR, just some suggeted changes, please remove duplicates in particular and update the docstrings. I'll take another look once you're done. Thanks!

2023-03-21 18:25 UTC, karalleyna commented on ivy/functional/frontends/torch/nn/functional/non_linear_activation_functions.py
> +    # ret = ivy.divide(ivy.minimum(ivy.maximum(ivy.add(input, 3), 0), 6), 6)
Done

2023-03-21 18:35 UTC, karalleyna commented on ivy/functional/ivy/experimental/activations.py
> +def sigmoid(
Removed

2023-03-21 18:49 UTC, karalleyna commented on ivy/functional/ivy/experimental/activations.py
> +def softplus(
Removed

2023-03-21 18:49 UTC, karalleyna commented on ivy/functional/ivy/experimental/activations.py
> +def leaky_relu(
Removed

2023-03-29 15:19 UTC, AnnaTz commented
Hi @karalleyna, could you please re-make this PR? It can't get merged as it is now because of the force-push.

2023-06-20 07:44 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 05:53 UTC, closed without merging

2023-06-28 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.