Updated docstring with relevant error raise and examples
unifyai/ivy pull request #12549
Opened 2023-03-16 15:44 UTC by John-Aradan

- Added a Type error raise in case of input is not an array-like object.
- Added thorough examples for the working of the function

2023-03-17 10:22 UTC, fspyridakos commented
Hey, thanks for your contribution, could you also update the docstrings in the array, container and backend instances of this function?

2023-03-17 19:09 UTC, John-Aradan commented
@fspyridakos 
#12544 

Updates made as requested:

- 
Added docstring for unique_value: array instance
- Added docstring for unique_value: container instance
- Added docstring for unique_value: numpy frontend instance
- Added docstring for unique_value: torch frontend instance
- Added docstring for unique_value: tensorflow frontend instance
- Added docstring for unique_value: jax frontend instance

2023-03-19 16:01 UTC, John-Aradan commented
@ivy-seed  Please assign a reviewer for my pull request.

2023-03-21 22:01 UTC, fspyridakos requested changes
Looks really good. I must apologize though for not being clear before, the backend variations don't actually need docstrings, they just need the typehints to be correct, which they seem like they already are, could you please remove them? Apologies again

2023-03-22 08:35 UTC, John-Aradan commented on ivy/array/set.py
> +        >>> print(y)
Its fine 😊 I will get into it right away

2023-03-22 08:38 UTC, John-Aradan commented on ivy/array/set.py
> +        >>> print(y)
@fspyridakos  I have made the necessary changes as asked for. Requesting for a re-review.

2023-03-22 10:31 UTC, John-Aradan commented
@fspyridakos I have made the necessary changes as asked for. Requesting for a re-review.

2023-03-22 15:16 UTC, fspyridakos commented
Looks good, there seems to be some conflicting changes. Please resolve them and then I'll push 😊

2023-03-22 19:27 UTC, John-Aradan commented
@fspyridakos I have resolved the merge conflict. Please review 😊

2023-03-23 03:11 UTC, fspyridakos commented
LGTM! Thanks for your contribution!

2023-03-23 03:11 UTC, merged

2023-03-23 05:03 UTC, John-Aradan commented
Thankyou ☺️ But, in the subtask set.py unique_values is still not marked as complete