fft2
unifyai/ivy pull request #12556
Opened 2023-03-16 17:51 UTC by Ali-Ibtehaj-Asif-Niazi

2023-03-16 17:52 UTC, Ali-Ibtehaj-Asif-Niazi commented
Hi, I have some questions

2023-03-19 12:47 UTC, juliagsy requested changes
Hello! Apologies if the PR is not ready yet, but just thought that I'd leave some side notes first so that you're in the right direction! The comments are left below, thanks again for the hard work!

2023-03-19 12:47 UTC, juliagsy commented on ivy/functional/frontends/numpy/fft/discrete_fourier_transform.py
> +import numpy as np
native numpy should not be a dependency in the ivy frontend

2023-03-19 12:47 UTC, juliagsy commented on ivy/functional/frontends/numpy/fft/discrete_fourier_transform.py
> +    return np.fft.fft2(x, s=s, axes=axes, norm=norm)
numpy native fit function should not be used here

2023-03-19 12:47 UTC, juliagsy commented on ivy/functional/frontends/numpy/fft/discrete_fourier_transform.py
> +    a = ivy.array(fft2_layer(a, s=s, axes=axes, norm=norm), dtype=ivy.complex128)
you may either complete this function as a composition of other functions, or in other cases, propose the `fft2` function to be added to the ivy functional API if you see fit, more information here in the section! 
https://lets-unify.ai/ivy/contributing/open_tasks.html#frontend-apis

2023-03-19 12:47 UTC, juliagsy commented on ivy/functional/frontends/numpy/fft/discrete_fourier_transform.py
> +        s: Optional[Tuple[int, int]] = None,
typehints are not required in the frontend

2023-03-19 12:47 UTC, juliagsy commented on ivy/functional/frontends/numpy/fft/discrete_fourier_transform.py
> +from typing import Optional, Tuple
this is then not needed as type hints are not required here

2023-03-20 08:25 UTC, closed without merging