random_uniform
unifyai/ivy pull request #1257
Opened 2022-05-31 13:30 UTC by rnwzd

2022-06-10 07:34 UTC, chie2727 requested changes

2022-06-10 07:34 UTC, chie2727 commented on ivy/functional/ivy/random.py
> +        device on which to create the array 'gpu:0', 'gpu:1', 'cpu' etc.
You can change this part back to `'cuda:0', 'cuda:1', 'cpu' etc. `

Also in a new line, please include: ` (Default value = None)` just like in Line 226.

2022-06-10 10:51 UTC, chie2727 requested changes
Hi @rnwzd ,
Please also include an Instance Method example for ivy.Container instances.

For example:
https://github.com/unifyai/ivy/blob/2045db570d7977830681a7498a3c1045fb5bcc79/ivy/functional/ivy/elementwise.py#L234

Also please leave 1 line of space between each example. You also need to organize them under the `Functional Examples` and `Instance Method Examples` headings.

2022-06-10 11:39 UTC, rnwzd commented
> 

 I am sorry but I don't see which argument accepts container instances.

2022-06-10 12:55 UTC, chie2727 commented
You can try placing `ivy.random_uniform()` into a container and generate an example from this

2022-06-14 03:35 UTC, chie2727 commented
Also, for your reference have a look at the Docstring Examples guide to get an idea of the overall layout
https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html

2022-06-24 05:35 UTC, chie2727 requested changes

2022-06-24 05:35 UTC, chie2727 commented on ivy/functional/ivy/random.py
Thanks for all the edits!

As this function has 4 input parameters, you need a minimum of 4 types of functional example variations.
So could you include 1 more example that takes maybe 2 parameters.
After that you should be done!

2022-06-24 05:36 UTC, chie2727 commented
Thanks for all the edits!

As this function has 4 input parameters, you need a minimum of 4 types of functional example variations.
So could you include 1 more example that takes maybe 2 parameters.

After that you should be done!

2022-06-24 05:37 UTC, chie2727 requested changes
.

2022-06-24 09:08 UTC, rnwzd reviewed
ok.
SHould be fixed now.
At the moment the button to request a review is not working though.

2022-06-26 09:47 UTC, chie2727 approved these changes

2022-06-26 09:49 UTC, chie2727 commented
Thanks for adding in the last example. I'll merge in your changes now.

2022-06-26 09:50 UTC, merged