Codespace tanyalondon musical succotash 5rxpvp957gw2vqx9
unifyai/ivy pull request #12770
Opened 2023-03-19 23:51 UTC by tanyalondon

Added tf frontend function expm1, original openIssue 12362.  Your review/comments are greatly appreciated. Thank you

2023-03-28 06:30 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-03-28 11:48 UTC, tanyalondon commented
HiIm still waiting for a review for this. I have not received any comments or review on my code in this PR.

Tanya 
 
  On Tue, 28 Mar 2023 at 7:30, ***@***.***> wrote:   


This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-28 19:20 UTC, karalleyna commented on .ivy/key.pem
I believe it is added by mistake. Can you remove it?

2023-03-29 16:32 UTC, tanyalondon commented on .ivy/key.pem
Hi
What would like me to remove? Thank you

2023-03-31 21:31 UTC, tanyalondon commented on .ivy/key.pem
HI 

Please can you clarify? Thanks

2023-04-05 13:56 UTC, karalleyna commented on .ivy/key.pem
[.ivy/key.pem](https://github.com/unifyai/ivy/pull/12770/files/693665c1eea4e171f15cf34c41684f524b4d4bc1#diff-113901f497e09c1565797ce0a0529e7abef7561225ff7e2ad372ef8da387fc3d)

2023-04-07 06:56 UTC, tanyalondon commented on .ivy/key.pem
Hi
Have you reviewed my code? I do not see any comments.

2023-04-11 08:25 UTC, tanyalondon commented
Im still waiting for a review for this. I have not received any comments or review on my code in this PR.

Sent from Yahoo Mail on Android 
 
  On Tue, 11 Apr 2023 at 7:26, ***@***.***> wrote:   


This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-19 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-25 16:36 UTC, hirwa-nshuti requested changes
Hey would you remove the `.ivy` folder.

We will then get your PR merged😊

2023-04-26 13:00 UTC, tanyalondon commented
Hi key.pem now deleted.  thank you

2023-04-26 13:03 UTC, tanyalondon commented
Hi  ivy folder with key.pem deleted.  thank you

2023-04-26 16:08 UTC, tanyalondon commented
Hi.
That's done -
Commits merged. 

Thank you

2023-04-28 02:39 UTC, hirwa-nshuti approved these changes
Looks good to me!
Thanks for contributing😊

2023-04-28 02:41 UTC, merged

2023-04-28 04:18 UTC, tanyalondon commented
Thank you!!

Sent from Yahoo Mail on Android 
 
  On Fri, 28 Apr 2023 at 3:41, Felix Hirwa ***@***.***> wrote:   


Merged #12770 into master.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>