Adding multi_dot to pytorch frontend
unifyai/ivy pull request #12830
Opened 2023-03-21 04:22 UTC by abdulasiraj

closes #11952

2023-03-21 05:31 UTC, abdulasiraj commented
Hi @ZoeCD,
This PR is ready for review. Can you please have sometime?

2023-03-24 05:27 UTC, abdulasiraj commented
Hi @ZoeCD,
Sorry for disturbing again. Couldn't you find sometime?

2023-03-24 14:25 UTC, ZoeCD requested changes
There are some conflicting files, so please update your branch to resolve them. Other than those minor details, looks good to me!

2023-03-24 14:25 UTC, ZoeCD commented on ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py
> +    # test_gradients=st.just(False),
Could you please remove the comment?

2023-03-24 14:25 UTC, ZoeCD commented on ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py
> +def test_multi_dot(
Also, could you please change the test signature to follow the style of the others? `test_torch_multi_dot`

2023-03-28 20:01 UTC, ZoeCD requested changes
You forgot to delete the commented line. And the test is failing now, I guess hypothesis found an edge case or something. This is the failure message `AssertionError:  the results from backend tensorflow and ground truth framework torch do not match`
Could you please check that out? You can see more information in the details section of the failing intelligent tests

2023-03-29 14:10 UTC, abdulasiraj commented
I have checked it. The problem is with underlying function defined in back end API. Because I'm just wrapping the function.

2023-04-02 18:46 UTC, merged