added unravel_index
unifyai/ivy pull request #12876
Opened 2023-03-21 17:57 UTC by rajshukla1102

Close #10421

2023-03-21 17:59 UTC, rajshukla1102 commented
@hirwa-nshuti hey I am trying to resolve unit test but for every backend test I am getting the error
`AssertionError: The length of results from backend jax and ground truthframework numpy does not match` can you help me in this?

2023-03-21 18:36 UTC, hirwa-nshuti commented
Hey @rajshukla1102 

It is likely an issue with how we are handling 0-d arrays when testing I'll look into this tomorrow😊
Meanwhile, once other backend tests are passing I'll get the PR merged

Thanks

2023-03-21 19:23 UTC, rajshukla1102 commented
@hirwa-nshuti Sure! Thankyou😊

2023-03-22 14:06 UTC, hirwa-nshuti requested changes
Hey @rajshukla1102 

The tests seems to be failing due to this tuple you introduced try to remove it and use `ivy.unravel_index` only

Thanks

2023-03-23 08:57 UTC, rajshukla1102 commented on ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py
> +    return tuple(np.asarray(x, dtype=np.int64) for x in ret)
I have added the changes you requested please do check once! Thankyou!

2023-03-23 14:33 UTC, hirwa-nshuti requested changes
Hey @rajshukla1102 

The tests are failing due to dtype of returned indices which seems to be `int32`
You must change it to `int64`.

Thanks

2023-03-24 21:51 UTC, rajshukla1102 commented
> The tests are failing due to dtype of returned indices which seems to be `int32` You must change it to `int64`.

you mean casting indices to int64? 
actually I have tried to cast indices to int64 then passed indices to unravel_index but it didn't work although!

2023-03-27 09:23 UTC, hirwa-nshuti commented
> > The tests are failing due to dtype of returned indices which seems to be `int32` You must change it to `int64`.
> 
> you mean casting indices to int64? actually I have tried to cast indices to int64 then passed indices to unravel_index but it didn't work although!

I meant something like this:
```python
ret = [x.astype("int64") for x in ivy.unravel_index(indices, shape)]
return tuple(ret)
   
```

2023-03-27 19:18 UTC, rajshukla1102 commented
@hirwa-nshuti I have made changes!

2023-03-29 14:30 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py
> +import numpy as np
This should be removed

2023-03-29 14:51 UTC, rajshukla1102 commented
@hirwa-nshuti I have deleted the file and also removed unused import! Please look at it once.
Thankyou🙂

2023-03-29 15:56 UTC, hirwa-nshuti commented
Hey @rajshukla1102 

if you check here the `.idea` changes are still there https://github.com/unifyai/ivy/pull/12876/files

2023-03-29 17:13 UTC, rajshukla1102 commented
@hirwa-nshuti Due to some issue I have referenced a new PR to this.  #13380

2023-03-29 17:13 UTC, closed without merging