implemented tensnorflow avg_pool1d
unifyai/ivy pull request #12899
Opened 2023-03-22 08:24 UTC by ajithpious

pr for #11775

2023-03-22 11:03 UTC, ajithpious commented
@kurshakuz could you please review my pr.

2023-03-23 11:56 UTC, kurshakuz requested changes
Hey! Thank you for your contribution!

Your implementation currently fails for one of the tests:
```
E           AssertionError:  the results from backend torch and ground truth framework tensorflow do not match
E            [[[-1.        ]
E             [-0.33333334]
E             [ 0.33333334]]]!=[[[-1.        ]
E             [-0.33333334]
E             [ 0.        ]]] 
E           
E           
E           Falsifying example: test_tensorflow_avg_pool1d(
E               data_format='NWC',
E               x_k_s_p=(['float32'], [array([[[-1.],
E                         [-1.],
E                         [ 1.]]], dtype=float32)], (3,), (1,), 'SAME'),
E               test_flags=FrontendFunctionTestFlags(
E                   num_positional_args=0,
E                   with_out=False,
E                   inplace=False,
E                   as_variable=[False],
E                   native_arrays=[False],
E               ),
E               fn_tree='ivy.functional.frontends.tensorflow.nn.avg_pool1d',
E               frontend='tensorflow',
E               on_device='cpu',
E           )
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2BiAAJGBghgRGbDGCA2E4QDAAEvAAw=') as a decorator on your test case

ivy_tests/test_ivy/helpers/assertions.py:53: AssertionError
```

2023-03-25 11:04 UTC, ajithpious commented
> Hey! Thank you for your contribution!
> 
> Your implementation currently fails for one of the tests:
> 
> ```
> E           AssertionError:  the results from backend torch and ground truth framework tensorflow do not match
> E            [[[-1.        ]
> E             [-0.33333334]
> E             [ 0.33333334]]]!=[[[-1.        ]
> E             [-0.33333334]
> E             [ 0.        ]]] 
> E           
> E           
> E           Falsifying example: test_tensorflow_avg_pool1d(
> E               data_format='NWC',
> E               x_k_s_p=(['float32'], [array([[[-1.],
> E                         [-1.],
> E                         [ 1.]]], dtype=float32)], (3,), (1,), 'SAME'),
> E               test_flags=FrontendFunctionTestFlags(
> E                   num_positional_args=0,
> E                   with_out=False,
> E                   inplace=False,
> E                   as_variable=[False],
> E                   native_arrays=[False],
> E               ),
> E               fn_tree='ivy.functional.frontends.tensorflow.nn.avg_pool1d',
> E               frontend='tensorflow',
> E               on_device='cpu',
> E           )
> E           
> E           You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2BiAAJGBghgRGbDGCA2E4QDAAEvAAw=') as a decorator on your test case
> 
> ivy_tests/test_ivy/helpers/assertions.py:53: AssertionError
> ```

Hi @kurshakuz, the tensorflow  avg_pool1d frontend function uses the functional api implemented in ivy\functional\ivy\experimental\layers.py . I tested the same API with different frontends and the results are different. I think this is causing the frontend to fail.
Code to repro:
a = [[[-1.], [-1.], [1.]]]
xnp = np.array(a)
xtf = tf.Variable(a)
xtch = torch.tensor(a)
print(ivy.avg_pool1d(xtf, 3, 1, "SAME"))
print(ivy.avg_pool1d(xtch,3,1,"SAME"))
print(ivy.avg_pool1d(xtf,3,1,"SAME"))

The outputs are different for the same input. Could you please have a look into this.

2023-03-28 11:41 UTC, kurshakuz requested changes
You are correct, outputs should not be different. I would sugges you to raise your issue in the corresponding Discord channel in case someone faced the same problem.

I also tried to run your implementation locally, and it seems to be producing incorrect results.

```
E           AssertionError:  the results from backend torch and ground truth framework tensorflow do not match
E            [[[-1.       ]
E             [-1.       ]
E             [-1.       ]]
E           
E            [[-1.       ]
E             [-1.3333334]
E             [-1.6666666]]]!=[[[-1.       ]
E             [-1.       ]
E             [-1.       ]]
E           
E            [[-1.       ]
E             [-1.3333334]
E             [-1.5      ]]] 

```

2023-04-05 19:34 UTC, ajithpious commented
Hi @kurshakuz, the issue has been fixed in one of the commits and all the test cases are passing.

2023-04-07 13:04 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_nn.py
> +    data_format=df(data_format=st.sampled_from(["NWC"])),
```
NameError: name 'df' is not defined
```

2023-04-27 07:35 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-04 06:27 UTC, closed without merging

2023-05-04 06:27 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.