Added floor function to numpy frontend
unifyai/ivy pull request #12948
Opened 2023-03-22 19:15 UTC by RakshitKumar04

Close https://github.com/unifyai/ivy/pull/12948

2023-03-22 19:16 UTC, RakshitKumar04 commented
Close #12948

2023-03-22 19:18 UTC, RakshitKumar04 commented
@hirwa-nshuti Created the new PR and added the floor function, please review it.

2023-03-23 14:26 UTC, hirwa-nshuti requested changes
Hey @RakshitKumar04 

Thanks for contributing to ivy😊

Here are general comments for this implementation:

* You need to import this private function in the init file of the numpy frontend: https://github.com/unifyai/ivy/blob/6c29acd94482e341148a629df523cf966d02aa4b/ivy/functional/frontends/numpy/__init__.py#L518

* You'll need to initialize ufunc object here in the same init file: https://github.com/unifyai/ivy/blob/6c29acd94482e341148a629df523cf966d02aa4b/ivy/functional/frontends/numpy/__init__.py#L676

You'll then fix the test issues refer to the comments below
Thanks

2023-03-23 14:26 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_rounding.py
> +    fn_tree="ivy.floor",
fn_tree should be `numpy.floor`

2023-03-23 17:32 UTC, RakshitKumar04 commented
Hey, @hirwa-nshuti fixed the testing issues, please review.

2023-03-23 17:38 UTC, RakshitKumar04 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_rounding.py
> +    fn_tree="ivy.floor",
Resolved the conflict

2023-03-24 11:31 UTC, hirwa-nshuti requested changes
Hey @RakshitKumar04 

The tests are failing due to wrong implementation of the unit test 🙂
Would you follow the unit test of `ceil` function above to understand anover view as the tests will be somehow alike😊

Thanks

2023-03-25 10:33 UTC, RakshitKumar04 commented
> Hey @RakshitKumar04
> 
> The tests are failing due to wrong implementation of the unit test slightly_smiling_face Would you follow the unit test of `ceil` function above to understand anover view as the tests will be somehow alikeblush
> 
> Thanks

Hey, did the changes you suggested, Please review

2023-03-27 04:00 UTC, hirwa-nshuti approved these changes
Looks good!

Going to merge
Thanks for contributing😊

2023-03-27 04:01 UTC, merged

2023-03-27 12:00 UTC, RakshitKumar04 commented
> Looks good!
> 
> Going to merge Thanks for contributingblush

Thank you @hirwa-nshuti for helping me contribute to ivy.