add tf.linalg.diag func frontend
unifyai/ivy pull request #12989
Opened 2023-03-23 03:13 UTC by Sindhuinti

2023-03-23 03:14 UTC, Sindhuinti commented
Close https://github.com/unifyai/ivy/issues/11750

2023-03-23 03:16 UTC, Sindhuinti commented
Hey @hirwa-nshuti review this PR.

2023-03-23 15:02 UTC, Sindhuinti commented on ivy/functional/frontends/tensorflow/linalg.py
> +    return ivy.diag(a, k=k)
required changes made

2023-03-24 11:35 UTC, hirwa-nshuti requested changes
Hey @Sindhuinti 

The tests now are failing for all backends would you look into this😊

Thanks

2023-03-24 16:55 UTC, hirwa-nshuti commented
> Is there any error in my code regarding test fail ?

Would you run the tests locally to see if they pass on your end?

2023-04-04 11:24 UTC, hirwa-nshuti requested changes
Would you fix the merge conflicts to rerun the tests here on CI

2023-04-27 07:35 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-04 06:27 UTC, closed without merging

2023-05-04 06:27 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.