added instance for prod
unifyai/ivy pull request #13044
Opened 2023-03-24 05:06 UTC by AkshayC2001

Close #13043

2023-03-24 11:51 UTC, hirwa-nshuti requested changes
Hey @AkshayC2001 

The unit tests are failing try checking if your data generation is correct😊
You need to generate castable dtypes for backends kindly do checkout this example to have an overview https://github.com/unifyai/ivy/blob/3cef1bba6b7abb4fd9d66d7933bff442aa87c9c1/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_sums_products_differences.py#L77

Thanks

2023-03-24 11:51 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +    def compress(self, value, *, axis=None):
This should be removed

2023-03-24 12:24 UTC, AkshayC2001 commented
> Hey @AkshayC2001 
> 
> The unit tests are failing try checking if your data generation is correct😊
> You need to generate castable dtypes for backends kindly do checkout this example to have an overview https://github.com/unifyai/ivy/blob/3cef1bba6b7abb4fd9d66d7933bff442aa87c9c1/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_sums_products_differences.py#L77
> 
> Thanks

Maybe because I have added compress by mistake. I will try removing it

2023-03-27 08:47 UTC, hirwa-nshuti requested changes
Hey @AkshayC2001 

The tests are failing due to that you're not generating `keepdims` you need to add it in test example generation.
After that try to run tests locally from your end and fix any error that will come up
Thanks😊

2023-03-27 10:14 UTC, AkshayC2001 commented
ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py this test is giving error. so this function is working fine i guess. can you confirm this

2023-03-27 10:19 UTC, AkshayC2001 commented
> Hey @AkshayC2001
> 
> The tests are failing due to that you're not generating `keepdims` you need to add it in test example generation. After that try to run tests locally from your end and fix any error that will come up Thanks😊

I will do. Thank you

2023-03-27 10:43 UTC, AkshayC2001 commented
hello @hirwa-nshuti 
are all tests supposed to pass except lint/check-formatting?

2023-03-27 10:52 UTC, AkshayC2001 commented
hello @hirwa-nshuti,
do i have added both keepdims and intials generations but still tests are not passing.

2023-03-27 14:09 UTC, AkshayC2001 commented
Hello @hirwa-nshuti 
Tests were passing locally but it is failing here. Can you check the code

2023-03-27 17:44 UTC, hirwa-nshuti requested changes
Hey @AkshayC2001 

The problem is mainly with the way that you're generating tests examples which is resulting into overflow. Kindly refer to the tests of the numpy fronted function here https://github.com/unifyai/ivy/blob/59e6f8fd57978501724dcb6425709171e1368584/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_sums_products_differences.py#L77

And do check the comments below.
Thanks

2023-03-27 17:44 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/helpers.py
> +        where = ivy.array(where[0], dtype='bool')
This one should be reverted

2023-03-27 17:50 UTC, AkshayC2001 commented
> Hey @AkshayC2001
> 
> The problem is mainly with the way that you're generating tests examples which is resulting into overflow. Kindly refer to the tests of the numpy fronted function here
> 
> https://github.com/unifyai/ivy/blob/59e6f8fd57978501724dcb6425709171e1368584/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_sums_products_differences.py#L77
> 
> And do check the comments below. Thanks

hello @hirwa-nshuti thank you for the reply. 
this is the error i am getting while locally running test

TypeError: Cannot cast array data from dtype('uint8') to dtype('bool') according to the rule 'safe'

so i had to explicitly convert 'where' array to 'bool'.
I have referred backend function and i have done the same implementation in frontend. still getting these errors.
Thank you

2023-03-27 17:54 UTC, AkshayC2001 commented
hello @hirwa-nshuti 
it seems like my solution worked and all tests are passing.
please can you review the code? 
Thank you

2023-03-27 17:59 UTC, hirwa-nshuti commented
> hello @hirwa-nshuti it seems like my solution worked and all tests are passing. please can you review the code? Thank you

The problem is that your solution might work but it will break other things while the test of this method is possible simple to modify following the example I shared with you.

2023-03-27 18:02 UTC, hirwa-nshuti approved these changes
Looks good now!

Going to merge😊
Thanks for contributing

2023-03-27 18:02 UTC, merged