added instance method for add
unifyai/ivy pull request #13042
Opened 2023-03-24 04:45 UTC by AkshayC2001

Close #13041

2023-03-27 16:29 UTC, juliagsy requested changes
Hey there! Apologies for the delay in reviewing! I've left the comments below, please request my review again when you're done with the changes! Thanks a lot!

2023-03-27 16:48 UTC, AkshayC2001 commented on ivy/functional/frontends/tensorflow/tensor.py
> +    def __add__(self, y, name="add"):
hello @juliagsy is this correct?

2023-03-28 11:07 UTC, juliagsy reviewed
Hey! Apologies for this but I just realised, the `add` instance method actually doesn't exist in `tensorflow` itself, so we should not be including this in the the ivy frontend too. This method is not present in the ToDo list as well: https://github.com/unifyai/ivy/issues/3616
The `__add__` method is ticked in the todo list so that shouldn't be chosen as it is completed, could you please select a different function/method to work on as this is not a valid one, thanks a lot!

2023-03-28 12:05 UTC, AkshayC2001 commented
I'll do thank you

2023-03-28 12:05 UTC, closed without merging