Added histogramdd function
unifyai/ivy pull request #13175
Opened 2023-03-25 22:56 UTC by nomeshkumar

- [ ] #12703

2023-03-26 12:30 UTC, hmahmood24 requested changes
Hey @nomeshkumar!
Thanks for an awesome contribution! I have left some comments and requested some changes. Kindly look into those. There are also a few points I want to mention that you overlooked in your implementation. 

1. You are supposed to add implementations in the `experimental` directories of not just all the Backend APIs and the Ivy Functional Experimental API, but also the **Array and Container** APIs as described [here](https://github.com/unifyai/ivy/issues/3856#issue-1356871035). You can look into [this](https://github.com/unifyai/ivy/pull/7462/files) PR for example as a reference so you know where else you need to add implementations of your function.
2. There are some linting and formatting checks that your PR is failing. Kindly look into those [here](https://github.com/unifyai/ivy/actions/runs/4521569029/jobs/7963383153?pr=13175) and fix them. I'm guessing you haven't installed `pre-commit` since it automatically runs all these checks whenever you commit your code and push it. I suggest you [set up](https://lets-unify.ai/ivy/overview/contributing/setting_up.html#pre-commit) `pre-commit` in your local environment and [run](https://lets-unify.ai/ivy/overview/deep_dive/formatting.html#pre-commit-hook) these linting and formatting checks because otherwise the CI tests will fail every time you submit a PR that has linting and formatting issues.
3. You have placed your test in the wrong directory. They are supposed to go in the `ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_statistical.py` directory. I'm guessing you didn't run the tests locally because `pytest` would have thrown an error otherwise. Kindly always make sure that you run all your tests locally and ensure that they pass for ALL backends because otherwise the CI tests will fail when you submit a PR. 

Once you've made all the requested changes and ensured that the tests are running fine, kindly re-request a review from me. Good luck! 😊

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/backends/numpy/experimental/statistical.py
> +        bins: Optional[Union[Tuple[int],int,Tuple[float]]] = 10,
The type hinting for generic arguments that do not involve any native elements should be the same across each file

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/backends/tensorflow/experimental/statistical.py
> +        input: Union[tf.Tensor, tf.Variable],
The input can only be a `tf.Tensor`

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/backends/torch/experimental/statistical.py
> +        weights : torch.tensor,
You cannot define non-default arguments after default arguments. Please provide a default value for `weights`

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/ivy/experimental/statistical.py
> +        a: Union[ivy.Array, ivy.NativeArray],
Rename this to `input` as you've done in all the other files

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/ivy/experimental/statistical.py
> +        (instead of 1). Must be of the same shape as a.
Change `a` to `input`

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/ivy/experimental/statistical.py
> +    a
Change `a` to `input`

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/backends/tensorflow/experimental/statistical.py
> +) -> Union[tf.Tensor, tf.Variable]:
Kindly keep the return type consistent in all files. Remove `tf.Variable` and add `Tuple` in the beginning instead like you have done in other files.

2023-03-26 12:30 UTC, hmahmood24 commented on ivy/functional/ivy/experimental/statistical.py
> +) -> ivy.Array:
Kindly keep the return type consistent across all files.

2023-03-26 12:33 UTC, hmahmood24 commented
Also just a small point. Kindly ensure that your PRs gets linked to the issue(s) you are trying to resolve by commenting: `Close #<issue_number>` as explained [here](https://lets-unify.ai/ivy/overview/contributing/the_basics.html#todo-list-issues). This just helps in keeping track of tasks that have been carried out and correctly closing any issues that should be closed once the PR gets merged. Thank you! 😊

2023-03-27 05:15 UTC, nomeshkumar commented
@hmahmood24 Thank you so much for your review, I'll fix these issues and let you know.

2023-04-02 20:02 UTC, nomeshkumar commented
Close #12703

2023-04-02 20:08 UTC, nomeshkumar commented
Hey @hmahmood24 , I have made all changes that you mentioned in comments except implementation of function in **Array and Container APIs**  because I couldn't find these folders in master branch

2023-04-03 18:02 UTC, hmahmood24 commented
> Hey @hmahmood24 , I have made all changes that you mentioned in comments except implementation of function in **Array and Container APIs** because I couldn't find these folders in master branch

Hey @nomeshkumar, The Array and Container APIs are located [here](https://github.com/unifyai/ivy/tree/master/ivy/data_classes). You'll need to implement your function in the `experimental` directories of both these modules as implemented in the reference PR I attached last time. 🙂

2023-04-03 18:26 UTC, nomeshkumar commented
> > Hey @hmahmood24 , I have made all changes that you mentioned in comments except implementation of function in **Array and Container APIs** because I couldn't find these folders in master branch
> 
> Hey @nomeshkumar, The Array and Container APIs are located [here](https://github.com/unifyai/ivy/tree/master/ivy/data_classes). You'll need to implement your function in the `experimental` directories of both these modules as implemented in the reference PR I attached last time. 🙂

Okay thanks @hmahmood24

2023-04-04 21:06 UTC, nomeshkumar commented
Close #12703

2023-04-07 09:15 UTC, nomeshkumar commented
@hmahmood24 Kindly review the updates

2023-04-07 10:01 UTC, hmahmood24 requested changes
I have reviewed the changes and left comments and changes for you to address. Again,

1. You have placed the test in the wrong directory. It will go in `ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_statistical.py` file.
2. You have copied over the docstring from one file into all the other files. They should be modified according to each file/class they are being placed in. Please look at the docstrings of methods/functions in each file to get an idea of how to modify the docstrings in these files.
3. I don't think you have gone through my points [here](https://github.com/unifyai/ivy/pull/13175#pullrequestreview-1358000490). I can see plenty of linting/formatting issues with the PR. I also know that the tests would be failing since the test was not placed in the required file. Some of the functions had missing arguments as well. If you go over what I said [here](https://github.com/unifyai/ivy/pull/13175#pullrequestreview-1358000490), you need to fix all these formatting issues as well as make sure you run the test for **ALL** backends and make it pass so that we can go ahead and merge the PR.

Please run your tests locally using `pytest` as explained in my first comment at the top of this page as well as fix the formatting issues using `pre-commit` as mentioned in that same comment above. I won't be able to merge your PR if the tests aren't ran and verified to be passing. Good luck!

2023-04-27 07:35 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-04 06:26 UTC, closed without merging

2023-05-04 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.