Adding fill diagonal function and test
unifyai/ivy pull request #13231
Opened 2023-03-27 06:44 UTC by abdulasiraj

closes  #13065

2023-03-27 06:46 UTC, abdulasiraj commented
I'm facing some issues regarding generating hypothesis inputs for test function. Any help or hint would be highly appreciated.
Thanks!

2023-04-02 15:24 UTC, Fayad-Alman requested changes
Hi @abdulasiraj, sorry for the late response!

Everything looks good so far, just one thing. On your forked branch, make sure you update the changes made to the files you edited.

Once you've updated the files, add the changes you made and send another review so I can properly check the commits.

Thanks for your contributions!

2023-04-06 02:47 UTC, Fayad-Alman requested changes
Hi @abdulasiraj,
For the file test_indexing_like_operations.py, it seems you deleted the function max_value_as_shape_prod. This function is required for the unravel_index test and thus is causing multiple tests to fail. 
Could you please restore that function? Just copy the function in the ivy repository and paste it into your forked repository in the correct file.
Many thanks,
Fayad

2023-04-06 02:50 UTC, Fayad-Alman requested changes

2023-04-06 02:50 UTC, Fayad-Alman commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> -    return dtype_and_x, shape
This function is required for the unravel_index test to work.

2023-04-07 02:30 UTC, abdulasiraj commented
Hi @Fayad-Alman,
Sorry for inconvenience. I think the problem is with hypothesis data generation. Can you please point that out?

Thanks in advance!

2023-04-07 06:36 UTC, abdulasiraj commented
I got the problem. Array manipulation function was missing. let me fix that

2023-04-07 18:45 UTC, Fayad-Alman approved these changes
Seems like most of the errors are coming from outside of the changes you made, so I'll go ahead and merge the new commits. Good work!

2023-04-07 18:46 UTC, merged