formatted docstring for bitwise_xor in ivy backend
unifyai/ivy pull request #1336
Opened 2022-06-06 12:46 UTC by abundance-io

- [ ] #761

2022-06-08 08:27 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +    `docstring <https://data-apis.org/array-api/latest/API_specification/generated/signatures.elementwise_functions.add.html>`_ # noqa
Update URL

2022-06-08 08:48 UTC, chie2727 requested changes
_Changes requested_

2022-06-10 07:39 UTC, chie2727 requested changes
Hi @abundance-io ,
Thanks for making the changes.
You need one more functional example in the `With :code: 'ivy.Array' input` section that updates the input array by using either `out=a` or `out=b`.

See Line 142 for reference: https://github.com/unifyai/ivy/blob/b0832f862245b12f9338442df696c058cb450ab1/ivy/functional/ivy/elementwise.py#L142

2022-06-11 00:12 UTC, chie2727 requested changes
Just need to make a few edits to the formatting and you'll be done

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +    >>> y = ivy.bitwise_xor(a,b)
`a = ivy.array([1,2,3])` -> `a = ivy.array([1, 2, 3])`
`b = ivy.array([3,2,1])` -> `b = ivy.array([3, 2, 1])`
`y = ivy.bitwise_xor(a,b)` -> `y = ivy.bitwise_xor(a, b)`

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +    >>> ivy.bitwise_xor(a,b,out=y)
`a = ivy.array([78,91,23])` -> `a = ivy.array([78, 91, 23])`
`b = ivy.array([66,77,88])` -> `b = ivy.array([66, 77, 88])`
`ivy.bitwise_xor(a,b,out=y)` -> `ivy.bitwise_xor(a, b, out=y)`

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +    >>> ivy.bitwise_xor(a,b,out = a)
-> `a = ivy.array([1, 2, 3])`
-> `b = ivy.array([3, 2, 1])`
-> `ivy.bitwise_xor(a, b, out=a)`

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +        ivy.array([[ 4,  6, 89, 26, 57]])
-> `([0, 1, 3, 67, 91])`
-> `([4, 7, 90, 89, 98])`
-> `(a, b)`

-> `([[4, 6, 89, 26, 57]])`

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete these 2 line-spaces

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete these 2 line-spaces

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +    Using :code: `ivy.Array` instance method:
Add a line-space above here

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +    With :code:`ivy.Array` instances:
Add a line-space above here

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +
Delete this line-space

2022-06-11 00:12 UTC, chie2727 commented on ivy/functional/ivy/elementwise.py
> +    >>> a = ivy.array([0,1,3,67,91])
Go through all the remaining arrays and correct the spacing for them too!

2022-06-13 01:40 UTC, chie2727 commented
Hi @abundance-io , let me know when you've finished making edits to the line-spacing and array spacing.

2022-06-13 12:37 UTC, abundance-io commented
I've corrected all the lines you mentioned 
and corrected the spacing for the arrays 

i'm not sure what's left 
is there something i'm missing?

2022-06-14 03:32 UTC, chie2727 commented
@abundance-io 
I was referring to any remaining double-line spaces as I cannot mention them all. Please change the rest to single-line spaces.

As for the array spacing, for numbers you have typed as `3,4,5` and `a,b,out = a` for example, simply change the spacing to `3, 4, 5` and `a, b, out=a`.
Very minor changes, but it's ideal to keep the formats all consistent.

2022-06-16 15:06 UTC, abundance-io commented
I'm done correcting everything 
sorry for taking so long

2022-06-17 08:24 UTC, merged