fixed issue
unifyai/ivy pull request #13380
Opened 2023-03-29 17:12 UTC by rajshukla1102

Close https://github.com/unifyai/ivy/issues/10421

2023-03-29 17:14 UTC, rajshukla1102 commented
@hirwa-nshuti look into once. Thankyou!

2023-03-29 21:30 UTC, Dsantra92 requested changes
Numpy converts each value to int64. You might want to cast each value in the tuple to int64. It should fix the current tests.

2023-03-29 21:30 UTC, Dsantra92 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +import numpy as np
Is is required here?

2023-03-29 22:31 UTC, rajshukla1102 reviewed
@Dsantra92 I have made the changes. please look into it once.

2023-03-31 17:29 UTC, rajshukla1102 commented
@zhumakhan Thanks for the review but currently I think ivy is not supporting orders. It is the reason I didn't add support. Thank you!

2023-03-31 17:44 UTC, zhumakhan commented
Yeah, you are right.
Lets merge then!

2023-03-31 17:47 UTC, merged