lerp #12985
unifyai/ivy pull request #13399
Opened 2023-03-30 00:04 UTC by plapacz6

lerp #12985
Can I have a review code please.
I'm stuck on a test issue for tensorflow backend
Can I ask for any suggestions.

As a model backend I chose torch, due to the fact that the lerp function is only available in this framework.
I limited the available float data types to two in the tests.
The function is a mix function. Only backed torch has native support.

thank you in advance

2023-04-01 14:18 UTC, plapacz6 commented
[lerp #12985](https://github.com/unifyai/ivy/pull/13399#top)#13399
![image](https://user-images.githubusercontent.com/83856031/229294429-aacb8c39-7e11-4c87-9b1b-13bea0bcd91b.png)
on my repository
tests : .../test_elementwise.py::test_lerp
for the lerp function all pass already.

Please let me know if PR is suitable for merging or if I should improve something.

2023-04-04 08:28 UTC, MahmoudAshraf97 commented on ivy/functional/ivy/experimental/elementwise.py
> +    <https://pytorch.org/docs/stable/generated/torch.lerp.html>
```suggestion
```

2023-04-04 08:30 UTC, MahmoudAshraf97 requested changes
Good work, I think you need to revise the handling of the mixed functions this is handled using the handle_mixed_function decorator in func_wrapper. If I'm not mistaken, there should be an attribute on the method in the Functional API like so: func.mixed_function = True and the @handle_mixed_function decorator would be applied on the backend implementation with which you want to decide on choosing the primary implementation or the composition one. For example: https://github.com/unifyai/ivy/blob/9affbccde21f522db09cde254c77466086b7aaa9/ivy/functional/backends/tensorflow/experimental/layers.py#L407-L412 (the backend implementation) and https://github.com/unifyai/ivy/blob/9affbccde21f522db09cde254c77466086b7aaa9/ivy/functional/ivy/experimental/layers.py#L1418 (the functional attribute setting) 

also change the dtypes in the tests as suggested and if there are any errors fix them, other than that we are ready to merge

2023-04-04 08:30 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_elementwise.py
> +        available_dtypes=["float32", "float64"],
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```

2023-04-05 00:02 UTC, plapacz6 commented
Thank you for the tips. I changed the available types in the test as suggested. I added the @handle_mixed_function decorator in the backend functions. I'm not sure if I correctly handled the cases where the output for the function is not valid. If anything needs to be changed, please let me know

2023-04-06 12:08 UTC, MahmoudAshraf97 requested changes
LGTM, will merge after the requested changes

2023-04-06 12:08 UTC, MahmoudAshraf97 commented on ivy/functional/ivy/experimental/elementwise.py
> +        weight = ivy.astype(weight, "float64")
Supposedly these variables are arrays,, so you need to check for the dtype of the array not if it's and instance,, that's if there is a needed check at all needed

2023-04-07 01:25 UTC, plapacz6 commented
Thanks for the hint. Type checking has grown a bit spatially. Not sure if I didn't complicate it too much. If anything needs to be changed, please let me know.

2023-04-11 12:56 UTC, MahmoudAshraf97 approved these changes

2023-04-11 12:56 UTC, merged