added zeta in paddle elementwise.py
unifyai/ivy pull request #13409
Opened 2023-03-30 06:16 UTC by vandit98

zeta #13408

2023-03-30 08:30 UTC, MahmoudAshraf97 requested changes
don't forget the unsupported ditypes decorator, uint16 and `bfloat16` are unsupported in all functions, and if there are more dtypes that you cant support, add them accordingly
```
@with_unsupported_device_and_dtypes(
    {"2.4.2 and below": {"cpu": ("uint16", "bfloat16")}}, backend_version
)
```
also the result is different than the ground truth, this is also a problem in the numpy implementation where this is derived from, so you will need to rethink this again
```
E           AssertionError:  the results from backend paddle and ground truth framework tensorflow do not match
E            [2.]!=[1.64493407] 
E           
E           
E           Falsifying example: test_zeta(
E               dtype_and_x=(['float64', 'float64'], [array([2.]), array([1.])]),
```

2023-03-30 08:52 UTC, vandit98 commented on ivy/functional/backends/paddle/experimental/elementwise.py
> +    n, res = 1, 1 / q**x
yes, I agree 
I will make the changes.

2023-04-03 08:22 UTC, vandit98 commented
hi @MahmoudAshraf97 
Please review my changes. Test are passing.
![Screenshot from 2023-04-03 13-52-22](https://user-images.githubusercontent.com/91458535/229453085-02dffd68-399a-46c3-8092-fdea7ef39829.png)

I have used jax implementation and also we need to update numpy backend zeta function.
I will be happy to do it as well.
Thanks

2023-04-03 21:45 UTC, MahmoudAshraf97 approved these changes
Good work

2023-04-03 21:45 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/elementwise.py
> +        N = M = np.float64(8) if q.dtype == np.float32 else np.float64(16)
please review this

2023-04-03 21:46 UTC, merged