Frontend np percentile
unifyai/ivy pull request #13404
Opened 2023-03-30 04:10 UTC by pradyyadav

close #10534

2023-03-30 04:57 UTC, pradyyadav commented
dependent on PR  #13401

2023-03-31 19:43 UTC, Daniel4078 requested changes
Hello! I know that we can not check the actural behavior of your frontend implementation. please for now just fix the small formatting error below.

2023-03-31 19:43 UTC, Daniel4078 commented on ivy/functional/frontends/numpy/statistics/order_statistics.py
> +    return ret
please do not forget to have one empty line at the end of each files!

2023-03-31 19:48 UTC, pradyyadav commented
@Daniel4078, thank you for your review, but as per ivy documentation, the frontends are supposed to follow their respective docs for easy to understand and refactor. I see that percentile is implemented at order statistics, please find the link: https://numpy.org/doc/stable/reference/routines.statistics.html. Please correct me if I got something wrong.

2023-03-31 19:55 UTC, Daniel4078 commented
> @Daniel4078, thank you for your review, but as per ivy documentation, the frontends are supposed to follow their respective docs for easy to understand and refactor. I see that percentile is implemented at order statistics, please find the link: https://numpy.org/doc/stable/reference/routines.statistics.html. Please correct me if I got something wrong.

you are very correct! then can you also try check if there is any other Order statistics function that is placed in the wrong place? Thanks!

2023-03-31 19:57 UTC, pradyyadav commented
> > @Daniel4078, thank you for your review, but as per ivy documentation, the frontends are supposed to follow their respective docs for easy to understand and refactor. I see that percentile is implemented at order statistics, please find the link: https://numpy.org/doc/stable/reference/routines.statistics.html. Please correct me if I got something wrong.
> 
> you are very correct! then can you also try check if there is any other Order statistics function that is placed in the wrong place? Thanks!

Sure I would be happy to do it. However Daniel, I need some help with the dependent PR. Would you like to voluntarily review it?

2023-03-31 20:09 UTC, Daniel4078 commented
I just cleared the current assignee for that pull request of yours, the bot will soon get you a new assignee that is more responsive I hope.

2023-04-13 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-13 15:00 UTC, Daniel4078 commented
@pradyyadav How is your other pull request going?

2023-04-21 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-11 06:26 UTC, closed without merging

2023-05-11 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.