add standard_exponential to numpy frontend
unifyai/ivy pull request #13422
Opened 2023-03-30 09:13 UTC by Aneesh02

Closes #13418

2023-04-05 14:59 UTC, YushaArif99 commented on ivy/functional/frontends/numpy/random/functions.py
> +    return ivy.gamma(1.0, beta, dtype="float64")
are you sure the `standard exponential` function in Numpy behaves identically to the `gamma` function? Numpy provides both these functions separately so shouldn't there must be some difference?

2023-04-05 15:02 UTC, YushaArif99 requested changes
Hi @Aneesh02 

Some of the tests for `test_standard_exponential` seem to be failing in the CI. You can view the detailed error log [here](https://github.com/unifyai/ivy/actions/runs/4597860171/jobs/8121118846?pr=13422)

Can you kindly fix these tests and re-request a review. Thanks! 🙂 

```

2023-04-21 05:39 UTC, Aneesh02 commented
Still working on it!

2023-06-08 04:02 UTC, YushaArif99 commented
Hey @Aneesh02 

Since there has been no activity on this PR for over a month now, I'll be closing this PR 🙂

2023-06-08 04:02 UTC, closed without merging