fmin numpy frontend
unifyai/ivy pull request #13595
Opened 2023-04-01 20:09 UTC by AgnesLL

Close #13594

2023-04-12 09:52 UTC, AgnesLL commented
@karalleyna could you review this when you are free? Thanks.

2023-04-20 06:27 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-25 16:09 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +    dtype_and_inputs=helpers.dtype_and_values(
Hey here we will use `np_frontend_helpers.dtypes_values_casting_dtype` to generate the casting dtypes as well

2023-05-23 11:15 UTC, hirwa-nshuti requested changes
Would you solve the merge conflicts😊

2023-05-25 07:52 UTC, AgnesLL commented
> Would you solve the merge conflicts😊

fixed

2023-05-31 05:49 UTC, hirwa-nshuti requested changes
Hey @AgnesLL 
This function is a ufunc instance its testing should be handled the same way as other ufuncs, would you take a reference on `minimum` unit test.
Thanks

2023-06-22 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-02 05:52 UTC, closed without merging

2023-07-02 05:52 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.