uint8, int32 and int64 support for 'gather' in paddle backend
unifyai/ivy pull request #13622
Opened 2023-04-02 14:10 UTC by czirabence

Close #12592

2023-04-03 16:16 UTC, czirabence commented
> I don't really follow what you've done here, can you explain to me your steps?

This is a correction for my previous pull request #12950, which added gather to paddle backend. Paddle.gather supports dtypes of uint8, int32, int64, float32 and float64 on cpu, according to the [paddlepaddle reference](ttps://www.paddlepaddle.org.cn/documentation/docs/en/2.2/api/paddle/gather_en.html#gather). However, when functional.ivy.gather with paddle backend was given uint8 type array inputs, the following error was raised: ivy.utils.exceptions.IvyBackendException: paddle: gather: (NotFound) The kernel with key (CPU, NCHW, uint8) of kernel `slice` is not registered. To overcome this, 4 list comprehensions inside ivy.functional.bakcends.paddle.gather were replaced with paddle.split. I also removed int32 and int64 from unsupported_devices_and_dtypes, because they are supported.

2023-04-03 21:27 UTC, MahmoudAshraf97 requested changes
Good work
the correct usage would be `paddle.unbind` instead of `split`, while both of them return the correct result, the shape is different because `split` keeps the axis that you split on while `unbind` removes that axis which is the desired behavior, and since unbind doesn't support a lot of dtypes, you can use `ivy.unstack` under `ivy.ArrayMode(False)`
btw try to extend to all dtypes except bfloat and uint16

2023-04-04 15:05 UTC, czirabence commented
Thank you,
Paddle functions were replaced with ivy functions in the second commit, and data casting for unsupported types was added, which I copied from backends.paddle.unstack.

2023-04-06 10:05 UTC, MahmoudAshraf97 approved these changes
Great work overall

2023-04-06 10:05 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/general.py
>      batch_dims = batch_dims % paddle.Tensor.ndimension(params)
```suggestion
    axis = axis % params.ndim
    batch_dims = batch_dims % params.ndim
```

2023-04-06 10:06 UTC, merged