Add jax.random.poisson frontend
unifyai/ivy pull request #13695
Opened 2023-04-03 21:35 UTC by MuhammedAshraf2020

closes #13483

2023-04-07 02:38 UTC, zaeemansari70 requested changes
Hey @MuhammedAshraf2020! 
Thank you so much for contributing to ivy! 🙂

Your PR looks amazing ✨!
Just requested a few changes and left comments on them which needs to be addressed! 🙂

Do let me know if you have any other questions!
Thanks!

2023-04-07 02:38 UTC, zaeemansari70 commented on ivy/functional/frontends/jax/random.py
> +@handle_jax_dtype
It's failing for 'uint32' for tensorflow, kindly look into this

2023-04-07 02:38 UTC, zaeemansari70 commented on ivy/functional/frontends/jax/random.py
> +def _get_seed(key):
As your previous PR is merged this is a duplicate function, remove this

2023-04-08 19:34 UTC, MuhammedAshraf2020 commented
@zaeemansari70, 
can you check now please ?

2023-04-14 07:57 UTC, sherry30 requested changes
Hi,

Your PR looks good, can you fix the merge conflicts?
There's also 1 lint error which you'll have to fix.
I'll merge your PR as soon you make these changes. 😄 

Thanks

2023-04-14 22:42 UTC, MuhammedAshraf2020 commented
@sherry30 
can you merge now please ?

2023-04-18 03:42 UTC, sherry30 approved these changes
Looks good,
Thanks a lot for the contribution 😄

2023-04-18 03:43 UTC, merged