array_str()
unifyai/ivy pull request #13747
Opened 2023-04-05 12:44 UTC by Sarvesh-Kesharwani

Closes #11961

1) for handing supress_small parameter.
2) to check the default parameter state of function.

2023-04-10 14:53 UTC, juliagsy requested changes
Hey! Great work so far! I've commented the involved Ivy API below, thanks for the hard work!

2023-04-10 14:53 UTC, juliagsy commented on ivy/functional/frontends/jax/numpy/creation.py
> +        precision = ivy.get_printoptions()['precision']
we have `ivy.array_significant_figures()` as an equivalent

2023-04-10 14:53 UTC, juliagsy commented on ivy/functional/frontends/jax/numpy/creation.py
> +        max_line_width = ivy.get_printoptions()['linewidth']
we don't have a function for this yet but you can hardcode it as `75` for the time being!

2023-04-10 14:53 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_creation.py
> +        shape=shape,
other than the default parameters for configuring the testing, the input parameters for testing the function should match the function

2023-04-27 07:43 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-03 17:36 UTC, juliagsy commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-05-03 17:36 UTC, closed without merging