Add non-linear activation fns to experimental API
unifyai/ivy pull request #13750
Opened 2023-04-05 13:33 UTC by karalleyna

2023-04-06 20:52 UTC, AnnaTz requested changes

2023-04-06 20:52 UTC, AnnaTz commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_activations.py
> +# leaky_relu
Why is this commented out?

2023-04-06 20:52 UTC, AnnaTz commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_activations.py
> +        available_dtypes=helpers.get_dtypes("float", full=False, key="leaky_relu"),
probably can remove the `, full=False, key="leaky_relu"` part

2023-04-06 20:52 UTC, AnnaTz commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_activations.py
> +        available_dtypes=helpers.get_dtypes("float", full=False, key="leaky_relu"),
same here

2023-04-06 20:52 UTC, AnnaTz commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_activations.py
> +        available_dtypes=helpers.get_dtypes("float"),
Please make sure to add the necessary `with_supported_dtypes` decorators to all functions so that we can test for `get_dtypes("valid")`.

2023-04-06 20:54 UTC, AnnaTz commented
Great PR 🙂 I can't see the CI test though because of a weird numpy failure. I think you'll have to pull master to resolve that.

2023-04-14 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-21 06:26 UTC, closed without merging

2023-04-21 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.