solve triangular
unifyai/ivy pull request #13786
Opened 2023-04-06 12:36 UTC by anurag629

solve_triangular #10423

2023-04-07 06:37 UTC, Aarsh2001 requested changes
Kindly look at the changes below, thanks.

2023-04-07 06:37 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +    ),
hey @anurag629, small change. Please generate float values for `lower`, `transpose`, and `unit_diagonal`

2023-04-07 06:37 UTC, Aarsh2001 commented on ivy/functional/backends/torch/experimental/linear_algebra.py
> +    unitriangular: bool = False,
These are not the arguments you are returning from the `Ivy API`. Please make sure that the arguments are consistent across backends.

2023-04-07 06:37 UTC, Aarsh2001 commented on ivy/functional/backends/tensorflow/experimental/linear_algebra.py
> +    conjugate: bool = False,
You should either handle the `conjugate` argument in all backends or skip it completely.

2023-04-07 06:37 UTC, Aarsh2001 commented on ivy/functional/backends/numpy/experimental/linear_algebra.py
> +    trans: bool = False,
There is no such thing as `trans` being returned from the `Ivy API`. You are also returning `unit_diagonal` in the `Ivy API`, how are you handling it here?

2023-04-07 06:37 UTC, Aarsh2001 commented on ivy/functional/backends/jax/experimental/linear_algebra.py
> +    unit_diagonal: bool = False,
You are also returning `transpose` from the `Ivy API`. How are handling it here ??

2023-04-07 06:37 UTC, Aarsh2001 commented on ivy/functional/backends/torch/experimental/linear_algebra.py
> +    unitriangular: bool = False,
For example, where are the arguments `lower`, `unit_diagonal` and `transpose`.

2023-04-18 07:19 UTC, Aarsh2001 requested changes
Hey @anurag629 all looks good, just a small change ,thanks

2023-04-18 07:19 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +
It will be better if we do this in `handle_test` decorator 😅.

2023-04-26 09:34 UTC, anurag629 commented
Hey @Aarsh2001 please review this PR 😃

2023-05-01 05:20 UTC, Aarsh2001 requested changes

2023-05-01 05:20 UTC, Aarsh2001 commented on ivy/data_classes/container/experimental/linear_algebra.py
> +        b: Union[ivy.Container, ivy.Array, ivy.NativeArray],
This is a positional argument, should come before line `892`

2023-05-01 05:20 UTC, Aarsh2001 commented on ivy/data_classes/container/experimental/linear_algebra.py
> +        b: Union[ivy.Container, ivy.Array, ivy.NativeArray],
Same here

2023-05-01 07:07 UTC, anurag629 commented
Hey @Aarsh2001, why these tests are failing? :)

2023-05-01 07:34 UTC, Aarsh2001 requested changes

2023-05-01 07:34 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +    return input_dtype, [matrix_1[1][0], matrix_2[1][0]]
I feel we don't need this function here, you can simply use `dtype_and_values` and pass `num_arrays=2`. You can also use these keyword arguments for generating the shape values - 

``` 
min_num_dims
max_num_dims
min_dim_size
max_dim_size
```

2023-05-10 05:57 UTC, Aarsh2001 requested changes
hi @anurag, if you look at the test logs, you'll see that the value test fails for majority backends. Meaning, your implementation may not be consistent across backends and the ground truth backend tensorflow. I suggest you try to create a demo file in your local machine and run the failing example for all backends. You should verify that all the outputs match.

2023-05-25 09:55 UTC, MahmoudAshraf97 commented
Hi, @anurag629 are you still working on this?

2023-06-27 05:52 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-04 05:53 UTC, closed without merging

2023-07-04 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.