Re-structuring numpy indexing routine functions to their respective f…
unifyai/ivy pull request #13852
Opened 2023-04-08 03:27 UTC by abdulasiraj

All numpy indexing routine functions were in a single file but according to the numpy structure & contribution guidelines they should be in their respective files. So, I re-arranged the functions in to their respective files.

2023-04-12 05:00 UTC, hirwa-nshuti requested changes
Hey @abdulasiraj 

Thanks for bringing this up🙂
It makes sense, just a few changes are needed then we merge the PR😊

2023-04-12 05:00 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/indexing_routines/generating_index_arrays.py
> +def unravel_index(indices, shape, order="C"):
Can we keep this in `indexing_like_operations.py`

2023-04-21 07:04 UTC, abdulasiraj commented
sure

2023-04-25 09:44 UTC, abdulasiraj commented
Hi @hirwa-nshuti ,
But in the numpy file structure, unravel is in generating... file. Should i still follow your instruction?

2023-04-25 10:05 UTC, hirwa-nshuti commented
> Hi @hirwa-nshuti , But in the numpy file structure, unravel is in generating... file. Should i still follow your instruction?

Well let's leave it just like this only resolve the merge conflict I'll get the PR merged then

2023-04-25 10:46 UTC, hirwa-nshuti requested changes
Would you resolve the merge conflicts

2023-04-25 11:13 UTC, abdulasiraj commented
> We can't merge the PR with merge conflicts. Mostly it is due to changes added lately after you opened the PR. You'll have to resolve this by updating your branch to the master branch of Ivy🙂 https://lets-unify.ai/docs/ivy/overview/contributing/the_basics.html#managing-your-fork

Sure!

2023-04-25 11:56 UTC, abdulasiraj commented
Hi @hirwa-nshuti,
Can we have 5 meeting video chat??

2023-04-25 12:32 UTC, hirwa-nshuti commented
You'll have to run `./merge_with_upstream.sh numpy` and fix conflicts then push the changes.
If you face any issue do text me on discord we can continue the discussion there😊

2023-04-25 13:35 UTC, hirwa-nshuti approved these changes
LGTM!
Thanks for the PR🙂

2023-04-25 13:35 UTC, merged