added jax.numpy.pad function
unifyai/ivy pull request #13863
Opened 2023-04-08 10:42 UTC by x0axz

2023-04-12 19:19 UTC, x0axz commented
@zaeemansari70 please review this PR.

2023-04-14 07:38 UTC, sherry30 requested changes
Hi,

Your PR looks good, torch and tensorflow are currently failing but thats because of an unrelated problem with `scatter_nd`.
Just 1 thing I pointed out on the specific line.

Thanks

2023-04-14 07:38 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_manipulation.py
> +    reflect_type,
unused argument, was this by mistake? 🤔

2023-04-14 13:05 UTC, x0axz commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_manipulation.py
> +    reflect_type,
yes

2023-04-14 13:09 UTC, x0axz commented
@sherry30 Thanks for the review. Also, if you could, please review this PR too, as I am not getting any response from the assignee. https://github.com/unifyai/ivy/pull/13864
Thanks

2023-04-20 06:22 UTC, sherry30 approved these changes
lgtm!

2023-04-20 06:24 UTC, merged