Adding subtract to torch frontend
unifyai/ivy pull request #13995
Opened 2023-04-11 12:21 UTC by vtsamit

Close #13990

2023-04-20 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-24 15:43 UTC, kurshakuz requested changes
Thank you for your contribution! Implementation looks good to me, but please address the issues I mentioned

2023-04-24 15:43 UTC, kurshakuz commented on ivy/functional/frontends/torch/tensor.py
> +        return torch_frontend.subtract(self._ivy_array, other, alpha=alpha)
```suggestion
    @with_unsupported_dtypes({"1.11.0 and below": ("bfloat16",)}, "torch")
    def subtract(self, other, *, alpha=1):
        return torch_frontend.subtract(self, other, alpha=alpha)
```

2023-04-24 15:43 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +        allow_inf=False,
No need for this flag

2023-04-24 15:43 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +    alpha=st.floats(min_value=-1e04, max_value=1e04, allow_infinity=False),
Similarly no need to set `allow_infinity=False` here

2023-04-24 15:43 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +        max_value=1e04,
You can remove setting those values as well

2023-04-24 15:43 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +    alpha=st.floats(min_value=-1e04, max_value=1e04, allow_infinity=False),
Similarly no need to add min and max values here

2023-04-24 15:43 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +        atol_=1e-02,
Please remove that argument

2023-05-01 06:26 UTC, closed without merging

2023-05-01 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.