Added tf.diag frontend + test
unifyai/ivy pull request #14057
Opened 2023-04-12 16:08 UTC by mobley-trent

Closes #13868

2023-04-20 06:29 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-22 08:00 UTC, mobley-trent commented
Hi @zaeemansari70, I am requesting a code review 🙂.
I've implemented the test but I am getting this error:

```
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py::test_tensorflow_diag[cpu-ivy.functional.backends.numpy-False-False] - AttributeError: 'NoneType' object has no attribute 'backend'
FAILED ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py::test_tensorflow_diag[cpu-ivy.functional.backends.torch-False-False] - AttributeError: 'NoneType' object has no attribute 'backend'
```

Does this mean the backends are not yet implemented ?

2023-04-26 16:46 UTC, hirwa-nshuti commented on ivy/functional/frontends/tensorflow/linalg.py
> +@to_ivy_arrays_and_back
Hey @mobley-trent 

The function signature you used here is incorrect I guess given the documentation of this function it indicates that it should be defined as 
```python
def diag(
    diagonal,
    name='diag',
    k=0,
    num_rows=-1,
    num_cols=-1,
    padding_value=0,
    align='RIGHT_LEFT'
):
    pass
```
You can read more here https://www.tensorflow.org/api_docs/python/tf/linalg/diag

2023-04-27 16:44 UTC, mobley-trent commented
Hey @hirwa-nshuti I implemented the function with the appropriate parameters but I am getting the same error that I got beforehand

2023-05-10 18:18 UTC, AnnaTz commented
Hi @mobley-trent, I tried running your code locally and I don't get the `AttributeError: 'NoneType' object has no attribute 'backend'` that you mentioned. Are you getting the same when you try running other tests as well? If so, there is something wrong with your ide setup. Otherwise, I would suggest syncing with the latest master and trying again then.

2023-05-15 08:29 UTC, hirwa-nshuti requested changes
Hey @mobley-trent 

Good Job so far,
But there is a mismatch between the shapes of returned array and the ground truth one🙂
Would you look into that?

2023-05-15 16:33 UTC, mobley-trent commented
@hirwa-nshuti I actually had a question about the testing. The test case which is failing produces this array:
```
x = array([[0, 0],[0, 0]], dtype=int64)
k = 0
```

But when I test this input on the `diag` function I have implemented and `tf.linalg.diag`, they both produce the same array with shape `(2, 2, 2)` yet the error trace for the test failure indicates that my function returns an array of shape `(2, 3, 3)`. How is this so ? I tested the function in a Jupyter notebook to make sure that both the ground truth function and my implementation produce the same outputs.

2023-05-17 05:30 UTC, hirwa-nshuti requested changes
Hey @mobley-trent 

Now looks great but the tests for paddle backend are failing, fix this then we can merge this PR.

Great job done😊

2023-05-17 10:14 UTC, hirwa-nshuti approved these changes
Hey @mobley-trent 

Thanks for contributing😊
Going to merge

2023-05-17 10:15 UTC, merged