AvgPool
unifyai/ivy pull request #14079
Opened 2023-04-13 03:39 UTC by shreyjain26

Close #12011

2023-04-13 04:53 UTC, shreyjain26 commented
Hi @AnnaTz , could you please review this?

2023-04-13 11:22 UTC, AnnaTz requested changes

2023-04-13 11:22 UTC, AnnaTz commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +@to_ivy_arrays_and_back
Please add `@with_supported_dtypes`. You can read about this decorator [here](https://lets-unify.ai/docs/ivy/overview/deep_dive/data_types.html#supported-and-unsupported-data-types).

2023-04-13 11:22 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +        value=x,
This should be `x[0]`, since `x` is a list containing an array and we only want to pass the array itself.

2023-04-14 08:51 UTC, AnnaTz commented
There are still some errors you need to resolve. Kindle have a look at `intelligent-tests-pr / run_tests_1 (pull_request)` or run the test locally to debug.

2023-04-24 06:29 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-01 06:25 UTC, closed without merging

2023-05-01 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.