bucketize
unifyai/ivy pull request #14105
Opened 2023-04-13 10:39 UTC by Aneesh02

Closes #14083

2023-04-15 14:06 UTC, ZiadAmerr commented
Hi @Aneesh02, thanks for your contribution. I will leave a few comments on the code and we can continue with the merge after that :)

2023-04-15 14:41 UTC, ZiadAmerr commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +        available_dtypes=helpers.get_dtypes("float"),
Why are we restricting the arrays generated to float only? I suggest using `valid` instead

2023-04-15 14:44 UTC, ZiadAmerr commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +        max_num_dims=1,
Why are we restricting the number of dims to 1 only?

The following is an example from PyTorch's documentation

```
>>> boundaries = torch.tensor([1, 3, 5, 7, 9])
>>> v = torch.tensor([[3, 6, 9], [3, 6, 9]])
>>> torch.bucketize(v, boundaries)
```

2023-04-15 14:50 UTC, ZiadAmerr commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +    boundaries=st.lists(st.integers(1, 10), min_size=1, max_size=10)),
`boundaries` was specified by torch's documentation as:

> 1-D tensor, must contain a strictly increasing sequence, or the return value is undefined.

But `st.lists(...)` doesn't necessarily generate an increasing sequence, it is a good approach to exhaustively test your function, but the probability that the strategy does generate a valid increasing sequence is very low as it randomly samples numbers from a list of integers. So all our test cases might be falling under the _"return value is undefined"_ criterion.

2023-04-15 15:44 UTC, ZiadAmerr commented
You should also make sure that the linting errors are passing, because I see some linting errors in your code.

Simply run `flake8 *.py`

2023-04-21 05:38 UTC, Aneesh02 commented
Still working on it!

2023-05-02 13:22 UTC, Aneesh02 commented
Hi @ZiadAmerr, I was a little occupied last week so did not work on it properly but I am having issues making the test case list as an increasing sequence. Could you please help me out with that a little?

2023-05-02 14:21 UTC, ZiadAmerr commented
> Hi @ZiadAmerr, I was a little occupied last week so did not work on it properly but I am having issues making the test case list as an increasing sequence. Could you please help me out with that a little?

You can create a helper function that generates a list of numbers from `min_value` to `max_value`, thus generating an uniformly increasing sequence. To remove that uniformity, you can remove random elements from that sequence, this can be done by generating random integers using `st.integers` and removing the elements with indices corresponding to these generated integers. This is the simplest approach I could think of. Feel free to modify it or create your own helper function that generates an non-uniform increasing sequence.

After finishing that, use `st.one_of` to choose between an increasing sequence or a random sequence of numbers to test both cases.

2023-05-05 14:46 UTC, ZiadAmerr requested changes
Feel free to work on it and request a review when you're done :)

2023-06-06 12:49 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-12 18:05 UTC, Aneesh02 commented
My apologies for the delay. Finally I am back working on it.

2023-06-20 07:56 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 18:06 UTC, closed without merging

2023-06-28 18:06 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.