Add bincount numpy frontend
unifyai/ivy pull request #14122
Opened 2023-04-13 15:43 UTC by ElsharkawyZz

2023-04-14 08:19 UTC, ElsharkawyZz commented
hi, what is the problem

2023-04-14 08:35 UTC, AnnaTz requested changes

2023-04-14 08:35 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_histograms.py
> +        )
You should be generating and passing the arguments of the function; `x`, `weights`, and `minlength`. I would suggest you have a look at `test_jax_numpy_bincount`.

2023-04-14 12:19 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_histograms.py
> +        )
This is still not correct. You shouldn't be passing None to arguments. You need to generate them in the test handler. Please use this as reference https://github.com/unifyai/ivy/blob/72b5158e133287851ac897b9cd0484cd2f3ded4e/ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_statistical.py#L196.

2023-04-17 08:25 UTC, AnnaTz requested changes
Please revert the changes to the `.idea` folder. These should not be merged with the PR.

2023-04-17 08:25 UTC, AnnaTz commented on ivy/functional/frontends/numpy/statistics/histograms.py
> +def bincount(x, /, weights=None, minlength=None):
You don't need all these decorators, just the `@to_ivy_arrays_and_back`.

2023-04-17 08:25 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_histograms.py
> +    keep_dims = st.booleans(),
`@handle_frontend_test` should generate and pass the function's arguments. So, you don't need `dtype`, `where` and `keep_dims`, but you need to add `weights` and `minlength`.

2023-04-17 20:51 UTC, closed without merging