Added function and test for Choose in numpy
unifyai/ivy pull request #14127
Opened 2023-04-13 17:33 UTC by SubbuS-22

2023-04-18 04:39 UTC, hirwa-nshuti requested changes
Hey @SubbuS-22 

I didn't go deep into the implementation but here are first things that need to be taken care of.
Do check the comments below.
Thanks🙂

2023-04-18 04:39 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py
> +def choose(indexes, choices, mode='raise'):
The function signature is supposed to be
```python
def choose(a, choices, out=None, mode='raise'):
    pass
```

2023-04-18 04:39 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +    dtypes, choices, indices, _ = dtype_x_indices_axis
There is an error in unpacking the generated test examples as it is a tuple of 5 elements

2023-04-18 04:40 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py
> +def choose(indexes, choices, mode='raise'):
Also ivy doesn't have the `choose` function

2023-04-27 07:36 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-04 06:27 UTC, closed without merging

2023-05-04 06:27 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.