Implement `rint` math functionality for TensorFlow frontend
unifyai/ivy pull request #14189
Opened 2023-04-15 07:34 UTC by edith007

Close https://github.com/unifyai/ivy/issues/14188

2023-04-23 06:29 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-05-01 05:27 UTC, Aarsh2001 requested changes

2023-05-01 05:27 UTC, Aarsh2001 commented on ivy/functional/frontends/tensorflow/math.py
> +    "tensorflow",
Can you please add `bfloat16` here. I think this should resolve the error in `intelligent-tests/run_test_1`

2023-06-09 08:16 UTC, Aarsh2001 commented
Closing this PR due to inactivity, feel free to reopen once you're ready with the changes 🙂

2023-06-09 08:16 UTC, closed without merging