Implement reciprocal math functionality for TensorFlow frontend
unifyai/ivy pull request #14185
Opened 2023-04-15 06:55 UTC by edith007

Close https://github.com/unifyai/ivy/issues/14184

2023-04-15 07:15 UTC, edith007 commented
@hirwa-nshuti Let me know if there are any suggestions or changes required ? 🙇🏻

2023-04-16 15:31 UTC, hirwa-nshuti requested changes
Hey @edith007 

Thanks for the PR. 
Generally you're close to a functioning implementation but some improvements are needed 😊
You'll need to make the tests comprehemnsive no need to limit to some values😁
Also check the comments below.
Thanks!

2023-04-16 15:31 UTC, hirwa-nshuti commented on ivy/functional/frontends/tensorflow/math.py
> +    return ivy.divide(ivy.array(1.0, dtype=x.dtype), x, name=name)
We have an `ivy.reciprocal` function no need to implement a composition.
Also leave the parameter name unused it's fine

2023-04-16 19:19 UTC, hirwa-nshuti approved these changes
Thanks for contributing😊
All looks good to me, going to merge

2023-04-16 19:20 UTC, merged