Add `getfield` instance method to NumPy Frontend
unifyai/ivy pull request #14197
Opened 2023-04-15 11:50 UTC by edith007

Close https://github.com/unifyai/ivy/issues/14195

2023-04-15 13:26 UTC, edith007 commented
@karalleyna Let me know if there are any suggestions or changes required ? 🙇🏻

2023-04-23 06:29 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-04-25 16:18 UTC, hirwa-nshuti requested changes
Hey @edith007 

Thanks for the PR😊
Tests are failing and a few changes are needed check the comments below.
Thanks🙂

2023-04-25 16:18 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +        return np_frontend.getfield(self._ivy_array, dtype, offset).astype(dtype)
Hey this function isn't implemented on the numpy frontend
You'll have to implement it using the composition of ivy functions

2023-06-20 08:56 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-01 05:53 UTC, closed without merging

2023-07-01 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.