set difference
unifyai/ivy pull request #14225
Opened 2023-04-16 07:09 UTC by anurag629

2023-04-18 05:05 UTC, hirwa-nshuti requested changes
Hey @anurag629 

I added some few comments below check them out🙂
Adding that we will need paddle implementation as well😁

2023-04-18 05:05 UTC, hirwa-nshuti commented on ivy/functional/ivy/experimental/set.py
> +def difference(
I think we can make a superset for this function as it is handled differently on the Tensorflow side, we can add `assume_unique` argument. And handle the case of multi-dimensional arrays as `TensorFlow supports this.
```python
import tensorflow as tf

set1 = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2], [2, 3]], values=[1, 2, 3], dense_shape=[3, 4])
set2 = tf.sparse.SparseTensor(indices=[[0, 0], [2, 2], [2, 3]], values=[1, 2, 3], dense_shape=[3, 4])

diff = tf.sets.difference(set1, set2)
print(diff)
```

2023-04-18 09:47 UTC, anurag629 commented on ivy/data_classes/container/experimental/set.py
> +    def static_difference(
But other functions are not private(in other files).

2023-04-18 10:41 UTC, hirwa-nshuti commented on ivy/data_classes/container/experimental/set.py
> +    def static_difference(
Only the container static methods

2023-06-20 07:45 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-27 05:53 UTC, closed without merging

2023-06-27 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.