Removed # noqa from docstrings
unifyai/ivy pull request #14272
Opened 2023-04-17 13:25 UTC by ebyau

Formating Docstrings in the ivy code base to remove "# noqa"

2023-04-18 12:47 UTC, KareemMAX requested changes
Please revert changes made in `.idea` directory. I've made some comments about places that actually are not problematic.

Regarding the other places you refactored, I guess that wasn't intended refactor. Please look into the the documentation provided by your IDE, if you looked at `ivy.data_classes.array.elementwise.logical_or()` you will find it like the (This is on my vscode):

> This function conforms to the Array API Standard <https://data-apis.org/array-api/latest/>_. This docstring is an extension of the
docstring `<https://data-apis.org/array-api/latest/API_specification/generated /signatures.elementwise_functions.logical_or.html>`_ in the standard.

There should be no space between `/generated` and `signatures`. Refer to our technical analysis in the trello card, if you have a better solution you are welcome to do it as well, as long as docstrings render correctly in both the doc-builder and vscode (or pycharm).

2023-04-18 12:47 UTC, KareemMAX commented on determine_test_coverage.py
> +    true > test_names"
As these are system commands they shouldn't be tampered with, please revert that change

2023-04-18 12:47 UTC, KareemMAX commented on determine_test_coverage.py
> +            > coverage_output;coverage "
As these are system commands they shouldn't be tampered with, please revert that change

2023-04-26 11:37 UTC, ebyau commented
@KareemMAX Other than the changes you requested above are the rest of the changes I made okay?

2023-04-26 11:51 UTC, KareemMAX commented
@ebyau, I'm not really sure what changes do you mean, please reference them to me if you can

2023-06-08 20:51 UTC, KareemMAX commented
As this PR is stale for a long time, I'll close it in the meantime.

If you wish to continue working on it in the future please feel free to reopen it

2023-06-08 20:51 UTC, closed without merging