jax
unifyai/ivy pull request #14295
Opened 2023-04-17 21:48 UTC by mohame54

2023-04-18 07:26 UTC, mohame54 commented
is there a problem with my PR

2023-04-18 15:00 UTC, mohame54 commented
#14263

2023-04-18 15:00 UTC, mohame54 commented
Really sorry, i forgot to mention the issue number

2023-04-19 11:03 UTC, MahmoudAshraf97 requested changes
Hello Mohamed, please remove all changes that are unrelated to your code

2023-04-19 17:00 UTC, closed without merging