Dummy pr to test behaviour
unifyai/ivy pull request #1439
Opened 2022-06-14 10:26 UTC by foobarrymore

2022-06-14 10:29 UTC, foobarrymore commented
@sherry30 Hi, can you add a dummy code review? We're trying to test a workflow for PRs. Thanks a lot!

2022-06-16 22:15 UTC, sherry30 reviewed
Dummy code Review

2022-06-17 09:56 UTC, foobarrymore commented
> Dummy code Review

Okay thanks a lot!

2022-06-17 10:03 UTC, MarShaikh requested changes
Test

2022-06-18 09:26 UTC, juliagsy requested changes

2022-06-18 09:26 UTC, juliagsy commented on dummy_PR_test.txt
> +Testing PR with small edit
dummy review

2022-06-18 09:38 UTC, closed without merging