Added jax.numpy.csingle
unifyai/ivy pull request #14414
Opened 2023-04-20 06:00 UTC by Dev-Khant

Solves #14413

2023-04-20 07:45 UTC, Dev-Khant commented
Hello @hello-fri-end, locally all the tests are passed but I don't why its failing here. So if something is wrong do let me know.
Thanks

2023-04-24 13:29 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_creation.py
> +    dtype_and_x=helpers.dtype_and_values(available_dtypes=helpers.get_dtypes("complex"))
looks like `jax.numpy.csingle` is an alias of `jax.numpy.complex64`. You should add `aliases=["jax.numpy.complex64"]` in the decorator :)

2023-04-24 13:30 UTC, hello-fri-end requested changes
Thanks for making this PR @Dev-Khant :rocket:. Just left a few minor comments - once you resolve those, we can merge this :)

2023-04-25 02:14 UTC, hello-fri-end requested changes
Can you please look at the formatting errors? @Dev-Khant

2023-04-25 03:37 UTC, Dev-Khant commented
@hello-fri-end I have made the changes and those lints errors are from other files.

2023-04-25 03:43 UTC, hello-fri-end approved these changes

2023-04-25 04:33 UTC, Dev-Khant commented
@hello-fri-end If everything is seems good, can you merge it?

2023-04-25 04:39 UTC, merged

2023-04-25 04:40 UTC, hello-fri-end commented
> @hello-fri-end If everything is seems good, can you merge it?
Was waiting for the jobs to finish. Thanks for the contribution. :)

2023-04-25 04:42 UTC, Dev-Khant commented
Thanks for Merging :)