Added conjugate function to Numpy Frontend
unifyai/ivy pull request #14594
Opened 2023-04-25 17:22 UTC by RakshitKumar04

2023-04-25 17:22 UTC, RakshitKumar04 commented
Close #14593

2023-04-25 18:36 UTC, RakshitKumar04 commented
Hey, @xoiga123 Please review my PR.

2023-04-27 18:55 UTC, xoiga123 commented
Hi, as noted in [numpy's docs](https://numpy.org/doc/stable/reference/generated/numpy.conjugate.html):
> [conj](https://numpy.org/doc/stable/reference/generated/numpy.conj.html#numpy.conj) is an alias for [conjugate](https://numpy.org/doc/stable/reference/generated/numpy.conjugate.html#numpy.conjugate)

And given that `conj` is already implemented in the numpy frontend, please change your implementation according to our [Duplicate Policy](https://lets-unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#frontends-duplicate-policy) :hugs: You should not repeat the same thing twice.

2023-04-28 08:17 UTC, RakshitKumar04 commented
Hey @xoiga123 I have re-implemented the `conjugate` function, Please review it.

2023-04-28 21:03 UTC, xoiga123 commented
LGTM! Thank you for contributing to Ivy :hugs:

2023-04-28 21:04 UTC, xoiga123 approved these changes

2023-04-28 21:13 UTC, xoiga123 requested changes
Hold up :stop_sign: Seems like the test doesn't pass

2023-04-28 21:13 UTC, xoiga123 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_handling_complex_numbers.py
This test is failing with: 
`AttributeError: module 'ivy.functional.frontends.numpy' has no attribute 'conjugate'`

2023-04-28 21:38 UTC, RakshitKumar04 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_handling_complex_numbers.py
Hey @xoiga123 I have resolved the `Attribute Error`, Please take a look.

2023-04-28 22:07 UTC, xoiga123 commented
LGTM for real this time! Have a nice weekend! :star:

2023-04-28 22:07 UTC, xoiga123 approved these changes

2023-04-28 22:10 UTC, merged