flip #1458
unifyai/ivy pull request #1459
Opened 2022-06-15 19:37 UTC by suhy-jang

#1458 Reformat the flip in the manipulation

2022-06-18 21:23 UTC, saeedashrraf requested changes
Hello @suhy-jang , for the 'out' argument, make sure to add the native array type appropriately the in backend type hints as shown in the examples [here](https://lets-unify.ai/ivy/deep_dive/9_function_arguments.html#examples). Thank you for your effort!

2022-06-19 12:01 UTC, suhy-jang commented
Hello @saeedashrraf 
I updated the "out" argument to use a native type.
Please review again.
Thank you.

2022-06-23 11:22 UTC, saeedashrraf approved these changes

2022-06-23 11:23 UTC, saeedashrraf commented
Looks good to me. Thank you for your effort 🎉 @suhy-jang

2022-06-23 11:23 UTC, merged