added corrcoef in Torch front end
unifyai/ivy pull request #14611
Opened 2023-04-26 05:46 UTC by Jayanth941

2023-04-26 05:53 UTC, Jayanth941 commented
close #13834

2023-05-01 05:41 UTC, Aarsh2001 requested changes

2023-05-01 05:41 UTC, Aarsh2001 commented on ivy/functional/frontends/torch/miscellaneous_ops.py
> +        raise ValueError("m has more than 2 dimensions")
The message should be like this -: 
`Expected 2D input array (N, M), but got input array of shape ({input.shape[1]}) instead`

2023-06-11 03:14 UTC, Aarsh2001 commented
Hi @Jayanth941, closing this PR due to inactivity, feel free to open it once you're done with the changes 🙂

2023-06-11 03:14 UTC, closed without merging