Added multiply to torch frontend
unifyai/ivy pull request #14644
Opened 2023-04-27 01:20 UTC by guitld

2023-04-27 01:25 UTC, guitld commented
This PR reffers to  issue #14573

2023-05-01 05:07 UTC, YushaArif99 commented on ivy/functional/frontends/torch/tensor.py
> +        return torch_frontend.multiply(self._ivy_array, other, out=out)
I don't think there's a need to do `self._ivy_array` here. Simply calling the frontend function by passing `self` should work as the frontend function's decorators will take care of converting the inputs to and from `ivy arrays` to `frontend array` etc.

2023-05-01 05:07 UTC, YushaArif99 commented on .idea/ivy.iml
This file should not be modified

2023-05-01 05:07 UTC, YushaArif99 commented on .idea/misc.xml
same for this file as well

2023-05-01 05:08 UTC, YushaArif99 commented on .idea/vcs.xml
same for this file as well

2023-05-01 05:10 UTC, YushaArif99 requested changes
Hi @guitld 

Thanks for making the PR. Could you kindly address the abovementioned points? Also, there are a couple of merge conflicts that will need to be resolved. Could you kindly also resolve them as this will allow the CI tests to run? Once all the relevant tests are passing, you can re-request a review 🙂

2023-05-02 16:09 UTC, guitld commented
Hi @YushaArif99 , just commited the changes you suggested! Thx for the review :)
I don't know why it's failing in the check formatting test though

2023-05-09 09:23 UTC, YushaArif99 requested changes
HI @guitld 

The `.idea` files are still showing in the modified files. You can try using `git revert` to revert the commit that modified these files. If that doesnt work, one solution could be to reset your HEAD to point to the master branch using `git reset --hard origin`. This will reset your branch's HEAD to point to the master branch and so your local changes would get removed. Its best to keep a backup before you use `git reset`. Once this is done, you can then do the usual `git add->git commit->git push` to create a new commit. **NOTE:** its best to manually add the files using `git add <file path>` rather than `git add .` as the latter might add unwanted files (eg: the `idea` files) to the staging area.

Hope that helps 🙂

2023-05-10 17:31 UTC, guitld commented
Hi @YushaArif99

I think .idea is not modified anymore. Also, the conflicts are resolved.
Could you review it again please? :)

2023-05-15 06:16 UTC, YushaArif99 approved these changes
Hi @guitld 

Thanks for removing the `.idea` files. The CI tests are also passing now which means we can merge this PR 🙂

2023-05-15 06:17 UTC, merged