Updated README.rst example code
unifyai/ivy pull request #14667
Opened 2023-04-27 13:24 UTC by ZiadAmerr

2023-04-29 10:20 UTC, guillesanbri reviewed
lgtm, one thing tho, the loss when executing this seems to be quite far from the one in the gif, is there any reason for this?

2023-04-29 10:28 UTC, ZiadAmerr commented
Yes, the number of training examples and the standard deviation of the error added to the labels

The example here has 3000 feature-label pairs, and the labels have an error added to them with mean of 0 and std of 2. While the graph has about 100 examples only and a std of 0.2. I did that so it would look better in visualization

2023-04-30 18:10 UTC, guillesanbri commented
I'd say it should be the same, feel free to change the code if the visualization needs to be simpler imo

2023-04-30 22:44 UTC, ZiadAmerr commented
Hey @guillesanbri, it should be much closer now.

2023-05-01 09:18 UTC, guillesanbri commented
> Hey @guillesanbri, it should be much closer now.

I'm afraid the final loss is still around ~175 for me :thinking:

2023-05-01 10:32 UTC, ZiadAmerr commented on README.rst
> +    optimizer = ivy.Adam(0.1)
```suggestion
    optimizer = ivy.Adam(0.3)
```

2023-05-01 10:33 UTC, ZiadAmerr commented on README.rst
> +    y = 0.2 * x ** 2 + 0.5 * x + 0.1 + ivy.random.random_normal(shape=(500, 1), mean=0, std=1)
```suggestion
    n_training_examples = 2000
    noise = ivy.random.random_normal(shape=(n_training_examples, 1), mean=0, std=0.1)
    x = ivy.linspace(-6, 3, n_training_examples).reshape((n_training_examples, 1))
    y = 0.2 * x ** 2 + 0.5 * x + 0.1 + noise
```

2023-05-01 10:35 UTC, ZiadAmerr commented
Hey @guillesanbri, with the latest code changes, I could reach a loss of 0.01.

2023-05-30 20:28 UTC, ZiadAmerr commented on README.rst
> +    </video>
```suggestion
   <div align="center">
      <img width="50%" src="https://github.com/ZiadAmerr/unifyai.github.io/blob/master/img/regressor_lq.gif">
   </div>
```

2023-06-20 09:03 UTC, guillesanbri requested changes
totally missed this sorry! Once the comment is addressed if the code runs fine we can merge it :+1:

2023-06-20 09:03 UTC, guillesanbri commented on README.rst
> +      <img width="50%" src="https://github.com/ZiadAmerr/unifyai.github.io/blob/master/img/regressor_lq.gif">
this should point to an Ivy repo directly :)

2023-06-22 08:56 UTC, guillesanbri commented
Hi @ZiadAmerr the example seems to be throwing an error locally for me, at first glance I'd say it's something on the framework side and not really the example, but we should get someone to look into it, could you raise it in Discord? Thanks!

2023-06-22 13:36 UTC, merged