Add GRU
unifyai/ivy pull request #14697
Opened 2023-04-28 09:47 UTC by karalleyna

2023-05-01 10:44 UTC, sherry30 requested changes
Hi,

Your PR looks good, the tests are also passing.
I think we should also add `linear_before_reset` as a boolean argument and `sequence_lens` argument.
Let me know what you think and if you have any questions.

Thanks

2023-05-01 10:44 UTC, sherry30 commented on ivy/functional/ivy/experimental/layers.py
> +    y = ivy.empty([seq_length, batch_size, hidden_size])
can remove this statement

2023-05-01 10:44 UTC, sherry30 commented on ivy/functional/ivy/experimental/layers.py
> +    self
change to `x`,
same with the rest of the parameters

2023-06-28 05:53 UTC, closed without merging

2023-06-28 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.