Add
unifyai/ivy pull request #14760
Opened 2023-04-30 20:12 UTC by soma2000-lang

2023-05-01 07:06 UTC, Aarsh2001 reviewed
Hey @soma2000-lang, we have updated the task a bit. Kindly have a look at the description, thanks 🙂

2023-05-01 17:13 UTC, soma2000-lang commented
Hi @Aarsh2001 Just  had some silly doubt.

1. Could not  find the native shape class for the torch.size.

2. We need to add the special methods to init py file right?

2023-05-03 12:05 UTC, Aarsh2001 reviewed
Hey @soma2000-lang, you need to check the methods by printing `dir(torch.Size)` and `dir(tf.TensorShape)`. So it should output something like this(for torch) -:

<img width="1792" alt="Screenshot 2023-05-03 at 5 21 22 PM" src="https://user-images.githubusercontent.com/65212523/235908452-b4981d57-2f69-487c-b999-e973bd8da707.png">

I guess the way they implement `torch.Size` is a bit different, and it is implemented as a subclass of std::vector<int64_t>, where it overrides several methods to provide additional functionality for working with tensor sizes. You can find the base file [here](https://github.com/pytorch/pytorch/blob/main/torch/csrc/Size.cpp). But it don't think you need to refer it for the implementations. 

What you should do instead is -:
1. check for the intersection of `dunder` methods in `tf.TensorShape` and `torch.Size()`. This is priority number 1
2. implement all other property/class methods as supersets. So these methods would be which don't have a preceding or succeeding underscore. For example `numel` and `count` in the screenshot above. You can open another PR for this. 

Hope this clarifies, if not, feel free to reach out to me 🙂

2023-05-04 07:38 UTC, soma2000-lang commented
![image](https://user-images.githubusercontent.com/56045049/236140185-db66f1ad-0818-4a0d-ba55-d0ada67c72c8.png)

2023-05-07 07:25 UTC, Aarsh2001 commented
> Hi @Aarsh2001 I have a doubt ,I cannot find reference to some dunder methods like '''**reduce_ex** ''' and ""**format**""" I am also taking reference from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/tensor_shape.py)
> 
> For the property methods I will open another PR

Hey @soma2000-lang, the `__reduce_ex` method is used for serialising/deserialising objects. I don't think we need to implement this, cause we would be defaulting to the `NativeShape` class anyway. They have handled it in their implementation🙂. Here's an example I ran, which works for `ivy.Shape` -:

```
import ivy
import pickle

ivy.set_backend("tensorflow")
x = ivy.array([2., 3.])
y = ivy.Shape(x.shape)

with open('my_dict.pkl', 'wb') as f:
    # Serialize the dictionary to the file using pickle.dump()
    pickle.dump(y, f)
```
This can be extended  to other backends as well. I don't think we need the `__format__` method either, and a few others like `__init_subclass__`, `__subclasshook__`. I think this PR is a good merge 🙂, requesting a final review from @VedPatwardhan

2023-05-07 07:27 UTC, Aarsh2001 requested changes

2023-05-07 07:27 UTC, Aarsh2001 commented on ivy/__init__.py
> +        return super().__setattr__(item)
Also, let's remove this, we don't need it

2023-05-09 06:04 UTC, VedPatwardhan approved these changes
looks good to merge, thanks @soma2000-lang @Aarsh2001 🙂

2023-05-09 07:01 UTC, merged