#14829
unifyai/ivy pull request #14830
Opened 2023-05-02 16:04 UTC by kaushal07wick

2023-05-02 16:07 UTC, kaushal07wick commented
I am bit confused on the data generation for meshgrid function.
Any suggestion in the data generation part would be helpful.

2023-05-03 09:26 UTC, kaushal07wick commented
@kurshakuz kindly suggest any tips for the data generation part for the Meshgrid function.

2023-05-08 14:32 UTC, sherry30 requested changes
Hi,

For generating data, you can take a look at hoe `meshgrid` is being tested in ivy's API. I think it should be very similar.

Thanks

2023-05-10 16:59 UTC, kaushal07wick commented
@sherry30 , please look into the test function, i think there is still something missing.

2023-05-18 05:02 UTC, kaushal07wick commented
Sure @sherry30 I'll take a look into it.

2023-05-18 05:02 UTC, kaushal07wick commented
@sherry30 is there anything missing from the test function, if you can just guide me once., that would be great. Thanks

2023-05-18 05:04 UTC, kaushal07wick commented
This was the issue #14829 , it got closed.

2023-05-19 08:48 UTC, kaushal07wick commented
meshgrid #14829

2023-05-23 08:00 UTC, sherry30 requested changes
Hi, 
Im not sure what you mean by something is missing. Can you point to a specific thing that you think might be missing

2023-05-28 09:29 UTC, sherry30 requested changes
Some changes requested

2023-05-28 09:29 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py
> +        sparse=sparse,
You should send arrays to the test function like `arrays=arrays`

2023-05-28 09:29 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py
> +    input_dtypes,
unsused argument, maybe by mistake?

2023-06-09 12:43 UTC, kaushal07wick commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py
> +    input_dtypes,
Okay

2023-06-22 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-30 10:14 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-11-25 15:52 UTC, closed without merging