Added ivy.array lint in docstrings
unifyai/ivy pull request #14928
Opened 2023-05-04 22:50 UTC by KareemMAX

2023-05-05 04:14 UTC, VedPatwardhan reviewed
Not sure if the PR was intended to be reviewed, but just wanted to bring a case into consideration. Thanks @KareemMAX 🙂

2023-05-05 04:14 UTC, VedPatwardhan commented on ivy/data_classes/array/array.py
> +            a: ivy.array(
I think the array above was originally formatted correctly, given that all frameworks format it that way. Same applies to other similar instances.

2023-05-08 18:32 UTC, CatB1t requested changes
Agree to @VedPatwardhan point, also we should ideally make sure when the linter is setup, that it can handle code and string arrays differenetly, so arrays existing in code should be formatted but not the ones in the docstring.

2023-06-20 07:45 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 18:05 UTC, closed without merging

2023-06-28 18:05 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.