Added cumulative_logsumexp to Tensorflow frontend
unifyai/ivy pull request #14957
Opened 2023-05-05 20:40 UTC by roboFiddle

Closes #14606

2023-05-06 03:57 UTC, Dsantra92 reviewed
Hi @roboFiddle, thanks for the PR. The changes look good overall but I had question on the type conversion happening here.

2023-05-06 03:57 UTC, Dsantra92 commented on ivy/functional/frontends/tensorflow/math.py
> +                ivy.exp(ivy.astype(x, "float64")),
Not sure if the type conversion is needed here.

2023-05-07 22:50 UTC, roboFiddle commented
I just refactored the function to avoid the type conversion. It's a little more faithful to the original Tensorflow version, which is implemented using a scan. Let me know if you have any questions about it.

2023-05-12 23:24 UTC, roboFiddle commented
@YushaArif99 Would it be able to get this push request reviewed again? If any changes are needed, please let me know.

2023-05-15 07:11 UTC, YushaArif99 commented on ivy_tests/array_api_testing/test_array_api
Also, can you kindly remove this from the modified files 🙂

2023-05-16 18:53 UTC, roboFiddle commented
I've resolved the test error (the "float" dtypes as a category in Ivy includes some types not valid for cumulative_logsumexp. The merge conflict seems to be that there's a lot of overlapping code between the two test functions - do I need to resolve that myself?

2023-05-22 06:28 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +    assume(input_dtype != "bfloat16")
You dont need to add any extra logic to filter out specific `dtypes` here. You can instead use the `@with_unsupported_dtypes` decorator in the `cumulative_logsumexp` function itself to achieve this purpose. You can read more about the use of this decorator [here](https://unify.ai/docs/ivy/overview/deep_dive/data_types.html#supported-and-unsupported-data-types)

2023-05-22 06:30 UTC, YushaArif99 requested changes
Hi @roboFiddle 

Can you kindly address the abovementioned issue and re-request a review once that is fixed. Also, can you kindly resolve the merge conflicts in this PR so that the CI tests can rerun. Thanks 🙂

2023-05-30 04:27 UTC, closed without merging