added logical_and to ivy/functional/frontends/tensorflow/raw_ops.py
unifyai/ivy pull request #14998
Opened 2023-05-07 20:06 UTC by MuhammadAbuzar36

2023-05-07 20:07 UTC, MuhammadAbuzar36 commented
Close #14996

2023-05-09 18:54 UTC, hmahmood24 requested changes

2023-05-09 18:54 UTC, hmahmood24 commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +LogicalAnd = to_ivy_arrays_and_back(map_raw_ops_alias(tf_frontend.math.logical_and))
Please add the corresponding test as well

2023-05-09 20:49 UTC, MuhammadAbuzar36 commented
@hmahmood24 Thank You for reviewing my PR. I have added the corresponding test function as asked by you and my new commit passes all the tests except one, can you guide me with this one particular test failing?
Thank You again

2023-05-10 07:34 UTC, hmahmood24 commented
> @hmahmood24 Thank You for reviewing my PR. I have added the corresponding test function as asked by you and my new commit passes all the tests except one, can you guide me with this one particular test failing? Thank You again

Hey @MuhammadAbuzar36. Thanks for making the changes. For which backend is the test failing right now? Looking at the CI it seems to be passing for all backends except `paddle` but it seems that it didn't even run the test against `paddle` to begin with. Can you kindly run the test locally and attach the output here? Make sure you run against all backends by using the flag `--backend "all"`

2023-06-20 07:56 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 06:46 UTC, hmahmood24 commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-06-28 06:46 UTC, closed without merging