Add the frontend for Jax random Truncated normal
unifyai/ivy pull request #14997
Opened 2023-05-07 19:51 UTC by iammarco11

closes #14882

2023-05-07 23:31 UTC, iammarco11 commented
Hi @hmahmood24 
The latest commit test fails and outputs the following
```
=================================== FAILURES ===================================
_ test_jax_truncated_normal[cpu-ivy.functional.backends.tensorflow-False-False] _
ivy/utils/exceptions.py:122: in _handle_exceptions
    return fn(*args, **kwargs)
ivy/functional/ivy/data_type.py:923: in as_ivy_dtype
    return current_backend(None).as_ivy_dtype(dtype_in)
ivy/functional/backends/tensorflow/data_type.py:202: in as_ivy_dtype
    dtype_str = ivy_dtype_dict[dtype_in]
E   TypeError: unhashable type: 'DeviceArray'
```

Now I am not sure why this happens, I researched a bit and came across this [issue](https://github.com/google/jax/issues/6233) and came across something called `HashableArrayWrapper`.
Is the backend faulty, or is it something to do with the way I implemented the frontend. Looking forward to hear your inputs and thoughts :)

2023-05-09 19:02 UTC, hmahmood24 requested changes
Hey @iammarco11, thanks so much for opening this PR! 😃 I have made a comment on the PR. Can you kindly address that and then try running the tests to see if they pass or still throw the same error. Let me know if you need any help afterwards. Thanks!

2023-05-09 19:02 UTC, hmahmood24 commented on ivy/functional/frontends/jax/random.py
> +
Kindly add the `@to_ivy_arrays_and_back` and `@handle_jax_dtype` decorators to the function here

2023-05-09 20:36 UTC, iammarco11 commented
Hi @hmahmood24 I did the changes you requested but the same error persists. Could you help me out? Thanks for taking a look into it!

2023-05-14 01:36 UTC, iammarco11 commented
@hmahmood24 fixed the test scenario. Finished implementing the truncated normal for jax frontend. This PR is now ready to be reviewed. Looking forward to hearing your inputs. Thanks!

2023-05-15 10:39 UTC, hmahmood24 requested changes

2023-05-15 10:39 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_random.py
> +@pytest.mark.xfail
Can you elaborate on why you've used this here?

2023-06-20 07:56 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 06:45 UTC, hmahmood24 commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-06-28 06:45 UTC, closed without merging