Reformatted unset_default_device #1498
unifyai/ivy pull request #1499
Opened 2022-06-17 15:29 UTC by naailkhan28

2022-06-20 07:28 UTC, chie2727 requested changes
Hi @naailkhan28 ,
It seems you are carrying out the reformatting task for this function, so please continue and carry out steps 2 to 4 as explained in the task description: https://github.com/unifyai/ivy/issues/814

2022-06-20 10:11 UTC, naailkhan28 commented
> Hi @naailkhan28 , It seems you are carrying out the reformatting task for this function, so please continue and carry out steps 2 to 4 as explained in the task description: #814

I've added a docstring as per the instructions, however this function has no arguments and doesn't return anything so I don't see any way I can add functions arguments, type hints, or docstring examples?

2022-06-20 10:45 UTC, chie2727 commented
Since the function has no return, you can add to the function argument by indicating that the return value is `None`.
For example:
https://github.com/unifyai/ivy/blob/44d3b9ca52115cf769f2f2b9c7a192ef7bf9de4a/ivy/functional/ivy/device.py#L255

You don't have to worry about type hints since there are no inputs.
For the docstring examples you can create simple examples of how the function is used.

2022-06-21 10:15 UTC, chie2727 commented on ivy/functional/ivy/device.py
> +    device(type="gpu:0")
Thanks for making the edits!
I just want to check the format of the output you're getting when running this example locally.
Is the format of your output showing as `device(type="gpu:0")` and not just `gpu:0` ?

![clip_2](https://user-images.githubusercontent.com/72862115/174776057-2942209a-dfae-422b-99f9-62e3c49286fc.png)

2022-06-21 10:34 UTC, naailkhan28 commented
Hi, thanks for bringing that up! I actually did get just `gpu:0` when I ran the code locally but I initially wrote my example to match the example for the `clear_mem_on_dev` function. I've updated my docstring example now to reflect the actual output of the functions :)

2022-06-24 04:13 UTC, chie2727 approved these changes

2022-06-24 04:18 UTC, chie2727 commented
Hi @naailkhan28 , 
Okay, I see! Thanks for making the edits.
I'll merge in your changes now.

2022-06-24 04:20 UTC, merged