Update layers.py added max_pool1d class
unifyai/ivy pull request #15017
Opened 2023-05-08 05:16 UTC by mtnvdsk

created a max_pool1d class and a forward method to pass the output from the layer.

2023-05-09 08:41 UTC, Sam-Armstrong commented
Close #15014

2023-05-09 08:45 UTC, Sam-Armstrong commented
Hey @mtnvdsk, I've linked this to the corresponding issue - but in future you should do this yourself by adding a comment ‘Close #Issue_number’, as explained here: https://unify.ai/docs/ivy/overview/contributing/the_basics.html

2023-05-09 08:53 UTC, Sam-Armstrong commented
@mtnvdsk Please could you add tests for this class in ivy_tests/test_ivy/test_stateful/test_layers.py? You might find this helpful for writing the tests: https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html.

Thanks!

2023-05-09 10:10 UTC, mtnvdsk commented
Thank for your suggestion sir and from next time I will use the close issue comment 
As you asked me to add test case I added the test case to the ivy_test/test_ivy/test_stateful/test_layers.py

2023-05-09 14:22 UTC, Sam-Armstrong commented
@mtnvdsk Thanks for making that change :)

When I run the test you created using the command pytest ivy_tests/test_ivy/test_stateful/test_layers.py::test_maxpool1d_layer the test cases all fail. Please could you try to resolve this?

Thanks

2023-05-10 04:37 UTC, mtnvdsk commented
@Sam-Armstrong sir, Modified both the layers.py and test_layers.py as it passed all the test cases. Could you please check for further changes?

2023-05-11 10:12 UTC, Sam-Armstrong requested changes
@mtnvdsk Sorry for the slow reply. All your test cases are still failing for me - I've suggested some changes here. With these changes for me only one of the test cases is still failing. Could you try this out and see if your getting the same? And if so, please can you try to fix any remaining test fails?

Thanks :)

2023-05-11 10:12 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_stateful/test_layers.py
> +        x[0] = np.expand_dims(x[0], axis=2)
```suggestion
```

2023-05-11 10:12 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_stateful/test_layers.py
> +            "padding": padding[-1],
```suggestion
            "kernel_size": kernel_size,
            "stride": stride,
            "padding": padding,
            "data_format": "NCW",
```

2023-05-11 10:12 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_stateful/test_layers.py
> +            "padding": padding[-1],
```suggestion
            "kernel_size": kernel_size,
            "stride": stride,
            "padding": padding,
            "data_format": "NCW",
```

2023-05-15 04:44 UTC, closed without merging

2023-05-15 08:41 UTC, Sam-Armstrong commented
@mtnvdsk There seems to be something strange going on with this, for me the test was passing for everything except jax. Not sure what you're seeing?