adding property methods
unifyai/ivy pull request #15091
Opened 2023-05-09 14:03 UTC by soma2000-lang

2023-05-22 11:36 UTC, Aarsh2001 requested changes

2023-05-22 11:36 UTC, Aarsh2001 commented on ivy/__init__.py
> +        return self._shap
Hey @soma2000-lang i think the shape property already exists above, you can remove this

2023-05-22 13:13 UTC, Aarsh2001 requested changes

2023-05-22 13:13 UTC, Aarsh2001 commented on ivy/__init__.py
> +            raise ValueError("as_list() is not defined on an unknown TensorShape.")
It shouldn't be TensorShape here

2023-05-23 02:06 UTC, soma2000-lang commented
Hi, @Aarsh2001 ,I will write the tests.

2023-05-29 17:02 UTC, VedPatwardhan reviewed
Hey @soma2000-lang and @Aarsh2001, feel free to re-request a review once the tests are added, I think the changes suggested by @Aarsh2001 are sufficient for now. Thanks for looking into this @soma2000-lang 🙂

2023-06-20 09:28 UTC, vedpatwardhan approved these changes
Hey @soma2000-lang, thanks for writing the tests, the changes look good to me, there's a few lint failures which the gardener would be able to fix, feel free to merge the PR once @Aarsh2001 is done reviewing 🙂

2023-06-20 09:28 UTC, vedpatwardhan commented
ivy-gardener

2023-06-23 08:25 UTC, soma2000-lang commented
ivy-gardener
white_check_mark Ivy gardener has formatted your code.
If changes are requested, don't forget to pull your fork.

2023-06-29 06:14 UTC, Aarsh2001 approved these changes
LGTM !

2023-06-29 06:37 UTC, merged