added fmax
unifyai/ivy pull request #15113
Opened 2023-05-09 17:42 UTC by UbajakaCJ

Added a new function fmax to the elementwise.py file.  It returns the element-wise maximum of array elements.

It compares two arrays and returns a new array containing the element-wise maxima. If one of the elements being compared is a NaN, then the non-nan element is returned. The latter distinction is important for complex NaNs, which are defined as at least one of the real or imaginary parts being a NaN. The net effect is that NaNs are ignored when possible.

2023-05-15 07:39 UTC, YushaArif99 requested changes
Hi @UbajakaCJ 

Thanks a lot for your contribution. A couple of points regarding your PR: 

- Is there a subtask associated with this PR? If so, could you kindly provide an issue # for it.  Contributors are only allowed to work on open tasks. And so if there is no open issue relating to this PR, I think then it's better to close this PR and choose another function in the open tasks [here](https://github.com/unifyai/ivy/issues?q=is%3Aopen+is%3Aissue+label%3AToDo)

- This task seems to be related to the `Extend Ivy API` task. In this case, the task also involves implementing each of the backends for the `fmax` function as well as writing the tests for it.

2023-05-22 06:39 UTC, YushaArif99 commented
Hi @UbajakaCJ 

By a subtask, what I mean is whether this PR is part of a broader ToDo list. An example of this would be [here](https://github.com/unifyai/ivy/issues/15055)
Basically, as a contributor, you are only allowed to work on tasks that are part of the ToDo list. You can read more about this in the contributing section of the documentation [here](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#open-tasks)

Regarding writing the tests, its going to be pretty much similar to how other tests are written using the hypothesis helpers. But in order to do that, the first step will be to implement the backends for `fmax`. 

But as I mentioned before, I'd only recommend you begin working on this once its verified this PR is associated with some existing ToDo list so that it can be tracked properly.

2023-06-08 04:12 UTC, YushaArif99 commented
Hi @UbajakaCJ 

Are you still working on this PR? If not, we can then close this PR 🙂

2023-06-20 17:10 UTC, UbajakaCJ commented
Yes, I would like to continue working on this PR.

2023-08-17 08:01 UTC, closed without merging