Added `AvgPool1D` + stateful test
unifyai/ivy pull request #15350
Opened 2023-05-11 17:26 UTC by mobley-trent

2023-05-11 17:27 UTC, mobley-trent commented
Closes #15348

2023-05-11 17:46 UTC, mobley-trent commented
@zaeemansari70 do you mind reviewing this PR ? The tests are passing on my end

2023-05-25 09:38 UTC, MahmoudAshraf97 requested changes

2023-05-27 05:23 UTC, mobley-trent commented on ivy/stateful/layers.py
> +        dtype=None,
They are needed in the `__init__` method of the `Module` class. I followed the convention used in the rest of the layers

2023-06-05 19:31 UTC, mobley-trent commented
> please review your implementation and remove unnecessary arguments, you can check `ivy.ReLU` class for example

The implementation is consistent with the rest of the layers in the module, even `AvgPool2D` which is right next to it

2023-06-07 13:05 UTC, closed without merging