reformat bitwise_and
unifyai/ivy pull request #1538
Opened 2022-06-19 17:36 UTC by jackhong12

2022-06-20 06:11 UTC, jackhong12 commented
Hi @chie2727. Could you review my PR and give me some feedback? Thanks a lot!

2022-06-21 10:25 UTC, chie2727 requested changes

2022-06-21 10:49 UTC, jackhong12 commented on ivy/functional/ivy/elementwise.py
> +
done!

2022-06-21 10:55 UTC, jackhong12 commented
I have added the example that uses a mix of `ivy.Array` and `ivy.Container` inputs.

2022-06-24 04:24 UTC, chie2727 approved these changes
Thanks for making the changes! Everything is looking good so I'll merge your edits in

2022-06-24 04:25 UTC, merged

2022-06-24 04:44 UTC, jackhong12 commented
Thanks!