Adding test for jax's _src frontend + fixing lint issues
unifyai/ivy pull request #15381
Opened 2023-05-12 15:47 UTC by Fayad-Alman

Your task is to write tests for the functions of this frontend module https://github.com/unifyai/ivy/tree/master/ivy/functional/frontends/jax/_src.
It would be ideal to use hypothesis as much as possible, but in complex cases you will probably have to resort to plain assertions.

2023-05-13 00:26 UTC, abdulasiraj reviewed
Hi @Fayad-Alman,

tree_leaves function return the leaves of the tree. you have to come up with the solution that checks the resulting leaves with some ground truth.

Thanks!

2023-05-13 19:25 UTC, Fayad-Alman commented
Thank you for the help @abdulasiraj 
I've been trying to fix the issue, but now I'm getting an error stating the tree_leaves function doesn't exist. Mind taking a look?
Thanks again!

2023-05-16 08:17 UTC, AnnaTz requested changes

2023-05-16 08:17 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_src_tree_util.py
> +    result = ivy.Container(tree_leaves(tree, is_leaf=None))
You need to use the full path of the function or import it from our jax frontend. That's why you are getting the error.

2023-05-17 10:56 UTC, AnnaTz commented
You seem to have done some kind of formatting to a bunch of files. Ideally the PR should affect the single test file you are working on, nothing else.

2023-05-17 13:39 UTC, Fayad-Alman commented
@AnnaTz in that case I'll undo the commits related to fixing the lint tests and put those on a separate PR soon

2023-05-17 20:40 UTC, closed without merging