Update layers.py added max_pool1d class
unifyai/ivy pull request #15444
Opened 2023-05-15 04:45 UTC by mtnvdsk

2023-05-15 04:46 UTC, mtnvdsk commented
claose #15444

2023-05-15 09:46 UTC, hello-fri-end commented
Hello @mtnvdsk! Thanks for opening this PR. Would you please link the issue that this PR closes in the description? Thanks :)

2023-05-15 09:57 UTC, mtnvdsk commented
@hello-fri-end sir, updated the description

2023-05-15 17:01 UTC, mtnvdsk commented
@hello-fri-end sir, all the test cases are passing except the jax test case. please guide me to correct the code.

2023-05-17 05:21 UTC, CatB1t requested changes

2023-05-17 05:21 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +        new_kernel = kernel
Hello @mtnvdsk, good catch! can you please create a separate PR for this fix? Thanks.

2023-05-17 05:24 UTC, CatB1t requested changes

2023-05-17 05:24 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
>      if return_dilation:
This will actually make it fail if the array dim is not 3, it shouldn't be indented.

2023-05-17 05:34 UTC, closed without merging