Add scipy.linlag.det
unifyai/ivy pull request #15472
Opened 2023-05-15 19:13 UTC by paulaehab

close #15470

2023-05-16 18:58 UTC, hmahmood24 requested changes
Hey @paulaehab. Left a comment for you to look at other than that looks good to me.

Can you maybe verify that the function runs fine for some of the example inputs generated by your composite strategy? Try generating examples from your strategy by running `.example()` on `_get_dtype_and_matrix()` and comparing the ground truth result and the frontend result for all backends and verify that the results match within a given tolerance. Thanks! 😃

2023-05-16 18:58 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_scipy/test_linalg/test_linalg.py
> +#     dtype_and_x=_get_dtype_and_matrix(),
We would probably need to pass in `symmetric=True` here since determinants of asymmetric matrices are undefined

2023-06-20 07:44 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-20 05:52 UTC, closed without merging

2023-07-20 05:52 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.