Numpy frontend item
unifyai/ivy pull request #15481
Opened 2023-05-16 00:07 UTC by marschattha

#15453 

The test needs work, not sure the best way to improve it.

2023-05-18 19:03 UTC, marschattha commented
@CatB1t could you review when feasible?
Not sure why some of these tests are failing.

2023-05-26 12:30 UTC, CatB1t requested changes

2023-05-26 12:56 UTC, marschattha commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +        elif index_type == "ellipsis" and Ellipsis not in index:
If we don't change it to `elif` and leave it with `if`, the `allow_slices` flag/param does not actually work. 
And we end up with non integer indexes (slices) as well in the return index.

2023-06-01 09:09 UTC, marschattha commented
@CatB1t @Aarsh2001 any updates?

2023-06-11 03:26 UTC, Aarsh2001 approved these changes
LGTM ! @CatB1t can you have a look at the changes in the helper files once, thanks 🙂

2023-06-20 08:08 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-20 10:20 UTC, marschattha commented
@CatB1t

2023-06-30 10:14 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-10 05:35 UTC, Aarsh2001 approved these changes
LGTM

2023-07-10 05:35 UTC, Aarsh2001 commented
Can you please fix the merge conflicts ? We'll then merge this PR ASAP, thanks 🙂

2023-07-10 14:24 UTC, marschattha commented
> Can you please fix the merge conflicts ? We'll then merge this PR ASAP, thanks 🙂

Had to do more than fix the conflicts, but should be good now.

2023-07-13 05:47 UTC, CatB1t requested changes

2023-07-13 05:47 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +
Hello @marschattha, can you kindly please revert this line here? this update seems irrelevant to the PR. Thanks in advance!

2023-07-15 11:20 UTC, CatB1t commented
Thanks @marschattha, @Aarsh2001 can take the lead on the review from here!

2023-07-21 06:39 UTC, Aarsh2001 approved these changes
My apologies for the delay, LGTM !

2023-07-21 06:39 UTC, merged