Adding tf.linalg.tensor_diag
unifyai/ivy pull request #15518
Opened 2023-05-16 23:56 UTC by Patric-Ramz

tensor_diag #15400

2023-05-17 00:02 UTC, Patric-Ramz commented
Hi,

I am getting this error when I run my test. I am not sure how to fix it. 

" Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind' " 

I am not sure how to adjust my function to fix this error. Please help me.

Thank you. : )

2023-05-17 14:07 UTC, Patric-Ramz commented
Hi,

I misnamed the branch. I added the tensor_diag function and not the linalg.diag function.

Regards,
Rele

2023-05-19 20:04 UTC, zaeemansari70 requested changes
Hi @Patric-Ramz 
Requested some changes :slightly_frowning_face:

2023-05-19 20:12 UTC, Patric-Ramz commented
Hi,

Thank you for the review, I will make the changes.

2023-05-20 01:48 UTC, Patric-Ramz commented
Hello @zaeemansari70 

I made the changes you requested, but I am still encountering this error.

ivy\functional\backends\numpy\experimental\linear_algebra.py:69:

" numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind' "

In the numpy backend 'output_array' and 'diagonal_to_add' seem to have conflicting data types. I am not sure how to fix this error. Please assist me.

Another issue I ran into is the 'bfloat16' data type is supported only when using the XLA JIT compiler, and I am running the tests on a CPU without XLA JIT. I chose to exclude the 'bfloat16'.

Kind regards,

2023-05-24 12:04 UTC, zaeemansari70 requested changes
Requested some changes :slightly_smiling_face:

2023-05-24 12:04 UTC, zaeemansari70 commented on ivy/functional/frontends/tensorflow/linalg.py
> +            "float16",
This "float16", is not supported by `linalg` in any framework as far as I know.
Kindly make sure you are using this decorator correctly :slightly_smiling_face: 

Also, as far as the casting error goes, can you please dive more deep and let me know why and where that occurs? :slightly_smiling_face:

2023-06-20 08:08 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 18:06 UTC, closed without merging

2023-06-28 18:06 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.