Update array_helpers.py
unifyai/ivy pull request #15523
Opened 2023-05-17 05:36 UTC by mtnvdsk

2023-05-17 05:44 UTC, CatB1t requested changes

2023-05-17 05:44 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +        new_kernel = kernel
Hello @mtnvdsk , this will actually make it fail if the array dim is not 3, it shouldn't be indented.

2023-05-17 06:20 UTC, mtnvdsk commented
@CatB1t sir, Updated the code and all the test cases are passed.

2023-05-23 04:23 UTC, mtnvdsk commented
@CatB1t sir, can you please review any further changes in the code because I need to do another PR in the ivy to add a max_pool1d code which is failing due to this dimension 3 in the array helpers code.

2023-05-23 07:53 UTC, mtnvdsk commented
@Daniel4078 sir,can I know why this pull request is closed?

2023-05-23 09:33 UTC, Daniel4078 commented
> @Daniel4078 sir,can I know why this pull request is closed?

I was thinking that it maybe better to try solve this problem in the pull request of yours that is affect this potential bug. As this pull request is not properly linked to anything with no tags or discription of the problem.

2023-05-23 09:38 UTC, mtnvdsk commented
But @CatB1t sir asked me to do a separate PR for this issue so please reopen this PR @Daniel4078

2023-05-26 12:26 UTC, CatB1t requested changes
Hello @mtnvdsk , can you please explain the rationale behind those changes? what is the bug/issue you're trying to fix?

2023-05-26 12:33 UTC, mtnvdsk commented
@CatB1t sir, I thought the dimension parameter is hard-coded for some sizes so to reduce it as well as the size 3 dimension error causing.

2023-06-20 07:56 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-02 09:36 UTC, closed without merging