torch_histc
unifyai/ivy pull request #15536
Opened 2023-05-17 11:32 UTC by teckno

2023-05-17 15:44 UTC, teckno commented on ivy/functional/frontends/torch/miscellaneous_ops.py
> +    return ivy.histc(input, bins=bins, min=min, max=max, out=out)
I guess it's a compositional function again ?

2023-06-05 08:39 UTC, hirwa-nshuti requested changes
Hey @teckno 

Below are a few comments for changes needed😊

2023-06-05 08:39 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +    fn_tree="ivy.histc",
The function tree should be for torch

2023-06-05 08:39 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +    out=st.just(None),
No need to specify out if we have just generated `test_without`

2023-06-05 08:39 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +        test_with_out=test_with_out,
These should not be added here as they're included in test_flags

2023-06-05 08:39 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +        test_with_out=test_with_out,
These should not be added here as they're included in test_flags

2023-06-30 10:14 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-08 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-16 05:53 UTC, closed without merging

2023-07-16 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.