Igamma
unifyai/ivy pull request #15717
Opened 2023-05-20 19:07 UTC by selvaraj-sembulingam

2023-05-23 09:42 UTC, sherry30 requested changes
Hi,

Sorry for the late review. Your PR looks good but can you also add this function for `numpy` backend as well. And if its not too difficult, can you also add it to `paddle` backend.

Thanks

2023-05-23 10:46 UTC, selvaraj-sembulingam commented
@sherry30, I couldn't find direct implementations of igamma in numpy and paddle.

In the case of numpy, can I use scipy.special.gammainc ?

Can you provide some guidance on the paddle as well? Do I need to implement igamma using basic paddle functions?

Thanks,
Selvaraj

2023-05-23 13:11 UTC, sherry30 requested changes
You cannot use scipy for numpy's implementation. You'll have to implement it through numpy functions. You could get help from scipy's implementation if it is available on github. 
You can leave the paddle backend for now.

2023-05-23 13:11 UTC, sherry30 commented on ivy/functional/ivy/experimental/statistical.py
> +    ivy.Array instance method variant of ivy.igamma. This method simply wraps the
The description of the function

2023-05-24 16:41 UTC, sherry30 requested changes
Seems like the numpy backend is failing because there are some differences in the answer with the ground truth. If you think this is because of precision error then feel free to add `rtol_` or `atol_` in the test function. Bu to me it seems like the problem is with  the implementation, I haven't dived too deep into it. In case this is a problem with the implementation, you should try to fix it and let me know if you need help with anything. 

Thanks

2023-05-24 18:05 UTC, selvaraj-sembulingam commented
@sherry30 Thanks for pointing this out. There was indeed a minor mistake. Rectified it. The test cases are passing now.

Thanks

2023-05-25 08:16 UTC, sherry30 requested changes
Hi,

Thanks for fixing the numpy implementation.
After thinking it through, we should also add paddle paddle implementation since the tests run for this backend as well 😅. Sorry for not deciding this sooner but can you add that implementation as well. should be similar to numpy.
and feel free to ask anything if you have any questions as always.

Thanks

2023-05-25 17:35 UTC, selvaraj-sembulingam commented
@sherry30 Sure. I have implemented it for the paddle as well. But couldn't able to test it as there are a few config issues in ivy tests.

> ImportError while loading conftest 'E:\Ivy\ivy\ivy_tests\test_ivy\conftest.py'.
> ivy_tests\test_ivy\__init__.py:1: in <module>
>     from .. import config
> E   ImportError: cannot import name 'config' from 'ivy_tests' (E:\Ivy\ivy\ivy_tests\__init__.py)

Thanks

2023-05-26 09:46 UTC, sherry30 approved these changes
Im not sure why you're getting that error, probably some environment error.
It seems to be working fine on my end and all the tests are passing.

Thanks a lot for the contribution and your hard work 😄

2023-05-26 09:48 UTC, merged

2023-05-26 12:08 UTC, selvaraj-sembulingam commented
Thanks @sherry30 💯 😄