Adding support for where argument
unifyai/ivy pull request #15718
Opened 2023-05-20 19:33 UTC by soma2000-lang

2023-05-29 05:05 UTC, soma2000-lang commented
@VedPatwardhan I am generating the where argument in the test ,by  '''where=draw(st.lists(st.booleans(), min_size=1, max_size=100))''' because where is basically an array of boolean mask,but still the tests are fmiailing.I am facing difficulty in understanding what am I missing here.

2023-05-29 17:06 UTC, VedPatwardhan requested changes
Hey @soma2000-lang, I think the tests might be failing because the input array and the boolean mask (i.e. `where`) should have broadcastable shapes, which isn't guaranteed in the data generation of the `where` argument. Could you please update it so that the input arrays and `where` are broadcastable? Thanks @soma2000-lang 🙂

2023-06-19 16:36 UTC, soma2000-lang commented
Hi @vedpatwardhan  One update reagrding this issue ,I have updated my the tests for addition of the where argument and I dont think the failures are due to this addition ,as seen locally
![image](https://github.com/unifyai/ivy/assets/56045049/7246710f-36d2-42d3-be69-0831eee4f7dd)

2023-06-20 09:21 UTC, vedpatwardhan requested changes
> Hi @vedpatwardhan One update regarding this issue,I have updated the tests for the addition of the where argument and I don't think the failures are due to this addition, as seen locally, you can check the PR once for the updated where implementation.I have tried to fix some tests for the torch backend but still there are failures remaining. 

Hey @soma2000-lang, just requested a few changes, yeah the `KeyError` issue isn't related to your PR and is something being fixed at the moment. Thanks 🙂

2023-06-20 09:21 UTC, vedpatwardhan commented on ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
> +    dtype2, where = draw(
I think the test should be made more exhaustive by generating `where` argument of all broadcastable shapes from `shape`. We can use helpers like [this](https://github.com/unifyai/ivy/blob/5d237bccc2ca36927b3f170c81aae331a7406d47/ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py#L1698) or [this](https://github.com/unifyai/ivy/blob/5d237bccc2ca36927b3f170c81aae331a7406d47/ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py#L1670) to generate such shapes

2023-06-22 14:56 UTC, soma2000-lang commented on ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
> +def _ishelp(draw):
Sure!

2023-06-30 10:14 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-08 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-27 14:10 UTC, closed without merging