Add ihfft to numpy frontend
unifyai/ivy pull request #15738
Opened 2023-05-22 04:33 UTC by trgiangdo

Close #15707

In this PR:
- The `_SWAP_DIRECTION_MAP` and `_swap_direction(norm)` method are copied directly from numpy, since they are not implemented in the layers yet, and we are going to need these for the `hfft` frontend method in the future.
- The conversion test on Tenserflow is failing due to
  > small error with the backend implementation of tensorflow complex casting

  as mentioned in https://github.com/unifyai/ivy/pull/14451

2023-05-22 04:44 UTC, trgiangdo commented
I also have a question. The [`numpy.fft.ihfft`](https://numpy.org/doc/stable/reference/generated/numpy.fft.ihfft.html#numpy-fft-ihfft) does not exist before numpy 1.13, so I added the

```python
@with_unsupported_dtypes({"1.12.0 and below": ("float16",)}, "numpy")
def ihfft(...
```

Is this correct? Because it is different from the decorator on `rfft()`
```python
@with_unsupported_dtypes({"1.9.0 and below": ("float16",)}, "torch")
def rfft(...
```

2023-06-01 10:22 UTC, hirwa-nshuti requested changes
Hey would you first resolve the merge conflicts so I can be able to run the tests and will be jumping in to assist on this PR.
Thanks😊

2023-06-01 10:29 UTC, trgiangdo commented
Hello @hirwa-nshuti, sorry for the trouble, I entirely forgot about this PR for the last week.
I have rebase to master and resolve the conflicts. Thank you for assisting me with this PR.

2023-06-03 04:42 UTC, hirwa-nshuti approved these changes
Hey @trgiangdo 

Thanks for contributing all, looks good I'm going to merge the PR
Thanks😊

2023-06-03 04:43 UTC, merged