Add median to paddle.tensor.stat
unifyai/ivy pull request #15778
Opened 2023-05-23 05:03 UTC by SANTHOSHKAKARLA

2023-05-23 05:03 UTC, SANTHOSHKAKARLA commented
Close #15774

2023-05-24 10:34 UTC, KSANTHOSH200 commented
Hi @Aarsh2001,

Can you please review this PR?

Thanks.

2023-05-24 11:44 UTC, SANTHOSHKAKARLA commented
Hi @Aarsh2001,

Can you please review this PR?

Thanks.

2023-06-23 06:29 UTC, Aarsh2001 requested changes

2023-06-23 06:29 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_stat.py
> +    dtype_and_x=statistical_dtype_values(function="median"),
the function is `_statistical_dtype_values`

2023-06-28 06:10 UTC, Aarsh2001 commented
closing this PR due to inactivity, feel free to reopen once you're ready with your changes 🙂

2023-06-28 06:10 UTC, closed without merging