Updated Max pool1d
unifyai/ivy pull request #15776
Opened 2023-05-23 04:30 UTC by mtnvdsk

Adding max_pool1d #15775

2023-05-23 04:31 UTC, mtnvdsk commented
close #15776

2023-05-24 04:24 UTC, mtnvdsk commented
sir @kurshakuz , All the test cases are passing except a jax test case failure could you please guide me to rectify the error and code.

2023-05-26 12:31 UTC, CatB1t requested changes

2023-05-26 12:31 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +                new_kernel.append(kernel[i] + (kernel[i] - 1) * (dilations[i-1] - 1))
Hello @mtnvdsk , can you please explain the rationale behind those changes? what is the bug/issue you're trying to fix?

2023-06-20 07:45 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-20 07:45 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-01 05:53 UTC, closed without merging

2023-07-01 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.