add frontend for jax.numpy.fft.fft
unifyai/ivy pull request #15835
Opened 2023-05-24 15:33 UTC by farhanoktvn

Close #15832

2023-05-24 17:56 UTC, farhanoktvn commented
The test failed for tensorflow backend at:
```
ivy/functional/backends/tensorflow/experimental/layers.py:479: in _fft_norm
    return x / tf.sqrt(n)
```

with error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
```
```
NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]
```

I tried adding `with_unsupported_dtypes` for `int32` on tensorflow backend, but it didn't resolve the issue. Do you have any suggestion on how to approach this problem?

2023-05-31 09:46 UTC, hello-fri-end commented on ivy/functional/frontends/jax/numpy/fft.py
> +@with_unsupported_dtypes({"1.24.3 and below": ("complex64",)}, "numpy")
```suggestion
@with_unsupported_dtypes({"1.24.3 and below": ("complex64",)}, "jax")
```

2023-05-31 09:47 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft.py
> +        available_dtypes=helpers.get_dtypes("complex"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```
`valid` should be able to return all the data types supported by the function even if it's only complex.

2023-05-31 20:28 UTC, farhanoktvn commented
I now have some nan/inf values from the test results:
```
 AssertionError:  the results from backend tensorflow and ground truth framework jax do not match
E            [ 5.92515092e+291-1.12355821e+307j -1.06856736e+307-3.47198581e+306j
E                        -inf            +infj  6.60410946e+306+9.08977685e+306j
E             1.06856736e+307-3.47198581e+306j]!=[-2.00000000e+000-1.12355821e+307j -1.06856736e+307-3.47198581e+306j
E            -6.60410946e+306+9.08977685e+306j  6.60410946e+306+9.08977685e+306j
E             1.06856736e+307-3.47198581e+306j] 
```
and
```
[-1.88708839e+307-1.63426649e+308j  9.43544196e+306-1.47083984e+308j
E             9.43544196e+306            -infj]!=[-1.88708839e+307-1.63426649e+308j  9.43544196e+306-1.47083984e+308j
E                         nan            -infj]
```

2023-05-31 20:33 UTC, farhanoktvn commented
Also, I think there's an issue on `ivy/functional/backends/tensorflow/experimental/layers.py`.
```
def _fft_norm(
    x: Union[tf.Tensor, tf.Variable],
    dim: int,
    /,
    *,
    norm: str = "backward",
):
    n = tf.constant(x.shape[dim])
    if norm == "backward":
        return x
    elif norm == "ortho":
        return x / tf.sqrt(n)
    elif norm == "forward":
        return x / n
    else:
        raise ivy.utils.exceptions.IvyError(f"Unrecognized normalization mode {norm}")
```

When the norm is orthogonal, it returns _x_ divided by _tf.sqrt(n)_. However, _tf.sqrt_ does not accept _n_ as type int32. One possible way to solve this issue is to cast _n_, such that `n = tf.cast(n, x.dtype)`

2023-06-01 11:25 UTC, hello-fri-end requested changes

2023-06-01 11:27 UTC, hello-fri-end commented
> Also, I think there's an issue on `ivy/functional/backends/tensorflow/experimental/layers.py`.
> 
> ```
> def _fft_norm(
>     x: Union[tf.Tensor, tf.Variable],
>     dim: int,
>     /,
>     *,
>     norm: str = "backward",
> ):
>     n = tf.constant(x.shape[dim])
>     if norm == "backward":
>         return x
>     elif norm == "ortho":
>         return x / tf.sqrt(n)
>     elif norm == "forward":
>         return x / n
>     else:
>         raise ivy.utils.exceptions.IvyError(f"Unrecognized normalization mode {norm}")
> ```
> 
> When the norm is orthogonal, it returns _x_ divided by _tf.sqrt(n)_. However, _tf.sqrt_ does not accept _n_ as type int32. One possible way to solve this issue is to cast _n_, such that `n = tf.cast(n, x.dtype)`

Hey @farhanoktvn ! Thanks for opening this PR. There are few problems `ivy.fft` which I'm currently fixing in https://github.com/unifyai/ivy/pull/16135. Will let you know once it's merged so that we can figure out the problems in the frontends :)

2023-06-02 06:01 UTC, hello-fri-end commented on ivy/functional/frontends/jax/numpy/fft.py
> +    return ivy.astype(res, a.dtype)
```suggestion
    if norm == None:
       norm == 'backward
    return ivy.fft(a, axis, norm=norm, n=n)
```

2023-06-02 06:03 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft.py
> +    norm=st.sampled_from(["backward", "ortho", "forward"]),
```suggestion
    norm=st.sampled_from(["backward", "ortho", "forward", None]),
```
We should also test for `norm=None`

2023-06-02 06:03 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_fft.py
> +    test_with_out=st.just(False),
```suggestion
    test_with_out=st.just(False),
```
No need for this :)

2023-06-02 06:05 UTC, hello-fri-end commented
> > Also, I think there's an issue on `ivy/functional/backends/tensorflow/experimental/layers.py`.
> > ```
> > def _fft_norm(
> >     x: Union[tf.Tensor, tf.Variable],
> >     dim: int,
> >     /,
> >     *,
> >     norm: str = "backward",
> > ):
> >     n = tf.constant(x.shape[dim])
> >     if norm == "backward":
> >         return x
> >     elif norm == "ortho":
> >         return x / tf.sqrt(n)
> >     elif norm == "forward":
> >         return x / n
> >     else:
> >         raise ivy.utils.exceptions.IvyError(f"Unrecognized normalization mode {norm}")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When the norm is orthogonal, it returns _x_ divided by _tf.sqrt(n)_. However, _tf.sqrt_ does not accept _n_ as type int32. One possible way to solve this issue is to cast _n_, such that `n = tf.cast(n, x.dtype)`
> 
> Hey @farhanoktvn ! Thanks for opening this PR. There are few problems `ivy.fft` which I'm currently fixing in #16135. Will let you know once it's merged so that we can figure out the problems in the frontends :)

Hey @farhanoktvn ! The issues have been fixed. Once you update the code as per the changes I've suggested, you shouldn't get any errors. Feel free to request another review when it's done. Thanks :)

2023-06-20 08:08 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-20 14:16 UTC, farhanoktvn commented
Hello, Bot. I'm still working on this PR.

2023-06-22 11:19 UTC, hello-fri-end commented
> Hello, Bot. I'm still working on this PR.

Hey @farhanoktvn ! I have removed the stale label from the PR :)

2023-07-01 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-02 16:06 UTC, farhanoktvn commented
I'm still working on this, sry it takes a while

2023-07-25 20:38 UTC, closed without merging

2023-07-25 20:40 UTC, farhanoktvn commented
Syncing my repo to the updated directory tree.