equal frontend function
unifyai/ivy pull request #15852
Opened 2023-05-24 22:04 UTC by mustafaa7med

2023-05-24 23:26 UTC, mustafaa7med commented
Hello @Dsantra92,

I've looked into the 2 errors and i assume it is unrelated to the function, I assumed it is an import fail ```statistical_dtype_values```
Kindly advice

Thanks in advance,
Moustafa

2023-05-25 10:52 UTC, mustafaa7med commented
Hello @paulaehab,

I would be grateful if you could review my PR.

Thanks in advance,
Moustafa

2023-05-25 17:50 UTC, paulaehab requested changes

2023-05-25 17:50 UTC, paulaehab commented on ivy/functional/frontends/torch/tensor.py
> +    eq = equal
you don't need to add this as it must be added in separated issue

2023-05-25 17:50 UTC, paulaehab commented on ivy/functional/frontends/torch/tensor.py
> +    def equal(self, other, *, out=None):
equal function don't take this arguments 😄  please check the torch docs and change it after that be sure that all tests is passing

2023-05-25 17:51 UTC, paulaehab requested changes
after you correct changes and all tests pass I will merge it

2023-05-26 09:43 UTC, mustafaa7med commented
Hello @paulaehab,

Thank you for your input and help, I reviewed the parameters required for this function and adjusted them accordingly, Moreover, Thanks for the referencing, It got slipped from my mind.

Unfortunately, the PR keeps failing test(1) and I'm not entirely sure what seems to be the reason, Could you please advise?
https://github.com/unifyai/ivy/actions/runs/5088963429/jobs/9146020121?pr=15852#step:3:160

Thanks in advance,
Moustafa Ahmed

2023-05-28 05:44 UTC, mustafaa7med commented
@paulaehab Any advise?

2023-05-28 20:46 UTC, paulaehab commented
@mustafaa7med  Hello, the problem was because ivy.equal is elementwise but torch.equal is single output
so reduce all reduces it down to single True if every entry is True else False it solved by adding ivy.all around ivy.equal around ivy.equal in comparison.py I already add it for you and Ishtiaq help us here in the PR. 
I will merge it nice work 😄 .

2023-05-28 20:54 UTC, merged