Added less_equal function and test to Paddle frontend
unifyai/ivy pull request #15856
Opened 2023-05-25 05:02 UTC by whatzittoya

2023-05-29 15:25 UTC, KareemMAX commented
add_frontend_checklist

2023-05-29 16:00 UTC, KareemMAX requested changes
Hey @whatzittoya, awesome work 🚀

Sadly some check have been missing as you can see on the checklist I placed. Can you please address them?

Please note that you haven't passed any of the tests, also you didn't use `pre-commit` on linting

2023-05-29 16:00 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py
> +def test_tensorflow_less_equal(
Naming is not correct here 
```suggestion
def test_paddle_less_equal(
```

2023-06-08 19:35 UTC, KareemMAX requested changes
Hey @whatzittoya,
Seems like I wasn't paying attention, there is no function called `paddle.less_equal` thus it's failing all the tests. And it seems like you were implementing a method for `paddle.Tensor`. That means you didn't have the function nor the test in their right files. https://github.com/unifyai/ivy/pull/16195 might be a good place where you can see how are implementing it.

Sadly I'll be resetting the checklist

2023-06-08 19:35 UTC, KareemMAX commented
add_frontend_checklist

2023-06-20 08:07 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 18:05 UTC, closed without merging