log_softmax #15916
unifyai/ivy pull request #15925
Opened 2023-05-26 16:45 UTC by maher-mohsen

- [ ] #15916

2023-05-28 12:09 UTC, maher-mohsen commented
@AnnaTz could you review please, and help me to resolve conflicts cause i have no idea how can i reslove it

2023-05-29 09:24 UTC, AnnaTz commented
> * [ ]  [log_softmax #15916](https://github.com/unifyai/ivy/issues/15916)

Hi @maher-mohsen, please link this PR to issues in the corresponding paddle ToDo list. 
You are supposed to leave this kind of comments under the ToDo, not here. And since you are adding more than one functions you will need to add more than one comments.

2023-05-29 09:26 UTC, AnnaTz commented
> > * [ ]   [log_softmax #15916](https://github.com/unifyai/ivy/issues/15916)
> 
> Hi @maher-mohsen, please link this PR to issues in all corresponding paddle ToDo lists. Since you are adding more than one functions you will need to open more issues.

2023-05-29 09:33 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py
> +        y=x[1],
I missed this line when merging conflicts. Please remove the duplicate.

2023-05-29 09:34 UTC, AnnaTz commented
> > * [ ]    [log_softmax #15916](https://github.com/unifyai/ivy/issues/15916)
> 
> Hi @maher-mohsen, please link this PR to issues in all corresponding paddle ToDo lists. Since you are adding more than one functions you will need to open more issues.

Nevermind ignore this. I realized you didn't add `log` and `divide` yourself, it just seemed like you did due to your incorrect merge.

2023-05-29 09:50 UTC, AnnaTz requested changes

2023-05-29 09:50 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py
> +
The test is passing! 
Only thing to fix is a lint formatting error. Please have a look at `lint / Check formatting / check-formatting (pull_request)` in the CI checks at the bottom of the PR.

2023-05-29 11:46 UTC, maher-mohsen commented
@AnnaTz could you help me to fix current formatting issue because I don't understand it .

2023-05-29 11:49 UTC, maher-mohsen commented
@AnnaTz all done, ...ready to merge now

2023-05-29 11:56 UTC, merged