Add laplace Functional API
unifyai/ivy pull request #15936
Opened 2023-05-27 02:17 UTC by trgiangdo

Close #15742

In this PR, the functional API on paddlepaddle is commented out because there is no Laplace in paddle 2.4.2
But there will be in the next version (hopefully) since the class does exist in the develop branch.

2023-05-27 16:20 UTC, MahmoudAshraf97 requested changes
Hello, I have several comments please address them, in addition to those, try to use the functional API in each framework instead of creating a distribution and sampling from it

2023-05-27 16:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/jax/experimental/random.py
> +    jax.numpy.broadcast_shapes(loc.shape, scale.shape)
```suggestion
```

2023-05-27 16:20 UTC, MahmoudAshraf97 commented on ivy/data_classes/array/experimental/random.py
> +        ----------
please add the instance method prefix to the docstring

2023-05-27 16:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/mxnet/experimental/random.py
you need to implement the mxnet function

2023-05-27 16:20 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/random.py
you need to implement the paddle function, as we support multiple versions of the frameworks so you can use a compositional implementation for now

2023-05-28 16:27 UTC, trgiangdo commented on ivy/functional/backends/mxnet/experimental/random.py
I'm trying to implement this and test it, but it might take a while since installing `mxnet` on Mac M1 is such a pain 🥲

However, I see that no other distribution is implemented with MXNet. So I'm not sure if it may cause problems in the future.

2023-05-28 16:28 UTC, trgiangdo commented on ivy/functional/backends/paddle/experimental/random.py
Hi, as stated in [this page](https://unify.ai/docs/ivy/overview/deep_dive/function_types.html#compositional-functions), a compositional implementation requires the function to be able to use other ivy API.

However, I'm not sure how to sample from a Laplace distribution from other ivy API (from other distribution). I will try my best.

2023-05-28 16:31 UTC, trgiangdo commented
Hello @MahmoudAshraf97, thank you for your quick review. I have answer to your comments and trying to fix the problems.

Also,
> in addition to those, try to use the functional API in each framework instead of creating a distribution and sampling from it

I don't understand what you mean by *"use the functional API in each framework"*, since sampling from a distribution is the usage in most backend doc (TF, Paddle, Torch), or I may miss something. Other experimental distributions are also using the same method.
Can you help me clarify this point?

2023-05-29 03:19 UTC, trgiangdo commented on ivy/functional/backends/mxnet/experimental/random.py
`mx.np.random.laplace` will be supported with the release of mxnet2.0. Also, the `loc` and `scale` is only supported as float, not an array.

So I guess the best solution for now is a compositional API as well. But again, I'm not sure if this is possible as a random function.

2023-06-19 10:30 UTC, MahmoudAshraf97 commented
Hey @trgiangdo , How are thing going?

2023-06-19 10:32 UTC, trgiangdo commented
I implemented laplace as compositional function. I think it is ready for you to review.

2023-07-08 17:12 UTC, MahmoudAshraf97 requested changes
I extremelly apologize for the delay in review

2023-07-08 17:12 UTC, MahmoudAshraf97 commented on ivy/functional/ivy/experimental/random.py
> +        low=float(np.nextafter(-1, 1)) + eps / 2,
we can't use np functions in ivy implementations, only ivy functions

2023-07-17 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-24 05:53 UTC, closed without merging

2023-07-24 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.