diag
unifyai/ivy pull request #15955
Opened 2023-05-27 13:06 UTC by Sarvesh-Kesharwani

Closed #15944

2023-05-27 13:07 UTC, Sarvesh-Kesharwani commented
Need help with the padding value test data generation, everything else is working as expected (tested the function keeping p=st.just(0), with composite strategy), need to generate numeric(int, float) values for it.

2023-06-02 11:48 UTC, hmahmood24 requested changes
Hey @Sarvesh-Kesharwani. Reviewed the PR and left comments you can refer to, to improve your implementation. Ask for a re-review once you're done. Thanks! 👍🏼

2023-06-02 11:48 UTC, hmahmood24 commented on ivy/functional/frontends/paddle/tensor/creation.py
> +    return d
Try implementing this using `ivy.diagflat` instead. It handles the padding argument for you

2023-06-02 11:48 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_creation.py
> +    p=st.floats(0, 1),
You can combine multiple strategies using the `st.one_of(..)` strategy. Include the strategies for generating integers `helpers.ints(...)` and `helpers.floats(...)` inside `st.one_of` for pickling randomly from either of these strategies and drawing the test data from that on runtime

2023-06-20 07:47 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-06-28 05:53 UTC, closed without merging

2023-06-28 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.