Add 'native_sparse_array' and 'native_sparse_array_to_indices_values_…
unifyai/ivy pull request #15973
Opened 2023-05-28 03:35 UTC by metric-space

close #10703 

# Testing
seems like the testing of this is covered here: `ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_sparse_array.py`

2023-05-28 04:06 UTC, metric-space commented
I think some tests are failing because of the lack of formats that are available in other non-paddle backends. Formats like `bsr` and `csc` at the moment isn't supported by paddle. Still thinking about how to go about this :thinking:

2023-05-30 03:25 UTC, metric-space commented
Update: I believe I figured out a way around the paddle unsupported sparse formats. The remaining failures seem to do with this reproducible error (I do not know if bug or not)

``` python
import ivy
import paddle
ivy.set_backend('paddle')

a = ivy.array([1,2,3,4,5])
ivy.flatten(a)

```
the error is 
```
During the handling of the above exception, another exception occurred:

  File "<stdin>", line 1, in <module>
  File "/home/user/ivy/ivy/utils/exceptions.py", line 128, in _handle_exceptions
    raise ivy.utils.exceptions.IvyError(fn.__name__, str(e))

IvyError: paddle: flatten: The input x should be a Tensor
```
this creeps up in within the `SparseArray` class's `to_dense_array` method

The stack trace is pretty clear, wondering why the conversion to paddle's tensor type isn't happening. Still investigating

2023-06-08 07:50 UTC, MahmoudAshraf97 commented
hello @metric-space and sorry for the delay, the code in the previous comment should be working fine now

2023-06-09 02:57 UTC, metric-space commented
@MahmoudAshraf97 hello there again, was hoping if you could give this PR a review please

2023-06-18 09:02 UTC, MahmoudAshraf97 requested changes

2023-06-18 09:02 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/sparse_array.py
> +    dtype=None,
```suggestion

```
please make sure the function signature is consistent across ivy

2023-06-26 05:52 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-01 11:54 UTC, MahmoudAshraf97 approved these changes

2023-07-01 11:54 UTC, merged