add
unifyai/ivy pull request #15986
Opened 2023-05-28 16:25 UTC by rohinish404

closes #15981

2023-05-28 17:40 UTC, ZiadAmerr commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py
> +        available_dtypes=helpers.get_dtypes("float"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```

2023-05-28 17:40 UTC, ZiadAmerr commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_math.py
> +        shared_dtype=True,
@MahmoudAshraf97 Should we use a shared dtype here? Should tensor math functions handle different dtypes?

2023-05-28 17:41 UTC, ZiadAmerr requested changes
Amazing work! Just a few changes and if the tests pass we will proceed with the merge :)

2023-05-28 17:45 UTC, rohinish404 commented
> Amazing work! Just a few changes and if the tests pass we will proceed with the merge :)

Yeah sure!! Do i need to make any changes from my side?

2023-05-28 17:53 UTC, ZiadAmerr commented
Nope, LGTM! We will just wait for Mahmoud's approval on this, and if we changing it to `shared_dtypes=False` and the tests pass, we will proceed with the merge :)

2023-06-02 20:40 UTC, ZiadAmerr requested changes
Amazing work, @rohinish404! Just this final comment and we are ready to merge.

Sorry for the late review though; I thought I had requested changes this whole time but I have just realized I didn't.

2023-06-02 21:07 UTC, rohinish404 commented
Should i first have to resolve conflicts?

2023-06-02 22:19 UTC, ZiadAmerr commented
No, we can leave that until everything is ready to merge and the checks are passing, then you can resolve the conflicts

2023-06-02 22:27 UTC, rohinish404 commented
How can i modify the code then? Can't push the changes;)

2023-06-02 23:22 UTC, ZiadAmerr approved these changes
LGTM! Amazing work, thanks a lot @rohinish404, will merge right after the test checks show that the tests are passing :)

2023-06-02 23:22 UTC, ZiadAmerr commented
Please resolve the conflicts now :)

2023-06-03 00:04 UTC, ZiadAmerr commented
Hey, looks like your function was taken over by another PR due to the comment on the tasks page wasn't in the standard format, you commented `Add` instead of `add` so it was not linked to the actual `add` function in the ToDo tasks. I will merge this PR and then remove the accidental problems myself, thanks a lot for your contribution :)

2023-06-03 00:05 UTC, ZiadAmerr commented on ivy/functional/frontends/paddle/tensor/math.py
> +
```suggestion
```

2023-06-03 00:05 UTC, ZiadAmerr approved these changes

2023-06-03 02:56 UTC, rohinish404 commented
Thank you so much for the help @ZiadAmerr !!!

2023-06-03 03:07 UTC, merged