fixed l1_normalize showing disprancy with jax and numpy
unifyai/ivy pull request #16015
Opened 2023-05-29 14:19 UTC by akshatvishu

The current version of `l1_normalize` is showing discrepancy between `numpy` , `jax` v/s `torch`, `tf` backends.

```python
import jax
import jax.numpy as jnp
import paddle
import torch
import tensorflow as tf
import ivy
import ivy.functional.frontends.tensorflow as tf_frontend
import ivy.functional.backends.jax as jb
import ivy.functional.backends.numpy as nb 
import ivy.functional.backends.torch as tb 
import ivy.functional.backends.tensorflow as tfb 
import ivy.functional.backends.paddle as pb

a = nb.experimental.l1_normalize(np.array([[-1., -1.], [-1., -2.]], dtype=np.float32), axis=0)
print(f"numpy output: {a}")

b = tfb.experimental.l1_normalize(tf.constant([[-1., -1.], [-1., -2.]], dtype=tf.float32), axis=0)
print(f"tf output: {b}")

c = ivy.experimental.l1_normalize(ivy.array([[-1., -1.], [-1., -2.]], dtype=ivy.float32), axis=0)
print(f"ivy output: {c}")

d = jb.experimental.l1_normalize(jax.numpy.array([[-1., -1.], [-1., -2.]], dtype=jax.numpy.float32), axis=0)
print(f"jax output: {d}")

e = tb.experimental.l1_normalize(torch.tensor([[-1., -1.], [-1., -2.]], dtype=torch.float32), axis=0)
print(f"torch output: {e}")

f = pb.experimental.l1_normalize(paddle.to_tensor([[-1., -1.], [-1., -2.]], dtype=paddle.float32), axis=0)
print(f"paddle output: {f}")

"""
numpy output: 
[[-0.5        -0.33333334]
 [-0.5        -1.3333334 ]]

tf output: 
[[-0.5        -0.33333334]
 [-0.5        -0.6666667 ]]

ivy output: 
ivy.array([[-0.5       , -0.33333334],
       [-0.5       , -1.33333337]])

jax output: 
[[-0.5        -0.33333334]
 [-0.5        -1.3333334 ]]

torch output: 
tensor([[-0.5000, -0.3333],
        [-0.5000, -0.6667]])

paddle output: Tensor(shape=[2, 2], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[-0.50000000, -0.33333334],
        [-0.50000000, -0.66666669]])
"""
```

2023-05-31 15:52 UTC, akshatvishu commented
Hey @MahmoudAshraf97   I don't why this PR added label `paddle backend` because I think this is more related to other `ivy backend` in-general ! I didn't even touch `paddle` backend implementation because it was working fine

2023-06-05 13:36 UTC, MahmoudAshraf97 requested changes

2023-06-05 13:36 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_norms.py
Why are these changes necessary?

2023-06-05 13:36 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/norms.py
why is float16 not supported? you can use functions from ivy paddle backend to mitigate this

2023-06-05 13:36 UTC, MahmoudAshraf97 commented on ivy/functional/backends/jax/experimental/norms.py
> +        denorm = jnp.maximum(denorm, 1e-12)
this is not needed since you can divide by 0

2023-06-05 13:36 UTC, MahmoudAshraf97 commented on ivy/functional/backends/numpy/experimental/norms.py
> +        denorm = np.maximum(denorm, 1e-12)
same as jax

2023-06-12 06:33 UTC, akshatvishu commented on ivy/functional/backends/paddle/experimental/norms.py
Hey @MahmoudAshraf97  I am very sorry for replying so late(I was on a vacation ) . The `float16` is not supported by [paddle.linalg.norm](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/linalg/norm_en.html#norm) hence, I added it to `unsupported_dtypes`

2023-06-12 06:35 UTC, akshatvishu commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_norms.py
Tests were failing with the updated changes hence, I need to tweak the test to make it work!

2023-06-12 07:03 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/norms.py
You should fix the failure then not change the test 😁

2023-06-12 07:04 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_norms.py
You should fix the failure then not change the test 😁
Mainly you need to test for all dtypes not just float

2023-06-22 08:06 UTC, MahmoudAshraf97 requested changes

2023-06-22 16:58 UTC, akshatvishu commented on ivy/functional/backends/tensorflow/experimental/norms.py
> +)
I  passed the wrong supported `dypes` ; as [tf.norm](https://www.tensorflow.org/api_docs/python/tf/norm) only accepts ` float32, float64, complex64, complex128`. Thus, I  still  kept the `with_supported_device_and_dtypes`

2023-06-30 10:14 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-01 12:07 UTC, MahmoudAshraf97 requested changes

2023-07-01 12:07 UTC, MahmoudAshraf97 commented on ivy/functional/backends/jax/experimental/norms.py
> +    denorm = jnp.linalg.norm(x, 1, axis, keepdims=True)
You need to handle the case when `axis=None` as this function accepts None axes only when the array is less than 3D

2023-07-09 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-17 05:53 UTC, closed without merging

2023-07-17 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.