dot function for paddle.tensor.linalg
unifyai/ivy pull request #16148
Opened 2023-06-01 14:32 UTC by benkimz

Close #16133

2023-06-02 08:16 UTC, jkeane508 requested changes
Hello,

For this task, you also need to write a test in the appropriate location of our testing suite.

Thanks!

2023-06-02 11:27 UTC, benkimz commented
> Hello,
> 
> For this task, you also need to write a test in the appropriate location of our testing suite.
> 
> Thanks!

Hi, I have added a test for the paddle.tensor.linalg.dot function.
Thank you

2023-06-03 04:52 UTC, benkimz commented
> > Hello,
> > For this task, you also need to write a test in the appropriate location of our testing suite.
> > Thanks!
> 
> Hi, I have added a test for the paddle.tensor.linalg.dot function. Thank you

You can review the changes.

2023-06-05 19:51 UTC, jkeane508 requested changes
Hellp

It looks like tests are failing for input dimensions here - https://github.com/unifyai/ivy/actions/runs/5179793914/jobs/9333151706?pr=16148#step:3:642

We should aim to have the test you've written passing before we can merge :)

Thanks

2023-06-07 08:53 UTC, jkeane508 requested changes
It looks as though the test is failing here - https://github.com/unifyai/ivy/actions/runs/5195848323/jobs/9368968211?pr=16148#step:3:244

It seems you are passing the keyword "axis" when it's not a parameter.

2023-06-07 08:53 UTC, jkeane508 commented on ivy/functional/frontends/paddle/tensor/linalg.py
> +# cross
Im not sure why this was added to the code, but I don't think its necessary

2023-06-07 11:00 UTC, closed without merging