adding logical_not to paddle
unifyai/ivy pull request #16145
Opened 2023-06-01 13:21 UTC by ahmadel1

Fixes #16126

2023-06-01 14:05 UTC, ahmadel1 commented
please review this PR @hmahmood24

2023-06-02 11:59 UTC, hmahmood24 requested changes
Hey @ahmadel1. Thanks for making the PR. I've reviewed it and left a few comments for you to address. Additionally, the PR is failing some [lint/formatting checks](https://github.com/unifyai/ivy/actions/runs/5144962653/jobs/9261940735?pr=16145#step:5:103) so can you please fix those as well? Kindly ask for a re-review from me once you're done. Thanks 😃

2023-06-02 11:59 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_logic.py
> +        available_dtypes=helpers.get_dtypes("valid"), num_arrays=1, shared_dtype=True
The `num_arrays` is set to `1` by default so you can remove that. The `shared_dtype` argument is used when we are generating more than `1` arrays so you can remove that as well.

2023-06-02 14:42 UTC, ahmadel1 commented
@hmahmood24  Could you please re-review my PR? Your feedback is highly appreciated

2023-06-04 08:40 UTC, hmahmood24 approved these changes

2023-06-04 08:41 UTC, hmahmood24 commented
Everything looks good to merge now. Thanks so much for the PR @ahmadel1! 🚀

2023-06-04 08:41 UTC, merged