Added hardtanh activation function and test to PaddlePaddle frontend
unifyai/ivy pull request #16192
Opened 2023-06-02 16:29 UTC by sachelsout

Close #16189

2023-06-03 09:57 UTC, Daniel4078 requested changes
I think that you should mimik how the selu function above write its function signature, specifically how it specifes that some arguments that include name are optional keyword_only arguments.

2023-06-03 09:57 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/activation.py
> +def hardtanh(x, min=-1.0, max=1.0):
I think that you should mimik how the selu function above write its function signature, specifically how it specifes that some arguments that include name are optional keyword_only arguments.

2023-06-03 13:39 UTC, sachelsout commented
> I think that you should mimik how the selu function above write its function signature, specifically how it specifes that some arguments that include name are optional keyword_only arguments.

Yes, I completely missed 'name' argument. I'll make changes right now. :)

2023-06-04 07:50 UTC, Daniel4078 approved these changes
looks good to me!

2023-06-04 07:50 UTC, merged