tf_not_equal fix
unifyai/ivy pull request #16288
Opened 2023-06-05 18:15 UTC by mobley-trent

Closes #15615

2023-06-05 19:42 UTC, mobley-trent commented
The paddle backend for `not_equal` only supports float32, float64, int32 and int64. This is what caused the test failure for paddle

2023-06-07 06:19 UTC, mobley-trent commented
@hirwa-nshuti

2023-06-07 06:59 UTC, hirwa-nshuti requested changes
Hey @mobley-trent 

Would you check thoroughly all supported dtypes

2023-06-07 06:59 UTC, hirwa-nshuti commented on ivy/functional/frontends/tensorflow/math.py
> +@with_supported_dtypes(
I think these are not only supported dtypes 😅
```python
import tensorflow as tf
print(tf.math.not_equal(tf.constant([-1.2+1.2j, 0.0+0.0j, 1.5+1.5j]), tf.constant([-1.2+1.2j, 0.0+0.0j, 1.5+1.5j])))
```

2023-06-07 07:12 UTC, hirwa-nshuti commented on ivy/functional/frontends/tensorflow/math.py
> +    {"2.9.0 and below": ("float32", "float64", "int32", "int64")},
The version is 2.12.0

2023-06-07 09:05 UTC, mobley-trent commented
@hirwa-nshuti I set the valid dtypes in the test and removed the decorator entirely

2023-06-08 12:51 UTC, hirwa-nshuti commented
Hey @mobley-trent can you try to update the branch so that the CI check should run

2023-06-09 05:10 UTC, merged