added thresholded_relu activation function and test for PaddlePaddle frontend
unifyai/ivy pull request #16346
Opened 2023-06-06 21:02 UTC by sachelsout

Close #16345

2023-06-12 11:04 UTC, kurshakuz requested changes
Hey! Your implementation is currently failing and throwing the following error. Can you resolve it? Thanks!

```ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py:361: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py:377: in test_paddle_thresholded_relu
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:608: in test_frontend_function
    ret = get_frontend_ret(
ivy_tests/test_ivy/helpers/function_testing.py:1774: in get_frontend_ret
    ret = frontend_fn(*args, **kwargs)
ivy/functional/frontends/paddle/func_wrapper.py:48: in new_fn
    ret = fn(*args, **kwargs)
ivy/functional/frontends/paddle/func_wrapper.py:78: in new_fn
    return fn(*new_args, **new_kwargs)
ivy/functional/frontends/paddle/nn/functional/activation.py:131: in thresholded_relu
    return ivy.where(ivy.greater(x, threshold), x, 0).astype(x.dtype)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (ivy.array(False), ivy.array(-1.), 0), kwargs = {}

    @functools.wraps(fn)
    def _handle_exceptions(*args, **kwargs):
        """
        Catch all exceptions and raise them in IvyException.
    
        Parameters
        ----------
        args
            The arguments to be passed to the function.
    
        kwargs
            The keyword arguments to be passed to the function.
    
        Returns
        -------
            The return of the function, or raise IvyException if error is thrown.
        """
        try:
            return fn(*args, **kwargs)
        # Not to rethrow as IvyBackendException
        except IvyNotImplementedException as e:
            raise e
        except IvyError as e:
            _write_traceback_history(buffer)
            raise ivy.utils.exceptions.IvyError(
                fn.__name__, buffer.getvalue() + " " + str(e), include_backend=True
            )
        except IvyBroadcastShapeError as e:
            _write_traceback_history(buffer)
            raise ivy.utils.exceptions.IvyBroadcastShapeError(
                fn.__name__, buffer.getvalue() + " " + str(e), include_backend=True
            )
        except IvyDtypePromotionError as e:
            _write_traceback_history(buffer)
>           raise ivy.utils.exceptions.IvyDtypePromotionError(
                fn.__name__, buffer.getvalue() + " " + str(e), include_backend=True
            )
E           ivy.utils.exceptions.IvyDtypePromotionError: paddle: where:   File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/func_wrapper.py", line 955, in _handle_nestable
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/func_wrapper.py", line 392, in _handle_array_like_without_promotion
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/func_wrapper.py", line 849, in _handle_out_argument
E               return fn(*args, out=out, **kwargs)
E             File "/workspaces/ivy/ivy/func_wrapper.py", line 432, in _inputs_to_native_arrays
E               return fn(*new_args, **new_kwargs)
E             File "/workspaces/ivy/ivy/func_wrapper.py", line 531, in _outputs_to_ivy_arrays
E               ret = fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/func_wrapper.py", line 349, in _handle_array_function
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/backends/paddle/searching.py", line 151, in where
E               x1, x2, ret_dtype = _elementwise_helper(x1, x2)
E             File "/workspaces/ivy/ivy/functional/backends/paddle/elementwise.py", line 16, in _elementwise_helper
E               x1, x2 = ivy.promote_types_of_inputs(x1, x2)
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           During the handling of the above exception, another exception occurred:
E            paddle: promote_types_of_inputs:   File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 2409, in promote_types_of_inputs
E               promoted = promote_types(
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           During the handling of the above exception, another exception occurred:
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 2409, in promote_types_of_inputs
E               promoted = promote_types(
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           During the handling of the above exception, another exception occurred:
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 2409, in promote_types_of_inputs
E               promoted = promote_types(
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           During the handling of the above exception, another exception occurred:
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 2409, in promote_types_of_inputs
E               promoted = promote_types(
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           During the handling of the above exception, another exception occurred:
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 2409, in promote_types_of_inputs
E               promoted = promote_types(
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           During the handling of the above exception, another exception occurred:
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 2409, in promote_types_of_inputs
E               promoted = promote_types(
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           During the handling of the above exception, another exception occurred:
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 210, in _handle_exceptions
E               return fn(*args, **kwargs)
E             File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 2409, in promote_types_of_inputs
E               promoted = promote_types(
E             File "/workspaces/ivy/ivy/utils/exceptions.py", line 226, in _handle_exceptions
E               raise ivy.utils.exceptions.IvyDtypePromotionError(
E           Dur [...]

2023-06-12 12:17 UTC, kurshakuz requested changes
It now throws another error as here:

```
E           RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int8) of kernel `thresholded_relu` is not registered.
E             [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:147)
E           
E           Falsifying example: test_paddle_thresholded_relu(
E               dtype_and_x=(['int8'], [array(0, dtype=int8)]),
E               threshold=1.0,
E               test_flags=FrontendFunctionTestFlags(
E                   num_positional_args=0,
E                   with_out=False,
E                   inplace=False,
E                   as_variable=[False],
E                   native_arrays=[False],
E                   generate_frontend_arrays=False,
E               ),
E               fn_tree='ivy.functional.frontends.paddle.nn.functional.thresholded_relu',
E               on_device='cpu',
E               frontend='paddle',
E           )
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2NABYwQCgAAqAAI') as a decorator on your test case

/usr/local/lib/python3.8/dist-packages/paddle/nn/functional/activation.py:1530: RuntimeError
```

Please test out your implementation locally and request a new review after.

2023-06-12 12:22 UTC, sachelsout commented
> It now throws another error as here:
> 
> ```
> E           RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int8) of kernel `thresholded_relu` is not registered.
> E             [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:147)
> E           
> E           Falsifying example: test_paddle_thresholded_relu(
> E               dtype_and_x=(['int8'], [array(0, dtype=int8)]),
> E               threshold=1.0,
> E               test_flags=FrontendFunctionTestFlags(
> E                   num_positional_args=0,
> E                   with_out=False,
> E                   inplace=False,
> E                   as_variable=[False],
> E                   native_arrays=[False],
> E                   generate_frontend_arrays=False,
> E               ),
> E               fn_tree='ivy.functional.frontends.paddle.nn.functional.thresholded_relu',
> E               on_device='cpu',
> E               frontend='paddle',
> E           )
> E           
> E           You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2NABYwQCgAAqAAI') as a decorator on your test case
> 
> /usr/local/lib/python3.8/dist-packages/paddle/nn/functional/activation.py:1530: RuntimeError
> ```
> 
> Please test out your implementation locally and request a new review after.

I did tested the code locally and all 5 tests are passing.

2023-06-13 11:14 UTC, sachelsout commented
> > It now throws another error as here:
> > ```
> > E           RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int8) of kernel `thresholded_relu` is not registered.
> > E             [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:147)
> > E           
> > E           Falsifying example: test_paddle_thresholded_relu(
> > E               dtype_and_x=(['int8'], [array(0, dtype=int8)]),
> > E               threshold=1.0,
> > E               test_flags=FrontendFunctionTestFlags(
> > E                   num_positional_args=0,
> > E                   with_out=False,
> > E                   inplace=False,
> > E                   as_variable=[False],
> > E                   native_arrays=[False],
> > E                   generate_frontend_arrays=False,
> > E               ),
> > E               fn_tree='ivy.functional.frontends.paddle.nn.functional.thresholded_relu',
> > E               on_device='cpu',
> > E               frontend='paddle',
> > E           )
> > E           
> > E           You can reproduce this example by temporarily adding @reproduce_failure('6.70.0', b'AXicY2NABYwQCgAAqAAI') as a decorator on your test case
> > 
> > /usr/local/lib/python3.8/dist-packages/paddle/nn/functional/activation.py:1530: RuntimeError
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please test out your implementation locally and request a new review after.
> 
> ![image](https://user-images.githubusercontent.com/86348193/245144216-20a88742-52c3-4ba1-bfc7-22233db65bc0.png)
> 
> I did tested the code locally and all 5 tests are passing. Also, in this error, its mentioning about 'int8' dtype. But I haven't used int8. I've just used float32 and float64 (supported_dtypes)

@kurshakuz

2023-06-14 09:54 UTC, sachelsout commented
Hi @kurshakuz , till now, test cases were passing. Only 1 was failing, which we are aware of. But right now I requested for a review and a lot of test cases started failing. I haven't made any changes in my code. Also, test cases are passing locally.

2023-06-21 21:09 UTC, sachelsout commented
Hi @kurshakuz , could you please review my PR ?

2023-07-01 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-01 10:30 UTC, kurshakuz reviewed
I keep getting the `KeyError: 'cpu'` error. Can you please run your test locally and show me the output? Thanks!

2023-07-02 15:04 UTC, sachelsout commented
> I keep getting the `KeyError: 'cpu'` error. Can you please run your test locally and show me the output? Thanks!

Hi @kurshakuz , even I am getting the same error while running the tests for thresholded relu.

![image](https://github.com/unifyai/ivy/assets/86348193/a434a1da-7af3-403f-9b29-ad7fb50358b7)

I haven't change the code. The tests used to pass successfully before (locally as well as CI tests)

![image](https://github.com/unifyai/ivy/assets/86348193/c83c5722-6b4f-4c26-b227-a705c278df70)

2023-07-06 20:30 UTC, sachelsout commented
Hi @kurshakuz , I updated the paddle version and now all the test cases are passing for thresholded relu function. 😄

![image](https://github.com/unifyai/ivy/assets/86348193/0cb530e8-35a5-4035-920c-629a3dbb2886)

2023-07-12 09:43 UTC, sachelsout commented
Hi @kurshakuz , could you please review my PR ? 😃

2023-07-21 14:48 UTC, kurshakuz approved these changes
LGTM! Can you please resolve the conflict? I will then merge your PR

2023-07-21 19:49 UTC, sachelsout commented
@kurshakuz , merge conflicts resolved ! 😃

2023-08-04 04:37 UTC, kurshakuz commented
@sachelsout I am sorry for a delay! Can you please resolve it once again? I will merge it right away! Thanks!

2023-08-11 13:24 UTC, sachelsout commented
Hi @kurshakuz , apologies for the delay. I've resolved the merge conflicts and changed the paddle version as well.
Thank you.

2023-09-19 10:20 UTC, sachelsout commented
Hi @kurshakuz , I've resolved merge conflicts and tested the function locally again. But this time, I am getting 'keyError: CPU' for one of the test case. I am getting the same error for other functions as well.

2023-12-01 22:26 UTC, closed without merging