Fixing __repr__ function in array
unifyai/ivy pull request #16381
Opened 2023-06-07 13:37 UTC by abdulasiraj

closes https://trello.com/c/SH9tX7ni

2023-06-08 17:14 UTC, VedPatwardhan requested changes
Hey @abdulasiraj, thanks for taking on this task! Just requested a few changes 🙂

2023-06-08 17:14 UTC, VedPatwardhan commented on ivy/data_classes/array/array.py
> +from time import perf_counter
Probably an import left over from debugging, could you please remove it?

2023-06-08 17:14 UTC, VedPatwardhan commented on ivy/data_classes/array/array.py
> +        # print('in the get attr function')
could you please remove this comment too?

2023-06-12 10:46 UTC, abdulasiraj commented on ivy/data_classes/array/array.py
> -        rep = ivy.vec_sig_fig(arr_np, sig_fig) if self.size > 0 else np.array(arr_np)
these lines can be removed safely.

2023-06-13 07:02 UTC, VedPatwardhan requested changes
Hey @abdulasiraj, just suggested a few more changes, thanks 🙂

2023-06-13 07:02 UTC, VedPatwardhan commented on ivy/data_classes/array/array.py
> +        dec_vals = ivy.array_decimal_values()
please revert the change to `dec_vals` as `ivy.array_decimal_values` isn't a function

2023-06-13 07:02 UTC, VedPatwardhan commented on ivy/data_classes/array/array.py
> -        rep = ivy.vec_sig_fig(arr_np, sig_fig) if self.size > 0 else np.array(arr_np)
Actually if you check the code, `ivy.array_significant_figures` allows users to decide the number of significant figures they'd like to be concerned about. Based on the number of significant figures defined by the user, we would be able to control the number of significant figures. Removing the use of `ivy.vec_sig_fig` loses that control.
For e.g. the below code returns the following result without the changes,
```
import ivy

ivy.set_array_significant_figures(5)
x = ivy.array([1.23124353453634634636])
print(x)
ivy.set_array_significant_figures(10)
print(x)
```
```
ivy.array([1.2312])
ivy.array([1.23124349])
```
while with the changes, it's the following,
```
ivy.array([1.2312435])
ivy.array([1.2312435])
```
We should aim to optimize the `__repr__` method of course, but we'd also want to retain that control 😅

2023-06-13 08:14 UTC, abdulasiraj commented on ivy/data_classes/array/array.py
> -        rep = ivy.vec_sig_fig(arr_np, sig_fig) if self.size > 0 else np.array(arr_np)
Oh, my bad. Thanks, I'll look into this.

2023-06-15 17:13 UTC, abdulasiraj commented
Hi @VedPatwardhan.

This PR is ready to review. Slow down occurs due to the expensive computation of significant figures. With the help @kgmann and [this](https://stackoverflow.com/questions/18915378/rounding-to-significant-figures-in-numpy) thread on stackoverflow. Things are now under controlled.

2023-06-17 07:32 UTC, vedpatwardhan requested changes
Hey @abdulasiraj, thanks for making the changes, just a couple more changes with some formatting issues that can be fixed using `pre-commit` 🙂

2023-06-17 07:32 UTC, vedpatwardhan commented on ivy/__init__.py
> +def sf(x, sig_fig=3):
let's rename this function to something verbose for code clarity, probably just `vec_sig_fig`

2023-06-17 07:32 UTC, vedpatwardhan commented on ivy/data_classes/array/array.py
> +
extra newline

2023-06-17 07:32 UTC, vedpatwardhan commented on ivy/data_classes/array/array.py
> +        return iter([to_ivy(i) for i in self._data])
missing newline here

2023-06-17 08:09 UTC, vedpatwardhan commented
ivy-gardener

2023-06-18 08:03 UTC, vedpatwardhan requested changes
> Actually if you check the code, `ivy.array_significant_figures` allows users to decide the number of significant figures they'd like to be concerned about. Based on the number of significant figures defined by the user, we would be able to control the number of significant figures. Removing the use of `ivy.vec_sig_fig` loses that control. For e.g. the below code returns the following result without the changes,
> 
> ```
> import ivy
> 
> ivy.set_array_significant_figures(5)
> x = ivy.array([1.23124353453634634636])
> print(x)
> ivy.set_array_significant_figures(10)
> print(x)
> ```
> 
> ```
> ivy.array([1.2312])
> ivy.array([1.23124349])
> ```
> 
> while with the changes, it's the following,
> 
> ```
> ivy.array([1.2312435])
> ivy.array([1.2312435])
> ```
> 
> We should aim to optimize the `__repr__` method of course, but we'd also want to retain that control 😅

The changes made don't seem to break anything, but the example I shared previously still doesn't seem to work properly with the changes, probably there's some fixes to be made to the logic. Thanks @abdulasiraj 🙂

2023-06-20 07:44 UTC, vedpatwardhan approved these changes
One last change, feel free to merge the PR once done. Thanks @abdulasiraj 🙂

2023-06-20 07:44 UTC, vedpatwardhan commented on ivy/data_classes/array/array.py
> +        arr_np = ivy.vec_sig_fig(arr_np, sig_fig) if self.size > 0 else np.array(arr_np)
we could probably rename this back to `rep`

2023-06-20 07:59 UTC, merged