Fix reptile_step implementation
unifyai/ivy pull request #16440
Opened 2023-06-08 17:23 UTC by abbasaliii

This pull request fixes the implementation of the reptile_step function in the meta.py file. The function was refactored according to the Deep Dive guidelines to improve its efficiency and functionality.

Changes Made:

Refactored the reptile_step function to enhance its performance and readability.
Addressed issues with variable assignments and function arguments.
Optimized the inner loop optimization process by adjusting gradient steps and learning rate.
Added support for batching along the time dimension for improved meta steps.
These changes aim to ensure that the reptile_step function operates correctly and efficiently within the larger codebase. The modifications have been tested and verified to provide the desired behavior.

Fixes #14980

Please review these changes and consider merging them into the main codebase. Thank you for your attention and feedback.

2023-06-09 18:45 UTC, Sam-Armstrong requested changes
@abbasaliii Thanks for the PR! I've added some comments for things we need to change, please could you take a look?

2023-06-09 18:45 UTC, Sam-Armstrong commented on ivy/functional/ivy/meta.py
> +    ] = gradient_descent_update,
I appreciate the detail you've added to these type hints, but I think we should leave them as just 'Callable' so they are less verbose and follow the same pattern as other functions.

2023-06-09 18:45 UTC, Sam-Armstrong commented on ivy/functional/ivy/meta.py
> +    batch : ivy.Container
There's no need to include type hints in the docstring

2023-06-09 18:45 UTC, Sam-Armstrong commented on ivy/functional/ivy/meta.py
> +    Tuple[ivy.Array, ivy.Container, Any]
Similarly, this should be left as 'ret'

2023-06-09 18:45 UTC, Sam-Armstrong commented on ivy/functional/ivy/meta.py
> +    By default, only the cost and gradients are returned.
Please can you add some docstring examples here? You can find more info on them here: https://unify.ai/docs/ivy/overview/deep_dive/docstring_examples.html. The docstring examples from this stale reptile_step PR would be a great start point https://github.com/unifyai/ivy/pull/15120

2023-06-14 19:27 UTC, abbasaliii commented
@Sam-Armstrong 

Thank you for your feedback and comments on the changes made to the reptile_step function. I have addressed the issues you mentioned and made the following updates:

Simplified the type hints to use just 'Callable' instead of the verbose versions.
Removed the type hints from the docstring to align with the standard practice.
Updated the return value to 'ret' instead of explicitly stating the tuple type.
Please review the changes and let me know if there is anything else that needs to be addressed. Your input is greatly appreciated.

2023-06-15 10:40 UTC, Sam-Armstrong requested changes
@abbasaliii I think something went wrong with your merge, please can you have a look?

2023-06-15 10:40 UTC, Sam-Armstrong commented on ivy/functional/ivy/meta.py
> +<<<<<<< HEAD
I think something has gone wrong with your merge conflict resolution - this HEAD should have been removed

2023-06-18 10:28 UTC, abbasaliii commented
@Sam-Armstrong , I have made the requested changes to the code. Please take a look and let me know if there's anything else I can assist you with.

2023-06-18 13:41 UTC, Sam-Armstrong commented
@abbasaliii Please can you add some docstring examples? You can find more info on them here: https://unify.ai/docs/ivy/overview/deep_dive/docstring_examples.html. The docstring examples from this stale reptile_step PR would be a great start point https://github.com/unifyai/ivy/pull/15120

2023-06-18 15:13 UTC, abbasaliii commented
@Sam-Armstrong, I have added docstring examples

2023-06-20 13:41 UTC, Sam-Armstrong commented
@abbasaliii apologies, I've been really busy, will review later today 😁

2023-06-20 14:46 UTC, merged