Add frontend numpy require
unifyai/ivy pull request #16463
Opened 2023-06-09 12:32 UTC by ahmedelgamal0

2023-06-09 14:10 UTC, Dsantra92 commented
Hi @ahmedelgamal0 thanks for your contribution 😄 . If you are making a pr for closing a issue mention `closes #<issue-number>`. See [ivy docs](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) for more details.

2023-06-09 14:33 UTC, ahmedelgamal0 commented
Close #16463

2023-06-09 14:40 UTC, Dsantra92 commented
Hi @ahmedelgamal0 it should be `Close #<issue-number>` not the pr number. You need to include the issue number you are trying to solve. You can refer to [github issue tutorial](https://www.youtube.com/watch?v=TKJ4RdhyB5Y) for finding the same.

2023-06-13 21:49 UTC, Sam-Armstrong requested changes
Hi @ahmedelgamal0, thanks for making the PR! I've left some comments, please could you address these when you get chance? 🙂

2023-06-13 21:49 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_manipulation_routines/test_changing_array_shape.py
> +def test_numpy_require(
It seems that the test you wrote is failing, please can you fix this? 

The test can be run with the command `pytest ivy_tests/test_ivy/test_frontends/test_numpy/test_manipulation_routines/test_changing_array_shape.py::test_numpy_require`

2023-06-16 23:16 UTC, Sam-Armstrong commented
@ahmedelgamal0 I've fixed the test and formatting so we can get this merged. Thanks for your work for this PR! 😊

2023-06-16 23:16 UTC, Sam-Armstrong approved these changes

2023-06-16 23:17 UTC, merged