added Is_empty function in paddle.tensor.logic
unifyai/ivy pull request #16468
Opened 2023-06-09 16:31 UTC by JayDeep1710

2023-06-09 16:57 UTC, JayDeep1710 commented
#16448

2023-06-09 17:17 UTC, JayDeep1710 commented
please review my code. thanks

2023-06-10 11:46 UTC, rishabgit requested changes
Hi! Thanks for working on this 😄 
Looks like you're accidentally removing other functions 😅. Could you please add the is_empty fn as a new function instead of replacing the previous functions?
Apart from this, your PR looks good to me - should be ready to merge after the requested changes 😅😄

2023-06-10 11:46 UTC, rishabgit commented on ivy/functional/frontends/paddle/tensor/logic.py
shouldn't be replacing existing fns and make sure to add a newline at the end

2023-06-10 11:46 UTC, rishabgit commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_logic.py
same as above, shouldn't replace existing different tests

2023-06-10 13:17 UTC, JayDeep1710 commented
i have updated the changes. please check.
Sorry for my silly mistake😅.

2023-06-14 17:22 UTC, rishabgit requested changes
Hi! Not sure how I missed this before, but your code seems to call ivy.is_empty which doesn't exist 😅 I'd heavily suggest going through these deep dive resources to help you out - https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#ivy-frontends, https://unify.ai/docs/ivy/overview/deep_dive/function_types.html
Also, I looked into Paddle's docs - https://www.paddlepaddle.org.cn/documentation/docs/en/2.2/api/paddle/is_empty_en.html#is-empty and the unsupported dtypes needs an update too
Feel free to re-request review after making these changes, thanks! 😄

2023-06-22 05:52 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-01 05:53 UTC, closed without merging

2023-07-01 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.