Implemented and tested  Cholesky for Paddel frontends
unifyai/ivy pull request #16483
Opened 2023-06-09 23:10 UTC by XinyuanWang283

2023-06-10 09:17 UTC, XinyuanWang283 commented
@rishabgit Could you please help me check my code?

2023-06-10 11:55 UTC, rishabgit requested changes
Hi! 😄
Please refer to the docs on how to pick up an issue that your PR gets correctly linked - https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues

Also, looks like you're accidentally removing other tests 😅. Could you please look into this too?

2023-06-10 11:55 UTC, rishabgit commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
shouldn't replace existing unrelated tests

2023-06-11 01:59 UTC, XinyuanWang283 commented
Close #16464

2023-06-12 13:32 UTC, XinyuanWang283 commented
@rishabgit,  Could you please help me check my code one more time? Thank you!

2023-06-16 10:14 UTC, XinyuanWang283 commented
@rishabgit Could you review my code again? It has been a week. Thank you for your help.

2023-06-16 15:20 UTC, rishabgit commented
Hi @XinyuanWang283, sorry about the delay. There were slight lint issues, which I've updated to get the test passing. In future, please use [pre-commit](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit) to check for the lint errors before a commit. Besides this, it seems to pass the tests and everything LGTM! 
Thanks a ton! 😄

2023-06-16 15:20 UTC, merged

2023-06-16 15:23 UTC, XinyuanWang283 commented
@rishabgit Wow! Thank you very much for your help and kind reminder! I will use pre-commit in the future!