Frontend paddle tensor tensor multiply
unifyai/ivy pull request #16633
Opened 2023-06-13 08:12 UTC by nikita-jare

multiply #16623 

Added multiply function in tensor class of Paddle frontend

2023-06-17 07:06 UTC, rishabgit commented
@nikita-jare Could you please look into the requested change and the merge conflicts? Apart from these, this looks good to me to merge :)

2023-06-17 07:31 UTC, nikita-jare commented
@rishabgit What are the requested changes? I am sorry if those are already mentioned somewhere but I cannot find it.

2023-06-17 07:39 UTC, rishabgit requested changes

2023-06-17 07:40 UTC, rishabgit commented
My bad, I completely missed it was in the draft section 😅 Should be visible now

2023-06-17 07:58 UTC, nikita-jare commented on ivy/functional/frontends/paddle/tensor/tensor.py
Changed the name parameter value to None.

2023-06-21 13:57 UTC, rishabgit commented
Hi @nikita-jare, thanks a lot for working on this and resolving the merge conflicts. Tests pass for me on Codespaces too. Merging this now :)

2023-06-21 13:57 UTC, merged

2023-06-22 18:52 UTC, MuhammadNizamani commented
```
@with_unsupported_dtypes({"2.4.2 and below": ("float16", "bfloat16")}, "paddle")
    def multiply(self, y, name=None):
        return paddle_frontend.multiply(self, y)
```
The implementation appears to be incorrect based on my understanding. According to my understanding, paddle.tensor.Tensor should receive functions from the backend, rather than the frontend. However, the above function is using paddle.tensor.tensor.math.py to access the backend.
and varible Y should be converted to ivy_array

2023-06-23 12:35 UTC, rishabgit commented
> ```
> @with_unsupported_dtypes({"2.4.2 and below": ("float16", "bfloat16")}, "paddle")
>     def multiply(self, y, name=None):
>         return paddle_frontend.multiply(self, y)
> ```
> 
> The implementation appears to be incorrect based on my understanding. According to my understanding, paddle.tensor.Tensor should receive functions from the backend, rather than the frontend. However, the above function is using paddle.tensor.tensor.math.py to access the backend. and varible Y should be converted to ivy_array

Hi, following this [conversation](https://discord.com/channels/799879767196958751/998782045494976522/1118814704928821271) would explain things much better than I could, hope this helps! :)

2023-06-23 12:49 UTC, MuhammadNizamani commented
@rishabgit thanks I got it 😄 sorry for your inconvenience