add_frontend_checklist_histogram
unifyai/ivy pull request #16669
Opened 2023-06-13 23:46 UTC by RohitSgh

add_frontend_checklist

2023-06-14 00:24 UTC, RohitSgh commented
Issue   
https://github.com/unifyai/ivy/issues/16539

2023-06-14 12:52 UTC, juliagsy requested changes
Hey there! Thanks for the great work so far! I've left a small comment below, feel free to ping me if there's any issue or question! Thanks!

2023-06-14 12:52 UTC, juliagsy commented on ivy/functional/frontends/numpy/statistics/histograms.py
> +    out=None,
not sure if I overlooked anything, but I don't think the numpy histogram has out and dtype argument?
ref: https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

2023-06-14 15:18 UTC, RohitSgh commented
add_frontend_checklist

2023-06-14 15:32 UTC, RohitSgh commented
Can you please help me in resolving the issue, @juliagsy? At least 5 checks have failed so far.

2023-06-14 15:57 UTC, RohitSgh commented
Tried to solve on own and things getting worse 😅   
Please help @juliagsy in your free time

2023-06-14 15:58 UTC, RohitSgh commented
add_frontend_checklist

2023-06-15 14:36 UTC, juliagsy commented
Hey @RohitSgh ! So sorry, seems like there might be some issue with the ci earlier, would you mind pushing a commit of some dummy changes so that the ci reruns automatically? Apologies for any inconvenience and thanks a lot!

2023-06-16 07:10 UTC, juliagsy requested changes
Hey! Thanks for contributing! I've left some comments below, please also make sure that all tests are passing after that! Thanks!

2023-06-16 07:10 UTC, juliagsy commented on ivy/functional/frontends/numpy/statistics/histograms.py
> +    [x.dtype for x in [a, weights]]
as the ivy histogram function are able to handle the default values from numpy, could you please try to reduce additional codes here?
unless there are necessary for the tests to pass, please try to minimise additional code!

2023-06-16 07:10 UTC, juliagsy commented on ivy/functional/frontends/numpy/statistics/histograms.py
> +        range = (a.min(), a.max())
one necessary condition might be if `density` is `None`, we set it to `False`

2023-06-16 19:56 UTC, closed without merging

2023-06-16 20:00 UTC, RohitSgh commented
Hi @juliagsy. I will work on some different issue. Therefore, Closing PR. Thanks!