Add ball random function in Jax frontend
unifyai/ivy pull request #16699
Opened 2023-06-14 10:31 UTC by ryanacs

2023-06-14 12:06 UTC, ryanacs commented
Close #16697

2023-06-16 07:34 UTC, hirwa-nshuti requested changes
Hey @ryanacs 

Sorry for the delay in review process🙂
Would you resolve the merge conflicts for CI run checks

Thanks

2023-06-16 15:29 UTC, hirwa-nshuti requested changes
Hey @ryanacs 

Would you check the comment below and update the changes accordingly?

2023-06-16 15:29 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +        "0.3.14 and below": (
The jax version is supposed to be the latest version as we are using `0.4.11`

2023-06-17 05:08 UTC, hirwa-nshuti requested changes
Hey @ryanacs 

Check the comments below😊

2023-06-17 05:08 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +    return ivy.ball(d, p, shape=shape, dtype=dtype, seed=seed)
Ivy doesn't have the ball function implemented in the functional API, you'll need to implement this using composition

2023-06-18 09:24 UTC, hirwa-nshuti requested changes
Hey check the comments below

2023-06-18 09:24 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +    return g / (((ivy.np.abs(g) ** p).sum(-1) + e) ** (1 / p))[..., None]
We don't call `ivy.np` all functions from our functional API should be directly accessed from `ivy`

2023-06-19 07:05 UTC, hirwa-nshuti requested changes
Hey @ryanacs 

Just a minor changes to be made, check the comments

2023-06-19 07:05 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +@with_unsupported_dtypes(
Can we make it clear that only supported dtypes for jax is `float32` and `float64`

2023-06-19 18:37 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-20 09:34 UTC, hirwa-nshuti requested changes
Just small change

2023-06-20 09:34 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +@with_unsupported_dtypes(
We can simply use `with_supported_dtypes` decorator

2023-06-21 08:00 UTC, hirwa-nshuti requested changes
Hey @ryanacs 

Some changes are needed here.
Check the comments below

2023-06-21 08:00 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_random.py
> +    dtype_d,
This was not generated in the `handle_frontend_test`

2023-06-21 08:00 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_random.py
> +    dtype_p,
And this

2023-06-21 08:00 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_random.py
> +        @pytest.mark.xfail
This will be removed as we used `test_values=False` the tests should be able to pass

2023-06-22 09:50 UTC, hirwa-nshuti requested changes
Would you try to debug your tests as this error is being thrown
```E           hypothesis.errors.InvalidArgument: Cannot sample from a length-zero sequence.```

I tried to run them locally

2023-06-24 05:36 UTC, hirwa-nshuti requested changes
Would you update your fork with the latest changes in the master branch in order to run tests locally

2023-06-24 05:36 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +        "0.4.11 and below": (
We have updated the jax to `0.4.13`

2023-06-24 12:48 UTC, hirwa-nshuti requested changes
Hey would you upda your fork with latest ivy changes as I can't run the tests locally😊

2023-06-26 10:13 UTC, hirwa-nshuti requested changes
Hey @ryanacs 

Are you able to run your tests locally, as it's not working for me🙂
Would you check and tell me if everything is working seemlessly for you😊

2023-06-26 18:05 UTC, ryanacs commented
Hey @hirwa-nshuti 

I can run the test, but I got this error message: 
TypeError: 'int' object is not subscriptable

2023-06-27 08:22 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +    g = generalized_normal(seed[0], p, (*shape, d), dtype)
I think the way that you're passing these values makes no sense

2023-06-28 11:40 UTC, ryanacs commented
Hey @hirwa-nshuti 

I think I have resolved the last issue by using the composition for generalized_normal and exponential

But now I got this error message when I try to run the test: 
TypeError: _ArrayWithStatistical.sum() takes 1 positional argument but 2 were given

I'm sorry to ask, but can you help me look at the problem
Thank you

2023-06-29 09:46 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +    return gn / (((ivy.abs(gn) ** p).sum(-1) + exp) ** (1 / p))[..., None]
Here sum you need to call it using axis keyword `some_values.sum(axis=-1)`

2023-06-29 09:46 UTC, hirwa-nshuti commented
> Hey @hirwa-nshuti
> 
> I think I have resolved the last issue by using the composition for generalized_normal and exponential
> 
> But now I got this error message when I try to run the test: TypeError: _ArrayWithStatistical.sum() takes 1 positional argument but 2 were given
> 
> I'm sorry to ask, but can you help me look at the problem Thank you

Check the `ivy.sum` function to know how arguments are passed https://unify.ai/docs/ivy/docs/functional/ivy/statistical/ivy.functional.ivy.statistical.sum.html#sum

2023-07-04 11:27 UTC, hirwa-nshuti requested changes
Hey

There are still many failures would you check the comments below😊
Thanks

2023-07-04 11:27 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/random.py
> +    b = ivy.bernoulli(ivy.array([0.5]), shape=shape, dtype=dtype, seed=seed)
There is shape inconsistency , which is throwing many exceptions, hard to trace for me, would you take your time and run the tests locally to inspect that🙂

2023-07-12 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-12 06:35 UTC, ryanacs commented
Sorry, I'm still working on resolving all the issues. I'll request for review as soon as possible.

2023-07-18 06:28 UTC, hirwa-nshuti approved these changes
Looks good to me going to merge

2023-07-18 06:30 UTC, merged