Refactored `get_dtypes(...)` to accept any combination of dtypes
unifyai/ivy pull request #16709
Opened 2023-06-14 12:30 UTC by ZiadAmerr

2023-06-14 12:33 UTC, ZiadAmerr commented
This PR is not finished yet, it requires the verification of `_get_fn_dtypes` working with `x_and_y` dtypes

2023-06-20 07:56 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-01 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-02 12:52 UTC, ZiadAmerr commented
Hey @CatB1t, can you review this PR? :)

2023-07-06 10:15 UTC, CatB1t requested changes

2023-07-06 10:15 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/dtype_helpers.py
> +def _get_type_dict(framework, *kinds):
Wouldn't it be more convenient to pass the `kind` as a list instead of processing a string? I think it will be more efficient and easier to use.

2023-07-23 11:26 UTC, closed without merging