Add support for list and tuple input in meshgrid function for torch_frontend
unifyai/ivy pull request #16719
Opened 2023-06-14 16:20 UTC by akshatvishu

Currently, the `torch_frontend.meshgrid` :
```python
x = [torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])]
print(torch_frontend.meshgrid(x))
```
raises an error :
```python
RuntimeError: torch.meshgrid: Expected 0D or 1D tensor in the tensor list but got:  1  2  3
 4  5  6
[ torch.LongTensor{2,3} ]
```
This fixes this and add support for ` list` and `tuple` input in `meshgrid` function.

Close #Issue_number

Discussion on the same at `# ivy-frontend` channel at [Discord](https://discord.com/channels/799879767196958751/998782045494976522/1118525133322199140)  for additional context! 
```python
import ivy
import ivy.functional.frontends.torch as torch_frontend

x = [torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])]

print(torch_frontend.meshgrid(x))
"""PRINT

(ivy.frontends.torch.Tensor([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]]), ivy.frontends.torch.Tensor([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]]))
"""
```

2023-06-15 08:44 UTC, jkeane508 requested changes
Hey,

Thanks for submitting this PR.

Would you mind creating an Issue for this first?

Thanks :)

2023-06-15 08:45 UTC, akshatvishu commented
> Would you mind creating an Issue for this first?


Should I select `Bug Report` under `Issues` ?

2023-06-15 08:50 UTC, jkeane508 commented
> > Would you mind creating an Issue for this first?
> 
> Should I select `Bug Report` under `Issues` ?

I've quickly had a look at the PyTorch docs [here](https://pytorch.org/docs/stable/generated/torch.meshgrid.html). It seems to me that `torch.meshgrid()` accepts `*tensors` as an argument. There is no specification for them to accept tuples or lists of tensors?

2023-06-15 09:18 UTC, akshatvishu commented
> I've quickly had a look at the PyTorch docs [here](https://pytorch.org/docs/stable/generated/torch.meshgrid.html). It seems to me that `torch.meshgrid()` accepts `*tensors` as an argument. There is no specification for them to accept tuples or lists of tensors?

If you hover the at the code for `torch.meshgrid`  [in-here](https://pytorch.org/docs/stable/_modules/torch/functional.html#meshgrid) in your source-code editor; you can see that it is stated that it accepts `(parameter) tensors: tuple[Tensor | List[Tensor], ...]`

2023-06-18 19:41 UTC, jkeane508 commented
> > I've quickly had a look at the PyTorch docs [here](https://pytorch.org/docs/stable/generated/torch.meshgrid.html). It seems to me that `torch.meshgrid()` accepts `*tensors` as an argument. There is no specification for them to accept tuples or lists of tensors?
> 
> If you hover the at the code for `torch.meshgrid` [in-here](https://pytorch.org/docs/stable/_modules/torch/functional.html#meshgrid) or at your source-code editor ; you can see that it is stated that it accepts `(parameter) tensors: tuple[Tensor | List[Tensor], ...]`
> 
> ```python
> import ivy
> import torch
> import ivy.functional.frontends.torch as torch_frontend
> 
> 
> x = [torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6])]
> print(f"torch = {torch.meshgrid(x)}")  # this will work
> print(f"torch_frontend: {torch_frontend.meshgrid(x)}")  # this will raise an error
> ```

Ah, I see, good find!

In this case, can you create an issue for this, please? I'll link it to this PR and we can go ahead and merge (providing all tests are passing)

Awesome work,
James

2023-06-18 19:42 UTC, jkeane508 commented
> > Would you mind creating an Issue for this first?
> 
> Should I select `Bug Report` under `Issues` ?

Yep Bug Report would be fine :)

2023-06-19 11:15 UTC, akshatvishu commented
Hey @jkeane508 ! I made a `issue` with the problem discussion and potential solution !

2023-06-19 18:37 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-23 09:08 UTC, jkeane508 commented
Co-authored-by: jkeane508 <jameskeane508@gmail.com>

2023-06-23 09:09 UTC, merged