Add all function
unifyai/ivy pull request #16712
Opened 2023-06-14 13:22 UTC by dhev-wisdom

Added a 'all' function using built in all function in the ivy package

2023-06-16 09:44 UTC, Sam-Armstrong requested changes
Hey @dhev-wisdom, please could you link your issue to https://github.com/unifyai/ivy/issues/15115 by leaving a comment in the format  "- [ ] #issue_number" on https://github.com/unifyai/ivy/issues/15115? 

Also please could you write a test for this function? You can find out how to do this here https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#ivy-frontend-tests.

2023-06-16 09:44 UTC, Sam-Armstrong commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +    def all(self, name=None):
This should have the kwargs axis=None, keepdim=False, name=None (from paddle docs https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/Tensor_en.html)

2023-06-16 09:45 UTC, Sam-Armstrong commented
Close https://github.com/unifyai/ivy/issues/16708

2023-06-19 18:37 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-02 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-06 14:10 UTC, Sam-Armstrong commented
closed stale pull request

2023-07-06 14:10 UTC, closed without merging