mse_loss added
unifyai/ivy pull request #16735
Opened 2023-06-15 05:15 UTC by ayushi2626

Mean square loss added in ivy/ivy/functional/ivy/losses.py

2023-06-15 11:39 UTC, Sam-Armstrong requested changes
Hi @ayushi2626, thanks for making the PR! I've left some comments, please could you take a look and try to address them? Also please could you remove the changes to the .idea files and your test_file.py? Thanks 😊

2023-06-15 11:39 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_misc/test_mse_loss.py
> +def mse_loss_test(x,y):
The test should be located in ivy_tests/test_ivy/test_functional/test_nn/test_losses.py, and follow the same test style as the tests found in there. You can find more details about testing here https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html.

2023-06-15 11:39 UTC, Sam-Armstrong commented on test_file.py
> +print(mse_loss(x,y))
File should be removed.

2023-06-15 11:39 UTC, Sam-Armstrong commented on ivy/functional/ivy/losses.py
> +    ivy.array([1])
Please can you change '>>x' to '>>> x' for example? To keep the syntax consistent and readable :). Also, some more examples with labels would be great. Have a look at the docstring examples on binary_cross_entropy or sparse_cross_entropy. More details here: https://unify.ai/docs/ivy/overview/deep_dive/docstring_examples.html#docstring-examples.

2023-06-15 11:39 UTC, Sam-Armstrong commented on ivy/functional/ivy/losses.py
> +def mse_loss(true : Union[ivy.Array, ivy.NativeArray],pred : Union[ivy.Array, ivy.NativeArray],axis : int=-1,out : Optional[ivy.Array]=None)-> ivy.Array:
```suggestion
@handle_exceptions
@handle_nestable
@handle_array_like_without_promotion
@inputs_to_ivy_arrays
@handle_array_function
def mse_loss(
    true: Union[ivy.Array, ivy.NativeArray],
    pred: Union[ivy.Array, ivy.NativeArray],
    /,
    *,
    axis: int = -1,
    out: Optional[ivy.Array] = None
) -> ivy.Array:
```

2023-06-15 11:39 UTC, Sam-Armstrong commented on ivy/functional/ivy/losses.py
> +        )
Please ensure that there are two lines of whitespace between each function.

2023-06-15 11:39 UTC, Sam-Armstrong commented on ivy/functional/ivy/losses.py
> +
Keep the end of this function as it was before.

2023-06-15 11:39 UTC, Sam-Armstrong commented on ivy/functional/ivy/losses.py
> +        the axis along which mse is computed. By default, it is the last axis (-1)
```suggestion
        the axis along which mse is computed. Default: ``-1``
```

2023-06-15 11:39 UTC, Sam-Armstrong commented on ivy/functional/ivy/losses.py
> +
Remove excess whitespace. There should be one line of whitespace at the end of the file.

2023-06-15 14:55 UTC, ayushi2626 commented
> Hi @ayushi2626, thanks for making the PR! I've left some comments, please could you take a look and try to address them? Also please could you remove the changes to the .idea files and your test_file.py? Thanks 😊

Hi. Thank you so much for the feedback. I will make the required changes. But just one doubt. I have not made any changes to .idea.py file.

2023-06-15 15:52 UTC, Sam-Armstrong commented
@ayushi2626 I mean .idea/ivy.iml, .idea/misc.xml, etc.
Look at https://github.com/unifyai/ivy/pull/16735/files

2023-06-15 16:33 UTC, ayushi2626 commented
Hi. I have made the changes. Should I create a new pull request?

2023-06-16 20:24 UTC, Sam-Armstrong commented
@ayushi2626 it just says you have removed one line of whitespace at the end of the file. Have you tried adding that line back in?

2023-06-16 21:54 UTC, Sam-Armstrong commented
@ayushi2626 I've removed a couple of unnecessary changes that you made, but unfortunately I can't remove your change to .github/workflows/test-ivy-nn.yml, as I don't have the permissions for it. But you just need to add 1 new line with nothing on it (not even any spaces) to the end of the file to remove the change.

2023-06-16 22:06 UTC, Sam-Armstrong requested changes
@ayushi2626 I've made a couple of updates so please `git pull` before doing anything else 😅. It looks like the your test is failing, so please can you try to get it working? You can run the test using the command `pytest ivy_tests/test_ivy/test_functional/test_nn/test_losses.py::test_mse_loss` from the terminal.

2023-06-17 04:09 UTC, ayushi2626 commented
> @ayushi2626 I've removed a couple of unnecessary changes that you made, but unfortunately I can't remove your change to .github/workflows/test-ivy-nn.yml, as I don't have the permissions for it. But you just need to add 1 new line with nothing on it (not even any spaces) to the end of the file to remove the change.

Oh okay sure. Thank you

2023-06-17 04:10 UTC, ayushi2626 commented
> @ayushi2626 I've made a couple of updates so please `git pull` before doing anything else 😅. It looks like the your test is failing, so please can you try to get it working? You can run the test using the command `pytest ivy_tests/test_ivy/test_functional/test_nn/test_losses.py::test_mse_loss` from the terminal.

Yes I will look into the same and get it working. Thank you very much

2023-06-18 17:30 UTC, ayushi2626 commented
Hello. I have been looking into the testing of the function but there is an import error that is not getting rectified. I had asked in the discord server too but the error still persists.

2023-06-19 17:41 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-21 01:08 UTC, Sam-Armstrong commented
@ayushi2626 I'd recommend running the tests with this command to get a clearer view of the stack trace:
pytest -p no:warnings --tb=short ivy_tests/test_ivy/test_functional/test_nn/test_losses.py::test_mse_loss

From this I can immediately see one problem 'negative() got an unexpected keyword argument 'axis'' - you are passing a axis kwarg to the negative function which has no axis kwarg.

2023-06-21 04:39 UTC, ayushi2626 commented
I am using docker and the test is now been executed. I have removed the syntactical error in the code but I have been getting an error: ivy.utils.exceptions.IvyBackendException and KeyError: 'cpu' Can you just explain what it means? Have I not imported any library or is it something else? Thank you very much

2023-06-21 09:45 UTC, Sam-Armstrong commented
@ayushi2626 are you getting this for all the test cases, or just for one of the backend frameworks?

2023-06-21 10:20 UTC, ayushi2626 commented
I am getting KeyError:'cpu" for numpy backend. And for the rest of the backend, I am getting the ivy.utils.exceptions.IvyBackendException error

2023-06-21 13:26 UTC, Sam-Armstrong commented
I think you can debug and fix the tests for the other backends then right? Ignore the numpy backend for now if you're getting KeyError

2023-06-21 15:39 UTC, ayushi2626 commented
Okay got it. I am working on it. If I have further questions I will let you know. Thank you very much

2023-06-24 09:17 UTC, ayushi2626 commented
Hello. I was debugging the code and was facing this one issue. There is an AssertionError, and it says that the value returned by the function isn't the same as the value of the out array. I don't seem to understand why this is happening. I printed the out and return values both of which are the same but the error still persists. Could you pls help me with this?

2023-06-24 12:51 UTC, Sam-Armstrong commented
@ayushi2626 Can you push your latest changes? I'm still getting the error "negative() got an unexpected keyword argument 'axis'"

2023-06-24 13:35 UTC, ayushi2626 commented
Hello. I have pushed the changes I have made.

2023-06-28 12:12 UTC, ayushi2626 commented
Hello. It says that there is an extra newline added in losses.py file after the cross_entropy function. But I just left two newlines between each function as you said. Could you please help me with that? Thanks!!

2023-06-28 18:34 UTC, Sam-Armstrong requested changes
@ayushi2626 I can't see any extra line so I think we're ok 🙂 apologies for the slow review, I've been very busy. 

I've suggested a simpler implementation which fixes the problem, as we are now utilising the 'out' argument. However, there seems to be another problem arising with this change, so please could you try debugging this. Feel free to let me know if you get stuck. Thanks!

2023-06-28 18:34 UTC, Sam-Armstrong commented on ivy/functional/ivy/losses.py
> +    return mse_diff
```suggestion
    s_diff = ivy.square(true - pred)
    return ivy.mean(s_diff, axis=axis, out=out)
```

2023-06-30 16:31 UTC, ayushi2626 commented
Okay sure I will make the changes and let you know if there are any other problems. Thank you so much!!

2023-07-06 14:12 UTC, Sam-Armstrong commented
@ayushi2626 Have you managed to make any progress on the changes? 🙂

2023-07-06 14:50 UTC, ayushi2626 commented
Hello. I am so sorry for the delay.  I had made the changes and pushed it but there were few errors. But I could not rectify that as the docker environment is not working on my system. I am working on fixing that. Can I report back the results in sometime.

2023-07-08 13:46 UTC, ayushi2626 commented
Hello. My docker and git bash have stopped working. In git bash, it says that flake8 is not compatible with the Python version I have. The last I checked was that with the changes, there was IndexError which shouldn't happen as for the test function, the values given to the axis are 0 and 1. I have been trying to debug it for days now but still, it has been the same. So sorry for the delay.

2023-07-08 16:55 UTC, Sam-Armstrong commented
@ayushi2626 No worries 🙂 which version of python are you using?

2023-07-09 04:25 UTC, ayushi2626 commented
I think my Python version is either 3.9 or 3.10. Whenever I try to commit the changes through git bash, it says that flake8 isn't compatible with the version of Python which I am using, as flake8 works only with Python versions 3.7.5 and below.

2023-07-11 10:49 UTC, Sam-Armstrong commented
`pip install --upgrade flake8` maybe?

2023-07-14 18:00 UTC, ayushi2626 commented
Hey, I did that too, the error still persists.

2023-07-16 11:38 UTC, Sam-Armstrong commented
@ayushi2626 I'm not really sure what to suggest here, other than maybe try rebuilding the docker container or starting to whole setup process from scratch

2023-07-16 20:07 UTC, ayushi2626 commented
Okay, I will rebuild the entire thing and let you know.

2023-08-20 19:28 UTC, sushmanthreddy commented
@Sam-Armstrong @ayushi2626 can i work on this, as it is inactive since so many days.. 

Pls let me knew if the issue is free

2023-08-20 19:32 UTC, ayushi2626 commented
@Sam-Armstrong I am not able to resolve the problem. I think the code I have written is fine but I am not sure why my git isn't working with the repo

2023-12-23 19:09 UTC, NripeshN commented
Hey @ayushi2626 
Looks like your tests are failing. Could you please take a look?

2023-12-31 05:52 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-01-01 18:12 UTC, Sarvesh-Kesharwani commented
Hi @ayushi2626,
you branch it looks like is outdated,
![image](https://github.com/unifyai/ivy/assets/22115102/12a1d671-b1bb-452b-b114-684bbab8f5e6)
please update it with latest changes from upstream.
And let me know then.

2024-02-14 05:53 UTC, closed without merging

2024-02-14 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.