refactor `data_type/can_cast`
unifyai/ivy pull request #1689
Opened 2022-06-29 12:28 UTC by flych3r

Added examples to `ivy/functional/ivy/data_type/can_cast`

Closes #1688

2022-06-30 12:26 UTC, sherry30 requested changes
Hi,

The examples look good, just a few additional things you have to do:
1. Instance methods for `ivy.array` and `ivy.container` needs to be added. The instance method for `ivy.array` will be added in `ivy/array/data_types.py` and for container it will be added in `ivy/container/data_types.py`. You can use [this](https://github.com/unifyai/ivy/blob/76d65119fef75a3592a6e2cd744c568ea73f7651/ivy/array/elementwise.py#L295) example of tan as a reference to complete can_cast.
2. You have to add docstring examples for `ivy.array` instance method and `ivy.container` method, These examples will be placed under the new instance function you will create in their respective folders(`ivy/array/data_types.py` for array and `ivy/container/data_types.py`).
3. And lastly you also have to add a static_method for can_cast in `ivy/container/data_types.py`. [here](https://github.com/unifyai/ivy/blob/76d65119fef75a3592a6e2cd744c568ea73f7651/ivy/container/elementwise.py#L1372) here is an example of static_tan. You also have to write 1 example of the new static function.

All of these requirements are mentioned [here](https://github.com/unifyai/ivy/blob/76d65119fef75a3592a6e2cd744c568ea73f7651/docs/partial_source/deep_dive/11_docstring_examples.rst) in details.
If you have any question then feel free to ask, I'd be happy to help 😄 .

2022-07-02 12:34 UTC, sherry30 requested changes
Hi,

can_cast does not accept `out` argument so you're right about not adding that. Other than that
your docstring seems to be failing, its because you haven't added a new line after writing the output so just a few minor changes you need to fix that I've mentioned on each specific line.
I'll merge your PR as soon as you fix these 😃 

Thanks

2022-07-02 12:34 UTC, sherry30 commented on ivy/array/data_types.py
> +        float32
add new line after this

2022-07-02 12:34 UTC, sherry30 commented on ivy/container/data_types.py
> +        float32 int32
add new line after this

2022-07-02 12:34 UTC, sherry30 commented on ivy/container/data_types.py
> +        float32 int32
add new line after this

2022-07-02 12:34 UTC, sherry30 commented on ivy/functional/ivy/data_type.py
> +    float32
add new line after this

2022-07-02 12:34 UTC, sherry30 commented on ivy/functional/ivy/data_type.py
> +    int16
write this as `<dtype:'int16'>`

2022-07-02 12:34 UTC, sherry30 commented on ivy/functional/ivy/data_type.py
> +    >>> x = ivy.native_array([[-1, -1, -1], [1, 1, 1]], dtype='int16')
1. add `With :code:'ivy.NativeArray' input:` before this
2. write dtype input on a new line using `\` separator

2022-07-02 12:34 UTC, sherry30 commented on ivy/functional/ivy/data_type.py
> +    float32 int32
add new line after this

2022-07-02 12:34 UTC, sherry30 commented on ivy/functional/ivy/data_type.py
> +    >>> x = ivy.Container(a=ivy.array([0., 1., 2.]), b=ivy.array([3, 4, 5]))
write b input on a next line using `\` separator

2022-07-02 12:34 UTC, sherry30 commented on ivy/container/data_types.py
> +        >>> x = ivy.Container(a=ivy.array([0., 1., 2.]), b=ivy.array([3, 4, 5]))
write b input on the next line using `\` separator

2022-07-02 12:34 UTC, sherry30 commented on ivy/container/data_types.py
> +        >>> x = ivy.Container(a=ivy.array([0., 1., 2.]), b=ivy.array([3, 4, 5]))
write b input on the next line using `\` separator

2022-07-02 15:37 UTC, flych3r commented
Hello, just made the requested changes. One thing, the item of the function `can_cast` on issue #780 was not marked when I made the comment.

2022-07-05 07:46 UTC, merged