added a function add_n
unifyai/ivy pull request #16989
Opened 2023-06-16 05:11 UTC by princebari

2023-06-17 07:16 UTC, rishabgit requested changes
Hi! Thanks a lot for looking into this 😄. Not sure which task board this belongs to, could you please add the appropriate comments so that your PR gets correctly linked? :)
Feel free to refer to the docs on the comment format - https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues

2023-06-19 05:12 UTC, princebari commented
close ##16748

2023-06-19 05:12 UTC, princebari commented
close #16748

2023-06-19 17:40 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-19 18:36 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-21 14:13 UTC, rishabgit requested changes
Hi! Your code seems to call ivy.add_n which doesn't exist 😅 I'd heavily suggest going through these deep dive resources to help you out - https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#ivy-frontends, https://unify.ai/docs/ivy/overview/deep_dive/function_types.html
Also, I looked into Paddle's docs - https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/add_n_en.html#add-n and the supported dtypes needs an update too
Feel free to re-request review after making these changes, thanks! 😄

2023-06-21 14:13 UTC, rishabgit commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +    @with_unsupported_dtypes({"2.4.2 and below": ("float16", "float16")}, "paddle")
this needs to be reverted

2023-06-21 14:13 UTC, rishabgit commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        return ivy.add_n(self._ivy_array)
ivy functional api doesn't have add_n, supported dtypes need update too

2023-07-01 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-06 10:58 UTC, princebari commented
Dear Rishab

I am writing to bring to your attention an issue regarding the implementation of the "add_n" function in the Ivy backend. After attempting to utilize this function, I have discovered that it is currently not available or supported.

I would greatly appreciate it if you could look into this matter and consider implementing the "add_n" function. If there are any updates or plans for future additions to the backend, I would be grateful to receive any information regarding the availability of this function.

Thank you for your attention to this matter. I look forward to hearing from you soon and resolving this issue.

Best regards,
Prince

2023-07-09 09:16 UTC, rishabgit commented
> Dear Rishab
> 
> I am writing to bring to your attention an issue regarding the implementation of the "add_n" function in the Ivy backend. After attempting to utilize this function, I have discovered that it is currently not available or supported.
> 
> I would greatly appreciate it if you could look into this matter and consider implementing the "add_n" function. If there are any updates or plans for future additions to the backend, I would be grateful to receive any information regarding the availability of this function.
> 
> Thank you for your attention to this matter. I look forward to hearing from you soon and resolving this issue.
> 
> Best regards, Prince

Hi, not sure if this is an issue of adding `add_n` in Ivy framework. Apart from the resources I shared above, could you please check out https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html to decide what approach makes the most sense for this task? Thanks!

2023-07-17 05:53 UTC, closed without merging

2023-07-17 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.