jax frontend histogram bin edges + test
unifyai/ivy pull request #16985
Opened 2023-06-15 20:43 UTC by mam15

Closes #16983

2023-06-19 10:28 UTC, MahmoudAshraf97 requested changes

2023-06-19 10:28 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/device.py
Please remove this change and if needed for a bug fix, keep it in a separate PR

2023-06-19 17:40 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-17 11:04 UTC, bipinKrishnan commented on ivy/functional/frontends/jax/numpy/statistical.py
> +    del weights
May be this could be removed as having this variable doesn't effect the function

2023-07-17 11:05 UTC, bipinKrishnan commented on ivy/functional/frontends/jax/numpy/statistical.py
> +    del weights
Is there any reason for not supporting the `weights` argument?

2023-07-17 11:14 UTC, bipinKrishnan commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_statistical.py
> +        dtype_input,
Could you specify the case for which this helper function is required. While going through the code I felt like we should be able to get these data from existing array helpers. Let me know if that's not the case :slightly_smiling_face:

2023-07-24 11:28 UTC, bipinKrishnan commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_statistical.py
> +    # jax.numpy.nanquantile does not support overwrite_input=True.
Seems like these are not related to your changes, can you remove these modifications?

2023-07-25 11:35 UTC, bipinKrishnan commented
The test for your function is failing due to missing kwarg, can fix this @mam15

2023-07-25 11:42 UTC, bipinKrishnan commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_statistical.py
> +    test_flags,
I think you missed an argument here, `backend_fw` I guess. Just refer to other test implementations and your test failure outputs in the CI

2023-08-01 11:34 UTC, bipinKrishnan commented on ivy/functional/frontends/jax/numpy/statistical.py
> +    del weights
> Is there any reason for not supporting the `weights` argument?

Hey can you address this question and the one below it as well :slightly_smiling_face:

2023-08-08 12:04 UTC, bipinKrishnan commented
I've left some comments in the review, clarifying those would allow merging the PR quicker. Thanks :slightly_smiling_face:

2023-08-08 16:49 UTC, mam15 commented
> I've left some comments in the review, clarifying those would allow merging the PR quicker. Thanks 🙂

@bipinKrishnan I'm so sorry! I had replied to those comments weeks ago but forgot to submit my review, so they were pending and you couldn't see them 🤦‍♂️

2023-08-22 10:52 UTC, bipinKrishnan commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_statistical.py
> +    values=histogram_helper(),
Most of the things returned from the `histogram_helper` could be obtained using existing helper functions, for example `a`, `bins`, `weights` etc are normal arrays which could be easily obtained using existing helpers. I would recommend going through the [testing deep dive](https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html) or the [hypothesis helpers](https://github.com/unifyai/ivy/tree/main/ivy_tests/test_ivy/helpers/hypothesis_helpers) to learn about the functions that suit your use-case.

2023-09-30 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-10-17 05:53 UTC, closed without merging

2023-10-17 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.