argmin #17061
unifyai/ivy pull request #17066
Opened 2023-06-17 09:37 UTC by ayam04

first commit to add the argmin under search.py

2023-06-17 17:12 UTC, Sam-Armstrong requested changes
@ayam04 Thanks for making the PR! 

The test you wrote is failing at the moment, but I think it should be fixed by the change I requested. You can run the test using the command `pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_search.py::test_paddle_argmin` to check this. 

Also, please could you ensure that there are two lines of whitespace between funtions (both the function and test you added), as this is the standard we are following in Ivy.

Other than these this looks really good, great work! 😊

2023-06-17 17:12 UTC, Sam-Armstrong commented on ivy/functional/frontends/paddle/tensor/search.py
> +
```suggestion


@with_supported_dtypes(
    {"2.4.2 and below": ("float32", "float64", "int16", "int32", "int64", "uint8")},
    "paddle",
)
```

2023-06-17 17:12 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_search.py
> +
Should be 2 lines of whitespace not 1

2023-06-17 17:17 UTC, Sam-Armstrong commented
Close https://github.com/unifyai/ivy/issues/17061

2023-06-17 17:18 UTC, Sam-Armstrong commented
Forgot to mention, you need to comment 'Close <issue_num>' on any pull requests you make. But I've done it here, so no worries 😊

2023-06-17 18:14 UTC, ayam04 commented
hey @Sam-Armstrong, I've updated the code accordingly. If you can look into the same.

2023-06-17 18:36 UTC, ayam04 commented
also if u can look into this https://github.com/unifyai/ivy/pull/16527/files , might helps us.

2023-06-17 22:00 UTC, Sam-Armstrong approved these changes
lgtm! thanks @ayam04

2023-06-17 22:03 UTC, merged

2023-06-18 09:29 UTC, ayam04 commented
Close #17061