added relevent docstring and docstring examples!
unifyai/ivy pull request #1713
Opened 2022-07-01 09:49 UTC by Nekorra

Added Examples for Abs function

2022-07-01 09:56 UTC, Nekorra commented
Issue: https://github.com/unifyai/ivy/issues/1711

Please give me feedback and improvements!!

2022-07-02 10:44 UTC, VedPatwardhan requested changes
Hi @Nekorra, thanks for contributing! There are a few changes to be mage to your PR before we get it merged:
1. The function formatting task has been changed a few days back, now all examples are not supposed to be added to a single file, so you would've needed to add an instance method in `ivy/container/elementwise.py` and a static and instance method in `ivy/container/elementwise.py`.
2. But, in case of the function you're formatting, there is an [array instance method](https://github.com/unifyai/ivy/blob/master/ivy/array/elementwise.py#L13) and a [container instance method](https://github.com/unifyai/ivy/blob/master/ivy/container/elementwise.py#L13) already. You would just need to add a `static_abs` method in `ivy/container/elementwise.py` referring the [`static_add`](https://github.com/unifyai/ivy/blob/master/ivy/container/elementwise.py#L71) method.
3. Then you need to update the [`abs`](https://github.com/unifyai/ivy/blob/master/ivy/container/elementwise.py#L13) instance method here to use the `static_abs` method internally which you created previously. You can refer to the [`add`](https://github.com/unifyai/ivy/blob/master/ivy/container/elementwise.py#L128) container instance method for the same.
4. After making that change, you'll have to update the docstrings for the `abs` method in `ivy/functional/ivy/elementwise.py`, `ivy/array/elementwise.py` and `ivy/container/elementwise.py` and the `static_abs` method in `ivy/container/elementwise.py`. You can refer [this](https://lets-unify.ai/ivy/deep_dive/11_docstring_examples.html) page for the same.

Let me know if you have any questions. Thanks 🙂

2022-07-04 13:26 UTC, VedPatwardhan requested changes
Hi @Nekorra, thanks for making the changes, I have made suggestions near the lines of code concerned, please make those changes. Once you're done, feel free to re-request my review after which we'll look into how to get the tests passing.

Let me know if you have any questions. Thanks 🙂

2022-07-04 13:26 UTC, VedPatwardhan commented on ivy/array/elementwise.py
> +    def abs(
Seems like you've added an `x1` argument to the functions, but we don't need that argument, the `abs` function simply accepts two arguments, `x` which is the input argument and `out` which is the out argument, please remove the `x1` argument.

2022-07-04 13:26 UTC, VedPatwardhan commented on ivy/container/elementwise.py
> +    def static_abs(
Same applies here too

2022-07-04 13:26 UTC, VedPatwardhan commented on ivy/container/elementwise.py
> +        x1: Union[ivy.Container, ivy.Array, ivy.NativeArray],
And here as well

2022-07-04 13:26 UTC, VedPatwardhan commented on ivy/container/elementwise.py
> +        >>> x = ivy.Container(a=ivy.array([-1.6, 2.6, -3.5]),\
Please update the formatting here, so that `...` is removed and the second line is positioned in a way that it aligns with `a` above it

2022-07-04 13:26 UTC, VedPatwardhan commented on ivy/functional/ivy/elementwise.py
> +    >>> x = ivy.Container(a=ivy.array([0., 2.6, -3.5]),\
Please update the formatting here, so that `...` is removed and the second line is positioned in a way that it aligns with `a` above it.

2022-07-04 13:26 UTC, VedPatwardhan commented on ivy/functional/ivy/elementwise.py
> +    >>> x = ivy.Container(a=ivy.array([-1.6, 2.6, -3.5]),\
Please update the formatting here, so that `...` is removed and the second line is positioned in a way that it aligns with `a` above it

2022-07-04 16:47 UTC, Nekorra commented
@VedPatwardhan Hi again! Did the changes you requested!! Hopefully it should all be good now!

2022-07-04 17:38 UTC, Nekorra commented
:( still not passing. Not sure why 😢

2022-07-05 05:02 UTC, VedPatwardhan requested changes
Hi, I have made some suggestions which could fix those issues, please have a look.

Thanks 🙂

2022-07-05 05:02 UTC, VedPatwardhan commented on ivy/array/elementwise.py
> +        With :code:`ivy.NativeArray` instance method:
Please remove this, as we shouldn't add an instance method for `ivy.NativeArray`

2022-07-05 05:02 UTC, VedPatwardhan commented on ivy/array/elementwise.py
>          return ivy.abs(self._data, out=out)
Please update this to `return ivy.abs(self, out=out)`

2022-07-05 10:46 UTC, Nekorra commented
Looks like indentation test passed 👍, however docstring still failing :(.

2022-07-06 04:39 UTC, Nekorra commented
Hmmm, this is so weird. Looks like Function Abs's docstrings are not failing anymore, but rather a function named not_equal's docstrings. Also another failure in helpers.py ? I'm not sure if I caused these errors, but I am pretty sure I did not. :). Please let me know!!

2022-07-06 10:08 UTC, VedPatwardhan requested changes

2022-07-06 10:08 UTC, VedPatwardhan commented on ivy/functional/ivy/elementwise.py
> +    Instance Method Examples
Please remove the Instance method examples from here, they're not supposed to be in this file

2022-07-06 10:09 UTC, VedPatwardhan commented
The test which is failing is not related to your function, once you're done making these changes, we can get your PR merged

2022-07-06 10:19 UTC, Nekorra commented on ivy/functional/ivy/elementwise.py
> +    Instance Method Examples
@VedPatwardhan Hmmm, i have already made these changes before in this commit: https://github.com/unifyai/ivy/pull/1713/commits/0e0a1a60b983b57dc71e88237332f7f41bf6cfd9. When I try to push again from my local machine, it says there is nothing to commit.

2022-07-06 10:19 UTC, Nekorra commented on ivy/functional/ivy/elementwise.py
> +    Instance Method Examples
I will remove the other instance methods however, and try pushing again!

2022-07-06 10:22 UTC, Nekorra commented on ivy/functional/ivy/elementwise.py
> +    >>> x = ivy.array([3.7, -7.7, 0, -2, -0])
@VedPatwardhan Thanks for the feedback, however I have already made this change before in this commit: https://github.com/unifyai/ivy/pull/1713/commits/2532b5927ea5d62c722c5c2798aad7d25cac1233. Not sure why it changed now!

2022-07-06 10:22 UTC, Nekorra commented
Should be good to go! Thank you so much @VedPatwardhan for your help!

2022-07-06 13:04 UTC, Nekorra commented
Let me know if you need me do change more stuff! @VedPatwardhan

2022-07-06 13:08 UTC, VedPatwardhan approved these changes
lgtm! Thanks for contributing 🙂

2022-07-06 16:12 UTC, Nekorra commented
@VedPatwardhan Should I close this pull request and also the issue I created in the beginning? Also, thank you again for all the help, I really appreciate it! :)

2022-07-06 16:36 UTC, VedPatwardhan commented
Hi @Nekorra, I'll be merging your PR and the issue you've created will automatically get closed as it's linked to the PR. About the internship application, your task is completed. You could ask any questions you have regarding the same on the discord server. Thanks 🙂

2022-07-06 16:37 UTC, merged