Added trapz
unifyai/ivy pull request #17152
Opened 2023-06-18 12:21 UTC by Bright-in

2023-06-19 17:14 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-19 17:25 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-26 05:18 UTC, YushaArif99 commented on ivy/functional/frontends/jax/numpy/mathematical_functions.py
> -abs = absolute
I think this file was added by mistake. Can you remove it 🙂

2023-06-26 05:19 UTC, YushaArif99 commented on ivy/functional/frontends/torch/indexing_slicing_joining_mutating_ops.py
this file too doesnt seem relevant to the PR. Can you remove it as well 🙂

2023-06-26 05:20 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py
same goes for this file as well 🙂

2023-06-26 05:24 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_blas_and_lapack_ops.py
> +        kwargs = {"y": y, "dx": dx, "dim": dim}
I am not sure what you're trying to do here in general 🤔. The frontend helper `helpers.test_frontend_function` takes care of testing the function with a combination of args/kwargs and so there is no need to hardcode this into your test function itself. Any particular reason for adding this check?

Also, the frontend function `trapz` does not contain any argument called `dx` so why are you supplying it here?

2023-06-26 05:26 UTC, YushaArif99 requested changes
Hi @Bright-in 

Apologies for the late response. Have been swamped with work recently and so haven't had the time to review any PRs 😅. 

Anyways, could you kindly look into the above-mentioned points? Feel free to discuss in detail any concern you have or to clarify anything I might have misunderstood 🙂

2023-07-05 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-13 05:53 UTC, closed without merging

2023-07-13 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.