fix `ivy.Container` type hints in `losses` container instances
unifyai/ivy pull request #1719
Opened 2022-07-01 13:29 UTC by juliagsy

in progress...

2022-07-01 22:36 UTC, djl11 requested changes

2022-07-01 22:36 UTC, djl11 commented on ivy/container/losses.py
> +        axis: Optional[Union[int, ivy.Container]] = -1,
these new changes are great, but again I've noticed as miss-use of the `Optional` type hint, which should only be used for arguments with default value of `None`.

2022-07-02 03:53 UTC, juliagsy commented
fixed the optional type hints! If the changes are all good, I'll check out the master branch and fix the lint before merging, thanks!

2022-07-02 12:52 UTC, djl11 approved these changes
lgtm!

2022-07-03 12:15 UTC, merged