added `ifftn` to ivy functional api
unifyai/ivy pull request #17397
Opened 2023-06-20 10:07 UTC by akshatvishu

Close #17393

2023-06-20 20:03 UTC, KareemMAX requested changes
Great job @akshatvishu 🚀

I've left some formatting comments, otherwise everything should be good to go after we run the test

2023-06-21 08:21 UTC, akshatvishu commented
Please let it 

![Dog LGTM Keyboard](https://media.giphy.com/media/kbVzENVNlE60MQR1HY/giphy.gif)

2023-06-22 11:58 UTC, KareemMAX requested changes
> Please let it
> 
> ![Dog LGTM Keyboard](https://camo.githubusercontent.com/21496c7fd6e2f0584a5ebcc11f16becfaa307751a2483c29079a050c098b3eaf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6b62567a454e564e6c4536304d51523148592f67697068792e676966) [ ![Dog LGTM Keyboard](https://camo.githubusercontent.com/21496c7fd6e2f0584a5ebcc11f16becfaa307751a2483c29079a050c098b3eaf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6b62567a454e564e6c4536304d51523148592f67697068792e676966) ](https://camo.githubusercontent.com/21496c7fd6e2f0584a5ebcc11f16becfaa307751a2483c29079a050c098b3eaf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6b62567a454e564e6c4536304d51523148592f67697068792e676966) [ ](https://camo.githubusercontent.com/21496c7fd6e2f0584a5ebcc11f16becfaa307751a2483c29079a050c098b3eaf/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6b62567a454e564e6c4536304d51523148592f67697068792e676966)

Wish I could 😅. As we are trying to adhere to [PEP 257](https://peps.python.org/pep-0257/#multi-line-docstrings) I need the issues you resolved to be fixed before merging. In the meantime I'm reviewing the `ifftn` input space to make sure that your test is exhaustive, if it is and it passes the PR will be good to go.

2023-06-22 13:18 UTC, KareemMAX commented
Just a quick side note, all tests have passed. Once you make the docstring changes your PR is good to merge

2023-06-22 13:29 UTC, akshatvishu commented
> Wish I could sweat_smile. As we are trying to adhere to [PEP 257](https://peps.python.org/pep-0257/#multi-line-docstrings) I need the issues you resolved to be fixed before merging. In the meantime I'm reviewing the ifftn input space to make sure that your test is exhaustive, if it is and it passes the PR will be good to go.

Ahh, So sorry @KareemMAX  I found where the mistake is happening. When I try to change the `docstring` as you suggested  the  `pre-commit` hook for `docformatter` fails.

![image](https://github.com/unifyai/ivy/assets/33392262/4ca6699a-c80a-47bd-bab1-7afaef7ff068)

And then this hook reformat my doc to its current state back again from the changes that you suggested and thus, changes you suggested aren't reflected when I push the code.
I was so confused because  I did make the changes that you suggested!  Should I skip the `pre-commit` hook entirely to apply changes that you suggested?

2023-06-22 13:51 UTC, akshatvishu commented
I made the changes to doc  as you suggested by skipping `pre-commit`

2023-06-22 15:53 UTC, KareemMAX commented
@akshatvishu I'm guessing you have missed the blank line between summary and description. Which confused pre-commit

2023-06-22 16:29 UTC, KareemMAX requested changes
Seems like it was an issue from my side 😅😅

Just apply those suggestions and commit them view pre-commit and you are good to go

Sorry 😅😅

2023-06-22 16:29 UTC, KareemMAX commented on ivy/data_classes/container/experimental/layers.py
> +        ivy.Container static method variant of ivy.ifftn.
Seems like I made a wrong code suggestion 😅
```suggestion
        ivy.Container static method variant of ivy.ifftn. 
        
```

2023-06-22 16:29 UTC, KareemMAX commented on ivy/data_classes/container/experimental/layers.py
> +        ivy.Container static method variant of ivy.ifftn.
Same error here
```suggestion
        ivy.Container static method variant of ivy.ifftn. 
        
```

2023-06-22 19:46 UTC, KareemMAX approved these changes
LGTM! finally 😂

Merging now

2023-06-22 19:46 UTC, merged

2023-06-23 06:28 UTC, akshatvishu commented
> LGTM! finally joy
> 
> Merging now

![Kid Pumped](https://media.giphy.com/media/3iih6qeruA0TzxDLHi/giphy.gif)