Add Reduction ops:nanquantile to PyTorch Frontend
unifyai/ivy pull request #17418
Opened 2023-06-20 13:42 UTC by srinivasmuzumdar

Close #17063

2023-06-20 13:45 UTC, srinivasmuzumdar commented
add_frontend_checklist

2023-06-20 20:20 UTC, KareemMAX requested changes

2023-06-20 20:20 UTC, KareemMAX commented on ivy/functional/frontends/torch/reduction_ops.py
> +    return ivy.nanquantile(
I'm not really sure if `ivy.nanquantile()` is an implemented function

```python
>>> ivy.nanquantile
  File "<stdin>", line 1, in <module>

AttributeError: module 'ivy' has no attribute 'nanquantile'
```

2023-06-22 11:55 UTC, KareemMAX commented
Please once you finish your changes request a review from me @srinivasmuzumdar 

Thanks

2023-06-23 11:15 UTC, KareemMAX requested changes
It seems like you forgot to add `interpolation` in your testing strategy. Do you mind adding that? Also tests are failing, can you fix that as well?

2023-06-24 11:48 UTC, srinivasmuzumdar commented
I have made the changes but " intelligent-tests-pr / run_tests (44) " is failing. I could not find out why. Can you help me ?

2023-06-26 09:50 UTC, KareemMAX requested changes
Looks like your code is still failing, I test it by running 
```bash
pytest ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py::test_torch_nanquantile
```
Once you solve the failing tests we would be ready to merge regarding of the CI results. Please also note that it looks like your branch have a broken version of `ivy_tests` so you might need to merge your branch with master in order to run tests

2023-07-01 15:36 UTC, srinivasmuzumdar commented
> Looks like your code is still failing, I test it by running
> 
> ```shell
> pytest ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py::test_torch_nanquantile
> ```
> 
> Once you solve the failing tests we would be ready to merge regarding of the CI results. Please also note that it looks like your branch have a broken version of `ivy_tests` so you might need to merge your branch with master in order to run tests

2023-07-01 15:41 UTC, srinivasmuzumdar commented
Checked it with the following test.It passed.

`pytest ivytests/test_ivy/test_frontends/test_torch/test_reduction_ops.py::test_torch_nanquantile --backend=torch`

So, is this OK or should the test pass for all backends??

2023-07-03 03:53 UTC, closed without merging