gather_nd function docstrings done.
unifyai/ivy pull request #1744
Opened 2022-07-03 07:48 UTC by zaeemansari70

2022-07-03 07:50 UTC, zaeemansari70 commented
#1637

2022-07-03 10:42 UTC, VedPatwardhan requested changes
Hi @zaeemansari70, please make the changes where I've mentioned. Also please update the docstring so that it's only indented with spaces, because otherwise it causes the numpy style docstring test to fail. 
Let me know if you have any questions. Thanks 🙂

2022-07-03 10:42 UTC, VedPatwardhan commented on ivy/functional/ivy/general.py
> +     	a: ivy.array(0.),
This line causes a lint failure as it seems to have a mix of spaces and tabs, please update that to have only spaces.

2022-07-03 10:42 UTC, VedPatwardhan commented on ivy/array/general.py
> +        return ivy.gather_nd(self._data, indices, out=out)
Please update this line to replace `self._data` with `self`, as `self._data` refers to native array while we want to call the function with the ivy array.

2022-07-03 14:07 UTC, VedPatwardhan requested changes

2022-07-03 14:07 UTC, VedPatwardhan commented on ivy/array/general.py
> +        >>> y = ivy.array([4, 5, 6])
Please update `y` which is being passed to the function as index cannot be larger than 2 for the current value of `x`

2022-07-04 05:16 UTC, VedPatwardhan requested changes
Hi @zaeemansari70, the docstring tests are failing because of passing a `device` argument to the function in some examples. The function doesn't accept a `device` argument currently, so please remove it from all examples which pass a `device` argument to the function. Thanks 🙂

2022-07-05 05:09 UTC, VedPatwardhan requested changes

2022-07-05 05:09 UTC, VedPatwardhan commented on ivy/container/general.py
> +        >>> x = ivy.Container(a=ivy.array([1, 2, 3]),\
Hi @zaeemansari70, please update this example as the output of the example is incorrect.

2022-07-05 11:00 UTC, VedPatwardhan commented on ivy/functional/ivy/general.py
> +    >>> x = ivy.array([[0., 1., 2.], \
Based on the logs of the test, the output of this example seems to be incorrect as well, please execute it on your machine and then update the result accordingly.

2022-07-05 13:23 UTC, merged