Paddle frontend: mse_loss
unifyai/ivy pull request #17471
Opened 2023-06-21 10:45 UTC by Kamil2601

Close - [ ] #17400

2023-06-21 10:54 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-22 19:47 UTC, MuhammedAshraf2020 commented
Hey @Kamil2601, thanks a lot for the PR. Some minor changes and we are good to go with the final tests

2023-06-22 19:55 UTC, MuhammedAshraf2020 requested changes

2023-06-22 19:55 UTC, MuhammedAshraf2020 commented on ivy/functional/frontends/paddle/nn/functional/loss.py
> +    return paddle.to_tensor(ret.reshape([-1]))
It appears that the flatten is causing unexpected behavior compared to the original function when the reduction is set to `none`. In this case, I think there is no need for the flatten operation.

2023-06-22 19:55 UTC, MuhammedAshraf2020 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_loss.py
> +        max_num_dims=1,
I think you are not covering all of the input space

2023-06-25 10:56 UTC, Kamil2601 commented
@MuhammedAshraf2020 fixed

2023-06-27 13:54 UTC, MuhammedAshraf2020 commented
Hey @Kamil2601, As you see here, the frontend function doesn't act similar to the original function with the same input shape/dtype 

![Screenshot from 2023-06-27 16-47-07](https://github.com/unifyai/ivy/assets/53389411/d801b397-480d-469f-97fd-51d151561611)

2023-06-27 15:02 UTC, Kamil2601 commented
@MuhammedAshraf2020 the problem is with binary_cross_entropy_loss, not mse
![image](https://github.com/unifyai/ivy/assets/33699940/28a4a15e-6b05-49a5-bfec-fe3b415e4250)

For me original paddle mse_loss returns tensor of shape (1,)
![image](https://github.com/unifyai/ivy/assets/33699940/cfaa821f-dcdf-4c88-b9e0-892ea3548017)

2023-06-27 16:51 UTC, MuhammedAshraf2020 commented
It seems that there is a problem with different versions, we will have a look on that

2023-06-27 16:51 UTC, MuhammedAshraf2020 approved these changes

2023-06-27 16:51 UTC, MuhammedAshraf2020 commented
LGTM

2023-06-27 16:52 UTC, merged