Added Cond
unifyai/ivy pull request #17529
Opened 2023-06-21 21:23 UTC by avi-thakur-0812

Close #17525

2023-06-22 09:10 UTC, avi-thakur-0812 commented
@zaeemansari70  Hey! Could you please review my PR?

2023-06-25 08:42 UTC, closed without merging

2023-06-25 08:44 UTC, zaeemansari70 requested changes
Hi @avi-thakur-0812 ,

I've requested some changes below :slightly_smiling_face: 

Do let me knwo of you have any other questions!
Thanks!

2023-06-25 08:44 UTC, zaeemansari70 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_linalg.py
> +    dtype_and_x=_get_dtype_and_matrix_non_singular(),
`_get_dtype_and_matrix_non_singular()`, is not defined and implemented anywhere.

2023-06-25 08:44 UTC, zaeemansari70 commented on ivy/functional/backends/torch/linear_algebra.py
> -# Extra #
Kindly un-commit your change from this file, you do not need to remove this.