Implement stateful class for dct #17431
unifyai/ivy pull request #17531
Opened 2023-06-21 22:11 UTC by rubada

Close #17431

2023-06-26 08:46 UTC, Sam-Armstrong requested changes
@rubada Thanks for making the PR! Looks like the test you wrote is failing, could you try to get it passing. You can use the command pytest ivy_tests/test_ivy/test_stateful/test_layers.py::test_dct to run the test.

2023-07-08 15:40 UTC, rubada commented
@Sam-Armstrong Hi Can you review my code.
Thanks

2023-07-08 17:49 UTC, Sam-Armstrong requested changes
@rubada sorry for the delay! I've left a couple of comments for minor things to change, but this generally looks really good, so we should be good to merge once that's done. Thanks 🙂

2023-07-08 17:49 UTC, Sam-Armstrong commented on ivy/stateful/layers.py
> +        out=None,
We don't need this 'out' kwarg in stateful layers. Please can you remove it, its description in the docstring, etc?

2023-07-08 17:49 UTC, Sam-Armstrong commented on ivy/stateful/layers.py
> +            The lenght of the transform. If n is less than the input signal lenght,
typo in the word 'length'

2023-07-08 19:40 UTC, rubada commented on ivy/stateful/layers.py
> +            The lenght of the transform. If n is less than the input signal lenght,
Thanks🙏🏻

2023-07-09 00:09 UTC, Sam-Armstrong approved these changes
lgtm! thanks @rubada 😁

2023-07-09 00:10 UTC, merged

2023-07-09 11:06 UTC, shephinphilip commented
I am encountering error 

 pip install --target=C:/Users/USER/AppData/Local/Programs/Python/Python311 --user -e .
ERROR: Can not combine '--user' and '--target'

and another error 

from ivy.functional.ivy.layers import _deconv_length
ModuleNotFoundError: No module named 'ivy.functional'

please help me out in this