Paddle glu
unifyai/ivy pull request #17566
Opened 2023-06-22 10:40 UTC by Adeola23

closes #16299

2023-06-22 10:46 UTC, Adeola23 commented
Hi @MuhammadSaeedBatikh I mistakenly closed the PR(https://github.com/unifyai/ivy/pull/17198) you commented on, could pls review the changes suggested

2023-06-22 13:59 UTC, Adeola23 commented
hi @juliagsy, the failed test are unrelated and for context pls see https://github.com/unifyai/ivy/pull/17198

2023-06-22 14:10 UTC, MuhammadSaeedBatikh commented
Hi @Adeola23, the `.filter(lambda x: x[-1] % 2 == 0)` seems to do the trick! However, you only seem to be testing for the last dimension (i.e. axis = -1).

2023-06-25 16:00 UTC, MuhammadSaeedBatikh commented
> @MuhammadSaeedBatikh I'm stuck on how to test for axis I'm either getting `ValueError: Expected value range of axis is [-1, 1], but received axis: 1` or hypothesis error

Hi @Adeola23, putting aside this issue for now; the tests are not running properly:
`E   TypeError: _get_input_and_new_shape() missing 1 required positional argument: 'draw'`
You need to add `@st.composite` decorator to `_get_input_and_new_shape` function.
Once added, your tests should run properly:
I got the following, different exception 
```
>           return op(x)
E           RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int8) of kernel `sigmoid` is not registered.
E             [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:147)
E           
E           Falsifying example: test_paddle_glu(
E               input_x_shape=(['int8'], [array([[0, 0],
E                        [0, 0]], dtype=int8)]),
E               fn_tree='ivy.functional.frontends.paddle.nn.functional.glu',
E               test_flags=FrontendFunctionTestFlags(
E                   num_positional_args=0,
E                   with_out=True,
E                   inplace=False,
E                   as_variable=[False],
E                   native_arrays=[False],
E                   generate_frontend_arrays=False,
E               ),
E               on_device='cpu',
E               frontend='paddle',
E           )
E           
```

2023-06-25 16:23 UTC, Adeola23 commented
> > @MuhammadSaeedBatikh I'm stuck on how to test for axis I'm either getting `ValueError: Expected value range of axis is [-1, 1], but received axis: 1` or hypothesis error
> 
> Hi @Adeola23, putting aside this issue for now; the tests are not running properly: `E TypeError: _get_input_and_new_shape() missing 1 required positional argument: 'draw'` You need to add `@st.composite` decorator to `_get_input_and_new_shape` function. Once added, your tests should run properly: I got the following, different exception:
> 
> ```
> >           return op(x)
> E           RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int8) of kernel `sigmoid` is not registered.
> E             [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:147)
> E           
> E           Falsifying example: test_paddle_glu(
> E               input_x_shape=(['int8'], [array([[0, 0],
> E                        [0, 0]], dtype=int8)]),
> E               fn_tree='ivy.functional.frontends.paddle.nn.functional.glu',
> E               test_flags=FrontendFunctionTestFlags(
> E                   num_positional_args=0,
> E                   with_out=True,
> E                   inplace=False,
> E                   as_variable=[False],
> E                   native_arrays=[False],
> E                   generate_frontend_arrays=False,
> E               ),
> E               on_device='cpu',
> E               frontend='paddle',
> E           )
> E           
> ```

Hi @MuhammadSaeedBatikh, I just checked the latest commit and  `@st.composite` decorator is present  and  the test are running fine unless I test for order axis. Pls check the file changed

2023-06-25 16:23 UTC, Adeola23 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
> +@st.composite
@MuhammadSaeedBatikh

2023-06-26 10:40 UTC, MuhammadSaeedBatikh commented
> > > @MuhammadSaeedBatikh I'm stuck on how to test for axis I'm either getting `ValueError: Expected value range of axis is [-1, 1], but received axis: 1` or hypothesis error
> > 
> > 
> > Hi @Adeola23, putting aside this issue for now; the tests are not running properly: `E TypeError: _get_input_and_new_shape() missing 1 required positional argument: 'draw'` You need to add `@st.composite` decorator to `_get_input_and_new_shape` function. Once added, your tests should run properly: I got the following, different exception:
> > ```
> > >           return op(x)
> > E           RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int8) of kernel `sigmoid` is not registered.
> > E             [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:147)
> > E           
> > E           Falsifying example: test_paddle_glu(
> > E               input_x_shape=(['int8'], [array([[0, 0],
> > E                        [0, 0]], dtype=int8)]),
> > E               fn_tree='ivy.functional.frontends.paddle.nn.functional.glu',
> > E               test_flags=FrontendFunctionTestFlags(
> > E                   num_positional_args=0,
> > E                   with_out=True,
> > E                   inplace=False,
> > E                   as_variable=[False],
> > E                   native_arrays=[False],
> > E                   generate_frontend_arrays=False,
> > E               ),
> > E               on_device='cpu',
> > E               frontend='paddle',
> > E           )
> > E           
> > ```
> 
> Hi @MuhammadSaeedBatikh, I just checked the latest commit and `@st.composite` decorator is present and the test are running fine unless I test for other axis. Pls check the file changed

You're right. Do you get the same error I posted here?

2023-06-26 11:33 UTC, Adeola23 commented
> > > > @MuhammadSaeedBatikh I'm stuck on how to test for axis I'm either getting `ValueError: Expected value range of axis is [-1, 1], but received axis: 1` or hypothesis error
> > > 
> > > 
> > > Hi @Adeola23, putting aside this issue for now; the tests are not running properly: `E TypeError: _get_input_and_new_shape() missing 1 required positional argument: 'draw'` You need to add `@st.composite` decorator to `_get_input_and_new_shape` function. Once added, your tests should run properly: I got the following, different exception:
> > > ```
> > > >           return op(x)
> > > E           RuntimeError: (NotFound) The kernel with key (CPU, NCHW, int8) of kernel `sigmoid` is not registered.
> > > E             [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /paddle/paddle/phi/core/kernel_factory.cc:147)
> > > E           
> > > E           Falsifying example: test_paddle_glu(
> > > E               input_x_shape=(['int8'], [array([[0, 0],
> > > E                        [0, 0]], dtype=int8)]),
> > > E               fn_tree='ivy.functional.frontends.paddle.nn.functional.glu',
> > > E               test_flags=FrontendFunctionTestFlags(
> > > E                   num_positional_args=0,
> > > E                   with_out=True,
> > > E                   inplace=False,
> > > E                   as_variable=[False],
> > > E                   native_arrays=[False],
> > > E                   generate_frontend_arrays=False,
> > > E               ),
> > > E               on_device='cpu',
> > > E               frontend='paddle',
> > > E           )
> > > E           
> > > ```
> > 
> > 
> > Hi @MuhammadSaeedBatikh, I just checked the latest commit and `@st.composite` decorator is present and the test are running fine unless I test for other axis. Pls check the file changed
> 
> You're right. Do you get the same error I posted here?

Hi @MuhammadSaeedBatikh, I don't get the same error.

2023-06-26 11:34 UTC, Adeola23 commented
> Hi @Adeola23, the `.filter(lambda x: x[-1] % 2 == 0)` seems to do the trick! However, you only seem to be testing for the last dimension (i.e. axis = -1).

HI @MuhammadSaeedBatik, did you get the same error when you tested here?

2023-06-27 20:49 UTC, Adeola23 commented
@MuhammadSaeedBatikh

2023-08-15 22:36 UTC, MahmoudAshraf97 commented
Hi @Adeola23  , are you still working on this function?

2023-08-20 22:58 UTC, MahmoudAshraf97 requested changes

2023-08-20 22:58 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/activation.py
> +    y = ivy.shape(x)
please use a better descriptive variable name other than `y`

2023-08-20 22:58 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/activation.py
> +    rank = len(ivy.shape(y))
```suggestion
    rank = y.ndim
```

2023-08-20 22:58 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
> +    test_with_out=st.just(True),
why are you forcing the function to test the out argument although it doesn't exist?

2023-08-20 22:58 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
you are not testing for `axis` argument

2023-08-20 23:11 UTC, closed without merging

2023-08-20 23:19 UTC, Adeola23 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
I'd make the changes and thanks for the response

2023-08-20 23:20 UTC, Adeola23 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
Plus I'm going to tag to review the new pull request.