Creation Function Docstrings
unifyai/ivy pull request #1757
Opened 2022-07-04 08:37 UTC by jkeane508

Updated doc-strings

Change in ivy_tests to accompany for rename of test_array_function

2022-07-04 18:09 UTC, mattbarrett98 requested changes
It seems as though you've copy and pasted the same docstring for all of them, so you're linking to the elementwise tan function in all of them. Also you're changes have quite a few failures in the `lint` CI check if you could take a look at these.

2022-07-05 08:25 UTC, jkeane508 commented
Oh yea, I forgot to go back and change the links, thanks!

2022-07-05 13:52 UTC, mattbarrett98 commented
Yes there is! I presume you haven't set up the pre commit hook yet. Go to your terminal and run `pip install pre-commit`, then run `pre-commit install`. This should then set up the pre commit hook for you, which means every time you try and git commit, the lint checks will automatically run (and if there are failures the commit will fail, and will continue to block your commits until the issues are resolved)

2022-07-06 09:19 UTC, mattbarrett98 reviewed
this looks good to me, apart from a very small detail in the meshgrid link, it says `mesgrid`

2022-07-06 12:14 UTC, jkeane508 commented
Ok, the branch was a lot of commits behind but it should be up do date now. The change to the torch backend, I think is from the pre commit hook? Its only a formatting change.

2022-07-06 14:53 UTC, djl11 requested changes
aside from one small change, looks good to me! Feel free to merge once this small thing is fixed.

2022-07-06 14:53 UTC, djl11 commented on ivy/functional/ivy/creation.py
> +    out: Optional[ivy.Array] = None,
`out` argument should be keyword-only, with a `*` added above it. This is the case for all functions (I may have missed this for others).

2022-07-06 15:52 UTC, merged