paddle dropout function
unifyai/ivy pull request #17664
Opened 2023-06-23 17:46 UTC by bsameer65

Close #17415

2023-06-24 08:38 UTC, Daniel4078 commented
add_frontend_checklist

2023-06-24 12:00 UTC, Daniel4078 requested changes
Hello! I just checked that your test is currently passing fine. But you do still need to fix some formatting errors. Check my comments below for some details. Thanks!

2023-06-24 12:00 UTC, Daniel4078 requested changes
Hello! I just checked that your test is currently passing fine. But you do still need to fix some formatting errors. Check my comments below for some details. Thanks!

2023-06-24 19:46 UTC, bsameer65 commented
Hi, can you review it again? Thankyou.

2023-06-25 00:27 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +def get_mask(shape,device,prob,seed=None):
-def get_mask(shape,device,prob,seed=None):
+
+def get_mask(shape, device, prob, seed=None):

2023-06-25 00:27 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +        ivy.random_uniform(shape=shape, device=device, seed=seed)
-        ivy.random_uniform(shape=shape, device=device, seed=seed)
-        < prob,
+        ivy.random_uniform(shape=shape, device=device, seed=seed) < prob,

2023-06-25 00:28 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +
one extra empty line needed here

2023-06-25 00:28 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +def dropout(x, p=0.5, axis=None, training=True,
-def dropout(x, p=0.5, axis=None, training=True,
-            mode='upscale_in_train', name=None):
-    
+def dropout(x, p=0.5, axis=None, training=True, mode="upscale_in_train", name=None):

2023-06-25 00:29 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +
```
-        
-    elif axis==None or (isinstance(axis,list) and len(axis==2)):
-        mask = get_mask(shape=x.shape, device=ivy.dev(x),prob=p, seed=None)
-    elif axis==0:
-        mask = get_mask(shape=(x.shape[0],1), device=ivy.dev(x), prob=p)
+
+    elif axis == None or (isinstance(axis, list) and len(axis == 2)):
+        mask = get_mask(shape=x.shape, device=ivy.dev(x), prob=p, seed=None)
+    elif axis == 0:
+        mask = get_mask(shape=(x.shape[0], 1), device=ivy.dev(x), prob=p)
```

2023-06-25 00:29 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +    elif axis==1:
```
-    elif axis==1:
-        mask = get_mask(shape=(1,x.shape[1]), device=ivy.dev(x), prob=p)
+    elif axis == 1:
+        mask = get_mask(shape=(1, x.shape[1]), device=ivy.dev(x), prob=p)
```

2023-06-25 00:29 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +    if mode == 'upscale_in_train':
```
-    if mode == 'upscale_in_train':
+    if mode == "upscale_in_train":
```

2023-06-25 00:30 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +            ret= ivy.multiply(out, 1.0 / (1.0 - p))
```
-            ret= ivy.multiply(out, 1.0 / (1.0 - p))
+            ret = ivy.multiply(out, 1.0 / (1.0 - p))
```

2023-06-25 00:30 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +            ret = ivy.multiply(x,(1.0-p))
```
-            ret = ivy.multiply(x,(1.0-p))
-    return ret
+            ret = ivy.multiply(x, (1.0 - p))
+    return ret
```

2023-06-25 00:31 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +    return ret
please keep an empty line at the end of files

2023-06-25 00:31 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_common.py
> +#dropout
-#dropout
+
+# dropout

2023-06-25 00:31 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_common.py
> +    axis= st.integers(min_value=0, max_value=1),
```
-    axis= st.integers(min_value=0, max_value=1),
-    training= st.booleans() ,
-    mode= st.one_of(*[st.just(seq) for seq in ['upscale_in_train','downscale_in_infer']]),
+    axis=st.integers(min_value=0, max_value=1),
+    training=st.booleans(),
+    mode=st.one_of(
+        *[st.just(seq) for seq in ["upscale_in_train", "downscale_in_infer"]]
+    ),
```

2023-06-25 00:32 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_common.py
> +    )
please keep an empty line at the end of files

2023-06-26 01:03 UTC, Daniel4078 approved these changes
Looks good to me!

2023-06-26 02:30 UTC, merged