Implemented min in paddle.tensor
unifyai/ivy pull request #17680
Opened 2023-06-24 02:06 UTC by Law47

2023-06-26 09:05 UTC, sherry30 requested changes
Hi,
Can you remove the changes from the .idea files.
Also you have to add a test for the function that you've added. You can go through our docs [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html) to get an idea how you would do that. 

Thanks

2023-06-29 03:39 UTC, sherry30 requested changes
Hi,

The changes in the .idea folder are still there. Can you remove those.
I think you've added the min function twice by accident, can you remove one implementation.'

Thanks

2023-07-01 11:07 UTC, sherry30 requested changes
minor changes,
other than that works fine

Thanks

2023-07-01 11:07 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
> +        available_dtypes=st.one_of(helpers.get_dtypes("float", "integer")),
You can add `helpers.get_dtypes("numeric")` instead

2023-07-01 11:07 UTC, sherry30 commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        {"2.5.0 and below": ("float16", "float32", "float64", "int32", "int64")},
`float16` is not supported for this

2023-07-01 11:07 UTC, sherry30 commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        return ivy.min(self._ivy_array, axis=axis, keepdim=keepdim)
`ivy.min` takes `keepdims` with the "s".

2023-07-06 08:39 UTC, sherry30 requested changes
minor change

2023-07-06 08:39 UTC, sherry30 commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +    def min(self, axis=None, keepdims=False, name=None):
Its still `keepdim` for paddle's `min` function.
only ivy's function has `keepdims`

2023-07-11 08:11 UTC, sherry30 commented
ivy-gardener

2023-07-11 08:20 UTC, sherry30 requested changes
lgtm!

Can you resolves the conflicts, I'll merge it as soon as you do. Also feel free to ask for a review when you're done making changes. 😄 

Thanks

2023-07-11 21:49 UTC, Law47 commented
Hello, I have resolved the conflicts. Please review my PR.

2023-07-12 10:25 UTC, sherry30 commented
ivy-gardener

2023-07-12 10:27 UTC, merged