EHN: adding greater_equal this paddle tensor.py
unifyai/ivy pull request #17746
Opened 2023-06-25 10:45 UTC by MuhammadNizamani

adding  greater_equal from issue    #17745

2023-06-25 10:54 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-27 17:30 UTC, zaeemansari70 reviewed
Hi @MuhammadNizamani ,

The PR looks great and it's ready to merge, kindly resolve your conflicts on this PR and let me know so I can merge it.

Thanks! :slightly_smiling_face:

2023-07-03 15:47 UTC, zaeemansari70 reviewed
Hi @MuhammadNizamani  
The conflicts are still there :slightly_smiling_face:

2023-07-25 17:29 UTC, zaeemansari70 requested changes
A small change is needed. there has been some changes in the testing pipeline, I have added the changes that you'll need.

I've locally tested your code, after that, you will probably need to add the decorator to handle the dtype errors you'll face.
Also, kindly reslove the merge conflicts as they seem to appear again :sweat_smile:  

Thanks!

2023-07-25 17:29 UTC, zaeemansari70 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +    method_flags,
backend_fw

2023-07-25 17:29 UTC, zaeemansari70 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +        method_input_dtypes=input_dtype,
backend_to_test=backend_fw

2023-08-07 15:11 UTC, zaeemansari70 requested changes
It's failing for the following error:
```
E           ivy.utils.exceptions.IvyValueError: numpy: nested_map: numpy: nested_map: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:536)
E           
E           Falsifying example: test_paddle_greater_equal(
E               backend_fw='tensorflow',
E               frontend='paddle',
E               on_device='cpu',
E               dtypes_and_x=(['bfloat16', 'bfloat16'],
E                [array(-1, dtype=bfloat16), array(-1, dtype=bfloat16)]),
E               frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.paddle', framework_init_module='paddle', init_name='to_tensor', method_name='greater_equal'),
E               method_flags=FrontendMethodTestFlags(
E                   num_positional_args=0,
E                   as_variable=[False],
E                   native_arrays=[False],
E               ),
E               init_flags=FrontendMethodTestFlags(
E                   num_positional_args=1,
E                   as_variable=[False],
E                   native_arrays=[False],
E               ),
E           )
E           
E           You can reproduce this example by temporarily adding @reproduce_failure('6.82.0', b'AXicY2YAAkYGCGBEY4MBAADUAAg=') as a decorator on your test case
```
"bfloat16" is not supported, add that in the unsupported dtypes.
Kindly request a review once the tests are passing.
Feel free to ask any question by commenting!
Thanks!

2023-08-21 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-21 05:54 UTC, MuhammadNizamani commented
I am working on it

2023-09-05 06:55 UTC, MuhammadNizamani commented
I am working on this

2023-10-16 21:32 UTC, closed without merging

2023-10-16 21:32 UTC, MahmoudAshraf97 commented
Hi Muhammad, Feel free to open a new PR when it's ready