Add stateless_categorical for TensorFlow frontend
unifyai/ivy pull request #17749
Opened 2023-06-25 10:56 UTC by eekamal

fixes #17747

2023-06-26 09:05 UTC, Sam-Armstrong requested changes
Hey @eekamal, thanks for making the pull request! I've left a couple of comments, please could you make the changes accordingly. Also please can you ensure that the test you wrote is passing? You can run it with the command pytest ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_ivy_stateless_categorical 🙂

2023-06-26 09:05 UTC, Sam-Armstrong commented on ivy/functional/frontends/tensorflow/random.py
> +        samples = ivy.assign(samples, sample, indices=i)
There is no ivy.assign method, you will have to find an alternative

2023-06-26 11:45 UTC, eekamal commented
I tried but I really need more guidance please @Sam-Armstrong

2023-06-27 08:42 UTC, Sam-Armstrong commented
@eekamal I'd recommend reading through these two sections of the docs to help you out:
https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html#ivy-frontends
https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html

If you have any specific questions, feel free to let me know either here or on discord 😁

2023-06-30 23:51 UTC, Sam-Armstrong requested changes
@eekamal Sorry its taken a while for me to look at this, I've been really busy. I've suggested a change here which allows the tests to run, but looks like the test cases are failing. Please could you try to debug the problem? Thanks 😊

2023-06-30 23:51 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py
> +    fn_tree="ivy.random.stateless_categorical",
```suggestion
    fn_tree="tensorflow.random.stateless_categorical",
```

2023-07-10 13:05 UTC, Sam-Armstrong requested changes
@eekamal the tests are still failing for me. Have you ran them with pytest ivy_tests/test_ivy/test_frontends/test_tensorflow/test_random.py::test_ivy_stateless_categorical ?

2023-07-26 05:53 UTC, closed without merging

2023-07-26 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.