Added floor_div paddle frontend
unifyai/ivy pull request #17869
Opened 2023-06-27 09:43 UTC by pranjalkar99

2023-06-27 09:45 UTC, pranjalkar99 commented
Close #17665

2023-06-27 09:54 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-10 06:38 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
> +    dtypes_and_x,
I think you've forgotten to use the `@frontend_method` decorator here. You can look at the other examples above to see how to correctly write the test function 🙂

2023-07-10 06:39 UTC, YushaArif99 requested changes
Hi @pranjalkar99 

Apologies for the late review. Have been extremely busy with work recently and so haven't had the time to review PRs 😓 

Could you kindly address the abovementioned issue and re-request a review once all tests are passing. Thanks! 🙂

2023-07-18 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-26 05:53 UTC, closed without merging

2023-07-26 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.