Added dropout1d functions to torch frontends and paddle backends(#17808)
unifyai/ivy pull request #17873
Opened 2023-06-27 12:00 UTC by yunsemr

I added dropout1d function to torch frontends and a test function for it, then I added dropout1d function to paddle backend to handle the test. The issue number is #17808

2023-06-27 12:24 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-27 12:43 UTC, yunsemr commented
I have just edited the description.

2023-06-27 12:54 UTC, Sam-Armstrong commented
Thanks for doing that @yunsemr! I think it would actually make more sense to split this into two pull requests - one for the torch frontend and one for the paddle backend. You can keep this one open, just removing the paddle backend changes, then make a new PR for the paddle changes.

2023-06-27 13:00 UTC, yunsemr commented
How can I split them, should I close this pull request and create new ones? And one more thing, the backend issue is not open, I wrote it because frontend test failed on paddle backend, so is it a problem that doing something which is not an open issue?

2023-06-27 15:36 UTC, yunsemr commented
Actually I am stuck, how can I restart the process because everything I try causes another problem :) I could not understand how to do what you said.

2023-06-27 15:45 UTC, Sam-Armstrong commented
@yunsemr You can make a new commit simply changing the paddle backend to what it was before you made any changes. Then push that commit here.

2023-06-27 15:49 UTC, yunsemr commented
@Sam-Armstrong I deleted the changes and committed. What then?

2023-06-27 15:51 UTC, Sam-Armstrong commented
Great! Now you can open a separate pull request with those changes by creating a new branch from your master, and committing your changes there. Then you can push those changes to a new branch of your fork and make a new PR from there :)

2023-06-27 15:57 UTC, yunsemr commented
You mean, I should push both backend and frontend changes to this new branch right? @Sam-Armstrong

2023-06-27 16:02 UTC, Sam-Armstrong commented
@yunsemr No just the changes you made to paddle which you removed here. That way we separate it out into two pull requests.

2023-06-27 16:16 UTC, Sam-Armstrong commented
Looks good, thanks 🙂

2023-06-29 23:16 UTC, Sam-Armstrong requested changes
@yunsemr This looks good! Just one change: we need to be able to handle inplace dropout, which we can do by adding the two lines in my suggested change. One we've done that we should be able to merge. Thanks!

2023-06-29 23:16 UTC, Sam-Armstrong commented on ivy/functional/frontends/torch/nn/functional/dropout_functions.py
> +    return ivy.dropout1d(input, p, training=training)
```suggestion
    if inplace:
        return ivy.dropout1d(input, p, training=training, out=input)
    return ivy.dropout1d(input, p, training=training)
```

2023-06-30 11:27 UTC, yunsemr commented
@Sam-Armstrong, I changed the function as you want to. And one more question, I am an applicant so this is the accepted PR to share url in the questionary right?

2023-06-30 23:28 UTC, Sam-Armstrong approved these changes
@yunsemr Yes, you can you this in your application process 😊

I just realised there was a bug here where we were defaulting to using the wrong data format for torch (channels last rather than channels first). I've pushed the change to fix this. Will get this merged now. Great work!

2023-06-30 23:32 UTC, merged

2023-06-30 23:56 UTC, yunsemr commented
@Sam-Armstrong Thanks!