Add: overlap_and_add tensorflow frontend and backend
unifyai/ivy pull request #17937
Opened 2023-06-28 04:06 UTC by ooshyun

1. Add overlap_and_add function for Tensorflow frontend and backend.
2. Add test for tensorflow frontend

2023-06-28 04:11 UTC, ooshyun commented
Add Signal functions for TensorFlow frontend https://github.com/unifyai/ivy/issues/1559

2023-06-28 04:24 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-28 05:30 UTC, ooshyun commented
@ivy-leaves Thanks for guide! I added PR description with issue and link also.

2023-06-28 16:28 UTC, KareemMAX requested changes
I think you are trying to create a backend function without adding backend functions for it. Do you really need to add `overlap_and_add`?

2023-06-29 04:29 UTC, ooshyun commented
I understand your question as a necessarily to add overlap_and_add function. I think when we consider inverse short time Fourier transform(istft), then overlap and add has necessary independent object. If so, it may need to add overlap_and_add.

2023-06-29 14:42 UTC, KareemMAX commented
@ooshyun That make sense, but sadly you should add `overlap_and_add` to all backends in that case. You might need to refer to the [open tasks guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) to know how to proceed. In this state your code won't pass tests sadly.

2023-06-30 01:32 UTC, ooshyun commented
I understand. Then do all backends mean "Jax, PyTorch, TensorFlow NumPy and Paddle"? I'll edit and let you know :)

2023-07-16 13:19 UTC, ooshyun commented
I added overlap and add backends for "Jax, PyTorch, TensorFlow NumPy and Paddle. Please check this commit:D

2023-07-16 14:05 UTC, ooshyun commented
@KareemMAX I added overlap and add function in backend for numpy, torch, Jax, paddle. I wander above failure of tests did not include overlap and add.

2023-07-17 11:43 UTC, KareemMAX requested changes
Hey @ooshyun,
Awesome work, I've made some comments that I want you to resolve in order for the PR to be merged. Also I've resolved the issue you were facing which you can see in my comment.

Other than that, seems like paddle backend is failing on your frontend function.

2023-07-17 11:43 UTC, KareemMAX commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +        input_dtypes=input_dtype,
Seems like those are the lines causing the error

```suggestion
    on_device,
):
    input_dtype, x, frame_step = dtype_x_and_args
    helpers.test_function(
        input_dtypes=input_dtype,
```

2023-07-17 11:43 UTC, KareemMAX commented on ivy/data_classes/container/experimental/layers.py
> +            https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/signal/reconstruction_ops.py
Is that necessary?

2023-07-17 11:43 UTC, KareemMAX commented on ivy/data_classes/container/experimental/layers.py
> +            https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/signal/reconstruction_ops.py
Is this necessary?

2023-07-17 11:43 UTC, KareemMAX commented on ivy/functional/ivy/experimental/layers.py
> +        https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/signal/reconstruction_ops.py
Is this necessary?

2023-07-17 17:51 UTC, ooshyun commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
> +    frame_step = draw(helpers.ints(min_value=1, max_value=1e6))
Does it already in a decorator for test_tensorflow_overlap_and_add?

2023-07-17 18:17 UTC, ooshyun commented
@KareemMAX Thanks for reviewing! I applied your comment, and I'll check paddle part.

2023-07-24 15:47 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
> +    frame_step = draw(helpers.ints(min_value=1, max_value=1e6))
Not sure what you mean, please take [this snippet](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py#L74-L90) as an example

2023-07-25 00:03 UTC, ooshyun commented
@KareemMAX Thanks for comments. I'm checking your comment. After finishing, let you know!

2023-09-21 09:23 UTC, KareemMAX commented
Hey @ooshyun,
Sadly I'll close your PR in the meantime as it has been stale for a very long time. I'd like to see your code being added to our codebase. If you would like to open this PR and continue working at anytime feel free to do so.

2023-09-21 09:23 UTC, closed without merging