Added is_floating_point for Paddle frontend
unifyai/ivy pull request #17971
Opened 2023-06-28 10:05 UTC by arshPratap

Solves #17970

2023-06-28 10:15 UTC, arshPratap commented
@hmahmood24 please take a look thanks !

2023-06-28 10:24 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-06-28 13:21 UTC, arshPratap commented
add_frontend_checklist

2023-06-30 17:07 UTC, arshPratap commented
@theRealBird @hmahmood24 I have rebased the current branch with the latest patches in master and have also updated the task list to the best of my knowledge ...please take another look at this. Thanks a lot !

2023-07-02 13:13 UTC, theRealBird commented
Hey @arshPratap,
The PR looks good to me! Thanks a lot for contributing to Ivy. 
I do have a request. Before we merge this, could you please resolve the merge conflicts? Thanks!

2023-07-02 17:35 UTC, arshPratap commented
> Hey @arshPratap, The PR looks good to me! Thanks a lot for contributing to Ivy. I do have a request. Before we merge this, could you please resolve the merge conflicts? Thanks!

Done ! @theRealBird thanks for your review. I have rebased the branch with `master`. PTAL .Thanks again !

2023-07-05 10:06 UTC, arshPratap commented
@theRealBird have rebased it to the latest changes on  `master` branch . Can this be merged now

2023-07-09 10:04 UTC, arshPratap commented
@theRealBird sorry for the delay ! Have rebased to the latest commits ! Please take another look. Thanks

2023-07-09 13:07 UTC, theRealBird requested changes

2023-07-09 13:07 UTC, theRealBird commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
@arshPratap, Thanks for making the changes. I was going through the code once more and I think passing only "float" data-types to a function which checks if a value is a float or not is not the correct approach for testing. We are not checking how does the function behave when the value passed is not a float.

2023-07-09 14:19 UTC, arshPratap commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
Yup yup..completely true..lemme add in a quick fix for this

2023-07-09 14:31 UTC, arshPratap commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
@theRealBird could you take a look now ..decided to move with the `numeric` data types as compared to the previous `float` data type

2023-07-09 14:33 UTC, arshPratap commented
@theRealBird have made the changes you requested .. would love to hearback on any thoughts you have regarding this PR.Thanks

2023-07-18 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-23 18:37 UTC, arshPratap commented
@theRealBird So sorry for the delay..I have rebased the PR to the current changes in the master..Please take a look.Thanks again

2023-07-31 03:42 UTC, theRealBird commented
Hey @arshPratap, I am sorry for the delay at my end too. 
Not sure how this skipped under my radar. Could you please take care of the conflicts one last time (hopefully)?
I will be careful to merge it in time. Thanks!

2023-07-31 03:54 UTC, theRealBird requested changes
Just need to resolve the merge conflicts. Thanks!

2023-07-31 04:38 UTC, arshPratap commented
@theRealBird done !!

2023-07-31 07:33 UTC, theRealBird requested changes
Could you please verify if the test you have implemented is passing? Currently it appears to be failing on the CI dashboard. 

Thanks!

2023-08-22 11:11 UTC, arshPratap commented
@theRealBird thanks for the .. review and so sorry for the late reply..lemme work on failing tests and I will update the thread here regarding the same.
Thanks

2023-08-30 11:04 UTC, arshPratap commented
@theRealBird fixed the tests..seems that there are some datatypes that are not compatible with paddle (unsigned integers being the case) ..i had to remove the `"valid"` and `"numeric"` data types and replace them

2023-09-04 14:52 UTC, arshPratap commented
@theRealBird ...the tests have been completed ..seems like the is_floating_point tests are not failing anymore

2023-09-04 16:31 UTC, theRealBird approved these changes
LGTM

2023-09-04 16:31 UTC, merged