triu_indices
unifyai/ivy pull request #18033
Opened 2023-06-29 09:28 UTC by Sarvesh-Kesharwani

Closes #

2023-06-29 12:19 UTC, Sarvesh-Kesharwani commented
![pycharm64_fIZU7WHQO1](https://github.com/unifyai/ivy/assets/22115102/dfe97a28-638b-4d6e-850c-490300cf9022)

2023-06-30 10:03 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-02 08:35 UTC, hmahmood24 requested changes
Hey @Sarvesh-Kesharwani, requested a couple of changes in the implementation. Do ask for a re-review once done with the changes. Thanks! :)

2023-07-02 08:35 UTC, hmahmood24 commented on ivy/functional/frontends/paddle/tensor/creation.py
> +        return arr
We shouldn't be putting our code in a try block and catching the exceptions, instead let them propagate to the user.

2023-07-02 08:35 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_creation.py
> +    offset=st.integers(min_value=0, max_value=4),
`offset` needs to be tested for negative values as well

2023-07-02 08:35 UTC, hmahmood24 commented on ivy/functional/frontends/paddle/tensor/creation.py
> +        arr = ivy.astype(arr, ivy.as_native_dtype(dtype))
No need to use the `ivy.as_native_dtype(dtype)`. Simply pass in `dtype` here. We don't work with anything native in the frontends.

2023-07-11 12:19 UTC, closed without merging