tril_indices
unifyai/ivy pull request #18040
Opened 2023-06-29 11:16 UTC by Sarvesh-Kesharwani

Closed #18039

2023-06-29 11:17 UTC, Sarvesh-Kesharwani commented
![pycharm64_Jz53Ojlwa4](https://github.com/unifyai/ivy/assets/22115102/a3b51c0c-f44e-4049-98c0-1b6b2cbe1d55)

2023-06-29 13:50 UTC, CatB1t requested changes

2023-06-29 13:50 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> -
Could you please revert unrelated changes to the issue? Thanks!

2023-07-02 08:41 UTC, hmahmood24 requested changes
Hey @Sarvesh-Kesharwani, requested changes for you to look into. Thanks! :)

2023-07-02 08:41 UTC, hmahmood24 commented on ivy/functional/frontends/paddle/tensor/creation.py
> +def tril_indices(row, col=None, offset=0, dtype="int64"):
The `col` parameter is not optional and so it shouldn't have a default value of `None` as indicated in the official docs

2023-07-02 08:41 UTC, hmahmood24 commented on ivy/functional/frontends/paddle/tensor/creation.py
> +    arr = ivy.astype(arr, ivy.as_native_dtype(dtype))
Again, we shouldn't be passing in `ivy.as_native_dtype` here, instead just `dtype`

2023-07-02 08:41 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_creation.py
> +    offset=st.integers(min_value=0, max_value=4),
`offset` should be tested for negative values as well

2023-07-05 19:01 UTC, closed without merging