updated asinh function
unifyai/ivy pull request #1805
Opened 2022-07-06 23:24 UTC by Rouizi

2022-07-06 23:25 UTC, Rouizi commented
- [ ]  #1792

2022-07-07 18:40 UTC, ankitdsi2010 commented
Looks good to me, Thank you

2022-07-08 17:32 UTC, Rouizi commented
Can you please review this PR? thank you

2022-07-08 17:58 UTC, ankitdsi2010 requested changes
then check if all the tests run properly

2022-07-08 17:58 UTC, ankitdsi2010 commented on ivy/functional/ivy/elementwise.py
> +    With :code:`ivy.NativeArray` input:
add space above and below the line 497

2022-07-08 18:59 UTC, Rouizi commented
I just added a new line. Please re-review my PR!

2022-07-08 19:30 UTC, ankitdsi2010 requested changes

2022-07-08 19:30 UTC, ankitdsi2010 commented on ivy/functional/backends/tensorflow/elementwise.py
>      return tf.asinh(x)
cast x to float type before passing to tf.asinh function to prevent attribute type errors in tensorflow

2022-07-08 20:11 UTC, Rouizi commented
I updated the dtype of x.

2022-07-08 20:21 UTC, merged

2022-07-08 20:21 UTC, ankitdsi2010 commented
lgtm ! thank you for the contribution

2022-07-08 20:22 UTC, Rouizi commented
Thank you.