updating docs
unifyai/ivy pull request #18103
Opened 2023-06-30 11:28 UTC by ndurumo254

Decorator order

2023-07-03 13:26 UTC, KareemMAX requested changes
I think this order is irrelevant to `ivy_tests`. For context https://github.com/unifyai/ivy/blob/b8b63b610c50e846f90e6e9ced64ad3bef5e3d6a/ivy/func_wrapper.py#L14-L32 is actually a file in `ivy` that holds global function wrapper if I understand correctly.

Anyhow I think @danielmunioz and @juliagsy might have more experience than me in that part of the docs

2023-07-03 16:22 UTC, danielmunioz commented
Yeah, these decorators are used for the framework mostly, I don't think they have any relevance for that part of the testing docs at least
Is this for the Trello task on adding this info to the docs? If so, I believe adding this info to the [function wrapping](https://unify.ai/docs/ivy/overview/deep_dive/function_wrapping.html) section of the deep dive would be better

2023-07-03 16:29 UTC, danielmunioz commented
Yeah, I think it'd be more useful to have this in the function wrapping section :)

2023-07-03 16:32 UTC, ndurumo254 commented
> Yeah, I think it'd be more useful to have this in the function wrapping section :)

ok

2023-07-04 08:56 UTC, zaeemansari70 reviewed
Hi @ndurumo254 , 

As @danielmunioz mentioned that you should be adding these in the function wrappers section in the deep dive :+1: 
I remember @vedpatwardhan working on something similar, just tagging him to avoid any overlap.

Thanks! :slightly_smiling_face:

2023-07-05 05:56 UTC, vedpatwardhan requested changes
Hey @ndurumo254, that's certainly an important think we've missed out on adding to the deep dive, just requested a small change. Thanks 🙂

2023-07-05 05:56 UTC, vedpatwardhan commented on docs/overview/deep_dive/ivy_tests.rst
> +- Decorator order
I think this should be placed on the Function Wrappers page of the deep dive instead (as everyone's already mentioned), as that page also has descriptions of what each decorator does

2023-07-06 14:21 UTC, KareemMAX requested changes
I guess you might have added `bincount` by mistake. I think it deserves a different PR instead. I won't review the decorator docs because I believe there are better people here to review than me 😅

Please delete `bincount` related code and remove me as a reviewer.

2023-07-06 16:24 UTC, danielmunioz commented
Hey! @ndurumo254!, the info looks good just a couple of things, the "test decorators" section would be work better if it'd be right before the "Decorator Order" section, it's ok to have it under "Function wrapping" but I think it'd be clearer to have it outside "Decorator order", also there is a minor typo with the word "Pytets", and could you also remove the comment linking this PR to `bincount` too please?

Thanks!

2023-07-06 18:35 UTC, ndurumo254 commented
> Hey! @ndurumo254!, the info looks good just a couple of things, the "test decorators" section would be work better if it'd be right before the "Decorator Order" section, it's ok to have it under "Function wrapping" but I think it'd be clearer to have it outside "Decorator order", also there is a minor typo with the word "Pytets", and could you also remove the comment linking this PR to `bincount` too please?
> 
> Thanks!

have done the changes

2023-07-06 20:28 UTC, danielmunioz commented
Yeah, last thing, I just made Decorators order a subsection for clarity's sake
Overall LGTM! Merging now

Thanks @ndurumo254!!

2023-07-06 20:31 UTC, merged