feat: add gru
unifyai/ivy pull request #18104
Opened 2023-06-30 11:47 UTC by notjedi

Closes #14698

2023-07-03 14:15 UTC, notjedi commented
@paulaehab can you please review?

2023-07-06 15:16 UTC, notjedi commented
@paulaehab can you please review?

2023-07-06 20:41 UTC, paulaehab commented on ivy/data_classes/container/layers.py
>              prune_unapplied=prune_unapplied,
This code must be added in container/experimental/layers

2023-07-06 20:42 UTC, paulaehab commented on ivy_tests/test_ivy/test_functional/test_nn/test_layers.py
>          bias=bias,
This code also needed to be add in test_experimental

2023-07-06 20:48 UTC, paulaehab commented on ivy/functional/ivy/experimental/layers.py
> +    Compute an one-layer GRU. This operator is usually supported via some custom
This documentation you took it from ONNX documentation you need to write the documentation in your own according to paramters and special cases

2023-07-06 20:49 UTC, paulaehab requested changes
You must look at the forward call for this function of each in the following frameworks (torch,tensorflow,paddle,Jax if founded) and check all arguments and to be sure if there is any special cases look at adding superset docs https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html

2023-07-19 08:21 UTC, notjedi commented
need a little help here. so after checking the docs for torch, tensorflow and paddle. there are a few parameters that are not common b/w them. for example, the following params are not present in all of them.

1. dropout
2. seq_length
3. bidirectional
4. bias / use_bias

so should i have to add them to the ivy params and manage them within the function?

2023-07-27 18:14 UTC, paulaehab commented
> need a little help here. so after checking the docs for torch, tensorflow and paddle. there are a few parameters that are not common b/w them. for example, the following params are not present in all of them.
> 
> 1. dropout
> 2. seq_length
> 3. bidirectional
> 4. bias / use_bias
> 
> so should i have to add them to the ivy params and manage them within the function?
Hi @notjedi sorry for late reply this PR get under my radar 😄 
yes, you have to add these parameters to ivy and handle them in the function to achieve the superset behavior check this link in doc: https://unify.ai/docs/ivy/overview/deep_dive/superset_behaviour.html

2023-07-28 07:46 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-13 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-20 05:53 UTC, closed without merging

2023-08-20 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.