added jax.numpy.round function
unifyai/ivy pull request #18128
Opened 2023-07-01 07:04 UTC by x0axz

Close https://github.com/unifyai/ivy/issues/12370

2023-07-02 01:03 UTC, Daniel4078 commented
Can you please comment `add_frontend_checklist` so that the Ivy bot can bring up a list of things to do in a frontend task, thanks!

2023-07-02 05:55 UTC, x0axz commented
@Daniel4078 done. please review now.

2023-07-02 13:19 UTC, Daniel4078 requested changes
Found something for you to fix, check the comments below, thanks!

2023-07-02 13:19 UTC, Daniel4078 commented on .github/workflows/checklist_actions.yml
> +    if: ${{ github.event.issue.pull_request }}
I don't think you should push changes in this unrelated files. So can you revert it?

2023-07-02 13:19 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_math.py
> +        available_dtypes=["float64"],
why the available_dtype here is only one, you should use the helpers.get_dtypes() function instead to cover all cases.

2023-07-02 22:34 UTC, Daniel4078 commented
I just found another thing for you to see: ivy/functional/frontends/jax/numpy/mathematical_functions.py:715:1: F811 redefinition of unused 'round' from line 545
It seems like there was another definition of round in the file, but that one may not be fully correct as well. So please remove that duplicated thing.

2023-07-04 00:34 UTC, x0axz commented
@Daniel4078 Thanks for reviewing. Fixed mention issues; please review now.

2023-07-04 05:41 UTC, Daniel4078 approved these changes
There was a small backend problem(https://github.com/unifyai/ivy/actions/runs/5449648901/jobs/9914787471#step:3:3475). But it is not yours. Looks good to me, Thanks

2023-07-04 05:42 UTC, merged