docstring_example_added_ivy_functional_ivy_activations_sigmoid
unifyai/ivy pull request #18133
Opened 2023-07-01 07:33 UTC by hemrajat

Close #18127

2023-07-01 11:31 UTC, hemrajat commented
Hi @hmahmood24 Can you please tell me what is the issue in failing checks ?
Some time a test fail and some time it passes

2023-07-07 07:25 UTC, hemrajat commented
Hi @hmahmood24 Can you please tell me what is the issue in failing checks ?
Some time a test fail and some time it passes

2023-07-07 07:30 UTC, hmahmood24 commented
> Hi @hmahmood24 Can you please tell me what is the issue in failing checks ? Some time a test fail and some time it passes

Hey @hemrajat. Sure thing I'll review it today. Thanks :)

2023-07-08 08:06 UTC, hmahmood24 commented
Hey @hemrajat. Regarding the tests, you need not worry since you simply added/modified the docstring and not the actual code itself so the only test relevant to you is the `lint / Check formatting / check-formatting (pull_request)` workflow which is passing :) 

However, I reviewed your PR but honestly I can't find anything that's missing with the docstring that this PR strives to add. I think the docstring as is, is quite clear and succinct. Still I think I'm going to leave the decision with @KareemMAX if he thinks we should merge the PR based on the current content or not. Thanks anyways :)

2023-07-08 10:18 UTC, hemrajat commented
Hi @hmahmood24 @KareemMAX  I got email from recruiting team given a list of todo there I saw this function in open todo #754. I saw some examples in doc string examples. I read in docstring example docs https://unify.ai/docs/ivy/overview/deep_dive/docstring_examples.html#ivy-add which says that example in docstring should cover all combination of arguments. Here in this PR I included one or two examples where out parameters is given, in earlier docstring example out argument is not passed. I strived to included that example. 
Thank you

2023-07-10 05:14 UTC, hemrajat commented
Hi @hmahmood24 @KareemMAX Can you please review the pr ? I've provided the reason for creating this pr in previous comment. Please let me know if anything is not clear from my side or if I'm missing something

2023-07-10 15:10 UTC, KareemMAX requested changes
Hey @hemrajat 

I agree with the changes you made, though I have some comments that I'd love you address before merging the PR.

Thank you for the sharp eye and for your contribution 🚀🚀 Waiting for more contributions from you to ivy.

2023-07-10 15:48 UTC, hemrajat commented on ivy/functional/ivy/activations.py
> +               [0.846,0.985,0.001]])
Hi @KareemMAX I've removed this section and added ivy.Container example. Please review the latest change thank you.

2023-07-10 15:49 UTC, hemrajat commented on ivy/functional/ivy/activations.py
> +        array for storing the result, shape of x and out must be same.
Hi @KareemMAX I've adjusted the out description to previous one. For standardized purpose it is better to stick with previous description. 
Thank you

2023-07-11 10:58 UTC, hemrajat commented
Hi @KareemMAX @hmahmood24 can you please review the changes I've made after resolving the comment of @KareemMAX ? 
Thank you

2023-07-12 10:57 UTC, KareemMAX approved these changes
LGTM! I have added a small clarification that we are using `ivy.Container` on the second half

2023-07-12 10:58 UTC, merged