Close #18063 (permuted in numpy frontend)
unifyai/ivy pull request #18205
Opened 2023-07-03 02:53 UTC by PerfectionistAF

2023-07-10 11:48 UTC, PerfectionistAF commented
# permuted test 
### (path: ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions)

@handle_frontend_test(
    fn_tree="ivy.functional.frontends.numpy.random.functions.permuted",
    dtype_value=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("valid", full=True),
        shape=st.shared(helpers.get_shape(min_num_dims=1), key="value_shape")
    ),
)
def test_permuted(
    *,
    dtype_value,
    permutation,
    x,
    out,
    copy,
    test_flags,
    fn_name,
):
    dtype, value = dtype_value
    shape = dtype_value.shape
    dims = [x for x in range(len(shape))]
    permutation = shape(st.permutations(dims))

    helpers.test_frontend_function(
        input_dtypes=dtype,
        test_flags=test_flags,
        fn_name=fn_name,
        x=value[0],
        axes=permutation,
        out=dtype,
        copy=None
    )

2023-07-10 12:07 UTC, PerfectionistAF commented
> # permuted test
> ### commit from closed test PR
> ### (path: ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions)
> ```
> @handle_frontend_test(
>     fn_tree="ivy.functional.frontends.numpy.random.functions.permuted",
>     dtype_value=helpers.dtype_and_values(
>         available_dtypes=helpers.get_dtypes("valid", full=True),
>         shape=st.shared(helpers.get_shape(min_num_dims=1), key="value_shape")
>     ),
> )
> ```
> 
> ```
> def test_permuted(
>     *,
>     dtype_value,
>     permutation,
>     x,
>     out,
>     copy,
>     test_flags,
>     fn_name,
> ):
> ```
> 
> ```
>     dtype, value = dtype_value
>     shape = dtype_value.shape
>     dims = [x for x in range(len(shape))]
>     permutation = shape(st.permutations(dims))
>     helpers.test_frontend_function(
>         input_dtypes=dtype,
>         test_flags=test_flags,
>         fn_name=fn_name,
>         x=value[0],
>         axes=permutation,
>         out=dtype,
>         copy=None
>     )
> ```

@PerfectionistAF
Thank you for your contributions, may I ask if you could link the relevant issue this PR is associated with? That way I can provide more structured help.

Also, please could you also comment "add_frontend_checklist" (no quotation marks). A bot should automatically edit your message to include the relevant checklist that you can also edit! 😄

2023-07-10 12:09 UTC, PerfectionistAF commented
add_frontend_checklist

2023-07-20 15:36 UTC, zhumakhan requested changes

2023-07-20 15:36 UTC, zhumakhan commented on ivy/functional/frontends/numpy/random/functions.py
> +    if out != x:  #when out is not x or is None, shuffle in the result
`out`'s should not be checked against anything. If out is not None, just need to store result in out and return it

2023-07-20 15:36 UTC, zhumakhan commented
Hi, could you please add tests for it?

2023-07-21 01:55 UTC, PerfectionistAF commented
The test is pasted above as a comment since some issues occurred with me while committing twice to the same PR

> # permuted test
> ### commit from closed test PR
> ### (path: ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions)
> ```
> @handle_frontend_test(
>     fn_tree="ivy.functional.frontends.numpy.random.functions.permuted",
>     dtype_value=helpers.dtype_and_values(
>         available_dtypes=helpers.get_dtypes("valid", full=True),
>         shape=st.shared(helpers.get_shape(min_num_dims=1), key="value_shape")
>     ),
> )
> ```
> 
> ```
> def test_permuted(
>     *,
>     dtype_value,
>     permutation,
>     x,
>     out,
>     copy,
>     test_flags,
>     fn_name,
> ):
> ```
> 
> ```
>     dtype, value = dtype_value
>     shape = dtype_value.shape
>     dims = [x for x in range(len(shape))]
>     permutation = shape(st.permutations(dims))
>     helpers.test_frontend_function(
>         input_dtypes=dtype,
>         test_flags=test_flags,
>         fn_name=fn_name,
>         x=value[0],
>         axes=permutation,
>         out=dtype,
>         copy=None
>     )
> ```

2023-08-11 15:05 UTC, zhumakhan requested changes

2023-08-11 15:05 UTC, zhumakhan commented on ivy/functional/frontends/numpy/random/functions.py
> +def permuted(x, axes=None, out=None):#, copy=None):
It seems this function is not implemented properly. Could you please fix it?

2023-08-19 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-09-26 05:53 UTC, closed without merging

2023-09-26 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.