Implemented jax.numpy.imag
unifyai/ivy pull request #18227
Opened 2023-07-03 11:53 UTC by moezAhmad

close #18226

2023-07-06 11:15 UTC, hello-fri-end requested changes
Hey @moezAhmad ! Thanks for opening this PR. The ToDo list you have linked in the issue actually contains functions that should be added as instance methods for the JAX frontend in `ivy/functional/frontends/jax/devicearray.py`. You can take a look at other functions inside this file to understand how to implement an instance method. Note that, you need to write the test inside `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_devicearray.py`. Again take a look at other tests in this file incase you're stuck. 

Feel free to request another review when you are done with the changes. Thanks

2023-07-06 19:12 UTC, moezAhmad commented
@hello-fri-end Thank you for reviewing my pr. I have added instance method for jax fronted as you requested However, my tests are failing locally, giving me the same error for every test "TypeError: 'ArrayImpl' object is not callable". I would appreciate any help in this regard

2023-07-08 08:45 UTC, moezAhmad commented
@hello-fri-end I made a mistake by getting math functions and instance methods confused. There's a math function called jax.numpy.imag that wasn't implemented before, due to which I have created a new issue for this according to the doc instruction linked here #20978. I also want to implement imag instance method. I'm ready to start when you can help me.

2023-07-11 04:12 UTC, hello-fri-end commented
> @hello-fri-end I made a mistake by getting math functions and instance methods confused. There's a math function called jax.numpy.imag that wasn't implemented before, due to which I have created a new issue for this according to the doc instruction linked here #18981 . I also want to implement imag instance method. I'm ready to start when you can help me.

Hey @moezAhmad ! Thanks for taking the initiative of adding the `imag` functions to the frontends. Now, you can just merge with the master branch here as `imag` as already merged into master. Let me know if you face any issues while doing so :rocket:

2023-07-11 11:20 UTC, moezAhmad commented
@hello-fri-end I have merged master as you requested

2023-07-12 08:07 UTC, hello-fri-end requested changes
The tests for `test_jax_devicearray_imag` are failing on the CI, can you please take a look?

2023-07-22 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-22 22:25 UTC, moezAhmad commented
@hello-fri-end 
I'm sorry for the delayed response. I've inspected the tests on my end, but I am unable to pinpoint the issue causing the tests for test_jax_devicearray_imag to fail. The specific error I'm encountering is "TypeError: 'ArrayImpl' object is not callable". At this point, I'm unsure of the best way to resolve this. I would greatly appreciate any assistance you can provide in this matter.

2023-07-25 10:43 UTC, hello-fri-end requested changes

2023-07-25 10:43 UTC, hello-fri-end commented on ivy/functional/frontends/jax/devicearray.py
> +        return jax_frontend.numpy.imag(self._ivy_array)
```suggestion
        return jax_frontend.numpy.imag(self)
```

I think this should fix your test :)

2023-07-26 02:36 UTC, hello-fri-end requested changes

2023-07-26 02:36 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py
> +        available_dtypes=helpers.get_dtypes("real_and_complex"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid),
```

Valid automatically determines the supported data-types for the function.

2023-07-26 02:36 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py
> +        on_device=on_device,
`backend_to_test = backend_fw`

Can you add this line to the to the `test_frontend_method`? This has been added in a refactor, the test_frontend_function and the test_frontend_function both has this argument now.

2023-08-12 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-19 05:53 UTC, closed without merging

2023-08-19 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.