ENH: Add softplus to paddle frontend
unifyai/ivy pull request #18286
Opened 2023-07-04 12:21 UTC by aadya940

Closes  #15949

2023-07-04 12:40 UTC, aadya940 commented
Can anyone let me know why the tests are failing?

2023-07-07 09:08 UTC, aadya940 commented
@Sam-Armstrong

2023-07-07 09:21 UTC, Sam-Armstrong commented
Sorry, I've been really busy - will review over the weekend :)

2023-07-09 00:22 UTC, Sam-Armstrong requested changes
@aadya940 thanks for making the PR! I've made a couple of comments with small things to change (the second comment fixes the tests), but otherwise this looks really good. We should be good to merge once you've made these changes 😁

2023-07-09 00:22 UTC, Sam-Armstrong commented on ivy/functional/frontends/paddle/nn/functional/activation.py
> +
we need two lines of whitespace between functions, not one

2023-07-09 00:22 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
> +    ),
```suggestion
    dtype_and_input=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("valid"),
        min_num_dims=1,
    ),
```

2023-07-09 09:19 UTC, aadya940 commented
Thank you @Sam-Armstrong :-)

2023-07-10 13:25 UTC, Sam-Armstrong approved these changes
lgtm! thanks @aadya940

2023-07-10 13:25 UTC, merged