added lgamma to tensorflow frontend, backend implementation missing
unifyai/ivy pull request #18292
Opened 2023-07-04 14:07 UTC by marccgrau

Close #18234

2023-07-06 11:21 UTC, hello-fri-end requested changes
Thanks for the PR! Just requested some changes. Please feel free to request another review when you are done :)

2023-07-06 11:21 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +        available_dtypes=helpers.get_dtypes("float"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```
`valid` should be able to return all the supported dtypes for the function.

2023-07-06 11:27 UTC, hello-fri-end commented
Hey @marccgrau! Looks like we don't have an `ivy.lgamma` function yet. In this case, you can implement it as a composition of other functions in the frontend unless the implementation takes more than a few lines in which case you should first implement the `lgamma` function in the functional API. Take a look at https://unify.ai/docs/ivy/overview/contributing/open_tasks.html for more details. Thanks :)

2023-07-08 11:14 UTC, marccgrau commented
Hi @hello-fri-end 
Thanks for the review! I think a compositional implementation is not feasible as the gamma function is missing in ivy.
I opened a new issue (#18985) to add `ivy.lgamma` to the functional API. Several implementations in the native backends are available.

pending #18985

2023-07-11 04:05 UTC, hello-fri-end commented
> Hi @hello-fri-end Thanks for the review! I think a compositional implementation is not feasible as the gamma function is missing in ivy. I opened a new issue (#18985) to add `ivy.lgamma` to the functional API. Several implementations in the native backends are available.
> 
> pending #18985

Sounds good @marccgrau ! Thanks for taking the initiative of adding `lgamma` to the functional API :rocket:

2023-07-19 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-19 06:51 UTC, marccgrau commented
Hi @hello-fri-end, `ivy.lgamma` is now included in the backend (#19152). Thus, I assume the frontend function could now be included.

2023-07-20 05:16 UTC, hello-fri-end commented
> Hi @hello-fri-end, `ivy.lgamma` is now included in the backend (#19152). Thus, I assume the frontend function could now be included.

Awesome! Again, thanks for taking the initiative of adding it in ivy :rocket: 

Would you please sync this PR with master so that the changes are reflected here as well?

2023-07-29 05:53 UTC, closed without merging

2023-07-29 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.