Logit to paddle tensor.py
unifyai/ivy pull request #18307
Opened 2023-07-04 20:19 UTC by AkshayVenkataraman

2023-07-04 20:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-21 14:54 UTC, kurshakuz requested changes
Hey! Your implementation is not working currently, so please fix them before next review, thanks!

2023-07-21 14:54 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
> +@handle_frontend_method(
`handle_frontend_method` is not defined

2023-07-21 14:54 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_tensor.py
> +    class_tree=CLASS_TREE,
`CLASS_TREE` is not defined

2023-12-23 19:13 UTC, closed without merging