tril_indices
unifyai/ivy pull request #18365
Opened 2023-07-05 19:07 UTC by Sarvesh-Kesharwani

Corresponding to #18040
Closes #18039

2023-07-08 09:05 UTC, hmahmood24 requested changes

2023-07-08 09:05 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_paddle_creation.py
> +    ),
No need to keep this here since you are not using `x` anywhere as you're generating the inputs `col`, `row` and `offset` explicitly

2023-07-24 12:33 UTC, abdulasiraj requested changes
same error here. be careful, i think you're using some wrong function as base. please try to debug and talk to mahmod ashraf if error persists.

2023-07-26 04:50 UTC, Sarvesh-Kesharwani commented
> same error here. be careful, i think you're using some wrong function as base. please try to debug and talk to mahmod ashraf if error persists.

Actually the there is new parameter introduced in the test function ie, backend_to_test, which i have to add in all of my old PRs.

2023-07-28 11:48 UTC, merged