matrix_rank
unifyai/ivy pull request #1847
Opened 2022-07-10 05:07 UTC by hyeonukim

Updated Functional Examples

2022-07-11 10:26 UTC, rush2406 commented
Hi @hyeonukim
Thanks for your work! However, there are a few things to be done:
- Can you please reference the issue linked to this PR? [issue](https://github.com/unifyai/ivy/issues/1649)
- Add an example using ivy.Container in [file](https://github.com/unifyai/ivy/blob/master/ivy/functional/ivy/linear_algebra.py)
- Add an example for the array instance method [here](https://github.com/unifyai/ivy/blob/master/ivy/array/linear_algebra.py#L90) 
- Implement the static method and container method for `matrix_rank`. Also add examples for both these methods. For reference, you can check [https://github.com/unifyai/ivy/blob/master/ivy/container/linear_algebra.py#L99](here)

Let me know if there are any further questions!

2022-07-12 01:52 UTC, hyeonukim commented
Hello @rush2406 

Thank you for such a fast review on my PR!

I had few questions regarding your reply:

1. I wanted to refer to the link that you have but it seems like the link you have given is not working right now. Is it possible to get a link for implementing the static method and container method for my functionality again?

2. Is there a way to manually reference the issue linking to this PR? I have tried to edit my issues using the tab on right side but it seems like I have no authorization

Thanks again for the review!

2022-07-12 03:56 UTC, rush2406 commented
Hi @hyeonukim 
1. Sorry, the updated link is [here](https://github.com/unifyai/ivy/blob/e45803551012432404ef864980ef8c6490dc1f77/ivy/container/linear_algebra.py#L43). You can follow the changes done for `cholesky` function
2. #1649 , okay I have referenced it here

2022-07-20 06:28 UTC, rush2406 requested changes
Hi @hyeonukim 
Can you please include the container static and instance examples as explained?

2022-07-20 09:21 UTC, rush2406 requested changes
Hi @hyeonukim 
can you please complete docstrings as mentioned in the comments and then re-request review when done

2022-07-20 09:21 UTC, rush2406 commented on ivy/array/linear_algebra.py
> +
Hi @hyeonukim 
Can you add the parameters and return docstrings as well to complete this PR? You can follow [this](https://github.com/unifyai/ivy/blob/f6738a28ca5d997f70ef6a8e4be7d367d35bf32b/ivy/array/linear_algebra.py#L31)

2022-07-20 09:21 UTC, rush2406 commented on ivy/container/linear_algebra.py
> +
same here, please add the parameters and return docstrings, [example](https://github.com/unifyai/ivy/blob/f6738a28ca5d997f70ef6a8e4be7d367d35bf32b/ivy/container/linear_algebra.py#L59)

2022-07-20 09:21 UTC, rush2406 commented on ivy/container/linear_algebra.py
> +
same here, please add the parameters and return docstrings, [example](https://github.com/unifyai/ivy/blob/f6738a28ca5d997f70ef6a8e4be7d367d35bf32b/ivy/container/linear_algebra.py#L147)

2022-07-26 20:05 UTC, hyeonukim commented
Hello, @rush2406

I have edited all the things you have requested for could you check it over again?

Thank you!

2022-07-27 11:57 UTC, rush2406 requested changes
Hi @hyeonukim 
Looks great! thanks for the changes. There's a change required in the container file, see the comment below!  Also
1. Can you please pull the master changes because there are conflicts now.
2. The `lint` and `numy-docstring` tests are failing. These are just formatting issues related to spaces, new lines etc. Please fix them as well.
Please request a review once done!

2022-07-27 11:57 UTC, rush2406 commented on ivy/container/linear_algebra.py
> +        return self.matrix_rank(
This should be `self.static_matrix_rank`, which is currently causing the docstrings tests to fail

2022-07-28 06:49 UTC, rush2406 commented
@hyeonukim you need not do formatting for `cholesky`, can you please restore the blank lines you've removed, it's causing the `numpy-docstrings` to fail. Remaining looks good, please request a review once done and it's ready to merge!

2022-07-28 17:37 UTC, hyeonukim commented
Hi @rush2406 
I do not know how that happened with cholesky functions as I did not touch them, sorry about that.
I did fix all the issues could you do a final review?
Thanks!

2022-07-28 18:48 UTC, merged

2022-07-28 18:49 UTC, rush2406 commented
@hyeonukim thanks for the changes! I have merged the PR.