`elementwise` fix up
unifyai/ivy pull request #1854
Opened 2022-07-11 06:45 UTC by rush2406

2022-07-12 09:37 UTC, rush2406 commented
@VedPatwardhan are all of the elementwise functions required to be added into `array/__init__.py`?

2022-07-16 07:29 UTC, djl11 requested changes
see comments :)

2022-07-16 07:29 UTC, djl11 commented on ivy/array/elementwise.py
> +# for review
could you please add the `ivy.Array instance method variant of ivy.<>....` docstrings for all instance methods? Could you please also add all parameters into the docstrings, as explained [here](https://github.com/unifyai/ivy/blob/d8f8fe6986145051e50816fe7bea33e92d997a86/docs/partial_source/deep_dive/11_docstrings.rst#docstrings)?

2022-07-16 07:29 UTC, djl11 commented on ivy/container/elementwise.py
> +# for review
could you please add the `ivy.Array instance method variant of ivy.<>....` docstrings for all instance methods? Could you please also add all parameters into the docstrings, as explained [here](https://github.com/unifyai/ivy/blob/d8f8fe6986145051e50816fe7bea33e92d997a86/docs/partial_source/deep_dive/11_docstrings.rst#docstrings)?

2022-07-18 16:56 UTC, merged