fix paddle.mean method
unifyai/ivy pull request #18627
Opened 2023-07-06 15:49 UTC by Mghrabi

Tests were not passing, so I fixed that by:
* Returning the proper shape
* corrected the supported data types according to docs [here](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/mean_en.html#mean)

2023-07-06 16:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-07 01:41 UTC, Daniel4078 approved these changes
Looks good to me! Thanks

2023-07-07 01:43 UTC, Daniel4078 requested changes
Thanks for your contribution, but please note that your implementation can only be correct in the 2.5.0 version of paddle, not any one before. So you need to consider version-specific fixes. https://discord.com/channels/799879767196958751/1028707571743334420/1126633818057617558

2023-07-30 19:05 UTC, V-G-spec commented
Seeing no update in a month, I'm closing this

2023-07-30 19:05 UTC, closed without merging