Add sigmoid activation to Paddle frontend and test
unifyai/ivy pull request #18926
Opened 2023-07-06 22:19 UTC by peterwisu

Close #18312

2023-07-12 07:41 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
> +        available_dtypes=helpers.get_dtypes("float"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```

2023-07-12 07:42 UTC, hello-fri-end requested changes
Hey @peterwisu ! Thanks for opening this PR. Requested a minor change and after that, we are good to merge. Feel free to request another review when you are done with the changes.

2023-07-12 07:44 UTC, peterwisu commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_activation.py
> +        available_dtypes=helpers.get_dtypes("float"),
sure will do it.

2023-07-12 11:17 UTC, peterwisu commented
@hello-fri-end Hi thank you for the code review, I have modified a code as you suggest. Thank you

2023-07-14 04:04 UTC, hello-fri-end commented
> @hello-fri-end Hi thank you for the code review, I have modified a code as you suggest. Thank you

Hey @peterwisu ! Thanks for making the changes. Could you please resolve the merge conflicts?

2023-07-14 04:13 UTC, closed without merging

2023-07-14 04:46 UTC, peterwisu commented
Close this PR (cannot reopen PR) new PR for this tasks https://github.com/unifyai/ivy/pull/19394