added lu factor to torch frontend and tested
unifyai/ivy pull request #18969
Opened 2023-07-07 19:48 UTC by Rakshith-611

2023-07-21 14:58 UTC, kurshakuz requested changes
Hello! Thank you for your contribution! Can you please resolve the issue?

2023-07-21 14:58 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py
> +    fn_tree="torch.linalg.lu_factor", input_dtype_and_input=_lu_factor_helper()
`_lu_factor_helper()` is not defined

2023-08-04 04:43 UTC, kurshakuz requested changes
Hey! Your implemenation is failing due to following error now:
```
E       NameError: name 'input_dtype' is not defined
```

2023-12-23 19:18 UTC, NripeshN commented
The code

2023-12-23 19:18 UTC, closed without merging