Added mathematical function jax.numpy.imag
unifyai/ivy pull request #18982
Opened 2023-07-08 08:34 UTC by moezAhmad

close #18226

2023-07-08 09:27 UTC, hmahmood24 requested changes
Hey @moezAhmad, requested some changes for you to look into. Do request a re-review once done. Thanks! :)

2023-07-08 09:27 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy/test_math.py
> +        input=x[0],
The `input` here should instead be `val`

2023-07-08 09:27 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy/test_math.py
> +        atol=1e-2,
Are the tests not passing with a low tolerance value? Somewhere around `1e-4`? `1e-2` seems to be too high of a tolerance value

2023-07-08 09:27 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy/test_math.py
> +
Pretty sure these are lint/formatting issues. Can you kindly resolve these? :) We recommend using `pre-commit` to automatically format your PRs every time you commit. Thanks

2023-07-08 11:04 UTC, moezAhmad commented
@hmahmood24 Thank you for reviewing my pr. I have implemented changes as you requested.

2023-07-09 16:19 UTC, hmahmood24 approved these changes
Everything seems good to merge now. Thanks @moezAhmad! 🚀

2023-07-09 16:20 UTC, merged