SquaredDifference function for TensorFlow RawOps  frontend
unifyai/ivy pull request #19002
Opened 2023-07-08 16:35 UTC by Romiest

Close #18994

2023-07-08 17:49 UTC, Romiest commented
I have removed the changes made in the `.idea` folder

2023-07-17 20:47 UTC, kgmann commented
Hey @Romiest, thanks for your contribution. Can you please address these
- IDE configuration files in the `.idea` folder are still present, please remove them 
- `int32` and `int64` are also part of the supported dtypes 
- The function `_squared_difference_helper` seems unnecessary, you can use `helpers.dtype_and_values` directly

2023-07-18 01:05 UTC, Romiest commented
> Hey @Romiest, thanks for your contribution. Can you please address these
> 
> * IDE configuration files in the `.idea` folder are still present, please remove them
> * `int32` and `int64` are also part of the supported dtypes
> * The function `_squared_difference_helper` seems unnecessary, you can use `helpers.dtype_and_values` directly

Thanks for your response @kgmann ! I addressed everything you mentioned but I think there is something wrong with `_template__of_py_test.xml` as there are no differences between my file and the origin one. If there is anything else I should adjust or modify let me know 👍🏻

2023-07-18 14:38 UTC, kgmann commented
ivy-gardener

2023-07-18 14:54 UTC, Romiest commented
> ivy-gardener ✅ Ivy gardener has formatted your code. If changes are requested, don't forget to pull your fork.

Thanks, @kgmann , any other modifications?

2023-07-19 13:18 UTC, Romiest commented
@kgmann

2023-07-24 16:14 UTC, Romiest commented
Would appreciate if I can get a reply. Thank you. @kgmann

2023-07-24 17:12 UTC, kgmann requested changes
Hey @Romiest, sorry for the confusion in my previous comment. I made the review and actually forgot to submit it 😅

2023-07-26 10:17 UTC, kgmann commented
ivy-gardener

2023-07-26 10:50 UTC, kgmann requested changes

2023-07-26 10:50 UTC, kgmann commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +            "2.12.0 and below": (
Please change the version to `2.13.0 and below` else the tests will fail.

2023-07-26 10:59 UTC, kgmann commented
Hey @Romiest , the code looks good to me (apart from the tf version to be changed to `2.13.0`) but the test for the implemented function is failing for some backends. 
You can run it locally with this command
 `pytest ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py::test_tensorflow_SquaredDifference`
Can you debug to find out why ? Please let me know how it's going. Thanks

2023-07-27 23:45 UTC, kgmann commented
lgtm 👍🏿

2023-07-27 23:46 UTC, merged