add bernoulli to paddle backend
unifyai/ivy pull request #19089
Opened 2023-07-09 19:58 UTC by mohame54

close #19078

2023-07-09 21:36 UTC, mohame54 commented
I am ready for the review @MuhammadSaeedBatikh

2023-07-14 08:34 UTC, mohame54 commented
I am ready for the review @MahmoudAshraf97

2023-07-16 16:21 UTC, MahmoudAshraf97 requested changes
please use `paddle.bernoulli` directly, don't create a distribution and sample from it
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/bernoulli_en.html#bernoulli

2023-07-17 08:07 UTC, mohame54 commented
> please use `paddle.bernoulli` directly, don't create a distribution and sample from it https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/bernoulli_en.html#bernoulli

Okay on it

2023-08-06 13:47 UTC, MahmoudAshraf97 approved these changes

2023-08-06 13:47 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/random.py
> +)
```suggestion
@with_supported_device_and_dtypes(
    {
        "2.5.0 and above": {
            "cpu": ("float32", "float64"),
            "gpu": ("bfloat16", "float16", "float32", "float64"),
        },
        "2.4.2 and below": {
            "cpu": (
                "float32",
                "float64",
            ),
            "gpu": ("float16", "float32", "float64"),
        },
    },
    backend_version,
)
```

2023-08-06 13:48 UTC, MahmoudAshraf97 commented
ivy-gardener

2023-08-06 13:50 UTC, merged