Added square_error_cost
unifyai/ivy pull request #19109
Opened 2023-07-10 03:18 UTC by m-gopichand

Close #17425

2023-07-11 05:43 UTC, mobley-trent commented
Hey @m-gopichand 👋

2023-07-12 16:22 UTC, mobley-trent commented on ivy/functional/frontends/paddle/nn/functional/loss.py
> +@with_supported_dtypes({"2.4.2 and below": ("float32", "float64")}, "paddle")
Latest paddle version is `2.5.0`

2023-07-12 16:24 UTC, mobley-trent commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_loss.py
> +        target=target,
The function doesn't have `pred` or `target` as inputs. Simple reformat to:

```
input=pred
label=target
```

2023-07-12 16:25 UTC, mobley-trent commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_loss.py
> +    reduction=st.sampled_from(["none", "sum", "mean"]),
This function doesn't have a reduction argument.

2023-07-12 16:27 UTC, mobley-trent requested changes

2023-07-12 16:27 UTC, mobley-trent commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_paddle_loss.py
> +        input_dtypes=[input_dtype, target_dtype],
Only one input dtype is necessary, choose any one of the two.

2023-07-12 16:29 UTC, mobley-trent commented
Hey @m-gopichand I've left a few pointers for you to improve this PR

2023-07-28 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-12 18:25 UTC, closed without merging