ivy.lgamma
unifyai/ivy pull request #19177
Opened 2023-07-10 13:00 UTC by marccgrau

Close #19152

2023-07-17 19:22 UTC, marccgrau commented on ivy/functional/ivy/experimental/elementwise.py
> +@integer_arrays_to_float
Apparently the decorator has been removed six days ago in #19205. So no need to include it anymore.

2023-07-18 06:40 UTC, sherry30 requested changes
Requested a few changes.

Can you add unsypported dtypes accordingly.
I think paddle doesn't support `float16` the rest you can test and find out.

Thanks

2023-07-18 06:40 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_elementwise.py
> +    ground_truth_backend,
You can remove this argument

2023-07-18 06:40 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_elementwise.py
> +        ground_truth_backend=ground_truth_backend,
remove this as well

2023-07-18 06:40 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_elementwise.py
> +        available_dtypes=helpers.get_dtypes("valid"),
use `"float"` instead of `"valid"` as dtypes

2023-07-19 05:57 UTC, sherry30 approved these changes
lgtm!
Thanks for the changes.

2023-07-19 05:58 UTC, merged