Update statistical var #912
unifyai/ivy pull request #1918
Opened 2022-07-13 16:50 UTC by sp1103

I modified the doc string for the var function in statistical. Looking at the function I did not see anything that needed reformatting. This is just a refactor of the doc string to add examples.

2022-07-15 10:28 UTC, sherry30 requested changes
Hi,

I've requested a few changes on each specific line. The rest looks good, I'll merge as soon as you make these changes 😃 

Thanks

2022-07-15 10:28 UTC, sherry30 commented on ivy/container/statistical.py
> +        >>> x = ivy.Container(a=ivy.array([0.1, 0.2, 0.9]), b=ivy.array([0.7, 0.1, 0.9]))
put array `b` on a new line using `\` separator

2022-07-15 10:28 UTC, sherry30 commented on ivy/container/statistical.py
> +    def static_var(
add `@staticmethod` above this

2022-07-15 10:28 UTC, sherry30 commented on ivy/container/statistical.py
> +        >>> x = ivy.Container(a=ivy.array([0.1, 0.2, 0.9]), b=ivy.array([0.7, 0.1, 0.9]))
put `b` on a new line using `\` separator

2022-07-18 08:53 UTC, sherry30 requested changes
Hi,

just requested some minor changes,

Thanks

2022-07-18 08:53 UTC, sherry30 commented on ivy/array/statistical.py
> +         >>> y = ivy.var(x)
you're supposed to add an instance method example here
`y = x.var()`

2022-07-18 08:53 UTC, sherry30 commented on ivy/container/statistical.py
> +             b=ivy.array([0.7, 0.1, 0.9]))
indent b exactly under a

2022-07-18 08:53 UTC, sherry30 commented on ivy/container/statistical.py
> +             b=ivy.array([0.7, 0.1, 0.9]))
indent b exactly under a

2022-07-21 16:14 UTC, sp1103 commented
Hi Sherry, 
I just noticed my pull request has not been merged. Is there anything else you need me to do.

2022-07-21 19:49 UTC, sherry30 requested changes
Hi,

sorry this PR flew under my radar, you can request a review once you're done making changes, that will let me know its ready to be reviewed.

It seems like there are some lint errors in this file, can you fix those. Also test docstrings are failing, can you look into those and try to fix the errors.

If you have trouble fixing those then you can ask question, I'd be happy to help.
Thanks.

2022-07-22 17:27 UTC, sp1103 commented
Hey Sherry, 
I am trying to fix the lint errors but I keep getting E251 unexpected spaces around keyword / parameter equals. Also I was wondering if there was anything else I needed to do after I fix the lint error.

2022-07-25 07:46 UTC, sherry30 requested changes
Hi,
i pointed out a lint error, other than that, a line cannot be greater than 88 characters.

You also have to look at the docstring error and figure out why it is failing. Try to fix it or let me know if you are having trouble figuring it out.
Let me know if i can help you out with any other problem.

Thanks

2022-07-25 07:46 UTC, sherry30 commented on ivy/container/statistical.py
> +        >>> x = ivy.Container(a=ivy.array([0.1, 0.2, 0.9]),\
write this as:
`x = ivy.Container(a=ivy.array([0.1, 0.2, 0.9]), \`
there should be space before and after the `\` separator.

2022-07-25 21:27 UTC, sp1103 commented
ivy_tests/test_ivy/test_functional/test_core/test_linalg.py:1280:9: E999 SyntaxError: keyword argument repeated

I keep getting this error for the linting other than that as far as I can tell everything should be in order.

2022-07-26 02:25 UTC, sherry30 requested changes
I pointed out the extra line in your commit, can you remove that, I think you accidentally added it or maybe it got added while solving merge conflicts.

Also can you remove changes to the Docker file GPU as well. It shouldn't be in your commit.

Other than that, the docstring test for `var` is failing, the output on run seems to be a bit different from the output written in docs.

2022-07-26 02:25 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_core/test_linalg.py
> +        x=np.random.uniform(size=(a, b)).astype(input_dtype[0]),
This line is extra

2022-07-26 02:25 UTC, sherry30 commented on DockerfileGPU
> +RUN pip3 install torch==1.11.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
Can you remove changes to this file in the commit

2022-07-27 03:30 UTC, sherry30 requested changes
Hi,

Can you add 1 functional example using container as an input in `ivy/functional/ivy/statistical.py` and also 1 functional example using native array as input.
Some extra changes which i pointed out need to be removed which i think you accidentally pushed. 
Other than that it all looks good 😃

2022-07-27 03:30 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_core/test_linalg.py
> +    )
remove change from this file

2022-07-27 03:30 UTC, sherry30 commented on ivy/functional/ivy/statistical.py
> -
remove change in this function

2022-07-28 17:28 UTC, sp1103 commented
Is it okay if we close this out

2022-07-29 05:34 UTC, merged

2022-07-29 05:35 UTC, sherry30 approved these changes
I've merged your PR, Thank you for the contribution 😄 
The PR will close automatically