Take
unifyai/ivy pull request #19212
Opened 2023-07-11 09:16 UTC by MuhammadNizamani

Closed  #19210

2023-07-12 21:20 UTC, V-G-spec commented
Hey @MuhammadNizamani, thanks for your contribution! However, I see branch conflict with your PR. Do you mind taking a look?

2023-07-13 08:00 UTC, MuhammadNizamani commented
@V-G-spec sure

2023-07-24 06:20 UTC, V-G-spec commented
@MuhammadNizamani thanks for resolving the conflicts. Can you take a look at the failing tests next?

2023-07-24 06:24 UTC, MuhammadNizamani commented
@V-G-spec it is passing all tests locally.

2023-07-30 19:10 UTC, V-G-spec commented
Can you go through the logs for failing tests, then? And also share a screenshot of the tests passing locally

2023-07-31 04:53 UTC, MuhammadNizamani commented
> Can you go through the logs for failing tests, then? And also share a screenshot of the tests passing locally

sure

2023-07-31 06:37 UTC, MuhammadNizamani commented
@V-G-spec  There is issue in method name  `test_jax_round`  in test-pr 20 and i have gone through all failed tests log and any of the error was not releteded to my changes. 
and in following screenshot 
![take function test](https://github.com/unifyai/ivy/assets/49721249/1edaa73d-1eb5-4038-8314-d87c99d58e94)

2023-07-31 17:55 UTC, V-G-spec commented
I can see errors in PR test 1 as well. 
```
ERROR: not found: /ivy/ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py::test_jax_devicearray_take
(no name '/ivy/ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py::test_jax_devicearray_take' in any of [<Module test_devicearray.py>])
```

2023-07-31 18:05 UTC, MuhammadNizamani commented
@V-G-spec can you tell me could be the error that I can resolve because it is passing all tests.

2023-07-31 19:13 UTC, V-G-spec commented
I'm not quite sure myself. If you go through the logs, you'll find some more details. It was something I have come across for the first time. Lmk if you can't figure it out. I'll raise it internally

2023-08-02 18:50 UTC, V-G-spec commented
Btw, you can also ask kapa on Discord to help with the error

2023-08-11 15:42 UTC, zhumakhan commented on ivy/functional/frontends/jax/array.py
> +        return jax_frontend.numpy.take(self, indices, axis=axis, out=out)
Could please also handle `mode` argument in here

2023-08-11 15:44 UTC, zhumakhan requested changes

2023-08-11 15:44 UTC, zhumakhan commented on ivy/functional/frontends/jax/array.py
> +        return jax_frontend.numpy.take(self, indices, axis=axis, out=out)
Rest seems good!

2023-08-12 11:25 UTC, MuhammadNizamani commented
@zhumakhan  Sir mode = None in the JAX documantion and the I am using `jax_frontend.numpy.take` .

2023-08-13 16:41 UTC, zhumakhan commented
jax_frontend.numpy.takes seems to have mode argument: https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/jax/numpy/manipulations.py#L111

2023-09-03 19:35 UTC, zhumakhan requested changes

2023-09-03 19:35 UTC, zhumakhan commented on ivy/functional/frontends/jax/array.py
> +        return jax_frontend.numpy.take(self, indices, axis=axis, out=out)
Please call `jax_frontend.numpy.take` with `mode` argument. E.g.: `jax_frontend.numpy.take(self, indices, axis=axis, out=out, mode=mode)`

2023-09-08 07:24 UTC, MuhammadNizamani commented
@zhumakhan  review this please

2023-12-14 13:31 UTC, closed without merging