Added LogSoftmax to raw_ops
unifyai/ivy pull request #19217
Opened 2023-07-11 10:04 UTC by DrZuse

Close #19216

2023-07-11 16:15 UTC, AnnaTz requested changes

2023-07-11 16:15 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +        available_dtypes=helpers.get_dtypes("float"),
Please use `helpers.get_dtypes("valid")` here and add a `with_supported_dtypes` decorator to the function. 
Other than that, looks good!

2023-07-12 10:01 UTC, DrZuse commented
Thank you for the detailed review. I have addressed all the mentioned nuances, please check them

2023-07-13 08:31 UTC, AnnaTz approved these changes
Thanks for the changes, looks good!

2023-07-13 08:31 UTC, merged