Adding STFT from ONNX to Ivy Experimental Files
unifyai/ivy pull request #19233
Opened 2023-07-11 12:11 UTC by KevinUnadkat

2023-07-12 04:59 UTC, vedpatwardhan commented
Hey @KevinUnadkat, just looked through the PR, the problem with the `jax` backend is with the `axis` argument, for which we've added the default value as `None`, but `jax.scipy.signal.stft` has a default value of `-1`. Basically you'd need to infer the `axis` from the `signal` and other relevant arguments of the `ivy` function and pass that inferred `axis` to `jax.scipy.signal.stft` if `axis` is `None`. 
Also, secondly you could add something like,
```
stft.mixed_backend_wrappers = {
    "to_add": (
        "inputs_to_native_arrays",
        "outputs_to_ivy_arrays",
    ),
    "to_skip": ("inputs_to_ivy_arrays",),
}   
```
instead of `stft.mixed_function=True` which was the old method (more info [here](https://unify.ai/docs/ivy/overview/deep_dive/function_types.html#mixed-functions))
Hope that helps :smile:

2023-07-20 14:10 UTC, zhumakhan commented
Hi @KevinUnadkat, could you please add test for this?

2023-08-13 17:40 UTC, zhumakhan requested changes

2023-08-13 17:40 UTC, zhumakhan commented on ivy/data_classes/array/experimental/layers.py
> +        Compute the discrete Fourier transform of input.
Hey, what is the reason that this description is updated?

2023-08-13 17:40 UTC, zhumakhan commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +def test_stft(
Hey, could you please fix tests: `hypothesis.errors.InvalidArgument: max_value=(2, 2) must be a real number.`

2023-09-03 19:37 UTC, zhumakhan commented
Hey, this PR has been updated a lot since last comments I left. Could you please respond to those comments with how latest changes addressed them?

2023-09-17 10:35 UTC, zhumakhan requested changes

2023-09-17 10:35 UTC, zhumakhan commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +    window = draw(helpers.get_dtypes("float", full=False)))
Parentheses do not match here 2x( and 3x)

2023-11-17 07:58 UTC, vedpatwardhan reviewed
Given that the focus is shifted from adding new functions to fixing and optimizing those used in popular models, I think we should close this PR now as there's already another `stft` function on `main` 😄

2023-12-26 03:47 UTC, vedpatwardhan reviewed
I believe @KevinUnadkat is still working on this, feel free to request a review once you're done with the changes. Thanks @KevinUnadkat 😄

2024-01-12 18:56 UTC, closed without merging

2024-01-12 18:56 UTC, aibenStunner commented
Hi @KevinUnadkat,

Thanks for the PR!

However, it looks like it has been inactive for a while.

Therefore, I’ve simply closed it for now. 🙂

Please feel free to submit other PRs based on our [Open Tasks](https://lets-unify.ai/ivy/overview/contributing/open_tasks.html).

Thanks!