add unstack paddle frontend manipulation
unifyai/ivy pull request #19242
Opened 2023-07-11 14:48 UTC by NripeshN

Close #19235

2023-07-13 14:47 UTC, NripeshN commented
add_frontend_checklist

2023-07-21 07:08 UTC, Aarsh2001 requested changes

2023-07-21 07:08 UTC, Aarsh2001 commented on ivy/functional/frontends/paddle/tensor/manipulation.py
> +    {"2.5.0 and below": ("bool", "float32", "float64", "int32", "int64")},
`bool` is not registered as a dtype for the `_unstack` kernel in the paddle backend, and so if you see the logs you'll see a runtime error. Can you please remove `bool` from the list and run the test again ?

2023-07-31 01:30 UTC, NripeshN commented
Hi @Aarsh2001, Could you please review this PR.

2023-08-18 07:00 UTC, Aarsh2001 approved these changes
My apologies for the delay ! 😅 LGTM !

2023-08-18 07:00 UTC, merged