add roll paddle frontend manipulation
unifyai/ivy pull request #19258
Opened 2023-07-11 16:11 UTC by NripeshN

2023-07-11 16:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-13 14:47 UTC, NripeshN commented
add_frontend_checklist

2023-07-24 07:03 UTC, rishabgit requested changes
Hi, thanks a ton for looking into this! :smile: 
Could you please update the supported [dtypes](https://github.com/PaddlePaddle/Paddle/blob/4f9404a6354f5442f4316c968356dd5aeec69c54/python/paddle/tensor/manipulation.py#L1715)?

Arg name should be `shifts` - https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/roll_en.html

Feel free to re-request a review after making those changes!

2023-07-26 07:48 UTC, rishabgit requested changes
Hey! There was a recent addition of backend_to_test arg in the testing pipeline, which was causing the code to fail tests. I added that, but it's throwing `AttributeError: module 'paddle.fluid.dygraph' has no attribute 'ParamBase'` now. It doesn't look to be due to your code, so I've dropped a note on our [discord](https://discord.com/channels/799879767196958751/1028267758028337193/1133662065974837289) regarding this. :smile: 
Until it's fixed -
- Could you take care of the merge conflicts ?

2023-07-26 07:56 UTC, rishabgit commented
Update: looks like that testing issue was resolved by [this](https://github.com/unifyai/ivy/commit/0ea0f555fc3a989d2d2329c3a62110e7112c9b4c)
Could you please update your branch with latest changes?

2023-07-26 08:17 UTC, NripeshN commented
Hi @rishabgit, I have fixed all merge conflicts

2023-07-27 15:22 UTC, rishabgit requested changes
Hey, your code looks great, but I'm getting an odd `AssertionError: returned shape = (), ground-truth returned shape = (1,)`. 
I've dropped a note to the testing team in case there's something off with ivy's testing pipeline. Could you please look into it in case it's not?

2023-07-31 01:31 UTC, NripeshN commented
Hi @rishabgit, could you please review this PR

2023-07-31 14:48 UTC, rishabgit requested changes
Hey, feel free to re-request review after changes. Thanks! smile

2023-07-31 15:00 UTC, NripeshN commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_manipulation.py
> +    shifts = 1
Hi @rishabgit, I have made the necessary changes!

2023-07-31 15:55 UTC, rishabgit commented
Thanks for the changes, they look great!

2023-07-31 15:55 UTC, merged