Added numpy linear algebra einsum method.
unifyai/ivy pull request #19292
Opened 2023-07-12 04:36 UTC by Ashwani132003

#18930

2023-07-12 05:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-19 19:38 UTC, MuhammedAshraf2020 commented
Hi @Ashwani132003,
Thanks for the PR. There seems to be a few small issues that I pointed out below.

2023-07-19 19:51 UTC, MuhammedAshraf2020 requested changes

2023-07-19 19:51 UTC, MuhammedAshraf2020 commented on ivy/functional/frontends/numpy/linalg/matrix_and_vector_products.py
> +def einsum(
In the frontend functions, it is essential to ensure that the function name and call signature precisely match the corresponding function in the target framework. The original function from the target framework is 
`def einsum(*operands, out=None, optimize=False, **kwargs)` [source](https://github.com/numpy/numpy/blob/v1.25.0/numpy/core/einsumfunc.py#L1010). Please refer to the frontend documentation [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html) for assistance. However, it appears that your call signature differs from the original function.

2023-07-28 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-13 05:53 UTC, closed without merging

2023-08-13 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.