Added numpy.order_statistics.quantile method
unifyai/ivy pull request #19334
Opened 2023-07-13 04:00 UTC by Ashwani132003

Close #19333

2023-07-13 08:16 UTC, Ashwani132003 commented
casting to float64 will needed to be updated at frontends when ivy start supporting higher float precision dtypes .
![image](https://github.com/unifyai/ivy/assets/76273539/d4b6a141-a8b1-4755-8f06-ac6aa5c71a01)

2023-07-16 11:56 UTC, theRealBird commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_order_statistics.py
Any reason why we are taking only the first dimension of the axis in the test?

2023-07-16 11:57 UTC, theRealBird requested changes
Have left a comment for `quantile` at the moment. Thanks!

2023-07-16 11:59 UTC, theRealBird commented
Hi @Ashwani132003,
Thank you for contributing to Ivy! Great work on the PRs! 
I also see that you have implemented `einsum` as a part of this PR? Was this intended?

2023-07-16 12:36 UTC, Ashwani132003 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_order_statistics.py
Hi, I referred it from torch_quantile. I suppose test function is designed to handle only a single-axis case. That's why added this.

2023-07-16 12:40 UTC, Ashwani132003 commented
> Hi @Ashwani132003, Thank you for contributing to Ivy! Great work on the PRs! I also see that you have implemented `einsum` as a part of this PR? Was this intended?

No, actually I am planning to do multiple contributions to this repo, initially I accidentally added commits from master/another branch. But now I learned to create commits from single branch. If there are any conflicts with it, then i can make a new pr if you want? Thanks

2023-07-16 12:49 UTC, Ashwani132003 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_order_statistics.py
![image](https://github.com/unifyai/ivy/assets/76273539/055aca5f-e9d5-46e1-9cbd-9025a761e268)
this is from backend

2023-07-23 13:40 UTC, theRealBird commented
> > Hi @Ashwani132003, Thank you for contributing to Ivy! Great work on the PRs! I also see that you have implemented `einsum` as a part of this PR? Was this intended?
> 
> No, actually I am planning to do multiple contributions to this repo, initially I accidentally added commits from master/another branch. But now I learned to create commits from single branch. If there are any conflicts with it, then i can make a new pr if you want? Thanks

Thanks a lot for investing your time at Ivy and doing multiple contributions. The only problem here is not the conflicts, but the problem of not linking the right issue in the PR description. The way you have linked #19333 should be followed for all the functions you are implementing. In this case, you would also have to create and then link and issue for einsum. I hope this clears it up.

Also, in the future, I would suggest making different PRs for different issues. This helps us quickly review and merge them and work on the implementations independently. Thanks a lot!

2023-08-11 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-20 05:53 UTC, closed without merging