Jax devicearray diagonal
unifyai/ivy pull request #19374
Opened 2023-07-13 15:22 UTC by VictorOdede

Close #15371

2023-07-13 15:28 UTC, VictorOdede commented
@hirwa-nshuti I've fixed the merge conflicts for this branch.

2023-07-13 18:34 UTC, hirwa-nshuti approved these changes
Looks good to me 😊
Going to merge🙂

2023-07-13 18:35 UTC, hirwa-nshuti requested changes
Would you resolve the merge conflicts

2023-07-18 05:42 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py
> +
```suggestion
```

2023-07-18 05:43 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py
> +
```suggestion
```

2023-07-18 05:43 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py
> +
```suggestion
```

2023-07-18 05:43 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py
> +handle_frontend_method(
```suggestion
@handle_frontend_method(
```

2023-07-18 05:47 UTC, merged