trace
unifyai/ivy pull request #19386
Opened 2023-07-13 21:41 UTC by hopedonn

Implemented paddle.tensor.math.trace function and testing

2023-07-13 21:45 UTC, hopedonn commented
Close #19385

2023-07-13 22:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-14 00:04 UTC, hopedonn commented
@MahmoudAshraf97

2023-07-20 13:56 UTC, xoiga123 requested changes
Thank you for contributing to Ivy :hugs: Need some changes here and there, but looking good overall :+1:

2023-07-20 13:56 UTC, xoiga123 commented on ivy/functional/frontends/paddle/tensor/math.py
> +
Please follow the formatting convention of 2 blank lines between function definitions and a newline at end-of-file.

2023-08-02 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-22 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-08-22 05:53 UTC, closed without merging