added all function to frontend.paddle.tensor.math
unifyai/ivy pull request #19392
Opened 2023-07-14 03:36 UTC by nikita-jare

Closes #19391

2023-07-17 06:51 UTC, rishabgit requested changes
Hi @nikita-jare, thanks a ton as usual :smile: 
- Automated Github tests have some issue, so I tried testing this locally by `pytest /workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py::test_paddle_all` but it seems to throw a bunch of errors?
- In the test file you're editing, it looks like you aren't making use of `assume`. Could you please remove that if that's the case?
- Also, could you take care of the [lint](https://github.com/unifyai/ivy/actions/runs/5550208012/jobs/10135089510?pr=19392) issues

2023-07-25 03:48 UTC, nikita-jare commented
Hi @rishabgit,
Please ignore the recent checkins.
Still facing some issues. I will request a review when final changes are pushed.

2023-07-31 15:34 UTC, rishabgit requested changes

2023-07-31 16:01 UTC, nikita-jare commented on ivy/functional/frontends/paddle/tensor/math.py
> +# @with_supported_dtypes({"2.5.0 and below": ("bool")}, "paddle")
Hi @rishabgit, for me with or without the `@with_supported_dtypes({"2.5.0 and below": ("bool")}, "paddle")`, it is running successfully. I tried now both through codespaces as well as locally.

Earlier, with `@with_supported_dtypes` uncommented, it was giving error: `KeyError:cpu`. That's why as per the suggestions from discord channel, I commented and removed it.

Now, as it is running without any errors, should I keep it commented or uncommented?

2023-08-07 10:40 UTC, rishabgit requested changes
Hi, tests are failing for numpy and jax, could you please look into them? Thanks! :smile: 
![image](https://github.com/unifyai/ivy/assets/52187856/c451b53a-5c91-49d5-be3e-53c8e39a1986)

2023-08-08 05:34 UTC, nikita-jare commented
Thank you for the review @rishabgit 
I have synced the branch with upstream, resolved the merge conflicts and ran the implementation again, all tests are passing for me when I run with codespaces. Not sure where the issue is exactly.

<img width="962" alt="Screenshot 2023-08-08 at 10 55 31 AM" src="https://github.com/unifyai/ivy/assets/106905968/a634a446-6821-44ce-abde-dc3bf40b4577">

2023-08-12 15:27 UTC, rishabgit requested changes
Hey, could you please take care of the merge conflicts? Everything lgtm to merge otherwise, thanks!

2023-08-22 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-09-29 05:53 UTC, closed without merging

2023-09-29 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.