Implement Softplus Function and Tests
unifyai/ivy pull request #19390
Opened 2023-07-14 01:18 UTC by BouchanaHicham

Requesting Team Decision on Softplus Functions

- Created my own Softplus functions and corresponding tests
- Similar Softplus functions were found and commented out
- Both implementations have been thoroughly tested and passed successfully

To proceed, the team needs to decide which implementation of Softplus functions to use:
1. The existing commented-out functions
2. My newly created functions

Please review both implementations and provide feedback on which option to proceed with. Additionally, if there are any changes or additions required in either implementation, please specify them for further refinement.

2023-07-14 01:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-14 06:44 UTC, sagewhocodes commented
Hello @BouchanaHicham , Thank you for contributing to ivy!

However as I can see, the `softplus` function you have reimplemented doesn't have the necessary arguments from the original softmax function from Paddle's API [here](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/Softplus_en.html) . 
Since frontend functions are used for transpiling across frameworks, You are required to ensure function signatures of the frontend function are exactly the same. You can refer to Ivy frontends doc [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html)

Happy Contributing 😄

2023-07-14 23:02 UTC, BouchanaHicham commented
Hello, @sagewhocodes!

I would greatly appreciate it if you could review my latest changes. I value your expertise and insights, and I'm eager to hear your thoughts on the direction I should take from here.

Thank you in advance for your time and feedback!

Best regards,

2023-07-17 11:32 UTC, sagewhocodes commented
Hello @BouchanaHicham , there seems to be redundant changes in `test_activation.py` file. Could you please look into it?

2023-07-17 14:39 UTC, BouchanaHicham commented
> Hello @BouchanaHicham , there seems to be redundant changes in `test_activation.py` file. Could you please look into it?

Hello @sagewhocodes ,

Thank you for your feedback. I believe you are referring to the removal of the softplus_test in test_activation.py. Allow me to clarify the rationale behind this change and provide further context.

The previous implementation of the softplus_test had some limitations and inconsistencies. Therefore, I made the decision to remove it and reimplement it to ensure better coverage and accuracy. The updated test now includes the necessary arguments and incorporates improvements to enhance its functionality.

By removing the redundant softplus_test and replacing it with an improved version, i aim to streamline the codebase and maintain consistency throughout the test suite.

I appreciate your attention to detail and your commitment to code quality. If you have any additional questions or concerns, please don't hesitate to let me know.

2023-07-21 06:07 UTC, sagewhocodes requested changes

2023-07-21 06:07 UTC, sagewhocodes commented on ivy/functional/frontends/paddle/nn/functional/activation.py
> +@with_supported_dtypes({"2.5.0 and below": ("float32", "float64")}, "paddle")
Revert the changes in this file, as the implementation is unchanged

2023-07-21 06:07 UTC, sagewhocodes commented
@BouchanaHicham please do the requested changes, rest looks good to me!

2023-07-21 13:44 UTC, BouchanaHicham commented
@sagewhocodes Done

2023-07-21 13:44 UTC, BouchanaHicham commented
> @BouchanaHicham please do the requested changes, rest looks good to me!

Done

2023-07-21 13:53 UTC, sagewhocodes commented
LGTM!

2023-07-21 13:54 UTC, merged