#19402. Added Einsum function to rawops
unifyai/ivy pull request #19405
Opened 2023-07-14 11:23 UTC by janchilling

Close #19402

2023-07-16 07:15 UTC, theRealBird commented
Hi @janchilling, 
Thank you for your contribution to Ivy, any information about the unsupported data-types which needs to be added here?

2023-07-16 07:44 UTC, janchilling commented
> Hi @janchilling, Thank you for your contribution to Ivy, any information about the unsupported data-types which needs to be added here?

Thank you for checking the PR. Since this is a rawops implementation, which refers to the Einsum in general functions so isn't the information about the unsupported datatypes be included in the general functions rather at rawops?

2023-07-18 09:03 UTC, janchilling commented
Would appreciate if I can get a reply. Thank you.

2023-07-23 09:15 UTC, janchilling commented
@theRealBird Can you please provide an review or request a change please :smile:

2023-07-23 14:10 UTC, theRealBird commented
Hi @janchilling, thank you so much for your patience. I really appreciate it.

Explicitly mentioning supported dtypes seems to be the norm for other raw_ops implementations as well, you are right, ideally the information should go in the frontend implementation, but currently that is not present as you might have also seen. I think it would be best to include it here just as a fail-safe.

Thanks!

2023-07-23 14:11 UTC, theRealBird requested changes

2023-07-23 14:11 UTC, theRealBird commented on ivy/functional/frontends/tensorflow/raw_ops.py
Please aslo resolve the merge conflicts. Thanks!

2023-07-26 12:23 UTC, janchilling commented on ivy/functional/frontends/tensorflow/raw_ops.py
@theRealBird I resolved the merge conflicts and added the supported data types for the function. Please update me if I have to make anymore changes.

2023-07-31 05:20 UTC, janchilling commented
@theRealBird Can I get an update please, Thank you!

2023-07-31 05:59 UTC, theRealBird approved these changes
Thanks @janchilling

2023-07-31 05:59 UTC, theRealBird commented
Hi @janchilling,
Thank you for your patience and making the changes!

2023-07-31 05:59 UTC, merged