add gamma and test_gamma to numpy frontend
unifyai/ivy pull request #19428
Opened 2023-07-14 15:33 UTC by Zeyad-Alaa17

2023-07-14 16:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-15 15:42 UTC, Zeyad-Alaa17 commented
On further review to the code i think i made a mistake @Sam-Armstrong .
Ivy uses shape parameter α = k and an inverse scale parameter β = 1/θ, called a rate parameter where Numpy uses shape k and scale θ.
So i think i should return 1/scale in numpy frontend
`def gamma(shape, scale=1.0, size=None):
    return ivy.gamma(shape, scale, shape=size, dtype="float64")`

should be changed to:
`def gamma(shape, scale=1.0, size=None):
    return ivy.gamma(shape, 1/scale, shape=size, dtype="float64")`

2023-07-17 23:55 UTC, Sam-Armstrong commented
@Zeyad-Alaa17 I think that makes sense, if you make another commit and push it, it will update the pull request 😊

2023-07-18 15:51 UTC, Zeyad-Alaa17 commented
@Sam-Armstrong I've updated the pull request with the requested change.

2023-07-19 23:53 UTC, Sam-Armstrong requested changes
Hey @Zeyad-Alaa17, I've had another look and an experiment with numpy.random.gamma - I don't think we actually need to do 1 / scale as this actually is done in numpy. Please could you change this, along with the other suggestions I've made here. Then hopefully we should be good to merge, if you agree with my assessment. Thanks 😊

2023-07-19 23:53 UTC, Sam-Armstrong commented on ivy/functional/frontends/numpy/random/functions.py
> +    return ivy.gamma(shape, 1 / scale, shape=size, dtype="float64")
```suggestion
    return ivy.gamma(shape, scale, shape=size, dtype="float64")
```

2023-07-19 23:53 UTC, Sam-Armstrong commented on ivy/functional/frontends/numpy/random/functions.py
> +        raise ValueError("scale must be greater than 0")
We no longer need this to avoid a divide by 0

2023-07-19 23:53 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +    assume("float16" not in scale_dtypes)
```suggestion
```

2023-07-19 23:53 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +        input_dtypes=shape_dtypes + scale_dtypes + size_dtypes,
```suggestion
        input_dtypes=dtypes,
```

2023-07-19 23:53 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +    size_dtypes=helpers.get_dtypes("integer", full=False),
You can replace these different dtypes definitions with a single `dtypes=helpers.get_dtypes("float", full=False)` to make this less verbose

2023-07-19 23:53 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +    assume("float16" not in scale_dtypes)
No need for these

2023-07-20 00:47 UTC, Zeyad-Alaa17 commented
@Sam-Armstrong  I've made the requested changes an i think we should be good to merge. I appreciate your assessment 😊

2023-07-20 09:07 UTC, Sam-Armstrong approved these changes
lgtm! thanks @Zeyad-Alaa17

2023-07-20 09:12 UTC, Sam-Armstrong commented
ivy-gardener

2023-07-20 09:14 UTC, merged