Implemented argpartition #18938
unifyai/ivy pull request #19429
Opened 2023-07-14 16:02 UTC by Aayushkumr

2023-07-20 06:42 UTC, xoiga123 requested changes
Sorry it took so long to review! I have some changes that you may want to look at. Thank you for contributing! :hugs:

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/backends/torch/sorting.py
> +    return torch.argpartition(x, kth=kth, dim=axis)
`torch.argpartition` doesn't exist?

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/backends/tensorflow/sorting.py
> +    return paddle.argsort(x, axis=axis).argsort(axis=axis)
This should be a `tensorflow` function, not `paddle` :sweat_smile:

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/backends/paddle/sorting.py
> +    return paddle.argsort(x, axis=axis).argsort(axis=axis)
`argpartition` and `argsort` is not the same, [reference](https://www.pythonpool.com/numpy-argpartition/)

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/frontends/jax/numpy/searching_sorting.py
> +) -> ivy.Array:
Correct me if I'm wrong but the signature for `jax.numpy.argpartition` doesn't have `kind` and `order` arguments? [reference](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.argpartition.html)

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/frontends/jax/numpy/searching_sorting.py
> +argpartition.support_native_out = True
I don't think it supports an `out` argument natively, [reference](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.argpartition.html)

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/frontends/jax/numpy/searching_sorting.py
> +) -> ivy.Array:
We used the decorator `@to_ivy_arrays_and_back`, which means that the return type of the function should be a frontend array, not `ivy.Array`. It's best not to typehint the frontend implementations.

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/frontends/numpy/sorting_searching_counting/sorting.py
> +    return ivy.stack(partitions, axis=axis)
Why didn't you use `ivy.argpartition`?

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/frontends/torch/comparison_ops.py
> +    return ivy.stack(partitions, axis=axis)
Why didn't you use `ivy.argpartition`?

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/ivy/sorting.py
> +@handle_out_argument
Why did you use `@handle_out_argument` when the function doesn't support `out`?

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/ivy/sorting.py
> +    kind: Optional[str] = "introselect",
```python
kind: str = "introselect"
```
We don't use `Optional` typehint when the default value is not `None`

2023-07-20 06:42 UTC, xoiga123 commented on ivy/functional/ivy/sorting.py
> +    API_specification/generated/array_api.argpartition.html>`_
Is the link correct? I got an `404` trying to access it.

2023-07-20 06:42 UTC, xoiga123 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_searching_sorting.py
> +    dtype_x_kth_axis=helpers.dtype_values_kth_axis(
`helpers.dtype_values_kth_axis` doesn't exist in the codebase?

2023-07-20 06:42 UTC, xoiga123 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_comparison_ops.py
> +    )
Is this mistakenly repeated :sweat_smile:?

2023-08-04 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-13 17:46 UTC, zhumakhan commented
Hi, thanks for you contribution! Could you please go through each comment left by xoiga123 and resolve them?

2023-09-02 05:53 UTC, closed without merging

2023-09-02 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.