Added pytorch frontend block_diag and its tests
unifyai/ivy pull request #19437
Opened 2023-07-15 03:05 UTC by vishwajit-vishnu

Close #19198

2023-07-15 03:14 UTC, vishwajit-vishnu commented
1 backend test is failing due to already faulty paddle's scatter_nd function

2023-07-15 04:26 UTC, vishwajit-vishnu commented
@Dsantra92 Can you please review and merge

2023-07-15 13:32 UTC, vishwajit-vishnu commented
@MuhammedAshraf2020 can you please review and merge

2023-07-20 11:51 UTC, vishwajit-vishnu commented
@ivy-leaves @MuhammedAshraf2020 can you please review or add any suggestions for the PR

2023-07-23 00:14 UTC, vishwajit-vishnu commented
@ivy-seed @MuhammedAshraf2020  can you please review this PR??

2023-07-27 01:08 UTC, vishwajit-vishnu commented
@ivy-leaves @ivy-seed @MuhammedAshraf2020 Can you please review it ?? Its been more than two weeks now. Atleast looking for some comment or some suggestions

2023-07-29 22:47 UTC, MuhammedAshraf2020 commented
Hey @vishwajit-vishnu ,
Apologies for the latency. Thank you for your valuable contribution. Your PR will be reviewed very soon.

2023-08-04 12:49 UTC, vishwajit-vishnu commented
@AnnaTz Can you please review it

2023-08-14 15:02 UTC, AnnaTz requested changes

2023-08-18 10:05 UTC, vishwajit-vishnu commented on ivy/functional/frontends/torch/miscellaneous_ops.py
> +    inp_tensors = [ivy.asarray(t, dtype=promoted_dtype) for t in tensors]
@AnnaTz  Its not redundant as we are copying the array to a specific location in zeros array and not promoting their dtype while copying. So Its failing the tests if we do not do this step

2023-08-18 10:08 UTC, vishwajit-vishnu commented
@AnnaTz  thanks for review. I have made the changes. You can merge it. Also wanted to ask if this can be implemented as a mixed function where for torch and scipy the backend will return the value but for other backends it will raise a NotImplementedError and we can use the current code  in a ivy function to give functionality for other backends

2023-08-18 10:15 UTC, AnnaTz commented
> @AnnaTz thanks for review. I have made the changes. You can merge it. Also wanted to ask if this can be implemented as a mixed function where for torch and scipy the backend will return the value but for other backends it will raise a NotImplementedError and we can use the current code in a ivy function to give functionality for other backends

There is one more line error to resolve.
Yes we could do that. In mixed function we don't get NotImplementedError error though. For the frameworks that don't have a corresponding function we use a compositional implementation which is the main ivy function made of other ivy functions, in this case the code you wrote for the frontend would work.

2023-08-18 11:28 UTC, AnnaTz approved these changes
Great, thanks!

2023-08-18 11:28 UTC, merged

2023-08-18 11:31 UTC, AnnaTz commented
> > Yes we could do that. In mixed function we don't get NotImplementedError errors though. For the frameworks that don't have a corresponding function we use a compositional implementation which is the main ivy function made of other ivy functions, in this case the code you wrote for the frontend would work.
> 
> You can merge the changes Can you create an issue to create ivy function for block_diag and I can add ivy functionn for that. I read documentation here [mixed function](https://unify.ai/docs/ivy/overview/deep_dive/function_types.html#mixed-functions), but compositional functions are used only when all backends do not have this function block_diag. But torch and scipy has that. I did not find any example on mixed function. Sorry if I misunderstood and again thanks for the help

I added `block_diag` [here](https://github.com/unifyai/ivy/issues/3856). Feel free to open an issue and start working on that!

2023-08-18 11:33 UTC, AnnaTz commented
> > Yes we could do that. In mixed function we don't get NotImplementedError errors though. For the frameworks that don't have a corresponding function we use a compositional implementation which is the main ivy function made of other ivy functions, in this case the code you wrote for the frontend would work.
> 
> You can merge the changes Can you create an issue to create ivy function for block_diag and I can add ivy functionn for that. I read documentation here [mixed function](https://unify.ai/docs/ivy/overview/deep_dive/function_types.html#mixed-functions), but compositional functions are used only when all backends do not have this function block_diag. But torch and scipy has that. I did not find any example on mixed function. Sorry if I misunderstood and again thanks for the help

![image](https://github.com/unifyai/ivy/assets/111577222/2efe4b84-472c-48c8-a27a-1a332d1ed639)