Implement rfft
unifyai/ivy pull request #19454
Opened 2023-07-15 14:25 UTC by AwkNinja

Close #19383

2023-07-15 22:35 UTC, AwkNinja commented
Still working on fixing the failing tests for tensorflow and torch.

2023-07-27 18:02 UTC, AwkNinja commented
@hmahmood24 Can you please have a look at the implementation here. I can't get the tensorflow and torch tests to pass.

2023-07-27 19:09 UTC, AwkNinja commented
The torch tests seem to be passing now but still having issues with tensorflow. The main error is that the elements list is empty so it throws the error cannot draw from an empty list. At first I thought it was because of the norm list that I am generating but it doesn't seem like its related to it.

2023-08-13 08:22 UTC, hmahmood24 requested changes

2023-08-13 08:22 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py
> +    ),
Why can't we use something like this?

```python
dtype_input_axis=helpers.dtype_values_axis(
        available_dtypes=helpers.get_dtypes("valid"),
        min_num_dims=1,
        min_dim_size=2,
        shape=helpers.get_shape(...),
        force_int_axis=True,
    )
```

2023-08-13 08:22 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py
> +    n=st.integers(min_value=2, max_value=10),
We also need to test for the default `n=None` case

2023-08-26 07:12 UTC, AwkNinja commented
Hi @hmahmood24 sorry for the late update but please take a look.

2023-08-27 07:24 UTC, hmahmood24 requested changes

2023-08-27 07:24 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py
> +                                max_dim_size=4,),
@asad0991 Perhaps you forgot to install/run `pre-commit` to fix your [lint/formatting errors](https://github.com/unifyai/ivy/actions/runs/5983491732/job/16233689761?pr=19454)?

2023-09-10 14:53 UTC, AwkNinja commented
@hmahmood24 Fixed the lint issues I changed devices forgot to install pre-commit on the new device.

2023-09-11 17:29 UTC, hmahmood24 requested changes
@AwkNinja I can see a couple of [failing tests](https://github.com/unifyai/ivy/actions/runs/6137850477/job/16654114642?pr=19454) still associated with this PR

2023-09-11 17:53 UTC, AwkNinja commented
@hmahmood24 The tests for tensorflow gives me keyError: "cup" its like the error you get when the version is wrong in the decorator but I used the correct one. For the paddle error it just started to occur just now. Its basically in ivy.dft function I'll take a look at it.

2023-09-11 17:58 UTC, hmahmood24 commented
> @hmahmood24 The tests for tensorflow gives me keyError: "cup" its like the error you get when the version is wrong in the decorator but I used the correct one. For the paddle error it just started to occur just now. Its basically in ivy.dft function I'll take a look at it.

Pretty sure you can find a solution to that key error problem in discord since that's been brought up numerous times already

2023-09-11 18:04 UTC, AwkNinja commented
> > @hmahmood24 The tests for tensorflow gives me keyError: "cup" its like the error you get when the version is wrong in the decorator but I used the correct one. For the paddle error it just started to occur just now. Its basically in ivy.dft function I'll take a look at it.
> 
> Pretty sure you can find a solution to that key error problem with a simple search in discord since that's been brought up numerous times already

I did read on discord chaning version to 2.5.1 and below should have fixed it. I'll have a look again might be another solution someone brought up.

2023-09-22 18:58 UTC, AwkNinja commented
Hi @hmahmood24, the `tensorflow` tests are passing now with the change I made but It should no longer be needed once [this](https://github.com/unifyai/ivy/pull/23439) feature is implemented. Also for the paddle tests I found the issue [here](https://github.com/AwkNinja/ivy/blob/463b0af5ec4f2cf68a5d2ddb85bd5f46f5526077/ivy/functional/ivy/general.py#L2934C46-L2934C46). Basically `query_` is a `slice` object and at some point value for `query_` is `slice(0, ivy.Array(2), None)` hence giving the error `TypeError: slice indices must be integers or None or have an __index__ method`. Maybe some with more experience in the handling of `paddle` framework can look into this.

2023-09-23 16:24 UTC, hmahmood24 commented
> Hi @hmahmood24, the `tensorflow` tests are passing now with the change I made but It should no longer be needed once [this](https://github.com/unifyai/ivy/pull/23439) feature is implemented. Also for the paddle tests I found the issue [here](https://github.com/AwkNinja/ivy/blob/463b0af5ec4f2cf68a5d2ddb85bd5f46f5526077/ivy/functional/ivy/general.py#L2934C46-L2934C46). Basically `query_` is a `slice` object and at some point value for `query_` is `slice(0, ivy.Array(2), None)` hence giving the error `TypeError: slice indices must be integers or None or have an __index__ method`. Maybe someone with more experience in the handling of `paddle` framework can look into this.

Hey @AwkNinja, thanks a lot for the effort. I'll ask someone from the team to take a look at this issue you brought up with `_parse_query`. In the meanwhile I think it should be okay to merge the PR because this issue stems from `set_item` itself and not with your PR. What do you think @AnnaTz ?

2023-09-23 16:26 UTC, hmahmood24 approved these changes

2023-09-25 12:24 UTC, AnnaTz commented
> > Hi @hmahmood24, the `tensorflow` tests are passing now with the change I made but It should no longer be needed once [this](https://github.com/unifyai/ivy/pull/23439) feature is implemented. Also for the paddle tests I found the issue [here](https://github.com/AwkNinja/ivy/blob/463b0af5ec4f2cf68a5d2ddb85bd5f46f5526077/ivy/functional/ivy/general.py#L2934C46-L2934C46). Basically `query_` is a `slice` object and at some point value for `query_` is `slice(0, ivy.Array(2), None)` hence giving the error `TypeError: slice indices must be integers or None or have an __index__ method`. Maybe someone with more experience in the handling of `paddle` framework can look into this.
> 
> Hey @AwkNinja, thanks a lot for the effort. I'll ask someone from the team to take a look at this issue you brought up with `_parse_query`. In the meanwhile I think it should be okay to merge the PR because this issue stems from `set_item` itself and not with your PR. What do you think @AnnaTz ?

This wasn't a `set_item` issue. I have just resolved it with a quick [fix](https://github.com/unifyai/ivy/commit/9ee0f944c2d51770f48eb0b6fec18e016d62da7e) in `ivy.dft`.

2023-09-28 04:21 UTC, AwkNinja commented
Hi @hmahmood24 all the test cases are passing now with the fix that @AnnaTz did. Please take a look.

2023-09-28 08:05 UTC, merged