refactor set_nest_at_index
unifyai/ivy pull request #1949
Opened 2022-07-15 01:49 UTC by Wilman2612

2022-07-15 01:57 UTC, Wilman2612 commented
#1948

2022-07-15 15:08 UTC, Wilman2612 commented
about this error : 

   output for  set_nest_at_index  on run:  shapemismatch:valuetensorofshape[2]cannotbebroadcasttoindexingresultofshape[1]torchivy.set_nest_at_index(x,y,z)ivy.array([[1.,2.],[3.,4.]]){'a':0,'b':[1,2],'c':(4,5)}[['a','b','c'],['d','e','f'],['g',['H','i']]] 
output in docs : ivy.array([[1.,2.],[5.,6.]){'a':0,'b':[1,2],'c':(4,5)}[['a','b','c'],['d','e','f'],['g',['H','i']]]

because of this : shapemismatch:valuetensorofshape[2]cannotbebroadcasttoindexingresultofshape[1]torchivy. Looks like an error in the front end implementation of the array setter is not allowing to execute the set_nest_at_index function therefore the output turns out incorrect. Should i remove Array and NativeArray from the signature or is something that will be fixed?

2022-07-18 13:46 UTC, jiahanxie353 requested changes
Your current docstrings are right, and please refer to the [deep dive docstring examples](https://lets-unify.ai/ivy/deep_dive/12_docstring_examples.html) as this section mentions many rubrics. For example, you should give docstring example of `ivy.Container`

Also, there are issues raised from docstrings tests, and the error is raised from `backend/torch/general/scatter_nd`, which is  irrelevant to your changes. I'm trying to fix it.

2022-07-18 13:46 UTC, jiahanxie353 commented on ivy/functional/ivy/nest.py
> +    index: Tuple,
`index` could be more than `Tuple`

2022-07-18 13:46 UTC, jiahanxie353 commented on ivy/functional/ivy/nest.py
> +    nest: Union[ivy.Array, ivy.NativeArray, Dict, List],
`nest` could also be a `ivy.Container`

2022-07-19 03:53 UTC, Wilman2612 commented
@jiahanxie353  I haven't included an container example because I think that is not a nestable function since is no implemented in ivy.container as specified in the function types and containers sections of the deep dive

2022-07-20 00:35 UTC, Wilman2612 commented
@jiahanxie353 I have included an example container. Is there anything else I need to amend?

2022-07-20 01:58 UTC, jiahanxie353 commented
> @jiahanxie353 I have included an example container. Is there anything else I need to amend?

@Wilman2612 it looks good to me. I will merge it.
Thanks very much for your contribution :)

2022-07-20 02:12 UTC, merged