Added elu activation function implementation
unifyai/ivy pull request #19494
Opened 2023-07-16 22:46 UTC by MansiAmbalam

Added implementation for elu based on the corresponding documentation.

Closes #19469

2023-07-17 09:02 UTC, Daniel4078 requested changes
Hello, you need to write a test function like the other pull requests linked in the TODO list this task is from. You can find other info about how to write our test in the [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues) and our [Deep Dive document](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html).

2023-07-17 09:02 UTC, Daniel4078 commented on ivy/functional/frontends/paddle/nn/functional/activation.py
> -    return ivy.elu(x, alpha=alpha)
Why did you remove the existing implementation? I think the ivy.elu (https://github.com/unifyai/ivy/blob/f5f8cd107865b7de6650e495474d0667e8ec4757/ivy/functional/ivy/experimental/activations.py#L408) is working alright?

2023-07-17 09:03 UTC, Daniel4078 commented
By the way, you did not reference the issue you created to the TODO list issue we created to track the status of tasks.

2023-08-14 03:41 UTC, juliagsy commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-08-14 03:41 UTC, closed without merging