added any to paddle math
unifyai/ivy pull request #19553
Opened 2023-07-18 09:43 UTC by sroycho4

close #19552

2023-07-24 07:13 UTC, rishabgit requested changes
Hey @sroycho4, thanks for looking into this! :smile:
Added comments in the code, feel free to request a review after making the changes. 
Hope this helps - https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/any_en.html
Thanks! :smile:

2023-07-24 07:13 UTC, rishabgit commented on ivy/functional/frontends/paddle/tensor/math.py
> +
missing supported dtypes

2023-07-24 07:13 UTC, rishabgit commented on ivy/functional/frontends/paddle/tensor/math.py
> +    return ivy.max(x, axis=axis, keepdims=keepdim)
not sure why it's calling ivy.max instead of ivy.any?

2023-07-24 07:43 UTC, sroycho4 commented
@rishabgit whoops, don't know how it got altered. Fixed them!

2023-07-27 16:10 UTC, rishabgit requested changes
Still missing supported dtypes :sweat_smile: 
Feel free to request a re-review!

2023-07-28 05:33 UTC, sroycho4 commented
@rishabgit done!

2023-07-31 15:52 UTC, rishabgit commented
Thanks for the changes, they look great!

2023-07-31 15:52 UTC, merged