max_unpool1d #19547
unifyai/ivy pull request #19561
Opened 2023-07-18 11:50 UTC by erimdogan

close #19547

2023-07-18 12:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-18 13:40 UTC, Daniel4078 requested changes
Hello, I found some formatting issues that you need to fix. Please check out the comments below, thank you!

2023-07-18 13:40 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +        indices=indices
```
-        indices=indices
+        indices=indices,
```

2023-07-18 13:40 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
please add one extra empty line here

2023-07-18 13:40 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +        fn_tree="functional.ivy.experimental.layers.max_unpool1d",
```
-        fn_tree="functional.ivy.experimental.layers.max_unpool1d",
-        x_k_s_p=helpers.arrays_for_pooling(min_dims=3, max_dims=3, min_side=1, max_side=4),
-        indices = st.lists(st.integers(0,1), min_size=1, max_size=4), 
-        ground_truth_backend="jax",
-        test_gradients=st.just(False),  
+    fn_tree="functional.ivy.experimental.layers.max_unpool1d",
+    x_k_s_p=helpers.arrays_for_pooling(min_dims=3, max_dims=3, min_side=1, max_side=4),
+    indices=st.lists(st.integers(0, 1), min_size=1, max_size=4),
+    ground_truth_backend="jax",
+    test_gradients=st.just(False),
```

2023-07-18 13:40 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
please add one extra empty line here

2023-07-18 13:40 UTC, Daniel4078 commented on ivy/functional/ivy/experimental/layers.py
> +)
```
-)
+    )
```

2023-07-18 13:40 UTC, Daniel4078 commented on ivy/functional/ivy/experimental/layers.py
> +    x:  ivy.Union[ivy.Array, ivy.NativeArray],
```
-    x:  ivy.Union[ivy.Array, ivy.NativeArray],
-    indices : Union[ivy.Array, ivy.NativeArray],
-    kernel : Union[int, Tuple[int]],
-    strides : Union[int, Tuple[int]],
-    padding : str,
+    x: ivy.Union[ivy.Array, ivy.NativeArray],
+    indices: Union[ivy.Array, ivy.NativeArray],
+    kernel: Union[int, Tuple[int]],
+    strides: Union[int, Tuple[int]],
+    padding: str,
     /,
     *,
-    data_format : str = "NWC",
-    out : Optional[ivy.Array] = None
+    data_format: str = "NWC",
+    out: Optional[ivy.Array] = None,
```

2023-07-18 13:40 UTC, Daniel4078 commented on ivy/functional/ivy/experimental/layers.py
please add one extra empty line here

2023-07-18 13:54 UTC, erimdogan commented
I made the changes that you reccommend. Thanks for advices.

2023-07-18 22:05 UTC, Daniel4078 approved these changes
Looks good to me!

2023-07-18 22:05 UTC, merged

2023-09-12 00:31 UTC, Daniel4078 reviewed
Well, it seems like there is no backend implemenations written for max_unpool1d so the tests are not passing