#19613 added sqrtm function to linalg in tensorflow front end and tested
unifyai/ivy pull request #19619
Opened 2023-07-19 12:01 UTC by SayalGorania

#19613

2023-07-19 12:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-27 05:18 UTC, YushaArif99 commented on ivy/functional/frontends/tensorflow/linalg.py
> +    return ivy.sqrtm(input)
I think the previous reviewer mentioned that there is no `ivy.sqrtm` function in Ivy. You'll have to implement it as a composition of other ivy functions. In the other case, you may also propose this function to be added to the API, more info here:[ https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis]. 

If you choose to go with the latter case, I'd suggest you close this PR and work on other any other open tasks. Thanks! 🙂

2023-07-27 05:20 UTC, YushaArif99 requested changes
Hi @SayalGorania 

The tests for `test_tensorflow_sqrtm` seem to be failing in the CI. There is also the other issue I have mentioned above. Let me know what you think 🙂

2023-07-27 12:00 UTC, SayalGorania reviewed
Have modified sqrtm function to use existing ivy functions. I am not sure why it is failing the tests though. Are you able to help?

2023-08-17 08:25 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py
> +def test_sqrtm(
this is not the correct way to write frontend tests. You should make use of the `helpers.test_frontend_function` which will handle the value assertion logic etc. You can look at the way the other tests have been written as an inspiration 🙂

2023-08-17 08:27 UTC, YushaArif99 requested changes
Hi @SayalGorania 

Could you kindly address the abovementioned issue. Feel free to re-request a review once all relevant CI tests are passing. Thanks! 🙂

2023-09-18 05:14 UTC, closed without merging