Added NumPy take method
unifyai/ivy pull request #19725
Opened 2023-07-20 20:35 UTC by joshsalce

Note: There is no Ivy Experimental API implementation, so I implemented it using Ivy array methods and Python. It will have to be simplified once implemented in Ivy

2023-07-20 21:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-24 09:51 UTC, jkeane508 requested changes
Seems to be an issue with your test. Maybe just check over and make sure that all your args are right for the test functions

2023-07-24 09:51 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +    test_with_out=st.just(False),
Seems to be an issue with this handle in testing [here](https://github.com/unifyai/ivy/actions/runs/5615801049/job/15216863669?pr=19725#step:3:220).

2023-07-26 09:16 UTC, jkeane508 requested changes

2023-07-26 09:16 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +def test_numpy_take(
Seems to be an issue with arguments according to tests [here](https://github.com/unifyai/ivy/actions/runs/5659074707/job/15331825717?pr=19725#step:3:182). Would double check that all of your args and kwargs are correct :)

2023-09-02 03:48 UTC, DecFox commented
Hey @joshsalce, thanks for the PR. Sorry for the late feedback. I left some comments which should hopefully help with the tests.

2023-09-02 09:37 UTC, DecFox requested changes

2024-03-25 16:14 UTC, Ishticode commented
closing this as take is already implemented in numpy frontend https://github.com/unifyai/ivy/blob/ea402610b7e2cdf77eccf2460e7b6be42e71c2b0/ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py#L88

2024-03-25 16:14 UTC, closed without merging