Jax devicearray sum
unifyai/ivy pull request #19723
Opened 2023-07-20 20:14 UTC by VictorOdede

Close #19418

2023-07-27 07:27 UTC, hirwa-nshuti requested changes
Hey @VictorOdede 

The changes are good, some requested changes are below

2023-07-27 07:27 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_jax/test_devicearray.py
> +        available_dtypes=["int64"],
The tests should also cover all supported dtypes

2023-07-31 08:31 UTC, VictorOdede commented
Hey @hirwa-nshuti , I've added tests to include all numeric dtypes

2023-07-31 19:15 UTC, hirwa-nshuti requested changes
Hey

Some other changes needed😊

2023-07-31 19:15 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/devicearray.py
> +    def sum(
The promotion here will be done with the same approach as the one mentioned on the `prod` PR.

2023-08-02 12:29 UTC, VictorOdede commented
Hey @hirwa-nshuti , the most recent changes to `main` are causing all Jax tests to fail with `AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'`. Not sure what's causing this problem

2023-08-02 13:23 UTC, hirwa-nshuti commented
> Hey @hirwa-nshuti , the most recent changes to `main` are causing all Jax tests to fail with `AttributeError: module 'jax.numpy' has no attribute 'DeviceArray'`. Not sure what's causing this problem

Working on a fix for this issue😊

2023-08-02 23:33 UTC, closed without merging