Add func wrapper for converting shapes to ivy shapes
unifyai/ivy pull request #19774
Opened 2023-07-21 08:16 UTC by vaithak

2023-07-21 08:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-21 21:43 UTC, Sam-Armstrong reviewed
lgtm, but maybe @AnnaTz can quickly check this as I'm not very familiar with this part of the codebase?

2023-07-24 10:25 UTC, AnnaTz requested changes

2023-07-24 10:25 UTC, AnnaTz commented on ivy/functional/frontends/torch/func_wrapper.py
> +    `ivy.Shape` instances.
To be clear, please refer to the shapes we are converting as `torch_frontend.Size`, not `torch.Size` (this refers to the original torch class) neither NativeShape (this refers mostly to the backends).
Also the first sentence is not necessary at all.

2023-07-24 10:25 UTC, AnnaTz commented on ivy/functional/frontends/torch/func_wrapper.py
> +        # if any of the args are instance of ivy.NativeShape, convert them to ivy.Shape.
Same here. Please change to `torch_frontend.Size`.

2023-07-24 10:26 UTC, AnnaTz commented
Tagging @vaithak to check the transpilation cases mentioned in the trello card.

2023-07-24 12:07 UTC, vaithak commented
> Tagging @vaithak to check the transpilation cases mentioned in the trello card.

Verified the transpilation of Bart and Levit models 👍🏼

2023-07-24 12:10 UTC, AnnaTz approved these changes

2023-07-24 12:49 UTC, merged