Add deep dive section explaining the device handling behaviour of ivy
unifyai/ivy pull request #19783
Opened 2023-07-21 11:03 UTC by bipinKrishnan

Adds the deep dive section explaining different ways to control the device on which the operation is performed, the soft device mode in Ivy and using `ivy.DefaultDevice` to force the operations on a specific device.

2023-07-21 11:08 UTC, vedpatwardhan approved these changes
lgtm! Thanks for updating the docs @bipinKrishnan, we can get the PR merged based on what @sherry30 thinks 😄👍

2023-07-25 08:50 UTC, sherry30 requested changes
Just 1 minor addition.
Looks good otherwise.

Thanks!

2023-07-25 08:50 UTC, sherry30 commented on docs/overview/deep_dive/devices.rst
> +all the functions except mixed and compositional functions in `ivy.functional.ivy`_ submodule. The decorator calls
All the functions that accept at least 1 array

2023-07-26 10:18 UTC, sherry30 approved these changes
lgtm!

2023-07-26 10:41 UTC, merged