ivy.Shape fixes
unifyai/ivy pull request #2006
Opened 2022-07-18 07:47 UTC by juliagsy

- fixed backend type hints `Union[native_arr, ivy.Array, ivy.Shape]`
- fixed return of each backend `shape` function to be ivy.Shape(x.shape)

2022-07-18 08:42 UTC, Oxbeefbabe commented
Hi @juliagsy,

There seem to be some docstring tests failing on this, can you have a look at them to see if it is your changes causing them or if they are unrelated.

Cheers :)

2022-07-18 16:00 UTC, djl11 requested changes

2022-07-18 16:00 UTC, djl11 commented on ivy/functional/backends/jax/general.py
> +        return ivy.array(x.shape)
actually we should have `ivy.array(jnp.shape(x))` or `ivy.Array(jnp.shape(x))` if `jnp.shape` returns a native shape instance.

2022-07-18 16:00 UTC, djl11 commented on ivy/functional/backends/mxnet/general.py
> +        return ivy.array(x.shape)
actually we should have `ivy.array(mx.nd.shape_array(x))` or `ivy.Array(mx.nd.shape_array(x))` if `mx.nd.shape_array` returns a native shape instance.

2022-07-18 16:00 UTC, djl11 commented on ivy/functional/backends/numpy/general.py
> +        return ivy.array(x.shape)
actually we should have `ivy.array(np.shape(x))` or `ivy.Array(np.shape(x))` if `np.shape` returns a native shape instance.

2022-07-18 16:00 UTC, djl11 commented on ivy/functional/backends/tensorflow/general.py
> +        return ivy.array(x.shape)
actually we should have `ivy.array(tf.shape(x))` or `ivy.Array(tf.shape(x))` if `tf.shape` returns a native shape instance.

2022-07-19 04:01 UTC, juliagsy reviewed
Hey @djl11, I have some doubts (as previously we said that it should be ivy.Array or ivy.Shape for this function) and I've put them in the comments below, thanks!

2022-07-19 18:27 UTC, djl11 commented on ivy/functional/backends/mxnet/general.py
>          return mx.nd.shape_array(x)
you should wrap this native array inside `ivy.array` :)

2022-07-19 18:27 UTC, djl11 commented on ivy/functional/backends/tensorflow/general.py
>          return tf.shape(x)
you should wrap this native array inside `ivy.array` :)

2022-07-19 18:27 UTC, djl11 requested changes
see comments :)

2022-07-20 02:39 UTC, merged