`elementwise` fix up
unifyai/ivy pull request #2044
Opened 2022-07-18 19:15 UTC by rush2406

- removed `np.random_int` in `bitwise_left_shift` and `bitwise_right_shift`
- for `divide`, used `assume` to exclude divide by 0

2022-07-19 18:51 UTC, djl11 requested changes
small changes, otherwise good to merge. But if you want a full review of the elementwise module then you will need to add comments to each relevant file, before I can indicate whether it is ready to be marked as complete.

2022-07-19 18:51 UTC, djl11 commented on ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
> +    assume(np.all(x1 <= 9223372036854775807))
is this needed, with the new `0.95` safety factor in the [data generation helpers](https://github.com/unifyai/ivy/blob/591ac37a664ebdf2ca50a5b0751a3a54ee9d5934/ivy_tests/test_ivy/helpers.py#L1470)?

2022-07-20 14:51 UTC, djl11 requested changes
seems as though the tests are failing on the PR, could you merge with master and see if this fixes things?

2022-07-21 06:07 UTC, djl11 requested changes
on `request_floor_divide`, the most elegant solution would be to add [this](https://github.com/unifyai/ivy/blob/423074c63bfc751c806f514705c89b10b1597bf8/ivy_tests/test_ivy/helpers.py#L1463) `safety_factor` argument to the helper `test_function`. With a value of `0.5`. This should achieve the same effect as this custom logic in the unit test body.

Also, some tests are checking for conditions and then returning, these should instead make use of the hypothesis `assume` statement.

Once these changes are made, please request a final review and then we can get it merged :)

2022-07-21 06:07 UTC, djl11 commented on ivy_tests/test_ivy/test_functional/test_core/test_elementwise.py
>          return  # ints to negative int powers not allowed
we should use `assume` statement here, rather than simply returning.

2022-07-21 07:20 UTC, rush2406 commented
> on `test_floor_divide`, the most elegant solution would be to add [this](https://github.com/unifyai/ivy/blob/423074c63bfc751c806f514705c89b10b1597bf8/ivy_tests/test_ivy/helpers.py#L1463) `safety_factor` argument to the helper `test_function`. You should then pass a value of `0.5` for this test. This should achieve the same effect as this custom logic in the unit test body.

Currently, `safety_factor` is not in the arguments of `dtype_and_values`, so I have added it with this commit.

2022-07-22 21:17 UTC, djl11 approved these changes
please check whether the tests are passing. If so, then it looks okay to me :)

2022-07-23 06:12 UTC, merged