finish reformatting of `round`
unifyai/ivy pull request #2049
Opened 2022-07-19 00:20 UTC by ahmedo42

2022-07-21 03:10 UTC, RickSanchezStoic commented
Check and fix the lint errors as well as the test-docstrings / run-docstring-tests. They both should go green.

2022-07-21 08:47 UTC, ahmedo42 commented
@RickSanchezStoic it seems to me that test-docstrings are failing for reasons unrelated to this PR -precisely `repeat()`- and lint tests are already green, can you confirm? or am I missing something?

2022-07-21 18:57 UTC, RickSanchezStoic commented
> @RickSanchezStoic it seems to me that test-docstrings are failing for reasons unrelated to this PR -precisely `repeat()`- and lint tests are already green, can you confirm? or am I missing something?

It seems like your fork is not updated, first try adding examples with `out` argument and then try updating your fork.

2022-07-21 22:32 UTC, ahmedo42 commented
@RickSanchezStoic  I think it's fixed now and examples with `out` are already there

2022-07-25 11:08 UTC, ahmedo42 commented
@RickSanchezStoic where is the review? can you request changes in the code or be more specific? , I went through the deep dive extensively and I don't understand what's still missing 

Again, examples with the `out ` argument  are already implemented so I didn't need to add them

2022-07-25 11:23 UTC, RickSanchezStoic requested changes

2022-07-25 11:24 UTC, RickSanchezStoic commented
My bad @ahmedo42, it should be visible now.

2022-07-25 11:34 UTC, ahmedo42 commented on ivy/array/elementwise.py
>          """
https://github.com/unifyai/ivy/blob/2539d99260dfe85c2ec97d1124e407e841196da9/ivy/functional/ivy/elementwise.py#L3660
it's in the functional module, should It also be implemented in the array module?

2022-07-26 19:04 UTC, RickSanchezStoic requested changes

2022-07-26 19:04 UTC, RickSanchezStoic commented on ivy/array/elementwise.py
>          """
We should add it for the array module too.

2022-07-27 05:12 UTC, RickSanchezStoic requested changes

2022-07-27 05:12 UTC, RickSanchezStoic commented on ivy/array/elementwise.py
> +        >>> print(x.round(out=y))
Since `y` is passed here to the `out` argument, it should be `print(y)` after `x.round(out=y)`

2022-07-27 18:00 UTC, RickSanchezStoic commented
lgtm! closes #1988

2022-07-27 18:01 UTC, RickSanchezStoic commented
Closes #1988

2022-07-27 18:02 UTC, RickSanchezStoic approved these changes

2022-07-27 18:19 UTC, merged