reformatted result_type
unifyai/ivy pull request #2077
Opened 2022-07-19 18:38 UTC by c1boo

2022-07-19 18:47 UTC, c1boo commented
#2041

2022-07-21 20:03 UTC, sherry30 requested changes
Hi,

A few changes are required
1. You have to write docstring example under the container instance method and also container static method.
2. Fix the lint issues caused by your changes.
3. Fix the docstring errors caused by `result_type`.

If you face any trouble or have any question, feel free to ask I'd be happy to help you out.

Thanks.

2022-07-26 08:29 UTC, sherry30 commented
Hi,

So it seems like there was a problem in the backend, this function is supposed to return ivy.Dtype but was returning the native dtype.
I have pushed a fix for this, now they all should be expecting the same answer i.e.  `{a:float32, b:int32}` which was the one you were receiving for torch before.

2022-07-27 03:39 UTC, sherry30 requested changes
Hi,

Can you add 1 functional example using container as an input in `ivy/functional/ivy/data_type.py`
I pointed out a few other changes on the particular lines 😃

2022-07-27 03:39 UTC, sherry30 commented on ivy/container/data_type.py
> +        b = ivy.array([3., 4., 5.]))
indent array `b` exactly under array `a`

2022-07-27 03:39 UTC, sherry30 commented on ivy/container/data_type.py
> +        >>> print(x.result_type(x))
running result type on the same containers, maybe create a different container `y` and then run it like `x.result_type(y)`

2022-07-29 05:40 UTC, merged