reformat tile
unifyai/ivy pull request #2079
Opened 2022-07-19 19:02 UTC by daisy-dotcom

- [ ] #2078

2022-07-25 12:36 UTC, MarShaikh requested changes
Hi, thanks for the examples. They look good but could you also add Array and container instance examples? Plus, can you also look at the backends, I noticed that some of them need to be reformatted as well! Thanks!

2022-07-28 20:35 UTC, daisy-dotcom commented
@MarShaikh will get to it as soon as i can (:

2022-08-16 12:53 UTC, MarShaikh requested changes
Everything else looks good. Please just remove the instance methods from the `ivy/functional` and add them to `tile` functions's array and container instances. Thanks!

2022-08-16 12:53 UTC, MarShaikh commented on ivy/functional/ivy/manipulation.py
> +    Instance Method Examples
The instance methods example belong to the `tile` instances in the `ivy/array` and `ivy/container`.

2022-08-18 18:16 UTC, daisy-dotcom commented
@MarShaikh okay. i moved them to the correct directories

2022-08-19 09:52 UTC, MarShaikh approved these changes
Lgtm!

2022-08-19 09:55 UTC, MarShaikh requested changes
Everything else in the code looks good, but you still need fix the docstring errors and the linting error. For the lint error, please just set up `pre-commit`, it will makes things a lot easier. You find more info on this in our docs. Thanks.

2022-08-22 23:31 UTC, daisy-dotcom commented
Hi @MarShaikh . I've fixed the lint error but I keep failing the docstring test. I checked and it says it's the depthwise_conv2d method with the issue. Is that okay?

2022-08-30 12:14 UTC, MarShaikh commented
> Hi @MarShaikh . I've fixed the lint error but I keep failing the docstring test. I checked and it says it's the depthwise_conv2d method with the issue. Is that okay?

Yes, since it isn't related to your function it is fine! I'll review your PR now.

2022-08-30 12:55 UTC, MarShaikh approved these changes
LGTM!

2022-08-30 12:55 UTC, merged

2022-08-31 11:42 UTC, daisy-dotcom commented
Thank you @MarShaikh