Fix: Replace paddle.prod with paddle.fluid.layers.reduce_prod to avoid segmentation fault
unifyai/ivy pull request #20836
Opened 2023-07-26 01:41 UTC by sladyn98

This PR addresses a segmentation fault issue found while using paddle.prod by replacing it with paddle.fluid.layers.reduce_prod. The implementation checks for optional parameters and applies reduce_prod on the specified axis, or the flattened tensor if axis is not provided.

2023-07-26 02:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-27 14:44 UTC, MahmoudAshraf97 requested changes
Hello, we should not be using layers instead of the functional API, the segmentation fault is cause by a bad set of input arguments and it should be handled manually

2023-07-27 19:01 UTC, sladyn98 commented
I refactored the prod function to use PaddlePaddle's functional API, replacing the use of paddle.fluid.layers.reduce_prod and paddle.flatten with paddle.prod and paddle.reshape respectively.

2023-08-20 23:04 UTC, MahmoudAshraf97 requested changes

2023-08-20 23:04 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +        result = paddle.cast(result, dtype)
as per function documentation, casting should be before calculation, unless its an unsupported dtype

2023-08-20 23:04 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +        return out
this should be handled automatically using `handle_out_argument` decorator, no need to handle it

2023-08-20 23:04 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/statistical.py
> +    dtype: Optional[str] = None,
please keep the function signature unchanged and consistent across all backends

2023-09-12 10:43 UTC, closed without merging