Added index_select to paddle frontend search mod
unifyai/ivy pull request #20841
Opened 2023-07-26 06:14 UTC by nikita-jare

Close #20840

Added index_select to paddle frontend search module

2023-07-26 08:21 UTC, AryanSharma21 reviewed
Hello, @nikita-jare , as per the test result, there is some argument error in the function that you have implemented. 
Please check by your side .

E   TypeError: index_select() got multiple values for argument 'index'

2023-08-12 16:23 UTC, rishabgit requested changes
Hi, thanks for looking into this. Getting this error on testing - 
```
TypeError: index_select() got multiple values for argument 'index'
```
I looked through your code and couldn't find anything wrong - except for hard-coding array shapes (added comment). Could you try syncing this branch with latest updates?

Feel free to re-request review after fixing, thanks! 😄

2023-08-12 16:24 UTC, rishabgit commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_search.py
> +        max_num_dims=1,
this would hard-code shape of inputs too which isn't ideal

2023-10-24 15:22 UTC, rishabgit commented
This PR has been closed because it has been stale for more than 7 days with no activity.

2023-10-24 15:22 UTC, closed without merging