Add cbrt to jax frontend api with test
unifyai/ivy pull request #20876
Opened 2023-07-27 02:18 UTC by Sjsingh101

2023-07-28 03:30 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_operators.py
> +        available_dtypes=helpers.get_dtypes("numeric")
```suggestion
        available_dtypes=helpers.get_dtypes("valid")
```
Valid automatically determines the supported dtypes for the function.

2023-07-28 03:31 UTC, hello-fri-end requested changes
Hey @Sjsingh101 ! Thanks for creating this PR. Just left a minor comment. Feel free to request another review when you have resolved it :smile:

2023-07-29 13:40 UTC, Sjsingh101 commented
Hi @hello-fri-end, I have updated the PR but many other test (like `test_jax_square`, `test_jax_add`, `test_jax_sub`, etc) operate on similar input types and have "numeric" dtypes. Should I update them as well?

2023-08-02 15:10 UTC, hello-fri-end requested changes

2023-08-02 15:10 UTC, hello-fri-end commented on ivy/functional/frontends/jax/lax/operators.py
> +def cbrt(x):
Can you add the `/` argument here as it's present in the `jax.cbrt` function here :https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.cbrt.html

2023-08-03 02:06 UTC, hello-fri-end approved these changes
Looks like the tests are passing now. Merging this :rocket: Thanks for the contribution :partying_face:

2023-08-03 02:06 UTC, hello-fri-end commented on ivy/functional/frontends/jax/lax/operators.py
> +def cbrt(x):
Oh awesome, thanks for the explanation  :fire:

2023-08-03 02:07 UTC, merged