nanquantile
unifyai/ivy pull request #20888
Opened 2023-07-27 08:38 UTC by aryankhatana01

2023-07-27 09:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-07-27 10:40 UTC, sherry30 requested changes
Requested 2 changes, can you get the tests to pass for this function.

Also its weird that there was no test for `nanquantile` in the experimental API, Thanks for adding that too 😄

2023-07-27 10:40 UTC, sherry30 commented on ivy/functional/frontends/torch/reduction_ops.py
> +nanquantile.unsupported_dtypes = {
You're only supposed to point out the unsupported dtypes for this frontend function. (The dtypes not supported by the function of the original framework)
So just `"torch": ("float16", "bfloat16")` would do.

The unsupported dtypes for the backend are determined by the test function itself

2023-07-27 10:40 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py
> +    _quantile_helper, _nanquantile_helper
Its giving an error `ImportError: cannot import name '_nanquantile_helper'`

2023-07-28 09:42 UTC, sherry30 requested changes
1 change requested

2023-07-28 09:42 UTC, sherry30 commented on ivy/functional/frontends/torch/reduction_ops.py
> +    "torch": ("float16", "bfloat16"),
Actually can you add this as a decorator on the function.
```
@with_unsupported_dtypes(
    {"2.0.1 and below": ("float16", "bfloat16")}, "torch"
)
```
Sorry for making you change this the 2nd time 😅

2023-07-31 11:43 UTC, sherry30 requested changes
Requested 1 change.

Can you get the test passing if they fail after that.
Feel free to ask me anything if you get stuck. 😄 

Thanks

2023-07-31 11:43 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_statistical.py
> +    *, dtype_and_x, keep_dims, test_flags, backend_fw, fn_name, on_device
`dtype_and_x` should be `dtype_x_axis` because that's how its defined above

2023-08-02 07:10 UTC, sherry30 requested changes
Pointed out 1 thing.
You can check the intelligent tests run in this PR and see if the tests are failing and you can see the failure. You'll get a good understanding of why is it failing form that.

Thanks

2023-08-02 07:10 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py
> +        input=x[0],
you're also supposed to generate and pass the other arguments here as well.
`q`, `interpolation` etc.
All argument should be covered

2023-08-04 08:44 UTC, sherry30 requested changes
Hi,

So one thing I realized, there is no backend implementation of `ivy.nanquantile` 😅, its just a hollow function with no implementation, This is a mistake on our end, I'll create a task for this and someone from the engineering team can look into it.
I'll merge your PR since you've written tests and torch frontend function is just supposed to call `ivy.nanquantile`.
 I've requested 1 change, I'll merge it after you've made that change
 Thanks

2023-08-04 08:44 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_statistical.py
> +        keepdims=keep_dims,
`keepdims` comes before `interpolation` in `ivy.nanquantile`

2023-08-07 08:21 UTC, merged