Formatted floormod
unifyai/ivy pull request #2090
Opened 2022-07-20 05:02 UTC by kylejcharlton

[#2082](https://github.com/unifyai/ivy/issues/2082)

2022-07-20 08:57 UTC, rush2406 requested changes
Hi @kylejcharlton 
Thanks for the great work! There are minor changes required to the docstring, pleae check the comments. You can re-request review once it's done and I'll merge it

2022-07-20 10:57 UTC, kylejcharlton commented
Hey @rush2406, I went ahead and made those changes to better reflect the container implementation. Let me know if everything looks good :)

2022-07-20 12:23 UTC, rush2406 requested changes

2022-07-20 12:23 UTC, rush2406 commented on ivy/array/general.py
> +        >>> a.floormod(b, c)
this should be `a.floormod(b,out=c)`. The keyword `out` is required otherwise the doctring tests are failing.

2022-07-20 13:12 UTC, rush2406 requested changes

2022-07-20 13:12 UTC, rush2406 commented on ivy/functional/ivy/general.py
> +    >>> c = ivy.native_array([0, 0, 0])
`out` is not supported with `ivy.native_array`, so ideally you can remove this example

2022-07-25 00:35 UTC, kylejcharlton commented
Hey @rush2406, I made those changes that you suggested and it appears that I am now passing the linting tests. Let me know if there's anything else for me to take care of :)

2022-07-25 13:03 UTC, rush2406 requested changes

2022-07-25 13:03 UTC, rush2406 commented on ivy/functional/ivy/general.py
> +    >>> ivy.floormod(a, b, out=b)
here the `out` argument should of type container, so please change it to `out=a`

2022-07-25 13:05 UTC, rush2406 commented
@kylejcharlton thanks for doing the changes, can you please check the `test-docstrings / run-docstring-tests` in this PR. It seems to be failing for a few examples

2022-08-04 00:00 UTC, closed without merging