Loss function for multilabel_soft_margin_loss in paddle frontend
unifyai/ivy pull request #20909
Opened 2023-07-27 18:51 UTC by Indraneel99

Close #20797

2023-07-27 19:29 UTC, Indraneel99 commented
Hi team,

Some checks are failing (2 in 128), does this mean I am missing edge cases? Please let me know where can i find crash log ( I am unable to find it 😟). 

I will update the formatting. Thanks

2023-08-01 03:07 UTC, hirwa-nshuti requested changes
Hey @Indraneel99 

I tried to run your tests locally and I'm getting the following errors
![image](https://github.com/unifyai/ivy/assets/67042527/f1112ed3-ea71-4251-82e9-e1b0f8512e63)

Would you check it out and the comments I left below🙂

2023-08-01 03:07 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_loss.py
> +        exclude_min=True,
I believe that we can add this if we set the bounds of both `max` and `min` values of arrays to be generated

2023-08-06 10:33 UTC, hirwa-nshuti requested changes
Hey I added a few comments to help you run tests successfully for you to debug the failing tests

2023-08-06 10:33 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_loss.py
> +        input_dtypes=[
This parameter is supposed to be a list, not a nested list, you can concatenate both `x_dtype` and `weight_dtype` lists

2023-08-06 10:33 UTC, hirwa-nshuti commented on ivy/functional/frontends/paddle/nn/functional/loss.py
> +def multilabel_soft_margin_loss(input, label, weight=None, reduction='mean', name=None):
Function name is written incorrectly would you rename it to `multi_label_soft_margin_loss`

2023-08-06 10:33 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_loss.py
> +    fn_tree="paddle.nn.functional.multilabel_soft_margin_loss",
The function should also be `multi_label_soft_margin_loss`

2023-08-08 10:42 UTC, Indraneel99 commented
Hi @hirwa-nshuti , Thanks for the review and comments. I have changed the function name to multi_label_soft_margin_loss and updated the code. All Tests are passing locally, but it seems some checks are failing in GitHub. please help me with the failing checks. Thanks

2023-08-11 06:31 UTC, hirwa-nshuti requested changes
Would you also try tp fix the merge conflicts so I can be able to run the tests locally😊
Thanks

2023-08-11 07:01 UTC, Indraneel99 commented
> Would you also try tp fix the merge conflicts so I can be able to run the tests locally😊 Thanks

I have resolved the conflicts. Please look into it. Thanks ☺️

2023-08-16 09:44 UTC, hirwa-nshuti requested changes
Hey @Indraneel99 

Good job so far 😊
There are assertion errors in backends would you look into this🙂
Thanks

2023-08-16 09:44 UTC, hirwa-nshuti commented on ivy/functional/frontends/paddle/nn/functional/loss.py
> +def nll_loss(
This should be removed as it was redefined from above

2023-08-16 19:57 UTC, Indraneel99 commented
Hey @hirwa-nshuti, Thanks for reviewing (sorry for the earlier mistakes 😢 ). I have updated the function and now all tests are passing locally. Please check it. Thanks 😄.

2023-08-29 04:06 UTC, hirwa-nshuti requested changes
Hey @Indraneel99 

Sorry for getting back to you this late 🙂
Would you resolve these merge conflicts so that the CI check should run
Thanks!

2023-09-11 06:27 UTC, Indraneel99 commented
Hey @hirwa-nshuti . I have resolved the conflicts. Please check the code. Thanks.

2023-09-11 14:49 UTC, hirwa-nshuti approved these changes
Hey @Indraneel99 

All looks great to me 😊
Thanks for contributing

2023-09-11 14:50 UTC, merged

2023-09-11 17:51 UTC, Indraneel99 commented
Hey @hirwa-nshuti . Thanks for all the help 🙂.