add a section for ivy-gardener in deep dive document
unifyai/ivy pull request #20931
Opened 2023-07-28 01:05 UTC by Daniel4078

2023-07-28 08:15 UTC, KareemMAX requested changes
Looks great, but can you mention as well that the same notes you wrote also apply to our scheduled linting bot which run every day at 8:00 UTC? Both actually share the same code, with `ivy-gardener` just runs on the changed files in a PR, the scheduled lint bot works on all files on `master`

2023-07-31 15:03 UTC, KareemMAX requested changes
One small nitpick, let me know what you think

2023-08-01 21:05 UTC, KareemMAX requested changes
That would be misleading, when `ivy-gardener` shows an error that it failed it will always be a permission issue.

If there are errors that need human intervention, `ivy-gardener` will pass, but the linting check will fail.

Can you please change that?

2023-08-04 10:55 UTC, KareemMAX requested changes
Hey @Daniel4078,
Here are some nitpicks. I'll leave them to you if you think they are not necessary please let me know and ask for a review afterwards.

Thank you so much

2023-08-04 10:55 UTC, KareemMAX commented on docs/overview/deep_dive/formatting.rst
> +should check the logs of lint checks to manually resolve the formatting errors by commiting the changes yourself.
Here, you can simply give the maintainers access (this is an option in GitHub UI)

2023-08-04 10:55 UTC, KareemMAX commented on docs/overview/deep_dive/formatting.rst
> +by the linters and by the lint checks that runs later, while the fixes for other normal errors will still be applied
They are all errors, I believe normal is a bit inaccurate

```suggestion
by the linters and by the lint checks that runs later, while the fixes for other errors will still be applied 
```

2023-08-04 10:55 UTC, KareemMAX commented on docs/overview/deep_dive/formatting.rst
> +However, it is possible for the linters run in the ivy-gardener and the github action every day to face formatting
```suggestion
However, it is possible for the linters run in the ``ivy-gardener`` and the GitHub action every day to face formatting 
```

2023-08-04 10:55 UTC, KareemMAX commented on docs/overview/deep_dive/formatting.rst
> +as the ivy-gardener is passing properly.
```suggestion
as the ``ivy-gardener`` is passing properly.
```

2023-08-04 10:55 UTC, KareemMAX commented on docs/overview/deep_dive/formatting.rst
> +On the other hand, ivy-gardener itself can fail if the bot handling it (ivy-branch) can not apply the changes
```suggestion
On the other hand, ``ivy-gardener`` itself can fail if the bot handling it (ivy-branch) can not apply the changes 
```

2023-08-05 00:28 UTC, Daniel4078 commented
@KareemMAX Done, I suppose it is pretty much done right?

2023-08-05 09:05 UTC, KareemMAX approved these changes
LGTM! Merging now

2023-08-05 09:05 UTC, merged