Fix map_raw_ops_alias wrapping the source function without wraps decorator causing unsupported dtypes not showing
unifyai/ivy pull request #20965
Opened 2023-07-28 16:18 UTC by fabriziocacicia

Fix #20963

2023-08-15 01:58 UTC, CatB1t requested changes

2023-08-15 01:58 UTC, CatB1t commented on ivy/functional/frontends/tensorflow/func_wrapper.py
> +        _wraped_fn.__alias__ = {fn.__name__: fn}
Does it have to be stored as a dictionary?

2023-08-15 01:58 UTC, CatB1t commented on ivy/functional/frontends/tensorflow/func_wrapper.py
> +        new_module = inspect.stack()[2][0].f_globals["__name__"]
What does this line here exactly do? it seems unclear, is it retrieving the current module?

2023-08-15 01:58 UTC, CatB1t commented on ivy/functional/ivy/data_type.py
> +    if hasattr(func, "__alias__"):
Is this addition required?

2023-10-03 20:15 UTC, Daniel4078 commented
This PR is closed due to inactivity for too long.

2023-10-03 20:15 UTC, closed without merging