feat: add round_ to jax.numpy
unifyai/ivy pull request #20968
Opened 2023-07-28 17:52 UTC by OzMoti

close #20967

2023-08-04 04:22 UTC, kurshakuz requested changes

2023-08-04 04:22 UTC, kurshakuz commented on ivy/functional/frontends/jax/numpy/mathematical_functions.py
> +    return ivy.round(a, decimals=decimals, out=out)
Hey! I have tested the implementation locally and it seems to be failing for the `AssertionError`. Can you please resolve it?
```
E       AssertionError:  the results from backend paddle and ground truth framework jax do not match
E        32768!=48896 
```
```
E       AssertionError:  the results from backend tensorflow and ground truth framework jax do not match
E        -inf!=-1.0 
```
```
E       AssertionError:  the results from backend numpy and ground truth framework jax do not match
E        -inf!=-1.0 
```

2023-08-08 06:13 UTC, OzMoti commented
Would you please give me or give me a clue on how to solve this issue ? I couldn't find the solution.

2023-12-26 18:02 UTC, NiteshK84 commented
Hello @OzMoti, I apologize for the lack of response from the Ivy team regarding your PR. Would you mind resolving the merge conflicts first? Afterward, we can address any implementation failures that may have occurred.

2024-01-31 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-25 05:53 UTC, closed without merging

2024-02-25 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.