chore: add svd to paddle linalg
unifyai/ivy pull request #21007
Opened 2023-07-29 21:07 UTC by a0m0rajab

closes #17843

2023-08-01 12:39 UTC, abdulasiraj commented
Hi @a0m0rajab,
Please resolve the conflicts!
Thanks!

2023-08-01 12:40 UTC, abdulasiraj commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +    class_tree=CLASS_TREE,
here you should write the function name not the CLASS_TREE

2023-08-01 13:22 UTC, a0m0rajab commented
@abdulasiraj conflict resolved.

2023-08-07 04:46 UTC, abdulasiraj commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
Hi @a0m0rajab,
Thanks for great work. just one quick thing, please add the test for this in `test_linalg.py` file. Thanks!

2023-08-07 04:47 UTC, abdulasiraj requested changes
requested review!

2023-08-08 22:21 UTC, a0m0rajab commented
Thanks, the file moved.

2023-08-09 04:21 UTC, abdulasiraj requested changes

2023-08-09 04:21 UTC, abdulasiraj commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_linalg.py
> +@handle_frontend_method(
It should be like `handle_frontend_test` and also you've to change the parameters accordingly. Also please make sure, All tests are being passed. Thanks!

2023-09-25 11:49 UTC, Aarsh2001 commented
Hey @a0m0rajab, closing this PR due to inactivity, feel free to reopen once you're done with your changes. Thanks

2023-09-25 11:49 UTC, closed without merging