added the hinge_embedding_loss
unifyai/ivy pull request #21077
Opened 2023-07-31 07:27 UTC by sushmanthreddy

close #21076

2023-08-02 05:51 UTC, sushmanthreddy commented
@MahmoudAshraf97 can u pls review th pulll request pls??

2023-08-18 08:16 UTC, sushmanthreddy commented
@MahmoudAshraf97 @YushaArif99 can u pls review my pull request, i have added the support for hinge_embeddding_loss ,and tests are passing in local system and the sc is attached over here..pls review and let me knew any changes are needed.

2023-08-19 21:01 UTC, sushmanthreddy commented
checked supporting datatypes by this method
![Screenshot from 2023-08-20 02-30-25](https://github.com/unifyai/ivy/assets/73489688/8db229fc-25bc-49a3-997e-7115bbe532cf)

2023-08-20 12:04 UTC, MahmoudAshraf97 requested changes
Hello @sushmanthreddy , the function argument should be unified across all backends and still satisfy the superset behaviour, please address the issues mentioned in the review

2023-08-20 12:04 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +        available_dtypes=helpers.get_dtypes("int"),
revert this change

2023-08-20 12:04 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +        min_dim_size=3,
remove these unnecessary constraints, the test should be as unconstrained as possible
```suggestion

```

2023-08-20 12:04 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +        min_dim_size=3,
```suggestion

```

2023-08-20 12:04 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +    ),
you can also generate two arrays with the same strategy instead of having two strategies

2023-08-20 12:04 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +    test_with_out=st.just(False),
why is this hardcoded to false?
```suggestion
```

2023-08-20 12:04 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
please address the concerns in the testing review, also add testing for reduction argument

2023-08-20 14:50 UTC, sushmanthreddy commented
@MahmoudAshraf97 I have implemented the changes u have mentioned.And ,I have  added the reduction parameter too in test file.It just got out of sight.
And after reading superset behaviour ,have understood the backend implementation too ,and removed unecessary parameters which are not present in other backends.
One strategy have true labels and other have targets which are binary  1 and -1 ,so it better to have two different strategies ,now tests are passing.can u pls review it ,if changes are needed pls let me knew otherwise pls merge it

2023-08-20 14:58 UTC, sushmanthreddy commented
![Screenshot from 2023-08-20 20-28-08](https://github.com/unifyai/ivy/assets/73489688/b151d9ee-06ed-49d9-afe4-686ab41a4aca)
tests passing screenshot

2023-08-20 22:40 UTC, MahmoudAshraf97 requested changes

2023-08-20 22:40 UTC, MahmoudAshraf97 commented on ivy/functional/backends/paddle/experimental/losses.py
> +        out=out,
paddle function doesn't have an out argument

2023-08-20 22:40 UTC, MahmoudAshraf97 commented on ivy/functional/backends/torch/experimental/losses.py
> +        out=out,
torch function doesn't have an out argument

2023-08-20 22:40 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +        rtol_=1e-2,
this is a relatively high tolerance please remove it

2023-08-21 20:16 UTC, MahmoudAshraf97 requested changes
Hi, please remove all tolerances not just relative
the out argument doesn't exist in the frameworks but it should stay in the function signature, please check how `handle_out_argument` works and make sure it wraps the main function

2023-09-18 05:16 UTC, closed without merging

2023-09-18 05:16 UTC, YushaArif99 commented
Hi, @sushmanthreddy. I'll be closing this PR has it has been inactive for over a month now. Thanks! 🙂