completed issue map_nest_at_indices #2104
unifyai/ivy pull request #2112
Opened 2022-07-20 17:37 UTC by am02785

2022-07-20 17:46 UTC, am02785 commented
This pull request resolves the issue map_nest_at_indices #2104,

Thank you

2022-08-04 08:13 UTC, sherry30 requested changes
Hi, 

Sorry for the late review, this PR flew under my radar,
Can you resolve the conflicts and also look into why the docstring is failing for this function.
Feel free to ask for any help ,I'd be happy to answer any question.

Thanks.

2022-08-16 18:26 UTC, am02785 commented
Hi sherry30, thank you for the message. I will try to resolve the conflicts and fix the docstring.

2022-08-17 16:38 UTC, am02785 commented
![image](https://user-images.githubusercontent.com/61350523/185195156-aaaf16d1-d1d6-48a2-b066-3d9f618ec79f.png)

2022-08-18 15:45 UTC, am02785 commented
@sherry30 I have fixed the earlier error by replacing set_nest_at_indices with map_nest_at_indices, however I'm getting a new error and I'm not sure why: 
![image](https://user-images.githubusercontent.com/61350523/185437760-021794b7-a2cf-4383-ba63-3d2c9e73825a.png)

The following is part of the docstring: 
![image](https://user-images.githubusercontent.com/61350523/185437978-92ac2a10-ef80-47cc-a231-1c49336ea5c0.png)

2022-08-18 16:40 UTC, am02785 commented
The example seems to work fine when I use docker: 
![image](https://user-images.githubusercontent.com/61350523/185448807-e25efdcf-13b9-43be-98c8-473b0100571f.png)

2022-08-19 13:15 UTC, sherry30 requested changes
Hi,

So i did some debugging and found out that you cannot use the argument `fn`, can you change its name to something else like, `fnn`, this argument is being used by our `docstring_test` function and it was being over written thats why it was giving the error.

Thanks.

2022-08-19 13:15 UTC, sherry30 commented on ivy/functional/ivy/nest.py
> +    >>> ivy.map_nest_at_indices(nest, indices, fn)
replace `fn` with `values`

2022-08-19 13:15 UTC, sherry30 commented on ivy/functional/ivy/nest.py
> +    >>> fn = lambda x : x + 'b'
change `fn` to something else

2022-08-19 13:15 UTC, sherry30 commented on ivy/functional/ivy/nest.py
> +    >>> fn = abs
change `fn`

2022-08-19 13:15 UTC, sherry30 commented on ivy/functional/ivy/nest.py
> +    >>> fn = lambda x : x + 1
change `fn`

2022-08-19 17:55 UTC, am02785 commented
@sherry30 Thank you for the response, I changed the name of the argument fn to function. I think that fixed the errors.

2022-08-22 12:58 UTC, merged