Chore: add addmv_ to tensor
unifyai/ivy pull request #21200
Opened 2023-08-02 16:15 UTC by a0m0rajab

Closes https://github.com/unifyai/ivy/issues/20959

@hirwa-nshuti closed the PR since I broke the Git history.

Previous review: https://github.com/unifyai/ivy/pull/20998

2023-08-03 08:48 UTC, hirwa-nshuti requested changes
Hey @a0m0rajab 

Thanks for making the requested changes😊
I added a few suggestions after they're added will get the PR merged.
Thanks🙂

2023-08-03 08:48 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +    on_device,
```suggestion
    on_device,
    backend_fw,
```
There is a missing fixture for backend to test

2023-08-03 08:48 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +        method_input_dtypes=input_dtype,
```suggestion
        method_input_dtypes=input_dtype,
        backend_to_test=backend_fw,
```
This argument was missing

2023-08-03 08:48 UTC, hirwa-nshuti commented on ivy/functional/frontends/torch/tensor.py
> +        self.ivy_array = torch_frontend.addmv(self, mat, vec, beta=beta, alpha=alpha)
Here we need to ensure that we are assigning `self.ivy_array` to correct `ivy.Array` instance
```suggestion
        self.ivy_array = torch_frontend.addmv(self, mat, vec, beta=beta, alpha=alpha).ivy_array
```

2023-08-03 08:50 UTC, a0m0rajab commented
@hirwa-nshuti, thanks for that, I just applied the suggestions.

2023-08-03 09:41 UTC, a0m0rajab commented
Here is the failing test logs, @hirwa-nshuti what's your input on this?
```logs
ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py::test_torch_addmv_,numpy
****************************************************************************************************

ImportError while loading conftest '/ivy/ivy_tests/test_ivy/conftest.py'.
ivy_tests/test_ivy/conftest.py:7: in <module>
    import ivy_tests.test_ivy.helpers.test_parameter_flags as pf
ivy_tests/test_ivy/helpers/__init__.py:2: in <module>
    from . import hypothesis_helpers
ivy_tests/test_ivy/helpers/hypothesis_helpers/__init__.py:1: in <module>
    from . import general_helpers
ivy_tests/test_ivy/helpers/hypothesis_helpers/general_helpers.py:8: in <module>
    import ivy
ivy/__init__.py:770: in <module>
    from . import stateful
ivy/stateful/__init__.py:1: in <module>
    from . import activations
ivy/stateful/activations.py:5: in <module>
    from ivy.stateful.module import Module
ivy/stateful/module.py:8: in <module>
    import dill
E   ModuleNotFoundError: No module named 'dill'
Error: Process completed with exit code 1.
```

2023-08-03 09:43 UTC, a0m0rajab commented
I did not use such `dill` module in my PR.

2023-08-06 09:56 UTC, hirwa-nshuti commented
> Here is the failing test logs, @hirwa-nshuti what's your input on this?
> 
> ```
> ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py::test_torch_addmv_,numpy
> ****************************************************************************************************
> 
> ImportError while loading conftest '/ivy/ivy_tests/test_ivy/conftest.py'.
> ivy_tests/test_ivy/conftest.py:7: in <module>
>     import ivy_tests.test_ivy.helpers.test_parameter_flags as pf
> ivy_tests/test_ivy/helpers/__init__.py:2: in <module>
>     from . import hypothesis_helpers
> ivy_tests/test_ivy/helpers/hypothesis_helpers/__init__.py:1: in <module>
>     from . import general_helpers
> ivy_tests/test_ivy/helpers/hypothesis_helpers/general_helpers.py:8: in <module>
>     import ivy
> ivy/__init__.py:770: in <module>
>     from . import stateful
> ivy/stateful/__init__.py:1: in <module>
>     from . import activations
> ivy/stateful/activations.py:5: in <module>
>     from ivy.stateful.module import Module
> ivy/stateful/module.py:8: in <module>
>     import dill
> E   ModuleNotFoundError: No module named 'dill'
> Error: Process completed with exit code 1.
> ```

Try to rebuild your container as this dependency was added recently

2023-08-06 09:57 UTC, hirwa-nshuti approved these changes
Hey @a0m0rajab 

All looks great now 🙂
Going to merge😊

2023-08-06 09:58 UTC, merged

2023-08-06 10:20 UTC, a0m0rajab commented
Thank you for the merge!