tensor math.py func
unifyai/ivy pull request #21257
Opened 2023-08-03 17:48 UTC by TangoIndiaMango

Close #21205
Close #21204
Close #21203

2023-08-07 09:51 UTC, KareemMAX requested changes
Hey @TangoIndiaMango,

Seems like you forgot to add unit tests. also both `add_n` and `erfinv` doesn't seem like they exist in Ivy for now. Are you sure this code is runnable?

Also to streamline the review process. Can you make a comment with "add_frontend_checklist" (with no quotes nor any spaces or new lines)? When you do that a checklist will appear which we use to make sure that your PR is good to merge. Please tick anything in it that you feel you have completed

2023-08-07 09:51 UTC, KareemMAX commented on ivy/functional/frontends/paddle/tensor/math.py
> -
Seems like you forgot to revert this change, which breaks our linting rules

2023-08-08 06:20 UTC, KareemMAX requested changes
I guess you removed `diff()` in the process of updating your PR, please revert that back.

Also the tests are still missing, please refer to our [open tasks guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis)

2023-08-08 11:23 UTC, TangoIndiaMango commented
add_frontend_checklist

2023-08-14 14:40 UTC, closed without merging