Add cummin to jax frontend api with test
unifyai/ivy pull request #21349
Opened 2023-08-05 23:30 UTC by Sjsingh101

2023-08-06 00:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-07 06:27 UTC, hello-fri-end requested changes

2023-08-07 06:27 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_operators.py
> +        available_dtypes=helpers.get_dtypes("numeric"),
Let's change this to valid.

2023-08-15 14:08 UTC, hello-fri-end approved these changes
LGTM! :rocket:

2023-08-15 14:08 UTC, merged