Add softsign to tensorflow frontend api with test
unifyai/ivy pull request #21352
Opened 2023-08-06 00:57 UTC by Sjsingh101

2023-08-07 06:31 UTC, hello-fri-end requested changes
Hey @Sjsingh101 ! Feel free to request another review when you have resolved the comment.

2023-08-07 23:01 UTC, Sjsingh101 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +    dtype_and_x=helpers.dtype_and_values(
This function supports `half, bfloat16, float32, float64`. Therefore, I have updated it with `available_dtypes=helpers.get_dtyeps("float")` and added exception for paddle.

2023-08-08 03:20 UTC, hello-fri-end requested changes

2023-08-08 03:20 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +    dtype_and_x=helpers.dtype_and_values(
In this case, you should add the `supported_dtypes` decorator to the function with these float datatypes and change `available_dtypes` to `available_dtypes=helpers.get_dtyeps("valid")`. As for paddle not supporting `bfloat16`, the backend implementation of `ivy.divide` already takes care of it : https://github.com/unifyai/ivy/blob/master/ivy/functional/backends/paddle/elementwise.py#L442

2023-08-11 11:25 UTC, hello-fri-end approved these changes
LGTM! :rocket:

2023-08-11 11:26 UTC, merged