Adds paddle grid_sample for spatial transformation and paddle floor_mod
unifyai/ivy pull request #21380
Opened 2023-08-06 19:31 UTC by Angel-ica

Hi, please review the following:
- [ ] #20198 

- [ ] #21377  

This is my first contribution to the project and I'm eager to learn and improve (especially with the grid_sample function as i found it challenging).  
Any feedback and guidance would be greatly appreciated.

2023-08-06 20:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-20 23:09 UTC, MahmoudAshraf97 requested changes

2023-08-20 23:09 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/vision.py
> +    """
we don't add docstrings to frontend functions

2023-08-20 23:09 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/vision.py
> +    """
please remove the docstring and rename the function to reflect it's private nature

2023-08-20 23:09 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/vision.py
> +    """
please remove the docstring and rename the function to reflect it's private nature

2023-08-20 23:09 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_vision.py
please take a look on how frontend tests are implemented, this implementation is not correct

2023-08-25 02:43 UTC, Angel-ica commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_vision.py
Hi Mahmoud! Thank you for your feedback, I've removed all docstrings and reattempted the tests. 
Please review the new changes.

2023-08-27 09:48 UTC, MahmoudAshraf97 requested changes

2023-08-27 09:48 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/vision.py
> +def grid_sample(input, grid, mode, padding_mode):
the fronend function signature must match the native framework function

```suggestion
def grid_sample(
    x,
    grid,
    mode='bilinear',
    padding_mode='zeros',
    align_corners=True,
    name=None,
):
```

2023-08-27 09:48 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/vision.py
> +def grid_sample_nearest(input, grid, padding_mode):
please rename to reflect its private nature

2023-08-27 09:48 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/nn/functional/vision.py
> +def grid_sample_bilinear(input, grid, padding_mode):
rename

2023-08-27 09:48 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/tensor/math.py
please revert all the code that is not related to your PR

2023-08-27 09:48 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_vision.py
you need to write the test for the main function, not the two helpers

2023-09-12 10:44 UTC, closed without merging