added indices function to jax frontend
unifyai/ivy pull request #21382
Opened 2023-08-06 21:40 UTC by JeffreyJu8

close #21163

2023-08-07 22:58 UTC, JeffreyJu8 commented
How should I go about resolving the New Failures Introduced errors?

2023-08-08 08:41 UTC, sherry30 requested changes
Requested a few changes, the rest looks good

Thanks

2023-08-08 08:41 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_indexing.py
> +    # *,
uncomment this

2023-08-08 08:41 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_indexing.py
> +    dtype=helpers.get_dtypes(),
You can pass `"numeric"` in the `heleprs.get_dtypes` method because by default it is `"valid"` an that also produces `bool`

2023-08-09 17:27 UTC, JeffreyJu8 commented
> 

It seems like the test is successful sometimes and unsuccessful other times. When I ran it on my local machine, I passed most times.

 `test_indexing.py::test_jax_numpy_indices[cpu-numpy-False-False] 
test_indexing.py::test_jax_numpy_indices[cpu-jax-False-False] 
test_indexing.py::test_jax_numpy_indices[cpu-tensorflow-False-False] 
test_indexing.py::test_jax_numpy_indices[cpu-torch-False-False] 
test_indexing.py::test_jax_numpy_indices[cpu-paddle-False-False] 

======================== 5 passed, 34 warnings in 7.07s ========================
PASSED   [ 20%]PASSED     [ 40%]PASSED [ 60%]PASSED   [ 80%]PASSED  [100%]
Process finished with exit code 0`

Is this still something to worry about?

2023-08-10 11:25 UTC, JeffreyJu8 commented
Can this PR be closed?

2023-08-11 12:29 UTC, sherry30 approved these changes
Yea seems to be passing, not sure why it failed previously 🤔 

either way, thanks for the contribution 😄

2023-08-11 12:29 UTC, merged

2023-08-11 16:02 UTC, JeffreyJu8 commented
> Yea seems to be passing, not sure why it failed previously 🤔
> 
> either way, thanks for the contribution 😄

My pleasure!