implemented Igamma
unifyai/ivy pull request #21393
Opened 2023-08-07 05:53 UTC by ShoaibMajidDar

2023-08-07 05:53 UTC, ShoaibMajidDar commented
Close #21392

2023-08-07 06:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-12 07:32 UTC, ShoaibMajidDar commented
hi @hmahmood24 can you please review this PR

2023-08-13 09:42 UTC, hmahmood24 requested changes
Hey @ShoaibMajidDar, apologies for they delay and thanks for the PR. Everything looks good to me. Just suggested a minor change. Thanks!

2023-08-13 09:42 UTC, hmahmood24 commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +    return ivy.igamma(a, x=x)
For this, you need to map this to the alias in the `math` submodule like so:
```python
to_ivy_arrays_and_back(
    (map_raw_ops_alias(tf_frontend.math.igamma))
)
```

2023-08-16 05:21 UTC, ShoaibMajidDar commented
Hi @hmahmood24 I have done the changes asked by you

2023-08-16 07:28 UTC, hmahmood24 commented
> Hi @hmahmood24 I have done the changes asked by you

Hi @ShoaibMajidDar, did you run your tests locally first? They are failing in the CI: https://github.com/unifyai/ivy/actions/runs/5874979109/job/15930549822?pr=21393. Can you fix those? Probably has to do with unsupported dtypes that need to be added

2023-08-16 07:29 UTC, hmahmood24 requested changes
We'll need to have the tests passing first in order to merge the PR

2023-08-16 09:12 UTC, ShoaibMajidDar commented
@hmahmood24 I have resolved the errors, please review the PR.

2023-08-17 06:27 UTC, hmahmood24 approved these changes
@ShoaibMajidDar Everything looks good now. Thanks for the PR! 🚀

2023-08-17 06:28 UTC, merged