Reformat asin #2045
unifyai/ivy pull request #2139
Opened 2022-07-21 05:33 UTC by vineel96

Made changes to asin function, please review. issue: #2045

2022-07-24 15:52 UTC, RickSanchezStoic commented
@vineel96 Kindly look through the changes that I have requested and let me know if you have any doubts, thanks!

2022-07-25 11:25 UTC, RickSanchezStoic requested changes

2022-07-30 11:05 UTC, vineel96 commented on ivy/container/elementwise.py
> +        }
@RickSanchezStoic  I have mage changes to all 3 requested changes, please check

2022-08-01 06:14 UTC, RickSanchezStoic commented
@vineel96 please fix the `lint` errors. It the lambda function `asin` needs to be removed in mxnet.

2022-08-02 18:49 UTC, vineel96 commented
@RickSanchezStoic I have fixed the lint errors, please check

2022-08-03 05:27 UTC, RickSanchezStoic commented
@vineel96 We shouldn't make any changes to any files or folders within `.idea`. Can you please fix that? Otherwise, everything looks good!

2022-08-03 05:29 UTC, RickSanchezStoic requested changes
Kindly make the requested change and then we can merge it.

2022-08-03 09:26 UTC, vineel96 commented
@RickSanchezStoic I have fixed the issue, please check

2022-08-04 06:14 UTC, RickSanchezStoic commented
Looks good!

2022-08-04 06:16 UTC, merged