add jax.numpy.lexsort and corresponding tests
unifyai/ivy pull request #21404
Opened 2023-08-07 10:42 UTC by illia-bab

Close #21403

2023-08-14 15:15 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-16 18:16 UTC, zaeemansari70 commented on ivy/functional/backends/paddle/experimental/sorting.py
> +    if keys.dtype in [
Why are we upcasting these? :slightly_smiling_face: 
Can't we handle this by adding the `unsupported_dtypes` decorators above this function?

2023-08-22 06:59 UTC, zaeemansari70 requested changes
Just required a small change

2023-08-22 06:59 UTC, zaeemansari70 commented on ivy/functional/backends/paddle/experimental/sorting.py
> +    if keys.dtype in [
According to our discussion as the dtypes suppported by this are `[int32, int64, float32, float64]`. Adding a logic here where we upcast to the closest possible `dtype` would make more sense I guess, what you can do is upcast to `float32` if its a float `dtype` and similarly cast to a closest `int` `dtype` if we get an unsupprted `int` dtype. We will actually be handling a broader set in this way. 
Hope that makes sense :+1:

2023-08-22 07:59 UTC, zaeemansari70 commented
Also, @MahmoudAshraf97 can you take a last look at this as this is related to the paddle backend as also the dtypes handling in paddle backend specifically. 
Thanks!

2023-08-22 16:32 UTC, MahmoudAshraf97 requested changes
Hello, the new change in the paddle backend doesn't ensure that the returned dtype is the same as the input, please make sure the tests for the functional function is passing in the paddle backend

2023-08-30 14:44 UTC, closed without merging