add ifftshift + tests to jax frontend
unifyai/ivy pull request #21431
Opened 2023-08-07 18:12 UTC by hnhparitosh

Greetings!
Added ifftshift to jax frontend. Please review the PR and let me know if any changes are needed.
🙂
This PR will close #21131

2023-08-18 08:04 UTC, hnhparitosh commented
@YushaArif99 Can you please review this PR?

2023-08-21 01:23 UTC, hnhparitosh commented
Hi! @aparajith21 @YushaArif99 Can anyone please review this PR, as it has been quite a few days? Thanks!

2023-08-21 14:28 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_fft.py
> +        available_dtypes=helpers.get_dtypes("valid"), shape=(4,), array_api_dtypes=True
using `shape=(4,)` seems a bit too restrictive here. The input can really be any n-dim array right?

2023-08-21 14:32 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_fft.py
> +        axes=None,
you're always passing `axis=None`. This again isn't *fully* generalizing to the function's domain of inputs. `axis` parameter should also be generated using hypothesis strategies.

2023-08-21 14:37 UTC, YushaArif99 requested changes
Hi @hnhparitosh 

Apologies for the delay in the review. Have been quite swamped with work recently and so haven't had the time to review any PRs 😓 

With regards to the PR, the tests for `ifftshift` seem to be failing for the *paddle* backend due to some  unsupported `dtype` issue. Here are the error logs [link](https://github.com/unifyai/ivy/actions/runs/5788595311/job/15687881849?pr=21431)

Could you kindly fix the failing tests? Also, could you kindly resolve the abovementioned points? Once these are all done, feel free to re-request a review. Thanks! 🙂

2023-09-02 14:35 UTC, closed without merging