Added project.toml
unifyai/ivy pull request #21514
Opened 2023-08-09 00:15 UTC by sladyn98

Convert setup.py to project.toml

2023-08-09 00:15 UTC, sladyn98 commented
@vedpatwardhan @KareemMAX I added this as a draft start do let me know how it looks

2023-08-09 05:27 UTC, vedpatwardhan commented
I think the `pyproject.toml` should be in the root project folder rather than the `ivy_tests`. I'd also suggest checking if the installation still continues to work with editable mode if we've removed the `setup.py` (i.e. using the `-e`) as it seemed as though having a `setup.py` was also important for using a package in editable mode (i.e. with the symbolic link from the local folder to `site-packages` to reflect changes in the local folder in the `site-packages` when we try to `pip install` from a local directory which is done with the `-e` flag). 
Happy to know what you think @KareemMAX, thanks @sladyn98 😄

2023-08-09 05:34 UTC, KareemMAX commented
Not much to add. There's still missing areas that are in `setup.py` which are not implemented yet, after they are implemented we can proceed

2023-08-10 02:33 UTC, sladyn98 commented
I added the dependencies, could you let me know how to run it  ? I dont have a lot of experience with toml files.

2023-08-10 05:47 UTC, vedpatwardhan commented
@KareemMAX would have a better idea of the process, thanks!

2023-08-10 09:21 UTC, KareemMAX requested changes
The general structure looks good to me (although I'm not that deep into how `pyproject.toml` work). I've addressed some issues and then we can start testing.

My idea of testing things would be to use `pip`. Maybe we can test in 2 phases, locally using `pip install .` and then we can upload it to PyPI test registry

2023-08-10 09:21 UTC, KareemMAX commented on project.toml
> +version = "{__version__}"
We import this value from `ivy/_version.py`. Does that heppen?

Ref: https://github.com/unifyai/ivy/blob/master/setup.py#L53

2023-08-10 09:21 UTC, KareemMAX commented on project.toml
> +readme = "README.rst"
Readme is now `README.md`, we also run custom code on the raw document to remove dark mode blocks 

Ref: https://github.com/unifyai/ivy/blob/master/setup.py#L28-L45

2023-08-10 09:21 UTC, KareemMAX commented on project.toml
> +license = "Apache-2.0"
Is there is a need for the dash? In `setup.py` it uses `Apache 2.0`

Ref: https://github.com/unifyai/ivy/blob/master/setup.py#L74

2023-08-10 09:21 UTC, KareemMAX commented on project.toml
> +dill = "*"
This way duplicate our code a bit, can we make it look like the original `setup.py`?

Ref: https://github.com/unifyai/ivy/blob/master/setup.py#L71

2023-08-10 09:29 UTC, KareemMAX commented
Also one small addition. Seems like one of our volunteers @NripeshN has made some duplicate efforts by mistake 😅. https://github.com/unifyai/ivy/pull/21577

As I see you both looking into this maybe you can join forces @sladyn98 @NripeshN? Feel free to contact privately and use each others code. Maybe decide to close one of those PRs and keep the other

2023-08-15 18:28 UTC, KareemMAX requested changes
Hey @NripeshN,

Overall everything seem good to me, but you still having some TODOs that need to be resolved. After that we might start testing the behavior of it against PyPI test environment maybe.

2023-10-12 05:53 UTC, closed without merging