label_smooth
unifyai/ivy pull request #21620
Opened 2023-08-10 21:54 UTC by teckno

2023-08-10 22:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-29 07:32 UTC, hirwa-nshuti requested changes
Hey @teckno 

Check the comments below
Thanks

2023-08-29 07:32 UTC, hirwa-nshuti commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +    return ivy.label_smooth(label, prior_dist, epsilon)
This function isn't present in the ivy API, you will implement a composition

2023-10-08 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-23 19:38 UTC, closed without merging