class_center_sample
unifyai/ivy pull request #21628
Opened 2023-08-11 02:19 UTC by teckno

2023-08-11 02:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-31 05:24 UTC, hirwa-nshuti requested changes
Hey @teckno 

Check the comments below

2023-08-31 05:24 UTC, hirwa-nshuti commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +    return ivy.class_center_sample( label, num_classes, num_samples, group=group )
Ivy doesn't have this function implemented on our API

2023-08-31 05:24 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_common.py
> +    weight = ivy.swapaxes(weight, -1, -2)
Ivy dependency should be removed

2023-10-09 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-23 19:42 UTC, closed without merging