Docs frontend tests
unifyai/ivy pull request #2172
Opened 2022-07-22 10:09 UTC by jkeane508

Frontend Ones Implementation and Frontend Tests Docs

2022-07-22 12:40 UTC, jkeane508 commented
Currently, the test for frontend torch ones, is failing which I believe might be an issue with num_positional_args. However this is my first draft of the doc based on @rush2406 's work.

2022-07-22 21:27 UTC, djl11 requested changes
a few changes, but otherwise it looks great :)

2022-07-22 21:27 UTC, djl11 commented on ivy/functional/frontends/torch/creation_ops.py
> +def ones(size, *, out=None, dtype=None, layout=None, device=None, requires_grad=False):
we should actually handle `requires_grad`, we can do this by calling `ivy.variable` on the returned value if `requires_grad=True`

2022-07-22 21:27 UTC, djl11 commented on ivy/functional/frontends/jax/__init__.py
> +from .numpy import functions
I should have made this clear, but we are actually only concerned with adding the `jax.lax` frontend for the time being, and not the `jax.numpy` namespace. If you want to add a similar frontend function for `jax` as well, then you could add [jax.lax.full](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.full.html#jax.lax.full)

2022-07-26 12:33 UTC, jkeane508 commented
Hi,

I've made the changes and full() and is one of the more complex examples which is a good complement to ivy.tan()

However, the test for PyTorch frontend test is not passing and it is not something that I could work out. If I could get a quick review of that with a fresh set of eyes, would be appreciated.

Other than that I'm pretty happy with this document :)

2022-07-26 17:34 UTC, djl11 requested changes
some small changes, could you also please provide a stack trace of the failing `torch` example that you are unable to figure out?

2022-07-26 17:34 UTC, djl11 commented on ivy/functional/frontends/torch/creation_ops.py
> +    else:
small detail, but we can actually replace:

```
else:
    return ret
```

with:

```
return ret
```

2022-07-26 17:34 UTC, djl11 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
> +    if ivy.is_int_dtype(dtype):
`elif`

2022-07-26 17:34 UTC, djl11 commented on ivy_tests/test_ivy/test_frontends/test_numpy/creation_routines/test_from_shape_or_value.py
> +    if ivy.is_int_dtype(dtype):
`elif`

2022-07-26 17:34 UTC, djl11 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tf_functions.py
> +    if ivy.is_int_dtype(dtype):
`elif`

2022-07-26 17:34 UTC, djl11 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_creation_ops.py
> +    if ivy.is_int_dtype(dtype):
`elif`

2022-07-26 17:34 UTC, djl11 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_creation_ops.py
> +    else:
see comment above

2022-07-27 13:47 UTC, merged