Implemented missing Hann_window to tf.signal
unifyai/ivy pull request #21731
Opened 2023-08-11 19:30 UTC by Enigmafiend

Closes #21512
The dtype part of the test is commented out as I cant seem to get it to work and instead get this error, if you can tell me how to fix it I would be grateful as it re-occurs in alot of signal functions
![image](https://github.com/unifyai/ivy/assets/41777835/831129b1-4d85-4b12-a6da-a86bad665c43)

2023-08-11 19:32 UTC, Enigmafiend commented
ivy-gardener

2023-08-11 19:35 UTC, Enigmafiend commented
ivy-gardener

2023-09-07 06:58 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

Can you kindly address the abovementioned points. That should fix the issue you were mentioning. Also, can you kindly resolve the merge conflicts as well? 
Feel free to ping me once you've made the changes and verified that all tests are still passing. Thanks! 🙂

2023-09-07 06:58 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
> +    # dtype=helpers.get_dtypes("float", full=False),
So I was debugging the error and after getting into the weeds of the `test_frontend_function` helper, it turns out that you basically dont need to pass the `dtype` argument seperately. The `input_dtype=input_dtype` takes care of the handling of `dtypes` and converting them to their native form. 
If you pass `dtype` seperately, it is used as an input when calling the `hann_window` and `dtype` is a string by default, hence you get the error of 
```python
E      AttributeError: str object has no attribute `is_floating_dtype`
```

So you can basically remove the `dtype` kwargs from the test. Just the `input_dtypes` is sufficient

2023-09-07 06:58 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
> +        available_dtypes=["int32", "int64"],
I think you should replace this with 
```python
available_dtypes=helpers.get_dtypes("valid"),
```

2023-09-18 05:31 UTC, YushaArif99 commented on ivy/functional/frontends/tensorflow/signal.py
I think you've made some unwanted changes in this file while doing a merge. Could you kindly revert these changes so that the only modified changes are that of `hann_window`

2023-09-18 05:33 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

Could you kindly address the abovementioned point and also resolve the merge conflicts so the CI tests can run? Once all relevant tests are passing, feel free to re-request a review from me. Thanks! 🙂

2023-09-20 00:53 UTC, Enigmafiend commented
A trivial resolve conflict, could you manually mark it as resolved?

2023-09-26 06:27 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

Again it seems you have added some unwanted changes to the files here. Resolving merge conflicts is a fundamental step towards open source contributions so its important to learn how to do it properly 🙂
Unfortunately, its not the job of the reviewer to resolve conflicts. I'd suggest you watch a few tutorials on how to resolve conflicts and then try it on your own. That's the best way to master this simple yet fundamental skill👍🏼 

Feel free to request a review **once** that's done and the tests are passing. Thanks! 🙂

2023-12-24 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-27 12:49 UTC, closed without merging