Implements Hamming Window for tf.signal
unifyai/ivy pull request #21732
Opened 2023-08-11 19:56 UTC by Enigmafiend

Close #21511
Dtype part of the test commented out as it gives the error shown below, help in resolving this would be greatly appreciated
![image](https://github.com/unifyai/ivy/assets/41777835/109cf6fa-8f67-4aa1-8677-609bee3c13bc)

2023-08-11 19:57 UTC, Enigmafiend commented
ivy-gardener

2023-09-07 07:01 UTC, YushaArif99 requested changes
This seems like a similar error to the one I just reviewed  (https://github.com/unifyai/ivy/pull/21731#discussion_r1318162968)

Also, could you kindly resolve the merge conflicts in this PR as well? Thanks! 🙂

2023-09-18 05:35 UTC, YushaArif99 commented on ivy/functional/frontends/tensorflow/signal.py
again there seem to be some unwanted changes made to this file. Can you kindly resolve these

2023-09-18 05:36 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

same comments as made for this PR (https://github.com/unifyai/ivy/pull/21731), could you kindly also resolve the conflicts on this PR so the CI tests can run? Thanks! 🙂

2023-09-26 06:14 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

There are still a few issues in the PR. Kindly resolve these (and ensure the tests are passing) before requesting a review as that helps with the reviewing process 🙂 

- there are  still some unwanted changes in `ivy/functional/frontends/tensorflow/signal.py`
- the PR compliance checks is failing 
- there are merge conflicts in the PR due to which the CI tests are not running

2023-12-24 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-27 13:08 UTC, closed without merging