Add testing for precise and non precise modes
unifyai/ivy pull request #21781
Opened 2023-08-13 03:30 UTC by Daniel4078

2023-08-14 11:10 UTC, CatB1t requested changes

2023-08-14 11:10 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        ivy.unset_precise_mode()
We shouldn't call global `ivy` but instead `ivy_backend`

2023-08-14 11:10 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        ivy.unset_precise_mode()
We shouldn't call global `ivy` but instead `ivy_backend`

2023-08-14 11:10 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        ivy.set_precise_mode(test_flags.precision_mode)
We shouldn't call global `ivy` but instead `gt_backend`

2023-08-14 11:10 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        ivy.unset_precise_mode()
We shouldn't call global `ivy` but instead `gt_backend`

2023-08-15 05:49 UTC, Daniel4078 commented
I still need to add generation of the new precision_mode parameter in the test_flags object. Is there any hint or advices?

2023-08-18 09:06 UTC, Daniel4078 commented
It seems like dispite me adding the generation strategy for precision mode, it fails to be generated or not being passed correctly as shown here: E   TypeError: accept.<locals>.init_method_flags() missing 1 required keyword-only argument: 'precision_mode'.

2023-08-23 14:18 UTC, Daniel4078 commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        ivy_backend.unset_precise_mode()
Can you give me a more detailed example of how to use the context manager? As I did not know that I added anything with the form of PreciseMode(precision_mode).

2023-08-25 07:51 UTC, Daniel4078 commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        ivy_backend.unset_precise_mode()
@sherry30 Currently I found there used to be another context manager implemented in ivy_tests/test_ivy/helpers/pipeline_helper.py as WithBackendContext. But I found that it is somehow removed from the current main branch, so I am not sure how to implement and use it. Can you give some hint?

2023-08-26 12:30 UTC, Daniel4078 commented
ivy-gardener

2023-08-27 10:23 UTC, merged