Put numpy instance frontend
unifyai/ivy pull request #21794
Opened 2023-08-13 13:08 UTC by IIDCII

Close https://github.com/unifyai/ivy/issues/18530

2023-08-13 13:20 UTC, IIDCII commented
Close #18530

2023-08-13 13:22 UTC, IIDCII commented
Close #18530

2023-08-13 13:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-13 17:04 UTC, AryanSharma21 reviewed
Hey @IIDCII , you should add the closing tag in PR description and not in comments 🙂

2023-08-14 10:41 UTC, CatB1t requested changes

2023-08-14 10:41 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
Hello @IIDCII, why are those changes required? can you explain the reason for those modifications? Thanks!

2023-08-14 10:41 UTC, CatB1t commented on ivy_tests/array_api_testing/test_array_api
Can we revert this?

2023-09-24 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-11-26 05:53 UTC, closed without merging

2023-11-26 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.