add unique
unifyai/ivy pull request #21867
Opened 2023-08-14 20:28 UTC by bilal-aamer

2023-08-15 09:10 UTC, jshepherd01 commented
Your test seems to be failing when I run it
```py
ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_manipulation.py:977: in <module>
    def test_unique(*, dtype_x_axis, none_axis, test_flags, backend_fw, fn_name, on_device):
ivy_tests/test_ivy/helpers/testing_helpers.py:363: in test_wrapper
    callable_fn, fn_name, fn_mod = _import_fn(fn_tree)
ivy_tests/test_ivy/helpers/testing_helpers.py:157: in _import_fn
    callable_fn = mod.__dict__[fn_name]
E   KeyError: 'unique'
```
because there doesn't seem to be a `unique` function in `ivy/experimental/manipulation.py`.

Also, could you please link your issue to the relevant ToDo list? It massively helps with bookkeeping to know what everyone's working on

2023-08-15 10:40 UTC, bilal-aamer commented
Hey @jshepherd01, thanks for the input will be putting a commit and linking ToDo issue.

2023-08-15 11:11 UTC, jshepherd01 commented
The tests are still failing for me:
```py
FAILED ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_manipulation.py::test_unique[cpu-numpy-False-False] - ivy.utils.exceptions.IvyBackendException: numpy: unique: numpy: unique: numpy: unique: numpy: unique: numpy: unique: numpy: unique: numpy: unique: numpy: unique: numpy: unique: numpy: unique: numpy: uniqu...
FAILED ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_manipulation.py::test_unique[cpu-jax-False-False] - hypothesis.errors.Flaky: Inconsistent test results! Test case was Conclusion(status=Status.INTERESTING, interesting_origin=(<class 'ivy.utils.exceptions.IvyBackendException'>, '/home/joe/dev/ivy/ivy/utils...
FAILED ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_manipulation.py::test_unique[cpu-tensorflow-False-False] - ivy.utils.exceptions.IvyBackendException: tensorflow: unique: tensorflow: unique: tensorflow: unique: tensorflow: unique: tensorflow: unique: tensorflow: unique: tensorflow: unique: tensorflow: unique: te...
FAILED ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_manipulation.py::test_unique[cpu-paddle-False-False] - hypothesis.errors.Flaky: Inconsistent test results! Test case was Conclusion(status=Status.INTERESTING, interesting_origin=(<class 'ivy.utils.exceptions.IvyBackendException'>, '/home/joe/dev/ivy/ivy/utils...
```
I'm also seeing a failed linting test which can probably be fixed by running the [pre-commit hooks](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit).

Also, I think your issue still needs to be linked to the ToDo list issue properly (following the instructions [here](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues)), and based on that issue it seems like you need to add `unique` to the paddle frontend rather than the `ivy.Array` class (see [here](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis) for more information about that).

2023-08-15 16:19 UTC, jshepherd01 commented
I'm still seeing failed tests, do you get the same thing?
![image](https://github.com/unifyai/ivy/assets/72616151/ee45a6d4-d26b-4750-981b-8a00273d6629)

2023-08-16 08:53 UTC, jshepherd01 requested changes

2023-08-16 08:53 UTC, jshepherd01 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_manipulation.py
> +    test_gradients=st.just(False),
The tests currently fail with `hypothesis.errors.InvalidArgument: test_unique() got an unexpected keyword argument 'test_gradients', from 'test_gradients=just(False)'`

2023-08-16 08:53 UTC, jshepherd01 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_manipulation.py
> +def test_unique(*, dtype_x_axis, none_axis, test_flags, backend_fw, fn_name, on_device):
Frontend test functions should be named `test_frontend_funcname` (i.e. `test_paddle_unique`)

2023-08-16 09:02 UTC, bilal-aamer commented
@jshepherd01 made the required changes

2023-08-16 09:02 UTC, bilal-aamer commented
@jshepherd01 made the required changes

2023-08-16 09:05 UTC, jshepherd01 requested changes
Tests are still failing for me, are they passing on your machine?

2023-08-16 09:05 UTC, jshepherd01 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_manipulation.py
> +    ground_truth_backend="torch",
Tests now throw the error `hypothesis.errors.InvalidArgument: test_paddle_unique() got an unexpected keyword argument 'ground_truth_backend'`.

2023-08-16 09:13 UTC, bilal-aamer commented
> Tests are still failing for me, are they passing on your machine?

Can't see the tests but most passed successfully

2023-08-16 09:31 UTC, jshepherd01 commented
If you can't see the tests then that's a problem in itself. You can run them locally from the `ivy` directory using `python3 -m pytest path/to/test/file.py::test_function_name -v` and see the results for yourself.

Also, I can still see some linting errors resulting from your code, please double check that you've installed the [pre-commit hooks](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit) correctly and that they're running every time you use `git commit`.

Thanks

2023-09-25 09:19 UTC, juliagsy requested changes
Hey! Thanks for the hard work! Just a quick one, would you mind quickly resolving the conflicts in this PR first? I'll try to check the tests after that soonest possible, thanks!

2023-09-27 11:44 UTC, juliagsy reviewed
Hey! I see that there are a lot of additions after resolving the merge conflicts, I believe these function are either already existing in another file, or a duplication of the same file, could you please cross check with the latest code in the master branch, and keep only the changes related to you frontend function in your issue? Thanks!

2023-10-09 14:00 UTC, juliagsy commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-10-09 16:24 UTC, bilal-aamer commented
Hey @juliagsy

2023-10-11 08:41 UTC, juliagsy reviewed
Hey! I couldn't see the refactor from the PR diff unfortunately, it's still showing a load of function additions which are not related to your chosen function. Could you please either push your changes to the PR so that it's up-to-date or could you please refactor them again? thanks!

2023-10-24 18:20 UTC, juliagsy commented
This PR has been closed because it has been stale for more than 7 days with no activity. Please feel free to reopen the PR yourself if you'd like to continue, thanks!

2023-10-24 18:20 UTC, closed without merging

2023-10-24 18:24 UTC, bilal-aamer commented
@juliagsy I'd like to continue