inverse_stft_window_fn
unifyai/ivy pull request #21888
Opened 2023-08-15 08:01 UTC by teckno

closes #21889

2023-08-15 08:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-31 05:37 UTC, hirwa-nshuti requested changes
Hey @teckno 

Check the comments below
Thanks

2023-08-31 05:37 UTC, hirwa-nshuti commented on ivy/functional/frontends/tensorflow/signal.py
> +    return lambda frame_length: tf.signal.inverse_stft_window_fn(frame_length, forward_window_fn, frame_step)
We don't use any framework in the frontends only Ivy functions are used to avoid dependency

2023-12-24 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-27 09:03 UTC, Sarvesh-Kesharwani commented
Hi @teckno, kindly focus on incorporating a singular function per pull request. Specifically, in this pull request, concentrate solely on the implementation of the inverse_stft_window_fn function. To enhance clarity and maintain consistency, eliminate any alterations made in files other than signal.py and test_signal.py.
Thanks for the contribution😊.

2024-01-10 13:33 UTC, closed without merging