cdist
unifyai/ivy pull request #21892
Opened 2023-08-15 08:32 UTC by teckno

closes #21894

2023-08-15 09:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-31 05:39 UTC, hirwa-nshuti requested changes
Hey @teckno 

Check the comments below🙂
Thanks

2023-08-31 05:39 UTC, hirwa-nshuti commented on ivy/functional/frontends/torch/miscellaneous_ops.py
> +    return ivy.cdist(x1, x2, p=p, compute_mode=compute_mode)
This function isn't present in the Ivy API

2023-09-21 03:55 UTC, hirwa-nshuti requested changes
Would you also resolve the merge conflicts for CI checks🤞

2023-12-31 17:51 UTC, Sarvesh-Kesharwani commented
ChibuezeOnejeme

2024-02-12 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-27 11:38 UTC, closed without merging