Added segment_sum function to math.py
unifyai/ivy pull request #21907
Opened 2023-08-15 12:27 UTC by soumesh113

Close #21903

2023-08-16 03:37 UTC, soumesh113 commented
Hi @ZoeCD , could you please review this PR and suggest any changes to be made?

2023-08-18 15:49 UTC, ZoeCD requested changes

2023-08-18 15:49 UTC, ZoeCD commented on ivy/functional/frontends/tensorflow/math.py
> +    data = ivy.array(data)
You don't need to change the arrays to ivy arrays. The `to_ivy_arrays_and_back` decorator handles that

2023-08-18 15:49 UTC, ZoeCD commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +        input_dtypes=["int32", "int64"],
Here you should be passing the dtype that your data has. I recommend checking other tests to see how it is done

2023-08-18 15:49 UTC, ZoeCD commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +def test_tensorflow_segment_sum(
Hello! The test is failing for all backends. You can see the stacktrace and error in the details section of the intelligent-tests (1) 

Let me know if you have any questions!

2023-08-31 15:02 UTC, ZoeCD requested changes

2023-08-31 15:02 UTC, ZoeCD commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +    helpers.test_frontend_function(
The tests are still failing. It shows` TypeError: 'Array' object cannot be interpreted as an integer`
You don't need to send the dtyès as an array. Check out this call as an example

``` input_dtype, x = dtype_and_x
      helpers.test_frontend_function(
        input_dtypes=input_dtype,
        backend_to_test=backend_fw,
        frontend=frontend,
        test_flags=test_flags,
        fn_tree=fn_tree,
        on_device=on_device,
        x1=x[0],
        x2=x[1],
    )

```
To the kwarg `input_dtypes` you only need to pass the `data_dtype`. And you pass the inputs at the end of the function call. And so on. Let me know if this makes sense!

2023-12-26 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-27 13:19 UTC, closed without merging