Implements hann_window for torch frontend
unifyai/ivy pull request #21913
Opened 2023-08-15 13:12 UTC by Enigmafiend

Close #21912

2023-08-15 13:12 UTC, Enigmafiend commented
ivy-gardener

2023-09-07 07:03 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_spectral_ops.py
> +    # dtype=helpers.get_dtypes("float", full=False),
again, this seems to be the same error as reviewed in a different PR (https://github.com/unifyai/ivy/pull/21731#discussion_r1318162968)

2023-09-07 07:04 UTC, YushaArif99 requested changes
Left a comment 🙂

2023-09-12 06:42 UTC, Enigmafiend commented
ivy-gardener

2023-09-18 05:45 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

Thanks for making the requested changes. The tests also seem to be passsing now. Just one final thing, could you kindly fix the linting errors [here](https://github.com/unifyai/ivy/actions/runs/6155860015/job/16703443012?pr=21913#step:5:144) before I go ahead with the merge? Thanks! 🙂

2023-09-18 05:46 UTC, YushaArif99 commented
ivy-gardener

2023-09-20 00:26 UTC, Enigmafiend commented
ivy-gardener

2023-09-21 02:35 UTC, Enigmafiend commented
The lint error that the test fails for seems to not even exist, it conforms to the lint rules as needed.

2023-09-26 06:09 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

In order to fix the linting errors, you'll have to run `pre-commit` on the modified files and then push the changes. 

so the command you need to run will be 
```python

pre-commit run --files ivy/functional/frontends/torch/spectral_ops.py ivy_tests/test_ivy/test_frontends/test_torch/test_spectral_ops.py

```

2023-12-24 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-27 06:54 UTC, closed without merging