expand_as
unifyai/ivy pull request #21976
Opened 2023-08-16 00:52 UTC by bilal-aamer

Closes https://github.com/unifyai/ivy/issues/21925 and https://github.com/unifyai/ivy/issues/21974

2023-08-17 19:21 UTC, bilal-aamer commented
@zaeemansari70 Any pointers to address the failing test cases, would be appreciated.

2023-08-22 08:40 UTC, zaeemansari70 requested changes
Requested some changes, let me know if you have any questions. Thanks!

2023-08-22 08:40 UTC, zaeemansari70 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_manipulation.py
> +from hypothesis import draw
This import should be removed from here

2023-08-22 09:09 UTC, bilal-aamer commented
@zaeemansari70 kindly review

2023-09-29 14:18 UTC, zaeemansari70 requested changes

2023-09-29 14:18 UTC, zaeemansari70 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_manipulation.py
> +@given(dtype_x_and_shape())
the decorator used here should be `@handle_frontend_test`, kindly refer to our docs for a better understanding.

2023-10-01 13:34 UTC, aparajith21 commented
Hi, please let me know when everything @zaeemansari70 suggested has been incorporated and this is ready for review!

2023-10-02 00:16 UTC, bilal-aamer commented
Sure @aparajith21 👍

2023-10-02 11:17 UTC, bilal-aamer reviewed
@aparajith21 Kindly check it out 

@zaeemansari70 👀

2023-10-06 13:45 UTC, aparajith21 commented
Hey, thanks for contributing! Could you please only add the function you're creating and not modify any of the rest of the file please? Thanks!

2023-12-24 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-24 06:21 UTC, bilal-aamer commented
@aparajith21 @Fayad-Alman Could you let me know how to proceed further.

2023-12-24 14:56 UTC, NripeshN commented
Hey @bilal-aamer,
Could you please resolve the merge conflicts so it is easier for the reviewer to review

2024-03-04 12:15 UTC, Ishticode commented
closing this as too many changes (besides the issues) like it adds `test_paddle_abs` in paddles manipulations tests which already exist https://github.com/unifyai/ivy/blob/2c11f9f2bf9070bef18a10ee91d7e66a44fdaca3/ivy_tests/test_ivy/test_frontends/test_paddle/test_manipulation.py#L307

2024-03-04 12:15 UTC, closed without merging