Added 'subtract_' to paddle frontend Math
unifyai/ivy pull request #22100
Opened 2023-08-17 17:00 UTC by shashi278

close #21937

2023-08-22 20:52 UTC, umairjavaid requested changes
The tests are not passing, probably due to incorrect paths in the test functions. Kindly make sure all the tests are passing. 
```
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py:384: in test_paddle_subtract_
    fn_tree="paddle.subtract_",
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py:405: in test_paddle_subtract_
    helpers.test_frontend_function(
ivy_tests/test_ivy/helpers/function_testing.py:825: in test_frontend_function
    frontend_ret = frontend_fw.__dict__[fn_name](*args_frontend, **kwargs_frontend)
E   KeyError: 'subtract_'
E   Falsifying example: test_paddle_subtract_(
E       on_device='cpu',
E       frontend='paddle',
E       backend_fw='torch',
E       dtype_and_x=(['float64', 'float64'], [array(-1.), array(-1.)]),
E       fn_tree='ivy.functional.frontends.paddle.subtract_',
E       test_flags=FrontendFunctionTestFlags(
E           num_positional_args=0,
E           with_out=False,
E           inplace=False,
E           as_variable=[False],
E           native_arrays=[False],
E           generate_frontend_arrays=False,
E       ),
E   )
E   
E   You can reproduce this example by temporarily adding @reproduce_failure('6.82.4', b'AXicY2AAAkYGCGBEYwMBAABkAAU=') as a decorator on your test case
```

2023-08-22 20:52 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py
> +    fn_tree="paddle.subtract_",
the path should be paddle.math.subtract_

2023-08-22 20:52 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py
> +    fn_tree="paddle.remainder_",
the path should be paddle.math.remainder_

2023-08-22 20:52 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py
> +    fn_tree="paddle.exp_",
the path should be paddle.math.exp_

2023-08-24 06:50 UTC, shashi278 commented
Hi @umairjavaid Thanks for the review. I fixed the tests but now I don't see any detailed test logs for these functions. Are they skipped for some reason? Could you please check?

2023-10-19 20:39 UTC, aparajith21 commented
Hi! Thanks for contributing. Mostly seems okay and LGTM, but will review in detail once you fix conflicts, please let me know when it is ready for review.

2023-12-25 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-27 13:19 UTC, closed without merging