add unshuffle
unifyai/ivy pull request #22247
Opened 2023-08-20 17:50 UTC by AmeenUrRehman

2023-08-20 18:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-27 14:12 UTC, AmeenUrRehman commented
@YushaArif99 Plz review this

2023-09-02 14:49 UTC, AmeenUrRehman commented
@AnnaTz could u plz review this 😢

2023-09-02 15:55 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_exponents_and_logarithms.py
could you kindly revert this change 🙂

2023-09-02 15:58 UTC, YushaArif99 requested changes
Hi @AmeenUrRehman 

Apologies for the delay in the review. Was away traveling for a few weeks due to which I couldnt responsive to the PRs 😓 

With regards to your PR, the implementation does look good to me. Could you kindly resolve the merge conflicts and then re-request a review? The CI tests are failing with a weird `dill` import error which I think should go away after the conflicts have been resolved. Thanks! 🙂

2023-09-02 16:04 UTC, AmeenUrRehman commented
> Hi @AmeenUrRehman
> 
> Apologies for the delay in the review. Was away traveling for a few weeks due to which I couldnt responsive to the PRs 😓
> 
> With regards to your PR, the implementation does look good to me. Could you kindly resolve the merge conflicts and then re-request a review? The CI tests are failing with a weird `dill` import error which I think should go away after the conflicts have been resolved. Thanks! 🙂

2023-09-02 16:06 UTC, AmeenUrRehman commented
Sure, I'll try to resolve this, sorry it closed by mistake.

2023-09-02 16:31 UTC, AmeenUrRehman commented
@YushaArif99 hey could u check now.

2023-09-03 05:56 UTC, YushaArif99 requested changes
Hi @AmeenUrRehman, the conflicts are still showing though 😅. Could you try resolving them once again? Thanks!

2023-09-03 09:06 UTC, AmeenUrRehman commented
Sure, working on it.

2023-09-03 10:58 UTC, closed without merging

2023-09-03 10:59 UTC, AmeenUrRehman commented
@YushaArif99 , I'll open another pr soon. Their is some problem in my environment