Close#7507
unifyai/ivy pull request #22255
Opened 2023-08-20 21:04 UTC by GamerLab

Done:

# Example of handling an empty array

# Note Added For Return type of Function:
benefit of explicitly mentioning the return type hint
Clarity:users immediately know the data type they can expect the returned value to be. This reduces ambiguity and confusion.
Type Checking:Many programming environments and tools, such as type checkers and IDEs, can use this explicit information to perform type checking. This helps catch potential type-related errors early in the development process

# The MXNet function you provided does not fulfill all the requirements. While the type hints are correctly defined for the function's input and output, the function itself raises an IvyNotImplementedException().
Additionally, should handle cases like converting input data to boolean 

# added exception handling for numpy

# added exception handling for paddle#

# added exception handling for torch

2023-08-20 21:17 UTC, GamerLab commented
@YushaArif99  Please review my pull request . 
I have been very careful this time not to update the existing coding of Ivy framework , and new example and change can follow the existing standard and pattern.

2023-08-20 21:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-02 17:15 UTC, GamerLab commented
@YushaArif99  hello have you seen this pull request ? 
Please have a look at that . Si can proceed with other working .

2023-10-02 05:49 UTC, YushaArif99 requested changes
Hi @GamerLab 

Extremely sorry for the delay in review 🙏🏼 . Don't know how this PR slipped under the radar as I normally try to be quite vigilant and frequently view my notifications. 

With regards to the PR itself,I am also noticing that you've made changes to the `all` function instead of the `any` function which is what the PR is referring. Any reason for doing that?

2023-10-09 02:37 UTC, GamerLab reviewed
Hello !
YushaArif , I have cross checked all the changes I have done was in Any function not in All function You can expand the file to view . Plz have a look again and let me know if there are some thing more to be fixed . Thanks .
Also Pleased let me know how i can fix the tests . Thanks

2023-10-09 02:42 UTC, GamerLab commented
![1](https://github.com/unifyai/ivy/assets/136035156/72a741ff-979b-45ff-801f-3f4a2eff3d2d)
![2](https://github.com/unifyai/ivy/assets/136035156/9848809d-16e7-4f60-9c75-5261af826b6e)
![3](https://github.com/unifyai/ivy/assets/136035156/25aae3a0-89e9-47a2-b9ed-edb2338dfabe)
![4](https://github.com/unifyai/ivy/assets/136035156/d80aa250-7d67-4242-8bb9-038dff427086)

2024-03-03 09:07 UTC, Ishticode commented
Hi GamerLab
Thanks for the PR. 
I will be closing this as the linked issue is for reformat only which is todo with docstring. In addition, the changes are a bit incoherent and the changes requested by Yusha above were not made. Please checkout our [Contributing Guidelines](https://unify.ai/docs/ivy/overview/contributing.html) for further details. Thanks you very much :)

2024-03-03 09:07 UTC, closed without merging