Dino utils
unifyai/ivy pull request #22344
Opened 2023-08-22 14:17 UTC by OmarJabri7

Utility functions and classes that were added to support DINO as well as their general need to be supported in ivy framework:
- Batch Norm 1D: Added for 1 dimensional batch normalization
- Weight Norm: Added weight normalization since their uses are more common
- weight_norm: utility function for Weight Norm Class
- DINOLoss: class presenting specific loss used in the DINO model

2023-08-23 05:37 UTC, vedpatwardhan requested changes
Hey @OmarJabri7, just requested a few changes, thanks 😄

2023-08-23 05:37 UTC, vedpatwardhan commented on ivy/functional/ivy/experimental/utility.py
> +    if x is None:
I think `ivy.exists(x)` would be equivalent to this anyway, so this function might be redundant

2023-08-23 05:37 UTC, vedpatwardhan commented on ivy/stateful/layers.py
> +class Identity(Module):
Actually we already have the [`Identity`](https://github.com/unifyai/ivy/blob/8ffd9ffad6f715a3b0bdedb3bbafe52d0085d2e6/ivy/stateful/layers.py#L2199) layer in this file, so we can use that instead

2023-08-23 05:37 UTC, vedpatwardhan commented on ivy/stateful/losses.py
> +        # TODO: Check dist.all_reduce implementation in IVY
We don't have distributed training supported in `ivy` 😅

2023-09-30 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-10-18 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-10-18 05:53 UTC, closed without merging