Update functions that has `copy` argument
unifyai/ivy pull request #22354
Opened 2023-08-22 16:07 UTC by Madjid-CH

this PR is for this [task](https://trello.com/c/cceeXvrr)

2023-08-23 11:19 UTC, AnnaTz requested changes

2023-08-23 11:19 UTC, AnnaTz commented on ivy/data_classes/array/creation.py
> +    @handle_view
@vedpatwardhan Is `ivy.asarray` an edge case? why have a `copy` argument if there is no `view` wrapper? Is `copy` handled somewhere else?

2023-08-23 11:19 UTC, AnnaTz commented on ivy/data_classes/array/experimental/manipulation.py
> +             a view of the input array.
Could you move this to under `self`? We want the docstrings to be in the same order as the arguments.

2023-08-23 11:19 UTC, AnnaTz commented on ivy/data_classes/array/manipulation.py
> +         copy
This indent is probably a mistake I think.

2023-08-23 13:25 UTC, AnnaTz commented on ivy/data_classes/array/creation.py
> +    @handle_view
@Madjid-CH actually please remove the changes from `creation` and `general` files. These are special cases. After that we are good to merge.

2023-08-25 11:02 UTC, Madjid-CH commented
Hey @AnnaTz,
I did the requested changes 🙂

2023-08-25 11:03 UTC, AnnaTz approved these changes

2023-08-25 11:04 UTC, merged