huber_loss
unifyai/ivy pull request #22375
Opened 2023-08-22 20:48 UTC by sushmanthreddy

2023-08-22 20:50 UTC, sushmanthreddy commented
@hello-fri-end plss assign this to you...I had so many conflicts,so this made me to make new pull request

2023-08-24 04:27 UTC, sushmanthreddy commented
@DragosStoican can u pls review my pr?
I was really looking forward for the some suggestions

2023-08-25 17:25 UTC, DragosStoican requested changes

2023-08-25 17:25 UTC, DragosStoican commented on ivy/functional/backends/tensorflow/experimental/losses.py
> +def smooth_l1_loss(
Don't forget to modify the name of this function, I see you've implemented huber_loss here

2023-08-25 17:25 UTC, DragosStoican commented on ivy/functional/backends/paddle/experimental/losses.py
> +                "float16",
You should add bfloat16 here, my test was failing because of bfloat16 dtype

2023-08-25 17:25 UTC, DragosStoican commented on ivy/functional/backends/tensorflow/experimental/losses.py
> +    abs_diff = ivy.abs(input - target)
You should be using tf functions here, do not import ivy in the backend implementations

2023-08-25 17:25 UTC, DragosStoican commented on ivy/functional/backends/tensorflow/experimental/losses.py
> +import ivy
Shouldn't be using ivy here. Use tf functions instead

2023-08-25 17:25 UTC, DragosStoican commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +        available_dtypes=helpers.get_dtypes("float"),
Can you try changing these to "valid" instead so we expand the scope of the tests? I've given it a try and it doesn't seem to add too many difficulties. it didn't cause any of the passing tests to fail

2023-08-25 17:28 UTC, DragosStoican commented
Hi @sushmanthreddy , first of all thank you for your contribution, this is a great PR. There's only a few small things to address before we can get this merged. Mainly I would like you to take a look at the tensorflow backend implementation, where I think you rushed a bit and forgot to change the ivy functions to tf function. Other than that, your function is failing on the paddle paddle backend due to an unsupported bfloat16 dtype. We need to make sure all tests pass before we get this merged. In addition, please make sure the `check-formatting` CI test is passing (you've introduced a few formatting errors).

Once you address all those points I am happy to get this merged. Thanks again, great work!

2023-08-25 18:50 UTC, sushmanthreddy commented
@DragosStoican i have made the changes..i think now everything is good to go..if u havee any changes pls let me knew

2023-08-25 18:51 UTC, sushmanthreddy commented
![Screenshot from 2023-08-26 00-21-25](https://github.com/unifyai/ivy/assets/73489688/1bcae58b-b98e-4a8e-9d7e-fe060b4f4e6c)

2023-08-26 08:02 UTC, DragosStoican commented on ivy/functional/backends/paddle/experimental/losses.py
> +                "bfloat16float16",
You are missing a break line here, should look like this:
"bfloat16",
"float16",

2023-08-27 10:08 UTC, DragosStoican commented on ivy/functional/backends/numpy/experimental/losses.py
> +# Implementation of smooth_l1_loss in the given format
Implementation of huber_loss not smooth_l1_loss

2023-08-28 14:38 UTC, DragosStoican commented on ivy/functional/backends/numpy/experimental/losses.py
> +import ivy
Remove this import

2023-08-28 14:38 UTC, DragosStoican commented on ivy/functional/backends/numpy/experimental/losses.py
> +        return ivy.sum(loss)
Use np functions only please :)

2023-08-28 14:44 UTC, merged