Add pytorch's cummax function to frontend
unifyai/ivy pull request #22386
Opened 2023-08-23 03:00 UTC by heisguyy

This commit implements the pytorch's cummax(torch.cummax) in Ivy's frontend, this allows users to call pytorch's cummax function from the torch_frontend in Ivy.

Closes #22325

2023-08-23 03:59 UTC, Daniel4078 requested changes
Hi, I suppose that you need to add a test for your commax frontend function for torch like other in ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py

2023-08-23 04:11 UTC, heisguyy commented
I am on it. Thank you.

2023-08-24 04:05 UTC, Daniel4078 reviewed
Please update your branch with the main one as I found that your tests are failing due to an old problem: E ModuleNotFoundError: No module named 'dill'. Which has been patched out in recent commits on the ivy main branch.

2023-08-24 09:10 UTC, heisguyy commented
Ok I will do that. Thank you.

2023-08-26 02:25 UTC, closed without merging