included max_unpool3d method
unifyai/ivy pull request #22398
Opened 2023-08-23 10:41 UTC by Reptilefury

2023-08-23 11:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-03 17:25 UTC, hmahmood24 requested changes
Hey @Reptilefury, thanks for the PR! However, in order to proceed forward, there a couple of points we need to work on.

1. First off, this PR is supposed to add just a frontend function and its test and so adding functions to any other APIs is not recommended/acceptable. You've also not added any test for the frontend function in this PR.
2. Secondly, you've added the `max_unpool3d` to just the experimental API and so this function is non-existent in all the other backends which would cause the tests to fail with every backend it is tested with.

There are two ways you can go about now:

1. The proper procedure of adding a new function to `ivy` is by first creating a new `Missing Function Suggestion` issue on ivy's repo. This issue is then reviewed by our team and if approved, this function would then need to be added not only to the experimental API in ivy but to all its backends along with its test as well. Once that PR is then merged, only then can you proceed with using that function from the frontends for your own PR. Till then this PR would have to be closed or halted.
2. Otherwise you can proceed to remove the implementations you added from the backend and the functional API and just implement the `max_unpool3d` in the frontend using a composition of existing `ivy` functions in this PR and also add its corresponding test that should pass with all the backends.

Let me know it this makes sense. Thanks! :)

2023-09-03 17:25 UTC, hmahmood24 commented on ivy/functional/ivy/experimental/layers.py
> +    )
@Reptilefury This is bound to fail because there is no backend implementations of `max_unpool3d` in any of the backends

2023-10-05 19:32 UTC, hmahmood24 commented
Closing this PR since it has been stale from more than 2 weeks now.

2023-10-05 19:32 UTC, closed without merging