update jax.lax.scan and test functions
unifyai/ivy pull request #22412
Opened 2023-08-23 14:36 UTC by Ahmed-abdelgalil

2023-08-23 15:56 UTC, Ahmed-abdelgalil commented
hi @yopknopixx i just update my test scan function and run it locally and success i create new pull request because i rename branch from master to main can you please review my PR and kindly let me know if there is any Changes 

thanks!

2023-08-24 06:01 UTC, yopknopixx commented on ivy/data_classes/array/experimental/utility.py
This is a Tax front-end task. Could you please explain why its necessary to modify this file?

2023-08-24 06:03 UTC, yopknopixx requested changes

2023-08-24 06:03 UTC, yopknopixx commented on ivy/data_classes/container/experimental/utility.py
Same here

2023-08-24 06:03 UTC, yopknopixx commented on ivy/functional/ivy/experimental/utility.py
And here

2023-08-24 06:03 UTC, yopknopixx commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_utility.py
And here.

2023-08-24 06:05 UTC, yopknopixx commented
@Ahmed-abdelgalil I see some failing tests related to the Tax front-end. Could you please verify that your changes are not causing those failures?

2023-08-24 06:06 UTC, Ahmed-abdelgalil commented on ivy/data_classes/array/experimental/utility.py
i didn't modify any one of them i just modify Control_flow_operatrors.py and test this modify done by root_yash

2023-08-24 06:09 UTC, Ahmed-abdelgalil commented
@yopknopixx frontend failure at ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_mathematical_functions.py::test_jax_polydiv,paddle

my changes at test_control_flow_operators.py::test_jax_scan don't cause failures

2023-08-24 06:31 UTC, Ahmed-abdelgalil commented
@yopknopixx this happen while i try to sync fork and i was think that is done by one of engineers so i didn't modify them and modify only my task at control_flow_operators should i modify them delete changes at these files keep it ??

thanks

2023-08-24 06:37 UTC, yopknopixx commented
@Ahmed-abdelgalil Please remove all changes not relevant to your task. Thanks

2023-08-24 06:43 UTC, yopknopixx commented
> @yopknopixx frontend failure at ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_mathematical_functions.py::test_jax_polydiv,paddle
> 
> my changes at test_control_flow_operators.py::test_jax_scan don't cause failures

Could you verify once that these tests are also failing on `unify:main` to be sure?

2023-08-24 06:47 UTC, yopknopixx commented on ivy/functional/ivy/experimental/utility.py
It seems you deleted the contents of the file completely. Please undo your changes and keep the file as-was.

2023-08-24 07:02 UTC, yopknopixx commented
@Ahmed-abdelgalil What we should have are only two modified files. `ivy/functional/frontends/jax/lax/control_flow_operators.py` and `ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_control_flow_operators.py`.
Could you try backing up your changes, doing a hard reset and then re-introducing your changes? That should clean things up.

2023-08-24 10:00 UTC, Ahmed-abdelgalil commented
@yopknopixx I'm sorry for this confusion this my first time i hope every things clear now 

also there is new failure introduced at display test results what should i do with it 

thanks for your time

2023-08-24 10:42 UTC, yopknopixx commented
@Ahmed-abdelgalil No problem, I'm happy to help. As for the new failure, you should make sure that your changes aren't the cause. To do that, you can check if the same tests are failing on `unifyai:main` without your changes, if they are, you're good to go!

2023-08-24 17:14 UTC, merged