Avg Pool time
unifyai/ivy pull request #22427
Opened 2023-08-23 19:57 UTC by inthedepthsofitall

#22426

2023-08-23 20:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-23 20:49 UTC, inthedepthsofitall commented
#22427 #22427

2023-08-25 11:19 UTC, AnnaTz requested changes

2023-08-25 11:19 UTC, AnnaTz commented on ivy/functional/frontends/paddle/nn/functional/pooling.py
> +#lets se how this works
Hi @inthedepthsofitall, please remove any code except the actual `max_pool1d` and `max_pool2d` functions.

2023-08-25 11:19 UTC, AnnaTz commented on ivy/functional/frontends/paddle/nn/functional/pooling.py
> +#lets se how this works
Also, you will need to add tests for these new functions. Our documentation describes how to do so and you can also look at the existing tests in our codebase a reference.

2023-08-25 11:21 UTC, AnnaTz commented
Are there corresponding ToDo issues for these functions? Please link your PR to them. Thanks!

2023-08-25 14:54 UTC, inthedepthsofitall commented
Hi Anna, I created my own issue as I did not see an average of the pooling
function. I also am not sure what I am getting rid of, asxI added to the
pooling file, unless you are referring that I must create a file called
avg.py.

Also I did create tests for the avg and ran them, but I I will take a look
to see if there was something I did wrong.



On Fri, Aug 25, 2023, 7:21 AM AnnaTz ***@***.***> wrote:

> Are there corresponding ToDo issues for these functions? Please link your
> PR to them. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unifyai/ivy/pull/22427#issuecomment-1693203112>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A64NOEZRXCZYL375YAJCYCTXXCDCTANCNFSM6AAAAAA337FMSM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-28 19:01 UTC, closed without merging