Add ifftn to JAX Frontend
unifyai/ivy pull request #22436
Opened 2023-08-24 04:24 UTC by abdllahdev

Close #22389

2023-08-31 05:44 UTC, hirwa-nshuti requested changes
Hey @abdllahdev 

Check the comments below
Thanks

2023-08-31 05:44 UTC, hirwa-nshuti commented on ivy/functional/frontends/jax/numpy/fft.py
> +    a = ivy.asarray(a, dtype=ivy.complex128)
As it is mentioned in the [Docs](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.fft.ifftn.html) no need to explicitly convert the input to complex, but input itself should be a complex type, this line can be omitted and we specify supported dtypes as complex using `with_supported_dtypes` decorator

2023-09-05 16:57 UTC, hirwa-nshuti requested changes
Hey @abdllahdev 

Thanks for updating the requested changes, would you resolve the linting issues as the lint check is failing you can refer to this [Pre-Commit](https://unify.ai/docs/ivy/overview/deep_dive/formatting.html#pre-commit) guide

Thanks

2023-09-05 17:28 UTC, abdllahdev commented
Hey @hirwa-nshuti, the pre-commit hooks had a problem before but now it's working. I pushed the new changes and it should be fine now. Thanks

2023-09-14 21:13 UTC, abdllahdev commented
Hey @hirwa-nshuti, Can you please check this PR. There are merge conflicts, formating is good and everything should be good to merge. Thanks

2023-09-21 03:57 UTC, hirwa-nshuti requested changes
If you check on bottom section of the PR comments,
You will find that there are merge conflicts and to resolve them you can follow this guide [managing your fork](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#managing-your-fork)

After that we can be able to run the tests on CI.
Thanks

2023-09-29 11:15 UTC, hirwa-nshuti requested changes
Hey @abdllahdev 
would you remove the changes that you added to the Array API submodule

Thanks!

2024-01-07 17:02 UTC, Sarvesh-Kesharwani commented
Closing the PR for the time being, since there has been no activity for more than 2 weeks.

2024-01-07 17:02 UTC, closed without merging