Implemented and tested count_nonzero() function for Jax frontend
unifyai/ivy pull request #22442
Opened 2023-08-24 09:27 UTC by lapatric

Close #22292

2023-08-24 14:00 UTC, lapatric commented
Could you please review when you have time, @hmahmood24?

2023-08-27 08:04 UTC, hmahmood24 requested changes
Hey @lapatric, requested changes for you to address. Also can you please fix the [lint/formatting](https://github.com/unifyai/ivy/actions/runs/5984134710/job/16235014138?pr=22442) issues with your files? Thanks! :)

2023-08-27 08:04 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_numpy/test_searching_sorting.py
> +        keepdims=False,
We are supposed to have strategies for testing the `axis` and `keepdims` arguments as well, just as we have for the `a` argument

2023-09-19 14:14 UTC, hmahmood24 commented
Closing this PR since there has been no activity for more than a week.

2023-09-19 14:14 UTC, closed without merging