Added dosctrings for ivy.astype
unifyai/ivy pull request #2248
Opened 2022-07-23 17:24 UTC by rensortino

When I first tested the function to generate the docstring examples, it raised the following exceptions:
1. `TypeError: astype() got an unexpected keyword argument 'out'`
    which I solved by adding the out argument in the corresponding numpy backend function (if needed, before merging the PR I can add it also to the other backends).
2. `TypeError: Cannot cast array data from dtype('float64') to dtype('int32') according to the rule 'same_kind'`, which was a problem of the `np.copyto` function called inside the numpy `inplace_update`, which I solved by casting the array before giving it to input to `np.copyto`.

2022-07-23 17:27 UTC, rensortino commented
Solves #2020

2022-07-26 13:33 UTC, RitujaPawas commented
@rensortino please add docstrings and docstring examples for `astype()` in `ivy/array/data_type` as well as in `ivy/container/data_type`

2022-07-26 13:33 UTC, RitujaPawas commented
Make sure to request a review when you have made the changes!

2022-08-02 15:38 UTC, RitujaPawas commented
There might be an issue with requesting a review. Thanks for letting me know. I will review ASAP!

2022-08-03 14:12 UTC, RitujaPawas commented
@rensortino  please fix the [lint-issues](https://github.com/unifyai/ivy/runs/7653345152?check_suite_focus=true)  and [test-docstrings issues](https://github.com/unifyai/ivy/runs/7653345018?check_suite_focus=true) related to data_type.py and specific to your function!

2022-08-03 14:35 UTC, RitujaPawas reviewed
make sure you add print statements for printing outputs! and please re-check the values of output.

2022-08-03 14:35 UTC, RitujaPawas commented on ivy/array/data_type.py
> +        ivy.array([[-1., -2.],  [0.,  2.]])
Add a print statement for this.

2022-08-03 14:35 UTC, RitujaPawas commented on ivy/container/data_type.py
> +        {
For dtype, please use ivy.{dtype}

2022-08-03 14:35 UTC, RitujaPawas commented on ivy/container/data_type.py
> +            b: ivy.array([1, 0, 1])
make sure the output is correct, and add print statement for printing outputs

2022-08-05 16:29 UTC, rensortino commented
Hi, after the last commits I checked the tests and there shouldn't be any more related to the `astype` function, as far as it concerns the docstring and lint tests. I hope everything's right, please let me know if there is anything else to fix.

2022-08-12 09:16 UTC, RitujaPawas commented
Sure @rensortino  sorry for the delay. I will take a look and let you know ASAP

2022-08-14 12:58 UTC, RitujaPawas requested changes
Hi @rensortino  can you please pull the latest changes from master and request review again ASAP. Everything looks good.

2022-08-17 05:37 UTC, RitujaPawas approved these changes
hey @rensortino this looks good! Thank you for your contributions!

2022-08-17 05:38 UTC, merged