amin
unifyai/ivy pull request #22488
Opened 2023-08-24 19:42 UTC by Seif-Mohamed1

I look forward to reviewing my pull request

2023-08-24 20:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-24 20:02 UTC, Seif-Mohamed1 commented
amin issue #22448

2023-08-24 20:07 UTC, Seif-Mohamed1 commented
I look forward to reviewing my pull request

2023-08-25 09:32 UTC, Seif-Mohamed1 commented
Can you please reviewing my pull request

2023-08-26 22:44 UTC, MahmoudAshraf97 requested changes

2023-08-26 22:44 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/tensor/math.py
> +
remove functions that are not related to your code

2023-08-26 23:42 UTC, closed without merging