implemented eigvals to frontend
unifyai/ivy pull request #22522
Opened 2023-08-25 09:26 UTC by moamen20

# PR Description 

## Related Issue 

Close #

## Checklist 

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-08-25 10:50 UTC, a0m0rajab commented
Hey, can you add the tests and add the related issue to the PR body?

2023-08-25 12:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-25 11:44 UTC, Aarsh2001 requested changes

2023-09-25 11:44 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_linalg/test_matrix_eigenvalues.py
> +    ret = np.sort(to_numpy(ret)).astype(np.complex128)
Hey @moamen20, can you please rectify the failing tests. There is no such thing as  `to_numpy`

2023-10-02 08:41 UTC, Aarsh2001 commented
Hey @a0m0rajab, closing this PR due to inactivity, feel free to reopen once you're done with your changes, thanks

2023-10-02 08:41 UTC, closed without merging