feat(Backend) : Implements vonneumann_entropy from tensorly to ivy/lineralg
unifyai/ivy pull request #22521
Opened 2023-08-25 06:12 UTC by Enigmafiend

Close #22049

2023-08-25 06:12 UTC, Enigmafiend commented
ivy-gardener

2023-08-30 14:57 UTC, Enigmafiend commented
ivy-gardener

2023-09-07 07:16 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +    dtype = draw(helpers.get_dtypes("float", full=True))
I think there are incompatible `dtypes` being generated here which are causing a few of the tests to fail with an error: 
```python
E   tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
E   	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name:
```
error log: [here](https://github.com/unifyai/ivy/actions/runs/6026565144/job/16349806736?pr=22521#step:3:448)

Maybe try using `helpers.get_dtypes("valid")` and see if that fixes the issue

2023-09-07 07:16 UTC, YushaArif99 requested changes
Left a comment 🙂

2023-09-26 07:02 UTC, YushaArif99 commented on ivy/functional/ivy/experimental/linear_algebra.py
> -    Functional Examples
Could you kindly revert these changes 🙂

2023-09-26 07:03 UTC, YushaArif99 commented on ivy/functional/ivy/experimental/linear_algebra.py
> +def general_inner_product(
where is this function being used?

2023-09-26 07:05 UTC, YushaArif99 requested changes
Hi @Enigmafiend 

Could you kindly address the abovementioned points? Also, could you kindly resolve the merge conflicts so that the CI tests can run? Thanks! 🙂

2023-12-26 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-27 12:50 UTC, closed without merging