Optimizebatchnorm
unifyai/ivy pull request #22535
Opened 2023-08-25 12:59 UTC by hello-fri-end

2023-08-25 13:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-28 02:22 UTC, vedpatwardhan requested changes
Hey @hello-fri-end, just requested a couple of changes apart from the debug statements of course. Thanks for diving into this 😄

2023-08-28 02:22 UTC, vedpatwardhan commented on ivy/functional/ivy/experimental/norms.py
> +    xnormalized = x * inv.astype(ivy.dtype(x), copy=False) + ivy.astype(
ig given that `x` is guaranteed to be an `ivy.Array` we could continue to use `x.dtype` right?

2023-08-28 02:22 UTC, vedpatwardhan commented on ivy/func_wrapper.py
> +        if ivy.curr_backend_str() == "tensorflow":
ig this should be `ivy.current_backend_str()`

2024-03-27 19:43 UTC, closed without merging