Fix tensorflow fft2 backend
unifyai/ivy pull request #22536
Opened 2023-08-25 13:27 UTC by AbdullahSabry

Fixed the backend for `fft2` in tensorflow backend related to the PRs #22366 and #22309 where the tests were failing.

2023-08-25 18:53 UTC, AbdullahSabry commented
Hey @abdulasiraj 

I believe the issue with the function is fixed with the added code. It works with both the PRs mentioned above. Check out the code whenever. Thanks!

2023-08-28 04:09 UTC, abdulasiraj commented on ivy/functional/backends/tensorflow/experimental/layers.py
> +    if out is not None:
Hi @AbdullahSabry,
`out` argument will be handled by `handle_out_argument` decorator. so, you no need to handle this. Please remove this block as it's reduntant.
Thanks

2023-08-28 04:10 UTC, abdulasiraj approved these changes
Everything else looks good to me. just remove the out block and let me know, I'll merge it. thankls!

2023-08-29 04:01 UTC, abdulasiraj requested changes
Hi @AbdullahSabry 
tests are failing locally, can you please double check what's the problem is?
```
Failed: [undefined]AssertionError: returned dtype = complex64, ground-truth returned dtype = complex128
```
P.S: problem is related to tensorflow backend

2023-08-30 04:31 UTC, abdulasiraj approved these changes

2023-08-30 04:31 UTC, merged