update the min function type hints, docstrings and docstring example
unifyai/ivy pull request #2257
Opened 2022-07-24 06:14 UTC by Pirunga

2022-07-24 06:17 UTC, Pirunga commented
#1888

2022-07-25 11:52 UTC, sherry30 requested changes
Hi,

The changes look good, just a few more things need to be added

1. static function for container instance method and its example.
2. example for container instance method

If you have any questions then feel free to ask, I'd be happy to help you out with anything.

Thanks.

2022-07-27 04:39 UTC, sherry30 requested changes
Hi,

A few changes are required:

1. You need to add the instance method examples in their appropriate files, so for array instance method example, you have to add it in `ivy/array/statistical.py` and for container instance method it should go in `ivy/container/statistical.py`.
2. You have to implement static function in container file as well and an example of that.

For all of these, you can checkout `tanh` in elementwise for reference.
you can read all the detailed requirements [here](https://github.com/unifyai/ivy/blob/48069d3a774e279eec2a4fb85b7ace69a8925291/docs/partial_source/deep_dive/13_docstring_examples.rst)

Let me know if you have any more questions.

Thanks.

2022-07-29 05:45 UTC, sherry30 requested changes
i requested 2 changes on specific lines,

other than that you don't have to add 2 examples of container in the functional examples, please remove the one being used as instance method.

2022-07-29 05:45 UTC, sherry30 commented on ivy/container/statistical.py
> +        >>> y = ivy.Container.min(x)
this should be called as a container instance method,
`y = x.min()`

2022-07-29 05:45 UTC, sherry30 commented on ivy/functional/ivy/statistical.py
> +    >>> x = ivy.Container(a=ivy.array([7., 77., 777.]), b=ivy.array([8., 88., 888.]))
indent array `b` on the next line

2022-08-08 08:10 UTC, sherry30 commented
Hi,

everything looks good, I think the only thing left to do is add examples for the array instance method in `ivy/array/statistical.py`.
Also there seem to be some lint errors in `ivy/container/statistical.py`, can you try fixing those.

Thanks

2022-09-05 06:40 UTC, closed without merging