test pre-commit
unifyai/ivy pull request #22600
Opened 2023-08-26 09:12 UTC by NripeshN

2023-08-26 09:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-28 11:23 UTC, AnnaTz approved these changes

2023-08-28 11:24 UTC, AnnaTz commented
You'll have to resolve the conflicts to sync with the latest main branch, but looks good overall. Thanks!

2023-08-29 04:32 UTC, sherry30 reviewed
I would prefer if you leave out helpers folder from the test_ivy folder.
just refactoring the test functions would be nice

2023-08-29 08:33 UTC, NripeshN commented
> I would prefer if you leave out helpers folder from the test_ivy folder. just refactoring the test functions would be nice

I have ignored all files in the helpers folder now!

2023-08-29 10:39 UTC, KareemMAX requested changes
Hey @NripeshN,
I only have this comment that I listed below, other than that LGTM

2023-08-29 10:39 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/config/jax.py
I feel this file and other files under `test_frontends/config` should be excluded from this lint

2023-08-29 10:47 UTC, merged