Adding Random sampling to Numpy Frontend: logseries
unifyai/ivy pull request #22719
Opened 2023-08-28 23:51 UTC by Tanzeel161

# PR Description 

## Related Issue 

Close #21402 

## Checklist 

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-08-30 09:05 UTC, KareemMAX commented
ivy-gardener

2023-08-30 09:06 UTC, KareemMAX requested changes
Hey @Tanzeel161,
I've added some comments that I would like you to address. After that we can run the final tests

2023-08-30 16:42 UTC, Tanzeel161 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +        exclude_min=True,
Hi @KareemMAX , i have made the requested changes. Please approve the workflows. Thanks for the help!!

2023-08-31 12:01 UTC, KareemMAX approved these changes
LGTM, merging now 😄

2023-08-31 12:03 UTC, merged