fixed Nonetype error in scipy.test_eigh_tridiagonal
unifyai/ivy pull request #22785
Opened 2023-08-30 11:21 UTC by humzakt

# PR Description 

fixed Nonetype error in scipy.test_eigh_tridiagonal. Previously the test was not running properly now the test is functional.

Note: The tests are failing due to difference in values from ground truth and Ivy implementation. However since this is an experimental function and the scipy implementation directly uses the ivy backend experimental implementation so tests will automatically pass once the backend is properly working

### Socials: 

twitter.com/humzakt

2023-08-31 10:00 UTC, umairjavaid requested changes
remove print

2023-08-31 10:00 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_scipy/test_linalg/test_linalg.py
> +    print(all_args[-1])
remove print

2023-08-31 10:23 UTC, humzakt commented on ivy_tests/test_ivy/test_frontends/test_scipy/test_linalg/test_linalg.py
> +    print(all_args[-1])
removed

2023-10-18 10:19 UTC, AnnaTz approved these changes
Looks good, thanks!

2023-10-18 10:19 UTC, merged