added code for handling hermitian  = True for pinv linear operation in pytorch frontend
unifyai/ivy pull request #22797
Opened 2023-08-30 14:34 UTC by Monsurat-Onabajo

# PR Description 

this pull request was created to solve this issue : #22793
## Related Issue 

Close #22793
https://github.com/unifyai/ivy/issues/22793

## Checklist 

- [✅] Did you add a function?
- [✅] Did you add the tests?
- [✅] Did you follow the steps we provided?

### Socials: 

[@onabajo3](https://twitter.com/Onabajo3)

2023-08-30 14:55 UTC, Monsurat-Onabajo commented
@Mr-Niraj-Kulkarni Can you review my pull request please

2023-08-31 09:30 UTC, Mr-Niraj-Kulkarni commented on ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py
> +
Please add only parts specific to your implemented function

2023-08-31 09:32 UTC, Mr-Niraj-Kulkarni commented
@Monsurat-Onabajo Hey, I added some comments on the code Please address those Also I see the tests are failing can you please look into that as well?  There are lint issues as well please resolve them

2023-08-31 13:35 UTC, Monsurat-Onabajo commented
@Mr-Niraj-Kulkarni I have worked on the test reviews. I have also run pre-commit tests to solve the linting errors but i noticed that some of the errors that are coming from there are not from my contribution.

2023-09-04 05:31 UTC, zhumakhan requested changes

2023-09-04 05:31 UTC, zhumakhan commented on ivy_tests/test_ivy/test_frontends/test_torch/test_linalg.py
> +    *, dtype_and_input, frontend, test_flags, fn_tree, backend_fw, on_device, hermitian
Please draw the hermitian value from random boolean value generator like below:
```
@handle_frontend_test(
    fn_tree="torch.linalg.pinv",
    dtype_and_input=_get_dtype_and_matrix(batch=True),
    hermitian=st.booleans(),
)
def test_torch_pinv(
    *,
    dtype_and_input,
    frontend,
    test_flags,
    fn_tree,
    backend_fw,
    on_device,
    hermitian,
):
    input_dtype, x = dtype_and_input
    helpers.test_frontend_function(
        input_dtypes=input_dtype,
        backend_to_test=backend_fw,
        frontend=frontend,
        test_flags=test_flags,
        fn_tree=fn_tree,
        on_device=on_device,
        input=x[0],
        atol=1e-02,
        rtol=1e-02,
        hermitian=hermitian
    )
```

and please fix the test failures that appear after that

2023-09-13 17:54 UTC, Monsurat-Onabajo commented
Hi, @Mr-Niraj-Kulkarni ...I was away on a conference and  I did not have access to my computer but i am back now. I tried solving the tasks but there is a circular import that is conflicting with the file i am trying to run, I kept on running into this error. "
ImportError: cannot import name 'array_helpers_dtype_info_helper' from partially initialized module 'ivy_tests.test_ivy.helpers.hypothesis_helpers.array_helpers' (most likely due to a circular import) (C:\Users\Onabajo Monsurat\Documents\venv\lib\site-packages\ivy_tests\test_ivy\helpers\hypothesis_helpers\array_helpers.py)"

2023-09-14 09:01 UTC, Mr-Niraj-Kulkarni commented
> Hi, @Mr-Niraj-Kulkarni ...I was away on a conference and I did not have access to my computer but i am back now. I tried solving the tasks but there is a circular import that is conflicting with the file i am trying to run, I kept on running into this error. " ImportError: cannot import name 'array_helpers_dtype_info_helper' from partially initialized module 'ivy_tests.test_ivy.helpers.hypothesis_helpers.array_helpers' (most likely due to a circular import) (C:\Users\Onabajo Monsurat\Documents\venv\lib\site-packages\ivy_tests\test_ivy\helpers\hypothesis_helpers\array_helpers.py)"

Can you please try updating your branch from the main this might solve the issue

2023-09-14 15:35 UTC, Monsurat-Onabajo commented
> > Hi, @Mr-Niraj-Kulkarni ...I was away on a conference and I did not have access to my computer but i am back now. I tried solving the tasks but there is a circular import that is conflicting with the file i am trying to run, I kept on running into this error. " ImportError: cannot import name 'array_helpers_dtype_info_helper' from partially initialized module 'ivy_tests.test_ivy.helpers.hypothesis_helpers.array_helpers' (most likely due to a circular import) (C:\Users\Onabajo Monsurat\Documents\venv\lib\site-packages\ivy_tests\test_ivy\helpers\hypothesis_helpers\array_helpers.py)"
> 
> Can you please try updating your branch from the main this might solve the issue

I have tried updating the main with my local clone but i am still getting the same error. When I checked, the error is coming from **'ivy_tests\test_ivy\helpers\hypothesis_helpers\array_helpers.py'** line 1513 and 1525 **'array_helpers_dtype_info_helper**' is referencing the backend implementation of it and line 1632 where **array_helpers_dtype_info_helper** is a function on its own, I am stuck because i dont want to change the name of the function so as not to break any code

2024-02-27 16:10 UTC, Ishticode requested changes
Hi @Monsurat-Onabajo 
Thanks for the PR and sorry for the delay on our end. I will take on your PR from now. Could you pls update your test code in accordance with what @zhumakhan had requested above i.e. add in a boolean strategy for hermitian and resolve the conflicts. Free free to request a further review and update after that. Thank you very much :)

2024-03-06 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-03-13 05:53 UTC, closed without merging

2024-03-13 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.