feat: Added 3D Max Pooling Layer and Test
unifyai/ivy pull request #22816
Opened 2023-08-31 06:38 UTC by Bibash06

- Added 'max_pool3d' function to 'pooling.py' for 3D max pooling.
- Implemented test code for the new function.
- Imported 'max_pool3d' function to '__init__.py'.

This commit adds the 'max_pool3d' function to enable 3D max pooling in the pooling module. The function includes parameters for kernel size, stride, padding, dilation, and ceil mode. The commit also includes a test script that applied the new function to input data and printed the output shape and max value.

Closes #<22313>

# PR Description 

## Related Issue 

Close #

## Checklist 

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-08-31 07:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-08-31 10:27 UTC, yopknopixx commented on .idea/ivy.iml
These files should not be changed

2023-08-31 10:28 UTC, yopknopixx commented
Hey @Bibash06 please remove the unnecessary file changes.

2023-09-01 06:28 UTC, yopknopixx requested changes
Hey @Bibash06 I have highlighted several points which need to be addressed. However, before moving forward with making changes, I'd suggest that you go through the relevant documentation as you seem unfamiliar with several aspects of Ivy.

2023-09-01 06:28 UTC, yopknopixx commented on ivy/functional/frontends/paddle/nn/functional/__init__.py
This is unnecessary since `from .pooling import *` already takes care of the import.

2023-09-01 06:28 UTC, yopknopixx commented on .idea/vcs.xml
File not removed. Please remove the file from PR changes.

2023-09-01 06:28 UTC, yopknopixx commented on .idea/runConfigurations/_template__of_py_test.xml
File not removed. Please remove the file from PR changes.

2023-09-01 06:28 UTC, yopknopixx commented on .idea/misc.xml
File not removed. Please remove the file from PR changes.

2023-09-01 06:28 UTC, yopknopixx commented on .idea/ivy.iml
File not removed. Please remove the file from PR changes.

2023-09-01 06:28 UTC, yopknopixx commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_pooling.py
This is not the proper way to implement the tests. Please have a look at `https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html`.

2023-09-01 06:28 UTC, yopknopixx commented on ivy/functional/frontends/paddle/nn/functional/pooling.py
I see two function implementations for `max_pool3d` (only one is expected). One of them calls the backend implementation directly which should not be the case when writing a frontend function.

2023-09-07 16:24 UTC, closed without merging