added t function of paddle frontend and related test cases
unifyai/ivy pull request #22871
Opened 2023-08-31 20:24 UTC by sachelsout

# PR Description 

This PR solves the issue named 't' (which comes under paddle.tensor.linalg). The function definition and related test cases done. All the test cases are passing locally.

## Related Issue 

Close #22865 

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials: 

<a href="https://twitter.com/rohan_dawkhar" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/twitter.svg" alt="rohan_dawkhar" height="30" width="40" /></a>

2023-09-04 10:58 UTC, sachelsout commented
Hi @Infrared1029 , could you please review my PR 😃

2023-09-07 09:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-19 10:06 UTC, sachelsout commented
Hi @Infrared1029 , I resolved merge conflicts and tested the function locally again. But one of the test case is failing (keyError: 'CPU'). This error popped up after I resolved the merge conflicts. Attaching below the screenshot of the error.

![image](https://github.com/unifyai/ivy/assets/86348193/5c5b4823-00ab-43c5-ad91-e4cfc5e546da)

2024-01-18 16:34 UTC, Sarvesh-Kesharwani requested changes

2024-01-18 16:34 UTC, Sarvesh-Kesharwani commented on ivy/functional/frontends/paddle/tensor/linalg.py
> +    return ivy.permute_dims(x, axes=perm)
Remove these changes as well.

2024-02-22 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-29 05:53 UTC, closed without merging

2024-02-29 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.