Added max unpool 2d to paddle frontend api
unifyai/ivy pull request #22900
Opened 2023-09-01 10:19 UTC by wassim249

# PR Description 

Add max unpool 2D to paddle frontend API

## Related Issue 

Close #22898

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

2023-09-01 18:01 UTC, vaithak commented
Hi @wassim249, `max_unpool2d` doesn't exist in `ivy's` functional layer or any of the backends, so this cannot be tested. Maybe you can try pick up the task of adding this in backends first.

2023-09-01 20:31 UTC, wassim249 commented
Alright,thank you @vaithak

2023-09-11 19:46 UTC, wassim249 commented
hello @vaithak, I've opened an issue for the unpool2d in the paddle backend.

2023-10-02 05:58 UTC, YushaArif99 commented on ivy/functional/ivy/experimental/layers.py
> +    return ivy.current_backend(x).max_unpool2d(
is there even a function called `max_unpool2d` in `ivy` 🤔

2023-10-02 05:59 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
why are you adding a test for `test_layers.py`? this has nothing to do with the PR so can you kindly revert this change?🙂

2023-10-02 06:03 UTC, YushaArif99 requested changes
Hi @wassim249 

Apologies for the delay in review. Have been quite swamped with work recently and so haven't really had the time to review any PRs 😅 

With regards to the PR itself, could you kindly address the above-mentioned points? I dont think there is a `ivy.max_unpool2d` function in `ivy`. If that's the case, this function will need to be added to the functional API of Ivy. I'd suggest closing this PR and working on a different one in the meantime as implementing functions for the Functional API is normally reserved for team members and is not open to contributors 🙂

2023-12-27 12:52 UTC, closed without merging