remove lambda and direct bindings for vmap
unifyai/ivy pull request #22949
Opened 2023-09-02 10:31 UTC by musah26

## PR description
removed lambda and direct bindings for vmap in torch backend and function instead defined using def

## Checklist 

- [ ] Step 1. reformatting general vmap function in torch backend

2023-09-02 10:52 UTC, musah26 commented
hello, can someone support review this PR thanks

2023-09-03 06:42 UTC, rishabgit requested changes
Hi @musah26! I'm not entirely clear on how these changes benefit the project. Could you please provide more context and explain what they contribute? Thanks! 😄

2023-09-03 06:51 UTC, musah26 commented
hi @rishabgit was trying to reformat as per the intern challenge that was emailed to me, and one of the steps is to have lambda functions removed and defined with def instead

2023-09-03 06:55 UTC, musah26 commented
@rishabgit , kindly let me know if there is something am doing wrong and how possibly to get it right!
Thanks.

2023-09-16 07:50 UTC, rishabgit commented
Hey @musah26, sorry about the intern tasks not being clear 😓 I'll suggest reading this - https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues and checking out any other PR to get the general convention. I'm closing this PR since this doesn't contribute to the project in its current stage. 😅

2023-09-16 07:50 UTC, closed without merging