Added kl_div loss to ivy experimental api
unifyai/ivy pull request #23054
Opened 2023-09-04 21:35 UTC by Vismay-dev

# PR Description 

This PR has added support for kl_div loss to the ivy experimental api. It has complete support for kl_div in the backends, including ivy array and container instance methods, and test function.

Close #22996

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

2023-09-04 22:22 UTC, Vismay-dev commented
Hey @mobley-trent! Could you please review this pull request?

2023-09-05 12:51 UTC, mobley-trent requested changes

2023-09-05 12:51 UTC, mobley-trent commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +        available_dtypes=helpers.get_dtypes("float"),
When using the decorator for supported / unsupported dtypes, always make sure to use valid dtypes during testing

```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```

2023-09-05 12:51 UTC, mobley-trent commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +        available_dtypes=helpers.get_dtypes("float"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```

2023-09-05 12:51 UTC, mobley-trent commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +
Even after making those changes, tests still fail due to some inconsistencies between the dtypes of the return of the ground truth and your function.

2023-09-05 12:53 UTC, mobley-trent commented
Hi @Vismay-dev your PR looks awesome ✨ 
Once the tests are up and running ok feel free to ping me 🙂

2023-09-06 18:13 UTC, Vismay-dev commented
@mobley-trent there are no new failures introduced by the latest commit of test_kl_div. please review and guide me.

2023-09-08 14:14 UTC, mobley-trent commented
Can you figure out what is causing the returned dtypes to be different ? Try testing the ivy function you've implemented along with its native version with the failing examples.

2023-09-10 02:35 UTC, Vismay-dev commented
@mobley-trent from the running the native and backend-implemented functions separately, I couldn't notice any discrepancy, except numpy's (default backend) implicit conversions to float64. 

I pulled all recent changes in the base branch into my fork and that **seemed to solve the problem with different returned dtypes.** 

The current errors are to do with numpy incompatibility with bfloat16 (which is external to this PR), **which has made other previously implemented loss functions fail as well.** There aren't any other errors stemming from kl_div. My local code-space tests are returning 100% passed.

Please review.

2023-09-11 18:47 UTC, mobley-trent commented on ivy/functional/ivy/experimental/losses.py
> +    return loss
```suggestion

    return ivy.inplace_update(out, loss) if out is not None else loss
```

2023-09-11 18:47 UTC, mobley-trent commented on ivy/functional/ivy/experimental/losses.py
> +    #     size = [1]
Remove this if it is not needed

2023-09-11 18:47 UTC, mobley-trent commented on ivy/functional/backends/numpy/experimental/losses.py
> +        pass
```suggestion
```

2023-09-11 18:47 UTC, mobley-trent commented on ivy/functional/backends/tensorflow/experimental/losses.py
> +        pass
```suggestion
```

I don't think this logic is necessary

2023-09-11 18:47 UTC, mobley-trent commented on ivy/functional/backends/jax/experimental/losses.py
> +        pass
```suggestion
```

2023-09-11 18:47 UTC, mobley-trent commented on ivy/functional/backends/jax/experimental/losses.py
> +    #     size = [1]
```suggestion
```

2023-09-11 18:47 UTC, mobley-trent commented on ivy/functional/backends/tensorflow/experimental/losses.py
> +
```suggestion
```

2023-09-11 19:33 UTC, Vismay-dev commented
@mobley-trent i've made the changes 👍.

2023-09-11 19:36 UTC, mobley-trent commented
Could you also remove the changes to `demos` please 🙂

2023-09-11 20:20 UTC, Vismay-dev commented
@mobley-trent I've removed the changes to demos.

2023-09-12 03:46 UTC, mobley-trent approved these changes
Just curious how did you manage to remove the changes  😅 ?
I think there was a force push to `demos`

2023-09-12 03:48 UTC, merged

2023-09-12 04:53 UTC, Vismay-dev commented
I overwrote the current branch folder with the origin/main version of docs/demos. That reset any changes within docs/demos to fit the most recently pulled version of the base branch which was upstream in my fork 🙂.

Honestly, I don't quite understand why there were changes to docs/demos or what prompted the force push in the first place. My understanding is that it was because of resolving a merge conflict.