Implemented IHFFT and its testing
unifyai/ivy pull request #23115
Opened 2023-09-06 08:58 UTC by ankurr0y

# PR Description 

Pull Request for adding the implementation of ihfft for paddle frontend.

## Related Issue 

Close #23103 

## Checklist 

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials:

2023-09-08 07:06 UTC, ankurr0y commented
Hello @kurshakuz could you review this please?

2023-09-11 09:40 UTC, kurshakuz requested changes
Hey! Your implementation is currently failing due to the error I outlined below. Please first test your PR locally and make sure all tests are passing before requesting a new review. This will reduce a need for back and forward requests and speed up the merge process.

Nevertheless, I have looked into it and showed you the line your PR is generating an error. I have also shown variables that you need to define in order to test.

Thanks!

2023-09-11 09:40 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py
> +        axes=axes,
```
E       TypeError: ihfft() got an unexpected keyword argument 'axes'
```

2023-09-11 09:40 UTC, kurshakuz commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py
> +    ),
You need to define and pass `axis`, `n`, `norm` variables.

2023-09-11 14:46 UTC, ankurr0y commented
@kurshakuz I believe I have done it this time. Could you check now?

2023-09-11 15:07 UTC, kurshakuz commented
> @kurshakuz I believe I have done it this time. Could you check now after the tests have finished running?

Can you first run your test locally and paste the result here? I can take a look after that.

2023-09-12 06:10 UTC, ankurr0y commented
Actually nevermind, here is the test I managed to run successfully.
![image](https://github.com/unifyai/ivy/assets/59106018/526987f0-8633-4658-ad1d-399f5d1e8e48)

2023-09-20 22:48 UTC, ankurr0y commented
Hello @kurshakuz  can you please check this PR now?

2023-10-01 07:42 UTC, ankurr0y commented
Hello @kurshakuz , it's been almost a month.

2023-10-08 09:10 UTC, kurshakuz requested changes
Hello! Your implementation is still failing due to the following cases:
```
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py::test_paddle_ihfft[cpu-numpy-False-False] - RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), complex128) of kernel `fft_r2c` is not registered. Selected wrong DataT...
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py::test_paddle_ihfft[cpu-jax-False-False] - RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), complex128) of kernel `fft_r2c` is not registered. Selected wrong DataT...
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py::test_paddle_ihfft[cpu-tensorflow-False-False] - RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), complex128) of kernel `fft_r2c` is not registered. Selected wrong DataT...
FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_fft.py::test_paddle_ihfft[cpu-torch-False-False] - RuntimeError: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), complex128) of kernel `fft_r2c` is not registered. Selected wrong DataT...
``` 
can you take a look and resolve them?

2023-12-27 13:21 UTC, closed without merging