draft function logic. this is the implementation of the function's logic
unifyai/ivy pull request #23143
Opened 2023-09-06 13:45 UTC by kahina45678

# PR Description 
this is only a partial solution. i tried to implement the function's logic first.

## Related Issue 

Close #

## Checklist 

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-06 14:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-08 21:34 UTC, MahmoudAshraf97 requested changes
Hello @kahina45678 , thanks for the contribution
the function you are trying to implement should be implemented in this file `ivy/functional/frontends/tensorflow/nn.py`, also please read the contribution guide here https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html and check the similar implemented functions in the same open tast

2023-09-11 13:43 UTC, kahina45678 commented
hello @MahmoudAshraf97 !
how about now ? what do i need to add or change ? Thank you.

2023-09-12 10:56 UTC, MahmoudAshraf97 requested changes

2023-09-12 10:56 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/tensorflow/nn.py
we must strictly use ivy functions in the frontends, and also delete the old file as it's not needed anymore

2023-10-01 21:41 UTC, closed without merging