formatting(docstrings): fix common errors
unifyai/ivy pull request #23152
Opened 2023-09-06 14:22 UTC by NripeshN

2023-09-06 15:42 UTC, vedpatwardhan requested changes
I've primarily gone through all framework files changed, and except one fix everything looks good with the framework files. Thanks @NripeshN 😄

2023-09-06 15:42 UTC, vedpatwardhan commented on ivy/functional/ivy/experimental/linear_algebra.py
> +
we'd probably need to also format the lines that follow to fix the indentation

2023-09-07 10:29 UTC, lucasalavapena requested changes
Thanks for the PR @NripeshN , I left some comments/general questions, make sure to check the pydocstyle linting errors in the CI too!

2023-09-07 10:29 UTC, lucasalavapena commented on ivy/functional/ivy/device.py
> +
What is the rationale behind this newline?

2023-09-07 10:29 UTC, lucasalavapena commented on ivy/data_classes/array/elementwise.py
> +
Is this intentional? If so why? I thought you were adding the newline to separate the title from the body or is it to have the line before the codeblock (I seemed to have seen comments on both on your other PR)

2023-09-07 10:29 UTC, lucasalavapena commented on ivy/data_classes/array/activations.py
> +
Why are we adding a newline here? Why only after examples, but not returns, parameters? You failing the format checks :sweat_smile:  D412: No blank lines allowed between a section header and its content ('Examples')

2023-09-07 11:35 UTC, KareemMAX requested changes
As @lucasalavapena mentioned, adding new lines after examples would trigger `D412` on `pydocstyle`. Maybe remove that so we can get a more clearer picture of what changes does happen

2023-10-09 21:19 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-10-10 06:34 UTC, vedpatwardhan commented
Hey @NripeshN @KareemMAX, is this PR still being worked on? Thanks!

2023-12-01 22:01 UTC, closed without merging