fix: skip tensorflow.zeros tests for Paddle backend with ndim >= 10
unifyai/ivy pull request #23156
Opened 2023-09-06 14:50 UTC by akshatvishu

# PR Description: 
Added a condition to skip tests in "test_tensorflow_zeros" when using the Paddle backend and the dimension is 10 or more.

This is a temporary measure until the Paddle backend supports dimensions greater than 9.

## Related Issue: 

Close #23155

2023-09-06 16:16 UTC, akshatvishu commented
Do tell if doing something like this would be better than current solution!
```py
# zeros
@handle_frontend_test(
    fn_tree="tensorflow.zeros",
    input=helpers.get_shape(
        allow_none=False,
        min_num_dims=0,
        max_num_dims=9,# CHANGE
        min_dim_size=0,
        max_dim_size=9, # CHANGE
    ),
    dtype=helpers.get_dtypes("valid", full=False),
)
```

2023-10-04 08:56 UTC, Ishticode requested changes
Hi @akshatvishu 
I think the solution posed in the comment above might work better. The current solution does not fix the test as can be seen in the [logs](https://github.com/unifyai/ivy/actions/runs/6098792966/job/16549761555?pr=23156) by searching for `test_tensorflow_zeros,paddle` which still gives the error `Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is 10.`. Could you perhaps update and test. Thanks 🙂️

2023-10-04 11:53 UTC, akshatvishu commented
> Hi @akshatvishu I think the solution posed in the comment above might work better. The current solution does not fix the test as can be seen in the [logs](https://github.com/unifyai/ivy/actions/runs/6098792966/job/16549761555?pr=23156) by searching for `test_tensorflow_zeros,paddle` which still gives the error `Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is 10.`. Could you perhaps update and test. Thanks 🙂️

Thanks for the suggestions @Ishticode , I have update the code with the suggested changes!

2024-03-27 19:55 UTC, Ishticode approved these changes

2024-03-28 10:49 UTC, merged