added the digitize function on JAX frontend
unifyai/ivy pull request #23198
Opened 2023-09-07 11:59 UTC by HarbdhulQuadri

# PR Description
digitize #23105

## Related Issue

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-12 11:14 UTC, saeedashrraf requested changes

2023-09-12 13:40 UTC, HarbdhulQuadri commented on ivy/functional/frontends/jax/numpy/statistical.py
> +@handle_jax_dtype
I've removed it

2023-09-13 10:47 UTC, HarbdhulQuadri commented
can you please check now ? thanks

2023-09-15 19:48 UTC, saeedashrraf requested changes
Hello @HarbdhulQuadri , it seems like the test implemented does not correctly follow the way provided in the guide. Can you please fix that and update it to follow the latest guide [here](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html#ivy-frontend-tests)? Thank you for your contribution!

2023-09-15 19:52 UTC, HarbdhulQuadri commented
Ok thanks for following up, is it the test alone that has issues or there’s a list and how can I reach out to you faster so I can make great progress on contributing

2023-09-15 21:17 UTC, saeedashrraf commented
Hello @HarbdhulQuadri, I apologize for the delay as it seems like your PR somehow slipped under the radar. Once you are done with the requested changes, just request a review from me and I will let you know if we can merge the PR. Thanks!

2023-09-15 22:11 UTC, HarbdhulQuadri commented
but is it compulsory i write test for the function i implemented...

2023-09-17 23:29 UTC, saeedashrraf commented
As per the [contributors guide](https://unify.ai/docs/ivy/overview/contributing/open_tasks.html#frontend-apis), you should write the tests for the function you implemented and make sure that the function implementation passes the tests successfully. Thanks in advance!

2023-12-30 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-10 05:53 UTC, closed without merging

2024-02-10 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.