fix: Reformat gpu_is_available() function.
unifyai/ivy pull request #23215
Opened 2023-09-07 16:46 UTC by Boghdady9

The function `gpu_is_available()` now correctly determines whether a GPU is available.

# PR Description

## Related Issue

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-07 16:51 UTC, Boghdady9 commented
#23215

2023-09-07 16:59 UTC, Boghdady9 commented
#23132

2023-09-08 08:12 UTC, AnnaTz requested changes
I don't think there was any change really needed for this function to be honest.

2023-09-08 08:12 UTC, AnnaTz commented on ivy/functional/ivy/device.py
> +    ret: bool
Hi @Boghdady9, we don't add typehints here in the docstring. You should remove this.

2023-09-08 08:12 UTC, AnnaTz commented on ivy/functional/ivy/device.py
> +    >>> print(gpu_is_available())
I think this was correct as it was.

2023-09-08 08:12 UTC, AnnaTz commented on ivy/functional/ivy/device.py
> +    return ivy.current_backend().is_gpu_available()
And this one as well. The way you have changed it now the name of the function is wrong.

2023-09-08 08:27 UTC, Boghdady9 commented
ok, thanks for your review. Please check my second commit @AnnaTz

2023-09-08 09:50 UTC, AnnaTz commented
Closing this as there were no formatting changes needed.

2023-09-08 09:50 UTC, closed without merging

2023-09-08 10:45 UTC, Boghdady9 commented
but why you didn’t mark it as completed @AnnaTz

2023-09-08 12:16 UTC, Boghdady9 commented
@AnnaTz 
I marked 'Allow edits by maintainer': please merge the issue