Addsetfield
unifyai/ivy pull request #23263
Opened 2023-09-08 09:56 UTC by assem1390

# PR Description

## Related Issue

Close #23184

## Checklist

- [ ] Did you add a function? yes
- [ ] Did you add the tests? yes
- [ ] Did you follow the steps we provided? to the best of my understanding 

### Socials:

2023-09-27 10:20 UTC, Aarsh2001 requested changes
Hey @assem1390 , can you please fix the failing tests ? Thanks

2023-09-28 07:37 UTC, assem1390 reviewed
request has changed

2023-09-28 09:09 UTC, assem1390 commented
Hi @Aarsh2001 I have fixed the failing test, but now new failing test that previously passed appears

2024-01-18 16:37 UTC, Sarvesh-Kesharwani requested changes

2024-01-18 16:37 UTC, Sarvesh-Kesharwani commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +            raise ValueError("Cannot cast value to the given dtype.") from e
Please remove this try catch block to allow the exception to propagate down to the inner call for improved debugging.

2024-02-22 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-29 05:53 UTC, closed without merging