Added random choice intial commit
unifyai/ivy pull request #23260
Opened 2023-09-08 07:58 UTC by rsaeta

# PR Description
Add frontend for `jax.random.choice`

## Related Issue

Close #23259

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-10-16 11:22 UTC, AnnaTz requested changes

2023-10-16 11:22 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_jax/test_random.py
> +
Hi @rsaeta, could you also assert the shapes are the same? Other than that, looks good to me!

2023-12-29 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-09 05:53 UTC, closed without merging

2024-02-09 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.