added numpy.choose frontend function
unifyai/ivy pull request #23335
Opened 2023-09-09 17:08 UTC by OriginCoding

# PR Description
added numpy.choose frontend function

## Related Issue

Close #23331 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:
kingoforigin -- discord

2023-09-09 17:12 UTC, OriginCoding commented
numpy.choose is absent in backend but i have implemented in frontend

2023-09-15 05:43 UTC, OriginCoding commented
Its almost a week can it get reviewed early

2023-09-20 14:04 UTC, YushaArif99 requested changes
Hi @OriginCoding 

Apologies for the delay in reviewing your PR. Have been swamped with work recently and so haven't had the time to review any PRs 😅.

Regarding the PR itself, I am noticing that the tests are failing due to a `key error` [here](https://github.com/unifyai/ivy/actions/runs/6246782847/job/16958054722?pr=23335#step:3:166). 

Could you kindly look into this? Also, while you're at it, could you kindly ensure the following checks also pass: 
- [linting tests](https://github.com/unifyai/ivy/actions/runs/6246782889/job/16958055101?pr=23335#step:5:155)
- [PR title convention](https://github.com/unifyai/ivy/actions/runs/6247054211/job/16958906837?pr=23335#step:2:43) 

Thanks! 🙂

2023-09-20 18:24 UTC, OriginCoding commented
i tried but not able to solve this error also edited the PR description

2023-09-26 06:32 UTC, YushaArif99 commented on ivy/functional/frontends/numpy/creation_routines/from_existing_data.py
> +    return ivy.choose(arr=arr, choices=choices, mode=mode)
I don't think you should be passing all arguments as `kwargs` when calling `ivy.choose`. Perhaps this is causing the error [here](https://github.com/unifyai/ivy/actions/runs/6246782847/job/16958054722?pr=23335#step:3:231)

2023-09-26 06:34 UTC, YushaArif99 requested changes
Hi @OriginCoding 

The CI tests are still failing with a different error this time 😅. Kindly view the above comment for more detail on this. 
Also, the PR compliance checks are *still* failing [here](https://github.com/unifyai/ivy/actions/runs/6255593787/job/16985174936?pr=23335#step:2:43). Could you kindly resolve these as well?
Edit: The linting tests are also failing. Could you kindly run `pre-commit` on the modified files and push the changes? This should resolve the linting errors.
Thanks! 🙂

2023-10-01 01:00 UTC, closed without merging