Ivy functional
unifyai/ivy pull request #23342
Opened 2023-09-09 18:26 UTC by shephinphilip

## Description

In this updated docstring:

- The parameter descriptions have been corrected and updated to match the actual parameters of the function.
- The default values for optional parameters are specified.
- Examples are provided to demonstrate the usage of the function with both ivy.Array inputs and different values for the offset parameter.

## Related Issue

Close #17543

## Checklist

- [x] Updated the docstring for `ivy.diagflat()` to accurately reflect the function's parameters and behavior.
- [ ] Added tests (if applicable).
- [ ] Followed the steps provided.

### Socials:

N/A

2023-09-13 16:18 UTC, vaithak commented on docs/overview/deep_dive/inplace_updates.rst
> +We also explain the rational for why each implementation is the way it is, and the important differences.
this is wrong, similarly in many other places. Please fix/remove these erroneous grammatical changes.

2023-09-13 16:19 UTC, vaithak commented on docs/overview/deep_dive/inplace_updates.rst
> +The main reason is because these frameworks do not natively support inplace updates so even if multiple native arrays are referencing the same memory buffer, you would ever be able to update it once
same here, this seems to a wrong fix. There are many such cases in the PR.

2023-09-13 16:19 UTC, vaithak requested changes
A lot of these changes are wrong and simply not required, please fix them.

2023-09-13 17:16 UTC, shephinphilip commented
> A lot of these changes are wrong and simply not required, please fix them.

Hi @vaithak, I actually have no idea. All I changed was one file, and after creating a pull request, some of the files are getting changed. All I changed was  update  diagflat docstring in  ivy\functional\ivy\experimental\linear_algebra.py  file

2023-09-24 06:00 UTC, shephinphilip commented
@YushaArif99 
It's been a week , since I  opened this pull request . Could you please review my PR. I would really  appreciate it.

2023-10-02 06:07 UTC, YushaArif99 commented on ivy/functional/ivy/experimental/linear_algebra.py
> -@handle_backend_invalid
could you kindly add this decorator back 🙂

2023-10-02 06:10 UTC, YushaArif99 commented on ivy/functional/ivy/experimental/linear_algebra.py
> -    *,
why remove the asterisk (*)? Arent the remaining parameters keyword-only? The docstring examples are passing the `offset` argument as a kwarg

2023-10-02 06:13 UTC, YushaArif99 commented on ivy/functional/ivy/experimental/linear_algebra.py
> +    x : Union[ivy.Array, ivy.NativeArray]
I dont think there is a need to specify type-hints in the docstring itself. The function's signature does provide type-hints which is sufficient 🙂

2023-10-02 06:14 UTC, YushaArif99 commented on ivy/functional/ivy/experimental/linear_algebra.py
> +    out : Optional[Union[ivy.Array, ivy.NativeArray]], optional
Same goes for here as well 🙂

2023-10-02 06:17 UTC, YushaArif99 requested changes
Hi @shephinphilip 

Apologies for the delay in review. Have been swamped with work recently and so havent had the time to review any PRs 😅 

Could you kindly address the abovementioned points?

2023-12-29 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-10 05:53 UTC, closed without merging

2024-02-10 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.