Added numpy.random.noncentral_chisquare function to Frontend
unifyai/ivy pull request #23378
Opened 2023-09-10 18:01 UTC by Tabassum-Wasila

# PR Description

Close #23370 

## Related Issue

Close #

## Checklist

- [ ] Did you add a function? Yes
- [ ] Did you add the tests? Not yet
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-11 09:22 UTC, KareemMAX requested changes
Hi @Tabassum-Wasila,
I've pointed out some comments. Also, can you please make a new comment with "add_frontend_checklist" without double quotes, spaces nor new lines? A checklist will appear were you can mark what you completed. If you are unsure about somethings you can leave it

2023-09-12 09:37 UTC, KareemMAX commented
add_frontend_checklist

2023-09-12 10:00 UTC, KareemMAX requested changes
Hey @Tabassum-Wasila,
Awesome work, just pointed some small issues. After you address them we will make the final tests and be ready to merge

2023-09-12 12:49 UTC, Tabassum-Wasila commented
Hi @KareemMAX, I've tried to make the changes according to your comments. Can you check if it's okay now? Thanks

2023-09-12 12:49 UTC, Tabassum-Wasila commented
#add_frontend_checklist

2023-09-12 14:01 UTC, Tabassum-Wasila commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +        available_dtypes=helpers.get_dtypes("float"),
Hi @KareemMAX, I think changing it to valid might have resulted in an error on my latest commit, namely, failing run_test(5). Inviting you to check, thanks

2023-09-13 10:37 UTC, KareemMAX requested changes
Hey @Tabassum-Wasila,
I've added some comments that I would like you to address.

Also I checked the failing tests, you may run them locally like this:
```bash
pytest -v ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py::test_numpy_noncentral_chisquare
```
I guess most of them are because of changing dtypes to `valid`, you can resolve that by adding `@with_supported_dtypes()` you may find examples for it like in [here](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/jax/numpy/dtype.py#L75-L78)

2023-09-13 10:37 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +    input_dtype = input_dtype_x + input_dtype_y
I don't feel this is really necessary, what about moving it inline?

2023-09-13 10:37 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_random/test_functions.py
> +    dtype_and_y,
Why don't you use `df` and `nonc` instead of `x` and `y`? I feel it would be more readable

2023-09-19 14:42 UTC, HaiderSultanArc commented on ivy/functional/frontends/numpy/random/functions.py
> +@with_supported_dtypes(
I don't think you need `with_supported_dtypes` decorator for float64 dtype. You should remove this decorator 😄

2023-09-20 19:01 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-24 16:06 UTC, HaiderSultanArc commented
@Tabassum-Wasila there seems to be something wrong with the testing pipeline 🤔! Let's wait till it's fixed and then we can re-run the tests.
![image](https://github.com/unifyai/ivy/assets/59045242/4bdf16e9-c426-41ef-ad14-ca2e744baa2e)

2023-09-26 16:24 UTC, Tabassum-Wasila commented
Hi @HaiderSultanArc, locally it's the same error as before 'Cannot interpret 'ivy.frontends.numpy.dtype('float64') as a data type.' I'm not sure why that error is only showing up in local, though. I had that error for the previous commits as well, but when I pushed here that error never showed up for any of the run failures.

2023-09-26 16:51 UTC, HaiderSultanArc commented
I see you haven't merged with the updated main branch so far. Can you do that real quick so we can be sure? 😄

2023-09-26 17:47 UTC, Tabassum-Wasila commented
@HaiderSultanArc Okay, maybe try and check now? I think nearly all of the errors are 'No module named 'dill'.', but run_test(35) has something different. I don't know what's triggering it though.

2023-09-26 19:43 UTC, HaiderSultanArc commented
@Tabassum-Wasila I'll test your changes and if we have no failing test then I can merge it 😄

2023-09-27 16:54 UTC, merged