add subtract_
unifyai/ivy pull request #23479
Opened 2023-09-12 15:07 UTC by Guilhermeslucas

# PR Description

PR that implements subtract_ on paddle frontend.

## Related Issue

Close #https://github.com/unifyai/ivy/issues/23202

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

2023-09-12 15:10 UTC, Guilhermeslucas commented
@D0m-inic Can I get your review in this one, since its a continuation of this https://github.com/unifyai/ivy/pull/23204 ? Thanks

2023-09-12 15:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-13 03:56 UTC, hello-fri-end requested changes
Hey @Guilhermeslucas, thanks for working on this PR. Just left a minor comment and once you resolve that, make sure that all the tests are passing first and then we can merge the PR :) Happy to help out if you run into any problems. Thanks :)

2023-09-13 03:56 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_math.py
> +        available_dtypes=helpers.get_dtypes("float"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```
This should always be `valid` - if only `float` data-type is supported then that's what `valid` will return.

2023-09-13 12:59 UTC, Guilhermeslucas commented
Thanks for the suggestion and for the fast response @hello-fri-end . I have just accepted your suggestion

2023-09-13 14:03 UTC, Guilhermeslucas commented
@hello-fri-end I am running into these errors. Can you please help me debug it?

![image](https://github.com/unifyai/ivy/assets/9682164/56091d14-46d8-4076-bc66-1f8d64f9ef2b)

2023-09-13 14:08 UTC, Guilhermeslucas commented
I have fixed the issues locally. @hello-fri-end

2023-09-13 20:26 UTC, Guilhermeslucas commented
Tests reports say that there is no failures introduced, so I imagine failures are not related to my change.

2023-09-14 03:44 UTC, hello-fri-end approved these changes
LGTM! Thanks for the contribution @Guilhermeslucas, merging this now :rocket:

2023-09-14 03:45 UTC, merged

2023-09-14 11:24 UTC, Guilhermeslucas commented
Thank you so much for the fast review and merge @hello-fri-end