Searching testing
unifyai/ivy pull request #2349
Opened 2022-07-27 13:31 UTC by Unevilicorn

Instance method for searching
Test for searching
Workflow for test_searching

2022-07-29 13:58 UTC, jiahanxie353 requested changes
Please see the comments :)

2022-07-29 13:58 UTC, jiahanxie353 commented on ivy/functional/backends/jax/searching.py
> +def where(condition: JaxArray, x1: JaxArray, x2: JaxArray) -> JaxArray:
Please do not delete `out` as explained :)

2022-07-29 13:58 UTC, jiahanxie353 commented on ivy/functional/backends/numpy/searching.py
> +def where(condition: np.ndarray, x1: np.ndarray, x2: np.ndarray) -> np.ndarray:
Please do not delete `out` as explained :)

2022-07-29 13:58 UTC, jiahanxie353 commented on ivy/functional/backends/tensorflow/searching.py
> -    out: Optional[Union[tf.Tensor, tf.Variable]] = None
Please do not delete `out` as explained :)

2022-07-29 13:58 UTC, jiahanxie353 commented on ivy/functional/backends/tensorflow/searching.py
> -    out: Optional[Union[tf.Tensor, tf.Variable]] = None
Please do not delete `out` as explained :)

2022-07-29 13:58 UTC, jiahanxie353 commented on ivy/functional/backends/tensorflow/searching.py
> -    out: Optional[Union[tf.Tensor, tf.Variable]] = None
Please do not delete `out` as explained :)

2022-07-29 13:58 UTC, jiahanxie353 commented on ivy/functional/backends/torch/searching.py
> -    out: Optional[torch.Tensor] = None
Please do not delete `out` as explained :)

2022-07-29 20:01 UTC, djl11 requested changes

2022-07-29 20:01 UTC, djl11 commented on ivy/functional/backends/jax/searching.py
> +def nonzero(x: JaxArray, *, out: Optional[JaxArray] = None) -> Tuple[JaxArray]:
we should not have the `out` argument for this function. The `out` argument is only relevant for functions which return a single array.

2022-08-02 06:36 UTC, djl11 approved these changes
lgtm!

2022-08-02 08:08 UTC, merged