added rrftn to Paddle Frontend (#23484)
unifyai/ivy pull request #23537
Opened 2023-09-13 15:09 UTC by Kilvny

# PR Description
added rrftn to Paddle Frontend and added tests related to it

## Related Issue
 (#23484)

Close #23484 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-13 16:10 UTC, Kilvny commented
Why these 2 check are failing, can you help me with that?

2023-09-14 14:00 UTC, KareemMAX requested changes
Hey @Kilvny, seems like you have edited the demos submodule by mistake. Can you please revert that?

2023-09-14 16:36 UTC, Kilvny commented
> Hey @Kilvny, seems like you have edited the demos submodule by mistake. Can you please revert that?

Done @KareemMAX

2023-09-15 13:41 UTC, Kilvny commented
@Mr-Niraj-Kulkarni

2023-09-19 12:12 UTC, Kilvny commented on ivy/functional/frontends/paddle/fft.py
> +    rfft_result = ivy.rfftn(x, s=s, axes=axes, norm=norm, name=name)
Thank you, the change is done, 
FYA

2023-10-09 05:24 UTC, YushaArif99 requested changes
Hi @Kilvny 

Apologies for the delay in review. Have been a little swamped with work recently and so havent had the time to review any PRs 😅 

With regards to the PR itself, the implementation does look good overall. However, I am noticing that the CI tests are failing [here](https://github.com/unifyai/ivy/actions/runs/6235375100/job/16924466164?pr=23537#step:3:200) with the following error: 
```python
E   ivy.utils.exceptions.IvyBackendException: tensorflow: rfftn: Invalid FFT input: `x` must be of a real dtype. Received: <dtype: 'complex128'>
```

Could you kindly look into fixing this and re-request a review once that's done? Thanks!😄

2023-11-26 14:16 UTC, Kilvny commented
> [YushaArif99](/YushaArif99)

Hi @YushaArif99 Thank you so much for the reply,
Apologies for taking so long to work on this changes, 
I was pretty busy and I got a new job recently

anyways, I resolved the conflicts, but regarding the checks that fails, I need some help and guidance I don't know exactly what causes the tests to fail, your help is highly appreciated 

@KareemMAX

2024-01-01 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-15 05:53 UTC, closed without merging

2024-02-15 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.