Add Paddle frontend index_sample to search.py
unifyai/ivy pull request #23562
Opened 2023-09-13 19:25 UTC by Hazannovich

# PR Description
- New Paddle frontend index_sample function was added to search.py.
- Test for the new function in test_search.py

## Related Issue

# 23165

Close #23165

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you follow the steps we provided?

### Socials:

2023-09-13 23:59 UTC, a0m0rajab commented
Hi @Hazannovich thank you for the PR, I just changed the title and removed a space at the beginning of it, which caused the semantic checks to fail. 

Thank you for contributing to ivy though!

2023-10-03 05:36 UTC, YushaArif99 commented on ivy/functional/frontends/paddle/search.py
> +def index_sample(x, index):
the signature of `index_select` does not match the original function's signature [here](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/index_select_cn.html#paddle.index_select)

2023-10-03 05:48 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_search.py
> +        max_num_dims=2,
the array and axis generation strategy also seems quite restrictive to me. The input `x` in [paddle.index_select](https://github.com/PaddlePaddle/Paddle/blob/release/2.5/python/paddle/tensor/search.py#L312) can be any n-dim tensor so there's no need to limit it to 2D. 
You'll also need to add the generation strategy for the `axis` parameter which can be in the range of `[-dim, dim-1]` where `dim` is the dimension of the input `x`

2023-10-03 05:49 UTC, YushaArif99 requested changes
Hi @ILB-96 

Apologies for the delay in review. Had been a little swamped with work recently and so haven't really had the time to review any PRs 😅 

Could you kindly address the abovementioned points. Feel free to re-request a review once these have been resolved and all relevant tests still pass. Thanks 🙂

2023-10-03 05:57 UTC, YushaArif99 approved these changes
Apologies for the previous comments. It turns out I was reviewing the wrong function here 😂. I thought this PR was implementing `paddle.index_select` which is slightly different from `paddle.index_sample` (which is what the PR is **actually** implementing). 

With this out of the way, the changes look good to me now 👍🏼

2023-10-03 06:01 UTC, merged