added complex dtype support for silu
unifyai/ivy pull request #23607
Opened 2023-09-14 15:33 UTC by mosesdaudu001

# added complex dtype support for silu

2023-09-14 16:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-15 19:05 UTC, jshepherd01 requested changes

2023-09-15 19:05 UTC, jshepherd01 commented on ivy/functional/ivy/experimental/activations.py
>  def silu(
I think you missed the `@handle_complex_input` decorator

2024-03-27 20:06 UTC, Ishticode commented
closing this as the suggested changes by @jshepherd01 have not been made for about 6 months. Please feel free to reopen and resolve conflicts and request a review if you would like another look. Thank you very much all :)

2024-03-27 20:06 UTC, closed without merging