Reformat Cross
unifyai/ivy pull request #2363
Opened 2022-07-28 03:53 UTC by Ajay6601

2022-07-28 08:35 UTC, Ajay6601 commented
Hi,
Can you able to tell me the requested changes need to be made?

2022-07-28 08:38 UTC, VedPatwardhan requested changes
Hi @Ajay6601, thanks for contributing, there are a few changes to be made to your PR before we get it merged along with the one I've suggested near the line of code concerned. :
`functional/ivy/linear_algebra.py`: 
1. The examples inside `functional/ivy/linear_algebra.py` should not need a header like on line 197.
2. Please remove the examples under `With ivy.NativeArray inputs:`
3. Please update the examples with `With one ivy.Container input` and `With multiple ivy.Container inputs`.
4. Please adjust the header of examples on line 224 to be on a single line.
5. Please remove the examples under `With a combination of ivy.NativeArray and ivy.Array inputs`.
6. Instance method examples shouldn't be in `functional/ivy/linear_algebra.py` please remove them from there.

Let me know if you have any questions. Thanks 🙂

2022-07-28 08:38 UTC, VedPatwardhan commented on ivy/functional/ivy/linear_algebra.py
>      Functional Examples
This section should be named `Examples`.

2022-07-28 08:40 UTC, VedPatwardhan commented
Also, please type in the number of the issue you've created so that I can link it to your PR, thanks 🙂

2022-07-28 08:43 UTC, Ajay6601 commented
#2138

2022-07-29 05:39 UTC, Ajay6601 commented
Still is there anything need to be changed.

2022-07-29 07:28 UTC, VedPatwardhan requested changes
Hi @Ajay6601, thanks for making the changes, they look fine to me. However, the docstring tests weren't working yesterday because of a segmentation fault because of which we won't be able to see the docstring test results for your PR. They are working now, so you can just merge the current master code into your branch and re-request my review so that we can take a look at the tests.
Let me know if you have any questions. Thanks 🙂

2022-07-29 11:25 UTC, Ajay6601 commented
I have merged with branch

2022-07-29 12:11 UTC, VedPatwardhan requested changes
Hi @Ajay6601, thanks for making the changes. I have suggested some more changes doing which would get the lint and numpy style docstring tests passing apart from the ones that are already failing on master. The docstring tests are already passing for our function.
Let me know if you have any questions. Thanks 🙂

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/array/linear_algebra.py
> +            the axis (dimension) of x1 and x2 containing the vectors for which to compute
This line is longer than 88 characters, which is why it fails the lint tests

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/array/linear_algebra.py
> +            an array containing the element-wise products. The returned array must have a
This line is longer than 88 characters, which is why it fails the lint tests

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/container/linear_algebra.py
> +            the axis (dimension) of x1 and x2 containing the vectors for which to compute
This line is longer than 88 characters, which is why it fails the lint tests

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/container/linear_algebra.py
> +            an array containing the element-wise products. The returned array must have a
This line is longer than 88 characters, which is why it fails the lint tests

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/container/linear_algebra.py
> +            the axis (dimension) of x1 and x2 containing the vectors for which to compute
This line is longer than 88 characters, which is why it fails the lint tests

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/container/linear_algebra.py
> +            an array containing the element-wise products. The returned array must have a
This line is longer than 88 characters, which is why it fails the lint tests

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/container/linear_algebra.py
> +        x1
this argument should be `self` here.

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/container/linear_algebra.py
> +        out
`out` is added twice.

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/container/linear_algebra.py
> +        out
`out` is added twice.

2022-07-29 12:11 UTC, VedPatwardhan commented on ivy/functional/ivy/linear_algebra.py
there shouldn't be a blank line here

2022-07-29 23:55 UTC, Ajay6601 commented
Hi,
It seems like lint tests are passed.

2022-07-30 06:58 UTC, VedPatwardhan approved these changes
lgtm! Thanks for contributing 🙂

2022-07-30 06:58 UTC, merged