using `assume` in ivy_tests
unifyai/ivy pull request #2364
Opened 2022-07-28 04:28 UTC by rush2406

2022-07-28 04:39 UTC, rush2406 commented
In some tests, there are checks for the backend call such as [here](https://github.com/unifyai/ivy/blob/fb0a54a7ddbe80cf85033366fac25f7a7bf2b360/ivy_tests/test_ivy/test_functional/test_core/test_general.py#L138). Are these also to be replaced with `assume`?

2022-07-28 07:18 UTC, djl11 requested changes
a couple of requested changes, I haven't gone through all of it. Could you please make these changes in all files and the re-request a review? Thanks!

2022-07-28 07:18 UTC, djl11 commented on ivy_tests/test_ivy/test_functional/test_core/test_device.py
> +        assume(not (ivy.current_backend_str() in ["tensorflow", "jax"]))
let's use `fw` rather than `ivy.current_backend_str`, the same goes for all other tests.

2022-07-28 07:18 UTC, djl11 commented on ivy_tests/test_ivy/test_functional/test_core/test_dtype.py
> +        assume(isinstance(res, ivy.NativeDtype))
we should not be removing any `assert` statements, these are added for a reason, and the test should fail if these are not met.

2022-07-28 07:20 UTC, djl11 commented
> * In some tests, there are checks for the backend call such as [here](https://github.com/unifyai/ivy/blob/fb0a54a7ddbe80cf85033366fac25f7a7bf2b360/ivy_tests/test_ivy/test_functional/test_core/test_general.py#L138). Are these also to be replaced with `assume`?
> * There are a few functions which still have pytest implementations so I haven't made changes in [these](https://github.com/unifyai/ivy/blob/fb0a54a7ddbe80cf85033366fac25f7a7bf2b360/ivy_tests/test_ivy/test_functional/test_core/test_meta.py#L492) currently . Should I change for them as well?

Yes these backend checks should also be replaced with `assume`, we are in the process of changing the backend selection to be governed by hypothesis, which will then make these `assume` statements work correctly.

Yes you are correct, there is no need to add `assume` into the `pytest` implementations

2022-07-28 15:46 UTC, djl11 requested changes

2022-07-28 15:46 UTC, djl11 commented on ivy_tests/test_ivy/test_functional/test_core/test_device.py
> +        assume(not (call is helpers.torch_call))
we should replace all `call is helpers.<name>_call` logic with `fw == "backend_name"` logic, both do exactly the same thing.

2022-07-30 14:10 UTC, djl11 approved these changes
lgtm!

2022-07-30 18:56 UTC, merged