Add Dockerfile for Apple Silicon Macs
unifyai/ivy pull request #23650
Opened 2023-09-15 10:06 UTC by NripeshN

2023-09-18 05:42 UTC, vedpatwardhan requested changes
Just tried building an image and then a container locally, there seem to be a few issues. 
1. The default `python` version is `2.7`, `python3` is `3.7` but our main focus has been on `3.8` and `3.10`.
2. Secondly, I was able to import ivy in a `3.7` console, but not sure if it's installed correctly because on doing `dir(ivy)`, it returns `['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']` meaning none of the functions are accessible.
3. The folder structure in the container contains the `requirement_mappings_apple_silicon.json` file alongside `ivy` in the root folder of the project, we should be cleaning that up at the end of building.

Happy to know what you and the others think, thanks @NripeshN 😄

2023-09-18 07:18 UTC, NripeshN commented
> Just tried building an image and then a container locally, there seem to be a few issues.
> 
> 1. The default `python` version is `2.7`, `python3` is `3.7` but our main focus has been on `3.8` and `3.10`.
> 2. Secondly, I was able to import ivy in a `3.7` console, but not sure if it's installed correctly because on doing `dir(ivy)`, it returns `['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']` meaning none of the functions are accessible.
> 3. The folder structure in the container contains the `requirement_mappings_apple_silicon.json` file alongside `ivy` in the root folder of the project, we should be cleaning that up at the end of building.
> 
> Happy to know what you and the others think, thanks @NripeshN 😄

Hi @vedpatwardhan, I have fixed all the above mentioned issues

2023-09-18 08:16 UTC, vedpatwardhan requested changes
The issue mentioned in the 2nd point of the previous review still seems to be there, just tried building again, the other 2 are resolved. Thanks @NripeshN 😄

2023-09-18 14:13 UTC, RickSanchezStoic commented
> The issue mentioned in the 2nd point of the previous review still seems to be there, just tried building again, the other 2 are resolved. Thanks @NripeshN 😄

Just curious are you having issues with the ivy locally installed or the one in the docker image? Because the ivy that is locally on your system should be picked at all times rather than the one in the image. I can't comment further on the Apple image since I don't have an Apple or arm64 device to test this out.

2023-09-18 14:16 UTC, RickSanchezStoic requested changes
I can't comment on the Apple image, but yeah some changes in the other docker files don't seem to be needed.

2023-09-18 14:16 UTC, RickSanchezStoic commented on docker/Dockerfile
> +
I don't think we need this, codespaces handle this itself.

2023-09-18 14:16 UTC, RickSanchezStoic commented on docker/DockerfileGPU
> +
Same as cpu Dockerfile

2023-09-20 06:26 UTC, RickSanchezStoic commented on docker/DockerfileGPUMultiCuda
> +
same changes to be made here too.

2023-09-20 06:26 UTC, RickSanchezStoic commented on docker/DockerfileMultiversion
> +# Post installation steps
same changes to be made here too.

2023-09-20 06:27 UTC, RickSanchezStoic requested changes
just some more changes

2023-09-20 06:43 UTC, merged

2023-09-20 06:54 UTC, vedpatwardhan commented on docker/DockerfileAppleSilicon
> +RUN chmod +x post_create_commands.sh && \
I think we should've also updated the other dockerfiles to make use of the `post_create_commands` script and decoupled it from the `.devcontainer` to also run those commands when the user isn't necessarily using a vscode devcontainer as we discussed @NripeshN 😅