feat: numpy loadtxt frontend function
unifyai/ivy pull request #23728
Opened 2023-09-16 21:26 UTC by khawajaJunaid

# PR Description
This PR add the loadtxt frontend functionality for `numpy.loadtxt`

## Related Issue

Close #23417 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-17 09:59 UTC, khawajaJunaid commented
hi @YushaArif99 can you guide me on how I can implement the test function correctly

2023-09-26 12:31 UTC, khawajaJunaid commented
@YushaArif99 can you please review so I can make necessary fixes

2023-10-02 05:18 UTC, YushaArif99 requested changes
Hi @khawajaJunaid 

Apologies for the delay in review. Have been quite swamped with work recently and so haven't had the time to review any PRs 😓 

With regards to your PR, I am a bit confused as to why you've gone on to implementing the `loadtxt` function for **all** backends. 

I think the logic seems generic enough that you could implement it as a compositional function in `ivy` rather than having backend-specific implementations. You might've already had a look into this but in case you haven't, try to read through the implementation of [`np.loadtxt`](https://github.com/numpy/numpy/blob/v1.26.0/numpy/lib/npyio.py#L1100) and see if we can reuse the logic purely using ivy functions.

On a side note, I also think there's a possibility of directly calling `np.loadtxt` in the frontend and then converting the np ndarray to the correct type (i.e `np ndarray` -> `ivy array` -> `np frontend array`). This will add a dependency to Numpy but I think that is the assumption that `ivy` works with as well.

2023-10-02 13:04 UTC, khawajaJunaid commented
hello @YushaArif99, thanks for the reply :) ! 
My first approach after reading the documentation was that the numpy backend had the loadtxt function so i decided to go with the mixed functon implementation i.e that you see implemented in different backends. However, I went through the numpy.loadtxt function source code and found that It can be implemented in ivy and thats what I have been doing (havent pushed the commits yet). I have tried to reuse the np.loadtxt function, and wrote it in ivy creation helpers so i can implement it as a composite function, there are some functions within the loadtxt that use various numpy core libraries that has been the issue for me

2023-10-03 16:04 UTC, khawajaJunaid commented
@YushaArif99 can I get your discord for quick questions, I raised the issue in the frontends > numpy and **felix** said that we should not add numpy as a dependency (want to discuss this as well). I wanted your discord to discuss the implementation, there are a lot of arguments and functionalities that numpy.loadtxt provides which also use numpy's core libraries coded in C

2023-10-09 04:42 UTC, YushaArif99 reviewed
Hi @khawajaJunaid 

Sure. Here's my discord username : `yushkk99`

2023-10-09 18:26 UTC, khawajaJunaid commented
Hello @YushaArif99,
Thanks I have reached out to you on discord

2024-01-01 18:16 UTC, Sarvesh-Kesharwani commented
Hi @khawajaJunaid , 
please resolve the merge conflicts so we can proceed with your pull request.

2024-01-08 14:38 UTC, Sarvesh-Kesharwani commented
Hi @khawajaJunaid,
![image](https://github.com/unifyai/ivy/assets/22115102/5c96eb72-08b3-49dc-b849-fb63e93ed03b)
![image](https://github.com/unifyai/ivy/assets/22115102/0f55419f-a67f-41b0-9be9-1e2f0043e15e)
Please work on fixing these errors and other suggested changes.

2024-01-08 14:39 UTC, Sarvesh-Kesharwani approved these changes

2024-01-08 14:39 UTC, Sarvesh-Kesharwani commented on ivy/functional/backends/numpy/creation.py
> +    )
Please remove these changes unrelated to your PR.

2024-02-16 05:10 UTC, closed without merging