`ivy.experimental.tensor_train`
unifyai/ivy pull request #23799
Opened 2023-09-18 09:28 UTC by mobley-trent

This PR adds the `tensor_train` function to the ivy experimental API

Ref:
- [TensorLy](https://github.com/tensorly/tensorly/blob/main/tensorly/decomposition/_tt.py#L8)

2023-09-25 04:21 UTC, hello-fri-end requested changes
Hey @mobley-trent , thanks for working on this. Just left a few minor comments. Happy to review again after you have resolved these :smile:

2023-09-25 04:21 UTC, hello-fri-end commented on ivy/functional/ivy/experimental/linear_algebra.py
> +):
let's add a type hint for the returned type here.

2023-09-25 04:21 UTC, hello-fri-end commented on ivy/data_classes/container/experimental/linear_algebra.py
> +    ):
type-hint missing

2023-09-25 04:21 UTC, hello-fri-end commented on ivy/data_classes/container/experimental/linear_algebra.py
> +    ):
type-hint mmissing.

2023-09-25 04:21 UTC, hello-fri-end commented on ivy/data_classes/array/experimental/linear_algebra.py
> +    ):
type-hint missing.

2023-09-26 08:35 UTC, mobley-trent commented
@hello-fri-end I don't know why the ivy test is failing. Maybe because it can't parse the returned ivy.TTTensor data structure. But I think my implementation should've worked 🤔 
The tests I implemented from Tensorly are passing though

2023-10-04 05:19 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +    rank = [1]
Hey @mobley-trent, can you explain this?

2023-10-04 05:27 UTC, hello-fri-end commented
Could you also link the issue no. in the PR title please?

2023-10-04 13:47 UTC, merged