fix: setting min and max as default `None` in `ivy.clip`
unifyai/ivy pull request #23956
Opened 2023-09-18 12:37 UTC by ShreyanshBardia

… as well

# PR Description

## Related Issue

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-18 12:39 UTC, ShreyanshBardia commented
Hey @hello-fri-end, even though we refactored `ivy.clip` we missed updating the function signature, thus not enabling the user to pass only min or max as arguments. Also to make this work, I have removed the condition of them being `positional-only ` arguments.

2023-09-18 13:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-20 11:11 UTC, ShreyanshBardia commented
Hey @hello-fri-end, please take a look at this PR, whenever you find some time

2023-09-21 08:08 UTC, hello-fri-end requested changes
Hey @ShreyanshBardia ! Thanks for looking into this again- just left a minor comment and after that we're good to merge :)

2023-09-21 08:08 UTC, hello-fri-end commented on ivy/functional/backends/numpy/manipulation.py
> +    x_max: Union[Number, np.ndarray] = None,
```suggestion
    x_min: Optional[Union[Number, np.ndarray]] = None,
    x_max: Optional[Union[Number, np.ndarray]] = None,
```

2023-09-21 08:08 UTC, hello-fri-end commented on ivy/functional/backends/paddle/manipulation.py
> +    x_max: Union[Number, paddle.Tensor] = None,
same as above

2023-09-21 08:08 UTC, hello-fri-end commented on ivy/functional/backends/tensorflow/manipulation.py
> +    x_max: Union[Number, tf.Tensor, tf.Variable] = None,
same as above

2023-09-21 08:08 UTC, hello-fri-end commented on ivy/functional/backends/torch/manipulation.py
> +    x_max: Union[Number, torch.Tensor] = None,
same as above

2023-09-21 08:08 UTC, hello-fri-end commented on ivy/functional/ivy/manipulation.py
> +    x_max: Union[Number, ivy.Array, ivy.NativeArray] = None,
same as above

2023-09-21 18:30 UTC, merged