NumPy Gradients Docstring tests
unifyai/ivy pull request #2402
Opened 2022-07-29 08:02 UTC by johanjino

2022-07-29 14:10 UTC, djl11 requested changes

2022-07-29 14:10 UTC, djl11 commented on ivy/functional/ivy/gradients.py
> +setattr(execute_with_gradients, "computes_gradients", True)
`execute_with_gradients.computes_gradients = True` is cleaner, same in other locations across the code.

2022-07-29 14:10 UTC, djl11 commented on ivy_tests/test_docstrings.py
> +                try:
you have only added this for `ivy.Array` instance method tests, we should also add it for `ivy.Container` instance method tests and functional tests below.

2022-07-29 14:10 UTC, djl11 commented on ivy_tests/test_docstrings.py
> +                except AttributeError:
we shouldn't use `try` `except` for this, we can do something like `gradient_incompatible = not backend.supports_gradients and hasattr(method, "computes_gradients") and method.computes_gradients`

we always evaluate expressions in `and`, `or` etc. from left to right, and this stops as soon as an evaluation leads to `False`, meaning that `method.computes_gradients` will not be evaluated if `hasattr(method, "computes_gradients")` returns `False`.

But actually, we should implement a simple dedicated helper function for this called `gradient_incompatible_function`, in a similar vein to [function_unsupported_dtypes](https://github.com/unifyai/ivy/blob/3dda99b1ed295e0ac67de7c4170dd041c23b78bc/ivy/functional/ivy/data_type.py#L1134) etc.

This helper function implementation can be as simple as:

```
return not ivy.supports_gradients and hasattr(fn_in, "computes_gradients") and fn_in.computes_gradients
```

2022-08-01 14:30 UTC, johanjino commented
Hey @djl11 

I have made the changes. Thank you so much for pointing these out, I can definitely write more cleaner codes now 😄

2022-08-02 06:41 UTC, djl11 approved these changes
lgtm!

2022-08-03 05:06 UTC, merged