Binary cross entropy
unifyai/ivy pull request #24962
Opened 2023-09-19 18:24 UTC by RummanAli

# Binary Cross Entropy Loss added to experimental.

## Related Issue

Close #23910

2023-09-21 12:48 UTC, RummanAli commented
@mohame54 1 test is failing due to some mismatch in outputs of paddle backend and tensorflow frontend
![image](https://github.com/unifyai/ivy/assets/45504456/1471385e-33a4-4a18-9c3e-146acd4d1921)

2023-09-28 12:10 UTC, mohame54 commented
Hi @RummanAli thanks for your contribution,

2023-09-28 12:11 UTC, mohame54 commented
I have some questions and modifications.

2023-09-28 12:15 UTC, mohame54 commented on ivy/data_classes/array/experimental/losses.py
you should modify your doc string a little bit like here
```
"""
        ivy.Array instance method variant of ivy.binary_cross_entropy. This method simply wraps the
        function, and so the docstring for ivy.binary_cross_entropy also applies to this method with
        minimal changes.
        Parameters
        ----------
        self
            input array containing true labels. # you should here specify what the input array is like you could specify that they  are  probabilities.
        target
            input array containing targeted labels. # also here you should specify that they are the same shape as input array with values between 0 and 1.
"""
```

2023-09-28 12:24 UTC, mohame54 commented on ivy/data_classes/container/experimental/losses.py
Also in here.

2023-09-28 12:31 UTC, mohame54 commented on ivy/functional/backends/jax/experimental/losses.py
- I don't know why you wrote this function **poisson_nll_loss**  and didn't use it.
- also you wrote **_apply_loss_reduction** and didn't use it.

2023-09-28 12:33 UTC, mohame54 commented on ivy/functional/backends/numpy/experimental/losses.py
also in here you didn't use **_apply_loss_reduction** function

2023-09-28 13:00 UTC, RummanAli commented on ivy/functional/backends/jax/experimental/losses.py
So basically poison loss function was added to main branch and it had conflicts with my branch so I just merged the upstream branch to my code.

2023-09-28 13:01 UTC, mohame54 commented
also you should look into lint errors and resolve them and follow the semantic check. @RummanAli

2023-09-28 13:01 UTC, RummanAli commented on ivy/functional/backends/numpy/experimental/losses.py
This was also from upstream main branch

2023-09-28 13:03 UTC, RummanAli commented on ivy/functional/ivy/experimental/losses.py
okok

2023-09-28 13:13 UTC, RummanAli commented
> also you should look into lint errors and resolve them and follow the semantic check. @RummanAli

okkk

2023-09-29 16:43 UTC, mohame54 commented on ivy/functional/backends/jax/experimental/losses.py
Oh, if that's the case

2023-09-29 16:44 UTC, mohame54 commented
Hi @RummanAli could resolve your PR conflicts and check my suggestions? thank you.

2023-09-29 22:27 UTC, RummanAli commented
> Hello, thanks for reviewing. I have made all the changes as you asked.

2023-09-29 22:28 UTC, RummanAli commented
> Hi @RummanAli could resolve your PR conflicts and check my suggestions? thank you.

2023-09-30 11:06 UTC, mohame54 commented
> @mohame54 1 test is failing due to some mismatch in outputs. the error says: "the results from backend paddle and ground truth framework tensorflow do not match" ![image](https://user-images.githubusercontent.com/45504456/269616744-1471385e-33a4-4a18-9c3e-146acd4d1921.png)
 
Your implementation for each backend should give the same outputs with little `unnoticeable` differences so if that error appeared to you, you should check your backend implementations.

2023-09-30 11:15 UTC, RummanAli commented
> > @mohame54 1 test is failing due to some mismatch in outputs. the error says: "the results from backend paddle and ground truth framework tensorflow do not match" ![image](https://user-images.githubusercontent.com/45504456/269616744-1471385e-33a4-4a18-9c3e-146acd4d1921.png)
> 
> @RummanAli Your implementation for each backend should give the same outputs with little `unnoticeable` differences so if that error appeared to you, you should check your backend implementations.

Yea I kind of resolved it but currently anew error has propped up:
![image](https://github.com/unifyai/ivy/assets/45504456/457c6d38-da2b-4655-b35e-0d9b9ae5b131)
do you know what could be the issue here?

2023-09-30 11:17 UTC, RummanAli commented
@mohame54 and tests are not running due to this error.

2023-09-30 11:25 UTC, mohame54 commented
Hi @RummanAli everything seems ok but I have some requests if you could fulfill them I will merge your PR I know it's too much but bear with me 😄.

- [ ] you should add the weight argument to **binary_cross_entropy**  function to fulfill the superset behavior like in [here](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html)  
- [ ] you should use **_apply_loss_reduction** in your backend functions to avoid code repetitions.
- [ ] you should solve your code lint errors

2023-09-30 11:27 UTC, mohame54 commented
> @mohame54 and tests are not running due to this error.

you could change the ground truth backend to another backend for example `jax` or `torch`

2023-09-30 11:30 UTC, mohame54 commented
> > > @mohame54 1 test is failing due to some mismatch in outputs. the error says: "the results from backend paddle and ground truth framework tensorflow do not match" ![image](https://user-images.githubusercontent.com/45504456/269616744-1471385e-33a4-4a18-9c3e-146acd4d1921.png)
> > 
> > 
> > @RummanAli Your implementation for each backend should give the same outputs with little `unnoticeable` differences so if that error appeared to you, you should check your backend implementations.
> 
> Yea I kind of resolved it but currently anew error has propped up: ![image](https://user-images.githubusercontent.com/45504456/271769861-457c6d38-da2b-4655-b35e-0d9b9ae5b131.png) do you know what could be the issue here?
could you show me a pic of the whole error msg cuz I can't see anything from the above pic 😆

2023-09-30 11:32 UTC, RummanAli commented
> Hi @RummanAli everything seems ok but I have some requests if you could fulfill them I will merge your PR I know it's too much but bear with me 😄.
> 
>     * [ ]  you should add the weight argument to **binary_cross_entropy**  function to fulfill the superset behavior like in [here](https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html)
> 
>     * [ ]  you should use **_apply_loss_reduction** in your backend functions to avoid code repetitions.
> 
>     * [ ]  you should solve your code lint errors

Okkk sure, thanks for reviewing. Let me fix and add the thing you mentioned 🖖

2023-09-30 11:34 UTC, RummanAli commented
![image](https://github.com/unifyai/ivy/assets/45504456/4570ac0d-6568-421b-a880-f2f1efd31e80)
![image](https://github.com/unifyai/ivy/assets/45504456/1e453269-41bd-47cb-8cdb-5f1797403fb4)
![image](https://github.com/unifyai/ivy/assets/45504456/6e2d7350-535f-42eb-89c7-6d89ef6b0255)
@mohame54 this is the whole traceback

2023-09-30 14:12 UTC, mohame54 commented
Hmm, It seems that the error is not related to your code could you try to run another existing test in test_losses file to check if this problem appears only to you or it's more general.

2023-09-30 17:35 UTC, RummanAli commented
yea the same error appears with kl_div, but this error vanishes as soon as I revert back to previous commit.

2023-09-30 18:29 UTC, RummanAli commented
@mohame54  I have made the changes as you requested and about _apply_loss_reduction that is from the upstream branch as well which I had to merge to resolve conflicts.

2023-09-30 18:29 UTC, RummanAli commented
Happy to change anything else if required!

2023-10-01 10:53 UTC, mohame54 commented
Hi @RummanAli, I see you added weight argument but I have some questions suppose we have the probabilities shape of
 (N, L, C) and the target should be also of the same shape (N, L, C) and you have a weight of shape (N,) wouldn't it cause mismatching errors

2023-10-01 10:56 UTC, mohame54 commented
also you should solve your lint errors 
![image](https://github.com/unifyai/ivy/assets/97109954/f0f6cf41-2872-4b70-a478-0b9770893b56)
here as you can see some doc string lines should be shortened

2023-10-01 10:57 UTC, mohame54 commented on ivy/functional/backends/numpy/experimental/losses.py
> +    if reduction == "mean":
You should use _apply_loss_reduction function instead of handling it yourself

2023-10-01 10:57 UTC, mohame54 commented on ivy/functional/backends/tensorflow/experimental/losses.py
> +    if reduction == "mean":
also in here

2023-10-01 10:59 UTC, mohame54 requested changes

2023-10-01 10:59 UTC, mohame54 commented on ivy/functional/backends/tensorflow/experimental/losses.py
> +    out: Optional[tf.Tensor] = None,
you should move the out argument from your function arguments

2023-10-01 11:07 UTC, mohame54 commented
you should also solve your test error I think there is something wrong related to the decorators you are using @RummanAli

2023-10-01 11:25 UTC, RummanAli commented
> Hi @RummanAli, I see you added weight argument but I have some questions suppose we have the probabilities shape of (N, L, C) and the target should be also of the same shape (N, L, C) and you have a weight of shape (N,) wouldn't it cause mismatching errors

I just checked the implementation on colab and it works well. So basicall the weights, input and target are multiplied element-wise:
![image](https://github.com/unifyai/ivy/assets/45504456/1ac745d5-def8-4e87-b6b0-f99d91bf3e21)

2023-10-01 12:50 UTC, mohame54 commented
> > Hi @RummanAli, I see you added weight argument but I have some questions suppose we have the probabilities shape of (N, L, C) and the target should be also of the same shape (N, L, C) and you have a weight of shape (N,) wouldn't it cause mismatching errors
> 
> I just checked the implementation on colab and it works well. So basicall the weights, input and target are multiplied element-wise: ![image](https://user-images.githubusercontent.com/45504456/271825029-1ac745d5-def8-4e87-b6b0-f99d91bf3e21.png)

Did you check for every backend like tensorflow or jax ?

2023-10-01 13:03 UTC, mohame54 commented
that's weird but Okay.

2023-10-01 13:04 UTC, mohame54 commented
still remains to check why there are errors in your tests and the modification of reduction part in numpy, tensorflow, jax backends and some lint errors

2023-10-01 13:07 UTC, RummanAli commented
> still remains to check why there are errors in your tests and the modification of reduction part in numpy, tensorflow, jax backends and some lint errors

I just pushed the changes for lint code errors and loss reduction is being used now. I am just unable to figure out why the tests are not running. The tests are not running for any of the loss function in the file but they run as soon as I revert back to previous commit: but that code has conflicts with main branch.

2023-10-01 13:28 UTC, mohame54 commented
> > still remains to check why there are errors in your tests and the modification of reduction part in numpy, tensorflow, jax backends and some lint errors
> 
> I just pushed the changes for lint code errors and loss reduction is being used now. I am just unable to figure out why the tests are not running. The tests are not running for any of the loss function in the file but they run as soon as I revert back .to previous commit: but that code has conflicts with main branch.

that's weird 😕

2023-10-01 19:58 UTC, RummanAli commented
> > > still remains to check why there are errors in your tests and the modification of reduction part in numpy, tensorflow, jax backends and some lint errors
> > 
> > 
> > I just pushed the changes for lint code errors and loss reduction is being used now. I am just unable to figure out why the tests are not running. The tests are not running for any of the loss function in the file but they run as soon as I revert back .to previous commit: but that code has conflicts with main branch.
> 
> that's weird 😕

I fixed this error, there was an conflict of distribution due to numpy as it seems. But I am getting this error now:
![image](https://github.com/unifyai/ivy/assets/45504456/ec3f6118-ee8e-44ba-9e28-3c1fe590f002)
This is shrinker file.

2023-10-01 19:59 UTC, RummanAli commented
![image](https://github.com/unifyai/ivy/assets/45504456/b74888f7-cd21-4c25-b547-26551097935d)

2023-10-01 20:02 UTC, RummanAli commented
While all the tests are passing for poisson_nll_loss: Which signifies there is something wrong with my code 🤔

2023-10-01 23:46 UTC, RummanAli commented
fixed that currently getting this error:
![image](https://github.com/unifyai/ivy/assets/45504456/8262bd09-3080-41a7-bbdb-03400d394e3f)

2023-10-02 12:57 UTC, mohame54 commented
you should check them.

2023-10-04 00:24 UTC, RummanAli commented
> you should check them.

![image](https://github.com/unifyai/ivy/assets/45504456/8b67f92e-2e7f-4024-8576-bd92a65702f5)
finally all tests cases are passing.

2023-10-04 10:27 UTC, mohame54 commented
Hi @RummanAli thanks for your PR it looks good to me.

2023-10-04 10:28 UTC, merged