Reformating lars_update #2334
unifyai/ivy pull request #2539
Opened 2022-08-01 15:15 UTC by vandit98

2022-08-02 08:53 UTC, jkeane508 commented
Hi @vandit98 can you let me know which issue you are creating this PR for?

2022-08-02 13:13 UTC, vandit98 commented
i have created this for lars_update #2334 in gradient.py for array function reformatting.
[](https://github.com/unifyai/ivy/issues/2334)

2022-08-02 14:31 UTC, jkeane508 commented
Hi @vandit98,

You are missing docstring examples for the functional and container implementations of this function. You can refer to the documentation [here](https://lets-unify.ai/ivy/deep_dive/13_docstring_examples.html) on how to complete this task.

Thanks,
James

2022-08-03 09:03 UTC, jkeane508 requested changes
As mentioned above

2022-08-03 10:37 UTC, vandit98 commented
thanks for mentioning i will update it.

2022-08-07 11:01 UTC, vandit98 commented
i have updated as per requirement.

2022-08-07 13:00 UTC, vandit98 commented
requesting for re-review.

2022-08-08 08:46 UTC, jkeane508 requested changes
Hi, 

You still need to add examples to the implementation in the functional module [here](https://github.com/unifyai/ivy/blob/9088011295737beacc7ed2d64929ec7ccd1428dc/ivy/functional/ivy/gradients.py#L778)

Thanks!

2022-08-08 16:38 UTC, vandit98 commented
hi
i have added the example in the functional module as well.

2022-08-09 07:44 UTC, jkeane508 commented
@vandit98 There seems to be some conflicts with the gradients file, if you could resolve to allow tests to run. If the docstring tests are passing and there are no lint errors this is good to merge!

2022-08-09 08:51 UTC, jkeane508 requested changes
I had another look through this and noticed some errors with the implementations. You can refer to docs [here](https://lets-unify.ai/ivy/deep_dive/13_docstring_examples.html#docstring-examples) on what requirements need to be met to complete this task :)

2022-08-09 08:51 UTC, jkeane508 commented on ivy/array/gradients.py
> +        w
As this is an instance method this should be self

2022-08-09 08:51 UTC, jkeane508 commented on ivy/container/gradients.py
> +        ivy.Container instance method variant of ivy.lars_update.
This is incorrect as this is the static implementation of this function

2022-08-09 08:51 UTC, jkeane508 commented on ivy/container/gradients.py
> +        self
As this is a static method it does not accept self as an argument

2022-08-09 08:51 UTC, jkeane508 commented on ivy/container/gradients.py
> +        >>> NewWeights = w.lars_update(dcdw, lr, inplace=False)
This example should use static_lars_update() not the instance method below

2022-08-09 08:51 UTC, jkeane508 commented on ivy/functional/ivy/gradients.py
> +        >>> ws_new = w.lars_update(dcdw, lr, inplace=False)
This is using the array instance method here we should use the functional implementation as outline above

2022-08-10 14:40 UTC, closed without merging