Fixed: floormod to support 'bfloat16'
unifyai/ivy pull request #25878
Opened 2023-09-21 20:36 UTC by omsai11

# PR Description
I added one function which do following things:
It calculates the floor of x using ivy.floor(x).
It calculates the floor of the result of x / y using ivy.floor(x / y).
It subtracts the second floor result from the first floor result and multiplies it by y to compute the modulus.

## Related Issue

Close #23905

feat: allow provided function for 'bfloat16'
BREAKING CHANGE: 'bfloat16' remainder will be provided by floormod

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-21 20:45 UTC, omsai11 commented
I tried my best kindly tell me why code is getting wrong i think other issues are occuring

2023-09-21 20:58 UTC, omsai11 commented
@ivy-leaves 
please let me know the result

2023-09-21 21:13 UTC, omsai11 commented
@hirwa-nshuti sir am i going well

2023-09-21 21:15 UTC, omsai11 commented
@hirwa-nshuti sir how to know which test case is used to test particular my issue

2023-09-22 09:10 UTC, omsai11 commented
Issue us resolved for #https://github.com/unifyai/ivy/issues/23905
@hirwa-nshuti @ivy-leaves kindly check the solution

2023-09-29 11:12 UTC, hirwa-nshuti requested changes
Hey @omsai11 
As I said in this [comment](https://github.com/unifyai/ivy/issues/23905#issuecomment-1740720370) we need to expand the support for such dtype as they're supposed to be supported refering to tf docs: https://www.tensorflow.org/api_docs/python/tf/math/floormod

2024-02-07 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-26 05:53 UTC, closed without merging

2024-02-26 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.