Added  approx_max_k function to math.py with test function is also added
unifyai/ivy pull request #25895
Opened 2023-09-22 06:14 UTC by Shubham7-1

# PR Description
Created `approx_max_k` function to math.py with test function is also added

## Related Issue
https://github.com/unifyai/ivy/issues/25774 

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-22 06:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-22 14:22 UTC, Shubham7-1 commented
@umairjavaid  Could you please Review My PR

2023-09-24 01:47 UTC, umairjavaid requested changes
Hi @Shubham7-1, The tests are failing. You have to make sure all the tests pass

2023-09-24 01:47 UTC, umairjavaid commented
Hi @Shubham7-1, The tests are failing. You have to make sure all the tests pass

```
    | Traceback (most recent call last):
    |   File "/ivy/ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py", line 3256, in test_tensorflow_approx_max_k
    |     helpers.test_frontend_function(
    |   File "/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 981, in test_frontend_function
    |     value_test(
    |   File "/ivy/ivy_tests/test_ivy/helpers/assertions.py", line 135, in value_test
    |     assert_same_type_and_shape([ret_np_flat, ret_np_from_gt_flat])
    |   File "/ivy/ivy_tests/test_ivy/helpers/assertions.py", line 74, in assert_same_type_and_shape
    |     assert (
    | AssertionError: returned dtype = int64, ground-truth returned dtype = int32
    | Falsifying example: test_tensorflow_approx_max_k(
    |     frontend='tensorflow',
    |     backend_fw='numpy',
    |     on_device='cpu',
    |     dtype_and_x=(['float32'],
    |      [array([-4.2813177e+00,  1.5000000e+00,  9.9998999e-01,  1.5000000e+00,
    |              -1.3524009e-02, -3.7381943e+01, -5.0000000e-01], dtype=float32)]),
    |     fn_tree='ivy.functional.frontends.tensorflow.math.approx_max_k',
    |     test_flags=FrontendFunctionTestFlags(
    |         num_positional_args=2,
    |         with_out=False,
    |         inplace=False,
    |         as_variable=[False],
    |         native_arrays=[False],
    |         test_compile=False,
    |         generate_frontend_arrays=True,
    |         transpile=False,
    |         precision_mode=False,
    |     ),
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.86.2', b'AXic42Zk4+VhYwACRobe3vMll+MEGRsUi+pP8ikIMTIyMTI0MIABIyMbMyPDAe6+p3q89f9RZBh4mBgZD2QAmZZP7jKwMjBGVoet2dtyoIexIag/bu+Ox20MrCxAFQxQwATUAgBy1xiD') as a decorator on your test case
    
```

2023-09-24 05:38 UTC, Shubham7-1 commented
Hii @umairjavaid  I had Done changes to test function Could you please Review it

2023-09-24 16:58 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +    k = 5
Why have you hard coded the value of `k` in the test function?

2023-09-24 16:59 UTC, umairjavaid requested changes

2023-09-24 16:59 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +    k = 5
You need to define an `int` strategy for 'k'

2023-09-25 15:11 UTC, Shubham7-1 commented
Hii @umairjavaid I had make changes according to feedback
Is it now good fit ?

2023-10-09 06:18 UTC, umairjavaid requested changes

2023-10-09 06:18 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +        large_abs_safety_factor=24,
Why have you hard coded `large_abs_safety_factor`

2023-10-09 06:18 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +        small_abs_safety_factor=24,
Why have you hard coded `small_abs_safety_factor`

2023-10-09 06:18 UTC, umairjavaid commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +        min_num_dims=1,
Why have you hard coded `min_num_dims`

2023-12-27 11:09 UTC, closed without merging