added docstrings examples for general:unstack
unifyai/ivy pull request #2594
Opened 2022-08-03 11:41 UTC by kunwarsaaim

Resolves #2530

2022-08-08 12:59 UTC, kunwarsaaim commented
@JLU-Neal Hi, can you have a look at my PR.

2022-08-15 20:00 UTC, JLU-Neal commented on ivy/array/general.py
> +        [ivy.array([1, 3]), ivy.array([2, 4])]
I think the correct output here should be:
`
[ivy.array([1,2]),ivy.array([3,4])]
`

2022-08-15 20:01 UTC, JLU-Neal commented on ivy/array/general.py
> +                    [4]])]
I think the correct output here should be:
`
[ivy.array([[1],[3]]),ivy.array([[2],[4]])]
`

2022-08-15 20:11 UTC, JLU-Neal commented on ivy/container/general.py
> +        >>> >>> y = ivy.Container.static_unstack(x, axis=0)
redundant ">>>"

2022-08-15 20:12 UTC, JLU-Neal commented on ivy/container/general.py
> +        >>> print(y)
check the test docstring check, some errors are raised

2022-08-15 20:13 UTC, JLU-Neal commented on ivy/container/general.py
> +        >>> print(y)
make sure the output value is correct

2022-08-15 20:13 UTC, JLU-Neal commented on ivy/container/general.py
> +        >>> print(y)
make sure the output value is correct

2022-08-15 20:14 UTC, JLU-Neal commented on ivy/functional/ivy/general.py
> +    >>> print(y)
Similarly, please make sure all the output values are correct.

2022-08-15 20:16 UTC, JLU-Neal requested changes
The test-docstrings test is not passed, please check the details and make sure all the output values are correct.

2022-08-17 13:46 UTC, JLU-Neal approved these changes
lgtm!

2022-08-17 13:47 UTC, merged