Added divide function to arithmetic_operations
unifyai/ivy pull request #2597
Opened 2022-08-03 12:44 UTC by Ajisco

2022-08-03 14:15 UTC, juliagsy requested changes
Hey! Great work there! There are a few things to amend before it is good to go! Please request my review when you're done, thanks for contributing!

2022-08-03 14:15 UTC, juliagsy commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +	if dtype:
over-indented

2022-08-03 14:15 UTC, juliagsy commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +    div = ivy.divide(x1, x2, out=out)
`ret` instead of `div` as you're using the `ret` variable in the `ivy.where` argument

2022-08-03 14:15 UTC, juliagsy commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +        div = ivy.where(where, ret, ivy.default(out, ivy.zeros_like(ret)), out=out)
`ret` instead of `div` as you're using the `ret` variable in the `ivy.where` argument

2022-08-03 14:15 UTC, juliagsy commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +    return div
`ret` instead of `div` as you're using the `ret` variable in the `ivy.where` argument

2022-08-03 14:15 UTC, juliagsy commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
>  add.unsupported_dtypes = {"torch": ("float16",)}
please move this above so that it is below the `add` function

2022-08-03 14:59 UTC, Ajisco commented
Hello thanks for the feedback. I made the corrections. Kindly review.

2022-08-03 15:04 UTC, Ajisco commented
> Hey! Great work there! There are a few things to amend before it is good to go! Please request my review when you're done, thanks for contributing!

Thanks for the feedback.
I already made the corrections.
Kindly review.

2022-08-04 08:05 UTC, juliagsy requested changes
Hello! Looks great so far! Please also create frontend tests for this function in the `ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_arithmetic_operations.py` file, thank you!

2022-08-04 11:22 UTC, Ajisco commented
> Hello! Looks great so far! Please also create frontend tests for this function in the `ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_arithmetic_operations.py` file, thank you!


I already created Front-end test for the function as asked.
Kindly review:

https://github.com/unifyai/ivy/pull/2629

Thanks.

2022-08-04 12:20 UTC, juliagsy commented
oh! I see, thanks for linking the PR! The assignee for your other PR will review as soon as possible! Meanwhile, I'll merge this PR of yours first, thanks for contributing!

2022-08-04 12:22 UTC, merged