feat: Added is_integer for Paddle frontend
unifyai/ivy pull request #26006
Opened 2023-09-24 15:56 UTC by PattarakornPongpukdeeskul

# PR Description

## Related Issue

Resolves #25937

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-29 22:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-10-01 21:40 UTC, MahmoudAshraf97 requested changes

2023-10-01 21:40 UTC, MahmoudAshraf97 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +        available_dtypes=["int16", "int32", "int64", "float32", "float64"],
it should get all the dtypes using `helpers.get_dtypes`

2023-10-01 21:40 UTC, MahmoudAshraf97 commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +            raise TypeError(f"Expected Tensor, but received type of x: {type(self)}")
this is a method defined inside the tensor instance, it's impossible to execute this condition so it should be removed

2023-10-30 10:03 UTC, closed without merging