feat(paddle backend): Manual dtype casting removal paddle --round 3
unifyai/ivy pull request #26042
Opened 2023-09-25 08:35 UTC by Madjid-CH

2023-09-25 09:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-26 05:48 UTC, vedpatwardhan requested changes
Just a minor point, thanks @Madjid-CH 😄

2023-09-26 05:48 UTC, vedpatwardhan commented on ivy/functional/backends/paddle/general.py
> +    {"2.5.1 and below": ("float16", "int16", "int8")}, backend_version
have you tested `bfloat16`?

2023-09-26 08:52 UTC, Madjid-CH commented on ivy/functional/backends/paddle/general.py
> +    {"2.5.1 and below": ("float16", "int16", "int8")}, backend_version
yes:
```python
x = paddle.to_tensor([1, 2, 3], dtype=paddle.bfloat16)
get_item(x, query=0)
Out[7]: 
Tensor(shape=[1], dtype=bfloat16, place=Place(cpu), stop_gradient=True,
       [1.])
```

2023-09-27 13:26 UTC, vedpatwardhan commented on ivy/functional/backends/paddle/general.py
> +    {"2.5.1 and below": ("float16", "int16", "int8")}, backend_version
awesome, thanks!

2023-09-27 13:26 UTC, vedpatwardhan approved these changes
lgtm! Feel free to merge, thanks @Madjid-CH 😄
(Given that the tests aren't running in the CI due to a docker issue, I'd suggest running the tests for these functions locally and ensuring that they're passing before you merge)

2023-09-27 13:38 UTC, Madjid-CH commented
> lgtm! Feel free to merge, thanks @Madjid-CH 😄 (Given that the tests aren't running in the CI due to a docker issue, I'd suggest running the tests for these functions locally and ensuring that they're passing before you merge)

understood

2023-09-27 13:39 UTC, merged