- [ ] #26054
unifyai/ivy pull request #26058
Opened 2023-09-25 12:20 UTC by OkeyAmy

# PR Description

## Related Issue

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials:

2023-09-25 12:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-26 06:04 UTC, OkeyAmy commented
Close #26054

2023-09-27 12:17 UTC, MuhammedAshraf2020 commented
Hello, @OkeyAmy 
I appreciate your contribution. Please inform me when you've completed your work so that I can review it with you.

2023-09-27 19:59 UTC, OkeyAmy commented
Am done.

2023-09-29 18:41 UTC, MuhammedAshraf2020 requested changes

2023-09-29 18:41 UTC, MuhammedAshraf2020 commented on ivy/functional/frontends/jax/numpy/mathematical_functions.py
> +def mean(x1, /):
This frontend function should have the same calling signature as the original function documented [here](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.mean.html)

2023-10-07 17:47 UTC, MuhammedAshraf2020 requested changes

2023-10-07 17:47 UTC, MuhammedAshraf2020 commented on ivy/functional/frontends/jax/numpy/mathematical_functions.py
> +    return ivy.mean(x)
You have added the same call signature, which is great. However, you need to ensure that you handle and match all of these arguments and keywords with the ones in `ivy.mean`. For example, `ivy.mean` has arguments such as `axis`, `keepdims`, and `out`, which also exist in the frontend function. You should leverage these arguments in the ivy API `ivy.mean`.

For more information, you can refer to the frontend documentation here: [ivy Frontend Documentation](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html).

Additionally, here's an example of that function in another framework for reference: [Numpy Example](https://github.com/unifyai/ivy/blob/main/ivy/functional/frontends/numpy/statistics/averages_and_variances.py#L75).

2023-12-24 14:20 UTC, closed without merging