add logical_xor Tensorflow frontend
unifyai/ivy pull request #2607
Opened 2022-08-03 15:41 UTC by ntg2208

2022-08-03 20:01 UTC, ntg2208 commented
PR for #2603

2022-08-05 08:45 UTC, Unevilicorn requested changes
Looks good! Just a small change then you're good to go.

2022-08-05 08:45 UTC, Unevilicorn commented on ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py
> +
There shouldn't be spaces between the comment and the function, same with the other functions in this file

2022-08-08 09:32 UTC, merged

2022-08-08 09:33 UTC, Unevilicorn commented
All merged :+1: