fix(torch backend): reintroduced necessary manual dtype casting.
unifyai/ivy pull request #26112
Opened 2023-09-26 08:07 UTC by Madjid-CH

Revert unnecessary changes https://github.com/unifyai/ivy/pull/23659

2023-09-26 08:09 UTC, Madjid-CH commented
Hey @vedpatwardhan you only need to approve this PR since you already reviewed all the changes [here](https://github.com/unifyai/ivy/pull/24615), in the mean while we see what @MahmoudAshraf97 say about this.
Thanks😄

2023-09-26 08:20 UTC, vedpatwardhan approved these changes
lgtm! Let's see what @MahmoudAshraf97 thinks, thanks @Madjid-CH 😄

2023-09-29 14:53 UTC, MahmoudAshraf97 requested changes
everything else LGTM

2023-09-29 15:23 UTC, MahmoudAshraf97 commented on ivy/functional/backends/torch/experimental/statistical.py
> +        x = x.real
I don't think these are similar situations, the problem here is that you discarded the imaginary part of the array without reason to do so

2023-09-29 15:24 UTC, Madjid-CH commented on ivy/functional/backends/torch/experimental/statistical.py
> +        x = x.real
did it was like that before I change it ?
`x = x.real.to(dtype=torch.float64)`

2023-09-29 15:26 UTC, Madjid-CH commented on ivy/functional/backends/torch/experimental/statistical.py
> +        x = x.real
It was discarding the imaginary part by creating a new array, now it discard it without a new array 😄

2023-09-29 15:52 UTC, MahmoudAshraf97 commented on ivy/functional/backends/torch/experimental/statistical.py
> +        x = x.real
yeah it was wrong from the beginning, we should add proper support or not support at all

2023-09-29 16:33 UTC, Madjid-CH commented on ivy/functional/backends/torch/experimental/statistical.py
> +        x = x.real
understood I'll change that

2023-10-05 15:07 UTC, merged