added multiplication function to frontend numpy
unifyai/ivy pull request #2613
Opened 2022-08-03 18:29 UTC by pushpahasa1

multiply 

- [ ] #2492

2022-08-03 18:32 UTC, pushpahasa1 commented
please let me know if any corrections needed

2022-08-04 09:17 UTC, rush2406 commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +#multiply
can be removed

2022-08-04 09:20 UTC, rush2406 requested changes
Hi @pushpahasa1 
Thank for contributing! Please add the hypothesis generation part as explained in the comment. Also please fix the lint issues

2022-08-04 09:20 UTC, rush2406 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_arithmetic_operations.py
> +#multiply
can you please add the data generation part for hypothesis? you can follow similar to [example](https://github.com/unifyai/ivy/blob/fe1e0d78073ddad93162ece2cee4a8269985e5ca/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_arithmetic_operations.py#L12)

2022-08-06 11:04 UTC, rush2406 requested changes
Hi @pushpahasa1 
Thanks for the changes! Can you please resolve the conflicts and let me know, remaining looks good to me!

2022-08-06 13:15 UTC, pushpahasa1 commented
@rush2406 I have added non conflicting file above under "conflict removed"

2022-08-06 16:02 UTC, rush2406 requested changes
Hi @pushpahasa1 
The conflict still seems to exist, so I can't merge to master. Can you try pasting the master copy of the file and then paste your changes? maybe that can help?

2022-08-06 17:16 UTC, pushpahasa1 commented
@rush2406  please check now.

2022-08-06 17:25 UTC, pushpahasa1 commented
Hi @rush2406 one thing,  I couldn't synchronise my forked repository. If i synchronise it will delete all existing comments made from me. Is it that because I haven't updated my repo the merge conflict is occurring, due to updates happened in other file in ivy repo but not updated in my repo?
If so please let me know I will send a fresh PR in that case

2022-08-07 09:38 UTC, pushpahasa1 commented
Hi @rush2406 Any updates?

2022-08-07 10:12 UTC, pushpahasa1 commented
Hi @rush2406 Due to rapid updates happening in codebase I noticed  there is new conflict happening in test generation part. I updated it. To avoid future merge conflict I request you to merge before any new updates happening on codebase. 
Thank you

2022-08-08 06:30 UTC, merged

2022-08-08 06:30 UTC, rush2406 commented
@pushpahasa1 no worries, I have resolved the new conflicts that have come up and merge the PR, thanks!