arcsin and arccos in #1525 addressed
unifyai/ivy pull request #2614
Opened 2022-08-03 19:15 UTC by aman190202

Mathematical Functions, arcsin and arccos are added.

2022-08-03 20:23 UTC, aman190202 commented
The failed checks are not from my commits but are pre-existing failed checks from other frontends which are outside the scope of my commit.

2022-08-06 01:05 UTC, kimbring2 commented
@aman190202 Hello, It seems like the arcsin and arccos were not tagged correctly in https://github.com/unifyai/ivy/issues/1525.
Can you follow the step of [this video](https://www.youtube.com/watch?v=TFMPihytg9U&t=132s)? It starts at 01:29.

2022-08-06 02:53 UTC, saeedashrraf commented
Hello @aman190202, as @kimbring2 has mentioned,  you should reserve the two functions with each being reserved through a separate issue.

2022-08-06 02:56 UTC, saeedashrraf requested changes

2022-08-06 02:56 UTC, saeedashrraf commented on ivy/functional/frontends/numpy/mathematical_functions/trigonometric_functions.py
> +    ret = ivy.arcsin(x, out=out)
This should be changed to `ivy.asin` instead of `ivy.arcsin` since the function exists under the name `asin` in the ivy namespace.

2022-08-06 02:56 UTC, saeedashrraf commented on ivy/functional/frontends/numpy/mathematical_functions/trigonometric_functions.py
> +    ret = ivy.arccos(x, out=out)
This should be changed to `ivy.acos` instead of `ivy.arccos` since the function exists under the name `acos` in the ivy namespace.

2022-08-06 07:05 UTC, aman190202 commented
> @aman190202 Hello, It seems like the arcsin and arccos were not tagged correctly in #1525.
> Can you follow the step of [this video](https://youtu.be/2aXMMnTO5So?t=86)? It starts at 01:26.

I have changed and now tagged this issue for arcsin. Thank you for the review.

2022-08-07 04:07 UTC, saeedashrraf requested changes
Can you try to address the formatting issues detected by lint [here](https://github.com/unifyai/ivy/runs/7703084201?check_suite_focus=true)? Thanks!

2022-08-07 05:49 UTC, aman190202 commented
> Can you try to address the formatting issues detected by lint [here](https://github.com/unifyai/ivy/runs/7703084201?check_suite_focus=true)? Thanks!

Thanks for the review ; I have now resolved the lint issues

2022-08-10 00:47 UTC, merged