IVY ML Engineer Intern Contribution
unifyai/ivy pull request #26159
Opened 2023-09-26 17:29 UTC by lucrieffel

# PR Description

## Related Issue

Close #

## Checklist

- [ ] Did you add a function? Yes
- [ ] Did you add the tests? Yes
- [ ] Did you run your tests and are your tests passing? Yes
- [ ] Did pre-commit not fail on any check? Yes
- [ ] Did you follow the steps we provided?Yes

### Socials

2023-09-26 18:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-27 10:03 UTC, AnnaTz requested changes

2023-09-27 10:03 UTC, AnnaTz commented on ivy/functional/frontends/paddle/stat.py
Hi @lucrieffel, please follow are PR naming convention described above.

2023-09-27 10:03 UTC, AnnaTz commented on ivy/functional/frontends/paddle/stat.py
> +@with_supported_dtypes({"float32", "float64"})
You will also need to add a test for you function. Please refer to our [frontend testing documentation](https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends_tests.html) about this.

2023-12-04 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-12-24 14:18 UTC, closed without merging