i added function for erf tensorflow frontend and also added test function for it.
unifyai/ivy pull request #26151
Opened 2023-09-26 15:49 UTC by sharjeelnawaz8182

# PR Description

## Related Issue

Close #19786

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-03 06:06 UTC, YushaArif99 commented on .idea/ivy.iml
can you kindly revert these changes 🙂

2023-10-03 06:06 UTC, YushaArif99 commented on .idea/misc.xml
these as well 🙂

2023-10-03 06:07 UTC, YushaArif99 commented on ivy/functional/backends/numpy/elementwise.py
these as well 🙂

2023-10-03 06:07 UTC, YushaArif99 commented on ivy/functional/frontends/mxnet/numpy/mathematical_functions.py
these as well 🙂

2023-10-03 06:07 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_math.py
> +from ivy_tests.test_ivy.test_functional.test_experimental.test_core.test_elementwise import (
this as well 🙂

2023-10-03 06:07 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_math.py
these as well 🙂

2023-10-03 06:08 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> -        y=x[1],
this as well 🙂

2023-10-03 06:12 UTC, YushaArif99 requested changes
Hi @sharjeelnawaz8182 

Apologies for the delay in review. Have been a little swamped with work recently and so havent had the time to review any PRs 😅 

With regards to the PR itself, it seems like you've added quite a lot of unwanted changes. Could you kindly revert these so that the only changes are of the `erf` function? 
Also, could you kindly make sure the `PR compliance checks` are passing for this PR? 

I am unable to view the CI tests at this moment but they should run once the merge conflicts are resolved. Feel free to re-request a review once all relevant tests are passing. Thanks! 🙂

2023-10-07 00:53 UTC, sharjeelnawaz8182 commented
okay

2024-02-29 20:22 UTC, closed without merging