Added expand function to Paddle frontend
unifyai/ivy pull request #26205
Opened 2023-09-27 10:47 UTC by m571adil

# PR Description

Close #26131 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-09-27 10:57 UTC, m571adil commented
I was unable to set up testing. I used conda environment and VS Code. I followed steps to set up testing in VS code but it was giving some error.

2023-10-05 09:05 UTC, m571adil commented
@hmahmood24 Please review this pull request and let me know if it is acceptable or requires any changes. Thank you

2023-10-05 18:45 UTC, hmahmood24 requested changes
Hey @m571adil, thanks for the PR. The tests however are [failing](https://github.com/unifyai/ivy/actions/runs/6393439716/job/17440593344?pr=26205) which you'll need to look into before we can proceed. You can view the logs from the link above. Thanks! :)

2023-10-05 21:23 UTC, m571adil commented
Hey @hmahmood24 I fixed the cause of failure in my test function. But it's still showing error while testing some other functions. Am i supposed to fix those as well?

2023-10-08 02:24 UTC, m571adil commented
@hmahmood24 can you please see if its ok now?

2023-10-09 15:49 UTC, hmahmood24 commented
Hey @m571adil, since the [tests](https://github.com/unifyai/ivy/actions/runs/6453319679/job/17516683758?pr=26205) on this PR are not being picked up by the CI and I'm also having some troubles setting up testing locally because of an issue that came up, can you please attach screenshots of your tests running locally on your machine? If they are passing fine, then we can merge the PR. Otherwise we'll have to wait for the testing issues to be resolved either on the CI or locally to be able to test your changes which might take some time. Thank you for the cooperation!

2023-10-10 06:40 UTC, m571adil commented
Hi @hmahmood24 I am also unable to setup testing on my local machine. Is there a solution or else when will the issue on CI be resolved.

2023-10-11 08:24 UTC, m571adil commented
Hi @hmahmood24 can you rerun tests please. I am also having same problem on my local machine not picking tests

2023-10-11 19:26 UTC, hmahmood24 commented
> Hi @hmahmood24 can you rerun tests please. I am also having same problem on my local machine not picking tests

What issue are you facing when setting up testing locally?

2023-10-11 19:28 UTC, hmahmood24 requested changes
The tests are failing locally. The issue is that you are generating two arrays using the helper function whereas we need to generate 1 array and a compatible shape along with it so that the array can be expanded to it. Just generating 2 arrays won't work. I recommend going through the tests of similar functions in the codebase to get a feel of what the inputs need to be

2023-10-12 06:45 UTC, m571adil commented
> > Hi @hmahmood24 can you rerun tests please. I am also having same problem on my local machine not picking tests
> 
> What issue are you facing when setting up testing locally?

First, I was getting this error
![image](https://github.com/unifyai/ivy/assets/145253791/fd0db045-7cce-44e1-a1ad-5c56496a9dca)

in _array_module I imported different libraries to test each but all of them giving some error. Numpy and JAX had 
 **AttributeError: module 'numpy' has no attribute 'bool'.
E   `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.**
Cause of error seem to be in my environment so I installed latest pytest but still the same.

For others error was 
![image](https://github.com/unifyai/ivy/assets/145253791/86dba529-36b2-457f-b6bf-695c9a7b272e)

2023-10-12 06:47 UTC, m571adil commented
> The tests are failing locally. The issue is that you are generating two arrays using the helper function whereas we need to generate 1 array and a compatible shape along with it so that the array can be expanded to it. Just generating 2 arrays won't work. I recommend going through the tests of similar functions in the codebase to get a feel of what the inputs need to be

Hi @hmahmood24 Thanks for responding. I will implement this and request review.

2023-10-12 06:58 UTC, hmahmood24 commented
> > > Hi @hmahmood24 can you rerun tests please. I am also having same problem on my local machine not picking tests
> > 
> > 
> > What issue are you facing when setting up testing locally?
> 
> First, I was getting this error ![image](https://user-images.githubusercontent.com/145253791/274504139-fd0db045-7cce-44e1-a1ad-5c56496a9dca.png)

@m571adil Please go through [this](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#github-codespaces) guide which highlights how you have to correctly configure the `_array_module.py` file. It's under the GitHub Codespaces > Setting Up Testing > Point 3:

> Configure the _array_module.py file in the array_api_tests to be set to one of the supported frameworks. e.g.

![image](https://github.com/unifyai/ivy/assets/70361308/57f40acf-e00e-4089-9b44-aff4102ec7ee)

2023-10-12 08:31 UTC, m571adil commented
Actually, error is coming even while configuration in step 1 and 2. 

![image](https://github.com/unifyai/ivy/assets/145253791/c1449323-86c3-4f35-aad8-17fffeada81f)

2023-10-12 12:23:59.554 [info] Discover tests for workspace name: ivy - uri: c:\Users\HP VICTUS\Documents\Study\environment\ivy
2023-10-12 12:23:59.555 [info] Running discovery for pytest using the new test adapter.
2023-10-12 12:23:59.565 [info] > "C:\Users\HP VICTUS\miniconda3\Scripts\conda.exe" run -n ivy_dev --no-capture-output python "c:\Users\HP VICTUS\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\get_output_via_markers.py" -m pytest -p vscode_pytest --collect-only ivy_tests
2023-10-12 12:23:59.565 [info] cwd: c:\Users\HP VICTUS\Documents\Study\environment\ivy
2023-10-12 12:24:05.398 [info] > "C:\Users\HP VICTUS\miniconda3\Scripts\conda.exe" run -n ivy_dev --no-capture-output python "c:\Users\HP VICTUS\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\get_output_via_markers.py" "c:/Users/HP VICTUS/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/printEnvVariables.py"
2023-10-12 12:24:05.398 [info] shell: commandPrompt
2023-10-12 12:24:06.390 [info] > "C:\Users\HP VICTUS\miniconda3\Scripts\conda.exe" run -n ivy_dev --no-capture-output python "c:\Users\HP VICTUS\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\get_output_via_markers.py" -c "import pytest"
2023-10-12 12:24:08.646 [info] Test server connected to a client.
2023-10-12 12:24:08.650 [error] pytest test discovery error 
 _pytest.config.ConftestImportFailure: AssertionError: C:\Users\HP VICTUS\miniconda3\envs\ivy_dev\lib\distutils\core.py (from c:\Users\HP VICTUS\Documents\Study\environment\ivy\ivy_tests\array_api_testing\test_array_api\conftest.py)
 Check Python Test Logs for more details.

Interrupted: 1 error during collection
 Check Python Test Logs for more details.
2023-10-12 12:24:08.650 [error] pytest test discovery error 
 _pytest.config.ConftestImportFailure: AssertionError: C:\Users\HP VICTUS\miniconda3\envs\ivy_dev\lib\distutils\core.py (from c:\Users\HP VICTUS\Documents\Study\environment\ivy\ivy_tests\array_api_testing\test_array_api\conftest.py)
 Check Python Test Logs for more details.

Interrupted: 1 error during collection
 Check Python Test Logs for more details.
2023-10-12 12:24:08.650 [info] ResultResolver EOT received for discovery.
2023-10-12 12:24:09.151 [error] Subprocess exited unsuccessfully with exit code 2 and signal null.
2023-10-12 12:24:09.151 [error] Subprocess exited unsuccessfully with exit code 2 and signal null. Creating and sending error discovery payload
2023-10-12 12:24:09.151 [error] pytest test discovery error 
  
 The python test process was terminated before it could exit on its own, the process errored with: Code: 2, Signal: null
2023-10-12 12:24:09.151 [info] ResultResolver EOT received for discovery.
2023-10-12 12:24:09.151 [info] Disposing data receiver for c:\Users\HP VICTUS\Documents\Study\environment\ivy and deleting UUID; pytest discovery.

2023-10-12 08:54 UTC, hmahmood24 commented
> Actually, error is coming even while configuration in step 1 and 2.
> 
> ![image](https://user-images.githubusercontent.com/145253791/274534778-c1449323-86c3-4f35-aad8-17fffeada81f.png)
> 
> 2023-10-12 12:23:59.554 [info] Discover tests for workspace name: ivy - uri: c:\Users\HP VICTUS\Documents\Study\environment\ivy 2023-10-12 12:23:59.555 [info] Running discovery for pytest using the new test adapter. 2023-10-12 12:23:59.565 [info] > "C:\Users\HP VICTUS\miniconda3\Scripts\conda.exe" run -n ivy_dev --no-capture-output python "c:\Users\HP VICTUS.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\get_output_via_markers.py" -m pytest -p vscode_pytest --collect-only ivy_tests 2023-10-12 12:23:59.565 [info] cwd: c:\Users\HP VICTUS\Documents\Study\environment\ivy 2023-10-12 12:24:05.398 [info] > "C:\Users\HP VICTUS\miniconda3\Scripts\conda.exe" run -n ivy_dev --no-capture-output python "c:\Users\HP VICTUS.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\get_output_via_markers.py" "c:/Users/HP VICTUS/.vscode/extensions/ms-python.python-2023.18.0/pythonFiles/printEnvVariables.py" 2023-10-12 12:24:05.398 [info] shell: commandPrompt 2023-10-12 12:24:06.390 [info] > "C:\Users\HP VICTUS\miniconda3\Scripts\conda.exe" run -n ivy_dev --no-capture-output python "c:\Users\HP VICTUS.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\get_output_via_markers.py" -c "import pytest" 2023-10-12 12:24:08.646 [info] Test server connected to a client. 2023-10-12 12:24:08.650 [error] pytest test discovery error _pytest.config.ConftestImportFailure: AssertionError: C:\Users\HP VICTUS\miniconda3\envs\ivy_dev\lib\distutils\core.py (from c:\Users\HP VICTUS\Documents\Study\environment\ivy\ivy_tests\array_api_testing\test_array_api\conftest.py) Check Python Test Logs for more details.
> 
> Interrupted: 1 error during collection Check Python Test Logs for more details. 2023-10-12 12:24:08.650 [error] pytest test discovery error _pytest.config.ConftestImportFailure: AssertionError: C:\Users\HP VICTUS\miniconda3\envs\ivy_dev\lib\distutils\core.py (from c:\Users\HP VICTUS\Documents\Study\environment\ivy\ivy_tests\array_api_testing\test_array_api\conftest.py) Check Python Test Logs for more details.
> 
> Interrupted: 1 error during collection Check Python Test Logs for more details. 2023-10-12 12:24:08.650 [info] ResultResolver EOT received for discovery. 2023-10-12 12:24:09.151 [error] Subprocess exited unsuccessfully with exit code 2 and signal null. 2023-10-12 12:24:09.151 [error] Subprocess exited unsuccessfully with exit code 2 and signal null. Creating and sending error discovery payload 2023-10-12 12:24:09.151 [error] pytest test discovery error
> 
> The python test process was terminated before it could exit on its own, the process errored with: Code: 2, Signal: null 2023-10-12 12:24:09.151 [info] ResultResolver EOT received for discovery. 2023-10-12 12:24:09.151 [info] Disposing data receiver for c:\Users\HP VICTUS\Documents\Study\environment\ivy and deleting UUID; pytest discovery.

No need to follow the first two steps. Those are for setting up `pytest` in VS Code. You can simply use the `pytest` CLI. The 3rd point is the important one that I tagged you with

2023-10-14 13:06 UTC, m571adil commented
Hi @hmahmood24 please review now. Tests were passing from my end
![image](https://github.com/unifyai/ivy/assets/145253791/7a335465-601a-4b1b-8f97-23036fc98c8b)

2023-10-15 15:29 UTC, hmahmood24 requested changes
Hey @m571adil, left a few comments for you to work on. I think you need to use the `st.shared` strategy to generate a shape that is consistent across two input generation strategies i.e. `helpers.dtypes_and_values` and `helpers.get_shape`. For example you can simply do something like this:
```python
# expand helper function
@st.composite
def dtypes_x_shape(draw):
    dtypes, x = draw(
        helpers.dtype_and_values(
            dtype=["float32"],
            shape=st.shared(
                helpers.get_shape(
                    min_num_dims=1,
                    max_num_dims=5,
                ),
                key="shape",
            ),
        )
    )
    shape = draw(
        st.shared(
            helpers.get_shape(
                min_num_dims=1,
                max_num_dims=5,
            ),
            key="shape",
        )
    )

    shape = list(shape)
    return dtypes, x, shape
```
and remove the `assume` statement from the body of `test_paddle_tensor_expand` and that should pass all the tests nonetheless. Let me know if this makes sense. Thanks

2023-10-15 15:29 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +    shape[-len(np.array(x).shape) :] = np.array(x).shape
Not sure why this was needed here?

2023-10-15 15:29 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +    assume(len(np.array(x).shape) < len(shape))
Again, it is not a good practice to use `assume` inside the body of the test function since we already control the input generation process.

2023-10-16 08:26 UTC, m571adil commented
Hi @hmahmood24  I made the changes but its still showing 1 failure as follows

FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_expand[cpu-numpy-False-False] - hypothesis.errors.InvalidArgument: Cannot sample from a length-zero sequence.

The input constraints should make sure the input is not empty. Not sure why it is showing this. Can you help?

2023-10-16 10:31 UTC, hmahmood24 commented
> Hi @hmahmood24 I made the changes but its still showing 1 failure as follows
> 
> FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_expand[cpu-numpy-False-False] - hypothesis.errors.InvalidArgument: Cannot sample from a length-zero sequence.
> 
> The input constraints should make sure the input is not empty. Not sure why it is showing this. Can you help?

@m571adil Try adding constraints on `min_num_dims` or `min_dim_size` in the `helpers.dtype_and_values` function just like you have for the `helpers.get_shape` function

2023-10-16 10:53 UTC, m571adil commented
> Hi @hmahmood24 I made the changes but its still showing 1 failure as follows
> 
> FAILED ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_tensor_expand[cpu-numpy-False-False] - hypothesis.errors.InvalidArgument: Cannot sample from a length-zero sequence.
> 
> The input constraints should make sure the input is not empty. Not sure why it is showing this. Can you help?

@hmahmood24 Actually I already tried that but didn't work. Anyway, I will commit that as well. First time when I ran it on Saturday it passed all tests. It was only yesterday that it started giving this failure. I did not even make any changes.

2023-10-25 15:29 UTC, hmahmood24 approved these changes
The changes look good to me. The tests all pass now. Thanks so much! @m571adil 🚀

2023-10-25 15:33 UTC, merged