Adding Tensor Exponential method
unifyai/ivy pull request #26236
Opened 2023-09-27 22:14 UTC by Viiktree

# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials
https://www.linkedin.com/in/okeavictory/

2023-09-27 22:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-28 07:53 UTC, lucasalavapena requested changes
Thanks for your contribution :smile: .

Could you please edit your initial comment with the issue you are closing ("Close #{ISSUE_NUMBER}") and make sure you are passing all your tests (the tests you introduced are failing)! I would recommend running the tests locally or on codespace and running pytest only for the specific test `test_paddle_tensor_exponential_`. Feel free to ping me when you have fixed all your tests!

2023-10-02 08:38 UTC, lucasalavapena reviewed
Could you please put the Issue for Close #numbers not this PR!

2023-10-02 08:38 UTC, lucasalavapena commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +    method_name="exp_",
Are you sure you are testing the right function?

2023-12-27 13:04 UTC, closed without merging