feat(Paddle frontend API): added t tensor method and test
unifyai/ivy pull request #26276
Opened 2023-09-28 16:19 UTC by Kartik0605

# PR Description
This PR will add t paddle frontend API method and its respective test.

## Related Issue

Close #26056 

## Checklist

- [X] Did you add a function?
- [X] Did you add the tests?
- [X] Did you run your tests and are your tests passing?
- [X] Did pre-commit not fail on any check?
- [X] Did you follow the steps we provided?

### Socials

2023-10-01 16:04 UTC, hello-fri-end requested changes
Hey @Kartik0605 , thanks for creating this PR - it's already in very good shape. Just left a few minor comments, let's resolve those after which this is good to merge:)

2023-10-01 16:04 UTC, hello-fri-end commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        axes = list(range(len(self._ivy_array.shape)))[::-1]
```suggestion
        axes = list(range(len(self.ivy_array.shape)))[::-1]
```
We shouldn't access a private attribute :)

2023-10-01 16:04 UTC, hello-fri-end commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        return ivy.permute_dims(self._ivy_array, axes=axes)
```suggestion
        return ivy.permute_dims(self.ivy_array, axes=axes)
```

2023-10-01 16:04 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +        available_dtypes=helpers.get_dtypes("float"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```
This should always be set to `valid` - if the function only supports floating-point data, then that's what valid will return :)

2023-10-03 17:50 UTC, Kartik0605 commented
@hello-fri-end i have updated the changes that u requested, please take a look again.

2023-10-04 05:01 UTC, hello-fri-end approved these changes
Looks like there are no failures on the CI. Merging this now, thanks for the contribution @Kartik0605

2023-10-04 05:01 UTC, merged