Lgamma paddle
unifyai/ivy pull request #26376
Opened 2023-09-30 21:16 UTC by lukaM19

# PR Description

## Related Issue

Close # 26351

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-09-30 22:08 UTC, lukaM19 commented
I don't think my PR introduces any new errors, let me know if anything else needs to be changed !

2023-10-01 14:51 UTC, lukaM19 commented
I added the function to the tensor class, I still think no new failed tests are introduced by my code, let me know if I should edit something

2023-10-03 06:24 UTC, YushaArif99 commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        return ivy.lgamma(self)
this should call `paddle_frontend.lgamma`

2023-10-03 06:25 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_manipulation.py
no need to add a separate test for `paddle.lgamma`. So you can remove these changes 🙂

2023-10-03 06:29 UTC, YushaArif99 requested changes
Hi @lukaM19. The changes look good to me at a first glance. There are a few small changes I have requested above. 
I am also noticing the CI tests for `test_paddle_tensor_lgamma` failing [here](https://github.com/unifyai/ivy/actions/runs/6370450261/job/17291572370?pr=26376#step:3:198) with the following error: 

```python
ret = torch.as_tensor(obj, dtype=dtype, device=device)
E   TypeError: object of type 'Tensor' has no len()
```

Could you kindly look into this and ensure the relevant CI tests are all passing? Feel free to request a review once this is done. Thanks! 🙂

2023-10-05 10:07 UTC, lukaM19 commented
@YushaArif99  I made some changes and none of the tests associated with my changes and lgamma seem to fail, I would love to know if you think I should change something else

2023-10-18 13:19 UTC, lukaM19 commented
@YushaArif99 just wondering if you could take another look at the PR

2023-12-25 11:40 UTC, closed without merging