Where #2634
unifyai/ivy pull request #2638
Opened 2022-08-04 16:02 UTC by Amri-Tarik

issue : #2634
Implementing numpy's "where" function (indexing_routines) in ivy's frontend.
any criticisms or tips are welcome.

2022-08-04 18:06 UTC, Amri-Tarik commented
@juliagsy can you please check what's wrong with the GitHub actions tests ? they seem to be failing in functions unrelated to what i have edited (like add or substract).
`test_numpy_where()` seems to be working fine locally for me when using Pycharm remote interpreter with docker on latest image (downloaded today).

2022-08-05 08:13 UTC, juliagsy commented
Hello! No worries on that! Some functions are failing on master so it might be unrelated to your changes. Also, I'll review as soon as possible! Thanks for contributing!

2022-08-05 08:52 UTC, juliagsy requested changes
Hello there! Great work so far! Please rename the files/imports so that they match conventions from NumPy - https://numpy.org/doc/stable/reference/routines.sort.html

Main files: indexing_routines >> sorting_searching_counting
subfiles: indexing_routines.py >> searching.py
(for tests, please update to the same names but with `test_` as prefix of every files)

Once you're done, please request my review again, thank you!

2022-08-06 03:50 UTC, juliagsy requested changes
Hey! Looks good so far! Only some issues related to lint fixes and unused imports, please request my review when you're done and thanks for contributing!

2022-08-06 03:50 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py
> +from datetime import timedelta
unused import

2022-08-06 03:50 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py
> +from hypothesis import given, strategies as st, settings
`settings` is unused import

2022-08-06 03:50 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py
> +import numpy as np
unused import

2022-08-06 03:50 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_sorting_searching_counting/test_searching.py
> +
for lint fix, remove a blank line (keep 2 blank lines only)

2022-08-06 03:50 UTC, juliagsy commented on ivy/functional/frontends/numpy/sorting_searching_counting/searching.py
> +        raise TypeError(f'where takes either 1 or 3 arguments')
lint fix - I think you can directly use double quoting as string placeholder or formatting isn't required

2022-08-06 11:33 UTC, Amri-Tarik commented
sorry for giving you some extra work, I was too focused trying to pass the tests I forgot to clean the code.
this should hopefully be the last one, thanks for the review and the tips.

2022-08-07 07:41 UTC, juliagsy commented
No worries! Thanks for all the changes, will merge in soon!

2022-08-07 07:42 UTC, juliagsy approved these changes
Thanks for contributing! I'll merge the PR soon!

2022-08-07 07:42 UTC, merged