feat: Add Digamma Function and tests to Jax Frontend
unifyai/ivy pull request #26390
Opened 2023-10-01 02:56 UTC by SalmaEl-gohary

## Related Issue

Close #26379

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-06 00:33 UTC, SalmaEl-gohary commented
Hi @AlexandraPosta, Thanks for the feedback. Yes, I have run the tests locally and I will attach them here. 
As I understood from the Deep Dive, The functions in the frontends are supposed to call the API from Ivy and that's what I applied with the addition of the invalid values. Plz correct me if my understanding is wrong.

2023-10-16 07:49 UTC, hmahmood24 requested changes
Hey @SalmaEl-gohary, just request some small changes on the PR. Thanks :)

2023-10-16 07:49 UTC, hmahmood24 commented on ivy/functional/frontends/jax/lax/operators.py
> +    return ivy.array(digamma_fun(x), dtype=x.dtype)
We can simply do `return ivy.astype(ivy.digamma(x), x.dtype)` here

2023-10-16 07:49 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_operators.py
> +    dtype_and_x=helpers.dtype_and_values(available_dtypes=helpers.get_dtypes("float")),
We prever using `"valid"` rather than `"float"` here

2023-10-16 10:59 UTC, SalmaEl-gohary commented
I have made the required changes. Are there any other changes?

2023-10-16 11:24 UTC, hmahmood24 requested changes
Hey @SalmaEl-gohary, did you run your tests locally using `pytest`? The tests are failing when tested locally. We'll need to fix the tests before we can merge the PR. Thanks :)
![image](https://github.com/unifyai/ivy/assets/70361308/cf78b55e-4fe9-4283-8b07-e4eb61999fe9)

2023-10-16 11:24 UTC, hmahmood24 commented on ivy/functional/frontends/jax/lax/operators.py
> +    ivy.digamma
I think you forgot to remove this line

2023-10-26 20:16 UTC, hmahmood24 requested changes
Hey @SalmaEl-gohary, as I mentioned above, you'll have to look into fixing the tests from your PR first before we can merge the PR. 
![image](https://github.com/unifyai/ivy/assets/70361308/4e0cbf80-caf8-4f4b-90b0-4e7b25793c3a)

2023-11-08 09:46 UTC, hmahmood24 commented
Closing the PR since it has been stale for more than 2 weeks.

2023-11-08 09:46 UTC, closed without merging