feat: added diagonal frontend
unifyai/ivy pull request #26407
Opened 2023-10-01 14:57 UTC by lukaM19

# PR Description
feat: added diagonal frontend

## Related Issue

Close #26377

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-10-01 16:55 UTC, lukaM19 commented
Doesn't seem to cause any new test failures ! Let me know if I can edit something!

2023-10-01 19:54 UTC, lukaM19 commented
@KareemMAX , Hi! I just marked my PR ready for review as it doesn't seem to introduce any new failures, if you think I should change something please lmk and I'll get it fixed asap.

2023-10-02 12:23 UTC, KareemMAX requested changes
Thank you so much @lukaM19,
LGTM as for now, I've just a small change. Once done we can run the tests

2023-10-02 12:23 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py
> +        available_dtypes=helpers.get_dtypes("float"),
I guess this should be changed to `valid`, you may do the necessary changes as well

2023-10-03 09:51 UTC, lukaM19 commented
I did the fix you suggested but it introduces a lot of errors with data types, could you suggest a fix

2023-10-04 08:43 UTC, KareemMAX commented
> I did the fix you suggested but it introduces a lot of errors with data types, could you suggest a fix, @KareemMAX

You may use `@with_supported_dtypes` as shown [here](https://github.com/unifyai/ivy/pull/26407/files#diff-19d3f3922bf2d8d7df9a9bdd6331822707caeb37e062644d129e8d95454801baR53)

2023-10-04 08:59 UTC, lukaM19 commented
> > I did the fix you suggested but it introduces a lot of errors with data types, could you suggest a fix, @KareemMAX
> 
> @lukaM19 You may use `@with_supported_dtypes` as shown [here](https://github.com/unifyai/ivy/pull/26407/files#diff-19d3f3922bf2d8d7df9a9bdd6331822707caeb37e062644d129e8d95454801baR53)

@KareemMAX   I tried using that in the last commit but now even more tests fail, to be honest that confused me a little. If you have any ideas as to why I would appreciate any tips!

2023-10-04 09:02 UTC, KareemMAX commented
> @KareemMAX I tried using that in the last commit but now even more tests fail, to be honest that confused me a little. If you have any ideas as to why I would appreciate any tips!

@lukaM19, that shouldn't happen. Have you tried running the tests locally?

2023-10-05 16:47 UTC, lukaM19 commented
@KareemMAX Hi, I tried to fix it and it doesn't seem to fail any tests, let me know if you think I should change something else as well. Best , Luka

2023-10-06 10:44 UTC, KareemMAX requested changes
Hey @lukaM19,
Sadly when I run this test `ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_linalg_diagonal` it fails sadly. Can you fix that?

You can run it locally by using this command:
```bash
pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_linalg_diagonal
```

2023-10-08 12:03 UTC, lukaM19 commented
@KareemMAX  Hi, I removed a redundant test since I realized the same function was being tested twice in test_tensor and test_linalg, still the tests here don't show any errors. I am having trouble running the tests locally even in a docker container, is it possible for you to check again? if you are getting an error what kind of an error is it?

2023-10-09 08:06 UTC, KareemMAX commented
> @KareemMAX Hi, I removed a redundant test since I realized the same function was being tested twice in test_tensor and test_linalg, still the tests here don't show any errors.

Actually that test you removed wasn't redundant, and it failing is considered a bug and a blocker to merge the PR. Can you please add it back and fix it?



> I am having trouble running the tests locally even in a docker container, is it possible for you to check again? if you are getting an error what kind of an error is it?

The docker image suppose to work without any additional configuration, can you post the error message you see? And are you sure you are using `unifyai/ivy` image from docker hub?

I can suggest you somethings to do to make sure you are working with the right environment. You can either:
1. Use codespaces, you have free number of hours every month.
2. Use vscode dev containers. It should give you an identical environment to code spaces locally through docker.

Those are the methods I use personally, of course if you are using PyCharm it should work fine when you use `unifyai/ivy` image from docker hub. Here are the instructions for all of the methods for [setting up your environment](https://unify.ai/docs/ivy/overview/contributing/setting_up.html).

2023-10-09 18:52 UTC, lukaM19 commented
> Hey @lukaM19, Sadly when I run this test `ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_linalg_diagonal` it fails sadly. Can you fix that?
> 
> You can run it locally by using this command:
> 
> ```shell
> pytest ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_linalg_diagonal
> ```

What error message are you getting? I tried running it on codespace and I get the following error messages ` ERROR: not found: /workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_diagonal
(no name '/workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_diagonal' in any of [<Module test_linalg.py>]) ` , in fact I tried running the command for other tests like `test_paddle_matmul` in codespaces and I got the same type of error for all the functions in the file, so I think it might be an issue with the file in general.

But when I test the test_tensor.py test, it fails 3/5 tests with the following error message:`  
  def _get_fn_dtypes(framework: str, kind="valid", mixed_fn_dtypes="compositional"):
        all_devices_dtypes = test_globals.CURRENT_RUNNING_TEST.supported_device_dtypes[
            framework
        ]
        if mixed_fn_dtypes in all_devices_dtypes:
            all_devices_dtypes = all_devices_dtypes[mixed_fn_dtypes]
>       return all_devices_dtypes[test_globals.CURRENT_DEVICE_STRIPPED][kind]
E       KeyError: 'cpu'`
I don't understand what could cause this do you have a suggestion on what to look for?

I only removed the `redundant` test because both tests test the same exact function, there is no difference in calling them so I thought it would be redundant to test the same function, is that wrong?

2023-10-16 15:17 UTC, KareemMAX commented
> I only removed the `redundant` test because both tests test the same exact function, there is no difference in calling them so I thought it would be redundant to test the same function, is that wrong?

Sadly they do in fact test different function signatures, this would be important for us later on to find bugs if we changed a specific method for any reason.



> What error message are you getting? I tried running it on codespace and I get the following error messages `ERROR: not found: /workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_diagonal (no name '/workspaces/ivy/ivy_tests/test_ivy/test_frontends/test_paddle/test_linalg.py::test_paddle_diagonal' in any of [<Module test_linalg.py>])` , in fact I tried running the command for other tests like `test_paddle_matmul` in codespaces and I got the same type of error for all the functions in the file, so I think it might be an issue with the file in general.

This seems to be an issue in your setup (most likely). I'll run the tests and provide you with the results, but you can consult `#ivy-tests` at anytime

2023-10-16 15:38 UTC, lukaM19 commented
How could I edit my setup if I'm running the tests on browser in codespaces?

2023-10-16 17:15 UTC, KareemMAX approved these changes
I looked into the issue and seems like you referenced the wrong function in your test, along with other issues with supported dtypes. I fixed those

2023-10-16 17:28 UTC, merged