instance_norm
unifyai/ivy pull request #26410
Opened 2023-10-01 15:50 UTC by shehroz65

# PR Description

## Related Issue

Close #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

Close #26408

2023-10-04 17:35 UTC, Sam-Armstrong requested changes
Hi @shehroz65, I've left a couple of comments. I suggest we just stick to implementing batch_norm here - you can remove the instance_norm function and test here and create a new PR for it if you'd like.

2023-10-04 17:35 UTC, Sam-Armstrong commented on ivy/functional/frontends/paddle/nn/functional/norm.py
> +    name=None,
```suggestion
    x,
    running_mean,
    running_var,
    weight,
    bias,
    training=False,
    momentum=0.9,
    epsilon=1e-05,
    data_format="NCHW",
    use_global_stats=None,
    name=None,
```
This should be the function signature, following the paddle docs here https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/batch_norm_en.html#batch-norm

2023-10-04 17:35 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_norm.py
> +)
Please can you complete this test so it passes?

2024-03-28 11:21 UTC, Ishticode commented
Thank you verymuch for the PR. closing this due to lack of activity with changes requested remaining unresolved. Please feel free to reopen if you would like to continue working on this.  :)

2024-03-28 11:21 UTC, closed without merging