feat: Added floordiv method in tensorflow frontend and unit test for it.
unifyai/ivy pull request #26474
Opened 2023-10-02 16:09 UTC by Dheeraj-Bal

# PR Description

 Added floordiv method in TensorFlow frontend in tensor.py file and unit test for it.

## Related Issue

Close #26463

## Checklist

- [ ] Added a function

2023-10-02 17:22 UTC, Dheeraj-Bal commented
Hi @hello-fri-end , Can you please guide me on how to pass all the checks and what am I doing wrong with my changes? It would be really helpful.

2023-10-04 05:12 UTC, hello-fri-end requested changes
Hey @Dheeraj-Bal , thanks for working on this issue. Just left some minor comments, happy to review once again after you're done making the changes. Happy coding :)

2023-10-04 05:12 UTC, hello-fri-end commented on ivy/functional/frontends/tensorflow/tensor.py
> +
Why are we using the `raw_ops` `FloorDiv` function here and not the frontend `tf.floordiv` which is defined here (https://github.com/unifyai/ivy/blob/0f33aebcbcd443174f27bb8b43f322853e4078a3/ivy/functional/frontends/tensorflow/math.py#L277)

2023-10-04 05:12 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tensor.py
> +        backend_to_test=backend_fw,
Why are we adding two test functions here? Looks like the only difference in these is that in (1) you're calling `helpers.get_dtypes("numeric")` while in the second you're calling `helpers.get_dtypes("float")`. You should actually use `helpers.get_dtypes("valid") and write only one test.

2023-10-13 13:31 UTC, closed without merging