feat: Add tensor scatter and add function
unifyai/ivy pull request #26479
Opened 2023-10-02 16:46 UTC by ayobamiakomolafe

# Adds sparse updates to an existing tensor according to indices

##26264

Close #26264

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-04 14:36 UTC, ayobamiakomolafe commented
Would appreciate if someone can let me know what to do to fix this Failed tests.

2023-10-04 20:54 UTC, zhumakhan requested changes

2023-10-04 20:54 UTC, zhumakhan commented on ivy/functional/frontends/tensorflow/general_functions.py
> +    return ivy.tensor_scatter_nd_add(tensor, indices, updates)
It seems ivy functional does not have `tensor_scatter_nd_add` implemented. You can add it or even better if you just use existing functions like `ivy.scatter_nd` and `ivy.add` to implement this

2023-10-04 20:54 UTC, zhumakhan commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py
> +        dtype=helpers.get_dtypes("integer"), shape=(8,), min_value=2, max_value=49
Please check for all numeric types: `dtype=helpers.get_dtypes("numeric")`

2023-10-04 20:54 UTC, zhumakhan commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_general_functions.py
> +        input_dtypes=["int32"],
please also generate dtype like in `test_tensorflow_tile` for example.

2024-02-29 20:06 UTC, Ishticode commented
closing this as it is a duplicate of https://github.com/unifyai/ivy/pull/26361

2024-02-29 20:06 UTC, closed without merging