26296: putmask
unifyai/ivy pull request #26514
Opened 2023-10-03 12:51 UTC by achak98

# PR Description

This implements the putmask function of numpy in indexing_like_operations.py in ivy's numpy frontend.

## Related Issue

Close #26296

## Checklist

- [✅] Did you add a function?
- [✅] Did you add the tests?
- [❌] Did you run your tests and are your tests passing?
- [✅] Did pre-commit not fail on any check?
- [✅] Did you follow the steps we provided?

### Socials

2023-10-16 17:48 UTC, KareemMAX requested changes
Hi @achak98,
I've pointed out some few comments with your PR. Can you address them please?

2023-10-16 17:48 UTC, KareemMAX commented on ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py
> +@with_supported_dtypes(
Are you sure this decorator should reference `paddle`?

2023-10-16 17:48 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +    mask = helpers.np.random.choice([True, False], size=a.shape)
I think this is better put in the decorator. You may use  `dtype_and_values` for that with dtype=`bool`

2023-10-16 17:48 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +    mask = mask.astype(ip_dtype)
Is this necessary?

2023-10-16 17:48 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +    values = helpers.np.random.randint(-100, 100, size=values_size)
Those might be better put in the decorator

2023-10-16 17:48 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +    print()
This should be removed
```suggestion
```

2023-10-16 17:48 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_indexing_like_operations.py
> +    values = values.astype(ip_dtype)
This is against convention, you might find another way to achieve the same behavior (maybe shared dtypes)

2024-03-28 11:44 UTC, Ishticode commented
Thank you very much for the PR. Closing this due to lack of activity in 6 months with changes requested remaining unresolved. Please feel free to reopen if you would like to continue working on this.  :)

2024-03-28 11:44 UTC, closed without merging