Sanjay
unifyai/ivy pull request #26558
Opened 2023-10-04 05:40 UTC by Sanjay8602

# PR Description

## Related Issue

Close #

## Checklist

- [ ] Did you add a function? : yes I added the task for 
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-10-04 06:00 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-10-04 06:17 UTC, Sanjay8602 commented
sir what I need to do changes as it is my first contribution on ivy

2023-10-09 03:46 UTC, hello-fri-end requested changes
Hey @Sanjay8602, thanks for creating this PR. For starters, could you please link the issue you're trying to fix in this PR and also update the tittle to match the name of the function you're implementing. Also, please undo unrelated changes from all the files. Thanks :)

2023-10-09 17:45 UTC, Sanjay8602 reviewed
I have made changes such as by mistake I added some so  have deleted all those files

2023-10-09 18:16 UTC, Sanjay8602 reviewed
feat:  added the tensor operations for slicing, mutations, joinings.

2023-10-13 08:35 UTC, Sanjay8602 commented
> Hey @Sanjay8602, thanks for creating this PR. For starters, could you please link the issue you're trying to fix in this PR and also update the tittle to match the name of the function you're implementing. Also, please undo unrelated changes from all the files. Thanks :)

Sir I have made some changes please have a look again please

2023-10-16 05:48 UTC, hello-fri-end reviewed
Hey @Sanjay8602, could you please link the issue that this PR is attempting to fix?

2023-10-16 06:40 UTC, Sanjay0806 commented
> Hey @Sanjay8602, could you please link the issue that this PR is attempting to fix?
Feat: Add Indexing, Slicing, Joining, Mutating Ops to PyTorch Frontend #9
Subtask: scatter #26245 
select_scatter #26519

2023-10-16 09:51 UTC, Sanjay8602 commented
> Hey @Sanjay8602, could you please link the issue that this PR is attempting to fix?



> Hey @Sanjay8602, could you please link the issue that this PR is attempting to fix?

https://github.com/unifyai/ivy/issues/26245

2023-10-16 10:01 UTC, Sanjay8602 reviewed
deleted files which I dont want in this PR

2023-10-16 10:20 UTC, closed without merging