added sklearn precision score metric and the test for it
unifyai/ivy pull request #26578
Opened 2023-10-04 11:15 UTC by EngineerLambda

# PR Description
I added a metric to the sklearn frontend.
Under the classification metrics, I added precision score

## Related Issue
No related issue, I just checked through the frontend codes and found that it was missing that

## Checklist

- [ ] Did you add a function? Yes
- [ ] Did you add the tests? Yes
- [ ] Did you run your tests and are your tests passing? Some passed
- [X ] Did pre-commit not fail on any check? No
- [ ] Did you follow the steps we provided? Yes

### Socials

twitter.com/abdulsomad_me

2023-10-17 18:34 UTC, Sam-Armstrong requested changes
@EngineerLambda Looks good, just left a few comments. Also the test seems to be failing, please could you look into this? Thanks!

2023-10-17 18:39 UTC, EngineerLambda commented on ivy/functional/frontends/sklearn/metrics/_classification.py
> +import numpy as np  # To handle the nans
Old habits, I actual made the pull request as it was required for an internship role at ivy that's already closed now. Had to do this in a short time, as I was dealing with school stuffs, personal projects and new learnings.

2023-10-17 18:40 UTC, EngineerLambda commented on ivy/functional/frontends/sklearn/metrics/_classification.py
> +    """
Thanks, Lol

2024-01-26 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-24 05:53 UTC, closed without merging

2024-02-24 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.