fix bug  #23044
unifyai/ivy pull request #26624
Opened 2023-10-05 05:58 UTC by Aryan8912

# PR Description

## Related Issue

Close #23044 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2024-01-18 16:30 UTC, Sarvesh-Kesharwani commented
Hi @Aryan8912,
would you mind resolving the merge conflicts please.

2024-02-20 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-02-27 11:36 UTC, Sarvesh-Kesharwani requested changes

2024-02-27 11:36 UTC, Sarvesh-Kesharwani commented on ivy/functional/backends/jax/general.py
> +    axis = get_positive_axis_for_gather(axis, params.ndim)
Hi @Aryan8912,
can you please describe what defect does this fix?

2024-03-05 05:53 UTC, closed without merging

2024-03-05 05:53 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.