Clip vector norm reformatting
unifyai/ivy pull request #26657
Opened 2023-10-05 15:02 UTC by monsterdevgit

# PR Description

feat: Add new example in clip_vector_norm docstring

This pull request enhances the `clip_vector_norm` function by including a new example in the function's docstring. The added example conforms with Point 7 of Ivy's Docstring examples. Which states: 

> passes in ivy.Container instances for multiple arguments

## Related Issue

Close #26481

2023-10-07 18:40 UTC, monsterdevgit commented
I have not received a response for this PR.
Am new to open source contributing, so will like some guidance please.

2023-10-09 06:08 UTC, umairjavaid requested changes

2023-10-09 06:08 UTC, umairjavaid commented on ivy/functional/ivy/test.py
Kindly remove this file. This is not needed.

2023-10-09 07:27 UTC, monsterdevgit commented on ivy/functional/ivy/test.py
Done. I don't know how it got uploaded.

2023-10-14 17:50 UTC, aparajith21 commented
Hey, thanks for contributing. LGTM!

2023-10-14 18:43 UTC, merged