Mahamed ducale patch 1
unifyai/ivy pull request #26714
Opened 2023-10-06 17:29 UTC by MahamedDucale

# PR Description

## Related Issue

Close #26701

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-09 03:58 UTC, hello-fri-end requested changes
Hey @MahamedDucale , thanks for creating this PR. Would you please add a test for the `uniform_` function as well. Please make sure all the tests are passing locally. Happy to help out if you run into any issues. Thanks :)

2023-10-09 08:25 UTC, MahamedDucale commented
@hello-fri-end I added the test. However I still have 1 test failing "array-api-intelligent-tests-pr"

2023-10-16 05:52 UTC, hello-fri-end requested changes
Hey @MahamedDucale , thanks for making the changes. Just requested another minor change, happy to review again once you're done with the changes :)

2023-10-16 05:52 UTC, hello-fri-end commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +        available_dtypes=helpers.get_dtypes("float"),
```suggestion
        available_dtypes=helpers.get_dtypes("valid"),
```

This should always be valid- if the function only supports floats, then that's what valid will return.

2023-11-13 04:55 UTC, hello-fri-end requested changes
Hey @MahamedDucale, sorry for the slow response here, I was OOO. Could you please address the comments I have left after which I think this should be good to merge!

2023-11-13 04:55 UTC, hello-fri-end commented on ivy/functional/frontends/paddle/tensor/tensor.py
> -        return paddle_frontend.Tensor(ivy.tile(self._ivy_array, repeats=repeat_times))
Why are we removing this function?

2023-11-13 04:55 UTC, hello-fri-end commented on ivy/functional/frontends/paddle/tensor/tensor.py
> -            }
Why are we removing these?

2023-12-28 09:02 UTC, NiteshK84 commented
Closing the PR for the time being, since there has been no activity for more than 2 weeks.

2023-12-28 09:02 UTC, closed without merging