feat(Jax-frontend): Add histogramdd to JAX Frontend #26584
unifyai/ivy pull request #26725
Opened 2023-10-07 07:23 UTC by ThanhDuonghcmut

# PR Description

## Related Issue #26584

Close #26584

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-10-14 18:43 UTC, aparajith21 commented
Hey, thanks for contributing! Please let me know once you've ticked off the items in the checklist and this is ready for review!

2023-10-15 00:24 UTC, ThanhDuonghcmut commented
![Screenshot_2023-10-15-07-21-27-206_com.github.android-edit.jpg](https://github.com/unifyai/ivy/assets/66547318/97e8ac74-76e1-4bf7-83c7-c87eb2beec1b)
Could you kindly help me to understand what this warning means? Does it affect my code quality?

![Screenshot_2023-10-15-07-21-59-343_com.github.android-edit.jpg](https://github.com/unifyai/ivy/assets/66547318/82cc6987-62ef-4faf-b5c4-63555c515718) 
And also, as my code runs with JAX frontend histogramdd, could I ask why I got this error about numpy_exp2?

I really appreciate your reviews. Please kindly help me clarify them. Thank you very much.

2023-10-16 03:46 UTC, ThanhDuonghcmut commented
I've checked all the ticks on the items. Could you please give me a review for my code?

2023-10-19 02:10 UTC, ThanhDuonghcmut commented
Hi @aparajith21 , could you kindly have a review for my code?

2023-10-24 13:53 UTC, aparajith21 commented
Thanks for contributing! All seems good, test failures seem unrelated to PR, but could you please remove usage of external libraries like `math` and `operator` and substitute their usage with either built in python functions or ivy functions

2023-10-24 13:53 UTC, aparajith21 commented on ivy/functional/frontends/jax/numpy/statistical.py
> +import math
Could the usage of these libraries be replaced with ivy functions please

2023-10-27 03:04 UTC, ThanhDuonghcmut commented
Hi @aparajith21 , I've replaced the external libraries with built-in Python or Ivy functions. However, it produced more failures. Could you kindly have a re-review of what is happening and help me to explain the reason of my failures, as I don't understand what the failures said? 
Thank you very much.

2023-11-08 11:34 UTC, ThanhDuonghcmut commented
Hello @aparajith21 , could you please review my code? I've removed the external libs as you requested

2023-12-29 11:11 UTC, ThanhDuonghcmut commented
Hello @Fayad-Alman, could you please review my code? Thank you very much

2024-03-03 11:57 UTC, Ishticode commented
waiting on fresh ci run

2024-03-25 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-03-30 16:31 UTC, Ishticode requested changes
Hi @ThanhDuonghcmut 
Thanks for the PR.
It seems like there is failure caught by the CI has caught a failure for test_jax_histogramd as you can check here at https://github.com/unifyai/ivy/actions/runs/8129963424/job/22217724147?pr=26725. Please try to fix and request a review when done. Thank you :)

2024-04-09 22:14 UTC, Ishticode commented
Closing this due to inactivity. Please feel free to reopen if you would like to continue working on this. Thanks :)

2024-04-09 22:14 UTC, closed without merging