feat(tensorflow frontend): Added a new inverse window function
unifyai/ivy pull request #26757
Opened 2023-10-07 23:55 UTC by teckno

https://github.com/unifyai/ivy/issues/21889

# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-10 13:13 UTC, hirwa-nshuti requested changes
Hey @teckno 

Check the comments below

2023-10-10 13:13 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
> +    fn_tree="ivy.signal.inverse_stft_window_fn",
This should be the frontend function not `Ivy` one 😅

2023-10-10 13:13 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
> +    def inverse_stft_window_fn(frame_step):
Would you clearly explain the use of this logic 🙄

2023-10-10 13:13 UTC, hirwa-nshuti commented on ivy/functional/frontends/tensorflow/signal.py
> +def inverse_stft_window_fn(frame_step, forward_window_fn=ivy.hann_window, name=None):
`forward_window_fn` should be a frontend version of the mentioned function

2023-12-28 08:27 UTC, Sarvesh-Kesharwani commented
Closing the PR for the time being, since there has been no activity for more than 2 weeks.

2023-12-28 08:27 UTC, closed without merging