feat(torch-frontend): Added cdist
unifyai/ivy pull request #26755
Opened 2023-10-07 22:46 UTC by teckno

# PR Description

## Related Issue

Close https://github.com/unifyai/ivy/issues/21894

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-10 13:06 UTC, hirwa-nshuti requested changes
Hey @teckno 

I ran your tests and I'm getting these failures
Would you look into this and run the tests locaaly to cross verify
![image](https://github.com/unifyai/ivy/assets/67042527/08512374-24ae-4265-b34b-ff9a9ddafddf)

2023-10-16 12:28 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +        available_dtypes=[
why only limit to `float32` and `float64`? I think you should use `avalaible_dtypes=valid` here

2023-10-16 12:28 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_miscellaneous_ops.py
> +        input_dtypes=["float64"],
shouldn't this be `input_dtypes=input_dtypes` ?

2023-12-28 08:19 UTC, Sarvesh-Kesharwani commented
Hi @teckno 
please resolve the merge conflicts.

2024-03-24 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2024-03-28 11:50 UTC, Ishticode commented
Thank you very much for the PR. Closing this due to lack of activity with changes requested remaining unresolved for over 6 months. Please feel free to reopen if you would like to continue working on this.  :)

2024-03-28 11:50 UTC, closed without merging