feat(paddle frontend): Added alpha dropout
unifyai/ivy pull request #26759
Opened 2023-10-08 00:51 UTC by teckno

https://github.com/unifyai/ivy/issues/22124

# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-10 13:26 UTC, hirwa-nshuti requested changes
Hey @teckno 

Check the comments below🤞

2023-10-10 13:26 UTC, hirwa-nshuti commented on ivy/functional/frontends/paddle/nn/functional/common.py
> +        random_values = ivy.random_normal(shape=x.shape, dtype=x.dtype)
With randomization we won't be able to get exact results here you can refer to how other `Selu` activation functions are implemented in frontends.

2023-10-10 13:26 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_common.py
> +        min_num_dims=1,
The function doesn't only work for `1-Dim` Arrays we need to test other dimensions as well

2023-10-10 13:26 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_common.py
> +    mode=st.sampled_from(["upscale_in_train", "downscale_in_infer"]),
This mode wasn't indicated in the docs we need to test function based on Documentation
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/alpha_dropout_en.html#alpha-dropout

2023-12-28 08:19 UTC, Sarvesh-Kesharwani commented
Closing the PR for the time being, since there has been no activity for more than 2 weeks.

2023-12-28 08:20 UTC, closed without merging