Add rfft2 to numpy frontend
unifyai/ivy pull request #26751
Opened 2023-10-07 21:34 UTC by samir-fama

close #26706

2023-10-30 06:32 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py
> +        available_dtypes=helpers.get_dtypes("complex"),
`numpy.rfftn` expects real-value arrays. why are you creating complex arrays as inputs?

2023-10-30 06:47 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py
> +    axes=st.sampled_from([(0, 1), (-1, -2), (1, 0)]),
rather than hard-coding a few `axes` values, it's better to make generate `axes` values using hypothesis strategies.

2023-10-30 06:47 UTC, YushaArif99 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_fft/test_discrete_fourier_transform.py
> +    s=st.tuples(
`s` shouldnt always be a tuple of length 2. Instead it should be either `None`, or a tuple of length of `dim(a)`

2023-10-30 06:52 UTC, YushaArif99 requested changes
Hi @ShreKrente 

The implementation looks good overall. The data generation strategy though seems a little restrictive to me and could potentially be better generalized. For instance, you could generate an n-dim array `a` based on which you could define a new helper which would then correspondingly generate valid values for `s` and `axes`. 
Here is a possible implementation for the helper: 

```python
def generate_s_and_axes(a):
    ndim = a.ndim  

    # Strategy for generating 's'
    s_strategy = st.one_of(
        st.none(),  # 's' can be None
        st.tuples(*(st.integers(min_value=0, max_value=a.shape[i]) for i in range(ndim))) # Each element of 's' is an integer between 0 and the size of the corresponding dimension of 'a'
    )

    # Strategy for generating 'axes'
    axes_strategy = st.one_of(
        st.none(),  # 'axes' can be None
        st.lists(
            st.integers(min_value=0, max_value=ndim-1), 
            min_size=1, max_size=ndim  
        ) #Each element of 'axes' is an integer between 0 and the number of dimensions of 'a' - 1
    )

    return s_strategy, axes_strategy
```

2023-12-28 08:18 UTC, Sarvesh-Kesharwani commented
Closing the PR for the time being, since there has been no activity for more than 2 weeks.

2023-12-28 08:18 UTC, closed without merging