feat(paddle frontend): Added ifft2
unifyai/ivy pull request #26804
Opened 2023-10-09 09:22 UTC by teckno

# PR Description

## Related Issue

Close #

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-10 18:05 UTC, hirwa-nshuti requested changes
Hey @teckno 

Would you check the comments below

2023-10-10 18:05 UTC, hirwa-nshuti commented on ivy/functional/frontends/paddle/fft.py
> +    return ivy.real(fft_result)
The return type should be of `complex` dtypes as specified in the docs

2023-10-16 08:27 UTC, hmahmood24 requested changes
Hey @teckno, can you please also link the issue that you are trying to resolving by commenting `Close #issue_number` ? Thanks!

2023-11-08 09:47 UTC, hmahmood24 commented
Closing this PR since it has been stale for more than 2 weeks now.

2023-11-08 09:47 UTC, closed without merging