Added Function
unifyai/ivy pull request #26845
Opened 2023-10-09 21:55 UTC by RohitSgh

# PR Description

Adding `signbit`  
https://numpy.org/doc/stable/reference/generated/numpy.signbit.html

## Related Issue

Close #23332

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials:

https://x.com/iRohitSgh
https://www.linkedin.com/in/iRohitSgh

2023-10-09 21:56 UTC, RohitSgh commented
add_frontend_checklist

2023-10-10 12:34 UTC, RohitSgh commented
Hi @hello-fri-end. Can you please review the proposed changes? Thanks!

2023-10-16 06:00 UTC, hello-fri-end requested changes
Hey @RohitSgh , thanks for creating this PR. Just left a minor comment, happy to review again once you're done with the changes. :)

2023-10-16 06:21 UTC, RohitSgh commented
Command

```
pytest -v ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_floating_point_routines.py::test_numpy_signbit`
```

After changing to `valid`, on testing locally, it produces following error, @hello-fri-end 

> ![image](https://github.com/unifyai/ivy/assets/81853910/356750d5-7856-4837-9bd9-994e67cafa6d)

It is 
`Cannot cast ufunc 'signbit' input from dtype('int8') to dtype('float16') with casting rule 'no'`

2023-10-16 07:29 UTC, RohitSgh commented
Ready for review, @hello-fri-end

2023-10-18 07:34 UTC, hello-fri-end requested changes
`ivy.logical_or` function does support the out argument, so we can pass it direclty :)

2023-10-18 07:34 UTC, hello-fri-end commented on ivy/functional/frontends/numpy/mathematical_functions/floating_point_routines.py
> +    return ivy.logical_or(ivy.less(x, 0), ivy.atan2(0.0, x) == ivy.pi)
```suggestion
    return ivy.logical_or(ivy.less(x, 0), ivy.atan2(0.0, x) == ivy.pi, out=out)
```

2023-10-25 06:15 UTC, RohitSgh commented
Ay update, @hello-fri-end ?

2023-10-25 06:37 UTC, hello-fri-end approved these changes
LGTM! There are no related failures on the CI, thanks for the awesome contribution and apologies for the delayed response :pray:

2023-10-25 06:38 UTC, merged