Feat/lu reconstruct
unifyai/ivy pull request #26881
Opened 2023-10-10 14:25 UTC by jdboachie

# PR Description

## Related Issue
#26760

Closes #

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-16 09:49 UTC, AnnaTz requested changes

2023-10-16 09:49 UTC, AnnaTz commented on ivy/functional/frontends/tensorflow/linalg.py
> +
Hi @jdboachie, thanks for the PR. You will also need to add a frontend test to be considered for merging.

2023-10-16 09:49 UTC, AnnaTz commented on ivy/functional/frontends/tensorflow/linalg.py
> +    L, U = ivy.array(lower), ivy.array(upper)
Also, please make sure you follow the original function signature as shown [here](https://www.tensorflow.org/api_docs/python/tf/linalg/lu_reconstruct).

2024-03-30 15:50 UTC, Ishticode commented
Closing this due to inactivity after changes were requested. Please feel free to reopen if you would like to continue working on this. Thank you :)

2024-03-30 15:50 UTC, closed without merging