feat: add qdwh() function to jax.lax frontend
unifyai/ivy pull request #26900
Opened 2023-10-11 09:01 UTC by rukiyearican

# PR Description

added qdwh and qdwh test

## Related Issue

Closes #25633

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-10-11 09:41 UTC, rukiyearican commented
hello @RickSanchezStoic 

this is my first pull request, therefore i'm not sure i did all of correctly. i would be very happy if you can comment. i receive some assertion errors in local testing, im still trying to figure it out, that's why im not sure

2023-10-13 11:37 UTC, rukiyearican commented
hello @hmahmood24 

this is my first pull request, therefore i'm not sure i did all of correctly. i would be very happy if you can comment. i receive some assertion errors in local testing, im still trying to figure it out, that's why im not sure

2023-10-16 10:43 UTC, hmahmood24 requested changes
Hey @rukiyearican, thanks for the PR. I left a few comments for you. It would also help to go through our docs on unifyai.com to get a feel of how to write frontend functions and frontend function tests. Thanks!

2023-10-16 10:43 UTC, hmahmood24 commented on ivy/functional/frontends/jax/lax/linalg.py
> +import numpy as np_frontend
We're not supposed to use native packages like `jax`, `numpy`, `torch` etc. in the frontends. Instead, we only implement the frontend functions using either `ivy` functions or functions from the same frontend e.g. `jax` frontend

2023-10-16 10:43 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_lax/test_linalg.py
> +            assert not is_converged
Please look at all the other tests in this file and all the other test files to get a feel of how to write the correct tests. You don't need to add assert statements manually here. Neither do you need to import the `qdwh` function from the jax frontend. The `helpers.test_frontend_function` already handles this internally by checking if the output of the frontend function and the actualy `jax.lax.linalg.qdwh` match or not.

2023-11-08 09:48 UTC, hmahmood24 commented
Closing this PR since it has been stale for more than 2 weeks now.

2023-11-08 09:48 UTC, closed without merging