ivy.index_add
unifyai/ivy pull request #26934
Opened 2023-10-12 05:45 UTC by imsoumya18

# PR Description

## Related Issue

Closes #26801 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials
[Twitter](https://twitter.com/imsoumya184)

2023-10-18 06:03 UTC, imsoumya18 commented
@saeedashrraf please review this PR

2023-11-30 13:57 UTC, imsoumya18 commented
@saeedashrraf can u please review the PR?

2023-12-04 05:22 UTC, imsoumya18 commented on ivy/functional/ivy/experimental/manipulation.py
> +@inputs_to_ivy_arrays
Hi @vedpatwardhan thanks for the review. I have made the changes. Please have a look

2023-12-05 03:55 UTC, vedpatwardhan commented on ivy/functional/ivy/experimental/manipulation.py
> +@inputs_to_ivy_arrays
sounds good, thanks!

2023-12-05 04:03 UTC, vedpatwardhan requested changes
Thanks for making the changes, the tests seem to be failing with [tensorflow](https://github.com/unifyai/ivy/actions/runs/7082403750/job/19273606133?pr=26934#step:4:396) which fails the tests with all backends (because `tensorflow` is the ground truth). I'll also request @NripeshN's review who'd be able to suggest the further steps , thanks @imsoumya18 😄

2023-12-06 04:03 UTC, vedpatwardhan reviewed
Hey @imsoumya18, @NripeshN would be reviewing the PR soon (as he's assigned to the PR). Thanks 😄

2023-12-07 15:49 UTC, imsoumya18 commented
> Hey @imsoumya18, @NripeshN would be reviewing the PR soon (as he's assigned to the PR). Thanks 😄

Yes, please. I have been waiting since October for this PR. If needed we can schedule a meeting. I am really worried about this one. Thank you 😄

2023-12-08 11:04 UTC, vedpatwardhan commented
Hey @imsoumya18, sorry just realized one thing, isn't this function be the same as `ivy.scatter_nd` with `sum` being the `reduction`? Was it present on a ToDo list cuz ideally this function shouldn't have been on a ToDo list. Thanks 😄

2023-12-08 12:43 UTC, imsoumya18 commented
> Hey @imsoumya18, sorry just realized one thing, isn't this function be the same as `ivy.scatter_nd` with `sum` being the `reduction`? Was it present on a ToDo list cuz ideally this function shouldn't have been on a ToDo list. Thanks 😄

Actually I was implementing `index_add` #26394 & `index_add_` #26761 in Paddle frontend as listed as ToDo in #15037

Then, I got [this review](https://github.com/unifyai/ivy/pull/26761#pullrequestreview-1663702572) and I paused the above 2 and this issue is still pending since then. Whereas the actual 2 was completed but not merged until it is being done.

2023-12-11 04:18 UTC, vedpatwardhan commented
> > Hey @imsoumya18, sorry just realized one thing, isn't this function be the same as `ivy.scatter_nd` with `sum` being the `reduction`? Was it present on a ToDo list cuz ideally this function shouldn't have been on a ToDo list. Thanks 😄
> 
> Actually I was implementing `index_add` #26394 & `index_add_` #26761 in Paddle frontend as listed as ToDo in #15037
> 
> Then, I got [this review](https://github.com/unifyai/ivy/pull/26761#pullrequestreview-1663702572) and I paused the above 2 and this issue is still pending since then. Whereas the actual 2 was completed but not merged until it is being done.

Got it, thanks for clarifying! I completely agree with the point @hello-fri-end made, the frontend implementations shouldn't be as long and we should do most of the heavy-lifting in the ivy api itself. However, I suspect using `ivy.scatter_nd` with the `sum` reduction might actually end up making the frontend implementation compact enough without the need of adding a new function to `ivy` itself. Could you please try using `ivy.scatter_nd` in the frontend implementation and see if the tests pass? Thanks @imsoumya18 😄

2024-01-18 13:58 UTC, imsoumya18 commented
NO MORE NEEDED

2024-01-18 13:58 UTC, closed without merging