feat: Add Tfill_diagonal_tensor to Paddle Frontend
unifyai/ivy pull request #27000
Opened 2023-10-13 19:49 UTC by mahmoud99-cell

# PR Description
I tested the method in a separate notebook by creating a custom class with this function only and using a normal tensor object from paddle package, and it worked correctly, of course system testing is the one who will tell if it is integrated correctly. 

Still need to test inplace behavior and update it (use ivy.update_inplace(self, y)). 

I created the tests but failed to run due to windows fatal threading error. Also pre-commit fails when I ran it, followed [the instructions](https://unify.ai/docs/ivy/overview/contributing/setting_up.html#pre-commit).

Command:
`pytest ivy\ivy_tests\test_ivy\test_frontends\test_paddle\test_tensor\test_tensor.py::fill_diagonal_tensor_ --no-header --no-summary --disable-pytest-warnings --backend all --hypothesis-verbosity verbose`

❌ Error  :
  test session starts
collecting ... Windows fatal exception: access violation
Thread 0x00004714 (most recent call first):
  File "D:\Anaconda3\envs\ivy_dev\lib\threading.py", line 324 in wait
  File "D:\Anaconda3\envs\ivy_dev\lib\threading.py", line 600 in wait
  File "D:\Anaconda3\envs\ivy_dev\lib\threading.py", line 1356 in run
  File "D:\Anaconda3\envs\ivy_dev\lib\threading.py", line 1009 in _bootstrap_inner
  File "D:\Anaconda3\envs\ivy_dev\lib\threading.py", line 966 in _bootstrap

## Related Issue

Closes #26892 

## Checklist

- [x] Did you add a function? yes
- [x] Did you add the tests? yes
- [ ] Did you run your tests and are your tests passing? no
- [ ] Did pre-commit not fail on any check? yes, package not running ImportError: DLL load failed while importing _ctypes:
- [ ] Did you follow the steps we provided? yes

### Socials
linkedin: https://www.linkedin.com/in/mahmoud-nabil-9a75b11a5/

2023-10-16 18:10 UTC, KareemMAX requested changes
Hey @mahmoud99-cell,
I've pointed out some comments that I would like you to resolve. Overall, I think you might be over complicating the function a bit as it's extremely hard to understand (therefore maintain). Have you tried using masking instead?

Also there are some irrelevant changes that you have made, please revert them back

2023-10-16 18:10 UTC, KareemMAX commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        self = self.fill_diagonal_tensor_impl(
I'm not really sure if assigning `self` is valid (or a good practice) in python, you are basically assigning memory address by itself.

2023-10-16 18:10 UTC, KareemMAX commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        dim2 %= len(inshape)
Are you sure that is computationally correct? Why don't you use more simpler terms?

2023-10-16 18:10 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +        available_dtypes=helpers.get_dtypes("float"),
Can you use `valid` instead?

2023-10-16 18:10 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
You seem to be missing the other arguments of the function

2023-10-16 18:11 UTC, KareemMAX commented
> I tested the method in a separate notebook by creating a custom class with this function only and using a normal tensor object from paddle package, and it worked correctly, of course system testing is the one who will tell if it is integrated correctly.

Seems like those error are Windows specific, have you tried another system? Maybe docker (as it's the most predictable)

2023-10-17 01:40 UTC, mahmoud99-cell commented
> > I tested the method in a separate notebook by creating a custom class with this function only and using a normal tensor object from paddle package, and it worked correctly, of course system testing is the one who will tell if it is integrated correctly.
> 
> Seems like those error are Windows specific, have you tried another system? Maybe docker (as it's the most predictable)

Can you test the pytest function on your end? Can you send me your discord ID ?

2023-10-17 11:30 UTC, KareemMAX requested changes
<details><summary>Error logs</summary>

```
Use Database in ReadOnly Mode with local caching !
============================= test session starts ==============================
platform linux -- Python 3.10.0, pytest-7.4.2, pluggy-1.3.0 -- /opt/miniconda/envs/multienv/bin/python
cachedir: .pytest_cache
hypothesis profile 'ivy_profile' -> max_examples=25, print_blob=True, deadline=timedelta(milliseconds=500000), suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much, HealthCheck.data_too_large], database=MultiplexedDatabase(DirectoryBasedExampleDatabase('/workspaces/ivy/.hypothesis/examples/'), ReadOnlyDatabase(RedisExampleDatabase(Redis<ConnectionPool<Connection<host=redis-17011.c259.us-central1-2.gce.cloud.redislabs.com,port=17011,db=0>>>, expire_after=datetime.timedelta(days=8))))
metadata: {'Python': '3.10.0', 'Platform': 'Linux-6.2.0-1014-azure-x86_64-with-glibc2.28', 'Packages': {'pytest': '7.4.2', 'pluggy': '1.3.0'}, 'Plugins': {'anyio': '4.0.0', 'hypothesis': '6.87.0', 'metadata': '3.0.0', 'json-report': '1.5.0'}}
backend(s): all
device: cpu
number of Hypothesis examples: 25
rootdir: /workspaces/ivy
plugins: anyio-4.0.0, hypothesis-6.87.0, metadata-3.0.0, json-report-1.5.0
collecting ... collected 5 items

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_fill_diagonal_tensor_[cpu-numpy-False-False] FAILED [ 20%]
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_fill_diagonal_tensor_[cpu-jax-False-False] FAILED [ 40%]
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_fill_diagonal_tensor_[cpu-tensorflow-False-False] FAILED [ 60%]
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_fill_diagonal_tensor_[cpu-torch-False-False] FAILED [ 80%]
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py::test_paddle_fill_diagonal_tensor_[cpu-paddle-False-False] FAILED [100%]

=================================== FAILURES ===================================
___________ test_paddle_fill_diagonal_tensor_[cpu-numpy-False-False] ___________

    @handle_frontend_method(
>       class_tree=CLASS_TREE,
        init_tree="paddle.to_tensor",
        method_name="fill_diagonal_tensor_",
        dtype_and_x=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
            num_arrays=2,
            shared_dtype=True,
        ),
        test_inplace=st.just(True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py:334: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py:355: in test_paddle_fill_diagonal_tensor_
    helpers.test_frontend_method(
ivy_tests/test_ivy/helpers/function_testing.py:2052: in test_frontend_method
    frontend_ret_ins = copy_ins.__getattribute__(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = ivy.frontends.paddle.Tensor(shape=[], dtype=bool, True)
y = ivy.array(False), offset = 0, dim1 = 0, dim2 = 1, name = None

    def fill_diagonal_tensor_(self, y, offset=0, dim1=0, dim2=1, name=None):
>       self._ivy_array = self.fill_diagonal_tensor_impl(
            self, y, offset=offset, dim1=dim1, dim2=dim2, inplace=True
        )
E       AttributeError: 'Tensor' object has no attribute 'fill_diagonal_tensor_impl'. Did you mean: '_fill_diagonal_tensor_impl'?
E       Falsifying example: test_paddle_fill_diagonal_tensor_(
E           frontend='paddle',
E           on_device='cpu',
E           backend_fw='numpy',
E           dtype_and_x=(['bool', 'bool'], [array(True), array(False)]),
E           init_flags=FrontendInitTestFlags(
E               num_positional_args=1,
E               as_variable=[False],
E               native_arrays=[False],
E           ),
E           frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.paddle', framework_init_module='paddle', init_name='to_tensor', method_name='fill_diagonal_tensor_'),
E           method_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E               precision_mode=False,
E               inplace=True,
E               test_trace=False,
E               generate_frontend_arrays=False,
E           ),
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.87.0', b'AAgAAQAAAAAAAAAAAA==') as a decorator on your test case

ivy/functional/frontends/paddle/tensor/tensor.py:928: AttributeError
____________ test_paddle_fill_diagonal_tensor_[cpu-jax-False-False] ____________

    @handle_frontend_method(
>       class_tree=CLASS_TREE,
        init_tree="paddle.to_tensor",
        method_name="fill_diagonal_tensor_",
        dtype_and_x=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
            num_arrays=2,
            shared_dtype=True,
        ),
        test_inplace=st.just(True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py:334: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py:355: in test_paddle_fill_diagonal_tensor_
    helpers.test_frontend_method(
ivy_tests/test_ivy/helpers/function_testing.py:2052: in test_frontend_method
    frontend_ret_ins = copy_ins.__getattribute__(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = ivy.frontends.paddle.Tensor(shape=[], dtype=bool, False)
y = ivy.array(False), offset = 0, dim1 = 0, dim2 = 1, name = None

    def fill_diagonal_tensor_(self, y, offset=0, dim1=0, dim2=1, name=None):
>       self._ivy_array = self.fill_diagonal_tensor_impl(
            self, y, offset=offset, dim1=dim1, dim2=dim2, inplace=True
        )
E       AttributeError: 'Tensor' object has no attribute 'fill_diagonal_tensor_impl'. Did you mean: '_fill_diagonal_tensor_impl'?
E       Falsifying example: test_paddle_fill_diagonal_tensor_(
E           # The test always failed when commented parts were varied together.
E           frontend='paddle',
E           on_device='cpu',
E           backend_fw='jax',
E           dtype_and_x=(['bool', 'bool'],
E            [array(False), array(False)]),  # or any other generated value
E           init_flags=FrontendInitTestFlags(
E               num_positional_args=1,
E               as_variable=[False],
E               native_arrays=[False],
E           ),  # or any other generated value
E           frontend_method_data=FrontendMethodData(ivy_init_module='ivy.functional.frontends.paddle', framework_init_module='paddle', init_name='to_tensor', method_name='fill_diagonal_tensor_'),
E           method_flags=FrontendMethodTestFlags(
E               num_positional_args=0,
E               as_variable=[False],
E               native_arrays=[False],
E               precision_mode=False,
E               inplace=True,
E               test_trace=False,
E               generate_frontend_arrays=False,
E           ),  # or any other generated value
E       )
E       
E       You can reproduce this example by temporarily adding @reproduce_failure('6.87.0', b'AXic42RABgAAjAAK') as a decorator on your test case

ivy/functional/frontends/paddle/tensor/tensor.py:928: AttributeError
________ test_paddle_fill_diagonal_tensor_[cpu-tensorflow-False-False] _________

    @handle_frontend_method(
>       class_tree=CLASS_TREE,
        init_tree="paddle.to_tensor",
        method_name="fill_diagonal_tensor_",
        dtype_and_x=helpers.dtype_and_values(
            available_dtypes=helpers.get_dtypes("valid"),
            num_arrays=2,
            shared_dtype=True,
        ),
        test_inplace=st.just(True),
    )

ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py:334: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ [...]

2023-10-18 11:35 UTC, KareemMAX requested changes

2023-10-18 11:35 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_tensor/test_tensor.py
> +
Those changes are irrelevant

2023-10-18 11:35 UTC, KareemMAX commented on ivy/functional/frontends/paddle/tensor/tensor.py
> +        self._ivy_array = self._fill_diagonal_tensor_impl(
I'm not sure if that still is the right way of implementing the function

2024-03-28 11:56 UTC, Ishticode commented
Thank you very much for the PR. Closing this due to lack of activity with changes requested remaining unresolved for over 6 months. Please feel free to reopen if you would like to continue working on this. :)

2024-03-28 11:56 UTC, closed without merging