corrcoef instance method  for pytorch frontend and test function added
unifyai/ivy pull request #27032
Opened 2023-10-16 07:40 UTC by sharjeelnawaz8182

# PR Description

## Related Issue

Closes #26843

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-10-16 11:32 UTC, hmahmood24 requested changes
Hey @sharjeelnawaz8182, thanks a lot for the PR. However, we need to fix the tests first in order to merge the PR. Please run your tests locally using `pytest` first to see if they're passing or not. I tested them locally and they were failing for me for all the backends. 
![image](https://github.com/unifyai/ivy/assets/70361308/b485a8f2-e93e-40fa-ba17-49b6977a0afb)

2023-10-16 11:45 UTC, sharjeelnawaz8182 commented
when i keep 
init_input_dtypes=input_dtype
it fails .
but when i test with 
init_input_dtypes = ["float"]
it pass for all the tests

2023-10-26 20:59 UTC, hmahmood24 requested changes
Hey @sharjeelnawaz8182, thanks for the PR. Requesting minor changes. Let me know if the tests still fail after this. Also, it would be helpful if you can share the logs of the test failures here so we can take a look at fixing them. Thanks!

2023-10-26 20:59 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +        shared_dtype=True,
We don't need to keep these arguments. You can remove these

2023-10-26 20:59 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +        available_dtypes=helpers.get_dtypes("float"),
We prefer using `"valid"` instead of `"float"` here

2023-10-26 20:59 UTC, hmahmood24 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py
> +        method_input_dtypes=[],
We need to pass `input_dtype` over here as well

2023-11-08 09:49 UTC, closed without merging

2023-11-08 09:49 UTC, hmahmood24 commented
Closing this PR since it has been stale for more than 2 weeks now.