(Draft) feat: select_scatter for torch frontend
unifyai/ivy pull request #27061
Opened 2023-10-17 16:02 UTC by lazyCodes7

# PR Description

## Related Issue

Closes #26519

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2023-10-18 14:28 UTC, lazyCodes7 commented
Hi @kurshakuz , 
I am contributing to this repository for the very first time. If I am missing something that needs to be done please do let me know assuming you are the point of contact for this.

2023-10-31 06:27 UTC, kurshakuz requested changes
Hey! Thank you for your contribution!

Your implementation is currently throwing the following error. Can you please resolve it?

```
ERROR ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py - AttributeError: module 'ivy.functional.backends.numpy' has no attribute 'bool'
```

2024-03-03 11:19 UTC, Ishticode commented
Thank you very much for the PR @lazyCodes7. Sorry for the delays on our end. You are right about the numpy bool issue.
Can you please resolve the conflict (and request a review) so that the ci can be frshly run. Thanks for your patience.

2024-03-28 11:57 UTC, Ishticode commented
Thank you very much for the PR. Closing this due to lack of activity with changes requested remaining unresolved for over 6 months. Please feel free to reopen if you would like to continue working on this. :)

2024-03-28 11:57 UTC, closed without merging