add reshape frontends.torch
unifyai/ivy pull request #2708
Opened 2022-08-07 04:44 UTC by PatternFinder

link to issue: #2636

reason for new PR: cleaned up local branch name formatting

2022-08-08 16:02 UTC, VedPatwardhan requested changes
Hi @PatternFinder, thanks for contributing. There are a few changes to be made to your PR before we get it merged. I have suggested changes near the lines of code concerned. Please feel free to re-request my review once you're done making the changes, we'll look into getting the tests passing after that.
Let me know if you have any questions. Thanks 🙂

2022-08-09 01:54 UTC, PatternFinder commented
> 

@VedPatwardhan got it, did all the things per your instructions. ready for review :)

2022-08-09 09:53 UTC, VedPatwardhan requested changes
Hi @PatternFinder, thanks for making the changes, I have suggested a few more changes and also mentioned the ones from the previous review that weren't made, please make those changes and re-request my review once you're done.
Let me know if you have any questions. Thanks 🙂

2022-08-09 09:53 UTC, VedPatwardhan commented on ivy/functional/frontends/tensorflow/functions.py
> -
Please revert all changes made to this file as this isn't related to the function in this PR.

2022-08-09 09:53 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tf_functions.py
> -        dtype_and_x=helpers.dtype_and_values(
These changes haven't been reverted yet, please revert them.

2022-08-09 09:53 UTC, VedPatwardhan commented on ivy/functional/frontends/torch/indexing_slicing_joining_mutating_ops.py
> +def reshape(input, shape, copy=None):
The `copy` argument isn't accepted by [`torch.reshape`](https://pytorch.org/docs/stable/generated/torch.reshape.html), hence we shouldn't have it here.

2022-08-09 09:53 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py
> +    copy=st.booleans(),
Please remove the usage of the `copy` argument from the `test_torch_reshape` function too.

2022-08-09 09:53 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py
> +    helpers.test_frontend_function(
Please also pass `with_out=False` to the `test_frontend_function` here.

2022-08-10 12:33 UTC, closed without merging

2022-08-10 12:40 UTC, PatternFinder commented
ok so here's what happend :)
1. the tf codes that were not part of my task I originally edited them to attempt to fix all the linting errors
2. but now I'm so far behind upstream so I decided just discard all my changes and remerge with upstream (which closed this PR :(
3. I've edited the reshape function per your instructions and added it back to this branch, and opened another PR for the reshape function at #2853

thanks for your support!