fix(torch-frontend): fix errors in torch.log and torch.erf
unifyai/ivy pull request #27100
Opened 2023-10-23 05:10 UTC by yopknopixx

# PR Description

Fix errors in torch.log and torch.erf with the paddle backend caused by unsupported datatypes

2023-10-26 15:40 UTC, yopknopixx commented
Hey @aparajith21! This is not an open task and is related to the Fixing Priority Functions task.

2023-12-26 03:50 UTC, vedpatwardhan commented
Hey @yopknopixx, feel free to request a review once you're done with the changes, thanks!

2023-12-27 04:59 UTC, vedpatwardhan requested changes

2023-12-27 04:59 UTC, vedpatwardhan commented on ivy/functional/frontends/torch/pointwise_ops.py
> +@with_unsupported_dtypes({"2.5.1 and below": ("bfloat16",)}, "paddle")
Hey @yopknopixx, actually the use of the `with_unsupported_dtypes` decorator in the frontends primarily refers to the datatypes that the function in the actual framework that the frontend belongs to doesn't support. For specifying backend-specific unsupported dtypes, we should update the corresponding decorator in the backend implementation (e.g. the decorator in the `paddle` backend implementation of `ivy.erf`), same applies to `ivy.log`. Thanks 😄

2023-12-27 06:56 UTC, yopknopixx commented
This seems to gave been fixed on `main`. Closing the PR. Thanks for the review @vedpatwardhan! 😊

2023-12-27 06:56 UTC, closed without merging