fix(torch-frontend): fix failing test for torch.min with the numpy backend
unifyai/ivy pull request #27115
Opened 2023-10-25 06:05 UTC by yopknopixx

# PR Description

fix failing test for torch.min with the numpy backend

2023-12-26 03:53 UTC, vedpatwardhan commented
Hey @yopknopixx, feel free to request a review once you're done with the changes, thanks!

2023-12-27 05:00 UTC, vedpatwardhan requested changes

2023-12-27 05:00 UTC, vedpatwardhan commented on ivy/functional/frontends/torch/reduction_ops.py
> +@with_unsupported_dtypes({"1.26.1 and below": ("complex",)}, "numpy")
could you please specify this unsupported dtype in the `numpy` backend implementation of `ivy.mean` as it's a backend-specific unsupported dtype? Thanks @yopknopixx 😄

2023-12-27 07:00 UTC, yopknopixx commented
@vedpatwardhan this has been fixed on `main`. Closing the PR. Thanks!

2023-12-27 07:00 UTC, closed without merging