add swapdims frontends.torch
unifyai/ivy pull request #2711
Opened 2022-08-07 04:55 UTC by PatternFinder

link to issue: #2705

2022-08-07 05:04 UTC, PatternFinder commented
question: since I've only edited the torch test functions, how come others' edits under the tensorflow test functions' lintting error is showing up on this PR? like so,

```
ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tf_functions.py:260:1: W391 blank line at end of file
```

2022-08-08 08:16 UTC, sherry30 commented
Hi,

Those lint errors are on the upstream master branch so they are not caused by your PR, you don't have to worry about those. Your PR will get merged if the lint errors are not caused by your code 😄 
Also just leave a comment if you're done making changes so i know its ready to be reviewed,

Thanks

2022-08-08 13:10 UTC, PatternFinder commented
@sherry30 Hi, I've fixed all the linting on my branch and I'm ready for review. 

for `test-frontend-torch / run-nightly-tests (pull_request)`, I'm seeing:
```
FAILED ivy/ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py::test_torch_swapdims[cpu-ivy.functional.backends.torch-True-False-torch_call-torch]
```
How should I resolve this?

2022-08-10 08:02 UTC, sherry30 requested changes
Hi,

You're not supposed to pass `container_flags` and `instance_method` argument to the `test_frontend_function`

2022-08-10 08:02 UTC, sherry30 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_indexing_slicing_joining_mutating_ops.py
> +        instance_method=instance_method,
remove this

2022-08-10 12:48 UTC, PatternFinder commented
Ok I removed the container_flags and instance_method args.

2022-08-14 02:21 UTC, closed without merging