Priority torch frontend
unifyai/ivy pull request #27411
Opened 2023-11-29 06:17 UTC by Vismay-dev

# Fixed torch.nn.functional.conv_transpose2d priority function.

## Checklist

- [x] Did you add a function?
- [x] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

2023-11-29 15:39 UTC, AnnaTz requested changes
This is great, thanks!
Only some minor updates needed.

2023-11-29 15:39 UTC, AnnaTz commented on ivy/functional/frontends/torch/nn/functional/convolution_functions.py
> +    stride = [stride] * dims if isinstance(stride, int) else stride
The `map` above is doing exactly that. You could just add `dilation` and `stride` there to avoid repetition.

2023-11-29 15:39 UTC, AnnaTz commented on ivy/functional/frontends/torch/nn/functional/convolution_functions.py
> +
Also, could you please remove the dilation and padding limitations of the corresponding tests? 
You would need to remove the condition [here](https://github.com/unifyai/ivy/blob/d3c562dcc91cd839e3e1a05bee0deb2fbda7c02e/ivy_tests/test_ivy/test_frontends/test_torch/test_nn/test_functional/test_convolution_functions.py#L232) and the use of `max_dilation` [here](https://github.com/unifyai/ivy/blob/d3c562dcc91cd839e3e1a05bee0deb2fbda7c02e/ivy_tests/test_ivy/test_frontends/test_torch/test_nn/test_functional/test_convolution_functions.py#L367) and [here](https://github.com/unifyai/ivy/blob/d3c562dcc91cd839e3e1a05bee0deb2fbda7c02e/ivy_tests/test_ivy/test_frontends/test_torch/test_nn/test_functional/test_convolution_functions.py#L447). Hope I'm not forgetting something.

2023-11-30 05:29 UTC, Vismay-dev commented
@AnnaTz I've made the required changes. Torch backend explicit padding wasn't needed for transpose 1d & 3d either, so changes were made there too. Please review and let me know if there are any concerns :)

2023-11-30 10:15 UTC, merged