numpy tanh frontend
unifyai/ivy pull request #2758
Opened 2022-08-08 11:45 UTC by anhdang000

#2756

2022-08-12 03:16 UTC, anhdang000 commented
@Aarsh2001 Hi, can you have a check on my PR?

2022-08-14 09:24 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
> +    as_variable=helpers.array_bools(),
pass num_arrays=1

2022-08-14 09:25 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
> +    native_array=helpers.array_bools(),
pass num_arrays=1

2022-08-14 09:25 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
> +        fn_name="tanh",
use `fn_tree` instead of `fn_name`

2022-08-14 09:26 UTC, Aarsh2001 commented on ivy/functional/frontends/numpy/mathematical_functions/trigonometric_functions.py
> +
add the decorator `@from_zero_dim_arrays_to_float`

2022-08-14 09:27 UTC, Aarsh2001 requested changes
Kindly have the look at the comments above, these are the changes that will be required for the tests to pass for this function, thanks🙂

2022-08-14 14:22 UTC, anhdang000 commented
Please have a look at my recent commits for the requested changes. Thanks 😃

2022-08-14 16:43 UTC, Aarsh2001 commented
Looks good, can you fix the merge conflicts?

2022-08-15 02:25 UTC, anhdang000 commented
I resolved the conflict. Are there still any issues or it's good to go?

2022-08-15 08:19 UTC, Aarsh2001 commented
lgtm!

2022-08-15 08:19 UTC, merged