Acos
unifyai/ivy pull request #2775
Opened 2022-08-08 17:26 UTC by Change-m

Add acos to jax/lax/operators.py #2773

2022-08-09 10:22 UTC, VedPatwardhan requested changes
Hi @Change-m, thanks for contributing. There are a few changes to be made to your PR before we get it merged. I have made suggestions near the lines of code concerned, please make those changes. Also please add the tests for your frontend function referring the [docs](https://lets-unify.ai/ivy/deep_dive/17_ivy_frontends_tests.html). 
Feel free to re-request my review once you're done making the changes. Thanks 🙂

2022-08-10 12:38 UTC, Change-m commented
Hi [VedPatwardhan](https://github.com/VedPatwardhan), I added the acos test and sorry to say but I am not able to find your suggestions. Can you guide me little more?

2022-08-11 15:51 UTC, VedPatwardhan commented
Oh sorry, it seems like the comments didn't get added for some reason, I'll add them right away!

2022-08-11 15:58 UTC, VedPatwardhan requested changes
Hi @Change-m, I have now added the comments. Some of the files seem to have been updated accidentally either while writing the tests or while merging the master branch into your branch. Please revert those changes so that the only files visible under the Files Changed Tab of this PR are the `ivy/functional/frontends/jax/lax/operators.py` and `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py`. Once you're done with it, feel free to re-request my review and we'll look into the results of the tests. And once again, sorry that you couldn't see them in the previous review 🙂

2022-08-11 15:58 UTC, VedPatwardhan commented on ivy/functional/frontends/jax/lax/operators.py
> +acos.ubsupported_dtypes = {"torch": ("float16", "bfloat16")}
Please add a new line here

2022-08-11 15:58 UTC, VedPatwardhan commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> -import ivy
Please revert all changes made to this file as it's not related to the function you're working on

2022-08-11 15:58 UTC, VedPatwardhan commented on ivy/functional/frontends/numpy/mathematical_functions/trigonometric_functions.py
> +def cosh(
Please revert all changes made to this file as it's not related to the function you're working on

2022-08-11 15:58 UTC, VedPatwardhan commented on ivy/functional/ivy/nest.py
> +) -> Union[ivy.Array, ivy.NativeArray, Iterable]:
Please revert all changes made to this file as it's not related to the function you're working on.

2022-08-11 15:58 UTC, VedPatwardhan commented on ivy_tests/test_docstrings.py
> -        "cross_entropy",
Please revert all changes made to this file as it's not related to the function you're working on

2022-08-11 15:58 UTC, VedPatwardhan commented on ivy_tests/test_ivy/helpers.py
> +def docstring_examples_run(
Please revert all changes made to this file as it's not related to the function you're working on

2022-08-12 08:22 UTC, Change-m commented
Hi [VedPatwardhan](https://github.com/VedPatwardhan), I made all the suggested changes. I am requesting for the review.

2022-08-12 12:14 UTC, VedPatwardhan commented
Hi @Change-m, if you take a look at the `Files Changed` tab of your PR, there still seem to be 7 files updated in your PR, please revert the changes to the files not related to your PR so that only the `ivy/functional/frontends/jax/lax/operators.py` and `ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py` files are changed which are the files related to your function. Doing that is necessary as otherwise it could cause failures in other functions. Moreover, I think your branch is 130 commits behind master as well, please pull the changes from master into your branch and resolve the merge conflicts.
Let me know if you have any questions. Thanks 🙂

2022-08-13 08:28 UTC, Change-m commented
Hi [VedPatwardhan](https://github.com/VedPatwardhan), revert all not related changes. I am requesting for the review.

2022-08-13 09:19 UTC, VedPatwardhan requested changes
Hi @Change-m, thanks for making the changes, I have suggested a couple more minor changes, which should get the lint tests and frontend tests passing for your function.
Feel free to re-request my review once you're done with the changes. If the tests pass we can get your PR merged. Thanks 🙂

2022-08-13 09:19 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
> +
There should only be 2 blank lines instead of 3.

2022-08-13 09:19 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
> +        fn_name="lax.acos",
This argument has now been renamed to `fn_tree`, please update it here.

2022-08-13 10:50 UTC, Change-m commented
Hi [VedPatwardhan](https://github.com/VedPatwardhan), I am requesting for the review.

2022-08-14 05:27 UTC, VedPatwardhan approved these changes
lgtm! Thanks for contributing 🙂

2022-08-14 05:27 UTC, merged

2022-08-15 08:33 UTC, Change-m commented
Thank You, [VedPatwardhan](https://github.com/VedPatwardhan)