feat: triplet margin loss added to functional experimental
unifyai/ivy pull request #27804
Opened 2023-12-27 17:40 UTC by BhumikaChauhan07

# PR Description
Changes Made
Added a new function triplet_margin_loss to the ivy library, which computes the triplet margin loss. This loss is commonly used in triplet loss scenarios, such as in siamese networks for learning embeddings.

Purpose
The purpose of this addition is to provide users with a convenient and efficient way to compute triplet margin loss, allowing for better support of applications involving metric learning and similarity-based tasks.

## Related Issue
Closes #27204

## Checklist

- [X] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2024-01-10 12:02 UTC, NiteshK84 commented
Hi @BhumikaChauhan07,
Please resolve the merge conflicts.

2024-01-10 12:38 UTC, BhumikaChauhan07 commented
Hello @NiteshK84, I'm on it. Thanks.

2024-01-10 15:22 UTC, NiteshK84 commented
Hi @BhumikaChauhan07,
you have not implemented the unit test_function
please implement it in this path "/workspaces/ivy/ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py"

2024-01-10 15:50 UTC, BhumikaChauhan07 commented
Ok I'll work upon it.

2024-01-12 16:59 UTC, BhumikaChauhan07 commented
Hi @NiteshK84,
I've implemented the respective test function. Regards.

2024-01-18 16:45 UTC, NiteshK84 requested changes

2024-01-23 07:58 UTC, BhumikaChauhan07 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_losses.py
> +    dtype_and_inputs=_triplet_loss_input(),
Okay , on it.

2024-03-28 12:05 UTC, Ishticode commented
Thank you very much for the PR. Closing this due to lack of activity with changes requested remaining unresolved for over 2 months. Please feel free to reopen if you would like to continue working on this. :)

2024-03-28 12:05 UTC, closed without merging