fix: Fixed torch.Tensor.not_equal for paddle backend
unifyai/ivy pull request #27997
Opened 2024-01-23 04:52 UTC by Sai-Suraj-27

# PR Description
Fixed `torch.Tensor.not_equal` for paddle backend

![image](https://github.com/unifyai/ivy/assets/87087741/72839e3b-67a1-4c8d-94c6-1afc258581a3)

## Related Issue
Closes #27996 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2024-01-23 15:30 UTC, KareemMAX requested changes
Seems like there is a conflict in addition to [failed tests](https://github.com/unifyai/ivy/actions/runs/7621613089/job/20758457814#step:6:12)

2024-01-23 16:09 UTC, MuhammadNizamani commented
@KareemMAX  I have fix this issue for backend paddle if you merge this PR then It will fail again for paddle backend. And my changes also solve this issue so how you are going to proceed?

2024-01-23 16:18 UTC, closed without merging

2024-01-23 16:25 UTC, Sai-Suraj-27 commented
> @KareemMAX I have fix this issue for backend paddle if you merge this PR then It will fail again for paddle backend. And my changes also solve this issue so how you are going to proceed?

Hey, @MuhammadNizamani. Your PR was created 6hrs after I created this PR. Since you commented about it in the discord channel, I guess your was merged quickly.
Since, your PR also addressed the problem my PR was addressing. This PR will be closed 👍🏻.

2024-01-24 06:45 UTC, MuhammadNizamani commented
@Sai-Suraj-27  Sir if my your PR merge before mine I still have to remove your code because your solution was good for fronted but and mine works both fronted and back-end.
I am so sorry you PR did not merge 😔

2024-01-24 06:52 UTC, Sai-Suraj-27 commented
> @Sai-Suraj-27  Sir if my your PR merge before mine I still have to remove your code because your solution was good for fronted but and mine works both fronted and back-end.
> I am so sorry you PR did not merge 😔
> 

Yes, i know. Mine was fixing one of the failing tests, and yours was fixing 2 or 3 more failing tests, including mine. I just normally said that I made it earlier, so that it doesn't look like I replicated your PR.
No issues at all...😄