fix: Fixed `stat.paddle.mean` for all backends
unifyai/ivy pull request #28087
Opened 2024-01-27 15:23 UTC by Sai-Suraj-27

# PR Description
Fixed `stat.paddle.mean` for all backends

![image](https://github.com/unifyai/ivy/assets/87087741/054a5535-c07e-4ae2-9fa1-5876fddf946d)

## Related Issue
Closes #28082
Closes #28083
Closes #28084
Closes #28085
Closes #28086

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2024-01-28 12:09 UTC, Sarvesh-Kesharwani commented
![image](https://github.com/unifyai/ivy/assets/22115102/bf7c26bc-453d-412b-a614-1b7040849c7a)
![Uploading image.png…]()

2024-01-28 13:45 UTC, Sai-Suraj-27 commented
> ![image](https://private-user-images.githubusercontent.com/22115102/300260950-bf7c26bc-453d-412b-a614-1b7040849c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDY3NzIsIm5iZiI6MTcwNjQ0NjQ3MiwicGF0aCI6Ii8yMjExNTEwMi8zMDAyNjA5NTAtYmY3YzI2YmMtNDUzZC00MTJiLWE2MTQtMWI3MDQwODQ5YzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEyNTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NGY1ZGI4ZDczZTFlODg0YzVlOTZmMmEzOGJlMTcxOTVjYWIyNTI0YTQxOGU0ZWU0MjVhZjNlNjUxMWNiMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P2RL0Ym1yWdpTCR76wvkFPYRQQJFDq8rUxlDaf9wkwE) ![image](https://private-user-images.githubusercontent.com/22115102/300260991-c6bed479-0ab7-4749-80a9-4e0d46a3e9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDY3NzIsIm5iZiI6MTcwNjQ0NjQ3MiwicGF0aCI6Ii8yMjExNTEwMi8zMDAyNjA5OTEtYzZiZWQ0NzktMGFiNy00NzQ5LTgwYTktNGUwZDQ2YTNlOWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEyNTQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNjg3ZGYzNDc2YmE3MDM5YzhmNzhiMzNiZGQ4NzhmOGJiMjg3ZGRlMjdkMGY1ZTI3YTUyNjI4NDg3ZTE0MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aijpne1eAOoiT2Syk26mxM5BWrMAz4I7_UFN7_lWbfE) please work on fixing these test failures

Hey, @Sarvesh-Kesharwani thanks for the review. I'm not sure, how many examples you set while testing, I tested with 25, 50, 100 and 150 examples.

![image](https://github.com/unifyai/ivy/assets/87087741/18b5900b-487a-4491-b880-48486baf7852)
All, the backends are passing with 50 examples.

Although when I tested with 100 examples, only `torch` backend is failing and when I tested with 150 examples only `numpy` backend is failing.

![image](https://github.com/unifyai/ivy/assets/87087741/c037b500-9d67-4ef3-a9f2-5b4a8ba4bdfc)

But, it is actually not any problem with code, it's just the accuracy of the result. You can see that the test is failing due to a minute difference of 10^(-3) difference in the outputs from the 2 backends, Due to this small difference some tests are failing when we set the number of examples too high.
 
![image](https://github.com/unifyai/ivy/assets/87087741/11f9c8eb-46b6-425e-8352-0094cf11ea80)

So, I guess we can merge this, no need to change anything. Please let me know your opinion.
Thank you.

2024-01-29 13:15 UTC, KareemMAX requested changes

2024-01-29 14:51 UTC, KareemMAX commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_stat.py
> +    input_dtype, x, axis, dtype3, where = dtype_and_x
Oh, I thought it won't unpack the rest like JS (sorry have been off Python for a while). But why don't we use this?
```suggestion
    input_dtype, x, axis = dtype_and_x[:2]
```
Not sure if I'm slicing correctly though

2024-01-29 14:53 UTC, KareemMAX commented
Also, regarding the current issues with the failing tests. They shouldn't fail even if the code appears right, the precision issue should be handled accordingly @Sai-Suraj-27. And make sure examples cited by @Sarvesh-Kesharwani are passing

2024-01-30 04:42 UTC, Sai-Suraj-27 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_stat.py
> +    input_dtype, x, axis, dtype3, where = dtype_and_x
Done👍🏻

2024-01-30 04:44 UTC, Sai-Suraj-27 commented
> Also, regarding the current issues with the failing tests. They shouldn't fail even if the code appears right, the precision issue should be handled accordingly @Sai-Suraj-27. And make sure examples cited by @Sarvesh-Kesharwani are passing

Hey, @KareemMAX I know precision should be handled but since the test was passing in CI also. I thought it's okay. Actually this is a clear example of this [2nd case](https://unify.ai/docs/ivy/overview/contributing/error_handling.html#error-handling) in the docs.
I have updated the test, and tested it for 150 examples, and it is successfully passing for all the backends.
![image](https://github.com/unifyai/ivy/assets/87087741/0f86dbc6-d8e4-4532-806a-26a2da5b0448)

Thanks @Sarvesh-Kesharwani for spotting this 😄.

2024-01-30 15:13 UTC, KareemMAX approved these changes
LGTM, waiting for @Sarvesh-Kesharwani's approval to merge

2024-01-31 14:40 UTC, Sai-Suraj-27 commented
Hey, @Sarvesh-Kesharwani. Can you please look into the PR once and merge it if you think it's good 😄.
Thank you.

2024-01-31 14:53 UTC, Sarvesh-Kesharwani commented
Okay let me test once, then I'll merge it.

2024-01-31 15:01 UTC, Sarvesh-Kesharwani commented
Hi @Sai-Suraj-27,
LGTM now,
Thanks for the hard work.

2024-01-31 15:01 UTC, merged