add set(difference) function
unifyai/ivy pull request #2818
Opened 2022-08-09 16:02 UTC by Abdulhaffiz-Umar

#1558

2022-08-10 09:17 UTC, Daniel4078 commented
I suppose that you should first create an issue for the sub task that you choose before you produce a pull request, in that way, we can track the progress of our TODO list more easily. Thank you.

2022-08-12 21:29 UTC, Daniel4078 requested changes
There are some changes to be made before the pull request can be approved, Thank you.

2022-08-12 21:29 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_tf_functions.py
> +        fn_name="difference",
Please refer to this pull request (https://github.com/unifyai/ivy/pull/2903) as fn_name should be changed to fn_tree. Also please add a blank line at the end of the file to conform to formatting standards. Thank you.

2022-08-12 21:29 UTC, Daniel4078 commented on ivy/functional/frontends/tensorflow/functions.py
> +subtract.unsupported_dtypes = {"torch": ("float16", "bfloat16")}
I don't think ivy.difference is defined in the code base, so it is not the correct function to use here.
Please add a blank line at the end of the file to conform to formatting standards.

2022-08-13 12:19 UTC, Daniel4078 commented
Also, ivy.difference does not exist yet and your current implementation is wrong. Please read the last paragraph here:
https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis
You might need to convert this issue.

2022-08-15 10:32 UTC, Abdulhaffiz-Umar commented
> Also, ivy.difference does not exist yet and your current implementation is wrong. Please read the last paragraph here: https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis You might need to convert this issue.

Thank you for the feedback, which branch should I channel the conversion to?

2022-08-15 10:34 UTC, Daniel4078 commented
In the case where your chosen function exists in all frameworks by default, but is not implemented in Ivy’s functional API, please convert your existing GitHub issue to request for the function to be added to Ivy. Meanwhile, you can select another frontend function to work on from the ToDo list!

2022-08-15 10:36 UTC, Daniel4078 commented
After you change the issue to be requesting adding the ivy.difference (set-version) function, you can close this pull request and start working on another TODO List issue.

2022-08-15 11:06 UTC, closed without merging