leaky_relu added to jax frontend
unifyai/ivy pull request #2824
Opened 2022-08-09 17:58 UTC by VikramxD

2022-08-10 08:17 UTC, sherry30 requested changes
Hi,

I think you've accidentally added `gelu`, can you kindly remove that.
other than that if you see the documentation of `leaky_relu` [here](https://jax.readthedocs.io/en/latest/_autosummary/jax.nn.leaky_relu.html#jax.nn.leaky_relu), the argument is called `negative_slope` and not `alpha`. so you will have to change that argument name.

Thanks

2022-08-10 08:17 UTC, sherry30 commented on ivy/functional/frontends/jax/nn/non_linear_activations.py
> +def gelu(x):
remove this

2022-08-10 08:17 UTC, VikramxD commented
pr for #2823 from the todolist issue #1515  

1. Implemented leaky_relu in  ivy/functional/frontends/jax/nn/non_linear_activations.py
2. added tests appropriate to leaky_relu functions in ivy_tests/test_ivy/test_frontends/test_jax/test_activations.py

2022-08-10 09:41 UTC, VikramxD commented
@sherry30 this pr is ready for re review please do tell if anything else needs to be changed

2022-08-10 13:19 UTC, VikramxD commented on ivy/functional/frontends/jax/nn/non_linear_activations.py
> +def gelu(x):
removed

2022-08-11 14:13 UTC, sherry30 requested changes
Hi,

Can you also add `negative_slope` argument in your test.
Ideally the test function should test all arguments of the function.

Thanks.

2022-08-12 09:52 UTC, VikramxD commented
@sherry30 changes done accordingly

2022-08-12 13:46 UTC, merged