fix: Fixed `tf.math.floor` for paddle backend
unifyai/ivy pull request #28356
Opened 2024-02-20 18:48 UTC by Sai-Suraj-27

# PR Description
Fixed `tf.math.floor` for paddle backend.

![image](https://github.com/unifyai/ivy/assets/87087741/23a97b85-c1a9-40c2-b04a-d9e20edb4836)

## Related Issue
Closes #28355

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2024-02-21 14:51 UTC, Sai-Suraj-27 commented
> Looks like some tests are failing, can you take a look?

Hey, @KareemMAX. None of them are related to the changes made in this PR.

2024-02-22 11:57 UTC, Ishticode requested changes
In general, good stuff. 
Do you think you can solve the paddle issue in this pr
i get the following error with the changes. I think paddle failed even before the change.
![image](https://github.com/unifyai/ivy/assets/53497039/7d93637c-7203-4561-b354-c4b70d70a4da)

2024-02-26 09:01 UTC, Sai-Suraj-27 commented
> In general, good stuff. Do you think you can solve the paddle issue in this pr i get the following error with the changes. I think paddle failed even before the change. ![image](https://private-user-images.githubusercontent.com/53497039/306985657-7d93637c-7203-4561-b354-c4b70d70a4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzc2ODIsIm5iZiI6MTcwODkzNzM4MiwicGF0aCI6Ii81MzQ5NzAzOS8zMDY5ODU2NTctN2Q5MzYzN2MtNzIwMy00NTYxLWIzNTQtYzRiNzBkNzBhNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA4NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZGMxMThiNDc2ZmJkMTVkN2M2ZTQ5MzJlMjM4ODllODc2ZTBmZDBiODU4YzFiNzNiYTgxNzg0OTQ0MTBlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRDANG62FTR8rUxU7_H_j52uLu-hECby1blzT7Xu3kE)

Hey, @Ishticode Thanks for the review. Yes, the test was failing for the paddle backend even before the changes. The problem is as I mentioned in my previous comment, paddle is considering `-3.7252903e-09` and `0.` to be equal, I think it's a bug from their side.
As you can see, here:
![image](https://github.com/unifyai/ivy/assets/87087741/d67b5db3-7472-48a5-b3e0-cfc4eb27d519)

Due to this, the `paddle.zero_fraction()` function is giving `1` as the output where as the actual output should be `0`.
So, I think it's a bug that should be reported to paddle paddle hence we cannot fix it in this PR.

Please correct me, If I'm wrong. Thank you.

2024-02-26 11:23 UTC, Ishticode approved these changes
willl get this merged. Thansk @Sai-Suraj-27

2024-02-26 11:24 UTC, merged