fixed tensorflow.math.softplus
unifyai/ivy pull request #28466
Opened 2024-03-01 19:16 UTC by ZJay07

# PR Description

## Related Issue

Closes #https://github.com/unifyai/ivy/issues/28465

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

<!--
Please mark your PR as a draft if you realise after the fact that your tests are not passing or
that your pre-commit check has some failures.

Here are some relevant resources regarding tests and pre-commit:

https://unify.ai/docs/ivy/overview/deep_dive/ivy_tests.html
https://unify.ai/docs/ivy/overview/deep_dive/formatting.html#pre-commit

2024-03-10 17:59 UTC, Ishticode requested changes
Hi @ZJay07 
Thank you very much for the PR
I think there are other dtypes that the native tf does support like tf.float16
as maybe checked with
```python
import tensorflow as tf
x = tf.constant([0.5], dtype=tf.float16)
tf.math.softplus(x)
```
does the test not pass for these?

2024-03-11 09:12 UTC, ZJay07 commented
Hey @Ishticode, I tried rerunning the test again adding float16 and got this error, does this means tf.math.softplus does not support float16? 

```
ivy.utils.exceptions.IvyBackendException: paddle: softplus: paddle: abs: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), float16) of kernel `abs` is not registered. Selected wrong DataType `float16`. Paddle support following DataTypes: int32, int64, float64, complex128, float32, complex64.
```

2024-03-16 15:37 UTC, Ishticode commented
> Hey @Ishticode, I tried rerunning the test again adding float16 and got this error, does this means tf.math.softplus does not support float16?
> 
> ```
> ivy.utils.exceptions.IvyBackendException: paddle: softplus: paddle: abs: (NotFound) The kernel with key (CPU, Undefined(AnyLayout), float16) of kernel `abs` is not registered. Selected wrong DataType `float16`. Paddle support following DataTypes: int32, int64, float64, complex128, float32, complex64.
> ```

This mean the paddle backend is unable to run this function with float16. You will need to specify float16 as unsupported for ivy's softplus function paddle backend. Does that make sense?

2024-03-16 15:38 UTC, Ishticode requested changes
This error means the paddle backend is unable to run this function with float16. You will need to specify float16 as unsupported for ivy's softplus function paddle backend. Does that make sense?

2024-03-17 10:08 UTC, ZJay07 commented
Just fixed it and including float16, is this the right way to do it?

2024-03-25 15:49 UTC, Ishticode commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_math.py
> +    if backend_fw == "paddle" and "float16" in input_dtype:
can this be specified as unsupported in paddle backends softplus implementation?

2024-03-26 04:42 UTC, Ishticode approved these changes
Thank you. Looks good to merge :)

2024-03-26 04:43 UTC, merged