Added docstring examples and test to current_backend_str function
unifyai/ivy pull request #2847
Opened 2022-08-10 11:58 UTC by hslau44

2022-08-10 12:04 UTC, hslau44 commented
address issue #2826

2022-08-15 14:45 UTC, ankitdsi2010 requested changes
Go through the logs for run-docstring-tests and figure out why the tests are failing for current_backend_str function.

2022-08-15 14:45 UTC, ankitdsi2010 commented on ivy_tests/test_ivy/test_functional/test_core/test_general.py
> +@pytest.mark.parametrize("backend_str", [None,"numpy", "mxnet", "torch", "tensorflow", "jax"])
Add single whitespace after None and also split it into two lines to prevent lint checks from failing

2022-08-19 10:41 UTC, merged

2022-08-19 10:41 UTC, ankitdsi2010 commented
LGTM! thanks