Fix Frontend Failing Test: torch - math.paddle.stanh
unifyai/ivy pull request #28493
Opened 2024-03-06 17:15 UTC by ZJay07

# PR Description
Failing because of exp returning NaN or inf due to large x, scale_a, scale_b values. Fixed by limit those values from being too large

## Related Issue

Closes #https://github.com/unifyai/ivy/issues/28492

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2024-03-11 14:43 UTC, Ishticode approved these changes
Thanks a lot for the PR @ZJay07  :)

2024-03-11 14:46 UTC, Ishticode requested changes
Although, the `test_paddle_stanh` seems to still fail with paddle and torch backends. You can see that in the logs at https://github.com/unifyai/ivy/actions/runs/8232013594/job/22509022640?pr=28493
Are you able to fix for these two?

2024-03-11 16:49 UTC, ZJay07 commented
Yup, happy to fix it, seems like some results are producing NaN or 0 instead, do you think increasing the min and max `x` values would be sufficient?

2024-03-26 04:28 UTC, Ishticode requested changes
You shold be able to reproduce the errors using the falsifying examples in the failure logs. Like one example for the failure of test_paddle_stanh is given as 
```
[array([[[-1.0000000e+00, -1.0000000e+00],
E                 [-1.0000000e+00, -1.0000000e+00],
E                 [-1.0000000e+00, -1.0000000e+00],
E                 [-1.0000000e+00, -1.0000000e+00]],
E         
E                [[-9.0909090e+00, -1.2930438e-38],
E                 [-1.8302815e-38, -2.3399685e-38],
E                 [-1.2930438e-38, -1.9542594e-38],
E                 [-1.2930438e-38, -1.0000000e+00]]], dtype=float32)]),
E       scale_a=10.0,
E       scale_b=1.0,
```
so you can write something like
```python
import ivy
import ivy.functional.frontends.paddle as ivy_paddle
ivy.set_backend("torch")
x = ivy.arrayarray([[[-1.0000000e+00, -1.0000000e+00],
[-1.0000000e+00, -1.0000000e+00],
[-1.0000000e+00, -1.0000000e+00],
[-1.0000000e+00, -1.0000000e+00]],

[-9.0909090e+00, -1.2930438e-38],
[-1.8302815e-38, -2.3399685e-38],
[-1.2930438e-38, -1.9542594e-38],
[-1.2930438e-38, -1.0000000e+00]]], dtype="float32")])
scale_a=10.0
scale_b=1.0
```
and add the same with native paddle
```python
import paddle
x = paddle.to_tensor([[[-1.0000000e+00, -1.0000000e+00],
                [-1.0000000e+00, -1.0000000e+00],
                [-1.0000000e+00, -1.0000000e+00],
                [-1.0000000e+00, -1.0000000e+00]],
               [[-9.0909090e+00, -1.2930438e-38],
               [-1.8302815e-38, -2.3399685e-38],
               [-1.2930438e-38, -1.9542594e-38],
               [-1.2930438e-38, -1.0000000e+00]]], dtype="float32")
scale_a=10.0
scale_b=1.0
print(paddle.stanh(x, scale_a, scale_b))
```
and you will see the value difference and why the test failed as ivy's paddle frontend's behaviour differs from native paddle.

My point is try to reconstruct the failing example from the falsifying examples provided in the logs and this way you can always reproduce and debug quickly. Thank you very much :)

2024-04-02 17:01 UTC, ZJay07 commented
Hey @Ishticode, I just updated the backend paddle code to accept `stanh` and re-cast it back to the same dtype as x as per paddle docs, also added some factors to `scale_a` and `scale_b` that is similar to `addmm` in the same file

2024-04-08 04:16 UTC, Ishticode approved these changes
now it seems to behave well :) haha
Thanks @ZJay07 for the fix

2024-05-02 08:41 UTC, merged