Add Lax Jax frontend square operator function and test passed
unifyai/ivy pull request #2863
Opened 2022-08-10 17:05 UTC by Bambarithm

This PR addresses the issue https://github.com/unifyai/ivy/issues/2862 which is tracked in https://github.com/unifyai/ivy/issues/1578

Please review.

Thanks

2022-08-15 08:41 UTC, Ishticode requested changes
Hi @Bambarithm Good PR. Minor change requested. Please request my review when done..

2022-08-15 08:41 UTC, Ishticode commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_operators.py
> +            fw="torch",
please add fw argument

2022-08-16 18:39 UTC, Bambarithm commented
Hi @Ishticode thanks for reviewing my PR :smiley:

2022-08-16 19:16 UTC, Ishticode requested changes
Hi. So two requests.
Firstly, Could you remove the unsupported part bcz torch does support square function for float16 or bfloat16. Any reason you stated them unsupported that i am unaware of perhaps?

Secondly, Could you try and resolve the conflict if possible. Let me know if you need help for that.
Thanks 😊

2022-08-16 21:00 UTC, Bambarithm commented
So I tried removing the unsupported part and part of the test started failing.  I get the following error: 

E           TypeError: can't convert np.ndarray of type bfloat16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

3 out of 4 ivy functional backend tests passed except for the torch one which is weird.

Also, I resolved the conflict. Please review it. 

Thanks

2022-10-03 14:43 UTC, MrZilinXiao commented
Hi @Bambarithm @Ishticode! I am responsible for checking stale PRs regularly. Since this PR has been inactive for 39 days, I am wondering if this PR is still ongoing. Feel free to reply, or I will close it within 24 hours. In the meanwhile, you could reopen it if you believe the PR is still useful for you.

2022-10-04 16:18 UTC, closed without merging