fix: fixed `test_torch___getitem__` for paddle backend
unifyai/ivy pull request #28631
Opened 2024-03-18 10:00 UTC by ZenithFlux

# PR Description

- Fixed the syntax for checking if x is a True.
- Added a function to remove negative values in arrays inside `query` of `paddle.get_item` because paddle currently throws an error if any value in the arrays inside the query is negative.

## Related Issue

Closes #28630

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

### Socials

2024-03-21 12:43 UTC, Ishticode requested changes
Hi @ZenithFlux 
Thank you very much for the PR.
The changes here are critical and seem to have lead to many many failures for paddle tests that you can check under logs here at https://github.com/unifyai/ivy/actions/runs/8326992315/job/22798877642?pr=28631
Check Display Test Failures for a list of functions failing.

2024-03-22 14:01 UTC, ZenithFlux commented
@Ishticode I don't think these failures are due to my changes.

I confirmed this by reverting all my changes and adding only a comment to both the functions (to trigger the same tests). Even without any changes to the code, there were still about a 100 tests failing. I also ran the tests for the some other failing functions on my local machine and I couldn't find any failure that was newly introduced by this branch. On the contrary, the tests I ran for `unfold` function passed successfully with no errors. I think this is because this change triggers many failing tests whose issues may be unrelated.

If there's is still something I am missing I will be happy to fix that.

2024-03-22 14:03 UTC, ZenithFlux commented
@Ishticode I don't think these failures are due to changes on this branch.

I confirmed this by reverting all my changes and adding only a comment to both the functions (to trigger the same tests). Even without any changes to the code, there were still about a 100 tests failing. I also ran the tests for the some other failing functions on my local machine and I couldn't find any failure that was newly introduced by this branch. On the contrary, the tests I ran for `unfold` function passed successfully with no errors. I think this is because this change triggers many failing tests whose issues may be unrelated.

If there's is still something I am missing I will be happy to fix that.

2024-03-25 12:54 UTC, Ishticode reviewed
Right, otherwise looks good. I will merge it after quick few checks later today :)

2024-03-26 04:04 UTC, Ishticode approved these changes
tests seems fine and i've checked with some custom examples. Looks good. I will merge now. Thank you very much for the effort put into this contribution @ZenithFlux :)

2024-03-26 04:08 UTC, merged