Implementation of less_equal function, conforming to Array API standard
unifyai/ivy pull request #291
Opened 2022-02-22 13:02 UTC by georg-wolflein

This is the implementation of issue #272.

Although all tests are passing on my local machine (numpy, jax, torch, tensorflow), I'd like to draw attention to two things:
1. I needed to modify `builtin_le` in `ivy/functional/ivy/core/array_builtins.py` to return the result of `ivy.less_equal` instead of `x.__le__` to get the tensorflow tests to pass. 
2. The tensorflow and pytorch implementation require some dtype casting which is similar for the `equal` function, so I refactored it into the `_compare` function, as I presume similar logic will be needed in the future for functions like `greater_equal`(#198, #220, #236, #126, etc.).

2022-02-23 10:19 UTC, djl11 commented
Thanks a lot for your contribution. Could you update the methods to follow the formatting explained in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/)? I also go through some examples in the Array API [tutorial series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl) on YouTube.

Essentially:

- All methods should be defined with `def func_name` explicitly, no lambdas or direct binding.
- All Ivy methods should have type-hints and doc strings
- All backend methods should have type-hints, but no doc strings.
- All Array API methods should be moved to the correct sub-modules and files.

Please check the contributor guide in the docs for more details. Thanks!

Additionally, it may be necessary to resolve new conflicts with master since the PR was made. As a guide for resolving conflicts with upstream, I have created this short [YouTube series](https://www.youtube.com/watch?v=KCMceLBBlgs&list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG).
Once there are no conflicts with upstream and the formatting is all correct, I'll then take a look at the tests and see if it's ready to be merged :)

2022-02-23 17:23 UTC, djl11 requested changes
Please make changes as explained in the earlier comment :)

2022-02-24 12:27 UTC, djl11 requested changes
Please reformat the code as describe in the [contributor guide](https://lets-unify.ai/ivy/contributing.html) in the [docs](https://lets-unify.ai/ivy/), and also as explained in this [YouTube series](https://www.youtube.com/watch?v=HNV4eI0zp4M&list=PLwNuX3xB_tv96FaEUmTirlQLIsnUgvtTl).

2022-02-24 12:28 UTC, georg-wolflein commented
Hi @djl11, thanks for your comments. Will implement the changes later today.

2022-02-24 14:42 UTC, georg-wolflein commented on ivy/array/__init__.py
> +        return ivy.less_equal(self._data, other)
I couldn't use `ivy.builtin_le` because that fails one of the tensorflow Array API tests

2022-03-10 01:13 UTC, 1Doomdie1 commented
Hey georg-wolflein, thank you for contributing!
Next time after you made the changes requested by a ivy team member please request a "Code Review".
I've requested one for you now but please keep this in mind!
If you fail to do so the PR will remain unchecked and will be closed automatically!

2022-03-10 13:04 UTC, merged

2022-03-10 13:04 UTC, djl11 commented
Thanks!