Adding leaky_relu torch frontend
unifyai/ivy pull request #2914
Opened 2022-08-11 21:38 UTC by AymenSe

2022-08-11 21:43 UTC, AymenSe commented
#2723

2022-08-16 12:14 UTC, AymenSe commented
@bicycleman15 Could you please review the changes please

2022-08-17 04:58 UTC, bicycleman15 commented
Hey, @AymenSe it's a good start.
Could you please remove changes made at `.idea` folder, we don't want to touch that.
Also there are some merge conflicts, please resolve those as well.

Rest of the PR looks good to me. will merge as soon as you make the above changes 🙂

2022-08-18 11:29 UTC, AymenSe commented
Hi, @bicycleman15  I think everything is okay now, could you check, please?

2022-08-18 17:53 UTC, bicycleman15 commented
Hey, I think the frontend tests are failing for `leaky_relu` that you implemented, could you please resolve it ? 🙂

2022-08-20 11:12 UTC, bicycleman15 requested changes
Have a look at my comments, the rest looks good. I will merge as soon as you do the changes :)

2022-08-20 11:12 UTC, bicycleman15 commented on .idea/misc.xml
> -<?xml version="1.0" encoding="UTF-8"?>
You should add this file back, and it's contents should be exactly as in: https://github.com/unifyai/ivy/blob/master/.idea/misc.xml

2022-08-20 11:12 UTC, bicycleman15 commented on .idea/runConfigurations/pytest_for_all__jax_.xml
> -<component name="ProjectRunConfigurationManager">
Same here for this file: add it back and the contents should be: https://github.com/unifyai/ivy/blob/master/.idea/runConfigurations/pytest_for_all__jax_.xml

2022-08-20 13:30 UTC, AymenSe commented
@bicycleman15 could you please check now?

2022-08-20 15:19 UTC, bicycleman15 approved these changes
LGTM!

2022-08-20 15:20 UTC, merged