torch negative frontend & test
unifyai/ivy pull request #2934
Opened 2022-08-12 13:17 UTC by ytg32

2022-08-12 16:34 UTC, simonetgordon commented
Hi,

Thanks for the contribution!

It's looking pretty good. However, before I can merge with master, merge conflicts will need to be resolved in the two files indicated.

2022-08-12 16:39 UTC, simonetgordon requested changes

2022-08-12 16:39 UTC, simonetgordon commented on ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py
> +    )
Insert blank line at the end of the file to conform to formatting standards

2022-08-12 19:40 UTC, ytg32 commented
It seems `fn_name` argument changed to `fn_tree` in last commit, but that change was not made for `asin `function for some reason. I also corrected as `fn_tree `in `asin` function.

2022-08-13 10:38 UTC, kanakmi commented
As someone who has recently implemented the negative function in Tensorflow frontend, I would like to point out that for this function, the valid inputs should not just be limited to floats but to all the numeric types except "uint".

2022-08-14 14:56 UTC, closed without merging