add softplus to jax
unifyai/ivy pull request #3032
Opened 2022-08-15 10:00 UTC by PatricYan

- [ ] #3030 
1. add **softplust** to **jax** 
2. test case

2022-08-15 15:21 UTC, ankitdsi2010 requested changes
fix the error in the [test-frontend-jax test](https://github.com/unifyai/ivy/runs/7835875962?check_suite_focus=true#step:4:131)

2022-08-16 02:11 UTC, PatricYan commented
Hi, it is ** test_jax_nn_gelu** error for the backended code updated, I think after this PR, I can make a new PR for this error

2022-08-16 02:14 UTC, PatricYan commented
> fix the error in the [test-frontend-jax test](https://github.com/unifyai/ivy/runs/7835875962?check_suite_focus=true#step:4:131)

done, the test case error is fixed

2022-08-16 11:48 UTC, ankitdsi2010 requested changes

2022-08-16 11:48 UTC, ankitdsi2010 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_nn_activations.py
> +    )
Add newline at end of file

2022-08-16 11:49 UTC, PatricYan commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_nn_activations.py
> +    )
done

2022-08-16 11:51 UTC, PatricYan commented
Hi, I have updated the code for the conflict. and in test-fronted-jax it is ** test_jax_nn_softmax** not **test_jax_nn_softplus** error

2022-08-16 12:02 UTC, PatricYan commented
Hi @ankitdsi2010, would you like to make a review for it?

2022-08-16 12:07 UTC, merged

2022-08-16 12:07 UTC, ankitdsi2010 commented
Thanks for your contribution