Checklist action changes
unifyai/ivy pull request #3039
Opened 2022-08-15 11:18 UTC by abdrahmandiab

2022-08-15 15:05 UTC, Aarsh2001 commented on .github/workflows/checklist_actions.yml
> +        uses: actions/checkout@v2
I suggest you checkout to ivy like this -:
```
 uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
```

and put `reformat_checklist.md` somewhere inside `automation tools`

2022-08-15 15:06 UTC, Aarsh2001 commented on .github/workflows/checklist_actions.yml
>            template: .github/reformat_checklist.md
do `ivy/automation_tools/somewhere/reformat_checklist.md`

2022-08-15 15:06 UTC, Aarsh2001 requested changes
I suggest you look at the following changes, nothing too big. Just that it would align the way we do things and have them a little more organised in fashion

2022-08-16 03:29 UTC, abdrahmandiab commented
> I suggest you look at the following changes, nothing too big. Just that it would align the way we do things and have them a little more organised in fashion

Hi Aarsh, I've made all the changes you requested :)
If you think it's all good now you can go ahead and merge or let me know and I'll do the merge myself 😃

2022-08-16 04:31 UTC, Aarsh2001 approved these changes

2022-08-16 04:31 UTC, merged