jax frontend - implement `while_loop` function and test
unifyai/ivy pull request #3236
Opened 2022-08-19 08:18 UTC by juliagsy

2022-09-02 19:56 UTC, Daniel4078 requested changes
Firstly, there is an Type error when running your test (TypeError('must be real number, not ShapedArray')). This seemed to be caused by a x = ShapedArray(bool[1]) passed to the format_float_positional function. I do not know the exact cause of the error but I suspect that it is cause by the fact that ivy.less produce an array of booleans but then the next loop expect an array of numbers
Secondly, there are some small errors that you need to fix and please check my comments below for details.

2022-09-02 19:56 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_control_flow_operators.py
> +        with_out=False,
with_out should be passed in through the arguments of test_jax_while_loop as the @handle_cmd_line_args will fill in the with_out argument automatically.

2022-09-02 19:56 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_control_flow_operators.py
> +
please add a comment here like: "# while_loop"

2022-09-03 02:34 UTC, juliagsy commented
Hey! Thanks for the comments! I'm one of the team member actually and I'm aware of the tests as well! Putting this on hold as I'm still thinking about it's design 😊 

You may skip this PR while searching for one to review! 😁

2022-09-12 07:16 UTC, closed without merging