Added numpy shape function and tests
unifyai/ivy pull request #3294
Opened 2022-08-20 13:39 UTC by alvin-98

- [] #3284

2022-08-26 05:36 UTC, RashulChutani requested changes
Hi @alvin-98 As mentioned in the Contributing guide (https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis), we do not need to have type hints for frontend functions. Can we please remove the same? Thanks.

2022-09-02 22:11 UTC, roboFiddle requested changes
I put a couple changes that need to be made, otherwise it looks good.

2022-09-02 22:11 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_manipulation_routines/test_basic_operations.py
> +    print(xs)
Please don't print in tests as it clutters the output.

2022-09-02 22:11 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_manipulation_routines/test_basic_operations.py
> +    )
There should be a empty line at the end of the file.

2022-09-04 00:42 UTC, closed without merging

2022-09-04 00:54 UTC, roboFiddle commented
Hi, it seems like there was an issue merging this PR. Could you reopen this or open a new PR and I'll merge it right away. 

Sorry for the difficulty.

2022-09-04 09:52 UTC, alvin-98 commented
Hi, I have created a new PR here #4029. Please let me know if this works.