add sin to tensorflow
unifyai/ivy pull request #3353
Opened 2022-08-22 04:10 UTC by PatricYan

- [ ] #3352

2022-08-22 05:56 UTC, rush2406 requested changes
Hi @PatricYan 
Thanks for contributing, there's a minor change required as mentioned below and please fix the merge conflicts as well!

2022-08-22 05:56 UTC, rush2406 commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +def sin(x):
can you please add `name="sin"`?

2022-08-22 06:13 UTC, PatricYan commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +def sin(x):
done

2022-08-22 06:14 UTC, PatricYan commented
> 

Hi @rush2406 , I have resolved it by adding "name"

2022-08-23 10:11 UTC, rush2406 approved these changes

2022-08-23 10:12 UTC, merged