Add Numpy Frontend trunc (#3503)
unifyai/ivy pull request #3504
Opened 2022-08-23 22:03 UTC by aryanxk02

Fixes #3503

2022-08-23 22:12 UTC, aryanxk02 commented
Hey @CatB1t,

I wrote code for implementing trunc function, but the commit shows commits from my previous PR where I have implemented cbrt function. 

Why is it so?

2022-08-24 05:26 UTC, aryanxk02 commented
Okay, I have resolved the merge conflicts!

2022-08-24 05:36 UTC, CatB1t commented
Hello @aryanxk02, Please add the test for the function `trunc`.

2022-08-24 05:56 UTC, aryanxk02 commented
Hello @CatB1t, I have added the test function for the ```trunc``` function. Please review!

2022-08-24 11:12 UTC, MrZilinXiao commented
> Hello @CatB1t, I have added the test function for the `trunc` function. Please review!

Hi @aryanxk02, the test you added recently has not passed numpy frontend testing. Please consider reviewing your code :)
https://github.com/unifyai/ivy/runs/7988315371?check_suite_focus=true#step:4:4363

2022-08-24 11:15 UTC, aryanxk02 commented
Hello @MrZilinXiao how do I approach exactly? Can you give me a few pointers on what changes must be done in order to get the tests passing? In this case numpy frontend tests!

2022-08-24 13:02 UTC, CatB1t requested changes

2022-08-24 13:02 UTC, CatB1t commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_arithmetic_operations.py
> +# trunc
Please add the @handle_cmd_line_args, this allows us to handle with_out, as_variable, etc, by us.

2022-08-24 14:01 UTC, aryanxk02 commented
Do I have to replace the code written from line 403 to line 413 and replace with ```@handle_cmd_line_args``` @CatB1t

2022-08-24 14:06 UTC, aryanxk02 commented
Do I have to remove the contents present from line 403 to line 413 and add ```@handle_cmd_line_args```? @CatB1t

2022-08-24 14:44 UTC, CatB1t commented
Hello @aryanxk02, sorry for the confusion, these parameters shouldn't be generated ey you: 
- `with_out`
- `native_array`
- `where`
- `as_variable`

and therefore you should remove them, after adding the `@handle_cmd_line_args` decorator.

2022-08-24 15:16 UTC, aryanxk02 commented
The requested changes have been made @CatB1t. Please review and let me know if anything needs to be changed!

2022-08-25 08:23 UTC, CatB1t commented
Hello @aryanxk02, the tests for `trunc` is not passing, please fix that. https://github.com/unifyai/ivy/runs/7998192463?check_suite_focus=true#step:4:4774

2022-10-03 14:55 UTC, MrZilinXiao commented
Hi all! I am responsible for checking stale PRs regularly. Since this PR has been inactive for 30 days, I am wondering if this PR is still ongoing. I will now close it. In the meanwhile, you could reopen it if you believe the PR is still useful for you.

2022-10-03 14:55 UTC, closed without merging