Fix module stateful submodule
unifyai/ivy pull request #3651
Opened 2022-08-26 10:43 UTC by RickSanchezStoic

fix_module_stateful_submodule

2022-09-06 14:58 UTC, MrZilinXiao commented on ivy/stateful/module.py
> +        argument is set to True during call
don't think this func works as the comment tells

2022-09-18 11:40 UTC, RickSanchezStoic commented
@djl11 Currently the following functions don't have a docstring `mod_with_top, _mod_key_chain
_add, _submod_enter,
_extract_v`. Rest all have been added by me Zilin and Jin from what we could figure out. Kindly have a look and let me know if more changes are needed. The tests are passing except for the module training for jax backend, it takes a little longer to train so will have to increase the hypothesis' time limit to about 5000 ms.

2022-09-19 08:11 UTC, djl11 requested changes
Please remove all cases of commented-out old code, otherwise looks good to merge. As you said, the docstrings will require some more work, but that can come later. Also, we should just increase the global default timeout to 7000 I would say.

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_ic_oc", [([1, 2], 4, 5)])
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_ic_oc", [([1, 2], 4, 5)])
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_ic_oc", [([1, 2], 4, 5)])
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_ic_oc", [([1, 2], 4, 5)])
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_c", [([1, 2], 64)])
these comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_ic_oc", [([1, 2], 4, 5)])
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +    # batch_shape, input_channels, output_channels = bs_ic_oc
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_ic_oc", [([1, 2], 4, 5)])
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +    # batch_shape, input_channels, output_channels = bs_ic_oc
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +# @pytest.mark.parametrize("bs_ic_oc", [([1, 2], 4, 5)])
this comments can be removed

2022-09-19 08:11 UTC, djl11 commented on ivy_tests/test_ivy/test_stateful/test_modules.py
> +    # batch_shape, input_channels, output_channels = bs_ic_oc
this comments can be removed

2022-09-20 05:46 UTC, merged