add binary_crossentropy
unifyai/ivy pull request #3658
Opened 2022-08-26 13:46 UTC by mustafa1adel

2022-08-29 16:34 UTC, roboFiddle commented
Hi @mustafa1adel,

Thanks for the PR! Could you please add a frontend test for the function, as described here in the [task description](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#frontend-apis) and [deep dive](https://lets-unify.ai/ivy/deep_dive/17_ivy_frontends_tests.html). 

Once this is added, I'll finish reviewing this PR.

2022-08-29 19:00 UTC, mustafa1adel commented
Hi @roboFiddle ,
I added the needed frontend test for binary_crossentropy.

2022-08-30 04:45 UTC, roboFiddle requested changes
I added some comments to the test function. Also, please fix the merge conflicts and then I'll be able to complete this.

2022-08-30 04:45 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_metrics.py
> +    num_positional_args=helpers.num_positional_args(fn_name= \
put the `fn_name` on the next line instead of breaking it up here

2022-08-30 04:45 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_metrics.py
> +def test_binary_crossentropy( y_true,
format with one argument per

2022-08-30 04:45 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_metrics.py
> +                            as_variable,
this should also be generated by hypothesis

2022-08-30 04:45 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_metrics.py
> +    y_true=st.lists(st.integers(min_value=0, max_value=4), min_size=1, max_size=1),
make sure that spaces line up

2022-08-30 18:45 UTC, roboFiddle commented
Thanks for the changes. It seems that the test function is referring to the wrong Tensorflow function in the `fn_tree` parameter. Can you also make sure that the lint passes. You can run it yourself using `flake8` or check the errors [here](https://github.com/unifyai/ivy/runs/8099282192?check_suite_focus=true).

2022-08-30 19:15 UTC, merged

2022-08-30 19:15 UTC, roboFiddle commented
Looks good, thanks.