Added pinv to tensorflow frontend.
unifyai/ivy pull request #3665
Opened 2022-08-26 15:49 UTC by JoelPendleton

#3615

2022-08-29 09:22 UTC, JoelPendleton commented
Would it be possible to get feedback on why my code did not pass the tests?

2022-08-30 08:05 UTC, Unevilicorn requested changes
The function looks good, the only ones not passing for this function are the lint tests.

2022-08-30 08:05 UTC, Unevilicorn commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py
> +@given(
lint errors in this function

2022-08-30 08:05 UTC, Unevilicorn commented on ivy/functional/frontends/tensorflow/linalg.py
> +def pinv(a, rcond=None, validate_args=False, name=None):
lint errors in this function

2022-08-30 14:37 UTC, Unevilicorn commented
Looks good, I'll get this merged

2022-08-30 14:38 UTC, merged