add minimum in mathematical function
unifyai/ivy pull request #3696
Opened 2022-08-27 18:46 UTC by AmeenUrRehman

Add minimum mathematical function 
#3691 issue no. one of the tasks of #1525

2022-08-27 18:50 UTC, AmeenUrRehman commented
@JLU-Neal Could we ready to merge plz check

2022-08-28 04:54 UTC, AmeenUrRehman commented
@juliagsy hey could review my code plz

2022-08-28 04:56 UTC, AmeenUrRehman commented
@VedPatwardhan Hey Could you review my code plz.

2022-08-28 11:40 UTC, AmeenUrRehman commented
Issue no. #3691

2022-08-29 02:58 UTC, AmeenUrRehman commented
@JLU-Neal could you plz check my code plz

2022-08-29 02:59 UTC, AmeenUrRehman commented
@Daniel4078 hey could you plz check my code Thank You!

2022-08-29 08:47 UTC, AmeenUrRehman reviewed
@JLU-Neal Plz check my code

2022-08-29 11:23 UTC, AmeenUrRehman commented
@juliagsy Could you plz review my code and check if we merge this

2022-08-29 11:32 UTC, juliagsy commented
Hey there! ahh sure, I'll review soon, sorry for the delay!

2022-08-29 11:43 UTC, juliagsy requested changes
Hey there! Thanks for contributing! There are slight changes needed and you're almost good to go! As usual, please request my review once you're done! Thank you!

2022-08-29 11:43 UTC, juliagsy commented on ivy/functional/frontends/numpy/mathematical_functions/extrema_finding.py
> +from ivy.func_wrapper import from_zero_dim_arrays_to_float
seems like unused import, please remove if it's not used

2022-08-29 11:43 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +    as_variable=helpers.array_bools(),
please add the `num_arrays=2` parameters in data generation for `as_variable` and `native_array` as there are 2 arrays involved in the operation

2022-08-29 11:43 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +    native_array=helpers.array_bools()
above comment

2022-08-29 11:43 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +    with_out=st.booleans(),
you can remove this as it is handled in the `handle_cmd_line_arg` decorator, but please keep it in the` test_numpy_minimum` argument list

2022-08-29 16:12 UTC, AmeenUrRehman commented
@juliagsy Plz review this I've try to resolve all issues

2022-08-30 00:49 UTC, juliagsy requested changes
Hello! Great work so far! One last small fix and you're almost good to go! Please request my review again once you're done! Thanks a lot!

2022-08-30 00:49 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_extrema_finding.py
> +        available_dtypes=ivy_np.valid_float_dtypes,
please also add a parameter `num_arrays=2` in this helper functions

2022-08-30 02:12 UTC, AmeenUrRehman commented
@juliagsy Thank You! for your guidance plz review the code I've fixes the issue

2022-08-30 03:06 UTC, juliagsy approved these changes
Thanks for contributing! I will merge the PR soon!

2022-08-30 03:17 UTC, merged