Adding tanh activation function for torch, addresses the issue #2686
unifyai/ivy pull request #3711
Opened 2022-08-28 10:31 UTC by bsovdat

Fixed some issues...

2022-08-29 03:09 UTC, juliagsy requested changes
Hey there! Great work so far! Please remove any changes related to the `idea` folder and only commit or keep changes related to the function and tests. As usual, please request my review again once you're done! Thank you!

2022-08-30 10:30 UTC, bsovdat reviewed
Now i am only commiting .py files?!

2022-08-31 03:05 UTC, juliagsy requested changes
Hey there! Thanks for the previous changes! There are some changes required before the PR is good to go! As usual, please request my review once you're done! Thank you!

2022-08-31 03:05 UTC, juliagsy commented on ivy/functional/frontends/torch/non_linear_activation_functions.py
> +tanh.unsupported_dtypes = ("float16",)
this is only unsupported in torch, please use `{"torch": ("float16",)}` instead

2022-08-31 03:05 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_torch/test_non_linear_activation_functions.py
> +    as_variable=st.booleans(),
please remove `as_variable`, `with_out` and `native_array` here, they are generated internally through the `@handle_cmd_line_arg` decorator

but remain to **keep** them in the argument lists in `test_torch_tanh`

2022-08-31 03:05 UTC, juliagsy commented on ivy_tests/test_ivy/test_frontends/test_torch/test_non_linear_activation_functions.py
> +        input_dtypes=input_dtype,
please use `[input_dtype]` here

2022-09-02 01:35 UTC, juliagsy approved these changes
Thanks for contributing! I will merge the PR soon!

2022-09-02 02:28 UTC, merged