maximum to torch frontend
unifyai/ivy pull request #3899
Opened 2022-08-31 20:22 UTC by mazy06000

#3898

2022-09-01 10:36 UTC, mazy06000 commented
Hello @RashulChutani, let me know if you think the code is correct.

2022-09-03 15:59 UTC, CheezBallzPi requested changes
Reviewed.

2022-09-03 15:59 UTC, CheezBallzPi commented on ivy_tests/test_ivy/test_frontends/test_torch/test_comparison_ops.py
> +        shared_dtype=True,
I think maximum supports differing dtypes, but check yourself to be sure.

2022-09-03 15:59 UTC, CheezBallzPi commented on ivy_tests/test_ivy/test_frontends/test_torch/test_comparison_ops.py
> +        input=np.asarray(inputs[0], dtype=input_dtype[0]),
The input should be a torch tensor, not a numpy array.

2022-09-03 15:59 UTC, CheezBallzPi commented on ivy_tests/test_ivy/test_frontends/test_torch/test_comparison_ops.py
> +    with_out,
`with_out` needs to be defined in `@given`.

2022-09-18 02:18 UTC, closed without merging