Stateful norms fix up
unifyai/ivy pull request #4000
Opened 2022-09-03 11:50 UTC by Aarsh2001

2022-09-08 05:35 UTC, VedPatwardhan requested changes
Hi @Aarsh2001, I have suggested a few changes, please take a look 🙂

2022-09-08 05:35 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_stateful/test_norms.py
> +    num_positional_args_init=helpers.num_positional_args(fn_name="LayerNorm.__init__"),
I think we don't need to use this helper as we have pre-defined positional-only and keyword-only arguments, please pass the number of positional-only args to the test_method as a constant directly.

2022-09-08 05:35 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_stateful/test_norms.py
> +    print(f"\nbefore -: {input_dtype}")
debug statement

2022-09-08 05:35 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_stateful/test_optimizers.py
> -        all_as_kwargs_np_method={
Please revert this change as it's related to a different submodule

2022-09-09 05:41 UTC, VedPatwardhan approved these changes
Hi @Aarsh2001, the changes look good to me, I'll just request Dan's review on this PR now 🙂

2022-09-09 15:49 UTC, djl11 approved these changes
lgtm!

2022-09-09 17:02 UTC, merged