Add band_part function for tensorflow frontend
unifyai/ivy pull request #4352
Opened 2022-09-12 11:57 UTC by Change-m

#4351

2022-09-13 04:30 UTC, VedPatwardhan requested changes
Hi @Change-m, I have suggested a change, please feel free to re-request my review once you're done. Thanks 🙂

2022-09-13 04:30 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py
> +    @handle_cmd_line_args
Please fix the indentation.

2022-09-13 07:01 UTC, Change-m commented
Hi [VedPatwardhan](https://github.com/VedPatwardhan), I fix the indentation.

2022-09-14 04:55 UTC, VedPatwardhan requested changes
Hi @Change-m, thanks for making the changes. Just requested a few more changes. Thanks🙂

2022-09-14 04:55 UTC, VedPatwardhan commented on ivy/functional/frontends/tensorflow/linalg.py
> +    return ivy.band_part(input, num_lower, num_upper)
I don't think there's a `band_part` function in Ivy's functional API, so either you'll have to implement the `tensorflow` `band_part` frontend as a composition of existing Ivy functions or extend Ivy's functional API by adding `ivy.band_part` in a separate PR referring to the [docs](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#ivy-api-extensions)

2022-09-14 04:55 UTC, VedPatwardhan commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_linalg.py
> +    dtype_and_input=_get_dtype_and_matrix(),
You need to generate data for all parameters in the function, i.e. `input`, `num_lower`, `num_upper`, `name` in the `given` block and then pass them to the `test_frontend_function`

2022-09-16 05:09 UTC, VedPatwardhan commented
I'll close this PR as discussed. Thanks 🙂

2022-09-16 05:09 UTC, closed without merging