Add rad2deg function to numpy frontend
unifyai/ivy pull request #4364
Opened 2022-09-12 18:19 UTC by JonaOmara

Close #4226

2022-09-12 19:34 UTC, roboFiddle requested changes
I added a few comments, otherwise it looks good.

2022-09-12 19:34 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
> +        test_values=False,
You should be testing values, set this to true

2022-09-12 19:34 UTC, roboFiddle commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py
> +    )
You don't need to call `handle_where_and_array_bools`. Take out lines 498-504 and just use `input_dtype` later.

2022-09-13 19:50 UTC, roboFiddle commented
It seems that your function does not match the NumPy function. For example, passing `-0.9090909090909091` returns `-52.08345413208008` from your function, while the NumPy rad2deg function returns `-52.09375`. As a guess, this probably is caused by the non-associativity of floating-point operations. Perhaps you can try first dividing by Pi and then multiplying by 180, or just multiplying by a factor of `180/pi` to do this in one operation. Secondly, you should make sure to set `out=out` in all Ivy function calls.

Lastly, you can check both these points by running the test using `python3 -m pytest --num-examples=500 -k test_numpy_rad2deg ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py`

2022-09-13 21:17 UTC, roboFiddle requested changes
See above comment.

2022-09-14 08:37 UTC, JonaOmara commented
@roboFiddle , when I run the test `python3 -m pytest --num-examples=500 -k test_numpy_rad2deg ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_np_trigonometric_functions.py` I get this error `/usr/bin/python3: No module named pytest`, I think there is some setting that I didn't put correct, but I have only been running the tests with the Run button but I would also wish to run the tests in the terminal, what do I need to set right.

However I've divided `x/pi` and multiplied with `180 ` and I've also added `out=out` for all the Ivy functions, I hope this sorts the issue.

2022-09-15 20:13 UTC, roboFiddle commented
Don't worry about it, if you're able to run the tests it's fine. This looks good, merging. Thanks for the contribution!

2022-09-15 20:13 UTC, merged