Add collapse_repeated to tensorflow frontend
unifyai/ivy pull request #4400
Opened 2022-09-13 10:49 UTC by Change-m

Close #4396

2022-09-14 05:00 UTC, VedPatwardhan requested changes

2022-09-14 05:00 UTC, VedPatwardhan commented on ivy/functional/frontends/tensorflow/nn.py
> +def collapse_repeated(labels, seq_length, name=None):
I don't think there's a `collapse_repeated` function in Ivy's functional API, so either you'll have to implement the `tensorflow` `collapse_repeated` frontend as a composition of existing Ivy functions or extend Ivy's functional API by adding `ivy.collapse_repeated` in a separate PR referring to the [docs](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#ivy-api-extensions)

2022-09-16 05:10 UTC, VedPatwardhan commented
I'll close this PR as discussed. Thanks 🙂

2022-11-06 14:38 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-14 06:50 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-14 07:09 UTC, closed without merging

2022-11-14 07:09 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.