softplus_superset
unifyai/ivy pull request #4449
Opened 2022-09-14 10:54 UTC by Ishticode

Based on the additional arguments in [torch softplus](https://pytorch.org/docs/stable/generated/torch.nn.functional.softplus.html).

This just requires that the `x` is `x * beta` and that the final results is multiplied by `1/beta` as explained [here](https://pytorch.org/docs/stable/generated/torch.nn.Softplus.html#torch.nn.Softplus). 

`torch` takes this as arg while for other backends it is done manually. Test passing.

Should we consider adding the argument `threshold` also from [torch softplus](https://pytorch.org/docs/stable/generated/torch.nn.functional.softplus.html)**?** It didn't seem to have much use given that softplus is linear for values beyond 4 or 5 unless beta is changed from 1.

2022-09-15 10:54 UTC, djl11 requested changes
looks great! Yes please add the threshold also and then request another review :)

2022-09-15 15:09 UTC, Ishticode commented
> looks great! Yes please add the threshold also and then request another review :)

added with docstring examples.

2022-09-15 19:58 UTC, djl11 requested changes
it says values above the threshold "revert to a linear function", you seem to just be clipping the values at `20`, I believe this is incorrect.

2022-09-15 20:29 UTC, Ishticode commented
> it says values above the threshold "revert to a linear function", you seem to just be clipping the values at `20`, I believe this is incorrect.

Sorry my bad. Updated now. Somehow it went thru tests with 50 example set. The current implementatio is according to [**this**](https://github.com/pytorch/pytorch/blob/2386cd2945498ce7261b761a8d9bd5b59d06c5a1/torch/_refs/nn/functional/__init__.py#L243). It seems need to add support for None as well.

2022-09-17 10:40 UTC, djl11 requested changes
the `threshold` argument should also have a default of `None` in each case. Please see [this section](https://github.com/unifyai/ivy/blob/b467afb70ead6ea2a826910a22654c16f9a31e8a/docs/partial_source/deep_dive/2_superset_behaviour.rst#balancing-generalization-with-efficiency) of the Deep Dive for a discussion on this :)

2022-09-19 09:22 UTC, Ishticode commented
Could you take a special look at torch backend. It doesn't accept None for either beta or threshold so in case these args are passed the default setting are used.

2022-09-19 14:57 UTC, djl11 requested changes
I reduced the number of lines in the torch implementation, but otherwise is good to merge!

2022-09-20 13:34 UTC, Ishticode commented on ivy/functional/backends/torch/activations.py
> +    if beta is None and threshold is None:
very cool @djl11 🙂.

2022-09-20 13:48 UTC, merged