Add dropout for tensorflow frontend
unifyai/ivy pull request #4476
Opened 2022-09-15 05:17 UTC by Change-m

Close #4475

2022-09-16 05:08 UTC, VedPatwardhan commented
I'll close this PR as discussed. Thanks 🙂

2022-09-20 04:18 UTC, VedPatwardhan requested changes
Hi @Change-m, just requested some changes, feel free to re-request my review once you're done with them. Thanks 🙂

2022-09-20 04:18 UTC, VedPatwardhan commented on ivy/functional/frontends/tensorflow/nn.py
> +    return ivy.dropout(x, rate, noise_shape, seed)
The parameters of the `ivy.dropout` function don't match with the actual parameters accepted by the function, please check the `dropout` function inside `functional/ivy/layers.py` and pass the parameters accordingly. Firstly, the parameter names of the `ivy.dropout` function may not always match with the parameters of the frontend function, but in such cases you can just refer the docs of the tensorflow dropout function and the docstring of the `ivy.dropout` function and understand which parameters have the same meaning. Finally, when you pass the parameters, there are some that are positional-only (the ones before `/`) and some that are keyword-only (the ones after `*`) so please pass them accordingly.

2022-09-24 13:13 UTC, Change-m commented
Hi @VedPatwardhan, I do the suggested changes, Please review.

2022-09-27 09:26 UTC, VedPatwardhan requested changes
Hi @Change-m, there are a few syntax errors in your PR, for e.g. numpy is being used but isn't imported, etc. Also, your PR is 532 commits behind master as the helpers have changed a lot, please pull the latest code on master, run the test for your function and resolve all syntax errors which occur as a result. 
Feel free to re-request my review once you're done with the same, also please use the right pane to request a review so that I get notified immediately about it. 
Let me know if you have any questions. Thanks 🙂

2022-09-30 13:56 UTC, VedPatwardhan approved these changes
lgtm!

2022-09-30 13:56 UTC, merged