slogdet of ivy functional linear algebra reformatted with examples in docstring
unifyai/ivy pull request #4507
Opened 2022-09-15 11:46 UTC by ash-ishh

2022-09-15 11:47 UTC, ash-ishh commented
Close #4450

2022-09-15 11:52 UTC, ash-ishh commented
TODO:

1 - Container representation issue
In ivy/container/base.py for named tuple follwing condition is executed

```
                elif (
                    isinstance(v, (list, tuple))
                    and v
                    and (self._ivy.is_native_array(v[0]) or isinstance(v[0], ivy.Array))
                ):
                    rep = (
                        "list[{}]".format(len(v)),
                        type(v[0]),
                        "shape=",
                        list(v[0].shape),
                    )
```

Which results in output with just len, type and shape
```
    {
        a: (list[2], <class ivy.array.array.Array> shape=[3])
    }
```
Should we print elements as well? will it affect existing desing decision?

In case of slogdet it will look something like this
```
    {
        a: ('slogdet(sign=ivy.array(-1.), logabsdet=ivy.array(0.69314718))', list[2], <class ivy.array.array.Array> shape=[3])
    }
```
2 - Type hint issue

In the backend implementations of slogdet `collections namedtuple` is used for return but in other parts of code `typing NamedTuple` is used
Should be fix one class for return? if yes which one
Difference between them: https://stackoverflow.com/questions/50766461/whats-the-difference-between-namedtuple-and-namedtuple

2022-09-15 16:21 UTC, ash-ishh commented
add_reformatting_checklist_linalg

2022-09-15 16:26 UTC, ash-ishh commented
add_reformatting_checklist_linear_algebra

2022-09-15 18:37 UTC, ash-ishh commented
add_reformatting_checklist_linear_algebra

2022-09-16 07:42 UTC, ash-ishh commented
Hi @abdrahmandiab @djl11 :wave: need your views on how should I proceed with the above 3 constraints

1 - Should I update container repr for a more descriptive namedtuple as part of this pr? or should I create the separate issue and let the example be in the current format only
2 - Should I go ahead with `collections namedtuple` for the return type hint?
3 - Should I remove optional `out` from ivy slogdet since backends are returning namedtuples?

Thanks.

2022-09-19 12:38 UTC, ash-ishh commented
add_reformatting_checklist_linear_algebra

2022-09-22 12:26 UTC, abdrahmandiab commented
Hi @ash-ishh, I am going to start the review process for your PR now, but for future reference, please do request a review when your work is ready for evaluation. 😄 

Thanks!

2022-09-24 13:31 UTC, abdrahmandiab commented
Hi @ash-ishh, 
I've asked Daniel about your queries regarding the `namedtuple` stuff and either me or him will be returning to you with a response on that shortly!

In the meantime, I would recommend checking out the Python Array API page on [`slogdet`](https://data-apis.org/array-api/2021.12/extensions/generated/signatures.linalg.slogdet.html?highlight=slogdet). Feel free to follow the type hints here as this is the standard that Ivy adheres to. Additionally, you can checkout this page for [`torch.slogdet`](https://pytorch.org/docs/stable/generated/torch.linalg.slogdet.html#torch.linalg.slogdet) for an example that implements the `out` argument.
* Note: it appears torch has a specialized dtype `torch.return_types.linalg_slogdet` which is returned when you make a call to slogdet.

Also, while playing around, I've found that the out argument doesn't actually work even if you pass in a correctly named `namedtuple`, but that's something we'll be looking at internally so no worries there! 😅

Examples:
```
>>> from collections import namedtuple
>>> x = ivy.array([[1,2],[3,4]])
>>> n_t = namedtuple('slogdet',['sign','logabsdet'])
>>> z = n_t(ivy.array(0.),ivy.array(0.))
>>> z
slogdet(sign=ivy.array(0.), logabsdet=ivy.array(0.))
>>> ivy.slogdet(x,out=z)
slogdet(sign=ivy.array(-1.), logabsdet=ivy.array(0.69314718))
>>> z
slogdet(sign=ivy.array(0.), logabsdet=ivy.array(0.))
```
*and*
```
>>> x = ivy.array([[1,2],[3,4]])
>>> y = ivy.slogdet([[0.,0.],[0.,0.]])
>>> y
slogdet(sign=ivy.array(0.), logabsdet=ivy.array(-inf))
>>> ivy.slogdet(x,out=y)
slogdet(sign=ivy.array(-1.), logabsdet=ivy.array(0.69314718))
>>> y
slogdet(sign=ivy.array(0.), logabsdet=ivy.array(-inf))
```

2022-09-24 21:29 UTC, djl11 commented
> Hi @abdrahmandiab @djl11 wave need your views on how should I proceed with the above 3 constraints
> 
> 1 - Should I update container repr for a more descriptive namedtuple as part of this pr? or should I create the separate issue and let the example be in the current format only 2 - Should I go ahead with `collections namedtuple` for the return type hint? 3 - Should I remove optional `out` from ivy slogdet since backends are returning namedtuples?
> 
> Thanks.

1. Don't worry about changing `ivy.Container.__repr__` as part of this PR, but thank you so much for pointing this out, we will incorporate your suggestions (or a similar variant) soon!
2. actually, changing all of these to typing.NamedTuple would be great, the Array API Standard [does not specify](https://github.com/data-apis/array-api/blob/eba54b35b040bb08359fdca7aaeb0340ecb5c87c/spec/API_specification/array_api/linalg.py#L347) one vs the other.
3. Yes please, in Ivy we only intend to support `out` for array returns, and so this does not apply for this function. Again, thanks for pointing this out!

2022-09-24 21:29 UTC, djl11 commented
Once these changes are made, feel free to review + merge @abdrahmandiab, thanks both!

2022-09-26 09:15 UTC, ash-ishh commented
Thank you @djl11 @abdrahmandiab 

PR is ready for review.

2022-09-29 07:16 UTC, ash-ishh commented
Hi @abdrahmandiab just a nudge for review and merge.

2022-09-30 00:29 UTC, abdrahmandiab commented
Hi @ash-ishh, sorry it took me a bit to review! 😅

There are actually a few failing docstring examples, could you please attempt to fix them, and of course if you need any help I'll be here! 

To checkout these failures, you can run the test_docstrings locally and then search for `slogdet` in the output logs and failures arising from it. Alternatively, at the bottom of this "Conversation" page on the PR, you will find our github check actions. You can check for docstrings failures by clicking on "Details" next to the "test-docstrings / run-docstring-tests (pull_request)" check. 
![image](https://user-images.githubusercontent.com/37490334/193164554-595c3f74-5386-4e07-839b-a98f28102c53.png)

After this, please navigate to the "Run Docstring Tests" job and search the logs for `slogdet`, below is an example! 😃
![image](https://user-images.githubusercontent.com/37490334/193164784-862b75fa-fab8-4e6e-be8c-adc4ad5abdbd.png)


Thanks! 😊

2022-09-30 08:27 UTC, ash-ishh commented
@abdrahmandiab All the slogdet docstring tests are passing now.

2022-10-03 12:24 UTC, abdrahmandiab requested changes
Hi @ash-ishh, sorry for the late reply, I had wrote this review a few days ago and forgot to submit it haha 😅 

Thanks for fixing the tests, and after these small changes hopefully we can merge right away!
Great job!

2022-10-03 12:28 UTC, abdrahmandiab commented on ivy/container/linear_algebra.py
> +        >>> x = ivy.Container(a=ivy.array([[1.0, 2.0], \
could you please add a `b` element here as well? 😃

2022-10-03 13:10 UTC, ash-ishh commented on ivy/functional/ivy/linear_algebra.py
> +    With :code:`ivy.Array` instance methods:
Instance methods of slogdet seems valid for both array and container, any specific reason why they are not necessary?

2022-10-03 17:20 UTC, abdrahmandiab requested changes

2022-10-03 17:20 UTC, abdrahmandiab commented on ivy/functional/ivy/linear_algebra.py
> +    With :code:`ivy.Array` instance methods:
they are correct and all, but they are already included in the relevant function be it instance or static, and therefore adding them here is just redundant and leads to unnecessary cluttering 😅

2022-10-03 17:20 UTC, abdrahmandiab commented on ivy/container/linear_algebra.py
> +        >>> x = ivy.Container(a=ivy.array([[1.0, 2.0], \
@ash-ishh this comment was marked as resolved even though it was not addressed 😅

2022-10-03 17:27 UTC, ash-ishh commented on ivy/functional/ivy/linear_algebra.py
> +    With :code:`ivy.Array` instance methods:
Makes sense, I have removed them.

2022-10-04 02:46 UTC, abdrahmandiab commented
Hi @ash-ishh, everything looks good to me! :)

Will be merging soon! Thanks for your work! 🚀

2022-10-04 02:46 UTC, merged