reformat ivy.inv #4280
unifyai/ivy pull request #4537
Opened 2022-09-16 10:16 UTC by lunava

2022-09-16 10:17 UTC, lunava commented
add_reformatting_checklist_lin_alg

2022-09-16 10:56 UTC, lunava commented
add_reformatting_checklist_linear_algebra

2022-09-16 10:59 UTC, lunava commented
add_reformatting_checklist_linear_algebra

2022-09-16 11:08 UTC, lunava commented
add_reformatting_checklist_linear_algebra

2022-09-16 12:21 UTC, Daniel4078 requested changes
Hello, I have a look at the CI tests and currently found one significant error for you to fix (details in the comment below). Now lets wait for the automatic check-list to be added and then we can see if there is anything else you need to do. Thank you!

2022-09-16 12:21 UTC, Daniel4078 commented on ivy/functional/ivy/linear_algebra.py
> +
you have an error here:
ivy/functional/ivy/linear_algebra.py:621 in public function `inv`:
D412: No blank lines allowed between a section header and its content ('Examples')

2022-09-16 19:59 UTC, lunava commented
add_reformatting_checklist_linear_algebra

2022-09-16 23:28 UTC, lunava commented
add_reformatting_checklist_linear_algebra

2022-09-17 08:45 UTC, lunava commented
add_reformatting_checklist_lin_alg

2022-09-17 08:47 UTC, lunava commented
add_reformatting_checklist_linearalgebra

2022-09-17 08:48 UTC, lunava commented
add_reformatting_checklist_linear_algebra

2022-09-17 14:45 UTC, Daniel4078 commented
Now with the checklist up and ready, you can edit the status accordingly. the docstring test does not pass currently and I hope the checklist can help you figure out why.

2022-09-21 08:05 UTC, lunava commented
Hi, @Daniel4078 can you review my commits? I added the docstring for the inv function.

2022-09-21 12:23 UTC, Daniel4078 approved these changes
It seems like there is nothing wrong with your changes. Good work.

2022-09-21 12:24 UTC, merged