value_is_nan #4600
unifyai/ivy pull request #4601
Opened 2022-09-18 16:59 UTC by usamafaisal98

- [ ] #4600

2022-09-18 17:26 UTC, usamafaisal98 commented
@juliagsy could you review please?

2022-09-19 05:17 UTC, juliagsy requested changes
Hey there! The changes so far looks good! There's just a bit more do check, could you also add some examples to the equivalent instance methods in `array/general.py` and `container/general.py`? Please request my review again once you're done, thank you!

2022-09-19 06:54 UTC, usamafaisal98 commented
Hi @juliagsy Could you review again please? Thanks!

2022-09-19 07:07 UTC, juliagsy requested changes
Hey! Thanks for the changes! Just some small fix and test resolving left for a merge! As usual, please request my review once again when you're done! Thanks!

2022-09-19 07:07 UTC, juliagsy commented on ivy/functional/ivy/general.py
> +    >>> y = x.value_is_nan()
sorry, I just realised, this should be `ivy.value_is_nan(x)` to showcase functional method

2022-09-19 07:07 UTC, juliagsy commented on ivy/functional/ivy/general.py
> +    With one :code:`ivy.Container` static method:
the examples starting from here are not needed as they are a repeat of the ones in `container/general.py`

2022-09-19 07:07 UTC, juliagsy commented on ivy/container/general.py
> +            a: False,
somehow the generated strings for bool representation is lowercase (i.e., `false`, `true`), which currently causes doctoring test failures, would you mind changing the container representation returns to be lowercase? only the examples here, thanks a lot!

2022-09-19 07:15 UTC, usamafaisal98 commented
@juliagsy could you review again please? thanks!

2022-09-19 09:33 UTC, juliagsy commented
Thanks for contributing!

2022-09-19 09:33 UTC, merged