added matrix_power function
unifyai/ivy pull request #4763
Opened 2022-09-21 14:14 UTC by ndurumo254

hello, have added a matrix_power function  in the front end jax.

2022-09-21 14:47 UTC, ndurumo254 commented
hello, once i try to run the test , am getting the era that i skipped the process.  how am i supposed to carry the test?

2022-09-21 17:37 UTC, jkeane508 requested changes
Hi I think you should refer to the [docs](https://lets-unify.ai/ivy/deep_dive/16_ivy_frontends.html) to see how to do the correct frontend implementations

I have highlighted the changes necessary :)

Can you also reference the issue you created for this task so I can link it to this PR.

2022-09-21 17:37 UTC, jkeane508 commented on ivy/functional/frontends/jax/lax/linalg.py
> +from brainpy.math.numpy_ops import _remove_jaxarray
same here

2022-09-21 17:37 UTC, jkeane508 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3.10" project-jdk-type="Python SDK" />
All changes in this file need to be undone

2022-09-22 14:49 UTC, ndurumo254 commented
am trying to figure out how I can reference the issue after I created it. would someone help me?

2022-09-23 16:31 UTC, jkeane508 requested changes
Hey,

You still need to make the changes I outlined in the previous review :)

Moreover, there seems to be some lint failures, you can import a pre commit hook here which will format code automatically before every commit [here](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit)

2022-09-25 17:37 UTC, ndurumo254 reviewed
am getting challenges with pytest library. how can i use it. i have installed it yet i get error that the module is not found

2022-09-25 18:00 UTC, ndurumo254 reviewed
am getting challenges with pytest library. how can i use it. i have installed it yet i get error that the module is not found

2022-09-26 13:39 UTC, jkeane508 commented
Hi,

2022-09-26 13:42 UTC, jkeane508 requested changes
Hi,

It seems that you have made changes to a lot of files on your fork. Unfortunately for PRs we only accept changes to files that are relevant to the task you are working on. Before I can merge this you need to remove changes to files that are not relevant :)

2022-09-29 16:14 UTC, closed without merging