Added TensorFlow Linalg eigvals function and tests.
unifyai/ivy pull request #4795
Opened 2022-09-22 10:49 UTC by Harshalzzzzzzz

#4794

2022-09-22 11:05 UTC, Harshalzzzzzzz commented
@sreegandh804 Can you please review this PR. I will update the PR with suggested changes and inputs asap.
Thanks

2022-10-03 09:01 UTC, zaeemansari70 requested changes
Hey! 
First of all thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Just requested a change and left a comment on it which needs to be addressed before we can merge your PR! 🙂
Thanks!

2022-10-03 17:05 UTC, zaeemansari70 commented on ivy/functional/frontends/tensorflow/linalg.py
> +    return ivy.eigvals(tensor)
This function is not present in `Ivy`. It is present in our Extended API task.
You can work on it to implement it.
Thanks!
https://github.com/unifyai/ivy/issues/3856

2022-11-21 11:15 UTC, fspyridakos commented
Due to lack of activity, I will be closing this PR.

2022-11-21 11:15 UTC, closed without merging