Erick
unifyai/ivy pull request #4805
Opened 2022-09-22 14:12 UTC by ndurumo254

updated matrix_power function

2022-09-22 14:26 UTC, ndurumo254 commented
updated matrix_power

2022-09-23 08:56 UTC, simonetgordon requested changes

2022-09-23 08:56 UTC, simonetgordon commented on ivy/functional/frontends/jax/lax/linalg.py
> +
Too many blank lines. There should just be 2.

2022-09-23 08:56 UTC, simonetgordon commented on ivy/functional/frontends/jax/lax/linalg.py
> +def matrix_power(m: Union[ivy.Array, ivy.NativeArray],
There should not be any type hints in the frontend functions. Delete the type-hint related imports too.

2022-09-23 08:56 UTC, simonetgordon commented on ivy/functional/frontends/jax/lax/linalg.py
> +                 n: int,
Change first two function args to `(a, n, `

2022-09-23 08:57 UTC, simonetgordon commented
Thanks for the contribution! You can check out some of the review comments. We'll also need you to delete changes in the .idea files before merging.

2022-09-25 06:29 UTC, closed without merging