add softmax function tensorflow frontend
unifyai/ivy pull request #4840
Opened 2022-09-23 13:45 UTC by zuruoke

2022-09-23 15:09 UTC, zuruoke commented
https://github.com/unifyai/ivy/issues/4819

2022-09-23 16:03 UTC, jkeane508 requested changes

2022-09-23 16:03 UTC, jkeane508 commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +        x = ivy.astype(x, "float64")
I think that we should cast to float, but not necessarily float64 in all cases. We should maybe look at casting to the nearest reasonable float dtype instead

2022-09-23 16:06 UTC, jkeane508 requested changes
The test for Softmax is also failing [here](https://github.com/unifyai/ivy/actions/runs/3113328790/jobs/5047820850)

2022-09-26 13:37 UTC, jkeane508 commented
Feel free to request a review form me whenever you have tests passing :)

2022-09-28 16:35 UTC, jkeane508 requested changes
It seems to be from the testing that there are failures when the dims argument and the number of dims in the input for the function don't line up. I would suggest looking at the mathematics for softmax and creating a helper function that doesn't generate invalid data :)

2022-11-11 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-18 06:25 UTC, closed without merging

2022-11-18 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.