torch frontend comparison ops
unifyai/ivy pull request #5031
Opened 2022-09-28 12:18 UTC by AnnaTz

2022-09-28 12:19 UTC, AnnaTz commented
Closes #5030

2022-09-29 11:16 UTC, simonetgordon requested changes

2022-09-29 11:16 UTC, simonetgordon commented on ivy_tests/test_ivy/test_frontends/test_torch/test_comparison_ops.py
> +    input = np.asarray(input, dtype=input_dtype)
Error with input data dtype seemingly, could from an assignment issue in line 792.
```
>       input = np.asarray(input, dtype=input_dtype)
E       TypeError: Field elements must be 2- or 3-tuples, got ''float64''
```

2022-09-29 11:16 UTC, simonetgordon commented on ivy_tests/test_ivy/test_frontends/test_torch/test_comparison_ops.py
> +def test_torch_maximum(
Seems to be passing just fine, nice!

2022-09-29 17:16 UTC, AnnaTz commented
Close #5029

2022-10-02 11:23 UTC, simonetgordon approved these changes
lgtm!

2022-10-02 11:24 UTC, merged