Jax.slogdet Frontend
unifyai/ivy pull request #5060
Opened 2022-09-29 11:57 UTC by nassimberrada

2022-09-29 14:31 UTC, nassimberrada commented
**Error**: Field elements must be 2- or 3-tuples
>           a=np.asarray(x, dtype=input_dtype)

2022-10-03 14:11 UTC, Ishticode requested changes
Mostly fine perhaps. According to [this](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.slogdet.html) There is an additional argument of method. Even if you don't make use of it in the call. This is just to ensure no arg mistmach between native jax and ivy's frontend jax. I Could explain this if it doesn't make sense. But essentially the frontend APIs need to have the same arguments as their corresponding frameworks.

2022-10-11 19:20 UTC, Ishticode requested changes
The composite will be perhaps better to write it like so

```python
@st.composite
def square_shape(draw):
    shape = st.integers(min_value=2, max_value=20)
    return (shape, shape)
```

OR  maybe we don't even need a composite for this
we can just add shape like this below

```python
shape = st.tuples(st.shared(st.integers(1,20), key="sq"), st.shared(st.integers(1,20), key="sq"))
```
Feel free to let me know if you want me to explain this.

2022-10-11 19:25 UTC, Ishticode requested changes
mthod in given and test parameters isn't required. but it should be passed to test_function as None as you already hv done. Let me know if this raises any issues.

2022-10-11 19:25 UTC, Ishticode commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_linalg.py
> +    method=st.none(),
we dont really require this to be generated as it is passed as `None` manually.

2022-10-11 19:25 UTC, Ishticode commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_linalg.py
> +    method,
can remove this

2022-10-11 19:44 UTC, nassimberrada commented
Now it's my turn to have long testing times, even with tights input ranges that's weird. Could you try running this on your side ?

2022-10-11 20:51 UTC, nassimberrada commented
The tests pass under the condition that i remove the method argument from the testing altogether, even by just setting methods to None in the test_frontend_function is fails. I pushed a commit without the method argument in the tests

2022-10-11 21:35 UTC, Ishticode approved these changes
Yh I should have simply just said remove the method arg altogether. It is present in the frontend function just to match the api and avoid throwing errors (arg mismatch) when it was passed in the way it would in native `jnp`. It won't effect the output. 

Looks great. Will get this merged. Thanks Nassim.

2022-10-11 21:39 UTC, merged