add_sort_ numpy_Frontend#3577
unifyai/ivy pull request #5067
Opened 2022-09-29 13:03 UTC by Hellenn07

2022-09-29 19:22 UTC, ogbanugot requested changes

2022-09-29 19:22 UTC, ogbanugot commented on ivy/functional/backends/numpy/creation.py
> + master
Hi @Hellenn07, can you please take a look at these lines, it appears the merge from master left some text that shouldn't be in the code. Kindly fix these and request for a review once you are done thanks! 🙂

2022-09-29 19:22 UTC, ogbanugot commented on ivy/functional/backends/tensorflow/creation.py
> +master
here too

2022-09-29 19:22 UTC, ogbanugot commented on ivy/functional/backends/torch/creation.py
> +master
same here

2022-09-29 19:22 UTC, ogbanugot commented on ivy/functional/backends/torch/elementwise.py
> +    # print("len: ", len(x))
Also, can you remove the commented `print` statements.

2022-09-29 19:22 UTC, ogbanugot commented on ivy/functional/backends/torch/elementwise.py
> + numpy_sort
see here again

2022-09-29 19:22 UTC, ogbanugot commented on ivy/functional/backends/torch/elementwise.py
> + master
here as well

2022-09-30 07:05 UTC, Hellenn07 commented
Hi,
Thank you for the detailed review. I have resolved the issues. Could you please check it out.
Regards.

2022-09-30 09:18 UTC, ogbanugot requested changes

2022-09-30 09:18 UTC, ogbanugot commented on ivy/functional/backends/numpy/creation.py
> + numpy_sort
Hi! There seem to still be a few missed lines with unwanted text. Please kindly remove these lines and commit the changes. Thanks!

2022-09-30 09:18 UTC, ogbanugot commented on ivy/functional/backends/numpy/creation.py
> + master
see here

2022-09-30 09:18 UTC, ogbanugot commented on ivy/functional/backends/torch/creation.py
> +numpy_sort
here

2022-09-30 09:19 UTC, ogbanugot commented
Also, can you please link the corresponding issue by adding a comment ‘Close #Issue_number’, as explained [here](https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues)”

2022-09-30 09:24 UTC, ogbanugot commented
Also, can you please write tests for the functions you have added, kindly use the docs on tests [here](https://lets-unify.ai/ivy/deep_dive/15_ivy_tests.html) and [here](https://lets-unify.ai/ivy/deep_dive/17_ivy_frontends_tests.html). Thanks for your effort so far!

2022-09-30 15:29 UTC, Hellenn07 commented
#5067

2022-09-30 17:05 UTC, Hellenn07 commented
#3577

2022-10-01 09:03 UTC, Hellenn07 commented
Hey, I have committed the changes as requested. I directly commented on the PR but I can't see it linked to my PR yet. I can see we are getting somewhere. I highly appreciate your help.

2022-10-03 09:38 UTC, ogbanugot requested changes
Hey! @Hellenn07 sorry for the late response. I'm looking through and there are still issues with the pr with respect to the merge that you did. Some lines of code have been removed and some unwanted lines of code are in the wrong places. If you are unable to fix these, I would suggest that you close this pr and reopen another one that is much cleaner than this one. 
First you should update your fork's master branch by using the `Sync fork` option. 
Next create a new branch from `master` you can use the command `git checkout -b branch-name`. 
Add your contribution to that new branch, commit them and push the changes. You can then open a pr from that branch and request a review from me. I think this would be the fastest approach to take. Otherwise, if you wish to continue working on this branch you should take some time to go through the files and make the appropriate changes.

2022-10-03 15:58 UTC, closed without merging