#5130 Uint16
unifyai/ivy pull request #5133
Opened 2022-10-01 09:19 UTC by trihernandez

- [ ] #5130

2022-10-06 11:06 UTC, zaeemansari70 requested changes
Hey! 
First of all thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Just requested a few changes and left comments on them which needs to be addressed before we can merge your PR! 🙂

1. It is giving an error for torch `Cannot convert to PyTorch dtype. uint16 is not supported by PyTorch.` 
2. There are a bunch of lint errors I've pointed out, they need to be fixed as well.
3. You've also committed a change in the conftest file please uncommit that change too.

Thanks!🙂

2022-10-06 11:06 UTC, zaeemansari70 commented on ivy/functional/frontends/jax/numpy/name_space_functions.py
> +    return ret.astype(dtype)
There should be a new line here.

2022-10-06 11:06 UTC, zaeemansari70 commented on ivy_tests/conftest.py
> +                break
Here too, No change should be there in the `conftest.py` file.

2022-10-06 11:51 UTC, trihernandez commented
I did the last two.  What would be the best way to interpret uint16 in pytorch (such as using an int32 datatype or two uint8 datatypes), or convert a value in pytorch to uint16 (even if this new data value is not using a pytorch datatype)?  Would I take the literal byte data of the uint16 and express that as the byte data for a signed 16-bit int?

2022-10-07 08:43 UTC, trihernandez commented
I did the last two. What would be the best way to interpret uint16 in pytorch (such as using an int32 datatype or two uint8 datatypes), or convert a value in pytorch to uint16 (even if this new data value is not using a pytorch datatype)? Would I take the literal byte data of the uint16 and express that as the byte data for a signed 16-bit int? How would I add a separate case for pytorch compared to the other data types?

When I ran the test cases on codespaces, my part of the code passed, so I do not know why my code is failing the test with this error now, especially since I worked on the jax frontend.

I read something that might be relevant to excluding pytorch here (https://lets-unify.ai/ivy/deep_dive/6_data_types.html#supported-and-unsupported-data-types), but it seems to be backend-related to it.

2022-10-07 13:14 UTC, zaeemansari70 requested changes
Just one more small change before we can merge your PR 😊 

1. Please un-commit the `ivy_array.pickle` file.

Also, no need to worry about the dtype issue for Torch, it will surely be handled by the `Ivy` team in the future.
Thanks! 😊

2022-10-07 21:45 UTC, trihernandez commented
Deleted the pickle file.  You should be good to commit!

2022-10-10 08:06 UTC, zaeemansari70 approved these changes
Lgtm!

2022-10-10 08:07 UTC, merged