Modity the linspace function of tensorflow backend for endpoint argument
unifyai/ivy pull request #5139
Opened 2022-10-01 11:26 UTC by kimbring2

Hello,

There is an error in processing the endpoint argument in the linspace function of the Tensorflow backend.
It can only deal with a specific array shape. I change it to a more general form.

Thank you

2022-10-03 09:48 UTC, ogbanugot requested changes

2022-10-03 09:48 UTC, ogbanugot commented on .idea/vcs.xml
> +    <mapping directory="$PROJECT_DIR$/ivy_tests/test_array_api" vcs="Git" />
Hey! I don't think you should commit changes in this file. Can you remove this from the commit.

2022-10-03 09:49 UTC, ogbanugot commented
Hey! Great work. Can you please add the appropriate labels to the pr, so that the tests can run.

2022-10-18 06:26 UTC, closed without merging

2022-10-18 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.