ivy.collapse_repeated
unifyai/ivy pull request #5151
Opened 2022-10-02 05:50 UTC by Change-m

2022-10-02 05:55 UTC, Change-m commented
Close #5152

2022-10-05 08:48 UTC, Change-m commented
Collapse_repeated function is belong to Neural Network which is wildly used in Tensorflow, implemented compositionally that's why it is in extension.py file.

2022-10-06 10:08 UTC, zaeemansari70 requested changes
Your PR looks amazing ✨!
Just requested a few changes and left comments on them which needs to be addressed before we can merge your PR! 🙂

You have to come up with a logic to implement this function using ivy functions as implemented here, as only tensorflow has it and therefore it is to be implemented compositionally, https://lets-unify.ai/ivy/deep_dive/1_function_types.html#compositional-functions 🙂

Do let me know if you have any questions!
Thanks!

2022-10-06 10:08 UTC, zaeemansari70 commented on ivy/functional/ivy/extensions.py
> +def collapse_repeated(
Only tensorflow has this function, it has to be implemented compositionally using other Ivy functions.

2022-11-27 13:48 UTC, closed without merging