hann_window extension
unifyai/ivy pull request #5183
Opened 2022-10-03 09:06 UTC by nassimberrada

2022-10-09 18:19 UTC, Ishticode requested changes
Very good PR.

Some comments were add in certain places. Additionally, as the window_length is a type hint, it maybe appropriate to generate using st.integers() or helper.ints functions and dtype can be separately generated by helper.get_dtype I think. Let me know if any of these doesn't make sense or If i am missing something. Thanks Nassim and sorry for the delay in this review. 

There should be no array method as you have correctly left out. 
For Container methods I need to check few things so leave that out for now.If test has any issues with the decorator @handle_nestable  you can remove it.

2022-10-09 18:19 UTC, Ishticode commented on ivy/functional/backends/torch/statistical.py
> +def hann_window(
It seems you have implemented for torch already in statistical so can safely remove this

2022-10-10 18:52 UTC, Ishticode requested changes
So yh. We should add container instance and static method. leaving @handle_nestable on.
Could you ensure lint is fixed and the tests are passing. Mostly seems good here.

2022-10-10 20:04 UTC, Ishticode requested changes
near ready to merge. Just minor few changes

2022-10-10 20:04 UTC, Ishticode commented on ivy/functional/backends/torch/extensions.py
> +hann_window.unsupported_dtypes = ("int32", "int64")
It seems this part about unsupported dtypes is not required. Tests pass for me. Not sure if you had something on mind here.

2022-10-10 20:04 UTC, Ishticode commented on ivy/container/extensions.py
> +        >>> ivy.hann_window(x)
should be an instance method call here.   about the square brackets in the result printed below (and above), not sure where they came from... ususally container is printed with just the curly brackets

2022-10-10 20:04 UTC, Ishticode commented on ivy/container/extensions.py
> +        >>> ivy.hann_window(x)
i think this should be `ivy.Container.static_hann`

2022-10-10 20:04 UTC, Ishticode commented on ivy/functional/ivy/extensions.py
> +
no gap here. Sorry for being picky. The numpy style docstring test gets angry otherwise.

2022-10-10 20:12 UTC, nassimberrada commented
I'm gonna have to thank you for your patience, i keep making the same typos, but i'll learn eventually...hopefully 😀

2022-10-10 20:26 UTC, Ishticode approved these changes
Thanks @nassimberrada. Should be merged now.✌️

2022-10-10 20:27 UTC, merged

2022-10-11 09:24 UTC, nassimberrada commented
close #5541