ivy.avg_pool1d
unifyai/ivy pull request #5266
Opened 2022-10-04 20:45 UTC by Change-m

Close #5174

2022-10-05 08:51 UTC, Change-m commented
avg_pool1d function is belong to Neural Network which is wildly used in Tensorflow, implemented as mixed function that's why it is in extension.py file.

2022-10-05 13:23 UTC, zaeemansari70 requested changes
Your PR looks amazing ✨!
Just requested a few changes and left comments on them which needs to be addressed before we can merge your PR! 🙂
Thanks!

2022-10-05 13:23 UTC, zaeemansari70 commented on ivy/functional/backends/numpy/extensions.py
> +    return np.avg_pool1d(x, ksize, strides, padding, data_format).astype(x.dtype)
Same for numpy backend. no function such as `avg_pool1d()`.
This also needs to be implemented compositionally.

2022-10-05 13:23 UTC, zaeemansari70 commented on ivy/functional/backends/jax/extensions.py
> +    return jnp.avg_pool1d(x, ksize, strides, padding, data_format, dtype=dtype)
There doesn't seem to be an `avg_pool1d()` in the jax backend.
This needs to be implemented compositionally.

2022-10-06 10:17 UTC, zaeemansari70 commented
Closing this as discussed 🙂

2022-10-06 10:17 UTC, closed without merging