Fixes task #5245 to add ReLU activation frontend tensorflow and merged latest commit histories
unifyai/ivy pull request #5338
Opened 2022-10-06 14:07 UTC by suvadityamuk

#5245

2022-10-08 17:50 UTC, suvadityamuk commented
Hi, @JonathanYang-yzh @jkeane508 Could y'all please check this one out? Thanks!

2022-10-10 17:48 UTC, jkeane508 requested changes

2022-10-10 17:48 UTC, jkeane508 commented on ivy/functional/frontends/tensorflow/activations.py
> +    x = ivy.clip(x, 0.0, ivy.inf)
I've just checked the docs and there is actually an `ivy.relu()` function in the [API](https://lets-unify.ai/ivy/functional/ivy/activations/relu/relu_functional.html?highlight=relu#ivy-relu), you can just use it instead :)

2022-10-10 17:50 UTC, jkeane508 requested changes
There are also some lint errors with this file, please install a [pre-commit hook](https://lets-unify.ai/ivy/contributing/0_setting_up.html#pre-commit) to fix these before pushing to your branch :)

2022-10-11 03:04 UTC, suvadityamuk commented
Hi, I've corrected the file and set up the linting as well. Please check it now

2022-10-11 16:52 UTC, jkeane508 approved these changes
LGTM!

2022-10-11 17:01 UTC, merged

2022-10-11 18:23 UTC, suvadityamuk commented
Awesome, thanks!