Superset behaviours of matmul
unifyai/ivy pull request #5385
Opened 2022-10-07 10:45 UTC by JLU-Neal

2022-10-07 11:28 UTC, Ishticode requested changes
This looks right 🙂 but could you also add the transpose parameters in the `test_matmul`

2022-10-14 15:52 UTC, JLU-Neal commented
Hey @Ishticode !
I did not intend to ask you to review after the first commit but ivy-seed automatically requested you to review hahaha!
Please review again :D 
I have added the transpose parameters and fixed some bugs! Thanks!

2022-10-21 11:32 UTC, Ishticode commented on ivy/functional/backends/numpy/linear_algebra.py
>          ret = np.array(ret)
the second `ret` can be undefined in case both x1 and x2 were were 1D.

2022-10-25 15:17 UTC, JLU-Neal commented
@Ishticode Hey I want to push the latest commits but seems I have no more write access now! Could you give me the write access for a little while so that I could wrap up this?

2022-10-31 17:24 UTC, Ishticode commented
> @Ishticode Hey I want to push the latest commits but seems I have no more write access now! Could you give me the write access for a little while so that I could wrap up this?



> @Ishticode Hey I want to push the latest commits but seems I have no more write access now! Could you give me the write access for a little while so that I could wrap up this?

Hmm I m not sure. I will ask @VedPatwardhan and see what we can do.

2022-11-04 08:35 UTC, Ishticode commented
Hi. I've been told the write permission is strictly for the members currently on team. If its not too much to ask, please copy over the content to a new file from the branch of your own fork. This will allow you to edit on the go and will also save you the trouble of resolving conflicts above. Sorry for inconvenience and thanks for your patience.

2022-11-12 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-19 06:25 UTC, closed without merging

2022-11-19 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2022-11-20 09:15 UTC, JLU-Neal commented
@Ishticode Hey, sorry about the late response. I tried to do as you said but when I tried to fix the merge conflict, it seems that the superset behaviour of the matmul has already been implemented. Let me know if there is anything else I can help with.