argmax updated(#117)
unifyai/ivy pull request #541
Opened 2022-03-14 19:24 UTC by 7wikd

Left out some of the parameters. Updated function to suit the same.

2022-03-14 20:17 UTC, Ishticode requested changes
Hi @7wikd. Seems good. Mostly done in previous PR#117. 
Could u just update the docstring as in the contributing guide. : )

2022-03-15 07:40 UTC, Ishticode approved these changes

2022-03-15 08:38 UTC, djl11 approved these changes
thanks!

2022-03-15 08:38 UTC, merged

2022-03-15 08:39 UTC, djl11 commented
Thanks!