fix matrix norm superset behaviour bug
unifyai/ivy pull request #5420
Opened 2022-10-07 23:51 UTC by randomstate42

fixes #5402

2022-10-08 14:54 UTC, randomstate42 commented
@sherry30 ready for review

2022-10-10 16:47 UTC, zaeemansari70 requested changes
Hey! 
First of all thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Just requested a few changes and left comments on them which needs to be addressed before we can merge your PR! 🙂

Mostly, the type-hints also have been fixed already what you can do is:

1. Add what is required to the `axis` argument in the type-hint only, I've also mentioned what to add and where to.

That's all, you can revert all other changes. 🙂
Thanks!

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/array/linear_algebra.py
> +        axis: Optional[Sequence[int]] = (-2, -1),
axis: Optional[Tuple[int,int]] = (-2, -1) 
else would remain the same.

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/container/linear_algebra.py
> +        axis: Optional[Sequence[int]] = (-2, -1),
here

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/container/linear_algebra.py
> +        axis: Optional[Sequence[int]] = (-2, -1),
here

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/functional/backends/jax/linear_algebra.py
> +    axis: Optional[Sequence[int]] = (-2, -1),
here

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/functional/backends/numpy/linear_algebra.py
> +    axis: Optional[Sequence[int]] = (-2, -1),
here

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/functional/backends/tensorflow/linear_algebra.py
> +    axis: Optional[Sequence[int]] = (-2, -1),
here

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/functional/backends/torch/linear_algebra.py
> +    axis: Optional[Sequence[int]] = (-2, -1),
here

2022-10-10 16:47 UTC, zaeemansari70 commented on ivy/functional/ivy/linear_algebra.py
> +    axis: Optional[Sequence[int]] = (-2, -1),
here

2022-10-11 07:22 UTC, zaeemansari70 approved these changes
Lgtm!

2022-10-11 07:23 UTC, merged