Vander extension
unifyai/ivy pull request #5449
Opened 2022-10-08 14:36 UTC by nassimberrada

2022-10-08 18:48 UTC, Ishticode requested changes
Looks mostly good. Two requests
Could you add the container (instance and static) and array methods
Could you move the example of container from ivy functional over to the container method.
The `NativeArray` examples are not required.
This would be the format with most functions, an array instance method, a container instance method and a container static method would be required usually. These methods will have their own docstring and examples. The examples of these methods are not to be added in ivy functional. Sorry if there is repetition. Please feel free to raise any question Nassim. This is good work. Thank you 🙂

2022-10-08 19:11 UTC, nassimberrada commented
Not at all, i just wasn't sure this structure was the same for all functions, thank you for bearing with me !

2022-10-09 18:30 UTC, Ishticode requested changes
Hi. Looking good. Some minor typos and mistakes. I have made inline comments. Pls feel free to query further or correct me if you believe I hv made a mistake anywhere. When done, pls ensure the tests are passing and hopefully this can be merged in.

2022-10-09 18:30 UTC, Ishticode commented on ivy/array/linear_algebra.py
> +    def vandedr(
name type

2022-10-09 18:30 UTC, Ishticode commented on ivy/array/linear_algebra.py
> +         Number of columns in the output. If N is not specified,
explanation requires indenting

2022-10-09 18:30 UTC, Ishticode commented on ivy/container/linear_algebra.py
> +            N=N,
could you copy all the kwargs here as we did in `flatten`

2022-10-09 18:30 UTC, Ishticode commented on ivy/container/linear_algebra.py
> +        offset
N and increasing parameters not explained here

2022-10-09 18:30 UTC, Ishticode commented on ivy/container/linear_algebra.py
> +        This method Returns the sum along the specified diagonals of a matrix (or a
this seems like an explanation of the trace function. Maybe you forgot to update the docstring here 😂

2022-10-09 18:30 UTC, Ishticode commented on ivy/container/linear_algebra.py
> +        >>> ivy.vander(x)
instance mehtod call should be x.vander()

2022-10-09 19:01 UTC, nassimberrada commented
I did forget to modify the docstrings after copying them didn't i hahah, i corrected that as fast as i could type

2022-10-09 19:01 UTC, nassimberrada commented
I did forget to modify the docstrings after copying them didn't i hahah, i corrected that as fast as i could type

2022-10-09 21:14 UTC, nassimberrada commented
I made sure the tests pass on all four backends now, let me know if there's anything else that requires changing

2022-10-10 17:07 UTC, Ishticode requested changes
ig should be ready to merge after these

2022-10-10 17:07 UTC, Ishticode commented on ivy/container/linear_algebra.py
> +            map_sequences,
perhaps pass this as keyword arguments

2022-10-10 18:12 UTC, Ishticode approved these changes
Looking great. Thanks Nassim.

2022-10-10 18:13 UTC, merged

2022-10-12 09:50 UTC, nassimberrada commented
closes #5562