dropout1d [#5105], Extend Ivy Functional API [#3856]
unifyai/ivy pull request #5469
Opened 2022-10-08 21:52 UTC by MuhammadSaeedBatikh

Maybe it's a good idea to create a unified dropoutxd function and have dropout1d, dropout2d, and dropout3d perform dimensionality checking and call dropoutxd instead of writing separate, identical logic for each?

2022-10-12 08:31 UTC, CatB1t requested changes
Hello @MuhammadSaeedBatikh, Thanks for the great work! I'll be reaching out to someone from the team regarding your suggestion, as this is something we're thinking about also for `convd`.

2022-10-12 22:19 UTC, MuhammadSaeedBatikh commented on ivy/functional/backends/jax/layers.py
> +RNG = jax.random.PRNGKey(0)
Hello @CatB1t, thanks for your review. It's now using `RNG` key from `jax/random.py`.

2022-10-13 18:51 UTC, MuhammadSaeedBatikh commented
Hi @ivy-leaves, and @CatB1t.

I think some of the failing tests might not be related to the task!
For example, the first check: `test-docstrings / run-docstring-tests`
the log says that there's an error at module `ivy/container/extensions.py` in method ``static_moveaxis``
caused by a missing blank line after section ('Parameters') and ('Returns'). I do not believe this is related to dropout1d since all of its container updates are in `container/layers.py` and not `container/extensions.py`.

For the second check: `test-numpy-style-docstrings / run-docstring-tests`
it says "The following methods had failing docstrings:"  and lists methods such as `Container.abs`, ``Container.layer_norm``, Container.conv1d`, and so forth; however, it does not list dropout1d.

2022-10-13 19:14 UTC, MuhammadSaeedBatikh commented
There are also other checks that are failing for some backends and working for others.
For example, `linalg` appears to be working only for numpy. The log indicates that `test_matrix_transpose`, `test_outer `, and `test_trace` have failed.
Also, `manipulation_functions` is working for numpy and jax, but failing for torch and tensorflow. The log for both failed backends outputs **test_squeeze FAILED**.

I am not sure how this is related to dropout1d. Any ideas?

2022-10-21 01:44 UTC, CatB1t requested changes
Please, make sure you run the test locally again with `training=True` after removing the `dtype` parameter, that was causing the test to silently pass, the tests seems to be failing for me locally for all backends.

2022-10-21 01:44 UTC, CatB1t commented on ivy_tests/test_ivy/test_functional/test_nn/test_layers.py
> +        dtype=dtype,
the function doesn't take a `dtype` parameter

2022-10-21 01:44 UTC, CatB1t commented on ivy/functional/backends/torch/layers.py
> +    res = torch.nn.functional.dropout1d(x, p=prob, training=training)
our torch version is pinned to an older release, which doesn't have `dropout1d`, running the test locally throws an exception, you should implement it manually for now, adding a # ToDo to be updated with torch version is updated.

2022-10-21 01:44 UTC, CatB1t commented on ivy_tests/test_ivy/test_functional/test_nn/test_layers.py
> +    ret = helpers.flatten_and_to_np(ret=ret)
you can use `return_flat_np_arrays` flag instead of manually doing it

2022-10-21 01:44 UTC, CatB1t commented on ivy_tests/test_ivy/test_functional/test_nn/test_layers.py
> +    ret = helpers.test_function(
it's better if we also test that the result also match the `ground_truth`

2022-10-21 03:53 UTC, CatB1t commented
> Hi @ivy-leaves, and @CatB1t.
> 
> I think some of the failing tests might not be related to the task! For example, the first check: `test-docstrings / run-docstring-tests` the log says that there's an error at module `ivy/container/extensions.py` in method `static_moveaxis` caused by a missing blank line after section ('Parameters') and ('Returns'). I do not believe this is related to dropout1d since all of its container updates are in `container/layers.py` and not `container/extensions.py`.
> 
> For the second check: `test-numpy-style-docstrings / run-docstring-tests` it says "The following methods had failing docstrings:" and lists methods such as `Container.abs`, `Container.layer_norm`, Container.conv1d`, and so forth; however, it does not list dropout1d.



> There are also other checks that are failing for some backends and working for others. For example, `linalg` appears to be working only for numpy. The log indicates that `test_matrix_transpose`, `test_outer `, and `test_trace` have failed. Also, `manipulation_functions` is working for numpy and jax, but failing for torch and tensorflow. The log for both failed backends outputs **test_squeeze FAILED**.
> 
> I am not sure how this is related to dropout1d. Any ideas?

You can ignore these if they're not related to your task.

2022-10-22 01:53 UTC, MuhammadSaeedBatikh commented
Hi @CatB1t, thanks for the very detailed review!
Regarding the requested changes; I added an additional test for `data_format`, reimplemented `dropout1d` from scratch for older torch versions, and fixed the tests that were failing. 
There are 9 failing checks. I believe 8 of them are unrelated to this task, however, the `run-nightly-tests (jax, layers)` seems to be relevant. 
The log for this Jax check indicates that are two distinct failures, the important one is that there is a type error when calling the `jnp.transpose` method from `jax.layers.dropout1d`.
Specifically it raises the following exception:
`TypeError: transpose requires ndarray or scalar arguments, got <class 'ivy.array.array.Array'> at position 0` 
It seems that during test, an ivy array is being passed to `jax.dropout1d` directly without conversion and subsequently passed to `jnp.transpose` , but I am not sure why/how this is happening.
Any Ideas?

2022-10-22 22:04 UTC, MuhammadSaeedBatikh commented
> Hi @CatB1t, thanks for the very detailed review! Regarding the requested changes; I added an additional test for `data_format`, reimplemented `dropout1d` from scratch for older torch versions, and fixed the tests that were failing. There are 9 failing checks. I believe 8 of them are unrelated to this task, however, the `run-nightly-tests (jax, layers)` seems to be relevant. The log for this Jax check indicates that are two distinct failures, the important one is that there is a type error when calling the `jnp.transpose` method from `jax.layers.dropout1d`. Specifically it raises the following exception: `TypeError: transpose requires ndarray or scalar arguments, got <class 'ivy.array.array.Array'> at position 0` It seems that during test, an ivy array is being passed to `jax.dropout1d` directly without conversion and subsequently passed to `jnp.transpose` , but I am not sure why/how this is happening. Any Ideas?

Adding `@to_native_arrays_and_back` decorator seems to resolve the issue.

2022-10-31 07:00 UTC, CatB1t requested changes
Just few changes! and then we're good to go! 😅

2022-10-31 07:00 UTC, CatB1t commented on ivy_tests/test_ivy/test_functional/test_nn/test_layers.py
>      for u in ret:
This should be `for u, v, k in zip(ret, gt_ret, x):`, also we should assert the shape across all 3.

2022-11-08 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-08 07:35 UTC, MuhammadSaeedBatikh commented
Hi @CatB1t, and @ivy-seed 
I think I have made the necessary changes, could you please review them?  Thanks.

2022-11-08 18:04 UTC, CatB1t approved these changes
lgtm! thanks for your contribution! 😄

2022-11-08 18:04 UTC, merged