Vorbis window
unifyai/ivy pull request #5529
Opened 2022-10-10 15:51 UTC by Change-m

Close #5392

2022-10-10 16:49 UTC, zaeemansari70 requested changes
Requested some changes 🙂

2022-10-10 16:49 UTC, zaeemansari70 commented on ivy/functional/frontends/tensorflow/signal.py
> +    return ivy.vorbis_window(window_length, dtype)
There should be 2 lines at the end of file

2022-10-10 16:49 UTC, zaeemansari70 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_signal.py
> +    ),
There is a syntax error here, kindly fix this.

2022-11-07 09:47 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-17 14:22 UTC, zaeemansari70 commented
Closing as it is marked as done by someone else in the ToDo list.

2022-11-17 14:22 UTC, closed without merging