print_all_ivy_arrays_on_dev
unifyai/ivy pull request #5545
Opened 2022-10-10 21:43 UTC by tamukagate

2022-10-10 21:47 UTC, tamukagate commented
Close #5498

2022-10-15 14:59 UTC, CheezBallzPi commented
Thanks for contributing! Can you add the Formatting Checklist to your PR as shown in this guide? https://lets-unify.ai/ivy/contributing/4_open_tasks.html#formatting-checklist

2022-10-15 16:49 UTC, tamukagate commented
add_reformatting_checklist_device

2022-10-19 03:23 UTC, CheezBallzPi requested changes

2022-10-19 03:23 UTC, CheezBallzPi commented on ivy/functional/backends/jax/device.py
> +def print_all_ivy_arrays_on_dev(
Since all the work is being done outside the backends you can remove these.

2022-10-19 03:23 UTC, CheezBallzPi commented
The failing tests have nothing to do with your code. You can safely ignore them.

2022-10-20 15:50 UTC, CheezBallzPi approved these changes
LGTM

2022-10-20 15:50 UTC, merged