Tensorflow sets.difference #5327
unifyai/ivy pull request #5692
Opened 2022-10-13 20:10 UTC by Abheast12

2022-10-17 03:40 UTC, Abheast12 commented
I'm unsure if I'm doing this correctly -- is there anything I need to modify?

2022-10-17 21:58 UTC, simonetgordon requested changes

2022-10-17 21:58 UTC, simonetgordon commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_sets.py
> +    )
add empty line to end of this file

2022-10-18 07:07 UTC, simonetgordon commented
closes #5327

2022-10-18 07:12 UTC, simonetgordon requested changes

2022-10-18 07:12 UTC, simonetgordon commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_sets.py
> +        fn_name="ivy.functional.frontends.tensorflow.difference"
should be `ivy.functional.frontends.tensorflow.sets.difference`

2022-10-20 17:43 UTC, Abheast12 commented
I have the tensorflow difference function defined in sets.py, so I changed the the tree in test_sets.py from "difference" to "sets.difference". Does that work, or do I have to edit the tensor.py file as well?

2022-10-23 14:38 UTC, simonetgordon requested changes
Hi there, unfortunately the frontend test is still failing. The stacktrace has this:
```
device = 'cpu', args = ('numpy',), kwargs = {'dtype': dtype('int8')}
arr = 'numpy'
```

which would indicate that there is something amiss in the data generation of the test function. Please have a look at 'Details -> Run Frontend Tests` to see the stacktrace yourself so you can go about debugging the issue.

2022-10-25 18:15 UTC, closed without merging