add prod at numpy_frontend
unifyai/ivy pull request #5714
Opened 2022-10-14 14:15 UTC by AmeenUrRehman

Issue no. #5713

2022-10-14 14:18 UTC, AmeenUrRehman commented
@juliagsy plz check this could we ready to merge. Thank You !!!

2022-10-15 14:34 UTC, AmeenUrRehman commented
@JamieLine could we be ready to merge plz check !!!

2022-10-15 14:38 UTC, AmeenUrRehman commented
@juliagsy hey, could we merge this plz check !!!

2022-10-15 15:44 UTC, juliagsy requested changes
Hey there! Great work so far! Just some small changes on formatting and keyword args, please also ensure that tests are passing!

As usual, please request my review again when you're done! Thanks!

2022-10-15 15:44 UTC, juliagsy commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +    def prod(self , axis=None, dtype=None, out=None, keepdims=False, initial=1, where=True):
(for lint fix) please format the parameters such that `param1, param2,...` (comma and spaces formatting)

2022-10-15 15:44 UTC, juliagsy commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +        return np_frontend.prod(self.data , axis , dtype , out, keepdims , initial , where= where)
all parameters beginning from axis are keyword args (i.e., `axis=axis, dtype=dtype,...`)

2022-10-16 05:52 UTC, AmeenUrRehman commented
@juliagsy hey, thanks I have fixed the issues could you plz check this !!!

2022-10-16 05:53 UTC, AmeenUrRehman commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +        return np_frontend.prod(self.data , axis , dtype , out, keepdims , initial , where= where)
@juliagsy done

2022-10-16 20:05 UTC, juliagsy requested changes
Hey! Thanks for the changes! Great work so far! I've just realised, a test is needed for this instance method in the `ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py` file

If the tests are passing, you'll be good to go soon!

2022-10-17 11:35 UTC, closed without merging