Fmod extension
unifyai/ivy pull request #5752
Opened 2022-10-15 13:03 UTC by nassimberrada

2022-10-16 08:36 UTC, Ishticode requested changes
Minor changes then I will link this with an issue and merge....

2022-10-16 08:36 UTC, Ishticode commented on ivy/array/extensions.py
> +        >>> ivy.fmod(x1, x2)
should be instance method use here

2022-10-16 08:36 UTC, Ishticode commented on ivy/functional/backends/numpy/extensions.py
> +        subok=True,
No need for these args
```python
        where=True,
        casting="same_kind",
        order="K",
        dtype=None,
        subok=True,
```

2022-10-16 15:26 UTC, Ishticode requested changes
This was almost ready but due to recent merging of the other PR i think there is more conflicts. Also there is `median` and `ndenumerate` functions added/modfied? is that intentional?

2022-10-16 15:33 UTC, nassimberrada commented
I don't think i worked on those, probably someone else added those extensions ?
I solved the conflicts, here's the link to the corresponding issue fmod #5793

2022-10-17 10:07 UTC, Ishticode approved these changes

2022-10-17 10:07 UTC, merged