Isin
unifyai/ivy pull request #5762
Opened 2022-10-15 17:55 UTC by pillarxyz

#5716 

added most backend implementations there is only problem with tensorflow I'm still trying to solve since it doesnt have the function isin, once I'm able to do that I will add tests

2022-10-17 19:34 UTC, pillarxyz commented
I'm really sorry for this mess of a pull request, I'm still not that good with working with git

just to summerize what I did here

- Added isin for all backends
- Created the implementation for ivy and added wrapping for the array class
- Added the tests but I think I didnt do it well since I'm not familiar with how tests working for the project

2022-10-18 15:55 UTC, abdrahmandiab commented
Hi @pillarxyz ,
As Saeed is taking a hiatus from working with our team, I will be taking over the reviewing process for this PR!
Regarding the messy commits, that's definitely not a problem! We will be squashing this all into one commit while merging so no worries there! 

I have self-requested a review for now as per your last comment which indicates the PR is ready for review, but in the future please request this review yourself once the code is ready. 😄 

Thanks and please be patient with the review as I have quite a few to go through now! 😅

2022-10-18 18:49 UTC, pillarxyz commented
@abdrahmandiab all good, thanks alot

2022-10-22 15:55 UTC, abdrahmandiab requested changes
Hi @pillarxyz , 
It seems that the tests for the function `isin` you implemented are currently failing because there are two parameters missing `with_out` and `container_flags` from the `helpers.test_function` method used for testing. 
For more information you can check the CI test logs [here](https://github.com/unifyai/ivy/actions/runs/3274977034/jobs/5389231390#step:6:517). 

For future reference, you can access the ci test logs by clicking on the `Details` button next to the failing check in our CI tests.
![image](https://user-images.githubusercontent.com/37490334/197348705-285d4591-817b-43da-9d59-499350e6ee5a.png)

After this you can check for the specific error by going to the `Run Extensions Test` section and searching the logs using the top right search bar for `isin`, example shown below... 😅
![image](https://user-images.githubusercontent.com/37490334/197348841-6e64314a-5b2f-4dce-82b2-df04a67dd07d.png)

Could you please work on fixing these errors? 😄
Thanks so much for your work so far, and please don't hesitate to ask for help or re-request a review! 🚀

2022-10-22 17:04 UTC, pillarxyz commented
I will fix it right away, I have a question tho since I noticed that we now have an extensions folder with seperate files where do you see this function fitting ? my first guess was it would be in array/extensions/general.py or array/extensions/utility.py

2022-10-25 12:52 UTC, abdrahmandiab commented
> I will fix it right away, I have a question tho since I noticed that we now have an extensions folder with seperate files where do you see this function fitting ? my first guess was it would be in array/extensions/general.py or array/extensions/utility.py

Hey @pillarxyz ,
sorry for the late reply 😅

Yes you can go ahead and implement this in the `extensions/general.py` file for now!
Thanks!

2022-10-25 13:53 UTC, pillarxyz commented
> > I will fix it right away, I have a question tho since I noticed that we now have an extensions folder with seperate files where do you see this function fitting ? my first guess was it would be in array/extensions/general.py or array/extensions/utility.py
> 
> Hey @pillarxyz , sorry for the late reply 😅
> 
> Yes you can go ahead and implement this in the `extensions/general.py` file for now! Thanks!

Hey @abdrahmandiab I already done that, can you check now if the PR is ready to be merged

2022-10-30 14:19 UTC, pillarxyz commented
Hello @abdrahmandiab 
Mind checking the PR, if there is any modification to be done or is it ready for merge ?

2022-11-02 11:38 UTC, abdrahmandiab commented
> Hello @abdrahmandiab Mind checking the PR, if there is any modification to be done or is it ready for merge ?

Hi @pillarxyz , super sorry for the late review, been quite swamped lately! I will get to this within today or tomorrow hopefully so be on the lookout for that!

Thanks! and apologies for the inconvenience! 😅

2022-11-05 20:06 UTC, abdrahmandiab requested changes
Hi @pillarxyz ,
Great work so far, and apologies once again for the late review 😅 
I have ran the test that you have implemented and found that it still throws some errors. I've already fixed most of the trivial ones which were causing some of the backends to fail, and you can see the changes I've in the commits.

Unfortunately however there still seems to be a problem with the behavior of the parameter `assume_unique` when it comes to the `tensorflow` backend implementation. Could you please try fixing that? and if you face any trouble you can ask me and I will hopefully reply faster this time for sure! 😅

2022-11-05 20:06 UTC, abdrahmandiab commented on ivy_tests/test_ivy/test_functional/test_extensions/test_core/test_general.py
> +        assume_unique=assume_unique,
The `assume_unique` parameter seems to produce unpredictable/incorrect behavior when set to `True` when `fw` is `'tensorflow'`. 😅

2022-11-05 20:25 UTC, abdrahmandiab commented on ivy_tests/test_ivy/test_functional/test_extensions/test_core/test_general.py
> +        assume_unique=assume_unique,
> Hi @pillarxyz , Great work so far, and apologies once again for the late review 😅 I have ran the test that you have implemented and found that it still throws some errors. I've already fixed most of the trivial ones which were causing some of the backends to fail, and you can see the changes I've made in the commits.
> 
> Unfortunately however there still seems to be a problem with the behavior of the parameter `assume_unique` when it comes to the `tensorflow` backend implementation. Could you please try fixing that? and if you face any trouble you can ask me and I will hopefully reply faster this time for sure! 😅
> 
> Thanks!

One more note, as this bug is kind of flaky and not very easy to reproduce, if you are unable to reproduce it we can just merge the PR and handle it later if it starts failing :)

2022-11-05 20:26 UTC, abdrahmandiab commented
One more note, as this bug is kind of flaky and not very easy to reproduce, if you are unable to reproduce it we can just merge the PR and handle it later from our side if it starts failing :)

2022-11-05 20:56 UTC, pillarxyz commented
> One more note, as this bug is kind of flaky and not very easy to reproduce, if you are unable to reproduce it we can just merge the PR and handle it later from our side if it starts failing :)

Yeah I've been having a hard time with the tensorflow implementation. I don't know if I'll be able to work on it the next few days since I'm getting my laptop fixed (I dropped coffee on it 😅)

2022-11-05 20:59 UTC, pillarxyz commented
> > One more note, as this bug is kind of flaky and not very easy to reproduce, if you are unable to reproduce it we can just merge the PR and handle it later from our side if it starts failing :)
> 
> Yeah I've been having a hard time with the tensorflow implementation. I don't know if I'll be able to work on it the next few days since I'm getting my laptop fixed (I dropped coffee on it 😅) 

@abdrahmandiab Also thanks a lot for the help in this PR, its been great.

2022-11-05 21:53 UTC, abdrahmandiab commented
> > > 
> @abdrahmandiab Also thanks a lot for the help in this PR, its been great.

it's my pleasure! truly, and sorry once again for the late reviews haha!
Also, shame about the laptop 😅 Happens to the best of us! Hope it will be fixed soon!

2022-11-06 18:55 UTC, pillarxyz commented
I dont how to deal with these .idea folders getting added to the commit after I solve merge conflicts😅

2022-11-09 09:15 UTC, abdrahmandiab commented on ivy/container/experimental/image.py
> +class ContainerWithGeneralExtensions(ContainerBase):
why was this change made? 😅

2022-11-09 09:50 UTC, abdrahmandiab commented
> I dont how to deal with these .idea folders getting added to the commit after I solve merge conflicts😅

Hi @pillarxyz, could you tell me what method you use for committing things? is it the terminal or through your IDE `source control` window? also what IDE do you use? 😅

2022-11-09 11:47 UTC, pillarxyz commented
> Hi @pillarxyz, could you tell me what method you use for committing things? is it the terminal or through your IDE source control window? also what IDE do you use? 😅

I'm using pycharm with ivy conda environment, and using git in the terminal

2022-11-09 12:04 UTC, pillarxyz commented on ivy/container/experimental/image.py
> +class ContainerWithGeneralExtensions(ContainerBase):
but I fixed that right now

2022-11-09 22:10 UTC, pillarxyz commented
@abdrahmandiab I think that the tensorflow implementation works fine now, although a particular example keeps failing for some reason even though when I try the function in the python console with the inputs in the examples it delivers the expected results.

2022-11-12 14:12 UTC, pillarxyz commented
Hello again

I saw these in both the numpy and jax implementations of isin

![image](https://user-images.githubusercontent.com/80272801/201478002-8867737e-cc53-4a0f-942a-42d26031de77.png)

![image](https://user-images.githubusercontent.com/80272801/201478024-4bf2b542-363c-4154-9ff1-f44577fbbc6f.png)

which suggests that this argument is already problematic in both of those frameworks.

2022-11-13 15:51 UTC, abdrahmandiab commented
hi @pillarxyz,
as a last effort, I think the `assume_unique` output might be producing incorrect results because the generated arrays in these specific test cases themselves are not unique.

So I think before we give up and merge it, if you could edit the data generation to ensure that the generated arrays contain unique elements, I think this might stop the failing examples. My initial idea to do this is to use something like...
```
dtypes_and_values(...).filter( 
    lambda x: x == np.unique(x) #np.unique returns the unique values in an array
)
```

2022-11-13 15:53 UTC, abdrahmandiab commented
> I'm using pycharm with ivy conda environment, and using git in the terminal

Aha, well in this case where you are using it from the terminal, please refrain from using `git add .` and rather please use `git add <specific file name>`  , this might be a bit tedious but it will save you the trouble of committing unwanted changes that are related to the IDE or to the Array API tests. 😅

2022-11-23 08:08 UTC, merged

2022-11-23 08:09 UTC, abdrahmandiab commented
Hi @pillarxyz,
after so long working on this PR, we've finally done it! 🚀

Thanks so much for your hard work, and good luck with the rest of your application process! <3

2022-11-23 11:25 UTC, pillarxyz commented
> Hi @pillarxyz, after so long working on this PR, we've finally done it! 🚀
> 
> Thanks so much for your hard work, and good luck with the rest of your application process! <3

Thanks alot for the help, I've learnt alot about the project thanks to you <3