frontends.tf.linalg: add support for l2_normalize
unifyai/ivy pull request #5772
Opened 2022-10-15 21:29 UTC by hmahmood24

Close #5769

2022-10-19 17:37 UTC, hmahmood24 commented
**Hello @RickSanchezStoic!**

Just a soft reminder to kindly review this PR as and when possible. Thanks you.

2022-10-20 08:54 UTC, RickSanchezStoic commented on ivy/functional/frontends/tensorflow/linalg.py
> +l2_normalize.supported_dtypes = (
We now use decorators to assign `unsupported , supported dtypes and devices` . You are supposed to use `with_supported_dtypes` for this. Check this link https://lets-unify.ai/ivy/deep_dive/data_types.html#backend-data-type-bugs on how to add the version

2022-10-20 18:44 UTC, hmahmood24 commented
Hi @RickSanchezStoic,

Made the changes you asked. Please review and let me know. Thanks

2022-10-21 13:37 UTC, hmahmood24 commented
Also I have reviewed the logs for the nightly tests and the test failed for one backend but when I tried to reproduce that falsifying example using `@reproduce_failure('6.48.2', b'AXicY2JkYIAgEIBSUBoAALAACA==')` as specified in the logs, they ran successfully on my machine with the following output: `hypothesis.errors.DidNotReproduce: Expected the test to raise an error, but it completed successfully.` Just letting you know in case you want to reproduce this at your end to verify that the test runs fine.

2022-10-26 06:05 UTC, hmahmood24 commented
Hello @RickSanchezStoic,

Can you please review the changes I made 5 days ago? Thank you.

2022-10-26 16:20 UTC, RickSanchezStoic requested changes

2022-10-26 16:20 UTC, RickSanchezStoic commented on ivy/functional/frontends/tensorflow/linalg.py
> +
add this decorator `to_ivy_arrays_and_back`

2022-10-28 06:42 UTC, RickSanchezStoic commented
@hmahmood24 Can you try resolving the conflicts, otherwise it looks good to me

2022-10-28 07:02 UTC, hmahmood24 commented
> @hmahmood24 Can you try resolving the conflicts, otherwise it looks good to me

Resolved. 😊

2022-10-31 11:42 UTC, merged