added max
unifyai/ivy pull request #5840
Opened 2022-10-17 16:05 UTC by Viditagarwal7479

Close #5836

2022-10-19 15:59 UTC, zaeemansari70 reviewed
Hey! 
First of all thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Actually, you have implemented the instance method of a function whose ordinary method is not yet implemented 🙂
I have mentioned the exact error in the comments as well.
Thanks!

2022-10-19 15:59 UTC, zaeemansari70 commented on ivy/functional/frontends/torch/Tensor.py
> +        return torch_frontend.max(self.data, dim=dim, keepdim=keepdim)
It's giving an error: `AttributeError: module 'ivy.functional.frontends.torch' has no attribute 'max'`
Make sure that the ordinary `max()` function is implemented before implementing the instance method.
You can implement that If you want. 🙂

2022-10-24 12:56 UTC, zaeemansari70 requested changes

2022-10-24 12:56 UTC, zaeemansari70 commented on ivy/functional/frontends/torch/Tensor.py
> +        return torch_frontend.max(self.data, dim=dim, keepdim=keepdim)
Hi 🙂
The torch frontend doesn't have a `max()` function yet.
This is an instance method that you've implemented, which should call the ordinary `max()` function for torch frontend which is not implemented yet.
 
We'd love if you'd implement the ordinary function too, as every contribution here at Ivy is appreciated.
Thanks! 🙂

2022-10-25 18:36 UTC, Viditagarwal7479 commented
Hey, ivy.max() and all needed functions were already there I noticed a sort of linking issue which I fixed and hope it works well now.:smile:

2022-10-28 13:04 UTC, zaeemansari70 requested changes
I've requested a few more changes!🙂:

1. For the completion on one task, one has to implement a function and it's test, this makes a one single complete task.
2. The instance and the special methods can not be implemented if the ordinary function is not yet completely implemented  which is ` max()` in this case.

You've just added the `max()` function in a file. 
What I would suggest in this case is, make a separate PR, where you implement the `max()` function in `ivy/functional/frontends/torch/reduction_ops.py` and it's test in `ivy_tests/test_ivy/test_frontends/test_torch/test_reduction_ops.py`.
You can revert your change in `ivy/functional/frontends/torch/pointwise_ops.py`, Once your PR for the original function is merged, we will look into this PR.

Do let me know if you have any other questions.
Thanks! 🙂
You can assign the function form here https://github.com/unifyai/ivy/issues/13

2022-11-01 11:38 UTC, zaeemansari70 requested changes
As the original torch frontend `max()` function is now implemented https://github.com/unifyai/ivy/issues/13, your instance method will now be working. 
I've requested a few changes.🙂
Thanks! 🙂

2022-11-02 15:24 UTC, zaeemansari70 approved these changes
Thank you soo much for contributing to ivy! 🙂
Your changes looks good to be merged now!
I hope you enjoyed contributing to Ivy, looking forward to your contribution for Ivy in the future too 🙂
Thanks!

2022-11-02 15:24 UTC, merged