Reformat flip
unifyai/ivy pull request #5863
Opened 2022-10-18 10:46 UTC by hnehme99

2022-10-18 10:49 UTC, hnehme99 commented
Close #5847

2022-10-21 16:19 UTC, Ishticode requested changes
Hi @hnehme99 
Thank you for the PR 🙂

Could you kindly remove any edits in the `.idea`  and the lint failures taken care of. Let me know if there is something unclear. When done request my review. Thank you

2022-10-21 19:02 UTC, hnehme99 commented
Hello @Ishticode ! Thank you for your time.

I have done the requested changes but a new lint error, not related to my changes, appeared
(ivy_tests/test_ivy/test_functional/test_extensions.py:167:52: E231 missing whitespace after ',')

should I fix that too? If there is any additional changes please let me know!

2022-10-23 13:15 UTC, Ishticode requested changes
Hi Looking good. Some minor change as in the comment. Also could you include one example using the `axis` argument for the container/array. Furthermore, could you delete the container, and instance method examples for the docstring in `ivy/functional/ivy/manipulation.py` for `flip`.

2022-10-23 13:15 UTC, Ishticode commented on ivy/container/manipulation.py
> +        >>> y = ivy.flip(x)
As its a container instance method example, the instance call should be made i.e., `x.flip()`

2022-10-23 21:09 UTC, hnehme99 commented
Thank you again @Ishticode ! 

I completed the requested changes. Please let me know if there is any additional changes!

2022-10-25 18:31 UTC, Ishticode approved these changes
Thank you very much @hnehme99 for you contribution and for taking care of flip in torch backend. Not sure how those typehint sneaked in there.

I will get this merged 🙂. Thanks.

2022-10-25 18:32 UTC, merged