added rfft
unifyai/ivy pull request #5865
Opened 2022-10-18 12:31 UTC by Viditagarwal7479

Close #5501

2022-10-20 15:36 UTC, MarShaikh requested changes
Can you update your PR to not add changes to the `test_array_api`?

2022-10-22 09:53 UTC, Viditagarwal7479 commented
Hey,
the extensions.py files have been removed from all the folders, and a new directory extension has been created in a recent change which took place in this PR https://github.com/unifyai/ivy/pull/5970

So in which file of the extensions directory shall I add ```rfft``` function?

Thanks
Vidit

2022-10-27 14:49 UTC, MarShaikh commented
> Hey, the extensions.py files have been removed from all the folders, and a new directory extension has been created in a recent change which took place in this PR #5970
> 
> So in which file of the extensions directory shall I add `rfft` function?
> 
> Thanks Vidit

You can add it to the `ivy/functional/ivy/extensions

> Hey, the extensions.py files have been removed from all the folders, and a new directory extension has been created in a recent change which took place in this PR #5970
> 
> So in which file of the extensions directory shall I add `rfft` function?
> 
> Thanks Vidit

You can add it to `ivy.functional.extensions.layers`!

2022-11-02 11:31 UTC, MarShaikh requested changes

2022-11-02 11:31 UTC, MarShaikh commented on ivy/array/extensions/layers.py
> +        return ivy.rfft(input, n, norm, out=out)
The way you have written this array method isn't correct, please check the other examples in file!

2022-11-02 11:31 UTC, MarShaikh commented on ivy/array/extensions/layers.py
> +        >>> ivy.rfft(x)
Also, please refer to the docs to see the correct way of calling array instance methods!

2022-11-02 11:33 UTC, MarShaikh requested changes
Finally if you see the test-extensions in the CI, it is also failing, can you check that as well!

2022-11-10 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-17 06:25 UTC, closed without merging

2022-11-17 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.