safety factor linalg
unifyai/ivy pull request #5909
Opened 2022-10-19 15:24 UTC by zaeemansari70

2022-10-21 18:20 UTC, djl11 requested changes
I think the layout of the function can be made much simpler. The "safety factor" should be a configurable parameter in the function, and I don't think we need the `condition_index` argument. In all cases we simply determine the condition of the matrix, and see if this is above or below a pre-defined threshold. Rather than `safety_factor` we should simply have a function like this using a `cond_limit`:

```
def matrix_is_stable(x, cond_limit=10):
    return np.linalg.cond(x.astype('float64')) <= cond_limit
```

What do you think?

2022-10-25 15:53 UTC, zaeemansari70 commented
Oh yeah, this would be a lot simpler.
I've refactored the description and the function too.
Just one more thing, I think that the `cond_limit=10` should be starting from "30", and gradually being decreased if the tests still fail just to result in more and more stable matrices.
Starting it from "10" will restrict the function from being tested on a smaller subset of matrices beforehand. Keeping it to "30" in the start we will be able to test it on a wider range of matrices.

What do you think?

2022-11-02 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-04 12:47 UTC, djl11 approved these changes
lgtm!

2022-11-04 13:48 UTC, merged