added numpy.indices to numpy frontend
unifyai/ivy pull request #6142
Opened 2022-10-25 12:50 UTC by lamaran1

2022-10-28 06:55 UTC, RickSanchezStoic commented
Hi, @lamaran1 can you try fixing the lint errors and the test failures? Thanks!

2022-10-30 20:49 UTC, lamaran1 commented
@Ric

> Hi, @lamaran1 can you try fixing the lint errors and the test failures? Thanks!

Okay, on it

2022-10-31 13:18 UTC, lamaran1 commented
> Hi, @lamaran1 can you try fixing the lint errors and the test failures? Thanks!

Hi @RickSanchezStoic, i have been able to fix the lint errors but i cant tell the source of the nightly-test error, on the discord server, it seems it was ignored without solutions. Is this something you could help me check and direct me? thank you.

2022-11-06 06:36 UTC, RickSanchezStoic requested changes

2022-11-06 06:36 UTC, RickSanchezStoic commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_generating_index_arrays.py
> +        fn_tree="numpy.indices",
change this to just `indices`

2022-11-17 15:18 UTC, lamaran1 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_indexing_routines/test_generating_index_arrays.py
> +        fn_tree="numpy.indices",
thank you

2022-11-17 15:30 UTC, lamaran1 commented
Made the change but still getting an error on the run-nightly-tests

2022-11-29 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-12-06 06:25 UTC, closed without merging

2022-12-06 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.