Added adjoint superset behavior
unifyai/ivy pull request #6243
Opened 2022-10-27 20:09 UTC by KareemMAX

2022-11-07 09:46 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-07 10:10 UTC, KareemMAX commented
@CatB1t Can please review the PR when you have the chance?

2022-11-09 06:29 UTC, CatB1t commented on ivy/functional/ivy/linear_algebra.py
> +    >>> x = ivy.Container(a=ivy.array([[1 + 1j, 2 + 2j, 3 + 3j],
Inconsistent indentation

2022-11-09 06:40 UTC, CatB1t requested changes

2022-11-09 06:40 UTC, CatB1t commented on ivy/functional/ivy/linear_algebra.py
> +    >>> x = ivy.Container(a=ivy.array([[1 + 1j, 2 + 2j, 3 + 3j],
Inconsistent indentation

2022-11-09 06:40 UTC, CatB1t commented on ivy/functional/ivy/linear_algebra.py
> +     >>> x = ivy.array([[1 + 1j, 2 + 2j, 3 + 3j],
Inconsistent indentation

2022-11-09 06:40 UTC, CatB1t commented on ivy/functional/backends/numpy/linear_algebra.py
> +    return np.conj(x.transpose(list(range(x.ndim - 2)) + [x.ndim - 1, x.ndim - 2]))
this can be simplified to `return np.moveaxis(np.conj(x), -1, -2)` similarity for JAX too, otherwise lgtm!

2022-11-09 06:44 UTC, CatB1t commented
just few changes, along with fixing the conflict then we're good to merge 😄

2022-11-17 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-24 06:25 UTC, closed without merging

2022-11-24 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.