Added OneHot to raw_ops
unifyai/ivy pull request #6244
Opened 2022-10-27 20:10 UTC by KareemMAX

2022-10-31 08:03 UTC, CatB1t requested changes

2022-10-31 08:03 UTC, CatB1t commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +def OneHot(*, indices, depth, on_value, off_value, axis=-1, name="OneHot"):
We should flag that the function does only support few data types, `int32, int64, uint8`

2022-10-31 17:35 UTC, KareemMAX commented
Addressed your issues and resolved conflicts

2022-11-08 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-09 04:02 UTC, CatB1t requested changes

2022-11-09 04:02 UTC, CatB1t commented on ivy/functional/frontends/tensorflow/raw_ops.py
> +OneHot.supported_dtypes = ("int32", "int64", "uint8")
we no longer use this, we now have a decorator for that: https://lets-unify.ai/ivy/deep_dive/data_types.html#supported-and-unsupported-data-types

2022-11-16 06:26 UTC, closed without merging

2022-11-16 06:26 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.