Added Pack to raw_ops
unifyai/ivy pull request #6245
Opened 2022-10-27 20:11 UTC by KareemMAX

Close https://github.com/unifyai/ivy/issues/5407

2022-10-31 07:10 UTC, CatB1t requested changes
just a small change, otherwise lgtm!

2022-10-31 07:10 UTC, CatB1t commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_raw_ops.py
> +        available_dtypes=helpers.get_dtypes("valid", full=True),
No need to specify `full=True` here, it's `True` by default.

2022-10-31 17:26 UTC, KareemMAX commented
Fixed the issue and resolved the conflicts I had

2022-11-04 05:19 UTC, CatB1t commented
lgtm! could you resolve the conflict? then we're good to merge 😄

2022-11-04 05:21 UTC, CatB1t approved these changes

2022-11-04 05:21 UTC, CatB1t approved these changes

2022-11-07 12:13 UTC, KareemMAX commented
@CatB1t Conflicts resolved

2022-11-08 17:58 UTC, merged