astype #6242
unifyai/ivy pull request #6252
Opened 2022-10-27 21:51 UTC by codeamic

2022-11-03 22:44 UTC, zaeemansari70 reviewed
Hey! 
Thank you soo much for contributing to ivy! 🙂
Your PR looks amazing ✨!
Just requested a few changes and left comments on them which needs to be addressed before we can merge your PR! 🙂
Thanks!

2022-11-03 22:44 UTC, zaeemansari70 commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +    def astype(self,dtype,order="K",casting="unsafe",subok=True,copy=True):
You haven't implemented the `test_function` which should be implemented to complete the task, I'll link you to the document which would help you in the process.
https://lets-unify.ai/ivy/deep_dive/ivy_frontends_tests.html#frontend-instance-method-tests
Also, there are some lint errors which also need to be fixed 🙂

2022-11-13 21:33 UTC, codeamic commented
close #6242

2022-11-13 21:58 UTC, codeamic commented
Hi zaeemansari70 , please could you review.

2022-11-15 08:46 UTC, zaeemansari70 requested changes
Awesome, thanks for the changes! 🙂
Just a few more changes required, I've mentioned them below!

1. In the `files changed tab`, your changes are also being showed in the `test_array_api` folder, which shouldn't be the case, changes should show only in the 2 files, `ndarray.py` and `test_ndarray.py` in this case. Kindly remove the changes in the `test_array_api` folder.
2. Also, there are multiple lint errors, you have to resolve them too.

Thanks! 🙂

2022-11-23 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-24 11:32 UTC, aditya-pola commented
Hey @codeamic :) apologies for the delay, I did not get notification of this reassignment.
Your code seems to be failing the lint checks. You can automatically resolve most of these be installing the [pre-commit hooks](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit)
The changes to test_array_api are not relevant to this PR as zaeemansari70 has kindly pointed out. Please revert them.

2022-11-25 12:26 UTC, closed without merging