eig function is added as en extension as for issue #6180
unifyai/ivy pull request #6347
Opened 2022-10-30 18:17 UTC by zhumakhan

#6180

2022-10-30 18:22 UTC, zhumakhan commented
Test is not added due to non-uniqueness of eigenvectors: https://pytorch.org/docs/stable/generated/torch.linalg.eig.html: "The returned eigenvectors are normalized to have norm 1. Even then, the eigenvectors of a matrix are not unique, nor are they continuous with respect to A. Due to this lack of uniqueness, different hardware and software may compute different eigenvectors."

2022-11-02 23:37 UTC, Ishticode requested changes
Hi. Thanks for the PR. We will still require a test. Yes the values may not be unique but many other attributes of the output sequence of arrays like dtype etc. to be checked. To ensure values are not tested for their correctness, the argument `test_values` can be set to false in `test_function`. 
🙂
Let me know if the above doesn't make sense or if you have any further queries. Thank you

2022-11-12 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-16 22:42 UTC, Ishticode requested changes
Hi. Apologies for the delay. This PR was opened and closed several times and I got a bit mixed up. Your PR seems good but there are several conflicts to resolve. Could you resolve these kindly and ask for a review 🙂. Feel free to ask any questions. Thank @zhumakhan

2022-11-17 13:42 UTC, zhumakhan commented
@Ishticode conflicts are resolved, thanks a lot for you comments

2022-11-21 13:14 UTC, Ishticode requested changes
Hi @zhumakhan 
Thanks for the update. Could you take care of the following comments.

2022-11-21 13:14 UTC, Ishticode commented on ivy/functional/backends/tensorflow/experimental/linear_algebra.py
> +Natively supports float32, float64, complex64, complex128 data types.
we don't really require these comments

2022-11-21 13:14 UTC, Ishticode commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +"""eig. Values are not tested since eigenvectors are not unique
These comments are not required

2022-11-21 13:14 UTC, Ishticode commented on ivy/container/experimental/linear_algebra.py
> +        return ContainerBase.multi_map_in_static_method(
Could we add a docstring for this too... with some examples : )

2022-11-28 09:28 UTC, closed without merging