Add log2 Reformatting function
unifyai/ivy pull request #6355
Opened 2022-10-31 05:00 UTC by mohanadtalat91

Issue #5896

2022-11-01 13:31 UTC, mohanadtalat91 commented
Hi @CatB1t, 👋😊
Could you please review my PR, feel free to ask for any updates. Thanks in advanced

2022-11-04 05:25 UTC, CatB1t commented on ivy/array/elementwise.py
> +        ivy.array([nan, nan, -inf, 0., 2., inf])
Space after output

2022-11-04 05:25 UTC, CatB1t commented on ivy/array/elementwise.py
> +        ivy.array([2., 0., -inf, nan])
Space after output

2022-11-04 05:25 UTC, CatB1t commented on ivy/functional/ivy/elementwise.py
> +    ivy.array([2.189, nan])
New line after output

2022-11-04 05:25 UTC, CatB1t commented on ivy/functional/ivy/elementwise.py
> +               [-inf, nan, nan, nan]])
New line after output

2022-11-04 05:26 UTC, CatB1t requested changes
Just few changes, we need to add a new lien after the example output. could you please fix that?

2022-11-08 22:01 UTC, mohanadtalat91 commented
> Just few changes, we need to add a new lien after the example output. could you please fix that?

I've fixed these changes. @CatB1t

2022-11-09 03:58 UTC, CatB1t requested changes
Just one small change, then we're good to merge!

2022-11-09 03:58 UTC, CatB1t commented on ivy/array/elementwise.py
> +        Using :code:`ivy.Array` instance method:
Could you provide a simple example by only using a 0-dim input? for example `ivy.array(10)`

2022-11-11 19:37 UTC, mohanadtalat91 commented
> 

Hello @CatB1t👋 , the 0-dim example has been added.

2022-11-16 23:44 UTC, CatB1t requested changes
Hello @mohanadtalat91, everything looks great! your changes seems to be causing the `lint / check-formatting` test to fail though, could please take a look and get that fixed before merging? Thanks! 😄

2022-11-26 16:40 UTC, mohanadtalat91 commented
> Hello @mohanadtalat91, everything looks great! your changes seems to be causing the `lint / check-formatting` test to fail though, could please take a look and get that fixed before merging? Thanks! 😄

Hi @CatB1t, I've resolved failure of this test, all `black & flake8` are passed at my local, but still failling here at `lint / check-formatting (pull_request)` !!
  
And here's the screenshot 
![ivy](https://user-images.githubusercontent.com/63791516/204099219-f7dfd981-fd9a-432c-813c-44189e1c986f.png)

2022-12-02 01:14 UTC, CatB1t requested changes
Hello @mohanadtalat91, I've fixed the linting and styling errors for you, but the output of examples seems to be invalid, can you double check why is it fail and get those fixed? Thanks!

2022-12-10 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-12-10 06:27 UTC, mohanadtalat91 commented
> Hello @mohanadtalat91, I've fixed the linting and styling errors for you, but the output of examples seems to be invalid, can you double check why is it fail and get those fixed? Thanks!

Yeah, sure.
Thanks

2022-12-18 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-12-18 13:35 UTC, mohanadtalat91 commented
> 

Continue

2022-12-19 09:51 UTC, CatB1t commented
Hello @mohanadtalat91 , `test-docstrings` and `test-numpy-style-docstrings` are still failing, can you have a look at what's causing them to fail and fix those? Thanks! 😄

2022-12-19 09:51 UTC, CatB1t requested changes
Hello @mohanadtalat91 , `test-docstrings` and `test-numpy-style-docstrings` are still failing, can you have a look at what's causing them to fail and fix those? Thanks! 😄

2022-12-26 06:25 UTC, closed without merging

2022-12-26 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.