added get in tensorflow frontends
unifyai/ivy pull request #6550
Opened 2022-11-04 03:17 UTC by MahmoudAshraf97

Hello, reference #6062 
this function is just a wrapper for ivy.deserialize when tensorflow backend is used. It's identical to the current tensorflow implementation without support for custom objects

2022-11-04 08:42 UTC, WilliamHirst requested changes
Hi Mahmoud, good job on the commit! 
There are a couple of formatting issues that need fixing.

2022-11-04 08:42 UTC, WilliamHirst commented on ivy/functional/backends/tensorflow/activations.py
> +def get(identifier: Union[str, ivy.Callable, None], /, *, custom_objects=Union[ivy.Dict, None]) -> Union[ivy.Callable, None]:
Here you have exceeded the maximum length for a line of code.

2022-11-04 08:42 UTC, WilliamHirst commented on ivy/functional/backends/tensorflow/activations.py
> +        raise TypeError('Could not interpret activation function identifier: {}'.format(identifier))
Same here. This I belive you can fix by simply changing to a f-string.

2022-11-04 14:49 UTC, MahmoudAshraf97 commented
Hi @WilliamHirst , Changes are finished please review.

2022-11-04 15:29 UTC, WilliamHirst reviewed
Hi, there are still some formatting errors that need fixing.

2022-11-04 15:29 UTC, WilliamHirst commented on ivy/functional/backends/tensorflow/activations.py
> +) -> Union[ivy.Callable, None]:
When splitting the function arguments over several lines, all arguments should be on a separate line. See the deserialize function in the same file for example.

2022-11-04 15:29 UTC, WilliamHirst commented on ivy/functional/backends/tensorflow/activations.py
> +        raise TypeError(f"Could not interpret activation function identifier: {identifier}")
The line is still too long. Please split the string into several lines. Again making sure that the argument (the string) is on a separate line.

2022-11-04 15:45 UTC, MahmoudAshraf97 commented
I've reformatted the function using black, please review

2022-11-05 08:43 UTC, WilliamHirst commented
Looks good!

2022-11-05 08:56 UTC, merged