Initial compiled Wrapping logic.
unifyai/ivy pull request #6564
Opened 2022-11-04 12:09 UTC by vaatsalya123

Will add more generalized cache registers for the MRUcache method.Though for now this is the initial start will explore TTL based caching as well.

docs for cachetools framework: https://cachetools.readthedocs.io/en/latest/

2022-11-04 13:02 UTC, djl11 requested changes

2022-11-04 13:02 UTC, djl11 commented on ivy/func_wrapper.py
> +# Just a native python compile function with cache #
Just write "Compiling with Cache", and change the number of `-` so that the title aligns correctly please :)

2022-11-07 01:09 UTC, JamieLine commented
Hi!

Because Daniel has already reviewed this, am I safe to assume I don't need to look through everything unless requested? Just want to make sure people aren't being held up.

2022-11-07 07:44 UTC, vaatsalya123 commented
Hey @JamieLine yep you don't need to go through this pr Dan will go through all of it thanks.

2022-11-10 21:40 UTC, djl11 requested changes
tiny change requested aha, but do we still want to merge this. Maybe we should close until we have finalised the discussion around the best design. What do you think @vaatsalya123?

2022-11-10 21:40 UTC, djl11 commented on ivy/func_wrapper.py
> +# Compiling with Cache #
small detail but the number of `-` still don't align with the title length! aha

2022-11-20 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-11-22 17:09 UTC, closed without merging