array_like_handler wrapper
unifyai/ivy pull request #6768
Opened 2022-11-09 08:23 UTC by Ishticode

2022-11-11 21:38 UTC, djl11 requested changes
general feedback, cache what you can, don't compute the same thing repeatedly. If something is called more than once in the script, do it once and store it rather than continuing to compute it repeatedly :)

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +        parameters = list(typing.get_type_hints(fn))
calling `typing.get_type_hints(fn)` twice is very inefficient. You should cache this first: `type_hints = typing.get_type_hints(fn)`

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +        for i in range(len(annotations)):
`for i, (annotation, parameter, arg) in enumerate(zip(annotations, parameters, args)):`

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +            if "Array" in str(annotations[i]) and all(
`if "Array" in str(annotation) and all(`

etc.

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +                if i < len(args):
`num_args = len(args)` should be cached outside the for loop

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +
`annotation_str = str(annotation)` should be cached

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +                    if isinstance(args[i], (list, tuple)):
`if isinstance(arg, (list, tuple)):`

etc.

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +                        args[i] = ivy.array(args[i])
`args[i] = ivy.array(arg)`

2022-11-11 21:38 UTC, djl11 commented on ivy/func_wrapper.py
> +                elif parameters[i] in kwargs:
```
elif parameter in kwargs:
    kwarg = kwargs[parameter]
    if isinstance(kwarg, (list, tuple)):
        kwargs[parameter] = ivy.array(kwarg)
```

2022-11-11 21:56 UTC, Ishticode commented
Thanks Dan. Very useful principal indeed and I am not sure why i didn't use zip in the first place 🙃.

2022-11-14 21:53 UTC, djl11 approved these changes
lgtm!

2022-11-16 10:48 UTC, merged