torch frontend ViewTensor class Update
unifyai/ivy pull request #7143
Opened 2022-11-17 21:51 UTC by JerryGCDing

2022-11-22 20:17 UTC, djl11 requested changes
haven't dived too deep but looks good to me. Could you please add unit tests which verify that the view tensor behaves as expected? Feel free to implement this test using pytest.parameterize rather than fully generalized via hypothesis. Thanks!

2022-11-22 20:17 UTC, djl11 commented on ivy/functional/frontends/torch/tensor.py
>          return self.data
Why exactly do these return `self.data`? Should they not return `self`? The current implementation will return an `ivy.Array` which is wrong I believe. Can you change these to all return `self` instead?

2022-11-22 20:17 UTC, djl11 commented on ivy/functional/frontends/torch/tensor.py
> +        view = torch_frontend.ViewTensor(weakref.ref(self), shape=shape)
this can be done in a single line

2022-11-23 06:32 UTC, JerryGCDing commented
Added a `pytest.mark` keyword check in the fixture within `confest.py` file for frontend tests so that it doesn't prevent parameterized tests from running. The behavior test design for `ViewTensor` class is that for non-inplace instance methods, the test will check if the returned values are the same as its base tensor. For inplace methods, the test will check if the base tensor is being properly updated.

2022-11-24 08:18 UTC, djl11 approved these changes
looks good to me! I'll also just request a review from Mustafa to verify that the changes to `conftest.py` are good, thanks!

2022-11-26 08:26 UTC, CatB1t requested changes
Hello @JerryGCDing, I've pushed a fix for `conftest.py` which should run all tests normally, you won't need to use a mark for it, feel free to merge after removing the markers.

2022-11-26 08:51 UTC, merged