Numpy frontend nanstd #7071
unifyai/ivy pull request #7218
Opened 2022-11-21 10:27 UTC by JortdeJong13

My previous pull request for this issue seems to be gone, so I'm making this new one.
I implemented a test function for _nanstd_, but I can't run the tests because of a code refractor that makes all tests fail. I used the other test functions in _ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py_ as reference.

2022-11-24 08:21 UTC, JortdeJong13 commented
Close #7071

2022-11-25 16:31 UTC, jkeane508 requested changes
After chatting with the testing team, it seems that you no longer need to specify the framework for frontend tests.

2022-11-25 16:31 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py
> +    fw,
You no longer need to specify this.

2022-11-25 16:31 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py
> +        fw=fw,
or this

2022-11-28 10:29 UTC, JortdeJong13 commented
I made the changes as requested. Are the tests still broken? All the tests in _test_averages_and_variances.py_ seem to fail.

2022-12-06 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-12-06 08:49 UTC, JortdeJong13 commented
.

2022-12-10 10:02 UTC, jkeane508 requested changes
Hey, sorry this PR completely slipped my radar. The files seem to have lint errors, you can fix this by installing a pre-commit hook as documented [here](https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit).

It also seems as though the tests didn't run properly, will follow up once I can see the test logs :)

2022-12-11 16:45 UTC, jkeane508 requested changes
Hey,

It seems the tests are still not running correctly, can you update your branch? Perhaps that would fix some bugs that have since been resolved. :)

Thanks!

2022-12-13 10:55 UTC, JortdeJong13 commented
The existing tests in _ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py_ still seem bugged.

2022-12-17 16:21 UTC, jkeane508 approved these changes
lgtm :)

2022-12-19 17:47 UTC, jkeane508 requested changes
Now that Master is open again, just need to resolve conflicts and we can go ahead and merge to master :)

2022-12-20 09:28 UTC, JortdeJong13 commented
I resolved the conflicts.

2022-12-22 13:06 UTC, merged