cosine embedding loss function in pytorch frontend
unifyai/ivy pull request #7234
Opened 2022-11-22 04:08 UTC by satani99

2022-11-22 04:11 UTC, satani99 commented
Issue #7199

2022-11-23 17:48 UTC, satani99 commented
Close #7199

2022-11-23 17:49 UTC, satani99 commented
hey @Ishticode check this code

2022-11-23 17:50 UTC, satani99 commented
I think nightly tests are failing in all PyTorch loss functions

2022-11-29 15:13 UTC, Ishticode requested changes
Hi @satani99 
Thanks a lot for the PR. 🙂.
There was a CI issue which failed to instantiate the tests properly at the time. Could you kindly resolve the merge conflicts and this should trigger the tests to be re-run. You can request a review once updated. Thanks. Let me know if you have any query. You can request a review once updated.

2022-11-30 04:16 UTC, satani99 commented
I think front-end tests run correctly. Ready for review.

2022-12-01 19:06 UTC, Ishticode requested changes

2022-12-01 19:06 UTC, Ishticode commented on ivy/functional/frontends/torch/nn/functional/loss_functions.py
> +        loss = 1 - similarity
This line throws an error as `TypeError: unsupported operand type(s) for -: 'int' and 'Tensor'`. Perhaps using a debugger to see why the operation isn't supported. Normally an operation as such should be valid. Feel free to ask anything and please request when my review when fixed.

2022-12-07 16:07 UTC, Ishticode requested changes
Hi. I see that the whole of the files `linalg.py` and `test_linalg` are deleted. Could you kindly undo that change and request a review.🙂

2022-12-13 09:37 UTC, Ishticode requested changes
Hi @satani99 
Thanks for the review request. 
The test `test_torch_cosine_embedding_loss` is failing with error `IndexError: Too many indices for array: 1 non-None/Ellipsis indices for dim 0`. You can see this by clicking on Frontend Pytorch test run "details" down below. Could you kindly fix this and also resolve the conflict. Feel free to follow or ask a question if this doesn't make sense and feel free to request a review when you its ready to be reviewed again. Thank you @satani99

2022-12-15 11:21 UTC, Ishticode requested changes
@satani99 
Somehow your last changes ended up removing the import for distance functions and now the test throws error for undefined `distance_function` call. Do you have a setup where u can check for tests. I would advice setting up test running or if not then perhaps checking out the CI logs from below for `test-frontend-torch / run-nightly-tests (pull_request)` 

Minor mistakes like this will take more time of yours than they should. The progress would be quicker if such errors have been taken care of and the tests have been checked out by yourself. 

However, I am totally happy to review whenever you want. This is just a tip to speed up your PR's progress. Hope it makes sense.

Meanwhile could you recover the `distance_function` import and fix any test error pointed to earlier and feel free to ask anything. 🙂

2022-12-15 11:32 UTC, satani99 commented
How do I test on my local computer?

2022-12-16 14:41 UTC, Ishticode reviewed
Hi You can setup with using this [setting up instructions](https://lets-unify.ai/ivy/contributing/setting_up.html) or try one of the relevant vidz from [this youtube playlist](https://www.youtube.com/playlist?list=PLwNuX3xB_tv-7NexAEzC2dCbgj5ojr-0X).
Let me know if anything doesn't quite make sense.  🙂

2022-12-31 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-12-31 16:05 UTC, Ishticode requested changes
Hi @satani99 
I am not sure how I missed leaving the review. I remember writing it two days ago but probably did not submit. 
Apologies for the delay anyhow.

Did you manage to setup a system.
The tests still fail for number of reasons.
The main reason is that the `target` argument needs more care. 

Pytorch expects targets to be tensors so we should also consider target to be tensor and treat it like tensors... They should be generated as tensors in the test and not as integers of 1 or -1.

Additionally, the case where target is just provided as a value other than 1 or -1, we should be catching it within the function and raising an exception. Otherwise the loss variable will be undefined... unless you want to define loss = None beforehand.
Please feel free to try these and ask any questions.

2023-01-07 06:25 UTC, closed without merging

2023-01-07 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.