Adding zeros_like to tf frontend
unifyai/ivy pull request #7235
Opened 2022-11-22 05:06 UTC by danielmunioz

2022-11-22 05:08 UTC, danielmunioz commented
Close #7233

2022-11-25 15:30 UTC, simonetgordon requested changes
Hi @danielmunioz, thanks for the contribution :) Could you please resolve the merge conflicts so the checks will run on this PR? Thanks!

2022-11-26 02:05 UTC, danielmunioz commented
Done! @simonetgordon

2022-11-28 15:27 UTC, simonetgordon approved these changes

2022-11-28 18:05 UTC, merged