Added numpy average frontend and test
unifyai/ivy pull request #7347
Opened 2022-11-25 08:59 UTC by shireenchand

Issue number - https://github.com/unifyai/ivy/issues/6739

2022-11-25 12:52 UTC, shireenchand commented
Hey @AnnaTz, can you please review the PR and let me know if any changes are required
Thanks!

2022-11-28 08:09 UTC, AnnaTz requested changes
Also, please have a look at `lint / check-formatting (pull_request)` > `Details`. There are some formatting errors that I think are caused by your PR.

2022-11-28 08:09 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py
> +    ),
The current test handlers should not be given the `num_positional_args`. Could you please remove it?

2022-11-28 08:09 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py
> +        keep_dims,
You should also add `on_device` to the arguments and pass it to `test_frontend_function` below, as done for example [here](https://github.com/unifyai/ivy/blob/2ae5f1e6b6ffd10e95c8e8c68f6747dd24cd4f0a/ivy_tests/test_ivy/test_frontends/test_numpy/test_linear_algebra/test_decompositions.py#L27).

2022-11-28 08:09 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py
> +        test_values=False,
Why have you chosen to set `test_values=False`?

2022-11-28 08:09 UTC, AnnaTz commented on ivy/functional/frontends/numpy/statistics/averages_and_variances.py
> +    # a = ivy.array(a)
You can clean up this comment.

2022-11-28 13:17 UTC, shireenchand commented
Hi @AnnaTz, I have made the changes requested. Can you please check and let me know
Thanks!

2022-11-28 14:16 UTC, AnnaTz requested changes
Could you please merge master to your PR? The CI test checks are failing due to an error that has now been resolved.

2022-11-28 14:16 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py
> +        test_values=True,
You can remove `test_values` entirely as `True` is the default value.

2022-11-28 18:10 UTC, shireenchand commented
Hi @AnnaTz,
I have merged master into the PR. Can you check and let me know
Thanks!

2022-11-29 08:03 UTC, AnnaTz requested changes
Currently `test_numpy_average` has some failures you need to fix. To see them, please click on `Details` next to the failing `test-frontend-numpy / run-nightly-tests (pull_request)`, then click on `Run Frontend Tests` to expand it, and search for 'test_numpy_average'.

2022-11-29 08:03 UTC, AnnaTz commented on ivy/functional/frontends/numpy/statistics/averages_and_variances.py
> +        return 0
You need to make sure the test function does not cause the ZeroDivisionError.

2022-11-29 16:53 UTC, shireenchand commented
Hi @AnnaTz, I have handled the ZeroDivisionError as well as the infinity error. Can you please check
Thanks!

2022-11-30 07:37 UTC, AnnaTz requested changes

2022-11-30 07:37 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py
> +)
Just noticed the `returned` argument is not tested. Could you please add it here?

2022-11-30 15:16 UTC, AnnaTz requested changes

2022-11-30 15:16 UTC, AnnaTz commented on ivy_tests/test_ivy/helpers/hypothesis_helpers/array_helpers.py
> +                        # allow_subnormal=allow_subnormal,
Is there a reason you commented out these lines here?

2022-11-30 15:27 UTC, AnnaTz approved these changes
Everything looks good to me now. Ready to be merged!

2022-11-30 15:28 UTC, merged