adding numpy diagonal instance method
unifyai/ivy pull request #7363
Opened 2022-11-25 18:14 UTC by hnehme99

Close #7190

2022-11-27 06:18 UTC, hirwa-nshuti requested changes
Hi,

The `diagonal` function isn't yet implemented on the numpy frontend. So I think we can have it implemented first before implementing its instance method. 
Feel free to go ahead and take on the task of implementing it or wait for it to be added to the numpy frontend.

Thanks🙂

2022-11-27 06:18 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +        return np_frontend.diagonal(
The `diagonal` function is not yet implemented in the numpy frontend

2022-11-27 06:18 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +            self.data,
```suggestion
            self._ivyArray,
```
Here the recent refactoring change to use `_ivyArray` instead of `data`

2022-12-07 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-12-12 04:32 UTC, hirwa-nshuti requested changes
These extra parameters should be deleted

2022-12-12 04:32 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +    method_tree="numpy.ndarray.diagonal",
```suggestion
```

2022-12-12 04:32 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +    method_tree="numpy.ndarray.sort",
```suggestion
```

2022-12-12 04:33 UTC, merged