jax_numpy_degrees implimentation
unifyai/ivy pull request #7492
Opened 2022-11-30 17:40 UTC by ndurumo254

#7477 degrees

2022-11-30 17:59 UTC, ndurumo254 commented
#7477

2022-11-30 18:01 UTC, ndurumo254 commented
#7492

2022-11-30 18:35 UTC, ndurumo254 commented
hello @fspyridakos.
am getting this error when i ran it from my local machine. how should i go about it.

E   ivy.exceptions.IvyError: tensorflow: function_supported_devices_and_dtypes: tensorflow: function_supported_dtypes: tensorflow: function_supported_dtypes: invalid literal for int() with base 10: '0-dev20221117'

2022-11-30 18:37 UTC, ndurumo254 commented
> hello @fspyridakos. am getting this error when i ran it from my local machine. how should i go about it.
> 
> E ivy.exceptions.IvyError: tensorflow: function_supported_devices_and_dtypes: tensorflow: function_supported_dtypes: tensorflow: function_supported_dtypes: invalid literal for int() with base 10: '0-dev20221117'

am also facing lint errors from other peoples contributions. is it advisable for me to do any changes on those files?

2022-12-01 09:28 UTC, fspyridakos requested changes
I've requested a change in a line of code that should make your function run. Otherwise, this PR includes changes to many files you shouldn't be changing, like `test_trigonometric_functions` and `test_array_contents`, please make sure you only have `name_space_functions` and `test_jax_numpy_namespace_functions` showing up in the "Files changed" tab. Additonally it seems you have added extra indentation in many function definitions, please revert these changes too.

2022-12-01 09:28 UTC, fspyridakos commented on ivy/functional/frontends/jax/numpy/name_space_functions.py
> +    return ivy.degrees(x)
There is no `ivy.degrees` function, please use `ivy.rad2deg`

2022-12-01 09:33 UTC, fspyridakos commented
> hello @fspyridakos. am getting this error when i ran it from my local machine. how should i go about it.
> 
> E ivy.exceptions.IvyError: tensorflow: function_supported_devices_and_dtypes: tensorflow: function_supported_dtypes: tensorflow: function_supported_dtypes: invalid literal for int() with base 10: '0-dev20221117'

Where do you get this error? When running the test? Also about the lint errors, you do not have to fix any lint errors in any files apart from the ones you're modifying. If you would like automatic lint checking, please check out the "pre-commit" section in our setting up giude: https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit

2022-12-01 11:57 UTC, fspyridakos requested changes
I pointed out another change you should make. Also my previous comments have not been adressed, please go over them again before requesting another review. Thanks!

2022-12-01 11:57 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_namespace_functions.py
> +def test_jax_numpy_deg2rad(
`fn_tree` and the test name should refer to the function as jax.numpy.degrees, as that is the function name in the jax.numpy frontend.

2022-12-02 20:54 UTC, ndurumo254 commented
@fspyridakos . am getting challanges in reverting the changes. i have done git reset --hard-- several times but although the branch is back dated the changes are not reverted.

2022-12-05 11:21 UTC, fspyridakos commented
First of all, the function you're trying to implement is fine so good job! Now as to reverting changes, you could remove unwanted files from the PR as described here: https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request.

Or you could just go to the Files changed, tab and manually reset changes by copy-pasting the original into your files. You could also do this on a whole-file scale by going to the files with changes and copy-pasting the whole original file into it (deleting your local file beforehand), then adding your wanted changes.

2022-12-05 19:02 UTC, closed without merging