soft_margin_loss in pytorch frontend
unifyai/ivy pull request #7787
Opened 2022-12-11 05:50 UTC by satani99

2022-12-11 05:51 UTC, satani99 commented
Close #7592

2022-12-12 05:00 UTC, hirwa-nshuti requested changes
Hey @satani99 
Thanks for contributing to Ivy😊
Everything looks good just one small change is needed. check the comments

Best🙂

2022-12-12 05:00 UTC, hirwa-nshuti commented on ivy/functional/frontends/torch/nn/functional/loss_functions.py
> +def soft_margin_loss(
The tests will fail for `float16` we need to specify unsupported dtypes
```suggestion
@with_unsupported_dtypes({"1.11.0 and below": ("float16", "bfloat16")}, "torch")
def soft_margin_loss(
```

2022-12-13 03:55 UTC, hirwa-nshuti approved these changes
LGTM🙂
Thanks for contributing

2022-12-13 03:55 UTC, merged