Numpy cov 7651
unifyai/ivy pull request #7834
Opened 2022-12-12 10:49 UTC by picqushini

Numpy frontend issue [cov]#7651

2022-12-15 17:47 UTC, simonetgordon requested changes

2022-12-15 17:47 UTC, simonetgordon commented on ivy/functional/frontends/numpy/statistics/cov.py
> +@to_ivy_arrays_and_back
Move the  test function to the `ivy_tests/test_ivy/test_frontends/test_numpy/test_statistics/test_averages_and_variances.py` file and the function definition to the mirrored place `frontends/numpy/statistics`

2022-12-15 17:47 UTC, simonetgordon commented on ivy/functional/frontends/numpy/statistics/cov.py
> +Input:
Remove these docstrings

2022-12-16 06:20 UTC, picqushini commented on ivy/functional/frontends/numpy/statistics/cov.py
> +Input:
Ok

2022-12-19 09:28 UTC, closed without merging