Add angle
unifyai/ivy pull request #7861
Opened 2022-12-12 17:20 UTC by xezbeth

2022-12-12 18:18 UTC, xezbeth commented
angle #7809

2022-12-12 21:08 UTC, xezbeth commented
Closes #7809

2022-12-14 16:15 UTC, fspyridakos commented
Hey @xezbeth thanks for your contribution!
Could you please remove the files from the .idea folder from your PR? Those should not be getting merged. Reffer to this thread for an explanation as to how this can be done: https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request

2022-12-14 17:36 UTC, xezbeth commented
> Hey @xezbeth thanks for your contribution! Could you please remove the files from the .idea folder from your PR? Those should not be getting merged. Reffer to this thread for an explanation as to how this can be done: https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request

I reverted the .idea folder. Don't know how these changes where made in the first place though.

2022-12-15 09:41 UTC, xezbeth reviewed
update tensorflow

2022-12-15 12:19 UTC, fspyridakos requested changes
Hey, please go over the changes I requested and ask another review when done. Also you've introduced a lot of lint changes, mostly in the form of additional indentation, in `tensorflow/experimental/elementwise.py` you can see all of those in the `Files changed` tab, please revert those changes as well.

2022-12-15 12:19 UTC, fspyridakos commented on ivy/functional/backends/tensorflow/experimental/elementwise.py
> +    return tf.math.angle(input, name=None)
I don't see the `deg` parameter being handled here, you should have a check if `deg` is True then multiply the function output by 180/pi.

2022-12-15 12:19 UTC, fspyridakos commented on ivy/functional/backends/torch/experimental/elementwise.py
> +    return torch.angle(input, out=out)
`deg` is also not handled here, handle it the same way as I described for tf.

2022-12-15 12:19 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_elementwise.py
> +        deg=False,
Please pass `deg=deg` once you fix the comments I made for torch and tf, that should make it work

2022-12-15 18:57 UTC, fspyridakos commented
Did some lint fixing and now it's ready to merge! Thanks again for your contribution

2022-12-15 18:59 UTC, merged

2022-12-15 19:02 UTC, xezbeth commented
> Did some lint fixing and now it's ready to merge! Thanks again for your contribution

Thank you very much.