Addition of torch instance method torch.argwhere
unifyai/ivy pull request #7899
Opened 2022-12-13 14:08 UTC by p-mishra1

solves the issue #7859

2022-12-14 06:04 UTC, hirwa-nshuti requested changes
Hi @p-mishra1 
Thanks for contributing to Ivy😊

- Everything looks good except that the function `argwhere` is not implemented on the torch frontend so we can't call it from there. And as you can see that it is still in [the open task for contribution](https://github.com/unifyai/ivy/issues/9).

We can merge this PR once this function is implemented on the torch frontend.
Feel free to take on another open task or work on implementing this function 🙂

Best!

2022-12-14 16:15 UTC, p-mishra1 commented on ivy/functional/frontends/torch/tensor.py
> +        return torch_frontend.argwhere(self._ivy_array)
Thanks @hirwa-nshuti for pointing it out i was confused why the test case was failing, 
we have to add argwhere in [this](https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/torch/comparison_ops.py) frontend function right ?

2022-12-14 16:21 UTC, hirwa-nshuti commented on ivy/functional/frontends/torch/tensor.py
> +        return torch_frontend.argwhere(self._ivy_array)
No it has to be in this [file](https://github.com/unifyai/ivy/blob/master/ivy/functional/frontends/torch/indexing_slicing_joining_mutating_ops.py)

2022-12-19 16:22 UTC, hirwa-nshuti commented
Hey good job so far, but we still need to write unit tests for the `argwhere` function.
Then I'll get the PR merged

2022-12-21 12:31 UTC, p-mishra1 commented
> Hey good job so far, but we still need to write unit tests for the `argwhere` function. Then I'll get the PR merged

@hirwa-nshuti can you give it a look

2022-12-21 12:46 UTC, hirwa-nshuti approved these changes
LGTM!
Thanks for contribution🙂

2022-12-21 12:58 UTC, merged