Parallel Operator
unifyai/ivy pull request #8013
Opened 2022-12-15 10:16 UTC by suwilanjichisanga

I added Parallel Operators

2022-12-23 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2022-12-24 00:13 UTC, ZoeCD commented
Hi! There are some branch conflicts. Could you please update your fork to resolve these conflicts? Also, each PR should be linked to an issue (or multiple issues) according to the functions being worked on. You can read more about the steps to contribute to Ivy [here](https://lets-unify.ai/ivy/contributing/open_tasks.html#frontend-apis) 🙂

2022-12-24 15:49 UTC, suwilanjichisanga commented
@ZoeCD can you only look at Parallel Operators to ivy/functional/frontends/jax/lax/linalg.py, an issue has been added. The other changes were my first attempt which were not linked to an issue. If you may review Parallel Operators to ivy/functional/frontends/jax/lax/linalg.py

2022-12-28 16:34 UTC, ZoeCD commented
I saw the closed issue. You need to create an issue per function worked on. For example, one titled `all-to-all` and another one titled `psum`. Then link those issues to this PR so they can be automatically closed once the PR is resolved. Also, each function needs to have a test function. If you prefer, [here](https://www.youtube.com/playlist?list=PLwNuX3xB_tv8Gf2sELkXSqCCWcUq-AbrG) is our contribution youtube series that explains the steps to contribute to the codebase. Let me know if you have any questions! 🙂

2022-12-30 13:13 UTC, suwilanjichisanga commented
Hi @ZoeCD I created the issues, but I am unable to access development. I want to link the pull request to the issues.

2022-12-30 17:45 UTC, ZoeCD commented
Please comment the link to the issues, and I'll add them in the development section

2022-12-30 17:55 UTC, suwilanjichisanga commented
I already commented the links @ZoeCD

2022-12-30 17:57 UTC, suwilanjichisanga commented
alright this is the link to the issues https://github.com/unifyai/ivy/issues/9246

2023-01-04 16:54 UTC, ZoeCD commented
Issues linked. Please add the corresponding tests and fix the merge conflicts. Let me know if you have any questions 🙂
Happy new year!

2023-01-06 08:24 UTC, suwilanjichisanga commented
@ZoeCD how can I add the corresponding tests?

2023-01-11 14:25 UTC, ZoeCD requested changes

2023-01-11 14:25 UTC, ZoeCD commented on ivy/functional/frontends/tensorflow/math.py
> +def argmax(input, axis, output_type=None):
I think this is a merge mistake that went unnoticed

2023-01-11 14:25 UTC, ZoeCD commented on ivy/functional/frontends/tensorflow/math.py
> +def asinh(x):
Question. Were all these formatting changes made by the lint pre-commit?

2023-01-11 14:25 UTC, ZoeCD commented on ivy/functional/frontends/tensorflow/math.py
> +def argmin(input, axis=None, output_type="int64"):
Another merge error

2023-01-11 14:25 UTC, ZoeCD commented on ivy/functional/frontends/jax/lax/linalg.py
> +    def all_gather(x, axis_name, *, axis_index_groups=None, axis=0, tiled=False):
All functions must to have a test. You can see plenty of examples under the folder `ivy_tests`. As you can see there, all our tests are organized by categories. For example, for the jax linalg functions, the tests must be in this file [ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_linalg.py](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_jax/test_jax_lax_linalg.py)

2023-01-11 14:25 UTC, ZoeCD commented on ivy/functional/frontends/jax/lax/linalg.py
> +    def all_gather(x, axis_name, *, axis_index_groups=None, axis=0, tiled=False):
I recommend you to read our [contribution guide](https://lets-unify.ai/ivy/contributing/open_tasks.html#frontend-apis). You will find step-by-step instructions on how to contribute to the codebase. You can also find function and tests examples 🙂

2023-02-26 14:16 UTC, closed without merging