Concatenate
unifyai/ivy pull request #8813
Opened 2022-12-17 12:39 UTC by optimusprime009

2022-12-17 12:40 UTC, optimusprime009 commented
why my merging is blocked

2022-12-19 17:42 UTC, jkeane508 requested changes
Hey,

For this PR you should only have changes to files for the relevant task. There seems to be changes in `ivy_tests/test_array_api`. These would need to be removed :)

Thanks!

2022-12-19 18:44 UTC, optimusprime009 commented
so are we do not need to write the test for the front end function?

2022-12-19 18:49 UTC, optimusprime009 commented
> 

sorry they were committed by codespace by accident

2022-12-23 04:19 UTC, optimusprime009 commented
can you connect the issue #4183 to this pull request

2022-12-23 05:29 UTC, optimusprime009 commented
ivy/functional/frontends/torch/linalg.py:10:89: E501 line too long (92 > 88 characters) what to do about this

2022-12-23 05:42 UTC, optimusprime009 commented
#4183

2022-12-23 11:10 UTC, jkeane508 commented
> ivy/functional/frontends/torch/linalg.py:10:89: E501 line too long (92 > 88 characters) what to do about this ?

This is a lint error, Ivy has formatting rules for code, you can install a pre-commit hook to prevent these issues in the future -https://lets-unify.ai/ivy/contributing/setting_up.html#pre-commit

2022-12-23 11:18 UTC, jkeane508 requested changes
Hi, in this PR there can't be any changes to files not relevant to the task. This PR deletes the array API folder and makes changes to the .gitignore, we can't merge until these are resolved.

Moreover, we should limit comments where possible. For imports, we should split them into global and local imports.

Thanks

2022-12-23 11:18 UTC, jkeane508 commented on .gitmodules
We cannot accept PRs with changes to the .gitignore file

2022-12-23 11:18 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_layers.py
> +# from pydoc import Helper
this can be removed

2022-12-23 11:18 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_layers.py
> +# from .test_raw_ops import _arrays_idx_n_dtypes
This can be removed

2022-12-23 11:18 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_layers.py
> +# layer_concatenate
This can just be `# concatenate`

2022-12-23 11:18 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_layers.py
> +    # xs_n_input_dtypes_n_unique_idx=_arrays_idx_n_dtypes(),
this can be removed

2022-12-23 11:18 UTC, jkeane508 commented on ivy_tests/test_ivy/test_frontends/test_tensorflow/test_layers.py
> +    # as_variable=Helper.array_bools(),
this can also be removed

2022-12-23 11:18 UTC, jkeane508 commented on ivy/functional/frontends/tensorflow/keras/layers.py
> +import ivy
we should add `# global` above this line

2022-12-23 12:44 UTC, optimusprime009 commented
> 

how we are going to do that?

2022-12-23 12:58 UTC, optimusprime009 commented
> Hi, in this PR there can't be any changes to files not relevant to the task. This PR deletes the array API folder and makes changes to the .gitignore, we can't merge until these are resolved.
> 
> Moreover, we should limit comments where possible. For imports, we should split them into global and local imports.
> 
> Thanks

How are we gonna work on that?

2022-12-23 13:50 UTC, jkeane508 commented
> why my merging is blocked ?

You don't have permission to merge PRs to the master branch of Ivy. The reviewer will merge the PR when its accepted :)

2022-12-23 13:52 UTC, jkeane508 commented
> > Hi, in this PR there can't be any changes to files not relevant to the task. This PR deletes the array API folder and makes changes to the .gitignore, we can't merge until these are resolved.
> > Moreover, we should limit comments where possible. For imports, we should split them into global and local imports.
> > Thanks
> 
> How are we gonna work on that? you told me to remove the test_Array_api folder.

Hey,

I didn't ask you to remove the folder, I asked you to remove changes to the folder. In your original commit, you had made changes to the code in the array API folder which would have made changes to the master branch. In general, there should only be changes made to the files relevant to the task you are working on :)

Hope this helps

2022-12-23 14:00 UTC, optimusprime009 commented
but I didn't commit those changes on the test array API it is automatically done by codespace. Do you know what I should do next?

2022-12-23 14:04 UTC, jkeane508 commented
> but I didn't commit those changes on the test array API it is automatically done by codespace. Do you know what I should do next?

Hi,

In this case, I would rebase your local branch with the Ivy Master branch, such that your local base is identical to the master branch. I would then make implement the function and test locally, and commit only the relevant changes to the task not all changes on the branch :)

2022-12-24 07:33 UTC, optimusprime009 commented
what should I do now? regarding the files, should I create a new pull request or delete the entire commit of the branch?

2022-12-30 15:13 UTC, jkeane508 commented
> what should I do now? regarding the files, should I create a new pull request or delete the entire commit of the branch?

You could probably just rebase your branch to the master branch of Ivy :)

2023-01-08 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-01-15 06:25 UTC, closed without merging

2023-01-15 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.