uniform #9002
unifyai/ivy pull request #9062
Opened 2022-12-23 22:28 UTC by Namangarg110

Close #9002

2022-12-30 15:11 UTC, jkeane508 requested changes
Hi,

Thanks for submitting a PR :)

As part of this task, you also need to write a unit test in the relevant file.

Thanks.

2022-12-30 20:35 UTC, Namangarg110 commented
> Hi,
> 
> Thanks for submitting a PR :)
> 
> As part of this task, you also need to write a unit test in the relevant file.
> 
> Thanks.

Hey @jkeane508,
I have added the unit test. However, it may require some improvements. Can you please review it and suggest changes??

2022-12-31 15:25 UTC, jkeane508 requested changes
Hey,

Thanks for submitting this PR,

Just a few questions about your implementation :)

2023-01-27 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-02-03 06:25 UTC, closed without merging

2023-02-03 06:25 UTC, ivy-seed commented
This PR has been closed because it has been marked as stale for more than 7 days with no activity.

2023-02-03 07:18 UTC, Namangarg110 commented on ivy/functional/frontends/tensorflow/random.py
> +@with_supported_dtypes({"2.9.0 and below": ("float16", "bfloat16",
Hey sorry @jkeane508 ,
I missed your comment,

Actually, this function has specific datatypes that are unsupported, that is why I used 2 decorators i.e. @with_supported_dtypes and @with_unsupported_dtypes. Please let me know if it is wrong to do so 

Thanks & Best Regards,
Naman Garg