feat(PyTorch Frontend): add poisson random sampling
unifyai/ivy pull request #9131
Opened 2022-12-27 06:55 UTC by DecFox

This diff introduces a new poisson random sampling to pytorch frontend along with the the corresponding backend implementations for `ivy.poisson`
Closes #9070

2022-12-28 22:14 UTC, fspyridakos requested changes
Many thanks for your contribution!
Looks pretty good, please add the extra check in the test as I describe and please migrate the ivy implementaiton of `poisson` into the experimental folders.

2022-12-29 17:14 UTC, DecFox commented on ivy_tests/test_ivy/test_functional/test_core/test_random.py
> +            seed=seed,
> No check for the shape parameter

Done here: https://github.com/unifyai/ivy/pull/9131/files#diff-03bd8031d342c7ccad25a959d741e11f6adb13688e09a6a512afbc291589adc5R203

2022-12-29 17:17 UTC, DecFox commented
Thank you for the review! I have made the requested changes. Feel free to take a look and let me know how if further changes are required.

2023-01-03 17:58 UTC, fspyridakos commented
Hey, thanks for the changes, the test is failing in a way I don't understand. I've asked from help from another member of the team who know more. I'll give another review once I hear back!

2023-01-04 10:25 UTC, fspyridakos requested changes
One small comment which should hopefully make the test pass

2023-01-04 10:25 UTC, fspyridakos commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_random.py
> +)
Please add a test_gradients=st.just(False) in the handle_test block as the function shouldn't support gradients. Even though the message only corresponds to the tensorflow function not supporting gradients, given that this is a random generation related function and it's not unified yet, we shouldn't test for gradients for any backend. Finally, just add a ToDo comment to enable gradient tests for this function with the other backends once random generation is unified

2023-01-04 13:06 UTC, DecFox commented
Thank you! I have made the requested changes (and added the `TODO` as requested). I can see the CI still fails although tests run successfully for me locally. (atleast those corresponding to `ivy.poisson`).

2023-01-04 17:11 UTC, fspyridakos commented
Looks good now! The failing CI tests aren't related to the poisson function you added. Many thanks for your contribution!

2023-01-04 17:12 UTC, merged