adding fmod api for numpy first try
unifyai/ivy pull request #9222
Opened 2022-12-29 21:56 UTC by EthanWangtl

I'm not seeing any test for this one. Please let me know what kinds of changes I should make.

2022-12-30 05:15 UTC, hirwa-nshuti requested changes
Hi @EthanWangtl 
Thanks for contributing to ivy😊
Would you please edit the first comment with the issue to be linked with this PR by using `close #issue_number`
For the required changes do check the comments.
Also, you will need to write down the unit test for the implemented function which should be placed in [this file](https://github.com/unifyai/ivy/blob/master/ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_arithmetic_operations.py).

Thanks🙂

2022-12-30 05:15 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +def fmod(
To handle dtype and casting we have a decorator for that no need for these if statements.
You will need to add these decorators to the function
```suggestion
@handle_numpy_dtype
@to_ivy_arrays_and_back
@handle_numpy_casting
@from_zero_dim_arrays_to_scalar
def fmod(
```

2022-12-31 01:08 UTC, EthanWangtl commented
I updated some, but no need to review, the unit tests didn't passed.

2022-12-31 01:32 UTC, EthanWangtl commented
Hi there, thank you for the feedback! I've added the decorations lines and unit test, together with some modifications of the fmod function to make sure the unit tests can pass. Let me know what changes I need to make further.

2022-12-31 01:47 UTC, EthanWangtl commented
Sorry, after I ran the unit test several times more. some tests didn't pass, I will try to figure that out and let you know asap.

2023-01-02 16:10 UTC, hirwa-nshuti requested changes
Hi there🙌
Happy new year🎉
The current progress is nice and you need to check a few changes required in the comments.
Best🙂

2023-01-02 16:10 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +    ret = ivy.remainder(x1, x2, out=out)
We have `ivy.fmod` implemented on our experimental API if you use it the tests should pass.
```suggestion
    ret = ivy.fmod(x1, x2, out=out)
```

2023-01-02 16:10 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_arithmetic_operations.py
> +    input_dtypes, xs, casting, dtype = dtypes_values_casting
Need to handle inputs to be different from zero to avoid zero division error

2023-01-02 18:56 UTC, EthanWangtl commented
Happy New Year! Thank you for the suggestions, after modifying the required files, when I try to run the test locally in Pycharm with docker, it encounters this error when it comes to the TensorFlow backend checks: Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory. Do you think this is a problem on my device with Cuda? or does my computer have a problem communicating with the docker image? Thanks!!!

2023-01-03 03:26 UTC, hirwa-nshuti requested changes
With these few changes, the tests will pass and just ignore the TensorFlow backend error the function seems to be buggy there I'll look into it and fix it.
Make these changes and I'll go ahead merging your PR😊

Thanks for contributing🎉

2023-01-03 03:26 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/mathematical_functions/arithmetic_operations.py
> +    ret = ivy.remainder(x1, x2, out=out)
```suggestion
    ret = ivy.fmod(x1, x2, out=out)
```

2023-01-03 03:26 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_arithmetic_operations.py
> +                min_value=0,
We don't need to specify minimum value
```suggestion

```

2023-01-03 03:26 UTC, hirwa-nshuti commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_mathematical_functions/test_arithmetic_operations.py
> +                exclude_min=True,
```suggestion
```

2023-01-03 04:42 UTC, EthanWangtl commented
Ok! all changes are made. Thank you and glad to work with you!
Best!

2023-01-03 05:10 UTC, hirwa-nshuti approved these changes
Looks good now😊
Thanks for contributing🤗

2023-01-03 05:12 UTC, merged