Create sequence_empty
unifyai/ivy pull request #9226
Opened 2022-12-30 04:26 UTC by Fayad-Alman

- Creates an empty tensor sequence 
- Input: shape, dtype (optional)
- Output: self.tensor

2022-12-30 04:47 UTC, Fayad-Alman commented
Issue:
https://github.com/unifyai/ivy/issues/9158

2023-01-05 20:44 UTC, Fayad-Alman commented
Hi @ZoeCD 
Just a friendly ping as a reminder to check the changes whenever you're ready :)

2023-01-11 15:22 UTC, ZoeCD requested changes

2023-01-11 15:22 UTC, ZoeCD commented on ivy/functional/backends/onnx_func/sequence_empty
> +class SequenceEmpty:
Hi! Sorry for the lack of proper instructions for this task. What we need is the backend implementation for `SequenceEmpty`. We just want to add some basic functions that ONNX supports. You can follow [these instructions](https://lets-unify.ai/ivy/contributing/open_tasks.html#ivy-experimental-api) to see what we expect from the PR. Thank you for your interest in helping Ivy! 😊

2023-01-19 06:25 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-01-19 07:47 UTC, Aarsh2001 commented
Hi @Fayad-Alman, apologies for the last moment changes but these functions are supposed to be added to the Experimental API. Kindly add it in the respective folders, and re-request a review thanks.

2023-01-22 01:17 UTC, Fayad-Alman commented
@Aarsh2001 Noted! Thanks!

2023-01-22 02:59 UTC, Fayad-Alman commented
#9915

2023-01-24 17:55 UTC, Fayad-Alman commented
Hi @ZoeCD 
I created a new PR for the proper changes. Mind taking a look?
#9973

2023-01-26 17:23 UTC, ZoeCD commented
I left a comment in the new PR. I'm closing this one

2023-01-26 17:24 UTC, closed without merging