Reformating zero_pad
unifyai/ivy pull request #9354
Opened 2023-01-03 18:52 UTC by ioannispol

2023-01-05 12:32 UTC, nassimberrada commented
Hi @ioannispol, thank you for your contribution ! The examples are great and you're in the right direction, but i've left some comments above. Could you give those a look as well as correct some lint errors as shown in the `lint / check-formatting` test ? Also, i noticed your PR makes some changes to some files in the .idea folder, namely ivy.iml and misc.xml, could you revert those as they are not needed ? Thanks !

2023-01-05 20:12 UTC, ioannispol reviewed
Hi @nassimberrada, thank you for your review. I've corrected the lint errors and revered the changes in the .idea folder (ivy.iml and misc.xml files). Please let me know if I need to make any further changes. 
Thank you!

2023-01-06 10:17 UTC, nassimberrada requested changes

2023-01-06 10:17 UTC, nassimberrada commented on ivy/array/manipulation.py
> +        Padded array of rank equal to x with shape increased according to pad_width.
Could you add an indent just like for other variables above ?

2023-01-06 10:19 UTC, nassimberrada commented
Hi @ioannispol thanks for fixing the lint errors, i think the changes to the ivy.iml files persist though. I made some comments yesterday for changes in the docs but didn't validate them somehow apologies, could you address those ? Thanks !

2023-01-06 16:32 UTC, ioannispol commented
Hi @nassimberrada, thanks again for your comments. This time I think I have done them all and tried not to include in my commit the ivy.iml and misc.xml files (I think that PyCharm automatically changes these files, and I mistakenly I committed all the changed files). Please let me know if everything is ok.
Thank you!

2023-01-07 10:32 UTC, nassimberrada requested changes

2023-01-07 10:32 UTC, nassimberrada commented on ivy/container/manipulation.py
> +        >>> y = ivy.zero_pad(x, pad_width = [[2, 3]])
This should be written like the example in array instance method, i.e x.zero_pad(pad_width=....)

2023-01-07 10:35 UTC, nassimberrada commented
Hi @ioannispol, i think this is almost done, could you just make the last requested change in the container instance method example ? Also, i think your commit still makes changes to the ivy.iml file, could you double check that ? Thanks !

2023-01-07 11:15 UTC, ioannispol commented
Hi @nassimberrada, I've corrected the zero_pad example in the container/manipulation.py file. I also doubled check to not commit the files in the .idea folder and it appears that the only file in my fork is the container/manipulation.py. 
Thank you!

2023-01-07 18:52 UTC, nassimberrada commented
@ioannispol there were still some changes being made to the ivy.iml but a member of our team rectified that, you may want to keep in mind these unintentional changed in future PRs eventually. In any case, this looks good to me now, i'll be merging, thank you for your contribution !

2023-01-07 18:52 UTC, merged

2023-01-07 19:22 UTC, ioannispol commented
Hi @nassimberrada, thank you again for your comments and your help. I'll keep in mind for similar unintentional changes in files such as the ivy.iml. 
Thank you!