Functional multi dot
unifyai/ivy pull request #9436
Opened 2023-01-06 06:28 UTC by danielmunioz

2023-01-06 06:30 UTC, danielmunioz commented
close #9325

2023-01-06 07:07 UTC, danielmunioz commented
Hi! sorry, I've been having some issues running the tests for this function, the test is only able to run if you uncomment the `test_flags.instance_method = False` flag otherwise the test raises the error:

`ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py:345: in test_multi_dot
    helpers.test_function(`
`ivy_tests/test_ivy/helpers/function_testing.py:249: in test_function
    ivy.prune_nest_at_index(args, instance_idx)`
`args = ([(ivy.array([[0, 0],
       [0, 0]]), ivy.array([[0, 0],
       [0, 0]]), ivy.array([[0, 0],
       [0, 0]]))], [0, 0]), kwargs = {}`

And the big one:
`ivy.exceptions.IvyBackendException: torch: prune_nest_at_index: torch: prune_nest_at_index: 'tuple' object doesn't support item deletion`

I'm not sure exactly why this happens, my guessing is that due to the nature of the inputs, the testing function somehow breaks when trying to test instance methods

2023-01-06 07:30 UTC, danielmunioz commented
It's also worth mentioning that due to the nature of the floating point arithmetic, there may be a bit of a difference in the results when running different backends, I managed to adjusts the rtol and atol test values for this, but the difference can sometimes be noticeable, as explained on [this github issue](https://github.com/numpy/numpy/issues/22953)

2023-01-06 07:35 UTC, danielmunioz commented
It's worth nothing that due to the nature of floating point arithmetic, there may be a bit of a difference in the results when using different backends, I managed to adjust the atol and rtol test values for this, but the difference can sometimes be a bit noticeable

2023-01-11 15:01 UTC, ZoeCD requested changes

2023-01-11 15:01 UTC, ZoeCD commented on ivy_tests/test_ivy/test_functional/test_experimental/test_core/test_linalg.py
> +    # test_flags.instance_method = False
If setting the instance method flag to False is a quick fix, the error may be in the array instance method or in the container one. Have you tried to use the debugger to find where the exception is exactly happening? 🤔

2023-02-26 14:16 UTC, closed without merging