Diag indices
unifyai/ivy pull request #9456
Opened 2023-01-06 15:08 UTC by seancraven

Close #9455

2023-01-06 15:10 UTC, seancraven commented
This is not on the to-do list, however, a similar function diag_indices_from is. Their implementation is complimentary.

2023-01-16 16:53 UTC, hirwa-nshuti requested changes
Hey @seancraven 
Thanks for contributing to ivy😊
Also, thank you for bringing this function to our attention. Below are a few changes and your PR will get merged🙂

Thanks

2023-01-16 16:53 UTC, hirwa-nshuti commented on ivy/functional/frontends/numpy/indexing_routines/indexing_like_operations.py
> +from ivy.functional.frontends.numpy.func_wrapper import outputs_to_numpy_arrays
This can be imported along with the wrapper above

2023-01-18 09:39 UTC, seancraven commented
Thanks very much for the help!

2023-01-18 14:10 UTC, hirwa-nshuti approved these changes
Looks good to me🙂

Thanks for contributing

2023-01-18 15:38 UTC, hirwa-nshuti requested changes
Fix the conflicts and I'll get this merged very soon

2023-01-18 16:23 UTC, hirwa-nshuti approved these changes
Looks good now😊

2023-01-18 16:25 UTC, merged