Separable conv2d
unifyai/ivy pull request #9458
Opened 2023-01-06 19:08 UTC by anurag629

2023-01-06 19:10 UTC, anurag629 commented
#8522

2023-01-15 15:42 UTC, Aarsh2001 requested changes

2023-01-15 15:42 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +    fn_tree="functional.experimental.separable_conv2d",
you are passing the wrong function tree here, and so the test fails at collection time. It should be `functional.ivy.experimental.separable_conv2d`.

2023-01-17 16:08 UTC, anurag629 commented
@Aarsh2001 How to resolve this error? I have not passed `kernel` variable then why this error?
![Screenshot from 2023-01-17 21-34-58](https://user-images.githubusercontent.com/78868769/212950951-74431a7a-ea4c-4f88-a895-3315226de52e.png)

2023-01-19 06:29 UTC, Aarsh2001 commented
Hey @anurag629, here are the following errors i see with the testing setup-:

2023-01-19 06:32 UTC, Aarsh2001 requested changes

2023-01-19 06:32 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +    x_k_s_p=helpers.arrays_for_pooling(min_dims=2, max_dims=2, min_side=1, max_side=4),
Inside `arrays_for_pooling`, you are not generating the appropriate `array_dims` and so the `kernel` is not initialized at all. You are passing `max_dims = 2`. I suggest you look at the helper function inside the file, you'll get an idea.

2023-01-19 06:32 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +    dtype, x, stride, pad = x_k_s_p
You are not unpacking `kernel` here.

2023-01-19 06:32 UTC, Aarsh2001 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +        strides=stride,
You haven't passed `kernel` variable here as well.

2023-01-19 06:32 UTC, Aarsh2001 commented on ivy/functional/ivy/experimental/layers.py
> +    pointwise_filter: Union[int, Tuple[int], Tuple[int, int, int]],
As you can see the function requires two filters, but at test time you are generating only one kernel. You should be generating two kernels/filters.

2023-02-05 17:41 UTC, Aarsh2001 commented
The tests are still failing, kindly have a look at the logs.

2023-02-26 14:16 UTC, closed without merging