Adding "to_ivy_array" flag to copy_array
unifyai/ivy pull request #9465
Opened 2023-01-07 07:12 UTC by danielmunioz

This allows for copy_array to return native arrays if desired.

2023-01-11 15:05 UTC, ZoeCD requested changes

2023-01-11 15:05 UTC, ZoeCD commented on ivy/functional/ivy/creation.py
> +    x: Union[ivy.Array, ivy.NativeArray],
Could you please update the copy_array_test to test this new functionality? 😊

2023-01-13 04:44 UTC, danielmunioz commented
Done! I also talked with Ved about how to more safely achieve this and I made some changes accordingly!

2023-01-18 17:33 UTC, ZoeCD approved these changes

2023-01-18 17:34 UTC, ZoeCD commented
@danielmunioz LGTM!

2023-01-18 17:34 UTC, merged