Reformat creation-meshgrid
unifyai/ivy pull request #9487
Opened 2023-01-08 02:23 UTC by cosmicthermo

2023-01-08 02:27 UTC, cosmicthermo commented
Close #9473

2023-01-08 07:45 UTC, CatB1t requested changes
Hello @cosmicthermo! thanks for your great work, just a few points to be addressed, also could you please revert the changes to the `.idea` folder? thanks!

2023-01-08 07:45 UTC, CatB1t commented on ivy/functional/ivy/creation.py
>      This function conforms to the `Array API Standard
We can actually delete this, it's not necessary to have them anymore.

2023-01-08 07:45 UTC, CatB1t commented on ivy/functional/ivy/creation.py
> -    With :class:`ivy.NativeArray` input:
Why this has been removed? I think we can keep it 😄

2023-01-08 07:45 UTC, CatB1t commented on ivy/container/creation.py
> +from typing import Optional, Union, List, Tuple, Dict, Sequence, Any, Type
`Any, Type` doesn't seem to be used after importing here, we should undo this.

2023-01-17 15:46 UTC, CatB1t commented
> Thank you so much for the review! This is actually my first PR! I am happy to finish this work and get everything right. One question about the out variable in the docstring of this function. They don't have this variable in the previous version. And in this case the output is more than one variables, which corresponds to the input variables. Do we need to add this out variable in this case? Thanks!

Hello @cosmicthermo, I'm not sure I understand, can you elaborate more?

2023-01-17 15:51 UTC, CatB1t requested changes

2023-01-17 15:51 UTC, CatB1t commented on ivy/functional/ivy/creation.py
> +    >>> xv = ivy.zeros((3, 2))
These are getting overwritten by the function return, we shouldn't have them.

2023-01-17 15:51 UTC, CatB1t commented on ivy/container/creation.py
> +        }
Could you add more examples including other parameters, simple ones will be sufficient 😄

2023-02-26 14:16 UTC, closed without merging