implimenting isfinite function
unifyai/ivy pull request #9517
Opened 2023-01-09 05:36 UTC by ndurumo254

2023-01-09 10:26 UTC, nassimberrada requested changes

2023-01-09 10:26 UTC, nassimberrada commented on ivy/functional/frontends/jax/numpy/logic.py
> +
You may need to add the @to_ivy_arrays_and_back decorator

2023-01-09 10:26 UTC, nassimberrada commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_logic.py
> +
The hypothesis part of the tests is missing, you can take a look at other functions tests (or even the tests for isfinite as implemented in torch for e.g) to get a better idea of the general structure, it's the part that starts with the @handle_frontend_test decorator

2023-01-09 10:34 UTC, nassimberrada commented
Hi @ndurumo254, thanks for your contribution ! You're in the right direction but some things should be changed, i've made some comments above could you try addressing those ?

Also, i see you've made changes to the numpy backend function as well as the tests for other frontend functions, those are not necessary to implement this particular function so maybe you could revert them back, just to make your PR's purpose clear, of course you are free to make unrelated corrections other PRs. 

Finally, could you reserve this function for yourself by creating an issue, commenting it in the corresponding To-Do list and linking it to this PR ? You can find more details about this [here](https://lets-unify.ai/ivy/contributing/the_basics.html#the-basics).

Let me know when you feel your PR is ready and you've made sure the tests pass so i can review it again, thanks !

2023-01-09 12:54 UTC, ndurumo254 commented
> Hi @ndurumo254, thanks for your contribution ! You're in the right direction but some things should be changed, i've made some comments above could you try addressing those ?
> 
> Also, i see you've made changes to the numpy backend function as well as the tests for other frontend functions, those are not necessary to implement this particular function so maybe you could revert them back, just to make your PR's purpose clear, of course you are free to make unrelated corrections other PRs.
> 
> Finally, could you reserve this function for yourself by creating an issue, commenting it in the corresponding To-Do list and linking it to this PR ? You can find more details about this [here](https://lets-unify.ai/ivy/contributing/the_basics.html#the-basics).
> 
> Let me know when you feel your PR is ready and you've made sure the tests pass so i can review it again, thanks !

thanks for your response @nassimberrada . i have made changes to the tests. you can review it.

2023-01-10 18:24 UTC, nassimberrada requested changes

2023-01-10 18:24 UTC, nassimberrada commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_logic.py
> +        input=input[0],
This should be `x=x[0]` given that your frontend implementation uses x as variable name

2023-01-10 18:24 UTC, nassimberrada commented on ivy_tests/test_ivy/test_frontends/test_jax/test_jax_numpy_logic.py
> +    input_dtype, input = dtype_and_input
Likewise, this should probably be written as `input_dtype, x = dtype_and_x`

2023-01-10 18:27 UTC, nassimberrada commented
Hi @ndurumo254, thanks for making these changes. I've made some more comments to address some issues with the testing. 

Also i see that the unrelated changes (to the numpy backend function, and to other frontend functions) persist, could you revert those ? Even if your changes are correct it would be best to separate them from this PR so that the purpose of each PR remains clear when debugging.

I suggest you take a look at the [ivy frontend tests](https://lets-unify.ai/ivy/deep_dive/ivy_frontends_tests.html) section of the docs to guide you in implementing the tests for your frontend function. Thanks !

2023-01-11 04:42 UTC, ndurumo254 commented
hello @nassimberrada ,hope this finds you well. in the effoort of reverting the unrelated changes i get rest --hard to previous commit and thereafter the behavior of the tests has changed. was i doing the right thing?

2023-01-11 16:56 UTC, nassimberrada commented
Hi @ndurumo254, it seems this created some issues in your PR, could you try to sync your fork with the master branch by going to your fork, clicking on "Sync fork" then "Update Branch", as shown in the following screenshot ?

![image](https://user-images.githubusercontent.com/112006029/211868096-13c50eda-250c-4389-b0d6-0ba7979b2bfa.png)

2023-01-12 14:37 UTC, nassimberrada commented
Hi, i think some unintended changed were made as you tried to revert your commits, one of our team members fixed those so your PR is back to normal, feel free to try making the changes i suggested again, thanks !

2023-02-07 14:11 UTC, closed without merging