Added instance method __len__ for numpy
unifyai/ivy pull request #9893
Opened 2023-01-20 14:46 UTC by ahmedelgamal0

2023-01-23 09:53 UTC, fspyridakos requested changes
Hey, thanks for your contribution! The function itself is done correctly but the tests needs some work, I added some comments but please check some other tests in the file and follow their example.

2023-01-23 09:53 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +@given(
Use @handle_frontend_method and include the additional parameters like class_tree, init_tree, method_name

2023-01-23 09:53 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +    native_array
Inlude more flags like num_positional_args_method, frontend_method_data, and frontend.

2023-01-23 09:53 UTC, fspyridakos commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +    )
Most of these are either wrongly named or hard coded when flags handled by the test should be passed.

2023-01-23 09:54 UTC, fspyridakos commented
Also please open an issue for this in this ToDo: https://github.com/unifyai/ivy/issues/3607 and link it in this PR as stated in our contribution guide.

2023-01-24 07:00 UTC, ahmedelgamal0 commented
Close #9948

2023-01-24 15:45 UTC, fspyridakos commented
Made a small change to get the test passing. Looks good! Many thanks for your contribution!

2023-01-24 15:46 UTC, merged