hystogram function with opening file
unifyai/ivy pull request #9900
Opened 2023-01-21 07:17 UTC by Tristan1649

Function of hystogram using Tensorflow methods and include creating file.

2023-01-24 05:43 UTC, Tristan1649 commented
> Function of hystogram using Tensorflow methods and include creating file.

2023-01-31 16:35 UTC, hirwa-nshuti requested changes
Hello @Tristan1649 
Thanks for contributing to Ivy😊

Would you explain more about this function you're implementing also if you're getting it hard to understand the contribution I would recommend you first check the [Contribution guide](https://lets-unify.ai/ivy/contributing.html)?

Thanks and happy coding🙂

2023-02-02 07:49 UTC, hirwa-nshuti commented
> > Hello @Tristan1649 Thanks for contributing to Ivy😊
> > Would you explain more about this function you're implementing also if you're getting it hard to understand the contribution I would recommend you first check the [Contribution guide](https://lets-unify.ai/ivy/contributing.html)?
> > Thanks and happy coding🙂
> 
> Hi @hirwa-nshuti Nice to meet you. I need sometime to fixi it because i have some problems wih it. Can we contact in discord?

Sure feel free to text me😊

2023-02-09 10:18 UTC, Tristan1649 commented
> > > Hello @Tristan1649 Thanks for contributing to Ivy😊
> > > Would you explain more about this function you're implementing also if you're getting it hard to understand the contribution I would recommend you first check the [Contribution guide](https://lets-unify.ai/ivy/contributing.html)?
> > > Thanks and happy coding🙂
> > 
> > 
> > Hi @hirwa-nshuti Nice to meet you. I need sometime to fixi it because i have some problems wih it. Can we contact in discord?
> 
> Sure feel free to text me😊

Hi Felix! how are you? About function. I took a function from Tensorflow. Main idea in 1)taking information from file(xls) 2) proceed it 3) visualisation at hystogram graphic.

2023-02-18 06:26 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-02-20 07:39 UTC, Tristan1649 commented
to tenzorlow flow adding nupmy, jax, pytorch

2023-02-24 15:24 UTC, hirwa-nshuti requested changes
Hey @Tristan1649 
Add the function to the functional side of the Experimental API,  also referring to documentation from both numpy and torch you don't need to print anything what is needed is to calculate the histograms of input tensors/arrays

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

https://pytorch.org/docs/stable/generated/torch.histogram.html

Also, Each backend is passed its native arrays/tensors as inputs not `ivy.Array`

Thanks😊

2023-02-24 15:24 UTC, hirwa-nshuti commented on ivy/functional/backends/torch/experimental/statistical.py
> +def histtorch(self: ivy.Array,
For torch backend we should be accepting `torch.Tensor` not `ivy.Array`

2023-02-26 14:16 UTC, closed without merging

2023-03-01 05:51 UTC, Tristan1649 commented
update

2023-03-01 05:53 UTC, Tristan1649 commented
update

2023-03-01 11:28 UTC, Tristan1649 commented
Hi @hirwa-nshuti . I accidiently close issue. Can we contact?