is_complex_torch
unifyai/ivy pull request #9906
Opened 2023-01-21 16:05 UTC by HadeerArafa108

2023-01-21 18:29 UTC, Daniel4078 commented
Can you post the link to the issue that this pull request is dealing with?

2023-01-21 19:01 UTC, HadeerArafa108 commented
https://github.com/unifyai/ivy/issues/7

2023-01-21 19:16 UTC, Daniel4078 commented
well you need to create a issue named "is_complex"and reference in the TODO list issue to mark this task as currently being dealt with, then you link this pull request with the "is_complex" issue you just create, so closing this pull request will also close that issue and update the info on the coorisponding TODO list.

2023-01-23 15:34 UTC, HadeerArafa108 commented
Close #9903

2023-01-23 17:44 UTC, Daniel4078 requested changes
Please try to remove your changes in your commits to the files in the .idea and runConfigurations folder, as the content of these files will be shared with other pull requests and should not be altered in usual situations.

2023-01-23 17:44 UTC, Daniel4078 commented on ivy_tests/test_ivy/test_frontends/test_torch/test_tensor_functions.py
> +    )
please do not forget to keep a blank line at the end of the file

2023-01-23 18:55 UTC, HadeerArafa108 commented
i am so sorry for the trouble I just added the blank line and restored the .idea files

2023-01-25 17:39 UTC, Daniel4078 commented
after you dealt with the last ivy.iml file, I will quick do a final check on your code and then merge it for you. Thank you!

2023-01-25 19:08 UTC, merged

2023-01-25 19:11 UTC, HadeerArafa108 commented
thank you so much for the help